### ISSUE TITLE
Using transition-group with SVG does not give smooth transition

### ISSUE THREAD

**Issue by arthurmcgregor** [vuejs/vue#10043]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/arthurmcgregor/41wz7nLr/24/](https://jsfiddle.net/arthurmcgregor/41wz7nLr/24/)

### Steps to reproduce
Open the JS Fiddle. Click between the home, all, air buttons (with at least 2s pause between each click)

### What is expected?
The circles should move smoothly from one position to another

### What is actually happening?
The circles jump about halfway to their new position, then move smoothly the rest of the way

---
I have tried this with fixed position divs instead of using SVG and the animation is smooth (however, the scaling is terrible so would like to avoid that!)

Although my actual project is runinng v 2.5.22, I assume the JSFiddle is the latest version and the bug is reproduced there.

There are around 250 circles but the same bug happens with fewer circles. eg `v-for="bubble of bubbles.slice(0,10)"`

**Comment by posva** [comment]
You don't need `transition-group` for that, `cx` and `cy` and animatable so you can write:

```css
transition: cx 2s, cy 2s;
```

and remove the `transition-group`: https://jsfiddle.net/posva/b82ngtzx/

The reason it doesn't work is because `transition-group` checks the position of elements (usually moved by layout) and applies a `transform` property. Here, because of the `cx` and `cy` properties they appear somewhere else

**Comment by arthurmcgregor** [comment]
Thank you! That is slick :-D Much appreciated
