### ISSUE TITLE
sometimes child component event won't be fired

### ISSUE THREAD

**Issue by CGQAQ** [vuejs/vue#10056]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/animationend-problem-zkgkh](https://codesandbox.io/s/animationend-problem-zkgkh)

### Steps to reproduce
just open [this code](https://codesandbox.io/s/animationend-problem-zkgkh),  you will see that sometimes Helloworld component's animationend event won't be fired, so that it won't be remove

### What is expected?
all event should be fired

### What is actually happening?
some fired, some not

---
I'm not sure this is a bug, but I'm kind of considering this is a bug

**Comment by posva** [comment]
I think it's because you are using a `key` attribute with the index value, so when the values are removed, the same element is reused because of the key.
Using `:key="i"` fixes the result.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by CGQAQ** [comment]
thank you so much
