### ISSUE TITLE
vue在v-for迭代的时候，会存在item（数组的元素）恒为最后一个迭代元素的问题

### ISSUE THREAD

**Issue by omega4github** [vuejs/vue#10082]
### Version
2.6.10

### Reproduction link
[https://output.jsbin.com/daroyiz](https://output.jsbin.com/daroyiz)

### Steps to reproduce
测试代码如下：
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vue 测试实例 - 菜鸟教程(runoob.com)</title>
<script src="https://cdn.bootcss.com/vue/2.6.10/vue.min.js"></script>
</head>
<body>
<div id="app">
	<div v-for="item in list">
		{{item.name}}
		<child @done="display(item, $event)"></child>
	</div>
	<button @click="add">添加</button>
</div>
<script>
var Child = {
	template: "<span>子组件</span>",
	mounted: function (){
		this.$emit('done');
	}
};
new Vue({
  el: '#app',
	components: {
		child: Child
	},
  data: {
	  list: [{name:"张三"},{name:"李四"}]
  },
	methods: {
		display: function (item){
			console.dir(item.name)
		},
		add: function (){
			this.list.unshift({name:"王五"})
		}
	}
})
</script>
</body>
</html>
```
点击添加按钮控制台打印的总是李四，而不是王五。

### What is expected?
display方法得到的item总是最新添加的元素

### What is actually happening?
display方法得到的是list的最后一个元素

**Comment by zrh122** [comment]
@omega4github, 加个key, 打印就变成你想要的了: `<div v-for="item in list" :key="item">`

**Comment by omega4github** [comment]
为什么要加key才能达到我想要的呢，普通的用法，比如@click="handleClick(item)"都是正常的。

**Comment by posva** [comment]
Please, always provide the editable version of the repro. You need to use a `key`, the component gets reused.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
