### ISSUE TITLE
[Feature Request] Dart Language Official Port

### ISSUE THREAD

**Issue by DQvsRA** [vuejs/vue#10125]
### What problem does this feature solve?
Dart language official support for Vue/Vuex/Router, or maybe it will be just webpack transpiler plugin or module.

### What does the proposed API look like?
Same as JS but instead of JavaScript we will be able to use Dart.

**Comment by posva** [comment]
Hi. Vue should work with dart like any other js library. There is no need to _port_ Vue to dart, that will simply not happen.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
