### ISSUE TITLE
<transition> updates item slot while animating in, but not while animating out

### ISSUE THREAD

**Issue by sp00x** [vuejs/vue#10132]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-lfgvz](https://codesandbox.io/s/vue-template-lfgvz)

### Steps to reproduce
Press "add" to animate in some items - the timer and color changes according to the "state" property - in both upper and lower versions.

Press "remove" on an item and the timer and color is "frozen" with what it was when last rendered in a "visible" state (in the lower list, with transition) but keeps updating in the upper (logically, since it's not being transitioned)

### What is expected?
Same behavior of in and out - that the slot is alive and reactive to changes as it is while animating in

### What is actually happening?
Different behavior of in and out

---
I understand this may be in an attempt to optimize something, but maybe an additional property for <transition> could be added to get the same behavior of in and out?

The example is not really how I was planning to use this, but just to illustrate the problem.

**Comment by posva** [comment]
It doesn't update because the element is being removed per v-if being false. It is consistent with v if which prevents anything inside from rendering. If you want to animate something and then remove it yourself, you can listen to the same event and remove the wrapper after the transitionend or animationend event is triggered
