### ISSUE TITLE
$refs will reactive at component.

### ISSUE THREAD

**Issue by haishengXie0712** [vuejs/vue#10161]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-j5jic](https://codesandbox.io/s/vue-template-j5jic)

### Steps to reproduce
Register the component globally and specify ref name.

### What is expected?
The data can reactive.

### What is actually happening?
The data can't reactive.

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/59593564-c0bd6a80-9124-11e9-84ad-a6da78cf92fe.png)
What do you expect?

**Comment by haishengXie0712** [comment]
@Justineo I hope this data doesn't reactive. because
![image](https://user-images.githubusercontent.com/18388933/59594216-0595d100-9126-11e9-8fb4-8cd59831b48c.png)

**Comment by Justineo** [comment]
The doc is saying the `$refs` object isn't reactive itself. In your case, your parent component is depending on the child component's reactive data so it rerenders when child data changes. It's not caused by `$refs` itself.

`$refs` is not reactive, which also means you can't use it in `computed` to derive component state.

**Comment by haishengXie0712** [comment]
@Justineo I don't quite understand what you mean, but thank you very much.
