### ISSUE TITLE
Click on button not triggered when DOM changes

### ISSUE THREAD

**Issue by hadrian625** [vuejs/vue#10186]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/s08n4agu/2/](https://jsfiddle.net/s08n4agu/2/)

### Steps to reproduce
1. Click the Save button
2. Red error message is shown and Save count text is 1
3. Type something in the text input (ex. Adrian)
4. Click the save on its lower part
5. The red error message disappears, Save button is move up, but the save count remains to 1, which indicates the click on button was not triggered at all. Only if the Save button is clicked again, the click handler is invoked and save count is incremented

### What is expected?
The click handler on save button is actually invoked for step 4

### What is actually happening?
The click handler is not invoked at all when the button moved up due to the fact that the red text element is removed from DOM.

**Comment by posva** [comment]
That is how the click works:

- the change event is triggered by mousedown outside
- html renders again
- button moves up
- you release cursor outside of the button, so no click triggered

it's the same as if you press the mouse then move the cursor away from the button and release it

**Comment by hadrian625** [comment]
This was created from a bug we received from our testers. As a user it is annoying to have to click twice on the save button in order to actually save your data. I understand what you are saying about the click event, but you can agree that for the end user this is irrelevant, for him it is just a bug in the application which makes him click twice on save button before his data is actually saved.
Is there a workaround to fix this behavior?

**Comment by posva** [comment]
Oh yeah, to be very frank: this is bad UI, but it would be the same in plain javascript that why it's not a bug. There are many ways to fix it, one is redesigning things so the button doesn't move when clicking, you could also use realtime validation, or use v-model so the error disappears right away instead of when the user clicks away.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions though!
