### ISSUE TITLE
A way to render a template with whitelisted directives

### ISSUE THREAD

**Issue by vaartis** [vuejs/vue#10205]
### What problem does this feature solve?
It would be good to have a way to render a template that includes user-provided content, while only interpreting a whitelist of directives/components and rendering only those, while ignoring all others. In my particular case, i was trying to build a comment section that allows people to put a spoiler/collapse at any point in the comment and tried to use Bootstrap-Vue's collapse ( https://bootstrap-vue.js.org/docs/components/collapse/#collapse ), however, that would require vue actually interpreting the comment that might have other directive input by the user, thus it would be good to have a way to only interpret certain whitelisted directives and components in the template.

### What does the proposed API look like?
Not sure about how the API'd look like, but maybe something like a `whitelist` in the component  would make it only interpret these directives, like this:

```
{
    template: "<Post /> <!-- works --> <v-directive>test</v-directive> <!-- does not expand and if left as is, not in whitelist -->"
    whitelist: ["Post"]
}
```

**Comment by posva** [comment]
Since this is a very specific use-case, I would recommend you doing some pre processing and post processing of the content provided by the user. Since a directive is Vue-specific, you could use a different prefix as well.
I'm confused about your example though, as you use components, you can already _whitelist_ those with `ignoredElements`
