### ISSUE TITLE
Add a track functionality to Vue

### ISSUE THREAD

**Issue by wolandec** [vuejs/vue#10230]
### What problem does this feature solve?
Time to time one need to track setting of component data. Basically we use watch, but watch call a handle function only if data is changed. But it could be usefull to track all sets of data even if old and new values are the same. For example it would be a log messages. It may be the same but I need to add it in a list or something all the time, so I need to know each time when message is set.

### What does the proposed API look like?
```
track:{
 handler: function(){},
 deep: true,
 immediate: true
}
```

**Comment by posva** [comment]
This looks like a very specific use case and it seems to go agains declarative + reactive data in Vue so I would rather see it in an external library because it's completely different from Vue Observation mechanism.
You could also implement this as a Vue plugin that generates computed setters or/and regular JS setters in the `beforeCreateHook`. I think this example could help you: https://github.com/posva/vue-recomputed/blob/master/src/index.js
