### ISSUE TITLE
服务器端渲染使用Store Code Splitting动态注册Stored导致 The client-side rendered virtual DOM tree is not matching server-rendered content. 的问题

### ISSUE THREAD

**Issue by Kidwind** [vuejs/vue#10259]
### Version
2.6.10

### Reproduction link
[https://github.com/Kidwind/vue-ssr-template.git](https://github.com/Kidwind/vue-ssr-template.git)

### Steps to reproduce
根据官方文档创建一个服务器端渲染的应用，将页面的存储直接写在根目录的store.js文件中，没有问题，但随着项目的复杂度增加，全都写在根目录的store.js中会导致代码臃肿，因而考虑使用官方文档的Store Code Splitting模式 （https://ssr.vuejs.org/guide/data.html#store-code-splitting），但改成该模式后，服务器端渲染完成后会在控制台提示：

“[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.”

且页面后续操作无法正常运行。

### What is expected?
消除控制台错误提示且页面正常运行。

### What is actually happening?
控制台提示：

“[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.”

初步估计按官方文档的模式修改，会导致store模块的注册晚于客户端的vdom与服务器端渲染的 DOM 结构的匹配验证，因而导致了错误提示及页面无法正常运行。

---
建议官方提供可行的解决方案。

**Comment by sodatea** [comment]
无法复现。

**Comment by Kidwind** [comment]
@sodatea 无法复现的原因是我已经调整了代码，官方文档中 unregisterStore 的调用过程在 destroyed 事件时，我就想对应的 registerStore 调用那应该在 created 事件上比较合适，试过以后发现确实可行，建议官方文档进行相应的调整，以给用户以最佳实践的参考，避免大家走弯路，谢谢！

**Comment by dongqudamage** [comment]
this.$store.unregisterModule('home')

**Comment by dongqudamage** [comment]
What do you do specifically?

**Comment by dongqudamage** [comment]
请问下按照官方文档出现此问题 具体如何解决

**Comment by Fredericson22** [comment]
HLPppllkkkkkkkkEnvoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
-------- Message d'origine --------De : Mr Ma <notifications@github.com> Date : 19-09-01  23:26  (GMT-05:00) À : vuejs/vue <vue@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : Re: [vuejs/vue] 服务器端渲染使用Store Code Splitting动态注册Stored导致 The client-side rendered virtual DOM tree is not matching server-rendered content. 的问题 (#10259) 请问下按照官方文档出现此问题 具体如何解决



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/vuejs/vue/issues/10259?email_source=notifications\u0026email_token=AHLD2BWPCBH2BA6ELRD4AHLQHSBVFA5CNFSM4IB6TZB2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5UTEBY#issuecomment-526987783",

"url": "https://github.com/vuejs/vue/issues/10259?email_source=notifications\u0026email_token=AHLD2BWPCBH2BA6ELRD4AHLQHSBVFA5CNFSM4IB6TZB2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5UTEBY#issuecomment-526987783",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
