### ISSUE TITLE
-leave transition class is not applied

### ISSUE THREAD

**Issue by dritir** [vuejs/vue#10289]
### Version
2.6.10

### Reproduction link
[http://jsfiddle.net/mftxrs1d/27/](http://jsfiddle.net/mftxrs1d/27/)

### Steps to reproduce
Click toggle button on fiddle

### What is expected?
I expected to see the square change to red.
initial color: grey.

leaving:
[red]->[green]
entering
[blue]->[yellow]

### What is actually happening?
Not applying v-leave class
initial color: grey.

leaving:
[grey]->[green]
entering
[blue]->[yellow]

**Comment by ray-kim-12** [comment]
This is not an issue with Vue.
Please post this on Stack Overflow

**Comment by posva** [comment]
It's true that this behavior can be a bit confusing but it's actually working correctly because of the transition being applied but not being left enough time to change the color:

The `.leave` and `.leave-active` classes are applied at the same time. Because `element` already has a background-color, this triggers a 5s transition from grey to red, but one frame after the `leave` class is removed and `leave-to` is adding, triggering a new transition to green. So the color never gets enough time to change to red.

The solution is not applying the transition on `leave-active` but only on `leave-to` so the first change do not apply a transition: http://jsfiddle.net/posva/o4Lqw5ts/

The problem do not appear on enter because the browser do not get the time to render the element without `enter` so it appears with the blue initial color and triggers the transition from there
