### ISSUE TITLE
Props 组件默认值问题

### ISSUE THREAD

**Issue by Erik5169** [vuejs/vue#10325]
### Version
2.6.10

### Reproduction link
[http://www.nothing.com](http://www.nothing.com)

BUG比较简单，没有提供具体的代码案例

### Steps to reproduce
定义子组件接受父组件值的时候， 子组件接收父组件的值为一个对象的时候，default: function(){return {name: '==='}}, 如果父组件传值为null的时候， default值没有启用， 经过测试 在父组件传 undefined的时候， default值启用

### What is expected?
期望父组件传null或者{}的时候，子组件default的值能够启用

### What is actually happening?
传null的时候，子组件访问数据会报错

**Comment by posva** [comment]
`null` is an accepted value, so it doesn't trigger the default.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

Also, a repro is always required

**Comment by Erik5169** [comment]
thank you
