### ISSUE TITLE
[DISCUSSION] Is it possible to change prop programmatically using refs or something else available for the same? 

### ISSUE THREAD

**Issue by UtkarshGupta-CS** [vuejs/vue#10349]
### Version
2.6.10

### Steps to reproduce
I have created vue instance programmatically using `new Vue`. Wanted to change the props of it. One way is to use vuex store and update the store accordingly. Wanted to know if other ways are possible to change the props?

### What is expected?
Want to update props programmatically using refs or something else available.

### What is actually happening?
Only way is to use vuex store and update the store accordingly.

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

It's not completely clear what you are trying to do, but if you want something to change, it cannot be a prop, it should be a `data` or state in Vuex. A prop is like function argument, it is given whereas you own a `data` properties and can freely change it
