### ISSUE TITLE
自定义组件的bug，slot的内容无法触发 外层touchstart事件 click事件可以

### ISSUE THREAD

**Issue by wxkcoder** [vuejs/vue#10359]
### Version
2.6.10

### Reproduction link
[https://github.com/wxkcoder/bugs_demo](https://github.com/wxkcoder/bugs_demo)

### Steps to reproduce
声明！！：这是vue的bug，不是代码实现问题  请@posva 不要直接关闭

问题描述：
页面A引用的一个自定义组件c ，c 允许通过slot标签插入节点内容 slot标签外层盒子绑定了touchstart事件和click事件

出现的问题：
在ios10.3.3版本下  通过 'this.$router.push({name:A})' 的方式跳转到页面A后，点击组件c通过slot标签插入的内容 无法触发touchstart事件 但是 可以触发click事件。
直接访问页面A 两个事件都可以触发

在ios12版本上没有发现这个bug。

将vue版本改为2.5.22后 所有ios版本都没发现这个bug

如果你觉得我没有描述清楚的话 请运行下面的demo在 ios10版本上 谢谢！请不要直接close！！
demo：https://github.com/wxkcoder/bugs_demo

### What is expected?
push跳转后 slot的内容不触发外层盒子的touchstart事件

### What is actually happening?
push跳转后 slot的内容触发外层盒子的touchstart事件

**Comment by posva** [comment]
Hey, please stop opening the same closed issue every day. It's not okay.

I already pointed you that the problem came from a change in 2.6 and you can read about it at https://github.com/vuejs/vue/issues/9340#issuecomment-455673559 and [this gist](https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd). If you 

If you try opening the same closed issue again, we will have to block you, so please use the appropriate channels to get help about how to implement your solution. The fact that the `click` event can be triggered at the same time as the parent `click` event that attaches the nested `click` event is not something you want to rely on either as it's prone to breaking and flaky. There are multiple reasons it may have worked in one iOS version and not others and it's probably related to the delay Safari waits before considering it a double tap and the fact it doesn't work in the newest version of iOS but it works on others only adds to my point of the pattern used being flaky.
