### ISSUE TITLE
[Feature Rquest] Create Async lifecycle events

### ISSUE THREAD

**Issue by TheInvoker** [vuejs/vue#10364]
### What problem does this feature solve?
Ability for app to trigger events when conditions are met async style.

### What does the proposed API look like?
In addition to mounted:

```
mounted : function() {
    // synchronous
    var table = this.$refs.myTable;  // will be undefined if it was loaded like        components : {  'my-tabe' : () => import(".../my-table.js") }
}
```

we should also have mounted.async:

```
"mounted.async" : async function() {
    // asynchronous
    var table = this.$refs.myTable;  // will be the actual table reference if it was loaded like         components : {  'my-tabe' : () => import(".../my-table.js") }
}
```

Essentially, whatever lifecycle hooks are applicable, should have an async version of it too, which only runs when all it's precondition resolves its promises. So the async mounted should only run when all it's child components have downloaded it's component and mounted it too.

The other benefit here is that the time between the regular mounted running and the async mounted running, you can also display a loading bar. 

Or an alternative is to make $refs async style

```
mounted : async function() {
    // asynchronous
    var table = await this.$refs.myTable;   // will be the actual table reference if it was loaded like         components : {  'my-tabe' : () => import(".../my-table.js") }
}
```

**Comment by posva** [comment]
Instead of doing that in mounted, you should create a method and call that method with a lifecycle hook: `@hook:created`, `@hook:mounted="doThingsWithMyTable"` (that event handler would go on the dynamic component, the one that also holds a `ref="myTable"`

I'm not even sure we can make the ref a promise for a dynamic component as they start as undefined and they are set as the component renders its children, but the problem is it would introduce more confusion than anything because a ref would have more states than undefined vs the element/component.

Another solution would be adding an `updated` lifecycle hook in the component and check if all the refs necessaries are preset before continuing:

```js
updated () {
  // no need to declare finished in data unless it's used in the template
  if (this.finished) return
  if (!this.$refs.myTable) return
  if (!this.$refs.other) return
  // do something with both
  this.finished = true
}
```

**Comment by TheInvoker** [comment]
the @hook:mounted="doThingsWithMyTable" solution worked great!
