### ISSUE TITLE
Capture template errors in vue production build

### ISSUE THREAD

**Issue by sajuthankathurai** [vuejs/vue#10400]
### What problem does this feature solve?
We use Adobe Experience Manager (AEM) to author pages. And Vue is acting as a Front end library. In our Vue code base we dont have any HTML templates. We initialize the data property, have computed and methods. HTML is authored in AEM. The problem is that if an author of AEM uses a non-existent method in HTML templates, then our Vue production build is not able to capture the error. Instead a black page is shown to user. Is there a way to capture these kind of errors in Vue production build. Basically the HTML is out of Vue control.  

### What does the proposed API look like?
I propose to enable Vue.config.errorHandler to catch errors even in production build.

**Comment by posva** [comment]
Unfortunately a part of those errors are at runtime, which means that if you want to display them, you will have to ship a version of Vue that is bundled with `process.env.NODE_ENV` equal to `development`. Production builds strip that off to get a better performance.

My recommendation would be to be able to switch between build in your app if the performance can make a difference so that users can debug their templates. Providing the env variable in your webpack config (or Vue CLI or nuxt config) should explicitly apply to Vue files only. This being a usage question I will ask you to use the proper channels like the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
