### ISSUE TITLE
Option to default all input v-model bindings to lazy

### ISSUE THREAD

**Issue by nicklepedde** [vuejs/vue#10436]
### What problem does this feature solve?
For an app I'm developing, it's more practical to have all the input binding/updates happen on change rather than input. So for every input I need to add the .lazy modifier to the v-model attribute.

I'd like a way to set this once, and have all bindings use it without needing to specify it in every place.

### What does the proposed API look like?
Per instance:
new Vue({
  el: '#app',

  **model: {**
    **event: 'change'**
  **},**

  data: {
    message: 'Hello Vue!'
  }
})

Globally:
Vue.config.defaultModelEvent = 'change';

..then if there is an exception where I ever need to revert this behaviour, I do (something like):
<input v-model="userName" **@input="emitChangeHandler"**>

**Comment by posva** [comment]
I don't think this is a good idea in terms of API because applying modifiers globally require having the _opposite_ modifier (`lazy` -> `immediate`?), creating the double api surface for every single modifier we want to support and I think that if we add support for one, then why not for others.
I think, these costs are way too much for a very app-specific, tiny writing improvements. It doesn't improve anything else beyond that.

The reason `lazy` is not the default is because for most users, having that immediate update makes sense. Therefore `lazy` exists to allow the other behavior whenever is needed but having good defaults.

Having this option could also allow very implicit and hard to debug behaviors where variables attached to v-model are not updating because somewhere there was a global mixin adding that `model`. It also adds more questions like, should this setting be modifiable during runtime? Should the setting be inherited?, etc

All this complexity outweighs the small improvement it would bring
