### ISSUE TITLE
vue子组件获取父组件实例

### ISSUE THREAD

**Issue by hqzh** [vuejs/vue#10448]
### What problem does this feature solve?
为什么要this.$parent.$parent这样繁琐的点两次才能获取父组件data,methods？节制使用原因吗？

### What does the proposed API look like?
this.$parent

**Comment by pcl1350306170** [comment]
组件通信中，$parent 只能是子组件获取他的父级组件的参数，祖父机必须写两次，组件通信建议使用props和$emit






在 2019-08-28 14:19:02，"hqzh" <notifications@github.com> 写道：

What problem does this feature solve?

为什么要this.$parent.$parent这样繁琐的点两次才能获取父组件data,methods？节制使用原因吗？

What does the proposed API look like?

this.$parent

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Your question isn't clear to me but `$parent` is nice to use in specific situations for lib and coupled components. Otherwise using props and events is better
