### ISSUE TITLE
Micro-FrontEnd implementation

### ISSUE THREAD

**Issue by engblh** [vuejs/vue#10441]
### What problem does this feature solve?
Convert monolithic UI applications into micro frontend. Integrate multiple vuejs apps dynamically. Idea is simple. lets say 3 vuejs apps are running at three different domains. domain1.com, domain2.com, domain3. com. To give single user expereince there is landing vuejs app called landing.com. Landing.com has configuration file for pointing towards multiple web apps. and dynamically it will render another vuejs app into landing.com web app. Allow to communicate apps via some interface.

### What does the proposed API look like?
Convert monolithic UI applications into micro frontend. Integrate multiple vuejs apps dynamically. Idea is simple. lets say 3 vuejs apps are running at three different domains. domain1.com, domain2.com, domain3. com. To give single user expereince there is landing vuejs app called landing.com. Landing.com has configuration file for pointing towards multiple web apps. and dynamically it will render another vuejs app into landing.com web app. Allow to communicate apps via some interface.

**Comment by posva** [comment]
Vue has been used to create Micro front ends architecture before. I really don't know what you are asking for since there isn't even a single piece of code.

I think this is a question and since Github issues are for bug reports and feature requests only, you should ask this on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
