### ISSUE TITLE
this.$emit not work on router-link in version 2.6

### ISSUE THREAD

**Issue by lyqline** [vuejs/vue#10465]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-1j5tj](https://codesandbox.io/s/vue-template-1j5tj)

### Steps to reproduce
steps in reproduction page

### What is expected?
Normally listen for events dispatched by router-link using $emit when click router-link

### What is actually happening?
it can't dispatch custom event when click router-link

**Comment by posva** [comment]
This is due to micro/macro tasks changes in 2.6.0. Please see https://github.com/vuejs/vue/releases/tag/v2.6.0 and similar issues with like https://github.com/vuejs/vue/issues/9340. In your case the handler is called but the event never reaches the component because page changes before it can happen. You can get around this by dispatching the event to the store or something that does not get affected by the navigation
