### ISSUE TITLE
Observable doesn't react to dynamic properties declared with Vue.set

### ISSUE THREAD

**Issue by Spittal** [vuejs/vue#10497]
### Version
2.6.10

### Reproduction link
[https://codepen.io/Spittal/pen/LYPdZdK](https://codepen.io/Spittal/pen/LYPdZdK)

### Steps to reproduce
- Create an observable 
```const data = Vue.observable({});```
- Add a property to it 
```Vue.set(data, 'test', true);```

### What is expected?
That the observable reacts to the changes made by Vue.set

### What is actually happening?
it is not reacting and the observable remains in the state before Vue.set

**Comment by AlexandreBonaventure** [comment]
It should be noted that the dependency tracking works fine if you nest the object referenced in the template.
Here's a example https://jsfiddle.net/4gLv6za2/4/

**Comment by LinusBorg** [comment]
That's because you have added them as a normal (non-reactive) property to the Vue proptotype.

That means that Vue's Reactivity System can't detect that your template has a dependency on the reactive object that is referenced through this non-reactive property.

So when you mutate this object, there's no registered dependency that a watcher could informa about the change.

it works for those other examples that have their existing propery changed since this code:
```
<h2>{{ $experimentB }}</h2>
```
Implicitly touches the existing reactive `propertyB` in order to turn the object into a string and print it, so now the Vue template has a dependency *on this one property*, but *not the object a a whole*

**Comment by Spittal** [comment]
Hey @LinusBorg . The use case is a permission system that is abstracted into a plugin.

The goal is to use the plugin in templates like
```
{{ $permissions['some-permission'] }}
```
And have that be reactive.

However the checks for the permissions come async and so we don't "know" about them at app start.

So, we start by installing the plugin and running this
```
Vue.prototype.$permissions = Vue.observable({});
```

Then later on calling a method that adds to that observable using `Vue.set`. For example:

```
// after getting user from API
export function initPermissions (user) {
  Vue.set(Vue.prototype.$permissions, 'some-permission', checkPermission(user));
}
```


it seems clear to me though that the `$permissions` object wouldn't be reactive, because there are no getters and setters made for that object, however I assumed (incorrectly) that Vue would assign a watcher for that observable based solely on the fact it is an observable. But I suppose only children of observables are actually reactive?

**Comment by AlexandreBonaventure** [comment]
interesting @LinusBorg ... this is why something like that is working https://jsfiddle.net/dq8jv6kb/

**Comment by posva** [comment]
As described by @LinusBorg, this is expected. You will need to use a property inside of the observable object as @AlexandreBonaventure pointed out
