### ISSUE TITLE
Give a way to use html5 custom element without global register

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue#10538]
### What problem does this feature solve?
When use custom element tag name in vue template/render, user must define the tag name global.

But technically, create a custom element just need `new CustomElement` rather than `document.createElement('custom-element')`.

### What does the proposed API look like?
Maybe:

```js
//customElements.define('custom-element');//not define this global, but:

componentOptions = {
    template: '<custom-element />`,
    components: {
        'custom-element': CustomElement, // if the constructor is instance of HTMLElement, then treat it as a local custom tag
    },
};
```

In Vue, it's better to pass `Vue` as the first argument of `CustomElement` constructor, so that user can use Vue in shadow root to write mvvm code. Then the custom element technology just supply css isolating wrapper, and outside/inside are both vue-mvvm.

**Comment by posva** [comment]
By global I imagine you mean https://vuejs.org/v2/api/#ignoredElements

I don't think it's a good idea to mix both in the same option because it could also introduce lazy loading and other features that we don't want to handle in Vue for custom components.
Also, since custom elements are declared globally, I don't think it makes sense to declare them locally and it would lead to repetition at the end to be able to use them everywhere needed

This can be achieved using a mixin that rewrites the `components` options in the `beforeCreate` hook to remove CustomElements if you really want to mix them together:

```js
Vue.mixin({
  beforeCreate() {
    for (const component in this.$options.components) {
      if (isCustomElement(this.$options.components[component])) {
        Vue.config.ignoredElements.push(component)
        delete this.$options.components[component]
      }
    }
  }
})
```
