### ISSUE TITLE
<video v-model="currentTime"/>

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vue#10542]
### What problem does this feature solve?
Reactively setting the playback position of the html5 video element.

This would allow playback position to be reflected in a data property, and the playback position to be set by modifying a data property.

### What does the proposed API look like?
Data binding with video element's `currentTime` property

```
<video v-model="currentTime"/>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by posva** [comment]
I don't think using a two way binding on a video element is a good idea as it creates lag when playing because we are setting the value all the time: https://jsfiddle.net/b5j3arym/. It needs to be worked around this way: https://jsfiddle.net/x1bkLg74/.

`v-model` is also for form elements and simply doesn't feel natural to apply to a video because there are quite some other parameters like the volume, playbackRate, fullScreen. Each of them needs to be handled differently but could also have a two-way binding. Adding support just for one but not the others seems off.

To put it in a nutshell I think this is better off in a user library also because `video` elements are not as common in applications as form elements are so adding this for all users would increase size and the different possibilities makes it unintuitive

**Comment by franciscolourenco** [comment]
`@timeupdate` is fired frequently, but the lag could be completely avoided by diffing with internal state, and setting `video.currentTime` time selectively. This would be the job of the `v-model` directive. The result would be similar to the second jsfiddle.

The fact that video has other properties besides `currentTime` is a reasonable impediment in the design of the API, but it would nonetheless be useful..
