### ISSUE TITLE
Extending Single File Component results to double mounting

### ISSUE THREAD

**Issue by itomtom** [vuejs/vue#10568]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-rr65f](https://codesandbox.io/s/vue-template-rr65f)

### Steps to reproduce
Run codesandbox and you will see 2 'Created Parent' and 1 'Create Child' console logs.

### What is expected?
Only 1 'Create Child' console log

### What is actually happening?
Extending the parent template and class is causing extra mounts not required. 

---
What is the correct way for extending Single File Components to reuse template and class?

**Comment by posva** [comment]
I don't know what you are trying to do by extending the components like that because the template cannot be reused but when it comes to `created` hooks (as others), they are merged to be both kept (https://vuejs.org/v2/guide/mixins.html#Option-Merging). But basically, only one of them should have a template as only the last one will be used: https://codesandbox.io/s/vue-template-6w60s

To reuse template parts, you should use scoped slots

See https://github.com/vuejs/vue/issues/6811 and https://github.com/vuejs/vue/issues/5401
