### ISSUE TITLE
[Vue Warn]: Unknown custom element: <some-component> - did you register the component correctly?

### ISSUE THREAD

**Issue by AasmundEndresen** [vuejs/vue#10563]
### What problem does this feature solve?
DO NOT CLOSE!! This is a bug - but I am working in a private repo, and have a NDA with my employer so I'm not able to provide a minimal reproduction which only leaves me with this option to actually submit an issue.

I am recieving a Vue Warn in multiple places that the components are not registered properly.  However I've been able to confirm through console.logs that the components are in fact imported.  I am also able to get rid of the error by changing the import style of the component.

The problem occurs, very inconsistently when I use named imports from an index file - if I change the imports to be default imports directly from the component file the problem disappears.  There is no reason this should be causing an issue in Vue, as this is basic ES6 syntax and works fine in other frameworks such as React and Svelte.

I'm lead to believe this SHOULD also work fine in Vue because for most components its not an issue, it only fails with some.

### What does the proposed API look like?
```
// In SomeComponent
<script>
export default { name: 'some-component', ... }
</script>


// In SomeOtherComponent
<script>
export default { name: 'some-other-component', ... }
</script>

// In index.js
export { default as SomeComponent } from './SomeComponent.vue';
export { default as SomeOtherComponent } from './SomeOtherComponent.vue';

// In MainScreen.vue
<template>
  <some-component />
  <some-other-component />
</template>

<script>
  import { SomeComponent, SomeOtherComponent } from './components';
  export default {
    name: 'main-screen',
    components: {
      'some-component': SomeComponent,
      'some-other-component': SomeOtherComponent,
    }
  }
</script>
```

**Comment by posva** [comment]
> DO NOT CLOSE!! This is a bug - but I am working in a private repo, and have a NDA with my employer so I'm not able to provide a minimal reproduction which only leaves me with this option to actually submit an issue.

You can still work on a boiled down reproduction if you believe this is a bug...
My only hint here is look at what is contained in the imported variables like `SomeComponent` and start debugging from there, come back if you manage to find a bug, but please provide a boiled down repro, that is required

**Comment by AasmundEndresen** [comment]
Please don't just close it - no I don't have time to work on a boiled down reproduction of the bug because I am under a tight deadline, and have lots of pressing issues that I should be spending my time on over this.  I have already looked at the imported components, and requested help on the forums, on gitter, on stackoverflow and this is my last resort.

Its very frustrating to also see multiple other issues on this problem having been closed in the same manner when searching the issues.  I have found a bug, I have told you exactly how it occurs.  The only difference between working code and not working code is whether or not the file is imported using named import or default import.

Please respect the fact that I am working a demanding job, and have other duties outside of work that doesn't give me the luxury of creating a boiled down repro of the issue, and at the very least allow the issue to stay open longer then 15 minutes so others may comment and involve themselves.

By closing it you make sure that its not taken seriously by others - and the problem remains.

**Comment by kinow** [comment]
@AasmundEndresen I don't see @posva closing it as a disrespect. The project has a guideline, not to put off contributors, but to help the maintainers to triage and work on issues. This ensures that issues are not forgotten after not being updated, or due to the lack of information.

You can create an issue in your fork, and log things. Sometimes I create a gist on GitHub and document my findings, then remove the unnecessary information and create an issue on GitHub. This helps me to keep tabs of the problems as I investigate, without causing too much noise on other OSS projects.

It can be frustrating, but once you have passed your deadlines, found more time to work on this issue and prepared a working example to reproduce the issue, I'm sure @posva and others will chime in here to help :+1:

**Comment by yyx990803** [comment]
Please respect the fact that as OSS maintainers, we are also working a demanding job, and have other duties outside of work that doesn't give me the luxury of creating a boiled down repro for every user who don't have the time to do that themselves.

**Someone** has to create the repro in order to fix the bug. It's either our time or yours. Since you are not paying for support, what makes your time more valuable than ours? Entitlement?
