### ISSUE TITLE
If a component's subcomponent has Props, the page will be rendered twice

### ISSUE THREAD

**Issue by mayunhai** [vuejs/vue#10581]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/vue-template-l5s3n](https://codesandbox.io/s/vue-template-l5s3n)

### Steps to reproduce
https://codesandbox.io/s/vue-template-l5s3n

See the difference by clicking on the top menu and the refresh button below

### What is expected?
rendered once

### What is actually happening?
rendered twice

---
Actually, if I replaced created with mounted(@/src/components/layout.vue), it will be OK
but I still think there may be some problems here

I did change the value of this.level List.But I don't think it should affect other subcomponents.

**Comment by posva** [comment]
it renders twice because the url is `/home/home` (the way you declared in routes).

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂. Also make sure to provide precise information about what specific buttons to click, and what component is rendering more, or what log is expected, it will make it easier for us as well. Finally, this involves vue-router as well and issues should be opened in that repo instead
