### ISSUE TITLE
when I try to render a child component's slot, it shows bizzare phenomenon

### ISSUE THREAD

**Issue by th3eesome** [vuejs/vue#10580]
### Version
2.6.10

### Reproduction link
[http://plnkr.co/edit/CTaAoEUXIQDV0RcPcz2M?p=preview](http://plnkr.co/edit/CTaAoEUXIQDV0RcPcz2M?p=preview)

### Steps to reproduce
1. create a parent component, it has a "childVMs" array data attribute to contain its child components' Vnode. in its template, this component will try to render both its own default slot and its childVMs' slots.

2. create a child component. inside its `create()`, it will detect its parent Vnode and push itself into its parent's "childVMs" array mentioned above. it has a slot which named "cell".

3. in the app component，try to render the`<parent><child><template slot="cell"><input /><template></child><parent>`
  
4. you'll find there are two `<input>` rendered. the first one is the `<child>` component(contains the `<input>`), the second one is the `<child>`'s slot(only the input). they bind to the same attribute.

5. when I type something into the first `<input>`, the second one suppose to update its value synchronously. However, the second `<input>` is always 1 step slower than the first one. Why? 

### What is expected?
the second `<input>`'s value should update synchronously

### What is actually happening?
the second `<input>`'s value updates 1 step slower than the first one.

**Comment by posva** [comment]
A vnode cannot be reused: https://vuejs.org/v2/guide/render-function.html#VNodes-Must-Be-Unique

FYI The whole thing you are doing about passing vnodes that belong to a child to a parent or vice versa is not something you should rely on

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
