### ISSUE TITLE
Cannot change transition-group duration dynamically

### ISSUE THREAD

**Issue by Monchi** [vuejs/vue#10602]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/vue-template-vsvmo](https://codesandbox.io/embed/vue-template-vsvmo)

### Steps to reproduce
1. Open codesandbox
2. Click shuffle

### What is expected?
Both list are shuffled with animation

### What is actually happening?
Only first list is shuffled with animation, and second one has no animation.

**Comment by posva** [comment]
The name of the transition is the one that needs the CSS class:

```css
.list-move {
  transition: transform 1.5s;
}
```
(with `name="list"`)

Please check the documentation about transitions for more info

**Comment by Monchi** [comment]
@posva I see, so there is no way to change duration dynamically?

**Comment by lupas** [comment]
@posva 
Your answer unfortunately doesn't answer the _dynamically_ part of the OP's question.

Since https://github.com/vuejs/vue/pull/4857, the `duration` of a transition can be set (dynamically) via its props. In a **transition-groups** however this prop does not exist.

Is there a reason for that - or would that be something for a PR?

If not, what ways do you see to dynamically define styles for a transition-group? I obviously don't want to create a class for each duration.

**Comment by hateskream** [comment]
Any solutions?
