### ISSUE TITLE
inheritAttrs: false will only prevent one level of inheritance 

### ISSUE THREAD

**Issue by ycmjason** [vuejs/vue#10622]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/-bkvl9](https://codesandbox.io/s/-bkvl9)

### Steps to reproduce
1. create a `Base` component which has `inheritAttrs: false` and renders `<div><div v-bind="$attrs">hello</div></div>`
2. create a `Wrap` component which renders `<Base data-a="a" />`.
3. create a `WrapWrap` component which renders `<Wrap data-b="b" />`.

### What is expected?
```html
<div><div data-a="a" data-b="b">hello</div></div>
```

### What is actually happening?
```html
<div data-b="b"><div data-a="a">hello</div></div>
```

---
I have a feeling this is likely an intended behavior. But I find this counter intuitive as I would expect `inheritAttrs: true` to be equivilant to `inheritAttrs: false` + `<root v-bind="$attrs">`, but it's not.

Please see the `Wrap.vue` in https://codesandbox.io/s/-4qhjo

**Comment by ESnark** [comment]
1. It is intended behavior.
2. You are missing the structure of the `Base` tag or misunderstanding the role of `inheritAttrs`.

As you know, `inheritAttrs: true` literally inherit attributes. But In your example, Each attribute is inherited in different ways.

The following code from a **Base.vue** assumes no change.
```vue
<template>
  <div> <!-- root div -->
    <div v-bind="$attrs">hello</div>
  </div>
</template>

<script>
export default {
  inheritAttrs: false
};
</script>
```
Because of `inheritAttrs: false` from the code, the root div doesn't get `data-a` directly from **Wrap.vue**.

---

If the **Wrap.vue** is:
```vue
<template>
  <Base data-a="a" v-bind="$attrs"/>
</template>

<script>
import Base from "./Base.vue";
export default {
  inheritAttrs: false,
  components: { Base }
};
</script>
```

the output would be:
```html
<div>
  <div data-a="a" data-b="b">hello</div>
</div>
```
Though the root div of **Base.vue** doesn't inherit `data-a="a"`, delivered through `v-bind=$attrs`.  
and the destination of directive is `<div>hello</div>`.

---

On the other hand, next **Wrap.vue** is little more complex.
```vue
<template>
  <Base data-a="a"/>
</template>

<script>
import Base from "./Base.vue";
export default {
  inheritAttrs: true,
  components: { Base }
};
</script>
```
Because of `inheritAttrs: true`, This **Wrap.vue** gets `data-b="b"` from `<Wrap data-b="b"/>` of **WrapWrap.vue**.

and the `data-a="a"` of **Wrap.vue** is passed to `v-bind=$attrs` of **Base.vue**.

As a result, the HTML output would be looks like this:
```html
<div data-b="b">
  <div data-a="a">hello</div>
</div>
```
