### ISSUE TITLE
全局拦截IMAGE请求并重新设置新值

### ISSUE THREAD

**Issue by f2009** [vuejs/vue#10642]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/akjrdqL3/](https://jsfiddle.net/akjrdqL3/)

### Steps to reproduce
import { transformURL } from "./utils/file";
(function(imageDesc) {
  const imageNativeSet = imageDesc.set;
  Object.defineProperty(Image.prototype, "src", {
    async set(url) {
      url = await transformURL(url); // 将不能直接显示的URL转成base64
      imageNativeSet.call(this, url); // 重新设置IMAGE -> SRC = base64
    },
  });
}) (Object.getOwnPropertyDescriptor(Image.prototype, "src"));

### What is expected?
图片的加载内容是转码后的base64
exp: <div style="url(xxxx.jpg)" />   => <div style="url(base64)" />

### What is actually happening?
1. async set function被执行两次；
2. 并不能用base64替代转码前的URL，图片加载报错；

---
像这种全局的图片属性(src)监听并重写set，我的理解应该只对 new Image().src = "xxxx.jpg" 起作用，可为何在Vue里面对css设置的图片属性(background-image: url("xxxx.jpg"))也生效呢，Vue是否有做了代理(proxy)？

Thanks.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The second call probably happens because of the rerendering

**Comment by f2009** [comment]
OK, Thank you.
