### ISSUE TITLE
DOM isn't correctly in sync with data modified in v-on:leave

### ISSUE THREAD

**Issue by schffp** [vuejs/vue#10723]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/9xb5ft7n/2/](https://jsfiddle.net/9xb5ft7n/2/)

### Steps to reproduce
1. Open the devtools javascript console
2. Click the Accordion Header once. It will slide the content out correctly
3. Click the Accordion Header again. It will just remove the content without the transition

In the console logs, you will see how I demonstrate the bug on the example of the "content--transition" class, which isn't being added.

### What is expected?
The same behaviour as in v-on:enter, where DOM gets updated correctly, after modifying the respective data.

### What is actually happening?
The DOM doesn't get updated after modifying the respective data.

---
If you don't trust the console logs, you can uncomment the "done", and comment out the contents of "afterTransitionLeave". Then you can see in vue devtools, that "inTransition" is true, but that the class doesn't get added in the DOM

**Comment by posva** [comment]
When you add a class through Vue on the leave event, it's too late since Vue doesn't get to render that element again with the changing data.
Regarding the collapse animation, in case you still need help with it, there are many many resources online that show how to implement it like https://markus.oberlehner.net/blog/transition-to-height-auto-with-vue/  there also quite a few other issues with more explanations and examples like this one: https://jsfiddle.net/rezaxdi/sxgyj1f4/3/
