### ISSUE TITLE
This keyword issue inside created hook when using custom event

### ISSUE THREAD

**Issue by shahinseu123** [vuejs/vue#10765]
### Version
2.5.17

### Reproduction link
[https://codepen.io/shahin-alam-the-encoder/pen/OJJgyej](https://codepen.io/shahin-alam-the-encoder/pen/OJJgyej)

### Steps to reproduce
created: () => {
         Bus.$on('buswithid',(id) => {
             hey.invoice_id = id
             console.log('this is invoice id' hey.invoice_id)
             
         })

### What is expected?
created(){
  Bus.$on('eventbus', (value) => {
      this.msg = value
})
}

value is inside data and I expect the value set to msg inside data

### What is actually happening?
when I console.log(msg) inside $on(the arrow function it shows me the value inside msg, but the value is not set inside data->mag.

---
I am new in Vue, I hope you help and I love vue and vue team.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I can't see all your code but don't use arrow functions for life cycle hooks like created because it breaks `this`
