### ISSUE TITLE
include Vue twice

### ISSUE THREAD

**Issue by zakariamouhid** [vuejs/vue#10773]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/obpf43mn/](https://jsfiddle.net/obpf43mn/)

### Steps to reproduce
click 'add item' under 'App 1' or 'App 2'

### What is expected?
'App 2' list is updating

'App 1' list is updating

### What is actually happening?
'App 2' list is updating

'App 1' list is not updating

---
'App 1' list is updating after clicking 'toggle' under 'App 1'

I got the problem when I include Vue inside an iframe and include Vue in the parent of iframe
https://jsfiddle.net/fpeb2a9w/

**Comment by posva** [comment]
Regarding two versions of Vue on the same page: you cannot share the data between two different versions of Vue. Regardless, using one version is the right approach
For the iframe: it's pretty much the same problem since the data is not being observed by the same Vue version, that's why you don't see the changes. But I wouldn't recommend relaying on something like that as it's not sure the same object is passed and the general approach for communication in frames seems to be `postMessage`

**Comment by zakariamouhid** [comment]
@posva 
I solved the problem of iframe by using one Vue version in iframe and pass it to the parent and it works,

I saw this problem in version 2.5 with deep properties `data.prop1.prop2.prop3.prop4` and it seems solved in 2.6 but the problem now in `Array` so I think it may be solved in some next version
