### ISSUE TITLE
v-bind:is to mount more than one component

### ISSUE THREAD

**Issue by epileftro85** [vuejs/vue#10792]
### Version
2.6.10

### Reproduction link
[https://github.com/epileftro85/vue-repo](https://github.com/epileftro85/vue-repo)

### Steps to reproduce
I was trying to mount the components according the documentation with the v-bind:is or :is, but when one have couple of components mounting in this way, there is an issue mounting.

### What is expected?
Mount just the component according the variable value.

### What is actually happening?
Mounting several components at the time.

---
Do not know if the way i am trying is not the way to do it, but i want to mount the components according the variable value.

**Comment by posva** [comment]
When reporting bugs, please provide a **boiled down repro** (no ts, no router, no store unless necessary, no extra dependencies, if possible, on a code sandbox).
The only weird thing I saw was you were using `is` on components, but you should use it on the special component `component` itself:

```vue
<component :is="create" :companyId="1" />
```

or on regular elements to bypass browsers limitations like with tables (that's explained on the docs)

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by epileftro85** [comment]
@posva Thank you for the reply, i asked on [stackoverflow](https://stackoverflow.com/questions/58676202/component-mounted-twice?noredirect=1#comment103671021_58676202)  first but no one answered, this was my last resort, i will have your recommendations in mind, Thanks again.
