### ISSUE TITLE
Win7 performance poor in FIrefox

### ISSUE THREAD

**Issue by tomByrer** [vuejs/vue#108]
Not sure if you are excited to go be an alpha version of a browser, but it seems Firefox both on my system & yours is slower.  Chrome is good at self-optimizing JS, but IE10 is faster?!?  There is something wrong.

I'd like to see another test on [Firefox Aurora](http://www.mozilla.org/en-US/firefox/aurora/) by someone else if possible. 

http://vuejs.org/perf/
##### PaleMoon 24 (FIrefox 24 64bit fork)

Vue : 586.761230527598 ms
Backbone : 977.2169178305776 ms
Knockout : 815.6319040128437 ms
Ember : 2331.162324649311 ms
Angular : 1280.6926272519922 ms
React : 1747.6014769616304 ms
Om : 623.692327035591 ms
Ractive : 2467.218046849128 ms
##### Firefox Aurora 29.0a2

Vue : 745.4743032800534 ms
Backbone : 896.2194555564347 ms
Knockout : 631.6288146074476 ms
Ember : 2321.457255099189 ms
Angular : 967.7536891965756 ms
React : 1735.6967456038801 ms
Om : 673.2709978214953 ms
Ractive : 2408.884350006032 ms
##### Chrome Beta  32.0

Vue : 582.0000000012442 ms
Backbone : 973.0000000008658 ms
Knockout : 586.0000000011496 ms
Ember : 1910.9999999982392 ms
Angular : 1287.9999999995562 ms
React : 2000 ms
Om : 645.0000000004366 ms
Ractive : 1545.999999999367 ms
##### IE10 64-bit

Vue : 494.68142430828356 ms
Backbone : 1078.8844013250573 ms
Knockout : 689.9541721086216 ms
Ember : 2681.7604479124684 ms
Angular : 1710.8371672923313 ms
React : 1300.7038404594095 ms
Om : 471.64880336858186 ms
Ractive : 1432.5738544951637 ms
### Animating 100 Instances

~200 iterations, ms, results for Vue
PaleMoon24 (FIrefox 24 64bit fork) : 8.24
Firefox Aurora 29.0a2 : 9.10 (CPU % is much higher & seems more sluggish)
Chrome Beta  32.0 : 4.4
IE10 : 4.86

---

tia

**Comment by moritzjacobs** [comment]
Sorry to bump, but I'm experiencing some issues with exactly these symptoms. Unfortunately I can't publicly provide a link to the site, and I also can't pin down the problem to a reduced test case, since it's a large project.

Is there any experience out there, as to why a vue instance with ~100 child component instances would behave extremely slow/sluggish only on **Firefox** (tested with 56 and 57) on **Win 7**, compared to other browsers on the same system and the same FF versions on other systems (Win 10, Mac)?
