### ISSUE TITLE
There are components of slot and input. The update of the parent component will cause the input of the input to be reset.

### ISSUE THREAD

**Issue by bigbanana** [vuejs/vue#10802]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/coinSnake/f03grbnh/22/](https://jsfiddle.net/coinSnake/f03grbnh/22/)

### Steps to reproduce
Try changing the value of input

### What is expected?
Normal input

### What is actually happening?
Cannot be input normally, the current input will be covered by the old value

---
If you don't use slot, you won't find this problem.

**Comment by posva** [comment]
This is expected because changing the slot rerenders the component containing the input and because of the lazy modifier, the old value is set again, overriding what was written by the user. You can get around this by using a regular v-model with copy of the text and listening to the change event to change the original value
