### ISSUE TITLE
can we use v-if to replace dynamic component, what's the difference?

### ISSUE THREAD

**Issue by cheng-github** [vuejs/vue#10815]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/0dja4nfu/2/](https://jsfiddle.net/0dja4nfu/2/)

### Steps to reproduce
https://cn.vuejs.org/v2/guide/components.html#%E5%8A%A8%E6%80%81%E7%BB%84%E4%BB%B6

### What is expected?
I wanna know what's the difference between v-if and dynamic component, because I think I can use v-if directive to replace the usage of dynamic componet.

### What is actually happening?
As url show

**Comment by posva** [comment]
A dynamic component can handle any amount of cases

—

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
