### ISSUE TITLE
After the object attribute El in VM instantiation is written incorrectly, the console will not give an error prompt

### ISSUE THREAD

**Issue by TDcloud** [vuejs/vue#10814]
### Version
2.5x-2.6.10 
（Other versions have not been tested）

### Reproduction link
[https://github.com/TDcloud/es6/tree/master](https://github.com/TDcloud/es6/tree/master)

### Steps to reproduce
  const vm = new Vue({
         // Intentionally misspelled el, pel
         pel: "#app",
         router
      })

### What is expected?
Want to have an error prompt to the console

### What is actually happening?
No error message

---
If the attribute El in VM instantiation is wrong, the console will not report an error, but the effect will not come out. Is this a big bug?

**Comment by posva** [comment]
This is because a Vue instance can be mounted later on with `$mount`.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
