### ISSUE TITLE
A serious problem with Vue.ja

### ISSUE THREAD

**Issue by hahmjt** [vuejs/vue#10849]
### What problem does this feature solve?
Evan You.
Go back to China if you dont like freedom.

### What does the proposed API look like?
No Evan You

**Comment by yyx990803** [comment]
For context, this is what I quoted on Twitter:

> 自由，多少罪恶假汝之名

The original phrase came from [Madame Roland](https://en.wikipedia.org/wiki/Madame_Roland) during the French Revolution:

> O Liberté, que de crimes on commet en ton nom! (O freedom, what crimes are committed in your name!)

If you really understand the context, you will realize this is not a slam against Freedom itself, but the fact that when there is not enough structured principles and boundaries for a movement in pursuit of freedom, it can lead to [actions that manifest the very opposite of freedom](https://en.wikipedia.org/wiki/Reign_of_Terror).

Do I dislike Freedom? Of course not. Do I support violation of human rights? Of course not. (Note: I condemn the violence committed by all sides, no matter the triads, the police or the protestors) But should there be a boundary for justifiable means to fight for freedom? I believe so. Does the current movement seem to have a boundary on what can be done in the name of freedom? It seems quite clear that it does not due to the "never cut the ties" rule. I'm sympathetic to the high level motive behind the movement, but I think the the resort to violence and the strong reluctance to distance from it is questionable on both moral and practical grounds.

Freedom is not a static target - it's an equilibrium. It involves mutual respect and compromises between the members of a society. It's ironic to see fellow citizens' freedom of going to work and support their families being violated in the name of freedom. It's even more ironic that citizens can be physically attacked when they try to clear up the roadblocks or stop vandalization of public transit.

Before you call me clueless, I've personally had lengthy conversations with many supporters of the movement from various backgrounds (American married to an HKer, native-born HKer now living in EU, mainlander who support the movement...). I know what's going on. I can understand the fear, distrust and anger coming from some HKers. But I don't believe these justify everything is being done. I don't believe blind and unconditional support for violence is going to help HK. I believe HKers can do better.

I hope I have shown that my view is much more nuanced than a "with us or against us" binary. And if you truly value Freedom, you should be willing to sit down and think about it.
