### ISSUE TITLE
Manually triggered listener throws error even if catched

### ISSUE THREAD

**Issue by mediafreakch** [vuejs/vue#10873]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/button-that-awaits-async-click-listener-in-vuejs-m3hz1](https://codesandbox.io/s/button-that-awaits-async-click-listener-in-vuejs-m3hz1)

### Steps to reproduce
1. Open the codebox.io console window
2. Click the button in the demo panel and observe the console

### What is expected?
The error should not be thrown. No warning message should be emitted.

### What is actually happening?
Error is thrown and a warning message is emitted.

---
The important code can be found in /components/VButton.vue on line 36 and following

**Comment by posva** [comment]
It may look confusing in this specific situation, but the error handling is added at `App` level since that's where it would be called usually via the `@click` event listener but we cannot predict that the listener is going to get called inside the component so we wrap the method call to make sure we can trace the errors. If we don't wrap it, your code would work but it would not trace errors for most users.
One way to get around this is by passing the method as a prop
