### ISSUE TITLE
@click.native doesn't work for non-custom-component  dynamic component

### ISSUE THREAD

**Issue by NE-SmallTown** [vuejs/vue#10890]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/heaven_xz/h5836dnt/](https://jsfiddle.net/heaven_xz/h5836dnt/)

### Steps to reproduce
Reproduce: Just click the content after the timer fire.

### What is expected?
The click listener will be bound to the actual component.

### What is actually happening?
No listener be bound

**Comment by xingleizhao** [comment]
你传入的就不是组件类型，谈何“非自定义组件”。你传 `div` / `span` or 任何符合约定的 `name` 结果都一样。

**Comment by posva** [comment]
Unfortunately this is because of what code is generated to handle native events listeners: https://template-explorer.vuejs.org/#%3Ccomponent%20v-bind%3Ais%3D%22currentComponent%22%20%40click.native%3D%22handleClick%22%3E%0A%20%20%20%20inner%20text%20node%0A%20%20%20%20%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20inner%20div%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fcomponent%3E.

Since the variable passed to `is` could be a component or a native tag, we cannot guess which one to use and putting both would be problematic.
You could make your custom components emit `click` events by reattaching event listeners to the root with `v-on="$listeners"`

**Comment by xingleizhao** [comment]
因为当你传入 `div/span`这样合法的 `tagName` 会视为模版元素，而并非是一个组件类型。所以 绑定的 `click` 被视为自定义事件 。此时你改成这样就可以了：
```
 <component v-bind:is="currentComponent" @click="handleClick">
   ...
  </component>
```

如果传入的是组件类型， `.native` 才会监听到绑定的原生事件。

**Comment by NE-SmallTown** [comment]
@posva Thanks for your response

> Since the variable passed to is could be a component or a native tag, we cannot guess which one to use and putting both would be problematic.

I don't understand fully, add listener is a runtime process, when I use `@click.native`, if the `is` is a component, Vue can add listener to the real DOM of that component renders, if the `is` is a HTML tag like `div`, Vue can just add the listener to the 'div', I'm a little confuse about why need to guess(this is not in the compiler phase)

> You could make your custom components emit click events by reattaching event listeners to the root with v-on="$listeners"

For the custom component case, `@click.native` works fine, the issue case I described is for the HTML tag case.

After read the [@xingleizhao's  comment](https://github.com/vuejs/vue/issues/10890#issuecomment-561564377), I find that if I add both `@click` and `@click.native` like `<component v-bind:is="currentComponent" @click.native="handleClick" @click="handleClick">...</component>`, this will works for custom component **and** HTML tag, but I'm not sure if it's a correct/legal way to use or has some potential bugs
