### ISSUE TITLE
模板渲染不同步

### ISSUE THREAD

**Issue by wzy4072** [vuejs/vue#10900]
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/embed/quiet-field-pl84l?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/quiet-field-pl84l?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1 任意页面，先后执行异步方法，分别赋值和修改事先声明的属性。
2 查看页面模板渲染。
（请查看连接中APP.vue）

### What is expected?
双向绑定失效了

### What is actually happening?
希望声明的对象能在变化后渲染到页面

**Comment by posva** [comment]
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by wzy4072** [comment]
刚找到答案，打算回来关闭issues。
非常抱歉提了一个毫无价值的问题。
