### ISSUE TITLE
ContentEditable = "true" v-for generated data error

### ISSUE THREAD

**Issue by csq2018** [vuejs/vue#10929]
### Version
2.5.20

### Reproduction link
[https://jsfiddle.net/csq2019/6vLansm3/12/](https://jsfiddle.net/csq2019/6vLansm3/12/)

### Steps to reproduce
After pressing enter, the contents of editable div will automatically generate child elements. Subelements in div are rendered using v-for, but after press enter, the array is updated and a v-for rendering error is found.

### What is expected?
After the contents of the div in editable state are pressed to enter, the sub-elements in the div are rendered correctly according to the new array

### What is actually happening?
After the contents in the editable div press enter, the sub-elements in the div are re-rendered according to the new array, and the sub-elements generated by enter still exist.

**Comment by LinusBorg** [comment]
contenteditabe is the devil. its many bugs and browser-specific problems require manual, imerative DOM manipulation to make it work. It's not recommended to manage the child nodes of a contenteditable element with Vue.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If you want to track the value within the content editable but still do a v-for, you will probably need to make each `p` _contenteditable_ instead of the container. If you need complex manipulations, we recommend using a library to manipulate the content since there are a lot of edge cases we cannot handle inside Vue
