### ISSUE TITLE
Button of type="button" triggers submit when used with v-if

### ISSUE THREAD

**Issue by Ayrtonms** [vuejs/vue#10928]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/z4eftxd7/](https://jsfiddle.net/z4eftxd7/)

### Steps to reproduce
All it takes is two buttons inside a form. One button must be of type="button" and the other must be of type="submit". Both buttons should be controlled by a condition, with the v-if linked to the first button, and the v-else to the second. If a click on the first button turns the condition into false, the form will be submitted.

### What is expected?
That the click on the button of type="button" will not submit the form.

### What is actually happening?
The click on the button of type="button" submits the form.

---
I ran into this bug while writing an editable table component. The state of the row (editing or not) is controlled by a flag, and the buttons for editting/saving are controlled by a v-if/v-else. However, clicks on the "edit" button trigger the submit.

**Comment by LinusBorg** [comment]
### What happens?

1. When you do `this.test = !this.test`, Vue updates the view to reflect this data change. This happens on the current callstack in a microtask, so the current click event is still "active", as far as the browser is concerned.
2. This View update turns the *same button element* that triggered the click into a submit button, as diefined by the `v-if/v-else`.
3. When the click event has bubbled up to the form element, it now triggers a submit event.

You can "simulate" the same thing with vanilla JS:

https://jsfiddle.net/Linusborg/9o1nmcaq/1/

### Solution

Use `key` to make Vue *replace* the button element with a fresh one:

https://jsfiddle.net/Linusborg/t82Leyqg/

### Documentation

https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

**Comment by Rolanddoda** [comment]
@LinusBorg even though there are workarounds (like adding `key` or adding `.prevent` to the `handle1` event), that's sounds like a bug to me.

When you click the `button` with type `button` it should not fire the event from the other `submit` button. The issue seems to be that events from both buttons are fired.

Furthermore, it could be very difficult to find where the issue is, or even worst to not find the issue at all. 

**I tried in the same example in version `2.5.22` and there is no issue there.**

**Comment by LinusBorg** [comment]
> When you click the button with type button it should not fire the event from the other submit button. The issue seems to be that events from both buttons are fired.

Please read my explanation again and check my vanilla JS example which shows the same issue with just *one* button: It's not two buttons and two event - the original button is changed to type="submit" *while the original event is still "running" and bubbling up, and thus makes this a click event that triggers a submit on the form element.

> I tried in the same example in version 2.5.22 and there is no issue there.

It doesn't happen in 2.5 because in that minor version range we nextTick() wasn't a macro task (which runs on the same callstack), it was pushed to the *next* callstack - in which the event had already finished.

We are now using a microtask (again, as we did in <=2.3 I believe) since the other way introduced bigger and more frequent issues than the one you experienced here, so we will keep using a microtask.
