### ISSUE TITLE
Problem with v-bind:class in Microsoft Edge for components

### ISSUE THREAD

**Issue by yamelkaya** [vuejs/vue#10963]
### Version
2.6.10

### Reproduction link
[https://codepen.io/yamelkaya/pen/KKwvdrY](https://codepen.io/yamelkaya/pen/KKwvdrY)

### Steps to reproduce
Open codepen example. There are 3 components `test-x` on the page which set text color and background. Each label tells about text color and background.

Chrome: everything works as expected 

Edge 18: 1st and 3rd labels have incorrect color

### What is expected?
1: red text on yellow bg
2: red on gray
3: black on yellow 

### What is actually happening?
1: black on gray
2: red on gray
3: black on gray

**Comment by posva** [comment]
Seems like a browser quirk that was fixed later on:

![Screen Shot 2019-12-27 at 15 11 28](https://user-images.githubusercontent.com/664177/71520207-28febd00-28bb-11ea-907b-45090f338e80.png)

As a workaround, you can use `inheritAttrs: false` and add `v-bind="$attrs"` to the `h3` element

**Comment by dagadbm** [comment]
if i wanted to help on this issue what could I do?

**Comment by jaireina** [comment]
@posva, I was going to fix this but I noticed that this is due to an issue on Codepen.io. If you open the provided pen on Edge and go to the console, you'll see an error in there. If you edit something in the pen, you won't see the changes reflected in the output panel because of that error. 

I grabbed the code and put it in my local as well as on [codesandbox.io](https://codesandbox.io/embed/busy-bardeen-jmewp?fontsize=14&hidenavigation=1&theme=dark) and everything worked just fine on Edge.

Here are some screenshots:
**codesandbox.io**
![image](https://user-images.githubusercontent.com/1864623/75116474-66b76200-562e-11ea-9bc7-45ffc42f15bb.png)

**My local server**
![image](https://user-images.githubusercontent.com/1864623/75116484-88184e00-562e-11ea-9d4a-697035f8e979.png)

**Codepen.io**
![image](https://user-images.githubusercontent.com/1864623/75116501-b26a0b80-562e-11ea-9369-e154da7d3d82.png)

**Comment by posva** [comment]
Thanks a lot for checking that @jaireina
