### ISSUE TITLE
Reactive data is leaking memory

### ISSUE THREAD

**Issue by zoaked** [vuejs/vue#11017]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/wn0v921q/](https://jsfiddle.net/wn0v921q/)

### Steps to reproduce
* Open the reproduction in a browser of your choice (issue confirmed in Firefox, Chrome, and IE 11)
* Open Task Manager on Windows or Activity Monitor on Mac
* Take note of memory usage for your browser
* Click the "Begin" button in the top left corner of the reproduction
* Wait a few seconds while the text appears
* Review memory usage of the browser (mine jumps up by more than 150MB)
* Click the "X" button just below the "Begin" button
* Wait a moment for the text to disappear
* Review memory usage of the browser (mine only dropped by 50MB or so)

### What is expected?
A reasonable amount of memory is used to monitor the data for changes and that memory is released when the data is no longer utilized.

### What is actually happening?
I'm not sure if 150MB is reasonable for 30,000 text nodes to be added to the DOM.  It seems high, but more importantly is that when the items are removed, only 1/3 of the consumed memory is being released.

**Comment by posva** [comment]
The overhead you see may be due to JSfiddle. I tested on an html file and didn't see that much memory consumption. Which is different from a memory leak, which I didn't found either:

![Screen Shot 2020-01-17 at 10 35 17](https://user-images.githubusercontent.com/664177/72601164-3127a680-3915-11ea-86cd-b0a054d77452.png)
