### ISSUE TITLE
factory defined in render causes infinite loop and crash the app

### ISSUE THREAD

**Issue by valq7711** [vuejs/vue#11046]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/valq/j65gfkq4/47/](https://jsfiddle.net/valq/j65gfkq4/47/)

### Steps to reproduce
just comment  `return h(factory_work);`

and  uncomment  `return h(factory_crash);`

### What is expected?
component is mounted and rendered

### What is actually happening?
infinite loop that crashes the app

**Comment by valq7711** [comment]
OK, It doesnt matter where the factory is defined, the problem happens if render return new instance of the factory per call

**Comment by posva** [comment]
This is normal because the render function executes every time the component renders:

- Executes once and start fetching the async component
- Once async component is fetched, it renders again
- A **new factory** function is created and start fetching it
- _recursion_

Having the function declared outside is necessary. It's similar to async component being hold in variables vs being passed directly:

```js
const Async = () => import('@/components/Async.vue)

// ...

render (h) {
  // good!
  return h(Async)
}
```

```js
render (h) {
  // does not work because every render creates a new async component
  return h(() => import('Async'))
}
```

**Comment by valq7711** [comment]
I got it, but I wasted a couple of days. It would be better if there is a few words about this edge case in the doc

**Comment by posva** [comment]
PRs to vuejs/vuejs.org are always welcome!

**Comment by WofWca** [comment]
Duplicate of #9943
