### ISSUE TITLE
False value cause aria boolean attributes to be removed from the DOM

### ISSUE THREAD

**Issue by falcon03** [vuejs/vue#11053]
### Version
2.6.11

### Reproduction link
[https://www.dropbox.com/s/3ltqeent65djedw/problematic-false-aria-values.zip?dl=0](https://www.dropbox.com/s/3ltqeent65djedw/problematic-false-aria-values.zip?dl=0)

### Steps to reproduce
1. Extract the provided zip archive and enter the produced "problematic-false-aria-values" directory.
2. Install dependencies (i.e. `yarn install`).
3. Run the development server (i.e. `yarn serve`) and head to its url with your favorite browser.
4. Inspect the DOM of the page: the `aria-checked` and `aria-expanded` attributes won't be there.
5. Enable the checkbox and/or expand the toggle.
6. Inspect the DOM of the page: this time both `aria-checked` and `aria-expanded` will be there as expected.
7. Disable the checkbox and collapse the toggle.
8. Inspect the DOM of the page: the `aria-checked` and `aria-expanded` attributes won't be there, again.

### What is expected?
Aria attributes should be present in the DOM even if their value is false.

### What is actually happening?
Aria attributes are not present in the DOM when their value is false.

---
Unlike for html 5 boolean values, removing aria attributes from the DOM when their value is false changes the page semantics and degrades its accessibility, causing markup validation issues as well.

**Comment by LinusBorg** [comment]
I didn't check out the repro as i don't have access to dropbox.

But: 

* A value of `false` is the only way to tell Vue to actually remove an attribute - which you may also want to do with an aria-attribute in some situtions.
* `aria-checked`values (like all html attributes) are strings, not boolean values: `'true'` and `'false'`, respectively, so you have to set them as strings:

`v-bind:aria-checked="checked ? 'true' : 'false'"`

I don't think it smakes sense to make aria attributes behave differently than other html attributes.

Also, we need a way to tell Vue *"remove that attribute"*, which is setting it to `false`

**Comment by posva** [comment]
For Aria attributes you have to cast them to string:

```html
<button :aria-pressed="isToggled.toString">
```

This is something I thought about but didn't take the time to make sure that

1. All existing boolean aria attributes take `true` and `false` string values
2. All new aria attributes will follow that rule

If those two points are true, I think it would make for aria attributes on HTML elements to be cast as strings

**Comment by falcon03** [comment]
@posva thanks for providing a code example, this is the workaround I am using right now. However, I think that automatically casting ARIA attribute values to strings makes sense. Regarding your first point I think that the answer is yes (see my previous comment), while the answer to your second point is yes unless W3C suggests different type mappings.

**Comment by LinusBorg** [comment]
> Also, the fact that an ARIA attribute has the false value can mean something different than completely omitting the attribute (think of aria-expanded, just to mention the one I used in the demo).

That's kind of my point: if we cast `false` to `'false'` for these category of attributes, then users have to be aware that to actually remove an aria attribute, they have to set it to `undefined`, whereas for all other attributes, setting it to `false` has the same effect.

But yeah I can see how casting would be helpful in practice. Will reopen just to discuss it further

**Comment by Josh68** [comment]
I was just looking at an older, closed issue on the same topic: https://github.com/vuejs/vue/issues/7422#issuecomment-617272952.

What about just addressing this in the docs? Maybe specifically calling out bindings of `aria-` attributes.

**Comment by jfbrennan** [comment]
This behavior was actually changed in Vue 3, unfortunately (see https://v3.vuejs.org/guide/migration/attribute-coercion.html#overview), and should be immediately reverted.

I came here looking to file an issue because upgrading to v3 broke most of my templates due of this change. I saw this issue was still open, so I'm adding my feedback. 

With Vue 3 it is now a **HUGE** pain for developers to get boolean attributes working correctly as our code now has to reassign completely legitimate `false` values to `null`, which is not only awkward and incorrect programming, but makes for more verbose and ugly code. As much as I love and support Vue, this was a big oversight that needs to be reverted before v3 adoption hits critical mass.

Two use cases to illustrate:
All of my components manage errors using none other than `true` and `false`, which then drives other component and templates logic. That validation logic now has to carefully reassign error states to `null` instead of `false` (or fill templates will explicit false => null conversions, gross!). There's also the dilemma that not all  of these error are used to toggled boolean attributes, so should they all blindly do the null thing, or do all devs need to learn and understand which errors get bound to bool attributes and null those while not nulling others? What was a clean and reliable solution is now messy and error-prone.

I have permissions UI where the permissions come from a data store with permission values stored as `true` and `false`. All the `false` permissions now have to be explicitly reassigned to `null` in order for the UI to be correct. And I have to write more code to convert them back to `false` before passing them over to my storage API. 

This is resulting in some really weird and ugly code. I've never had to do something like this in my 10+ years writing JavaScript.

Non-boolean attributes, in particular those that expect the string `"false"`, should continue to be required to provide a string. Unlike the `false` to `null` dookie that's now required, the `false` to `"false"` is a very easy and clean `false.toString()`. This was never a problem for people who read the docs.

For the sake of Vue's ease-of-use and cleanliness, please consider reverting!

**Comment by posva** [comment]
This is a breaking change improvement so it won't be possible to add to Vue 2 but it's working properly in Vue 3 by automatically casting `false` in `true` and only removing attributes in `null` and `undefined` 🎉 . More info at https://v3.vuejs.org/guide/migration/attribute-coercion.html#enumerated-attributes

**Comment by jfbrennan** [comment]
`<x-foo :boolean-attribute="aBoolean" :attribute-with-false-as-string="aBoolean.toString()">` <-- How it should be.
