### ISSUE TITLE
Mounted legacy function in promise

### ISSUE THREAD

**Issue by Sp3r4z** [vuejs/vue#11062]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/dsboqkn0/1/](https://jsfiddle.net/dsboqkn0/1/)

### Steps to reproduce
Just click on JSfiddle link and see nothing, totally white result window.

Issue seems to be on L10 of JS, when I set "arrow function" on response it doesn't work, when I switch to "legacy function" it works. Even if it seems to work with a "console.log", response doesn't front refresh the "info" variable.

Same test done, with native browser API Fetch, and same issue.

After some tests, it seems that having a "legacy function declaration" in a `.then` promise, doesn't allow/accept to refresh my 'info' variable, even if it populate it (checked with `console.log`)

### What is expected?
Having information

### What is actually happening?
Nothing visible

**Comment by posva** [comment]
This is how JS work with normal functions and arrow functions. They both change the value of `this`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
