### ISSUE TITLE
Why so shitty support?

### ISSUE THREAD

**Issue by BonBonSlick** [vuejs/vue#11095]
I hate to spend 5 minutes to register every time for 1 question on your different forums which will maybe receive an answer in 10 years after it was asked.  

Why so shitty support from the community?
Why you do not use git for issues like everyone who respects their client's time do?

**Comment by smolinari** [comment]
Different forums? There is only one. 

https://forum.vuejs.org/

Register for 5 minutes? It takes literally only 2 clicks to register, if you are a Github user and a minute if otherwise. And, you only have to do it once. 

Shitty support? It's open source dude. Support, if offered at all, is a bonus, not something you can demand. 

Your attitude doesn't belong in open source. Either change it, or your life will be miserable as a developer. 

Scott

**Comment by BonBonSlick** [comment]
@smolinari  

1. If you have to register every time, it counts as different
2. If you do not give a shit about what you do, you should not develop at all
3. 2 clicks? Really? You are a lier.
4. I do not want to link, my git, to some voodoo service
5. You are right about I can not demand, I am asking why it is so shitty and that is a big difference
6. This "open source" has a enough investors and money for support. The are many reasons, a couple of them are: The do not give a fuck, lazy, greedy.

>  _"Why we should spend time and money, let the community solve our issues and we will get money"_
7. My attitude is _open-sourced_ as you love to say  
8. Everyone who lives in this world is miserable, nothing at all, all your and humanity actions, life is nothing if you do not understand such obvious things there is nothing to talk about with you, continue to live in your Happyland and write shit.

**Comment by Justineo** [comment]
I think we have covered enough about the reason behind current issue policy [here](https://new-issue.vuejs.org/?repo=vuejs/vue#why-strict). If project members or everybody else in the community are interested in answering questions in closed issues, they are free to offer help. But I don't think your attitude is worth our help.

BTW. You are not a client. Sorry.
