### ISSUE TITLE
Something weird happening when using computed setter in input binding

### ISSUE THREAD

**Issue by renjithspace** [vuejs/vue#11137]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/Ly3tmeuk/](https://jsfiddle.net/Ly3tmeuk/)

### Steps to reproduce
Find the code from https://jsfiddle.net/Ly3tmeuk/. Please input on the fullName computed property bind field.

### What is expected?
Working properly

### What is actually happening?
Not getting result as expected

**Comment by posva** [comment]
Check the result of the split function in the computed setter and you will understand

---


Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
