### ISSUE TITLE
Attach elements to DOM with event listeners

### ISSUE THREAD

**Issue by goetas** [vuejs/vue#11133]
### Version
2.6.10

### Steps to reproduce
This is more of a support request to be honest but I'm pretty sure to not be the first one having this issue. Sorry for the fake reproduction link.

We are running our acceptance tests using selenium and we have random failures on some tests. 

What we are doing is basically waiting for a button to appear (vue to draw it), and then we click on it.

After spending a lot of time, what  it seems happening is the following:

1. Vue draws a component on the DOM (but did not make in time to attach events yet).
2. Selenium detects the element and clicks on it
3. Nothing happens, the event listener on that button is not triggered since vue did not make in time to attach the event listener.

Adding a small delay (50ms as example) fixes the issue. 

### What is expected?
When vue draws a component, event listeners are already registered

### What is actually happening?
It seems that takes some time for event listeners to be registered 

---
Is there some parameter to tweak vue and to not attach the nodes to the dom without registering event handlers?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by RichardDern** [comment]
My 50 cents: I believe this totally belongs here as I face the same issue and it's easily reproducible by adding a link with a ```v-on:click``` event handler in a component: event is not handled right after component is displayed, only after an unwanted and annoying delay, which is not the expected behavior. 

So either it is a bug report because it could be considered Vue doesn't behave as expected, or attaching events before actually rendering the component **is** actually a feature request.
