### ISSUE TITLE
A visible unwatched input value is changed after mounting a Vue instance

### ISSUE THREAD

**Issue by SgtHoloToaster** [vuejs/vue#11209]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/sgtHoloToaster/qe7sa39k/41/](https://jsfiddle.net/sgtHoloToaster/qe7sa39k/41/)

### Steps to reproduce
Press the 'Press me!' button

### What is expected?
The value of the input #test-input is 'new' after a Vue instance is mounted

### What is actually happening?
The value is changed to 'old'

---
If change the input type to 'hidden' everything is fine

**Comment by posva** [comment]
This is expected because any change in the template triggers the rerender of the whole template, setting again the `value` prop of the `input` element to `old`

Note that `v-model` doesn't work with `hidden`

The problem comes from manually manipulating the DOM. The rule of thumb is: if you need to manually manipulate the DOM, isolate that in a component (that way the rerender won't cause any internal rendering (unless props change) or vice versa: isolate in a component everything else
