### ISSUE TITLE
props are undefined and computed properties error during evaluation

### ISSUE THREAD

**Issue by PrismPrince** [vuejs/vue#11264]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-template-mv0x7](https://codesandbox.io/s/vue-template-mv0x7)

### Steps to reproduce
Computed property on a child component returns error when passing a value as props from parent.

Here's a [screenshot](https://i.imgur.com/KvC0HPN.png) on devtools

### What is expected?
the computed property must evaluate if the prop value is present

### What is actually happening?
the computed property that requires the prop value evaluate even it is not defined yet

**Comment by posva** [comment]
Arrow functions change the value of the context, you need to write this instead:

```js
 computed: {
    name() { return this.artGroup.name }
```

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
