### ISSUE TITLE
Keydown event gets fired in component which was mounted through the key press

### ISSUE THREAD

**Issue by jan-scorl** [vuejs/vue#11265]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/dreamy-austin-2k8u0](https://codesandbox.io/s/dreamy-austin-2k8u0)

### Steps to reproduce
Press any letter on your keyboard.

### What is expected?
I expect the `Hello` component to render.

I don't expect the letter I pressed to appear in the input field.

### What is actually happening?
The letter I pressed appears in the input field.

---
Apparently `keydown` or `keyup` gets triggered in the new component. But I don't understand why.
The letter already appears before you release the key, so it actually must be the `keydown` event.

How can it get triggered in the new component if the button press itself happened before the component was mounted and the input field was focused? It seems like time travelling to me.

I worked around this unexpected behaviour by putting `this.$refs.input.focus();` into a 1ms `setTimeout()` call.

**Comment by posva** [comment]
This is due to changes in `nextTick`. More at  _Important Internal Changes_ at https://github.com/vuejs/vue/releases/tag/v2.6.0 and https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd.

In your specific case you can also call `preventDefault` and `stopPropagation` to stop the event. Make sure to check the target of the event to still trigger it in other places
