### ISSUE TITLE
Form being submitted with <button> tags with type button and submit being toggled alltogether

### ISSUE THREAD

**Issue by NikoGJ** [vuejs/vue#11285]
### Version
2.6.11

### Reproduction link
[https://codepen.io/NikoGJ/pen/OJVeYbQ?editors=1011](https://codepen.io/NikoGJ/pen/OJVeYbQ?editors=1011)

### Steps to reproduce
- Click on Submit button, then on Stop button
- Check the console logs

### What is expected?
When clicking on the stop button, (with the v-if/v-else attributes being present on the html), the console log should display only the following message:
"stop button clicked"

it should not trigger the form submition, as the stop button is just a regular button.

We can test the same, with the v-if/v-else attributes being removed, the 2 buttons are then shown, and the behaviour when clicking on each button is appropriate

### What is actually happening?
When clicking on the stop button, (with the v-if/v-else attributes being present on the html), the console log displays the following messages
"stop button clicked"
"submit on form called"

---
- Sorry for the title not being accurate
- 2 workarounds found to make it work:
  - replacing the &lt;button type="button"&gt; by an &lt;input type="button"&gt; instead
  - or specifying v-on:click.prevent="..." on the &lt;button type="button"&gt; instead of v-on:click="..."
On both workarounds, I do not understand the reason of why it suddently makes it work.

**Comment by posva** [comment]
This is due to changes in `nextTick`. More at  _Important Internal Changes_ at https://github.com/vuejs/vue/releases/tag/v2.6.0 and https://gist.github.com/yyx990803/d1a0eaac052654f93a1ccaab072076dd.

**Comment by Haeresis** [comment]
Hello, I think @posva, I do not understand the way `nextTick` can help us here.

From my understanding, the issue here is due to the fact Vue.js use the same `button` item from DOM to do the render of a `button type="submit"` and the render of `button type="button"` that lead to the issue.

To explain to Vue.js the two buttons should not be the same item in the DOM, the solution is to use the `key` attribute to explicitly indicate it's two distinct elements we need to add/remove in DOM.
— https://vuejs.org/v2/api/#key

This is the codepen to resolve the issue:  https://codepen.io/Haeresis/pen/jOPjgZY?editors=1111

**Comment by posva** [comment]
I forgot to point out about the key as a workaround, thanks for that! `nextTick` is the cause of the problem, not the solution 😉

**Comment by NikoGJ** [comment]
Thanks both of you for your explanations. It all makes sense now ! :)
