### ISSUE TITLE
On iOS 13.4, page will crash if data is too big.

### ISSUE THREAD

**Issue by imzue** [vuejs/vue#11301]
### Version
2.6.11

### Reproduction link
[https://github.com/imzue/vue-for-issue](https://github.com/imzue/vue-for-issue)

### Steps to reproduce
1. Require a big json file (for example, there are 10,000 elements, like `{ "test0": "message1", ... "test10000": "message9990" }`);
2. Assign it to a variable in data;
3. Open the safari on the damn iOS 13.4.1;
4. YOU WILL SEE `a problem repeatedly occurred on "http://192.168.1.100:8080/#/"` OR `"http://192.168.1.100:8080/#/"`重复出现问题

### What is expected?
A normal web page on the damn iOS 13.4.1.

### What is actually happening?
a problem repeatedly occurred on "http://192.168.1.100:8080/#/

**Comment by posva** [comment]
Vue does add a little bit of size to data to be able to observe it but the memory limitation will always be there. You can probably use object freeze and other techniques to make data non reactive and reduce part of the memory usage.

Closing because this is a request for help and should be asked in the forums, discord server or stack overflow
