### ISSUE TITLE
Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by leevscript** [vuejs/vue#11328]
### Version
2.6.10

### Reproduction link
[https://codepen.io/leevscript/pen/gOawPgP](https://codepen.io/leevscript/pen/gOawPgP)

### Steps to reproduce
```
<template>
  <ul>
    <li v-for="num in nums" :key="num">{{num}}</li>
  </ul>
</template>

<script>
  export default {
    data () {
      return {
        nums: [1, 2, 3]
      }
    },
    mounted () {
      this.nums = [2, 2]
    }
  }
</script>
```

### What is expected?
normal

### What is actually happening?
error

---
英文不太好，问题又比较复杂，所以就用中文了，抱歉。
当 oldCh 里的元素跟 newCh 里的元素匹配到且该元素不在 oldCh 的首尾且 newCh 里该元素有多个时，diff 算法会报错。
我知道 key 应该是唯一标识，但我理解这种情况不应该报错，因为很多数据由服务端返回，我们不能保证不会有重复元素。

**Comment by webxmsj** [comment]
key 可以使用索引值 index 啊

**Comment by posva** [comment]
Use the dev version of Vue and you will get an error that describes the problem:

```
[Vue warn]: Duplicate keys detected: '2'. This may cause an update error.
```

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
