### ISSUE TITLE
Stress Test Mode

### ISSUE THREAD

**Issue by adamvleggett** [vuejs/vue#11331]
### What problem does this feature solve?
It would be nice if there were a build of Vue that is designed to destroy and recreate components unnecessarily, perhaps at every render, to stress test code that may be assuming a component will remain alive.

### What does the proposed API look like?
This could be implemented as a separate build of Vue, or as a flag of some kind.

**Comment by adamvleggett** [comment]
I think this may be even more crucial in Vue 3, with its more intelligent vdom.

**Comment by posva** [comment]
I don't think this is a good idea because it would only be able to detect a subpart of performance issues as not every component perf bottleneck would the creation/destroying of it. Resulting in an incomplete solution for stress testing.

Maybe with Vue 3 custom renderers, some specific kind of stress testing could be achieved but I'm not sure about that.

Regardless, this needs further research and details and if you still feel like there is something to dig, you should start an [RFC](https://github.com/vuejs/rfcs/#vue-rfcs) with more information about the performance testing this is aiming to solve, why this is useful, drawbacks, etc

**Comment by adamvleggett** [comment]
@posva the purpose of the stress testing would not be for performance, it would be to expose components that make assumptions about their life cycle that may not be true, and therefore may behave in unexpected ways. This has shown to be an issue in our organization, which writes a large body of code dependent on Vue.

**Comment by posva** [comment]
I see, then maybe it should be some kind of part of test utils? In theory, forcing recreation could be achieved through using a changing `key` but as mentioned, this feature request is way too light and it should follow the RFC process
