### ISSUE TITLE
$attrs makes a lot unRecognized property to child component root html

### ISSUE THREAD

**Issue by wulucxy** [vuejs/vue#11353]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/sleepy-colden-2mzcw?file=/src/components/list-wrapper.vue](https://codesandbox.io/s/sleepy-colden-2mzcw?file=/src/components/list-wrapper.vue)

### Steps to reproduce
1. `grand-parent` pass props to parent component
2. `parent` does't need some props, so we just `proxy` to `children` component(or grand-children)
3. `children` component get the props
4. the `parent` component get a lot unrecognized props to the root Dom Tag, this is annoying

### What is expected?
the `parent` component ignore the unrecognized dom props

### What is actually happening?
the `parent` dom still show the un needable `m1`, `m2`props。

![image](https://user-images.githubusercontent.com/5326403/80456278-e4b22500-895f-11ea-8621-895f0614a857.png)

**Comment by posva** [comment]
This is expected behavior to easily pass undeclared data attributes and events to the root of a component. You can avoid it by using https://vuejs.org/v2/api/#inheritAttrs and/or declaring props.

---

Remember you should use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to quick questions!
