### ISSUE TITLE
String deconstructing produces wrong output in template compiling

### ISSUE THREAD

**Issue by aleissner** [vuejs/vue#11369]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/silly-snowflake-gd586?file=/src/App.vue](https://codesandbox.io/s/silly-snowflake-gd586?file=/src/App.vue)

### Steps to reproduce
Check output

### What is expected?
[...'abc'] should compile to ['a', 'b', 'c']

Example component output should be:
a
b
c

### What is actually happening?
[...'abc'] compiles to ['abc']

Example component output is:
abc

---
If I use the string decontructor in a computed property it will be applied correctly. I have added that into the example component.

**Comment by posva** [comment]
You can just do `v-for="entry in 'abc'"`. It will also avoid creating a new array every time the component renders

**Comment by aleissner** [comment]
That's a very good workaround. But still a work around. Keep in mind that this Bug will also hit you at any other usage of the `[...'abc']` statement anywhere in the template. For example if you were to put it into a prop to pass it into a subcomponent.

Yes, you can always do it differently, maybe even better. But if the compiler doesn't handle this correctly it shouldn't accept it without an error warning.

**Comment by posva** [comment]
I tried it on a jsfiddle and on the template explorer: https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%3E%0A%20%20%20%20%20%20%3Cdiv%20v-for%3D%22entry%20in%20%5B...'abc'%5D%22%3E%7B%7B%20entry%20%7D%7D%2C%3C%2Fdiv%3E%0A%20%20%20%20%20%20%3Cp%3E%7B%7B%20%5B...'abc'%5D%20%7D%7D%3C%2Fp%3E%0A%3C%2Fdiv%3E and the result is correct. The problem does reproduce with a bare project with the CLI, so this is probably coming from vue-loader. Could you open an issue there?

Keep in mind using a spread in the template is in general a bad idea because it's  creating a new array every render
