### ISSUE TITLE
Custom Events do not follow W3 spec

### ISSUE THREAD

**Issue by tamb** [vuejs/vue#11378]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/custom-event-bug-to8qn](https://codesandbox.io/s/custom-event-bug-to8qn)

### Steps to reproduce
Click the Click me button and see that the alert does not fire

### What is expected?
The custom event should fire because it is written as an appropriate DOMString.
A custom event like `hello:world.open` should fire and should be able to be registered.  This is a valid `DOMString`.  This is very helpful to namespace events.  
A possible solution would be `@[delimiter]crazycustomname[delimeter]="()=>alert('hey')"`

### What is actually happening?
no event is firing.  ESLint is throwing this compilation error:
"'v-on' directives don't support the modifier 'event'. (vue/valid-v-on)"

---
Sources:

https://dom.spec.whatwg.org/#customevent

https://dom.spec.whatwg.org/#event

https://heycam.github.io/webidl/#idl-DOMString

https://www.w3.org/TR/DOM-Level-3-Core//core#ID-C74D1578

Strings are fully-normalized:
https://www.w3.org/TR/xml11/#dt-fullnorm

**Comment by posva** [comment]
Vue events are not DOM custom events. When you do `$emit`, you are firing a Vue event. It works differently so please take a look at the docs to see how they work: https://vuejs.org/v2/guide/components-custom-events.html

Concerning the `.event`, that's a modifier for directives in Vue: https://vuejs.org/v2/guide/syntax.html#Modifiers
It has a special meaning and that's why you are seeing the error.

---

Remember we have a [forum](http://forum.vuejs.org/) and a [Discord chat](https://vue-land.js.org/) to ask questions and exchange about topics around Vue!
