### ISSUE TITLE
vue web component not working with openlayers

### ISSUE THREAD

**Issue by bnping** [vuejs/vue#11379]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/bold-matsumoto-tpxsn?file=/src/App.vue](https://codesandbox.io/s/bold-matsumoto-tpxsn?file=/src/App.vue)

### Steps to reproduce
First you can see the link to minimal production that work very well.  
To produce the bug:

- Download the project using or execute npm run build-component. This will run: 
vue-cli-service build  --target wc --name openlayers-vue ./src/components/MapContainer.vue
- Go to dist, then open demo.html. As you can see, openlayer not working any more. 

### What is expected?
I must see the map works in dev mode  and prod mode (web component)

### What is actually happening?
The map is working only in dev mode . Something prevent openalyers from mounting. This is an image in prod mode, the div map is empty.
![image](https://user-images.githubusercontent.com/63243110/81279845-eebade80-9057-11ea-8a6d-5a3f38f93b1f.png)
and this an image  in dev mode, the map div html is not empty.
![image](https://user-images.githubusercontent.com/63243110/81280044-3ccfe200-9058-11ea-8fa4-c267f25004ce.png)

**Comment by posva** [comment]
At this stage, there is too much to take a look. There should be no Openlayer for us to take a look or at least more information regarding the library because the incompatibility could come from the library.
I recommend you to seek for help on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) as well as the Openlayer library first.
Once you have gathered more information, if it's a bug on vue-cli build, you can open an issue at vuejs/vue-cli with a reproduction without Openlayer

**Comment by bnping** [comment]
@posva  the bug is in the vue and not openlayers. beacuse in dev mode everything is work but in prod  no. This is a deep bug and not every one can solve it. Only the people how have a deep inforamtion in dom.  I do not understand why you closed the ticket.
