### ISSUE TITLE
Wrong parent of a component

### ISSUE THREAD

**Issue by dxvladislavvolkov** [vuejs/vue#11377]
### Version
2.6.11

### Reproduction link
[https://github.com/dxvladislavvolkov/vue-issue](https://github.com/dxvladislavvolkov/vue-issue)

### Steps to reproduce
1. Clone repo
2. Run npm i
3. Run npm run serve
4. Open dev-tools and you can see <div id='app'>

### What is expected?
The parent should be another component (my-comp2). Because I wrapped my component.

### What is actually happening?
The parent is topmost component

---
It happens when I use no module approach

**Comment by posva** [comment]
When reporting a bug, please use boiled down reproduction without extraneous dependencies (devextreme?) to ensure the problem comes from Vue. It was also referencing an old version of Vue.

I copied your code over a jsfiddle https://jsfiddle.net/posva/4njob6xh/ and the parent is mycomp2.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by dxvladislavvolkov** [comment]
I fixed the example. To reproduce I create two js files and create my components using extend. Then I import my files to index js and create global components using Vue.component. After it, I get the wrong parent of a component when I wrap my-comp

**Comment by posva** [comment]
By using `  <script src="https://unpkg.com/vue"></script>` you using two builds of Vue. Move the script with `new Vue` code to the index.js file and remove that other script.
