### ISSUE TITLE
Vue.js on the server

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vue#114]
Wouldn't be cool to require vue on node.js and use browserify to reuse viewmodels? :)

**Comment by robertleeplummerjr** [comment]
I was racking my brain thinking of how would be the best way to achieve prerendering, and @yyx990803 your comment on http://prerender.io ... WHAT A WINNER!  In particular their bit on using hashes - found here: https://prerender.io/documentation .  And, no I don't work for them, just building a single page app engine ( https://github.com/Enpowi/Enpowi ).  I'm curious is combining your lib with a routing engine like http://millermedeiros.github.io/crossroads.js/ ideal in your opinion?

**Comment by yyx990803** [comment]
@robertleeplummerjr Vue can pair with pretty much any routing lib, it really depends on which routing lib you like the best ;)

**Comment by robertleeplummerjr** [comment]
*high fives @yyx990803 *
I don't want to brag... but javascript rules.

**Comment by Pines-Cheng** [comment]
before  the SEO problem of  the front side render templates  is perfect solved,I really think server side render is worth to consider by vuejs.

**Comment by fullfs** [comment]
@Pines-Cheng Try this https://github.com/ngsru/vue-server

**Comment by ansarizafar** [comment]
@yyx990803  you mentioned in Vue forum:
Someone came up with a custom pre-rendering solution for Vue which is blazing fast, but it's not open source.

Could you please share the contact details of the person so that we can request him to opensource his custom pre-rendering solution. I want to use Vue but I badly need SSR feature for my next project. SSR is a must have feature, if Vue wants to compete with other frameworks like React, Angular2 and Aurelia.

**Comment by yyx990803** [comment]
@ansarizafar it's already been open sourced: https://github.com/ngsru/vue-server

**Comment by ansarizafar** [comment]
@yyx990803 I have seen this repo before. It doesn't look like a perfect solution. Any chance of an official SSR solution? I have worked with React/Angular2 and recently Aurelia but after playing with Vue I dont want to use any other framewok. I request you to consider working on this feature to make Vue the best framework in 2016.

**Comment by smolinari** [comment]
With my limited knowledge, I'd agree with @ansarizafar. Having a "reworked" version of Vue for SSR is sub-optimal, even though I understand it might not work any other way (except the jsdom way). 

Just throwing out thoughts here, but wouldn't it be possible to go with a hybrid for desktop web applications (which are spidered), where Vue is melded into a standard server rendered application (like what Laravel is doing), and couldn't those components made for the desktop web application also be reusable in a full Vue application (pure client-side rendering), which would be reserved for say, back-end (non-spidered) web applications and mobile apps? 

The key I am sure everyone is looking for is reusability. Doesn't Vue components give us that? Or would components built for a desktop web application not be compatible with a full Vue web application?

Scott

**Comment by fullfs** [comment]
@ansarizafar @smolinari Hello! Well yeah guys, you're absolutely right. 
Many of us want Vue.js to be SSR, want it to be official, perfect and etc. I'm also one of those who asked @yyx990803 for this.
It may look easy, but it's not. It's a hell of a work to make it this way. Also remember Vue.js doesn't have a team of developers working for salary like React. It's @yyx990803 alone (well not quite, but still) who's developing all the stuff.
I've made Vue-server.js because I understood that. I wanted to help, but I've also felt like I'm not that skilled to help developing Vue.js itself, but I think its still something.
I there any help you guys could provide in the direction?

P.S. Vue-server.js. is not perfect, it has restrictions and etc, but still... it's being used at production already. You can even get a perfect isomorphic app if you get used to it and understand the way it works. I'm also ready to ask any related queston.

**Comment by smolinari** [comment]
No disrespect to your work meant at all on my part @fullfs. I hope that is understood. :smile: 

In fact, I can appreciate the effort you've made a lot.

It's just that two parallel projects with similar goals (although Vue doesn't have the SSR goal) is wasted effort and practically useless from a "userland dev's" perspective. That is, from what I understand, you've rewritten parts of Vue to make it also work server-side. Please correct me if I am wrong.

If I am correct and your project were to be a module or plugin that just ties into Vue or works with Vue, that would make it much more attractive. Does that make sense?

Scott

**Comment by fullfs** [comment]
@smolinari Yeah, I understand you mean now offence, its just I feel for @yyx990803. I mean he's already doing insanely great job. And I get a bit emotional about it.

About Vue-server.js you're right. Its just independent module that shares some part of code with Vue.js and probably it has no future, I'm also okay with it.
It was made for a single practical purpose: we needed SSR at our project while using Vue.js. We've already reached the goal. Open sourcing it was just a bonus.
I also hope some day Vue.js will support SSR nativly, but until then, if you really need SSR while using Vue.js - Vue-server.js will help you.

**Comment by lichenhao** [comment]
How about list all the stable spec and all the developers force on that, so we can write some engine like VUE-LLVM for node translate.

**Comment by smolinari** [comment]
Not sure you all know this, but the plan is to have SSR capability built into Vue.js 2.0. :smile:

https://github.com/vuejs/vue/issues/2873

Scott
