### ISSUE TITLE
The isNative function not 100% reliable

### ISSUE THREAD

**Issue by rluvaton** [vuejs/vue#11400]
### Version
2.6.11

### Reproduction link
[https://codepen.io/raz-luvaton/pen/mdeQqKN](https://codepen.io/raz-luvaton/pen/mdeQqKN)

### Steps to reproduce
```js
isNative(isNative) // Return true
```

### What is expected?
expected to return false (function is not native)

### What is actually happening?
thinking that the function is native (returning true)

---
While reading this article - [5 JavaScript Tips I Learned From Vue Source Code - Medium](https://levelup.gitconnected.com/5-javascript-tips-i-learned-from-vue-source-code-6095df4e9bc1) I've noticed that flaw

the code is from
https://github.com/vuejs/vue/blob/a9a303009a4267b7f12b956741b4e34dfdc6566f/src/core/util/env.js#L58-L60

**Comment by posva** [comment]
So what is the bug you are trying to fix? You are not describing the case you are trying to fix. do you have a reproduction using Vue? `isNative` is never called by the user, so it doesn't make sense to directly pass something to it unless it can be passed by using Vue

**Comment by rluvaton** [comment]
The bug is that if you run
```js
isNative(isNative);
```
it returns `true` while it shouldn't

**Comment by posva** [comment]
no, that's not a bug because `isNative` is not called with `isNative`. That's why I asked you for a reproduction with Vue code

**Comment by rluvaton** [comment]
There is no way (I think) this should happen with Vue code, but if there is a function that has the words `native code` in it, it gonna think it's a native function

**Comment by rluvaton** [comment]
In example this code (which means absolutely nothing): 
```js
function fn() {
    // calls a native code
    Array.isArray([])
}
isNative(fn) // will return true
```

**Comment by Justineo** [comment]
I checked [all current usages](https://github.com/vuejs/vue/search?q=isNative) of the `isNative` function in Vue and none of them should cause any problems IMO. It's used to check whether the environment has any `Promise`/`Set`/`Proxy` implementation and will only be bypassed if user provide some environment with custom `Promise`/`Set`/`Proxy` implementation with any `native code` string in their function bodies. If there is any, that should be probably polyfills checking native support (imagine we may also have a `native code` check inside a `Promise` polyfill). Though technically by only checking the appearance of `native code` is not 100% correct, I don't think it make much sense to change it because there's little actual benefits but the [proposed change](https://github.com/vuejs/vue/pull/11401) is much harder to maintain.

Still, thank you for your suggestion anyway!
