### ISSUE TITLE
Transition group is not working in <iframe>

### ISSUE THREAD

**Issue by ozgurrgul** [vuejs/vue#11407]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/78ucsog3/](https://jsfiddle.net/78ucsog3/)

### Steps to reproduce
I've created a reproduction of the issue. Basically, transition animations are not working in the iframe. I have a case where I need the render vue components in the iframe, it works great, but animations are not working.

- I copied the example List transitions from https://vuejs.org/v2/guide/transitions.html#List-Entering-Leaving-Transitions
- Wrapped it in custom <i-iframe> component.
- Transitions are not triggering. I also injected css transition classes to the iframe but still no luck. 

### What is expected?
Transition animation should trigger in the iframe

### What is actually happening?
Transition animation is not triggering in the iframe

**Comment by posva** [comment]
You need to add the CSS to the iframe's document and it will work.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by ozgurrgul** [comment]
It worked well as yo said. I corrected it in the fiddle in case someone needs : https://jsfiddle.net/L0srtdxe/61/
