### ISSUE TITLE
parent component rewrites the domlisteners in child component doesnt work until update the child

### ISSUE THREAD

**Issue by xuqingxi** [vuejs/vue#11415]
### Version
2.6.10

### Reproduction link
[https://codepen.io/xuqingxi/pen/gOaNaxm?editors=1111](https://codepen.io/xuqingxi/pen/gOaNaxm?editors=1111)

### Steps to reproduce
HIT the button can see the logs no change ,cancel the comment row " this.bb='B' ",it can work

### What is expected?
update the eventlistener the dom has binded

### What is actually happening?
it doesnt

---
this maybe a bug,when use the thirdpart modules,i want rewrite its event because it doesnt apply the api

**Comment by posva** [comment]
You shouldn't change the existing methods of the component, they are not reactive, so it's normal the template doesn't update but you can call `$forceUpdate` on the component you want to update. I would instead have a function attached in data and set that instead of a method to make it work since data is reactive:

```js
  data(){
    return {
      bb:'A',
       clickA(){
      // change to invoke the updateDomListeners();
      // this.bb="B"; 
      console.log('2222');
    }
    }
```

**Comment by xuqingxi** [comment]
@posva thanks,this is real a good solution to me
