### ISSUE TITLE
Should add try-catch block on setProp methods

### ISSUE THREAD

**Issue by zl7261** [vuejs/vue#11423]
### Version
2.6.11

### Reproduction link
[https://github.com/zl7261/vue-set-prop/blob/master/index.html](https://github.com/zl7261/vue-set-prop/blob/master/index.html)

### Steps to reproduce
Click 'switch color' button

### What is expected?
switch color by every click

### What is actually happening?
works once, then get an error on ie11

---
```javascript
 document.querySelector('#test').style['height']='calc(100% - 0)' 
```

causing an error on ie11

Should setProp function better with try-catch block and throw error info?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---


Your code is working fine. Make sure to check the console because you are modifying prop and as the error suggests, you shouldn't do that
