### ISSUE TITLE
Input value gets out-of-sync (using v-model or :value binding) when input is a dynamic component

### ISSUE THREAD

**Issue by bnjm** [vuejs/vue#11457]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/flamboyant-kowalevski-2sxo0?file=/src/App.vue](https://codesandbox.io/s/flamboyant-kowalevski-2sxo0?file=/src/App.vue)

### Steps to reproduce
Edit the values in the 3 inputs under the "dynamic inputs" header.

### What is expected?
The inputs should always be in sync with the value `syncTextA` 

### What is actually happening?
After an input is edited, it no longer stays in sync with `syncTextA` 

---
The inputs under the "normal inputs" header behave as expected, it seems this is only an issue with dynamic inputs defined like  `<component is="input" />`.

**Comment by posva** [comment]
This is due to the generated `$attrs` being a `:value="value"` instead of `:value.prop="value"`.
See https://github.com/vuejs/vue/issues/10444#issuecomment-525283331 and https://github.com/vuejs/vue/issues/4763#issuecomment-274345379 regarding using a dynamic component with v-model for a native element.

If you use `<component is="input" :value.prop="value" @input="$emit('input', $event.target.value)" />`, you will see a normal behavior. It works with a regular input because it internally does apply the `.prop` modifier
