### ISSUE TITLE
<input> with v-model does not strictly maintain the model's value

### ISSUE THREAD

**Issue by andrezsanchez** [vuejs/vue#11524]
### Version
2.6.11

### Reproduction link
[https://codepen.io/andrezsanchez/pen/GRoYKoR](https://codepen.io/andrezsanchez/pen/GRoYKoR)

### Steps to reproduce
Select the input and type anything.

### What is expected?
The text in the input should not change.

### What is actually happening?
The text in the input changes.

---
See an equivalent example in React to understand the expected behavior:
https://codepen.io/andrezsanchez/pen/dyGgdLy

**Comment by posva** [comment]
This is intended in Vue because the templates does not render again so the value on the input is not forced. This makes things more consistent among browsers which can move the cursor differently and enable other use cases. You can still force it manually if needed by setting the input's value html attribute or calling `this.$forceUpdate()` inside of the setter
