### ISSUE TITLE
SSR rendered component has no attributed updated but does have content updated

### ISSUE THREAD

**Issue by xgrn** [vuejs/vue#11536]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/hvqctx21/](https://jsfiddle.net/hvqctx21/)

### Steps to reproduce
Run the fiddle. It emulates a case when the server side rendered component doesn't match the browser render result.

### What is expected?
The "I'm red" text should be red indeed. Also it's wrapper should have the 'some-attr' attribute.

### What is actually happening?
The "I'm red" text has the server side rendered class 'blue'. Also the 'some-attr' is absent.

---
Any update action turn the things right. E.g. if you click the "I'm red" text the adjacent 'span' is updated but the whole component wrapper also gets the correct attributes.

Also (and this is a workaround) it works fine if the SSR provides any other block type. E.g. 
```
<span class="blue"></span>
```
 In this case the 'span' is properly replaced by the 'div' with suitable attributes.

Sorry for possible duplicate: tried to search the same case but no result. 

We use Vue 2.6.6 on our production but the behavior is the same for 2.6.11 in the Jsfiddle. For some reason if I use the Jsfiddle Vue boilerplate template it works as expected.

Unfortunately we can't provide the matching content form SSR: it's created by a 3rd-party library which doesn't support SSR yet.

**Comment by posva** [comment]
It sounds like the problem comes from having an SSR mismatch. The client should mount the same HTML as the one returned by the server. In your demo they both should have the same class and attributes.
If you can't fully render on SSR, make sure to delay the rendering client side after the initial mount so that the initial mount generates the same HTML as your server side rendered HTML

If you think this is still coming from Vue, you should provide a boiled down reproduction like the one at https://github.com/vuejs/vue/issues/11533
