### ISSUE TITLE
Rerender will not be triggered when listening on a element which gets replaced

### ISSUE THREAD

**Issue by JanDevDE** [vuejs/vue#11694]
### Version
2.6.11

### Reproduction link
[https://jsfiddle.net/gbpm5y3k/4/](https://jsfiddle.net/gbpm5y3k/4/)

### Steps to reproduce
Just click on "click me" and see that the view is not getting updated

### What is expected?
View should get updated. At least with Vue.set 

### What is actually happening?
View is not getting updated

**Comment by posva** [comment]
You have to use `mapState` to keep the reactivity (https://vuex.vuejs.org/guide/state.html#the-mapstate-helper)

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by JanDevDE** [comment]
@posva Yea, I've been using that instead, but as you can see in the linked documentation there is no mention of the fact that the reactivity is being lost. I think that should definitely be mentioned, especially for newcomers to Vue/Vuex like me.
Or is it just me who feels like that?

**Comment by JanDevDE** [comment]
And if you feel really kindly today, could you explain to me in which case I have to use mapState? Only when I reassign and listen to root level objects? :)
