### ISSUE TITLE
Computed fields for named slots stop working if I add watchers to them

### ISSUE THREAD

**Issue by awulkan** [vuejs/vue#11713]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/serene-thunder-0hxw2?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/serene-thunder-0hxw2?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1. Click the buttons to see that the computed fields work.
2. Uncomment the watcher.
3. Click buttons again and notice that computed fields don't work, and the watcher is never triggered.

### What is expected?
Computed fields work and watcher is triggered.

### What is actually happening?
Computed fields don't work and watcher is never triggered.

### Code
App.vue
```vue
<template>
  <div id="app">
    <button @click="slotOneActive = !slotOneActive">toggle slot</button>

    <HelloWorld>
      <template v-slot:one>
        <span v-if="slotOneActive">I am active</span>
      </template>
    </HelloWorld>
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld";

export default {
  name: "App",
  components: {
    HelloWorld,
  },
  data() {
    return {
      slotOneActive: true,
    };
  },
};
</script>

<style>
#app {
  text-align: center;
  margin-top: 60px;
}
</style>
```
HelloWorld.vue
```vue
<template>
  <div>
    <slot name="one" />
    <p><strong>computedSlotValue:</strong> {{ computedSlotValue }}</p>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  computed: {
    computedSlotValue() {
      return !!this.$slots.one;
    },
  },
  // watch: {
  //   computedSlotValue() {
  //     console.log("watch triggered");
  //   },
  // },
};
</script>
```

Edit: I updated the code example to make it easier.

**Comment by xiaoyao316** [comment]
https://vuejs.org/v2/guide/computed.html#Computed-Setter

**Comment by awulkan** [comment]
@xiaoyao316 Thanks for the help, I did not know about committed setters. Wouldn't it be considered bad practice in this case though? In the code above I just do a console.log(), but in reality the point was to trigger other methods, which means its sole purpose is to perform side effects.

I wonder how that will work with this ESLint rule: https://eslint.vuejs.org/rules/no-side-effects-in-computed-properties.html

I'll try out your code when I get back to work next week.

**Comment by jacekkarczmarczyk** [comment]
This rule refers only to getters, not setters @awulkan

**Comment by xincept** [comment]
@awulkan I also think it's a bug. in your code, with watch options, it run like:
1. init computedSlotValue
 add a lazy watcher①, `dirty` is `true` 
2. add custom watcher② for computedSlotValue 
in this step, this watcher② is not lazy, so the getter of `computedSlotValue` is called, watcher①‘s `dirty` is set to be `false`, since `this.$slots` has not be inited (slot is initing in mount func), so no deps is collected for watcher①
3. mount components
`this.$slot` is inited. the getter of `computedSlotValue` is called again. since watcher①‘s `dirty` is  `false`, cached value is used. so, there is still no deps is collected for watcher①
4. click toggle button, slotOneActive changed, but watcher① has not depends, so `computedSlotValue` can't compute again
