### ISSUE TITLE
Vuejs integrated with AEM through CDN is blank on IE11 

### ISSUE THREAD

**Issue by Epsilon-Rashmi** [vuejs/vue#11710]
### Version
2.6.11

### Reproduction link
[http://10.226.185.144:4502/](http://10.226.185.144:4502/)

### Steps to reproduce
Integrated with AEM Sightly template
 <script type="text/x-template" id="loader-template" data-sly-include="partials/loading-screen.html"></script>

Vuejs is included through <script> tag and initialised as below
new Vue({})
Vue.component('centerCard', {});

### What is expected?
To render the vue component on IE11

### What is actually happening?
The page which has the Vue component is blank on IE11

---
This component is  in our internal development environment running on internal network. Hence the url shared would no work

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

In order to report a bug we need a boiled down reproduction that we can test. BTW, avoid using acronyms like AEM without context because people will not know what it is
