### ISSUE TITLE
defineAsyncComponent

### ISSUE THREAD

**Issue by 4uva4ok1905** [vuejs/vue#11742]
### What problem does this feature solve?
    setup() {
    let component = shallowRef({});

    const { visibly, component: componentName, hideModal } = useModal();

    watch(
      () => componentName.value,
      componentName => {
        if (!componentName) return;

        component.value = defineAsyncComponent({
          loader: () => import(`@/components/modals/modal/${componentName}`),
          loadingComponent: LoadingModal,
          errorComponent: ErrorModal,
          delay: 50000000000
        });
      }
    );

    const escapeHandler = e => {
      if (e.key === `Escape` && visibly) {
        hideModal();
      }
    };

    onMounted(() => document.addEventListener("keydown", escapeHandler));
    onUnmounted(() => document.removeEventListener("keydown", escapeHandler));

    return { component, visibly, hideModal };
    }

### What does the proposed API look like?
delay not working

**Comment by LinusBorg** [comment]
1. this is the Vue 2 repository. the Vue 3 repository lives at https://github.com/vuejs/vue-next until we have released stable versions of all support libs
2. Your issue is missing a runnable reproduction and lacks any understandable description of the issue.

Open a new issue with a runnable reproduction in the vue-next repo please.
