### ISSUE TITLE
about function sameVnode

### ISSUE THREAD

**Issue by pndllxzzy** [vuejs/vue#11802]
### What problem does this feature solve?
sameVnode对emptyVNode和AsyncPlaceholder VNode进行区分

### What does the proposed API look like?
VNodeA: v-if="false"产生的emptyVNode
VNodeB: asyncComponentB在resolve前产生的AsyncPlaceholder
VNodeC: asyncComponentC在resolve前产生的AsyncPlaceholder

sameVnode(VNodeA, VNodeB) 返回的是true
sameVnode(VNodeB, VNodeC) 返回的是true

返回true的话容易导致一些错误，期望sameVnode以上情况返回false

**Comment by Justineo** [comment]
It seems that you are reporting a bug instead of making a feature request.

To report a bug you should provide a minimal reproduction to demonstrate what userland code would cause the unexpected behavior and how it affects application logic. 

Ps. To follow the template doesn't mean to adding those heading texts in your issue, but providing essential information of the problem you are describing. I believe this is already described in detail in our issue helper so please do read it.

Thank you.
