### ISSUE TITLE
"watch" always listen for an unchanged array !

### ISSUE THREAD

**Issue by gh-xiaoxiao** [vuejs/vue#11812]
### Version
2.6.11

### Reproduction link
[https://codepen.io/gh-xiaoxiao/pen/ExgyewZ](https://codepen.io/gh-xiaoxiao/pen/ExgyewZ)

### Steps to reproduce
Enter text1 or text2, and then view the print information

### What is expected?
Print "form.text1" or "form.text2" only

### What is actually happening?
"form.arr" is also printed out

**Comment by posva** [comment]
It's because you are emitting a copy of the whole object and setting the whole form, and `form.arr` is triggering because `form` changed to a new object whereas the other ones are primitives and only triggering if the actual value changes


---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
