### ISSUE TITLE
In 2.6.12 too, the vm's $off can not remove callback defined in vm's methods

### ISSUE THREAD

**Issue by huang-weijian** [vuejs/vue#11891]
### Version
2.5.21

### Reproduction link
[https://github.com/huang-weijian/vue--off](https://github.com/huang-weijian/vue--off)

### Steps to reproduce
vue source code:
// cb.fn is undefined
if (cb === fn || cb.fn === fn) {
    cbs.splice(i$1, 1);
    break
}
In fact:
In vm._events[eventName][fn defined in vm's methods], There is no fn attribute, only fns attribute

### What is expected?
can remove cb defined vm'methods

### What is actually happening?
can not

**Comment by posva** [comment]
`vm.$off` is to remove event listeners added with `$on` https://vuejs.org/v2/api/#vm-on

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
