### ISSUE TITLE
Hello! Does vim have nodejs vue smart (such as: coc-html) code completion

### ISSUE THREAD

**Issue by jclivi** [vuejs/vue#11895]
### What problem does this feature solve?
such as: coc-html

### What does the proposed API look like?
vim Plugin

**Comment by LinusBorg** [comment]
Hello 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
