### ISSUE TITLE
Any roadmap for 2021？

### ISSUE THREAD

**Issue by laoboxie** [vuejs/vue#11927]
### What problem does this feature solve?
Hello vue,

I have three questions related to Vue's roadmap:
1. The latest progress of vue3 IE11 compat build and the approximate release time.
2. The latest progress of vue 2.7 and the approximate release time.
3. The latest progress of 2.x -> 3.0 Migration build and the approximate release time.

I hope that the official vue will update the roadmap for 2020 and release the roadmap for 2021 to help developers:
1. Understand the current progress of vue and future plans
2. Better promote vue3 in the company and use vue3 in the production environment

Thanks

### What does the proposed API look like?
-

**Comment by smolinari** [comment]
> The latest progress of vue3 IE11 compat build and the approximate release time.

@laoboxie - I know I'm hijacking your thread, and I apologize up front for that, but I feel Vue should put a line in the sand for IE11 support at Vue 2. With today's "modern" JavaScript, there should really be no more effort wasted on IE11. Microsoft is also stopping support of IE11, and even their legacy Edge version, in their online properties this year (i.e. Office 365, Outlook, OneDrive, etc.). And, they've got legacy IE11 support built into the new chrome based Edge. Even Microsoft wants their customers off of IE11, because putting effort into IE11 compatibility within web apps/ sites is going to end up wasted effort relatively soon. 

Scott

**Comment by posva** [comment]
https://blog.vuejs.org/posts/hello-2021.html

**Comment by laoboxie** [comment]
> https://blog.vuejs.org/posts/hello-2021.html

thank you very much, it helps a lot.

**Comment by laoboxie** [comment]
> > The latest progress of vue3 IE11 compat build and the approximate release time.
> 
> @laoboxie - I know I'm hijacking your thread, and I apologize up front for that, but I feel Vue should put a line in the sand for IE11 support at Vue 2. With today's "modern" JavaScript, there should really be no more effort wasted on IE11. Microsoft is also stopping support of IE11, and even their legacy Edge version, in their online properties this year (i.e. Office 365, Outlook, OneDrive, etc.). And, they've got legacy IE11 support built into the new chrome based Edge. Even Microsoft wants their customers off of IE11, because putting effort into IE11 compatibility within web apps/ sites is going to end up wasted effort relatively soon.
> 
> Scott

thank you for your comment first.
I agree that IE11 should be abandoned. But, 
1. I can’t decide to give up IE compatibility in the company’s products
2. IE11 compat build is in 2020 Vue's roadmap, and I need to konw the process of it

**Comment by jacekkarczmarczyk** [comment]
@laoboxie you may also want to see the Evan's talk from few days ago
