### ISSUE TITLE
clear data from heap

### ISSUE THREAD

**Issue by vadimt2** [vuejs/vue#11955]
### Version
2.6.11

### Steps to reproduce

 * Issue - When i click on one of the listed projects it's routing to project and showing structuresTree data of 168mb, then data become to be 2GB
 *When i'm going back to projects my heap stay 2GB, I'm working with large data so when i'm going back to projects i need to clear the JavaScript VM Instance.

I have 2 routes (Porjects - show all the projects list, Project - show project details and structure) Inside **project** i have:
```
computed: {
    ...mapGetters("structures", ["allStructuresTree"]),
  },
created() {
      // simple actions that return axios.get API call ....
    this.$store
        .dispatch("structures/getStructureItemTree", 1223)
        .then(({ data, status }: { data: any; status: number }) => {
          debugger
          this.$store.commit("structures/setStrItemTree", data);

          // for some reason data become to be 2GB, If you know why i will appreciate your answer
        });
  },
beforeDestroy() {
    this .$store.commit("structures/setStrItemTree", []);
    this.$store._vm.$destroy();
}
```

What have i tried to clear the JavaScript VM Instance:
```
beforeDestroy() {
    this .$store.commit("structures/setStrItemTree", []);
    this.$store._vm.$destroy();
}
```
and it didn't work and JavaScript VM Instance showing: 2GB

This my state:
```
    state: {
        structuresTree: [],
    },
    mutations: {
        setStrItemTree: (state, structuresTree) => (state.structuresTree = structuresTree),
    },
```
[Projects](https://ibb.co/DMtFjmQ)

[Project](https://ibb.co/smWCx1c)

[Back to Project
](https://ibb.co/jwKrzz6)
VM Heap is still 2gb

[When going to project again](https://ibb.co/KzYHyyd)

### What is expected?
Clear the JavaScript VM Instance.

### What is actually happening?
It didn't work and JavaScript VM Instance showing: 2GB

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This is a support question on how to reduce the memory usage of your app.

**Comment by vadimt2** [comment]
This is a bug in vue js!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by LinusBorg** [comment]
> This is a bug in vue js!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Making data reactive (which happens to store state) has an overhead. Wether or not that's the (only) reason for your issues is not for us to judge as there's no reproduction for us to analyze.

If still think this is a bug, then provide a reproduction we can analyze. Screenshots don't allow us to do that. We have issue guidelines for a reason.

**Comment by vadimt2** [comment]
Please check this code and fallow the instruction that is in app.vue.
```
https://codesandbox.io/s/gallant-ritchie-d0wn3?file=/src/App.vue
```
Please download this json to your local machine and fetch it with axios.
[https://num1.co.ilhttp://num1.co.il/fetchdata/data.json](https://num1.co.ilhttp://num1.co.il/fetchdata/data.json)
Then open your devtools inspector and you will see that heap size will be 2GB
after the line
```
  data() {
    return {
      data: [],
    };
```
Here:
```
    axios.get("json").then(({ data }) => {
      // Will be 2GB instead of 168mb
      // Check the heap with inspector.
      // - if you will call axios from another component and then you will
      // destroy the component, you will see that your heap is 2GB
      this.data = data; // -> **After this line**
      // Will be 168 mb
      //this.howItShouldBeData = data
    });
```

**Comment by Soresu** [comment]
I think both of you (@LinusBorg, @posva) misunderstood the problem. I have the same issue. When a component created and destroyed, it stays in the memory with all of its data. If you create a list compnent, fill it with 10000 item, then destroy it, the 10000 item will stay in the memory until you recreate the same component in the same place (then it will be rewritten).

[Check this example.](https://jsfiddle.net/Szgtafz/r4Lkfy3m/) Sorry for the code, I'm trying to find a workaround, it is a mess.

1. Initially it use around 6MB.
2. Click Show/Hide button. It will show two "todo-container" with its first 10 items. It has two inner component, each has one computed property, which process the items. Now the memory usage 245MB.
3. Click Show/Hide button again. Now, the components are disappeared. The memory should shrink to 6MB, but it stays 245MB. The generated items are visible in the memory.
![image](https://user-images.githubusercontent.com/9396091/111032361-12834980-840c-11eb-93b1-17ad0d16fa9d.png)

If the lists are visible and you click the Recreate button severel times, the memory usage will add up to some GB, but it will automatically shrink to 245MB.

The only workaround I found is directly clear the data from the parent before the child component is disappeared (hide, modal close, routerLeave events, and "this.$refs.list.data = []"). Using the list component's beforeDestroy doesnt work. 

In our project, we have hundrends of components which handle around some megabytes data. Not so much, but since it is a single page app, it is adding up above 500MB (It should be around 20MB). It happens in production version too, without devtool and vuex.

**Comment by LinusBorg** [comment]
@Soresu I don't actually think that's what OP mean. His issue is with the overhead reactivity, from the looks of it.

Yours is with memory not being freed. However, looking at your example, that's not really a problem of Vue - the browser simply chose not to actually free the memory up until that point.

You can go to your devtools' "Memory" tab, and after hiding todos again, click "collect garbage" in the upper left (the small trashcan icon). This forces the browser to actually do its garbage collection, which it normally does when it feels like it, so to speak. You can't really force a garbage collection through some browser API from your code.

After clicking the button, you will see the memory dropping to the expected number, for me it's 4.9 MB.

That shows that Vue itself isn't holding on to that data anymore, it has no references to it - otherwise it could not be garbage collected. It's the browser that hasn't gotten around to collect the memory yet.

**Comment by LinusBorg** [comment]
@vadimt2 As I said: Making data reactive has a significant memory overhead, especially in dev. I you work with datasets this large - don't make them reactive. The workaround you found yourself (using a non-data property) is one of those. Using `Object.freeze()` can be another.

**Comment by Soresu** [comment]
@LinusBorg Ah, I saw his question on other platforms, where the example was similar to mine.
For me, It isn't freed even clicking the collect garbage button or waiting for minutes (Chrome 89.0.4389.82). I've tried that.

**Comment by LinusBorg** [comment]
It works well for me in Chrome 89 as well, as well as in MS Edge. Have you tried incognito mode to see if some extension is messing up something?

**Comment by vadimt2** [comment]
The first issue is:
1. When you receive large data of 168 Mb, and then you store data inside data() { return { array } } when you do array = dataFromApi - **Memory increase to 2 GB**.
2.  **If you are using VUEX in Vue js 2 - You will have the same issue and you can't use the way around - data outside of data() {return ....} ... and i'm using vuex so for me it's a big issue.**
3.  When you destroy the component and make vuex property list to [] on ondestroy() method it still stay on the heap.
**I had to switch to Vue js 3 and this it was my way around and it wasn't simple - this issue not existing in vue 3**

**Comment by LinusBorg** [comment]
I have to ask you: 

1. Did you actually verify that the problem is the same for `data:` as it is for Vuex? The repro you provided seems incomplete, as it says:

> //if you will call axios from another component and then you will
> // destroy the component, you will see that your heap is 2GB

* If you verified that for this example why no make the demo show that? Now you are forcing me to try and come up with what you maybe did or didn't do.

2. do you use strict mode in Vuex? In strict mode, *all* of the state is watched deeply, which means for each object, additional watchers are created, meaning: additional reactivity overhead compared to local reactive state, and: more memory. This can be particularly troublesome for big data sets.

3. You can prevent data from being made reactive, as I mentioned above. This means it will stay performant, but you have to come up with alterantive ways to trigger render updates. Usually not necessary but an escape hatch that does exist for extreme scenarios like yours. Unfortunately its not well documented, I freely admit.

4. Yes, Vue 3 doesn't have a similar overhead as its ne Reactivity system is much slimer
>

**Comment by Soresu** [comment]
@LinusBorg Indeed, it works fine in inkognito mode. However, in my bigger project with SFC and webpack, It can still stuck. Using my previous example because it has similar structure, "todo-container" gets the list from the server, and save it with Object.freeze. when the comonent is destroyed, it does not free up. Even if I stop using/passing around the "list" property from data to other components (its unused). 

So it seems like something in my code globally blocks it from GC, but I do not found it yet.

**Comment by vadimt2** [comment]
@LinusBorg 
```
So I haven't bothered running it.
```
Ok let me start over again about the issue.

Issue: When you are fetching data with 168MB after this line
```
this.data = data;
```
It's jumping to 2GB.

**You don't need any button, no Destroy method, just to fetch data from json that i have provided and see how the heap  is jumping from 168 to 2GB and this is it.**

If this is ok that data jumping from 168 mb to 2GB when you are fetching data to object that is in
```
  data() {
    return {
      data: [],
    };
  },
```

So there is no bug.

**Comment by LinusBorg** [comment]
I understand you think you said all there is necessary to say/show.

Please consider though, that we very, very often get issues where people think like this, and it turns out, they were wrong. We get "bugs" are are no bugs. bugs that miss vital information. Bugs that turn out to be bugs in the user's code, 

Speaking generally, we can't afford to waste a lot of time on such issues, and therefore we request to find a certain base level of preparation in *all* reported issues, to make use of our limited time and resources as efficient as possible.

> just to fetch data from json that i have provided and see how the heap is jumping from 168 to 2GB and this is it.

Link a repo that does just that after `npm install & npm serve` and I'm happy to look at it. If you find that to be too much of a bother for your to do, then we can both stop here and work on other things.
