### ISSUE TITLE
unreachable code after return statement - vuejs.2.6.11.js:3:24

### ISSUE THREAD

**Issue by iansebryk** [vuejs/vue#11952]
### Version
2.6.11

### Reproduction link
[https://jsbin.com/mijahor/edit?html,js,console](https://jsbin.com/mijahor/edit?html,js,console)

### Steps to reproduce
download copy and simply add it with a `<link>` tag.  error shows up immediately on load.

### What is expected?
there should be no error from the vuejs library.

### What is actually happening?
have no idea.  line 3 is still in the comment header.

---
while it doesn't seem to stop anything from running, it is irritating to have it as a Warning in the console that never goes away.  this was an issue some time back, and it appears to have come back.

**Comment by posva** [comment]
This is ont a Vue.js problem and there is nothing we can do in core.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by iansebryk** [comment]
not sure how this _isn't_ a Vue problem.  nothing else throws this error.  and by itself, with nothing else in the DOM, it barfs out this warning.  the forums have nothing on this.
