### ISSUE TITLE
[Vue warn]: Do not use built-in or reserved HTML elements as component id: rt

### ISSUE THREAD

**Issue by xon52** [vuejs/vue#11985]
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/runtime-water-6pxgx](https://codesandbox.io/s/runtime-water-6pxgx)

### Steps to reproduce
Using a relatively standard vue-cli build, the minification script replaces variable names with letters in ascending order. These eventually run into such letters such as "Rt" and in certain build combinations end up conflicting with Vue's reserved HTML element names.
As I'm building a library, this Vue error is visible to everyone who wants to use the library, even if it's just a package.

### What is expected?
No errors for standard builds.

### What is actually happening?
**[Vue warn]: Do not use built-in or reserved HTML elements as component id: rt**

From: ![Screenshot](https://i.imgur.com/cxh1m4x.png)

**Comment by posva** [comment]
The issue is with the build/minification process of x5-gmaps not with Vue. You can copy existing configs that work like https://github.com/posva/pinia/blob/v2/rollup.config.js or https://github.com/vuejs/vue-router-next/blob/master/rollup.config.js

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
