### ISSUE TITLE
throw Uncaught SyntaxError in chrome 43

### ISSUE THREAD

**Issue by WhileKing** [vuejs/vue#11999]
### Version
2.6.11

### Reproduction link
[https://codepen.io/dydhyh/pen/dyNvqdr](https://codepen.io/dydhyh/pen/dyNvqdr)

### Steps to reproduce
browse app page through chrome (Version 43)

### What is expected?
browse app normally

### What is actually happening?
page is empty, and throw a error in console

---
Uncaught SyntaxError: Unexpected token ) at http://192.168.51.57:8080/#/entry/course:4486
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools at webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8418
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html at webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8428

browse app normally when chrome version >= 58

**Comment by posva** [comment]
It works fine on Chrome 43

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
