### ISSUE TITLE
v-bind or ":" use async method return ,actually result reuturn [object Promise],expected html

### ISSUE THREAD

**Issue by GavinChain** [vuejs/vue#12026]
### Version
2.6.11

### Reproduction link
[https://codepen.io/GavinChain/pen/VwPqrJY](https://codepen.io/GavinChain/pen/VwPqrJY)

```
<div id="app">
  <table border="1" cellpadding="10">
    <tbody>
      <tr v-for="row in pingZhengRows">
        <td>{{row.col1}}</td>
        <td>{{row.col2}}</td>
        <td>{{row.col3}}</td>
        <td v-html="castPingZhengHtml(row)"></td>
      </tr>
    </tbody>
  </table>
</div>


<script>
  new Vue({
    el:'#app',
    data(){
      return {
        pingZhengRows:[
          {col1:1,col2:1,col3:1},
          {col1:1,col2:1,col3:1},
          {col1:1,col2:1,col3:1},
          {col1:1,col2:1,col3:1}
        ]
      }
    },
    methods:{
      async castPingZhengHtml(row){
        const col1Html=await queryCol1Value(row)
        const col2Html=await queryCol2Value(row)
        const col3Html=await queryCol3Value(row)
        return `
          ${col1Html}<br>
          ${col2Html}<br>
          ${col3Html}<br>
        `
      }
    }
  })


  function queryCol1Value(col1){
    return new Promise((resolve, reject)=>{
      resolve('col1：'+'500')
    })
  }
  function queryCol2Value(col2){
    return new Promise((resolve, reject)=>{
      resolve('col2：'+'1500')
    })
  }
  function queryCol3Value(col3){
    return new Promise((resolve, reject)=>{
      resolve('col3：'+'2500')
    })
  }
</script>

```

### Steps to reproduce
1.一个表格,每行4列
2.每行前3列固定值
3.每行第4列:从（异步）请求后端 获取三列计算值,返回HTML

### What is expected?
返回实际数据，而不是[object Promise]

### What is actually happening?
v-html='castPingZhengHtml(row)'返回了[object Promise]

**Comment by posva** [comment]
This is expected behavior, you are explicitely giving to `v-html` the promise. You will need to call the promise inside a component that receives the `row` and put that into a data property that is passed to v-html

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
