### ISSUE TITLE
v-for inside v-for inside v-for skipping second line of contents if element on first line

### ISSUE THREAD

**Issue by DutchPrince** [vuejs/vue#12056]
### Version
3.0.5

### Reproduction link
[link](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHYtZm9yPVwiY2F0ZWdvcnkgaW4gbXNnXCI+XG4gICAge3tjYXRlZ29yeS50aXRsZX19XG4gICAgPGRpdj5cbiAgICAgICAgPGRpdiBzdHlsZT1cIm1hcmdpbi1sZWZ0OiA0cHg7XCIgdi1mb3I9XCJpdGVtIGluIGNhdGVnb3J5Lml0ZW1zXCIgOmtleT1cIml0ZW0uaWRcIj5cbiAgICAgICAgICAgPGlucHV0IHR5cGU9XCJ0ZXh0XCIgdi1tb2RlbD1cIml0ZW0udGl0bGVcIiAvPlxuICAgICAgICAgICAgPHNwYW4+e3tpdGVtLnRpdGxlfX08L3NwYW4+XG4gICAgICAgICAgPGRpdiBzdHlsZT1cIm1hcmdpbi1sZWZ0OiA0cHg7XCI+XG4gICAgICAgICAgICAgIDxkaXYgdi1mb3I9XCJzdWIgaW4gaXRlbVwiIDprZXk9XCJzdWIuaWRcIj5cbiAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT1cInRleHRcIiB2LW1vZGVsPVwic3ViLnRpdGxlXCIgLz5cbiAgICAgICAgICAgICAgICAgICA8c3Bhbj57e3N1Yi50aXRsZX19PC9zcGFuPlxuICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmNvbnN0IG1zZyA9IFt7XG4gIGRlc2M6IFwibG9sXCIsXG5pZDogMzEsXG5pdGVtczogW10sXG50aXRsZTogXCJsb2xcIixcbn0se1xuZGVzYzogXCJsb2xcIixcbmlkOiA0MSxcbml0ZW1zOiBbXSxcbnRpdGxlOiBcImxvbFwiXG4gIH0sIHtcbmRlc2M6IFwibG9sXCIsXG5pZDogNSxcbiAgICBpdGVtczogW3tcbmNhdGVnb3J5OiB7aWQ6IDUxMiwgdGl0bGU6IFwibG9sXCIsIGRlc2M6IFwibG9sXCJ9LFxuaWQ6IDkwLFxuc2VsZWN0ZWQ6IGZhbHNlLFxuc3ViX2NhdGVnb3JpZXM6IFt7XG5jYXRlZ29yeToge2lkOiA1MywgdGl0bGU6IFwibG9sXCIsIGRlc2M6IFwibG9sXCJ9LFxuaWQ6IDksXG5zZWxlY3RlZDogZmFsc2UsXG5zdWJfY2F0ZWdvcmllczogW10sXG50aXRsZTogXCJsb2xcIixcbiAgICB9XSxcbnRpdGxlOiBcImxvbFwiLFxuICAgIH1dLFxudGl0bGU6IFwibG9sXCIsXG59XVxuPC9zY3JpcHQ+In0=)

### Steps to reproduce
1. Nest 3 v-for's
2. add element to the first line of each iteration in the last v-for loop and text to the second line

### What is expected?
be able to add an element in a nested v-for

### What is actually happening?
The v-for is iterating the element on the first line without the text on the second line

**Comment by posva** [comment]
You had a typo in the nested `v-for`: [fixed here](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHYtZm9yPVwiY2F0ZWdvcnkgaW4gbXNnXCI+XG4gICAge3sgY2F0ZWdvcnkudGl0bGUgfX1cbiAgICA8ZGl2PlxuICAgICAgPGRpdlxuICAgICAgICBzdHlsZT1cIm1hcmdpbi1sZWZ0OiA0cHhcIlxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gY2F0ZWdvcnkuaXRlbXNcIlxuICAgICAgICA6a2V5PVwiaXRlbS5pZFwiXG4gICAgICA+XG4gICAgICAgIDxpbnB1dCB0eXBlPVwidGV4dFwiIHYtbW9kZWw9XCJpdGVtLnRpdGxlXCIgLz5cbiAgICAgICAgPHNwYW4+e3sgaXRlbS50aXRsZSB9fTwvc3Bhbj5cbiAgICAgICAgPGRpdiBzdHlsZT1cIm1hcmdpbi1sZWZ0OiA0cHhcIj5cbiAgICAgICAgICA8ZGl2IHYtZm9yPVwic3ViIGluIGl0ZW0uc3ViX2NhdGVnb3JpZXNcIiA6a2V5PVwic3ViLmlkXCI+XG4gICAgICAgICAgICA8aW5wdXQgdHlwZT1cInRleHRcIiB2LW1vZGVsPVwic3ViLnRpdGxlXCIgLz5cbiAgICAgICAgICAgIDxzcGFuPnt7IHN1Yi50aXRsZSB9fTwvc3Bhbj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuY29uc3QgbXNnID0gW1xuICB7XG4gICAgZGVzYzogJzMxIGRlc2MnLFxuICAgIGlkOiAzMSxcbiAgICBpdGVtczogW10sXG4gICAgdGl0bGU6ICczMScsXG4gIH0sXG4gIHtcbiAgICBkZXNjOiAnNDEgZGVzYycsXG4gICAgaWQ6IDQxLFxuICAgIGl0ZW1zOiBbXSxcbiAgICB0aXRsZTogJzQxJyxcbiAgfSxcbiAge1xuICAgIGRlc2M6ICc1IGRlc2MnLFxuICAgIGlkOiA1LFxuICAgIGl0ZW1zOiBbXG4gICAgICB7XG4gICAgICAgIGNhdGVnb3J5OiB7IGlkOiA1MTIsIHRpdGxlOiAnNTEyJywgZGVzYzogJ2Rlc2MgNTEyJyB9LFxuICAgICAgICBpZDogOTAsXG4gICAgICAgIHNlbGVjdGVkOiBmYWxzZSxcbiAgICAgICAgc3ViX2NhdGVnb3JpZXM6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBjYXRlZ29yeTogeyBpZDogNTMsIHRpdGxlOiAnMzUnLCBkZXNjOiAnMzUgZGVzYycgfSxcbiAgICAgICAgICAgIGlkOiA5LFxuICAgICAgICAgICAgc2VsZWN0ZWQ6IGZhbHNlLFxuICAgICAgICAgICAgc3ViX2NhdGVnb3JpZXM6IFtdLFxuICAgICAgICAgICAgdGl0bGU6ICdvbmUnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICAgIHRpdGxlOiAndHdvJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgICB0aXRsZTogJzUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4ifQ==)


---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
