### ISSUE TITLE
子组件条件渲染，引入的js数据经过computed，状态会被记住

### ISSUE THREAD

**Issue by Hsxzn** [vuejs/vue#12061]
### Version
2.6.11

### Reproduction link
[https://github.com/Hsxzn/demo_vue](https://github.com/Hsxzn/demo_vue)

### Steps to reproduce
> npm run serve，
> click button title 'open'，
> children template show，
> click children template button 'change computed modalFromData'，
> state change，
> click children template button 'close dialog'，
> again children show, data and computed of status It will be remembered

### What is expected?
Render the subcomponent state again and do not update it

### What is actually happening?
Render the subcomponents again，last time change remember

---
 复用弹窗（新建/编辑/详情），数据来源js 引入,  引入的数据被更改，再次渲染的是更改后的数据

**Comment by posva** [comment]
You are modifying the original object, so it's normal for it to remember changes.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
