### ISSUE TITLE
Does slot support v-slot$ syntax?

### ISSUE THREAD

**Issue by Vgbire** [vuejs/vue#12117]
### Version
2.6.13

### Reproduction link
[https://codepen.io/vgbire/pen/WNGZbOQ](https://codepen.io/vgbire/pen/WNGZbOQ)

### Steps to reproduce
The official usage is v-slot: but v-slot$ is also supported

### What is expected?
There seems to be no introduction similar to the v-slot$ syntax on the official website

### What is actually happening?
v-slot$default can use

---
when i view compiler/parser/index.js，I found v-slot$default can also be used normally
I wonder if the regular matching of slotRE is wrong
soucre code: const slotRE = /^v-slot(:|$)|^#/
in this re v-slot$ can use
If you don't actually support the v-slot$ syntax
maybe there can be const slotRE = /^v-slot:?|^#/

**Comment by Vgbire** [comment]
@yyx990803 hello! can you cc?maybe compiler/parser/index.js slotRE can be this 
![image](https://user-images.githubusercontent.com/32129111/120808275-7df83580-c57b-11eb-9b45-4709bd4a1878.png)
![image](https://user-images.githubusercontent.com/32129111/120808480-b13ac480-c57b-11eb-9910-c0bee4b14cfd.png)

**Comment by posva** [comment]
it's `v-slot:slot-name` or `#slot-name`.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
