### ISSUE TITLE
In some case，Slot will case the component to be forced to update

### ISSUE THREAD

**Issue by trcat** [vuejs/vue#12131]
### Version
2.6.14

### Reproduction link
[https://github.com/trcat/vue-2x-playgroud](https://github.com/trcat/vue-2x-playgroud)

### Steps to reproduce
use `yarn install` to install all dependence, and use `yarn serve` run the project。

now, you can click the button, and then，you will see the number changed, and also you can see a alert，it‘s mean the title-slot component updated，which should‘t updated，because it's props or data never updated。

but you can change App.vue code as bellow，and then，click the button，the title-slot component wouldn‘t updated：

```vue
<template>
  <div id="app">
    <h1>{{ count }}</h1>
    <button @click="count  = 1">click add count</button>
    <title-slot>
      <template #default>
        this is second title（by slot）
      </template>
    </title-slot>
  </div>
</template>
```

I don't know why？what happend？

### What is expected?
click button，count changed and App component updated，but title-slot shouldn't updated

### What is actually happening?
click button，count changed and App component updated，
and title-slot also updated

**Comment by posva** [comment]
This is expected: the whole template renders when something changes inside of it (in this case count)

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
