### ISSUE TITLE
Quick queries for size and orientation, to be used with v-show for fast development of responsive pages

### ISSUE THREAD

**Issue by informationretrievalunit** [vuejs/vue#12241]
### What problem does this feature solve?
Currently v-show doesn't seem to recognize window.innerWidth or window.innerHeight, so we have to write logic under mounted to listen for 'resize'; or as an alternative way, we have to use css media queries, but this also adds to complexity, and is a redundant job too. So, since responsive design is now part of almost every single project, it might feel much better for vue to provide some quick queries, thus getting life of developers way easier. You can think of it like the quick save feature in video games, which at the first glance looks like a redundant feature by itself, yet in the long term, it actually gets rid of so much redundant action which makes people love it.

### What does the proposed API look like?
You might just create another thing like v-if and v-show, but that would prevent developers to have multiple conditions, so it would be better if you could provide something more flexible, like actually usable references to window.innerWidth and window.innerHeight, but in a reactive manner. Like 'v-show="vuery.width < vuery.height"'. And you could expand the feature in the future for marketing vue to even more people.

**Comment by posva** [comment]
Writing media queries in JS instead of CSS is an anti pattern and it will only negatively affect your page (e.g. flashes, worse page scores). 

There are however some valid cases, for those, you can use https://github.com/flatanimals/vue-media-queries or similar solutions.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
