### ISSUE TITLE
iframe in transition-group ,created canceled requests

### ISSUE THREAD

**Issue by babytutu** [vuejs/vue#12249]
### Version
2.6.14

### Reproduction link
[babytutu.github.io/vue-error/](https://babytutu.github.io/vue-error/#/)

### Steps to reproduce
F12 to open Chrome DevTools, choose Network, filter Doc, click button to toggle view iframes, will see canceled request on every click

I creat a repo with version vue 2.6.14, and this bug is still in vue3

### What is expected?
no canceled requests

### What is actually happening?
every click created a canceled request

**Comment by posva** [comment]
This is not related to Vue and isn't a bug. It's about iframe network requests behavior when their elements are moved.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
