### ISSUE TITLE
v-model for Radio inputs can't set initial value

### ISSUE THREAD

**Issue by lucasreppewelander** [vuejs/vue#12309]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/frosty-smoke-ezijx?file=/src/App.vue)

### Steps to reproduce
Despite the docs stating the following **checkboxes and radiobuttons use checked property and change event** here [Form Input Bindings](https://vuejs.org/v2/guide/forms.html) it does not seem to work as it should

### What is expected?
Expected as in the `CInput` component (from the same codesandbox) If the *state* has a value from the start it should be **checked**

### What is actually happening?
the radio buttons checked doesn't seem to be triggered but when I use the provide my own `:checked="value"` and `@change=""` it do work as expected.

**Comment by posva** [comment]
This is because you are not setting the `value` attribute of the `input` of type radio so vue cannot match the `checked` property for you.

The repro contains a lot more so please ask on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for help debugging your component.
