### ISSUE TITLE
Dynamic class binding's object syntax applied to <component> tag

### ISSUE THREAD

**Issue by DamianGlowala** [vuejs/vue#12377]
### What problem does this feature solve?
It allows binding the component's name by using `:is="{...}"` keyword directly in the template using an object syntax. For components like Snackbar/Toast, this would be quicker and cleaner than having to do so in the `data()` or `setup()`. If we can switch CSS classes using object syntax, why cannot it be done in the exact same way for the components?

### What does the proposed API look like?
```
<component
  :is="{
      'SuccessIcon': type == SnackbarType.Success,
      'WarningIcon': type == SnackbarType.Warning,
      'InfoIcon': type == SnackbarType.Info,
      'ErrorIcon': type == SnackbarType.Error
  }"
  :class="{
      'success-color': type == SnackbarType.Success,
      'warning-color': type == SnackbarType.Warning,
      'info-color': type == SnackbarType.Info,
      'error-color': type == SnackbarType.Error
  }"
/>
```

**Comment by posva** [comment]
Use a dictionary insetad:

```js
const dict = {
[SnackbarType.Success]: 'SuccessIcon',
// others
}
```

and then `<component :is="dict[type]" />`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
