### ISSUE TITLE
slot 组件的name属性为什么不支持v-bind绑定一个变量

### ISSUE THREAD

**Issue by ThorSmallice** [vuejs/vue#12405]
### What problem does this feature solve?
现在的slot组件name属性如果用v-bind绑定一个变量 会导致调用时关联不到这个插槽，现在的情况是name属性只允许填写一个字符串，有些场景下，需用到循环创建命名插槽，如果name属性支持变量，就可以实现这一功能

### What does the proposed API look like?
slot :name="slotname"></slot
data(){
    return {
       slotname: ' name '
    }
}

**Comment by posva** [comment]
Because it's extracted during compilation: https://template-explorer.vuejs.org/#%3Cdiv%20id%3D%22app%22%3E%7B%7B%20msg%20%7D%7D%0A%20%20%3Cslot%20name%3D%22hey%22%3Ehello%3C%2Fslot%3E%0A%3C%2Fdiv%3E

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
