### ISSUE TITLE
父子组件绑定的v-model值 在子组件中使用watch监听失败

### ISSUE THREAD

**Issue by 2016011969sunyifang** [vuejs/vue#12428]
### Version
2.6.10

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/serverless-frost-zebrq?file=/src/components/HelloWorld.vue)

### Steps to reproduce
等待三秒即可 如果监听到子组件的值应该会改变

### What is expected?
子组件中的值变成我发生改变了 同事显示在页面上

### What is actually happening?
子组件的值未发生改变

---
如果不可以  请给出替代方案 谢谢

**Comment by 2016011969sunyifang** [comment]
快解决啊 大佬们

**Comment by posva** [comment]
You need to properly declare your props to work with v-model: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by cbtpro** [comment]
对你的代码进行了简单的修改，解决了子组件值没有发生改变的问题。
https://codesandbox.io/s/icy-dream-61b80?file=/src/components/HelloWorld.vue
问题点有：
父组件使用v-model绑定的值，在子组件中默认是value,并且需要在props中定义value，然后监听value的值的变化。

重新使用model自定义v-model绑定的值修改了下：
https://codesandbox.io/s/amazing-khayyam-28zqf?file=/src/components/HelloWorld.vue

重新使用简化的方式写写了一份，供参考：
https://codesandbox.io/s/zealous-visvesvaraya-l7sw8?file=/src/components/HelloWorld.vue

**Comment by guofengcrazy** [comment]
v-model 只是绑定了父组件某个值 但是并没有赋予子组件
在vue3中可以写成v-mode:value="" 然后在子组件监听value
在vue2中可以写成:value="" 然后在子组件监听value
vue可换成任意，只是一个key
