### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by arun-nd** [vuejs/vue#12429]
### Version
2.6.11

### Steps to reproduce
I followed steps from the official document
https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html

I tired the Real-World Example 

### What is expected?
Show the default vueJS page 

### What is actually happening?
Getting a blank page with the error Uncaught SyntaxError: Unexpected token '<' in the console

---
Locally it is working fine. I get this error when I'm trying to set it up on a cloud instance.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You need to configure your server to properly serve the file. It is serving an HTML file instead of the JS file you want
