### ISSUE TITLE
SECURITY ISSUE - possibility to turn on vue devtools at prod mode

### ISSUE THREAD

**Issue by demianchuk** [vuejs/vue#12458]
### Version
2.6.14

### Reproduction link
[dev.to](https://dev.to/valentin9/force-enable-vue-js-devtools-in-production-mode-49jg)

### Steps to reproduce
Hi,

It appeared that I've got information that is east to bypass framework and open vue dev tools at prod
Here is the link you can get all necessary info how to reproduce steps https://dev.to/valentin9/force-enable-vue-js-devtools-in-production-mode-49jg

You may also test prepared chrome extension that use according workaround. I've tested it - and it really works.

From my point of view that is security hole. That allows to investigate code and application logic easily for hackers

The only correct way to avoid it  - is to move dev tools from framework as separate npm package that should be used only at
dev environment. 

What do you think about it?
 

### What is expected?
vue dev tools should not be available at prod mode and it is not possible to hack that behaviour

### What is actually happening?
It is possible to open vue dev tools at prod mode making small workaround

**Comment by aviatrix** [comment]
Any JS loaded by the browser cab downloaded, inspected, and modified. Prod mode or not, i can do whatever i want with your JS and see all the logic inside of it

**Comment by demianchuk** [comment]
You can try

But if it is minified and compressed I doubt you can do a lot :)

**Comment by sodatea** [comment]
This is not a vulnerability.
FYI, React Dev Tools works on any React website - including facebook.com

**Comment by demianchuk** [comment]
Hi,

I am not saying that is vulnerability that should be added to exploit cve list

I dont know how react dev tools work. Unfortunately I am not working with React within last 5 years as developer

But if is true and react dev tools are working at prod mode at facebook - it does not mean VUE should inherit that behavior


I am working at security area within last 3 years and can say definitely one thing - such behavior gives for hackers

much more possibilities and I am disappointed a lit bit that you neglect that fact like it is worth of nothing :(

**Comment by sodatea** [comment]
A few more thoughts:

- Making it harder to access the component tree does not make it impossible. Therefore it provides a false sense of security, which, IMO, is more dangerous than showing the dev tools to all developers.
- So, actually, I initially advocate for not providing the ability to turn off dev tools in production at all.
- Because front-end code is not secure at all. JS files are minified for size concerns, not for security. Visitors can always inspect the website's front-end logic. Sensitive info and business logic should be secured at the back end.
- Nevertheless, in Vue 3, it is possible to completely turn off Vue Devtools in production by setting the compile-time flag `__VUE_PROD_DEVTOOLS__` to `false`. But again, this is to reduce the bundle size, not to secure the app.
