### ISSUE TITLE
Vue.extend name always is `VueComponent` in webpack,   CDN is correct

### ISSUE THREAD

**Issue by chenjiangui** [vuejs/vue#12481]
### Version
2.6.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/silly-turing-of5fns?file=/src/main.js)

### Steps to reproduce
only look console log out,   CodePen is ok
```
const ABC = Vue.extend({
  name: 'ABC',
  template: `<div>abc</div>`
})

// always: VueComponent,  hope: ABC, in cdn is correct
console.log(ABC.name);
```

### What is expected?
Component name: `ABC`

### What is actually happening?
codesandbox(webpack) Component name is `VueComponent`,
CodePen(cdn) is `ABC`

**Comment by posva** [comment]
That's the name of the function (or class). You need `ABC.extendOptions.name`.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by chenjiangui** [comment]
> That's the name of the function (or class). You need `ABC.extendOptions.name`.

i try import vue in cdn way, the name will be correct (`ABC`), in vue-cli is always  `VueComponent`, i think this is a bug. 
you can try the same code in codesandbo and CodePen, you will get diffrent result
```
const ABC = Vue.extend({
  name: 'ABC',
  template: `<div>abc</div>`
})

// always: VueComponent,  hope: ABC, in cdn is correct
console.log(ABC.name);
```
