### ISSUE TITLE
Using the same array V-for rendering on the same page will report an error

### ISSUE THREAD

**Issue by ludengdeng-for-who** [vuejs/vue#12506]
### Version
2.5.20

### Reproduction link
[codepen.io](https://codepen.io/ludengdeng/pen/jOYyERr)

### Steps to reproduce
When I'm on the same page or component，“v-for” multiple times using the same array， "Duplicate keys detected. This may cause an update error." will be reported on the page，But the key of V-for is not repeated

### What is expected?
In a page, using an array to render V-for multiple times will not report an error

### What is actually happening?
In a page, use an array to render V-for multiple times and report errors

**Comment by posva** [comment]
You cannot have the same key for adjacent elements. Keys must be unique.

---



Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by ludengdeng-for-who** [comment]
However, the error will still be reported if it is not adjacent. I have modified codepen
