### ISSUE TITLE
Vue 2.7: `getCurrentInstance()` returns `ComponentInstance` proxy instead of `ComponentInternalInstance`

### ISSUE THREAD

**Issue by dm4t2** [vuejs/vue#12577]
### Version
2.7.0-beta.5

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue-2-7-0-getcurrentinstance-be6ghd?file=/src/App.vue)

### Steps to reproduce
Open the CodeSandbox and watch the console output.

### What is expected?
`getCurrentInstance()` should return the `ComponentInternalInstance` similar to the behavior in Vue 2.6 with Composition API plugin or Vue 3.

### What is actually happening?
`getCurrentInstance()` returns the `ComponentInstance` proxy object 

---
Working example with Vue 2.6 and Composition API plugin: 
https://codesandbox.io/s/vue-2-6-14-getcurrentinstance-i8s8e3?file=/src/App.vue

**Comment by yyx990803** [comment]
This is intentional. `ComponentInternalInstance`, as the name suggests, is internal. The fact that the Composition API plugin exposed a mocked internal instance was a mistake, because it has subtle differences from the Vue 3 behavior that can't be fully compatible. In 2.7, the returned instance only exposes `proxy`, which is the equivalent of `this` in Options API. Code that relies on any other properties should be refactored.
