### ISSUE TITLE
vue.min.js is missing in 2.7.0

### ISSUE THREAD

**Issue by GaneshKandu** [vuejs/vue#12592]
### What problem does this feature solve?
easy to use

### What does the proposed API look like?
#

**Comment by lorand-horvath** [comment]
I confirm, please add the necessary builds to the /dist folder, as it was in Vue 2.6. Thanks!

**Comment by yyx990803** [comment]
It is published on npm: https://unpkg.com/browse/vue@2.7.0/dist/

**dist files are no longer checked into the repository** - Please note that source code is not part of the framework's public interface and your code should never rely on using the source repository as a CDN.

Please use CDNs like unpkg or jsdelivr which automatically syncs with npm.

**Comment by earlAchromatic** [comment]
I understand the philosophy behind this but not sure it makes sense to change the public interface on the last release since it has been that way for most of its life. I would argue that this constitutes a breaking change.

This is perhaps niche and not applicable to the greater community but for my use case I am locked into using Bower for the foreseeable future and Bower pulls from the repo, since it no longer maintains a registry. This is not a choice that I have control over as a user of Bower and ultimately renders 2.7 inaccessible.

Since both Vue 2 and Bower are legacy software I am wondering if there will be others in a similar situation. What is the benefit of this particular decision if the tradeoff is friction for legacy users to adopt 2.7 (and therefore backported Vue 3 features)?
