### ISSUE TITLE
It seems that watcher doesn't meet expectation, when it watches a computed function with 'deep' option.

### ISSUE THREAD

**Issue by dO-ob94** [vuejs/vue#12650]
### Version
2.7.2

### Reproduction link
[codepen.io](https://codepen.io/Michael9411/pen/Yzayvdx)

### Steps to reproduce
Click button 'Exchange'.

### What is expected?
The callback should not gets called, since new value is same as old value.

### What is actually happening?
The callback gets called, but new value is same as old value. 

---
You may have noticed that a computed function watched with 'deep' option. This wired scenario came out when I studied a piece of Vue source code. 
https://github.com/vuejs/vue/blob/018d29af5fa171b2d2f4793c5d471f21bb7cd1e7/src/core/observer/watcher.ts#L205-L212
As you can see, the new value is same as the old (both are primitive values), but the callback gets called. So, is it better below?  
```
 if ( 
   value !== this.value || 
   // Deep watchers and watchers on Object/Arrays should fire even 
   // when the value is the same, because the value may 
   // have mutated. 
   isObject(value) &&
   this.deep 
 ) {
```

**Comment by yyx990803** [comment]
While this may be improved, it's unlikely that can actually change the behavior. As you can see if we change the code as you suggested, there will be multiple test cases failing.
The edge case you demonstrated here won't really happen in practice often because it's pointless to use the deep flag on a non-object value, so it's more important to ensure that we do not break existing code.
