### ISSUE TITLE
UnwrapRefSimple is not exported

### ISSUE THREAD

**Issue by Flamenco** [vuejs/vue#12665]
### What problem does this feature solve?
In this example, my layer items are of type `UnwrapRefSimple`

```
const layers = ref([])
let layer = layers.value.find(it => it.id === '')
```

I have a factory function that returns items of type `UnwrapRefSimple`
```
opts: { itemProp: string, newLayer: () => UnwrapRefSimple }
```

This worked in older versions of Vue with the Composition API plugin, but after upgrading to Vue 2.7, the `UnwrapRefSimple` type is not exported.

### What does the proposed API look like?
```
export type UnwrapRefSimple ...
```

**Comment by yyx990803** [comment]
You should be using `UnwrapRef` instead. `UnwrapRefSimple` was never intended to be a public type (it's not exported in Vue 3 either). Although `@vue/composition-api` exported it, the behavior of Vue 3 should be treated as the source of truth.

Also, I can't really understand your code example since `UnwrapRefSimple` has a required generic argument. Please make sure to provide fully reproducible code.

**Comment by Flamenco** [comment]
The problem is that the type `UnwrapRefSimple` is how typescript defines my array elements.  So I get an error assigning it to `UnwrapRef`


<img width="631" alt="Screen Shot 2022-07-16 at 9 13 58 AM" src="https://user-images.githubusercontent.com/819940/179356437-3460ab87-3e6b-46de-ab99-4b9675176478.png">

<img width="371" alt="Screen Shot 2022-07-16 at 9 14 15 AM" src="https://user-images.githubusercontent.com/819940/179356439-015947ea-6c66-496e-bdfe-3ac35f7c212f.png">

**Comment by Flamenco** [comment]
@yyx990803 Does that screenshot make it clearer?  My factory function has no way to match the interpolated private type.
