### ISSUE TITLE
现有组件 a b c d e f g h ，如何在编译过程中 ，在上述 组件的模版中中增加一个固定的包裹组件 

### ISSUE THREAD

**Issue by xiaobo1215** [vuejs/vue#12681]
### Version
2.7.7

### Reproduction link
[new-issue.vuejs.org/](https://new-issue.vuejs.org/?repo=vuejs/vue)

### Steps to reproduce
问题：
我现在的页面都需要包裹一个容器组件，是否能通过 vue-loader 实现？我知道可以通过 router-view 实现；；我想通过 vue-loader ，或者 新的一个loader 来实现？

### What is expected?
问题：
我现在的页面都需要包裹一个容器组件，是否能通过 vue-loader 实现？我知道可以通过 router-view 实现；；我想通过 vue-loader ，或者 新的一个loader 来实现？

### What is actually happening?
问题：
我现在的页面都需要包裹一个容器组件，是否能通过 vue-loader 实现？我知道可以通过 router-view 实现；；我想通过 vue-loader ，或者 新的一个loader 来实现？

---
问题：
我现在的页面都需要包裹一个容器组件，是否能通过 vue-loader 实现？我知道可以通过 router-view 实现；；我想通过 vue-loader ，或者 新的一个loader 来实现？

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
