### ISSUE TITLE
Vue2.7 should support events on tsx

### ISSUE THREAD

**Issue by iceprosurface** [vuejs/vue#12680]
### What problem does this feature solve?
Hello.tsx
```tsx
import { defineComponent } from "vue";
export default defineComponent({
  emits: ["confirm"],
  setup() {
    return () => <div />;
  },
});

```
app.tsx
```
import Hello from "./Hello";
defineComponent({
  setup() {
    return () => <Hello onConfirm={() => "test"} />;
  },
});

```

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/16058059/179679758-69a932c5-9a72-4161-aaf6-2a01c4ac3be5.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/16058059/179679773-8775750b-9dbd-4045-900a-cfe3a88ffb45.png">

### What does the proposed API look like?
no

**Comment by JorisAerts** [comment]
Since the "listeners" are gone from the setup context, I cannot pass any event to the child components anymore.
They are nowhere to be found. Not on the attrs either, not even with inheritAttrs:false.

**Comment by yyx990803** [comment]
Vue 2 JSX transform doesn't support transforming `onXXX` listeners, nor does Vue 2 accept `onXXX` props for emit-declared events. Basically, this is a feature that does not exist in Vue 2 and we do not intend to backport this since it's a niche feature and doesn't justify the effort needed to implement and maintain it.

@JorisAerts your issue is valid but is unrelated to this one.

**Comment by yyx990803** [comment]
Added `context.listeners` in adf3ac8a

**Comment by iceprosurface** [comment]
@yyx990803 

There is no needs for us to have `emit-declared`,but we just needs type-check on tsx for custom events.

**Comment by Sleaf** [comment]
Or fallback to any? 
The problem is tsx will not pass the type checker now.

**Comment by litt1e-p** [comment]
try it :
```jsx
<Hello {on: { confirm: () => test()}} />
```
