### ISSUE TITLE
toRefs(proxyRefs(...)) works, but warns that toRefs() expects a reactive object but received a plain one

### ISSUE THREAD

**Issue by vmihailenco** [vuejs/vue#12741]
### Version
2.7.8

### Steps to reproduce
The following code

```js
toRefs(proxyRefs({ foo: computed(() => 1) }))
```

prints a warning

```
vue.runtime.esm.js:4560 [Vue warn]: toRefs() expects a reactive object but received a plain one.
```

### What is expected?
No warning

### What is actually happening?
Warning in console

**Comment by sodatea** [comment]
I think it's expected behavior.

`proxyRefs()` does not return a reactive object.
Its type signature is `ShallowUnwrapRef<T>`, while `reactive()` returns an `UnwrapNestedRefs<T>`

It only happens to be the case that the `toRefs()`'s internal implementation can handle `ShallowUnwrapRef<T>`'s structure. But `toRefs()`'s documented usage is only to handle reactive objects.
So I think you better create a custom utility function to handle it than reusing `toRefs()` for this purpose.
