### ISSUE TITLE
The component rerenders without updating anything

### ISSUE THREAD

**Issue by 1593292349** [vuejs/vue#12852]
### Version
2.7.13

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/snowy-cdn-b3361q?file=/src/App.vue)

### Steps to reproduce
1. Open the CodeSandbox link and view the console
2. It's logical to print "app 更新"
3. But it also prints "comp1 更新"
4. The comp1 component didn't change anything, so why did it render again?

### What is expected?
Do not print "comp1 更新"

### What is actually happening?
it prints "comp1 更新"

**Comment by 1593292349** [comment]
![image](https://user-images.githubusercontent.com/48791868/198054461-c36c2290-2cbb-41c1-9aff-a55d641727ab.png)

**Comment by 1593292349** [comment]
If I delete the slot for the Comp1 component, the Comp1 component will not be rerendered
![image](https://user-images.githubusercontent.com/48791868/198055018-5f3eedf8-590e-4b5d-923e-02ace75c6e74.png)

**Comment by 1593292349** [comment]
v3.2.41 also has this problem

**Comment by yyx990803** [comment]
This is a known behavior/limitation of Vue 2 because you are passing slot content to the child.

This is *not* present in Vue 3: [playground](https://sfc.vuejs.org/#eNq1kr1O40AQgF9ltFUiiDdpfSbS6aor7g228dmTxMjeXe2McydF6e54BAp4B0RBwwMBr8F4nTgRRIiGZjU7P9/8btR375N1iypVGWPj65xxbixAVlZrKOqc6MKo3Hujohpgs4F1XrcI2+2gqN3yFy1H0RGebx+er++NGg8e2Q/X+Nk8vi83/56u/j/dPWa618ZkWrKJlOmjGuRLRag8i1w13gWGGAGL4BowKukBXfVGfTMW/0afEhd5WzNsOnAhHs6iZUp7BfSM807exrfMOR+N99aA3Aa7/0Hfagp9gIRInn1gEVAKLQ+xhPzTMgaJGYn2Yn7AnJ3xqqIk0iKig8BsOp2Oj4gN8sqVh1J3YyUOQ46uJUuuxkSM0TLg9pyuxkzvRqfOVT+7SZP75JKclU1HltkZyKghoVFxmKkIK2ZPqda0KLoJX1LiwlKLlITWctVggtRMfgf3hzAI2KjdiCJDi3KNYRLQlhgwfMR84/qOG/uStqSVYeEnz/VwoMM9dvufnbpIqh2D/tzxnTqs01dzfB5fscztK/+mOmU=)

**Comment by 1593292349** [comment]
@yyx990803 Can you look at this similar code? Scoped Slots was not used, but the slots were re-rendered anyway. Vue3

**Comment by 1593292349** [comment]
@yyx990803  In vue2, I packaged a lot of components and made a lot of use of slots. There was a performance bottleneck in the fact that slots were constantly being re-rendered when they didn't change. How can I improve?
