### ISSUE TITLE
Vue 2.7 provide/inject not working with <script setup> in most builds

### ISSUE THREAD

**Issue by hsinpaohuang** [vuejs/vue#12883]
### Version
2.7.14

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vue2-vue-cli-yr8s1z)

### Steps to reproduce
1. Create a project with `vue-cli`
2. Add `provide` and `inject` to Vue components that are using `<script setup>`
3. Start the dev server

### What is expected?
provide and inject work properly

### What is actually happening?
Injected variable is undefined, and the following errors are logged to the console:
`provide() can only be used inside setup()`
`inject() can only be used inside setup() or functional components`

---

Upon further investigation, all builds beside `vue.runtime.esm.js` do not seem to work.

For our usecase, we have multiple vue instances on a webpage (which is rendered by a template engine on our backend), and props will be passed into each instance from the templates on the rendered webpage. That is why I tried to use the full build and ran into this issue.

**Comment by craigrileyuk** [comment]
Your problem is that in `main.js` you're using `import Vue from 'vue/dist/vue'` to instantiate your application.

Then inside your components, you're importing `provide` and `inject` straight from `vue`.

You need to use same import location, otherwise they can't connect with each other or your main application (hence the errors).

Usually, it's recommended to use an alias in your Vite/Webpack file to resolve `vue: "vue/dist/some.vue.build.js"` to ensure consistency.
