### ISSUE TITLE
Allow methods to be nested

### ISSUE THREAD

**Issue by JosephSilber** [vuejs/vue#1470]
I think it would make sense to allow methods to be nested under sub-objects:

```js
new Vue({
    methods: {
        group: {
            foo() {
                // `this` should be the vm
            },
            bar() {
                // `this` should be the vm
            },
        }
    }
});

**Comment by vprimachenko** [comment]
yeah this kind of namespace-ing would really clean some of my code up.

At the moment all UI describing variables live in
```js
Vue({
   data: {
      ui: {
        …
      }
   }
})
```

yet UI manipulator just live in `methods` and are prefixed `ui_` which makes, imo, some ,through consistent, yet errorprone code e.g.
```js
if(this.ui.foo) {
   this.ui_bar();
   this.ui.baz++;
}
```

**Comment by yyx990803** [comment]
I don't see the point other than style preferences. What makes it different from, say `uiFoo()` and `uiBar()`? If these methods on are invoked on the instance then they shouldn't be nested.

**Comment by JosephSilber** [comment]
They are mainly for style preference, yes. But I do have a another use case for it. It's very convenient to pass a group of methods to a child component.

In Vue 0.12, I had a validation component used to show server-side validation errors. It used a component in conjunction with a mixin. Here's a watered-down  version of it:

**Component**:

```js
Vue.component('validation', {
    template: `
        <div>
            <content></content>
            <span class="error"
                  v-show="isInvalid(property)"
                  v-text="getValidationError(property)"
            ></span>
        </div>
    `,
    inherit: true,
    props: [
        { name: 'property', type: String, required: true },
    ],
});
```

**Mixin**:

```js
{
    data() {
        return { serverValidation: {} }
    },
    methods: {
        isInvalid(property) {
            if (_.hasOwn(this.serverValidation, property)) return true;
        },
        isValid(property) {
            return ! this.isInvalid(property);
        },
        getValidationError(property) {
            if (this.isValid(property)) return null;

            return this.serverValidation[property][0];
        },
        catchValidation({ data }) {
            this.serverValidation = data.validationErrors || {};
        }
    }
};
```

**Page**:

```js
Vue.component('some-page-view-component', {
    template: `
        <validation property="name">
            <input type="text" v-model="name" v-class="error: isInvalid('name')">
        </validation>
    `,
    mixins: [validation],
    data() {
        return { name: '' };
    },
    methods: {
        save() {
            attemptToSaveStuff(...)
                .then(() => router.go('/someplace'))
                .catch(this.catchValidation.bind(this));
        }
    }
});
```

In short, I have a component and a mixin that work hand in hand. Since Vue 0.12 supported `inherit`, the component was able to utilize the validation methods directly from the parent component.

Fast forward to 1.0, and `inherit` is no more. I'll now have to pass all those methods down directly into the child component. Passing them all separately (for each input field) would severly clutter up the template. So I thought grouping them all in a single object and only passing that in would make more sense.

---

I might be approaching this all wrong, and I'll be happy to hear of an alternate solution. Regardless, I still think allowing methods to be group is a good idea. [I like nesting](https://github.com/vuejs/vue-router/issues/199#issuecomment-149768656) :smile:

**Comment by yyx990803** [comment]
I still hold the opinion that nested methods are more confusing than useful. The preferred way of connecting a child and a parent method is now doing so via `v-on`. If the parent and child are so tightly coupled that you are using `inherit` true, then it is effectively the same as directly calling `$parent.method()`.

**Comment by baberuth22** [comment]
Nested methods would be useful in giving mixin methods their own namespace.

**Comment by Glidias** [comment]
If you are not re-setting data objects as plain Json which will kill off their prototypes,  you could create instantiated  class based objects with nested object  methods since prototypes methods/getters/setters are not proxied by Vue. Only problem is you don't get computed caching unless you manually import those nested getters into an optionally namespaced flat vue structure mixin  in order to manually proxy into them. I have a custom haxevx macro that does this, but haxevx isn't vanilla Vue. Otherwise, nested data may have to exist in nested prescribed Vue components or modules, but u can't get object oriented  dot access with regular Vue via nested computed since vue isn't really  traditionally object oriented  (  using nested Vues/modules emulate this in a different way ) . However,  I think using non computed nested object  methods isn't much of a problem for this case though, as long as you don't reset yr data as plain json.

**Comment by floriansimon1** [comment]
Agree with @baberuth22, and thanks for your input @Glidias: it would be cool to be able to do `vm.validation.validateEmail(email)`, because it allows you to find quickly where a method comes from (in this case, I know I should be searching for the definition of the method inside a Validation mixin), which is more than just style preferences IMO.

**Comment by jasonlfunk** [comment]
I'd also like to advocate that this be implemented. Using objects to namespace and group functions is much more convenient than prefixing. Not only is it cleaner, but it also allows for IDEs to fold the methods as well.

![image](https://user-images.githubusercontent.com/685188/33305521-7ea61f8e-d41f-11e7-97eb-f9269361a03f.png)

As a workaround for now, this can be accomplished by using functions instead of objects:

```javascript
methods: {
    validation() {
            return {
                isEmail(email) {
                },
                isBlank(str) {
                },
                isUnique(arr) {
                },
            }
        }
}
```

And then these can be used like `validation().isEmail(addr)`. Not perfect, but it still gives the organizational benefits.

@yyx990803 It's been a couple years, has your opinion changed at all?

**Comment by Glidias** [comment]
If you adopt that approach, you should not use `method`, but `computed` and simply use `validation`, without the function brackets, in order to get computed caching (in fact, I tend to use `computed`  for pseudo stateful singletons/single-global refs/utility-classes/objects, etc. as well).

**Comment by jasonlfunk** [comment]
Validation was simply an example use-case which may or may not always make sense to use it as a computed property. It doesn't negate the original uses for nested methods.

**Comment by FSou1** [comment]
+1

**Comment by mirzabusatlic** [comment]
+1

**Comment by activeRobert** [comment]
+1, but as a decent workaround:

https://stackoverflow.com/questions/36108953/is-it-possible-to-nest-methods-in-vue-js-in-order-to-group-related-methods?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by CaelanStewart** [comment]
+1

**Comment by fhadiel** [comment]
+1

**Comment by Fortyseven** [comment]
+1

**Comment by yyx990803** [comment]
Locking as this is not going to happen.
