### ISSUE TITLE
failed el.form access when v-if used on custom directive

### ISSUE THREAD

**Issue by kazupon** [vuejs/vue#1673]
see the following url:
https://jsfiddle.net/kazupon/4uv5dg3t/2/

**Comment by yyx990803** [comment]
This is because the `v-if` block is compiled in an off-DOM fragment before being inserted. Unfortunately this is somewhat necessary to ensure correct compilation results. In general, directives should not assume where its `el` is.

As a workaround, you can wait for a `nextTick` before trying to access `this.el.form`. Note this means you will have to do some extra checks in your `update` function, but it should be ok...

**Comment by kazupon** [comment]
Thanks!!
I understood :)
