### ISSUE TITLE
Using activate hook with promise

### ISSUE THREAD

**Issue by fenivana** [vuejs/vue#1677]
I've tried returning a promise object in activate hook, or assigning a promise object to activate hook directly, but neither worked.

```js
Vue.component('example', {
  activate: function () {
    return ajax();
  }
})
```

```js
Vue.component('example', {
  activate: ajax()
})
```

**Comment by OEvgeny** [comment]
As I know promises are supported only in vue-routers hooks. 
Please use forum and chat for questions.

**Comment by fenivana** [comment]
As per https://github.com/vuejs/vue/issues/1169 ("The component will not be inserted until the user calls the passed-in callback, or return a promise."), I think it's a unimplemented feature, so I reported here.

**Comment by OEvgeny** [comment]
Ah ok, didn't know :)

**Comment by yyx990803** [comment]
Ah, I forgot that issue mentioned a promise... it is not implemented (and not mentioned in the actual doc).  There are no other places that assume Promises in Vue.js core so introducing Promise handling for this particular case is probably not worth it, since you can just do `activate (done) { ajax().then(done) }`.
