### ISSUE TITLE
Suggestion: "$last", "$even", "$odd" etc (v-for special properties)

### ISSUE THREAD

**Issue by furey** [vuejs/vue#1842]
Would it be relatively inexpensive to add other special properties to `v-for` loops?

For example ([from the Angular docs](https://docs.angularjs.org/api/ng/directive/ngRepeat)):

![ngrepeat](https://cloud.githubusercontent.com/assets/1914481/11316439/4d9defde-905b-11e5-90aa-f17d6faa1912.png)

I'm currently writing a breadcrumb component and a property like `$last` would simplify:

```javascript
<li :class="{ active: $index + 1 == crumbs.length }">
```

into:

```javascript
<li :class="{ active: $last }">
```

Interested to hear your thoughts!

**Comment by yyx990803** [comment]
Unfortunately, it is in fact relatively expensive to add these aliases, because in Vue these properties need to be reactive, so each of them would have extra initialization and memory costs. It would be wasteful to always define them on every repeated fragment.

You can define custom methods like `isLast` and just use it like

``` html
<li :class="{ active: isLast($index) }">
```

**Comment by furey** [comment]
Understood. Cheers.
