### ISSUE TITLE
Mixing Vue with custom JS logic for a complex app

### ISSUE THREAD

**Issue by ardoramor** [vuejs/vue#1848]
I've run into a problem trying to implement an architecture of an application where the state driver is not a parent but a nested child. I switched from evaluating React to Vue because it is more flexible but I still cannot quite understand how the particular architecture needs to be implemented in my case.

I have posted this question with details of layout on SO: http://stackoverflow.com/questions/33837541/vuejs-connect-unrelated-as-in-parent-child-components

It may be the case that MVVM cannot necessarily address the issue but I'm also finding it hard to combine Vue app with some custom JS controller logic baked in.

As for the issue wise, it is more of a suggestion to be able to provide component references to components that are not hierarchically related.

Or maybe a suggestion as to how address a similar architectural design. It cannot be the case that all apps use pure top down design where data gets filtered and only flows down.

Btw, thanks for the framework! Overall, I love it much more than React, in places where I can apply it per design!

**Comment by yyx990803** [comment]
In terms of state management, the general concept is let the source of truth be a reactive object shared by multiple component instances.

Start by describing your app state with a plain object, for example:

``` js
var playerState = {
  currentTime: 123,
  paused: false
}
```

Then, pass this object as a prop to both the player and the controller. Because they share the same state by identity, changing it from one component will automatically sync to the other one.

This object can also live as a standalone JavaScript module, or a "service". The point is that components don't need to have any relationship at all to be able to share this same object as the source of truth.
