### ISSUE TITLE
Vue crashes in Debug mode if path doesn't exist in 'v-if' directive

### ISSUE THREAD

**Issue by janschoenherr** [vuejs/vue#1919]
It seems, that Vue now throws an error and stops the execution if a path does not exist in the _v-if_ directive. In none debug mode it simply warns the user.

    <div v-if="does.not.exist">
       <span>Foo</span>
    </div>

http://jsbin.com/nagiradefi/1/edit?html,js,output

**Comment by yyx990803** [comment]
This is a small change in 1.0.10 that I forgot to list - in debug mode, if a warning was generated due to an actual Error, it now throws the original Error. The benefits is that you get stack trace all the way to where the real error occurred, which was not previously available with just a printed stack for the warning.

IMO this is better for debugging purposes. Do you have any particular reason that makes this undesirable?

**Comment by janschoenherr** [comment]
Well, we use this "fault tolerance" throughout our views. E.g. _package.extra.image_

    <img :alt="package.title" :src="package.extra.image" v-if="package.extra.image">

we check for the _image_ directly, no need to test for _extra_ first. But maybe that is not the correct approach.

**Comment by yyx990803** [comment]
You can rewrite that `v-if` as `v-if="package.extra && package.extra.image"` and it will short-circuit other directives on/inside the same element.

**Comment by janschoenherr** [comment]
Absolutely, it is just convenient to be able to ignore that. On the other hand, the warnings weren't too pretty anyway.

**Comment by janschoenherr** [comment]
Just discovered, that this only happens with the _v-if_ directive. _v-show_ and _v-bind_ are still fault tolerant.
