### ISSUE TITLE
Suggestion: expose _vue_directives in production

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue#1927]
In relation to:
https://github.com/fergaldoyle/vue-form/issues/7

When authoring a plugin I found `el._vue_directives` very useful, only to find it's removed in production.

Would it be possible to keep it in production builds? Maybe with the same naming convention as v-models internal object.

```
__v_model
__v_directives
```

**Comment by vprimachenko** [comment]
cant you use `$vm.$options.directives`?

**Comment by fergaldoyle** [comment]
Didn't know about `$vm.$options.directives` but it's not the same thing as `el._vue_directives`.

**Comment by yyx990803** [comment]
I added it mostly for potential devtools use and was cautious about the additional memory usage since this is adding an array to every single node that has a directive. But it seems we don't need it for textNodes, which may bring the usage to an acceptable level.

Can you elaborate a bit more on what use case you have found for this?

**Comment by fergaldoyle** [comment]
When writing a directive it's a useful way to check attribute bindings, and gives you a lot of detail about them. 
Although a simple attribute check and `$eval` would probably meet most requirements, as I've now done for the issue I referenced above.

So if there's a memory usage concern it's probably not worth enabling it in production builds.

**Comment by yyx990803** [comment]
I think I'll close this for now - Vue's reactivity system is pretty memory hungry, so I'd like to avoid any non-critical memory consumption.
