### ISSUE TITLE
Not able to compute properties and pass them in as props.

### ISSUE THREAD

**Issue by qw3n** [vuejs/vue#1972]
Basically setting a computed property and prop to the same name doesn't work very well.  Here is my sample use case.
    
    <div id="app">
    <custom-input value="z,x"></custom-input>
    </div>
    
    <template id="custom-input">
    <span >
      <input type="text" v-model="value">
      <div>Custom Input<br>{{$data | json}}</div>
    </span>
    </template>
    
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.min.js"></script>
    <script type="text/javascript">
    Vue.component('custom-input',{
      template:'#custom-input',
      data:function(){
        return {
          part1:'a',
          part2:'b'
        }
      },
      computed:{
        value:{
          get:function(){
            return this.part1+','+this.part2;
          },
          set:function(parts){
            parts=parts.split(',');
            this.part1=parts[0];
            this.part2=parts[1];
          }
        }
      },
      props:['value']
    });
    
    new Vue({el:'#app'});
    </script>

I have a custom input and I would like to be able to pass in a default value. But, it also needs to be a computed value so that the component can manipulate it. Maybe I am just going about this the wrong way. There is a workaround where you use a different name for the prop and then use the `created` callback to set it to the computed value.

**Comment by yyx990803** [comment]
It doesn't make sense to have a prop be computed at the same time. You can use [two way filters](http://vuejs.org/guide/custom-filter.html#Two-way_Filters) though.

**Comment by ardoramor** [comment]
I'd like to see if the issue can be reopened. Lets say there is a component that does something like so:

    // Child component
    <template>
      <div v-el:widget></div>
      <p>{{msg}}</p>
    </template>
   
    <script>
      {
         props: {
            msg: {
               type: String,
               required: false,
               default: 'Hello!'
            }
         },
         computed: {
            msg: {
               cached: false,
               get: function () {
                  $(this.$els.widget).get('text');
               },
               set: function (value) {
                  $(this.$els.widget).set('text', value);
               }
            }
         },
         ready: function () {
            $(this.$els.widget).superWidget({
               text: this.msg
            });
         }
      }
    </script>

And the parent script can define an instance of child like so:

   <template>
      <child :msg="greeting"></child>
   </template>

In my view, this creates a very powerful interaction because `computed` is an interface to an underlying value generator/container/producer while `props` declares that the values can be passed in.

Of course, I'm not that well familiar with the underlying code of Vue yet, but, internally, the `props` value provider can assign the value that will trigger a call to `set`, which will update the internal value.
