### ISSUE TITLE
v-for performance issue

### ISSUE THREAD

**Issue by petersn-github** [vuejs/vue#2000]
hi, I have a table with a 300 row *60 column, using V-for's rendering is very slow, how to improve efficiency?

**Comment by zigomir** [comment]
@petersn-github I think your description lacks details. It would help a lot if you tell a bit more and/or show an example through JSBin or similar tool so one can see what is going on in your case.

**Comment by yyx990803** [comment]
This is somewhat inevitable, the cell count is simply too large. There's currently no simple way to make it magically fast.

There are two possible ways around this:

1. Rethink your UI design. Do you really need 18,000 cells all rendered at the same time? Does it even make sense? How about pagination?

2. Do you need interactivity on every single cell? If not, you can scrap `v-for` and write your custom directive that simply renders the table with `innerHTML`. Or maybe you shouldn't be using Vue to render it in the first place.

**Comment by smolinari** [comment]
I am also interested in listing large amounts of data for reports. However, no real interactivity is needed, except for regular linking. I would imagine this is possible without any kind of performance issues? What would be the best practice to include such a large set of data into a vue?

Scott

**Comment by yyx990803** [comment]
@smolinari pagination is probably the most reasonable solution, both performance and UX wise. The real bottleneck is how many items are rendered on the page at the same time. Just limit it to a reasonable amount.

**Comment by smolinari** [comment]
Pagenation for a report isn't really good usability.

The reports we are looking at would be limited to a maximum of 2000 or maybe 2500 rows, but there could be up to 15 columns. A lot of data, yes, but any decent reporting system would need to show that amount. Maybe need to come up with a completely different way to show this data?  Hmm...maybe some sort of infinite scrolling might be the answer?

Scott

**Comment by yyx990803** [comment]
I don't think any web framework can handle that many cells with acceptable rendering performance. So yeah, you have to do some dirty work to implement infinite scroll or virtual scroll.

**Comment by KennedyTedesco** [comment]
@yyx990803 I'm having the same Issue with 200 records, it cost almost 6s to render. It would be great a way to render without data binding ... This make any sense?

**Comment by yyx990803** [comment]
@KennedyTedesco 6s for 200 records doesn't sound right. I assume you have more nested `v-for`? What does the template look like?

**Comment by KennedyTedesco** [comment]
@yyx990803 Sorry, my mistake. For my happiness the problem wasn't on Vue.

**Comment by PrimozRome** [comment]
@yyx990803 I am experiencing the same issue with only 50 records but not sure is it my problem or Vue's. Described here http://forum.vuejs.org/topic/3888/long-render-time-v-for.

**Comment by PierBover** [comment]
I've hit this problem and if **you really must show all these records at the same time** the simplest solution is to use divs instead of a table.

Render time in my case was reduced from 2 seconds to 100ms (aprox) for about 5500 rows * 8 columns (44000 cells).

But like @yyx990803 said usually the best option is to question whether showing you should be really painting all those cells. The are very few cases where showing all the data is justified and these are edge cases which need to be handled with care.

**Comment by kinanson** [comment]
I also have this issue.I have large size data 5000 row that is key and value like below:
I binding in the ul li that is ok.
But I binding in the select option that is so slow.
I think select binding large size data is common situation.
can i find the vue have any way to support without databind?
Below is example.

 ```
<input type="checkbox" v-model="isCheck" />
    <select v-model="name" v-if="isCheck">
      <option v-for="(value,key) in competitions" :key="key">
        {{value}}
      </option>
    </select>
    <hr>
    <input type="checkbox" v-model="isCheck1" />
    <ul v-if="isCheck1">
      <li v-for="(value,key) in competitions" :key="key">
        {{value}}
      </li>
    </ul>
```

![1](https://user-images.githubusercontent.com/5998113/34033237-5b2b789a-e1b4-11e7-91a4-2e4f91ca6aa8.gif)

**Comment by MaherSoua** [comment]
Hi @kinanson , you can use :value ( v-bind:value) instead of v-model, I test it with 1000 element and it is really fast.

**Comment by kinanson** [comment]
In fact that is not real.I try no binding on select,It is also slow,Maybe you can tray more then 5000 rows.

**Comment by MaherSoua** [comment]
@kinanson I try it with 5000 is still ok, but with 10000 was really slow.

**Comment by Akryum** [comment]
Did you try https://github.com/Akryum/vue-virtual-scroller?

**Comment by Soletiq** [comment]
This is a huge problem that needs to be addressed somehow.

Im using laravel and we needed an infinite scrolling table. We only load about 50 rows per batch. Ive been using vue for the entire project. We were using the v-for table but quickly noticed it couldnt handle a large amount of rows without slowing down the entire page. Also, scrolling becomes laggy and sticky.

My workaround was to dynamically create the table HTML and insert using v-html. But this is a terrible workaround. The code is extremely messy and hard to work with. I absolutely love using vueJS but this is a massive setback.

**Comment by PierBover** [comment]
@Soletiq if you really need to display thousands of rows at the same time you will get much better performance with `<div>` than using tables.

**Comment by Soletiq** [comment]
It works slightly better but even at 500 rows I start to notice lag in scrolling.

How does no one else find this to be a gigantic issue? How does one build an application with infinite scrolling like a feed of posts, similar to facebook or twitter? The scrolling behavior would feel terrible after only a few hundred posts. The only solution i've found is to generate the HTML myself in an application that uses VueJS entirely. This is a terrible solution.

**Comment by yyx990803** [comment]
@Soletiq have you seen https://github.com/Akryum/vue-virtual-scroller ?

**Comment by PierBover** [comment]
> It works slightly better but even at 250 rows I start to notice lag in scrolling.

250 rows is nothing. I've had thousands div of elements with no penalty in performance.

Are you sure the issue is not somewhere else?

**Comment by Soletiq** [comment]
Its not an extremely simple table. It has 7 columns that use v-if / else elements and a few number conversions.

An equally significant problem when using v-for is when you scroll the bottom (to load more rows), it takes more time each batch to insert the rows into the table since it has to handle an increasing amount of rows. So when you get to a few hundred rows it can actually take 3+ seconds for it to insert the next batch.

> @Soletiq have you seen https://github.com/Akryum/vue-virtual-scroller ?

I will try this, thank you.

**Comment by Soletiq** [comment]
This is a GIF of me scrolling on the first batch. Scrolling is much smoother here.
https://gyazo.com/07e617c350b9d16ecb3e280c71139153

This is a GIF of me scrolling after about 10 more batches of 50 rows each. So about 500 rows here. If you look closely the scrolling is more glitchy, not as smooth. It gets worse as you load more rows. Its also really important to mention that changing other state values is extremely slow. For example, when I click a button that brings up a modal, it simply changes the state from open = false to open = true and this takes about 10-20s with this amount of rows in the table.
https://gyazo.com/ee6aef78a441cd8f2d307268fec49582

- I changed my table elements to divs (very little performance impact)
- Im using Vue Material currently (but my tables are my own code)
- Im using v-for still, but i've switched to (i in data.length) so instead of all of the data being stored, its only storing the index and that's how im retrieving the value for each column.

I've done everything I can think of. My only solution is the most terrible solution which is writing the tables in HTML with javascript.

**Comment by PierBover** [comment]
@Soletiq could you post a reproducible example?

**Comment by ethan-deng** [comment]
Put the usability issue aside, I tested the performance of v-for of Vue.js and compared it to React.js. And here is what I found.

Vue.js v-for to render 50,000 lines
```
<template>
  <div>
    <div
      v-for="n in 50000"
      :key="n">Hello World {{ n }}
    </div>
  </div>
</template>
```

React.js to render 50,000 lines
```
const About = () => {
  var lines = []
  for (let i=0; i<50000; i++){
    lines.push(<div>hello world {i}</div>)
  }
  return <div>{lines}</div>
}
```

Vue.js takes 30 seconds to render and React.js takes 5 seconds to render. Vue.js is 5 times slower than React.js.
The worst for Vue.js is that when testing rendering 100,000 lines, Vue.js will just hang the browser (Chrome) and I have to kill the browser process through OS. However React.js can "easily" render all 100,000 lines in about 7 seconds.

To summary to test result  
| Number of Lines | Vue.js | React.js |  
| 50,000 | 30 seconds | 5 seconds |  
| 100,000 | 4 minutes | 7 seconds |  
| 500,000 | forever | 3 minutes |  

The conclusion is that React.js has more capacity than Vue.js when rending large amount of data.
### Why is this important?
Many application may need to render large amount of data occasionally but the amount of data is within a range. For example a data set may never reaches 100,000. With the capacity of rendering 100,000 lines within 7 seconds, the application will accommodate a lot more scenarios without complex solutions.

I actually came to this issue when rendering just about 2000 components with each of them primary just contains a file name. When adding a one or more complex components such as a Vue material design button to each component, the rendering will unbearably slow and I have to optimize the component without using any advanced component in it in order to let it renders in reasonable time.

Although the ultimate solution for rendering a large amount of data may be using paging or other techniques but in my opinion, capacity is also important. With the capacity like React.js, we can go a lot further without reaching the limitation of the platform.

**Comment by Akryum** [comment]
@ethan-deng How is Vue performance if you use functional components in your list?

**Comment by ethan-deng** [comment]
@Akryum I haven't tried that. Could you provide a code to do that? Thanks.

**Comment by PierBover** [comment]
In my experience rendering lists with about 3000 divs I experienced noticeable better performance with React than Vue. Nothing as drastic as what @ethan-deng is mentioning, but the React app definitely feels more snappy.

It's weird though because in these benchmarks Vue usually comes on top of React:
https://www.stefankrause.net/js-frameworks-benchmark7/table.html
https://github.com/krausest/js-framework-benchmark/

**Comment by ethan-deng** [comment]
@Akryum Just tested with this code

```
<script>
export default {
  name: 'PerfTest',
  render (h) {
    const lines = []
    for (let i = 0; i < 100000; i++) {
      lines.push(<div>Hello World {i}</div>)
    }
    return (
      <div>
        {lines}
      </div>
    )
  }
}
</script>
```

Feel there are some improvements of performance but not a whole lot.

**Comment by yyx990803** [comment]
I'll just say this: **measuring performance of rows more than what you can show in one screen is pointless**. If you have such a large amount of data, 7 seconds render time is pretty much still unusable, and you should be using a [virtual list component](https://github.com/Akryum/vue-virtual-scroller).

**Comment by ethan-deng** [comment]
One use case of this that a customer want to generate a report which contains all the data which about 100,000 lines of data. We can wait and then print it out and hand it over to them. Or save it a PDF file using the browser and email the report to them. This only needs to be done once in a while and at the same time our app support pagination and searching to get access to the data.

Another point is the "capacity" I mentioned, while rendering 100,000 of simple data is pointless most of the time except the case above, the framework should support rendering 2000 of more complex components at once without hanging the browser.

Another point, most of the enterprise apps are exposed the "big data" set randomly. At the start of a project, it is hard to predict what is the upper limit of any data set. We cannot afford to put "good design" everywhere in the application.

**Comment by PierBover** [comment]
> I'll just say this: measuring performance of rows more than what you can show in one screen is pointless. Is there any practical use case where you need 100,000 rows rendered at the same time?

Maybe not rows, but there is a case for rendering thousands of SVG nodes, in the same screen.

**Comment by yyx990803** [comment]
Btw my argument has nothing to do with React vs. Vue because your 5x perf difference doesn't exist:

- Vue http://jsfiddle.net/3ncjyd1a/5/
- React https://jsfiddle.net/Lu1025ax/6/

**Comment by ethan-deng** [comment]
@yyx990803 Thanks for the links. Yes, I don't feel there are too much differences between Vue and React from the links. I took a second look at my project, it seems the culprit is the the 3rd party UI library we introduce, we have 
```
import Vue from 'vue'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'
import 'vue-material/dist/theme/default.css'
Vue.use(VueMaterial)
```
in the App root,

After removing this code, I don't see the 5x perf difference any more. It is good to know it is not the issue of the framework. Thanks!

**Comment by Akryum** [comment]
I can confirm there is almost no difference between the two with those production builds using vue-cli and create-react-app (100000 elements rendered):
- Vue: https://perf-isvwyijykv.now.sh/ (https://perf-isvwyijykv.now.sh/_src)
- React: https://new-zlahotjhpc.now.sh/ (https://new-zlahotjhpc.now.sh/_src)

Also for some reason on my Firefoxx on Windows, Vue is consistently (800ms) faster than React (3500ms)

**Comment by ethan-deng** [comment]
@Akryum Have you tried 500,000? This is just out of curiosity than practical.  It seems Vue sample never renders but I have a result that React takes  164485.100000049ms to render 1,000,000 lines.

**Comment by yyx990803** [comment]
@ethan-deng 500k is simply not a reasonable number for a web framework to deal with. If you have that requirement, just use React. That's fine.

**Comment by Akryum** [comment]
@ethan-deng Also, a virtual scroller is a perfect solution for your use case. It will make your app render 500k items almost instantly.

**Comment by ethan-deng** [comment]
Thanks. It is always good to know the boundary of a framework. Also I am using a Vue Material UI library https://vuematerial.io/. Anyone has a good guess why it slows down the rendering so much.

I got this from Chrome debug tool with rendering 20,000 <div>

Recalculate Style
Total Time
5.36 s
Self Time
5.36 s
Elements Affected
20007
Pending for
452.0 ms
Initiator
reveal
First Invalidated
createStyleElement	@	addStylesClient.js?ae38:114

Parse HTML
Total Time
5.40 s
Self Time
13.12 ms
Range
:8080/#/perf:10 [10…-1]

**Comment by smolinari** [comment]
@ethan-deng - If you are not happy with ElementUI, please take a look at [Quasar Framework](https://quasar-framework.org/) and see if it fits your needs better. It won't help you with your rendering issue, (which isn't really an issue) but it might in other areas. 

If you are going to stick to ElementUI, you'd be much better off asking them about your rendering issue. :smile:

Scott

**Comment by ethan-deng** [comment]
More findings related to this issue.
The performance difference is actually introduced by referencing the CSS files as 
```
import 'vue-material/dist/vue-material.min.css'
import 'vue-material/dist/theme/default.css'
```
or in the index.html file. When either the index.html imports the CSS files or using import in the JS file, the "createStyleElement	@	addStylesClient.js?ae38:114" will slow down the rendering quite a lot.

After removing any references of CSS file, Vue.js actually shows better performance than React. Vue.js can rendering 10,000,000 divs in about 120 seconds which is better than 180 seconds of React.js

However, since we need to use Vue.js with a material ui library https://vuematerial.io, I tested using Vue.js to render 20,000 raised buttons to using React.js with material ui library https://material-ui.com to rendering 20,000 raised buttons.

React.js with the material ui library is significantly shower than rendering just 20,000 divs but it can be done within seconds however the Vue.js with its material ui library never renders and hangs the browser.

I know it may be the issue of the https://vuematerial.io, but I am worried this may related to how the style loader is implemented in Vue.

**Comment by yyx990803** [comment]
Pretty sure CSS is a complete framework agnostic problem.

**Comment by martinandersen3d** [comment]
Here is table creation benchmarks on all JavaScript frameworks

https://github.com/krausest/js-framework-benchmark/blob/master/README.md

Use whatever works in this edge case :)

Maybe even write the table in vanilla JavaScript?

**Comment by PierBover** [comment]
> Here is table creation benchmarks on all JavaScript frameworks
> 
> https://github.com/krausest/js-framework-benchmark/blob/master/README.md

Here are the results of that benchmark:

https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html

**Comment by kyleparisi** [comment]
I came upon this issue in search of why my 100 row table (~1500 cells) was lagging when sorting a column. The data set was only 3500 rows.  Although this is not directly related to the above descriptions it is worth noting that I had fallen for the https://vuejs.org/v2/guide/list.html#v-for-with-v-if logic gotcha.  I had made this mistake on an element which would not render anything but still loop the whole data set.

**Comment by mathieu-gilloots** [comment]
Same problem here, I try to display a card board, with a lot of card (responsive) sometime I've 2 card per line some time 3 or 4, depending of the screen.
With a big client we have a lot of card and Google Chrome crashes after a freeze time.

If you do a v-for on a large number, there seems to be buggy.

We can't use virtual scroller because our client need to be able to print the page with Control + P and we have a PDF renderer service that do the same things.

Any ideas ?

**Comment by PierBover** [comment]
> Any ideas ?

Vue, React, etc, are intended for reactive DOM manipulation which is why there is an overhead on each element and that can become problematic on extreme cases like yours. Personally I've rendered thousands of SVG elements with Vue and never hit such a serious a problem.

If you only need to paint DOM elements you could simply render in the server or use browser APIs bypassing the virtual DOM.

If you do need reactivity, and assuming there is nothing wrong with your Vue code, maybe you could try with Inferno. I've found it's faster than Vue on some use cases.

**Comment by ethan-deng** [comment]
This could be performance issue of CSS rendering. I tested vue + vue UI a library and react + a react UI library. Vue is slower than react, but if I test vue vs react without any third party UI library, vue out-perform react.

**Comment by amrlafi** [comment]
Did you consider using functional components? also one-way binding (using :value instead of v-model) usually helps as it skips generating watchers for the model, would definitely help if you model is complex.

**Comment by sh0ber** [comment]
One optimization not mentioned here is `Object.freeze()` for data that doesn't need reactivity, such as that used in a static report.  Even when displaying table rows with functional components, a large reactive data set carries its own reactivity overhead which can be removed by freezing data prior to using in the UI, or even immediately after load.  And if your data is being stored in Vuex, it's reactive, because "[a Vuex store's state is made reactive by Vue](https://vuex.vuejs.org/guide/mutations.html)".  All that's needed is to freeze the data before loading it into Vuex.   

Without this optimization, each data value is tracked for changes by the reactivity system, which makes rendering slower.  It's even possible to make changes by "unfreezing" data (by cloning the set), making a change to the clone, re-freezing, and replacing the original.

**Comment by original0594** [comment]
For anyone who is having troubles with infinite/virtual scrolling for a table, an easy way to implement this is with Pagination and a onScroll listener, once a user scrolls to the bottom of the page simply increase the Pagination "perPage" by 100(or whatever you want)

**Comment by nkostadinov** [comment]
I notice enormous penalty when destroying(set to []) a list of around 500 - 600 items in v-for cycle (each item has 5-6 child components). Can this become faster ? May be some framework optimization, if the lenght of the array is 0 then making innerHtml='' is instant, while destroying those items takes 5-6 seconds.
I've migrated our product which is very large RSS reader(nearly 1.5mln users) to Vue, but the older version using jquery and plain js is MUCH faster. I'm depressed now :(

**Comment by Akryum** [comment]
@nkostadinov Vue still needs to properly destroy all the child/nested components. You should try a virtual scrolling solution as mentioned in the thread.

**Comment by PierBover** [comment]
@nkostadinov have you tried not using reactive data for that list?

**Comment by nkostadinov** [comment]
@Akryum I will try to use the list but I have a card view which will be difficult to implement with virtual scroller because the articles are ordered in lines up to 4 cards (card is item from v-for)

@PierBover the data for that list have to be reactive :)

**Comment by maicWezaoski** [comment]
hello, I need help, chrome browser crashes when my app still processing the data. 
i have csv file which contains approximately 5000 rows and 20cells per row. then in vue js i have components that process the csv. the process includes multi mapping on each cell lots of mapping on array/object. the data reaches thousands of array and has thousands of nested array. when processing i used async so that it will just process and display if done processing. i put a spinner if ever the process isnt done, with 2000 rows data the app works, but when the data reaches 5000 rows the spinner show for about 25seconds and then the browser crashes. 
Please help. thank you and God Bless Sir.

**Comment by KarmaBlackshaw** [comment]
Hi! I am having the same problem of rendering a list of 200 rows. However, I think the problems is in the dynamic class binding. I use a method to dynamically add class based on the given parameter and every time I click the list, it recalls the function 200 times.

**Comment by killo9ramm** [comment]
Hi! Facing the same problem I have datalist in input with 650 option items. 
If I use v-for in html directly:
```
<datalist id="bxCityList">
             <option v-for="item in itemsList" :value="item.uniqName"></option>
</datalist> 
```
to fill values list I have 3 to 5 seconds lag to find an item while typing in input

But following solution became much more faster resulting no lag at all:
js file
```
Vue.component('cities-list-item', {
    props: ['city'],
    template: 
`     
  <option v-bind:data-value='city.code' v-bind:value="city.uniqName" />
`
  })
```

html
```
<datalist id="bxCityList">
    <cities-list-item v-for="item in itemsList" v-bind:city="item" v-bind:key="item.code">
    </cities-list-item>
</datalist>
```
I hope this helps

**Comment by AllanOricil** [comment]
After finally made it work. I just added a debounce function on the input handler. Now I can type anything, and wait the 110ms vue takes to rerender everything.

**Comment by AllanOricil** [comment]
I also noticed that css is kind making the input to lag. When I remove all the css that I'm using to style inputs inside table cells, the input works really fine and I don't even need to use debounce. This css is not applied conditionally on the template and the DOM is also not being modified when typing. So I don't really know why the css is slowing down inputs. Does anyone here has any thoughts about it?

**Comment by mabokslot** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

https://github.com/github/hub/issues/3088
--
https://github.com/xtekky/gpt4free/issues/294
https://github.com/AIGC-Audio/AudioGPT/issues/34
https://github.com/NVIDIA/NeMo-Guardrails/issues/12
https://github.com/orchidsoftware/platform/issues/2596
https://github.com/metabase/metabase/issues/30453
https://github.com/TeamNewPipe/NewPipe/issues/10057
https://github.com/github/codespaces-jupyter/issues/367
https://github.com/github/codespaces-jupyter/issues/368


</body>
</html>

**Comment by samuelkilada** [comment]
I came up with my own form of "virtualization", since I couldn't find a good library for it. I am able to render 150,000 items with quite decent performance (at this point, the only thing that starts to slightly slow down is scrolling, but it's still quite good and once you stop scrolling, performance is buttery smooth).

This works by rendering in a for loop only the items that are currently in view. The rest of the items are "faked" with a table row before and after the viewable items, with the height of those table rows calculated to the height of the offscreen items. This makes it so that you only have to v-for through the visible items and not the whole array. Here's basically the code to do it. I'll be continuing to test and refine this but it's pretty stable already:

```
<script>
const items = ref([] as Array<any>)
for (let i = 0; i < 50000; i++) {
  items.value.push({
    id: i,
    name: `Item ${i}`,
    date: '11/10/2023'
  })
}
const scrollY = ref(0)
// Put in the pixel height of one of your table rows. Inspect the DOM in the browser to find this out
const rowHeight = 50
// If you have some kind of header or something at the top that gets scrolled with the table items, put the height of that below, as a negative number
const tableExtraContent = -50
// The height of the scrollable part of the table that you want to display (based on max-height in styles)
const viewableHeight = 800
// Calculate what part of the array we're currently viewing
const viewingStartIndex = computed(() => {
  let startIndex = Math.floor((scrollY.value + tableExtraContent) / rowHeight)
  if (startIndex < 0) {
    startIndex = 0
  }
  return startIndex
})
const viewingItems = computed(() => {
  let endIndex = Math.ceil((scrollY.value + tableExtraContent + viewableHeight) / rowHeight)
  if (endIndex > items.value.length) {
    endIndex = items.value.length
  }
  return items.value.slice(viewingStartIndex.value, endIndex)
})

// Calculate how big the empty space above the table should be
const aboveItems = computed(() => {
  return items.value.slice(0, viewingStartIndex.value)
})
const aboveItemsStyle = computed(() => {
  const height = aboveItems.value.length * rowHeight
  return {
    height: `${height}px`
  }
})

// Calculate how big the empty space below the table should be
const belowItems = computed(() => {
  return items.value.slice(viewingStartIndex.value + viewingItems.value.length)
})

const belowItemsStyle = computed(() => {
  const height = belowItems.value.length * rowHeight
  return {
    height: `${height}px`
  }
})

// Table scroll event
const tableScrolled = (e: any) => {
  scrollY.value = e.target.scrollTop
}
</script>

<template>
    <div class="scrollable" @scroll="tableScrolled">
      <table>
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Date</td>
          </tr>
        </thead>
        <tbody>
          <tr :style="aboveItemsStyle">
          </tr>
          <tr v-for="(item, rowIndex) in viewingItems" :key="item.id">
            <td class="id">
              {{ viewingStartIndex + rowIndex + 1 }}
            </td>
            <td>
              {{ item.name }}
            </td>
            <td>
              {{ item.date }}
            </td>
          </tr>
          <tr :style="belowItemsStyle">
          </tr>
        </tbody>
      </table>
    </div>
</template>
<style lang="scss" scoped>
  .scrollable {
    max-height: 800px;
    overflow-y: auto;

    table {
      tr {
        height: 50px;
        
        td {
          width: 20%;
        }
      }
    }
  }
</style>

```

**Comment by AllanOricil** [comment]
> I came up with my own form of "virtualization", since I couldn't find a good library for it. I am able to render 150,000 items with quite decent performance (at this point, the only thing that starts to slightly slow down is scrolling, but it's still quite good and once you stop scrolling, performance is buttery smooth).
> 
> This works by rendering in a for loop only the items that are currently in view. The rest of the items are "faked" with a table row before and after the viewable items, with the height of those table rows calculated to the height of the offscreen items. This makes it so that you only have to v-for through the visible items and not the whole array. Here's basically the code to do it. I'll be continuing to test and refine this but it's pretty stable already:
> 
> ```
> <script setup lang="ts">
> const items = ref([] as Array<any>)
> for (let i = 0; i < 50000; i++) {
>   items.value.push({
>     id: i,
>     name: `Item ${i}`,
>     date: '11/10/2023'
>   })
> }
> const scrollY = ref(0)
> // Put in the pixel height of one of your table rows. Inspect the DOM in the browser to find this out
> const rowHeight = 50
> // If you have some kind of header or something at the top that gets scrolled with the table items, put the height of that below, as a negative number
> const tableExtraContent = -50
> // The height of the scrollable part of the table that you want to display (based on max-height in styles)
> const viewableHeight = 800
> // Calculate what part of the array we're currently viewing
> const viewingStartIndex = computed(() => {
>   let startIndex = Math.floor((scrollY.value + tableExtraContent) / rowHeight)
>   if (startIndex < 0) {
>     startIndex = 0
>   }
>   return startIndex
> })
> const viewingItems = computed(() => {
>   let endIndex = Math.ceil((scrollY.value + tableExtraContent + viewableHeight) / rowHeight)
>   if (endIndex > items.value.length) {
>     endIndex = items.value.length
>   }
>   return items.value.slice(viewingStartIndex.value, endIndex)
> })
> 
> // Calculate how big the empty space above the table should be
> const aboveItems = computed(() => {
>   return items.value.slice(0, viewingStartIndex.value)
> })
> const aboveItemsStyle = computed(() => {
>   const height = aboveItems.value.length * rowHeight
>   return {
>     height: `${height}px`
>   }
> })
> 
> // Calculate how big the empty space below the table should be
> const belowItems = computed(() => {
>   return items.value.slice(viewingStartIndex.value + viewingItems.value.length)
> })
> 
> const belowItemsStyle = computed(() => {
>   const height = belowItems.value.length * rowHeight
>   return {
>     height: `${height}px`
>   }
> })
> 
> // Table scroll event
> const tableScrolled = (e: any) => {
>   scrollY.value = e.target.scrollTop
> }
> </script>
> 
> <template>
>     <div class="scrollable" @scroll="tableScrolled">
>       <table>
>         <thead>
>           <tr>
>             <td>ID</td>
>             <td>Name</td>
>             <td>Date</td>
>           </tr>
>         </thead>
>         <tbody>
>           <tr :style="aboveItemsStyle">
>           </tr>
>           <tr v-for="(item, rowIndex) in viewingItems" :key="item.id">
>             <td class="id">
>               {{ viewingStartIndex + rowIndex + 1 }}
>             </td>
>             <td>
>               {{ item.name }}
>             </td>
>             <td>
>               {{ item.date }}
>             </td>
>           </tr>
>           <tr :style="belowItemsStyle">
>           </tr>
>         </tbody>
>       </table>
>     </div>
> </template>
> <style lang="scss" scoped>
>   .scrollable {
>     max-height: 800px;
>     overflow-y: auto;
> 
>     table {
>       tr {
>         height: 50px;
>         
>         td {
>           width: 20%;
>         }
>       }
>     }
>   }
> </style>
> 
> ```

If you virtualize columns as well it would be amazin

**Comment by samuelkilada** [comment]
I think you shouldn't need to virtualize the columns, unless you're doing something super strange with your table!

**Comment by bilogic** [comment]
> I've hit this problem and if **you really must show all these records at the same time** the simplest solution is to use divs instead of a table.
> Render time in my case was reduced from 2 seconds to 100ms (aprox) for about 5500 rows * 8 columns (44000 cells).

@PierBover do you know why divs are faster than tables?
