### ISSUE TITLE
Class and Style Bindings BUG

### ISSUE THREAD

**Issue by coderzh** [vuejs/vue#2011]
When v-bind:class with array, there are some bug, but use v-bind:class="{'active': isActive} works.

Example:

```
<label v-bind:class="['btn', 'btn-default', flag == 1 ? 'active' : '']">
    <input type="radio" name="xxx" value="1" /> 1
</label>
<label v-bind:class="['btn', 'btn-default', flag == 2 ? 'active' : '']">
    <input type="radio" name="xxx" value="2" /> 2
</label>
<label v-bind:class="['btn', 'btn-default', flag == 3 ? 'active' : '']">
    <input type="radio" name="xxx" value="3" /> 3
</label>
```

flag = 2

Steps:

1. radio input  2 active default.
2. Click radio input 1
3. Change flag = 3
4. Result: both radio input 1 and radio input 3 are active

But when I changed to use v-bind:class="{'active': flag == 1} , it works correctly.

```
<label class="btn btn-default" v-bind:class="{'active': flag == 1}">
    <input type="radio" name="xxx" value="1" /> 1
</label>
<label class="btn btn-default" v-bind:class="{'active': flag == 2}">
    <input type="radio" name="xxx" value="2" /> 2
</label>
<label class="btn btn-default" v-bind:class="{'active': flag == 3}">
    <input type="radio" name="xxx" value="3" /> 3
</label>
```

**Comment by yyx990803** [comment]
Can't reproduce. Please make live demo.

**Comment by coderzh** [comment]
http://jsfiddle.net/nb0zebmq/

**Comment by yyx990803** [comment]
This only happens when you include `bootstrap.js`, because it adds the "active" class to the element when you click it. When using `v-bind:class` with Array syntax, it **preserves existing classes** on the element.

Consider the element:

``` html
<label class="active">
```

Now we add `v-bind:class` with array syntax:

``` html
<label class="active" v-bind:class="['a', 'b', condition ? 'active' : '']">
```

Because `condition` is always false, all Vue knows is that your third class in the Array is empty - it will not attempt to remove the "active" class because Vue has never been able to render it, so it assumes it is not on the element.

In comparison, when using the object syntax, Vue knows you want to toggle the `active` class.

I'd say this is intended behavior on Vue's part. Just be careful when using the array syntax with another library that also modifies the classes.

**Comment by smolinari** [comment]
Would using vue-strap be a possible alternative?

http://yuche.github.io/vue-strap/

Scott

**Comment by coderzh** [comment]
@smolinari cool !!!

**Comment by smolinari** [comment]
Yeah. When I found that library, I was like "Oh yeah! This is so cool." too. It doesn't cover all of bootstrap, but they are already working on [a version 4](https://github.com/yuche/vue-strap/tree/bootstrap4) to match up with Bootstrap4, so it looks promising.

Scott

**Comment by posva** [comment]
@coderzh don't forget about vue-mdl :stuck_out_tongue: 
https://github.com/posva/vue-mdl

**Comment by smolinari** [comment]
Nice work there @posva. If you got the feature set up to vue-strap's, I'd actually be very interested in vue-mdl, simply because it is different. Everybody and their brother is using Bootstrap.

Scott

**Comment by posva** [comment]
Thanks @smolinari, if by up to vue-strap you mean the same feature set, then I'm affraid that won't be the case as I follow http://www.getmdl.io/ which has a different set of features. I may, however, add other features on top of it.

**Comment by smolinari** [comment]
This is pretty close to the same feature/component set. 

http://www.getmdl.io/components/index.html#tooltips-section

Still, keep up the good work! I'll keep an eye out. :smile: 

Scott

**Comment by posva** [comment]
Thanks, that's great. I'm always looking for feedback :smile:
