### ISSUE TITLE
transition not ending in firefox

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue#2040]
the code is at jsfiddle:  https://jsfiddle.net/efkn1njd/

chrome is ok, but firefox is not……but if i change the value `show` to false with `setTimeout 0`, it is ok ……

the use case is：before page loaded, show a loading gif, and hide the loading gif after page loaded ……

**Comment by genhoi** [comment]
The same for me

**Comment by yyx990803** [comment]
`ready` is called **synchronously**. This is similar to adding `.test-leave` to the element synchronously on page load - the browser will optimize it and render the element directly with `.test-leave` without triggering any transition.

Using a `setTimeout` is a proper fix here (to give the browser time to render the initial state, so that adding the leave class can trigger transition).
