### ISSUE TITLE
Binding "muted" attribute on <video> does not work

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue#2042]
Repro: https://jsfiddle.net/simplesmiler/qsuvjk3r/

**Comment by yyx990803** [comment]
Cause: this is because `muted` works similar to `value` for `<input>`: if it is present inline when the element is created, it sets the initial value; but if it's not, just changing the attribute has no effect, we need to set the corresponding property.

It's a bit frustrating that there is no centralized documentation on the correspondence of HTML attributes/properties... there may be other attributes like this, and if there are we need to add them to the list too.

**Comment by rhyzx** [comment]
@yyx990803 
open https://www.w3.org/TR/html5/single-page.html and drop these code in console:
```js
[...new Set(document.body.innerText.match(/default[A-Z]\w+/g))]

// ["defaultView", "defaultPlaybackRate", "defaultMuted", "defaultChecked", "defaultValue", "defaultSelected"]
```

`view` belongs to `document` and `playbackRate` does not have a corresponding attribute, so the current list is complete.

**Comment by yyx990803** [comment]
Looks like `playbackRate` doesn't have a content attribute though. It's property only.

**Comment by xekri** [comment]
@yyx990803 However, when server side rendering with vue, I think it's ok to add such attributes to the element since it will be rendered on server side.
