### ISSUE TITLE
$arguments is undefined or null in IE/EDGE

### ISSUE THREAD

**Issue by gejgalis** [vuejs/vue#2052]
I wanted to emit custom event with `$arguments` variable inside repeater. It works as expected on Chrome and Firefox, but on IE9-11 and EDGE `$arguments` is `undefined` or `null` at the first call.

https://jsfiddle.net/b6jy7so9/4/

**Comment by yyx990803** [comment]
Wow, this is actually because IE fires a non-standard, native `activate` event when the button is clicked (and sometimes rendered initially)... so I guess you'll just have to avoid using `activate` as a custom event name...

Wondering if there's anything we can do to work around this, but don't have a really good idea at the moment.
