### ISSUE TITLE
Referencing previous elements in v-for

### ISSUE THREAD

**Issue by ardoramor** [vuejs/vue#2067]
I have ran into an issue while trying to inspect previous element in a list in relation to the current one. In more detail, I'm working on an event log and would like to assign a special class to the first event in the series of events generated by a user. The logic is similar to any messaging app where it creates a little arrow to the chat bubble when a user, different from the previous, sends a message. When that user again sends a message, the markup doesn't happen because its the same user:

    <-- userA
     -- userA
    <-- userB
     -- userB
     -- userB
    <-- userC
    <-- userA

It is also not a straight-forward markup. Notice the filtering and sorting. As such, I cannot simply use `events[index].data.user` because events is the original data source that is not filtered or sorted. Moreover, I have a factory that returns the component type to be created:

    <ul v-if="events.length > 0" class="list-unstyled event-list">
        <li v-for="(index, event) in events | orderBy 'time' order | filterBy type in 'type'">
            <compoent :is="eventFactory(event)" :info="event" :class="{'event-user-change': (index === 0 || event.data.user !== events[index].data.user)}"></compoent>
        </li>
    </ul>

What is the best approach in this case for trying to access the previous or some abstract index within the underlying dataset of the `v-for` operation?

**Comment by smolinari** [comment]
You aren't going to get answers to questions here. If you have an issue with the software, as in a possible bug, then you should post it here. Otherwise, there are the gitter channel and the forum to ask questions. 

Sorry for the runaround, but you're going to get this answer from Evan himself anyway, so might as well close this issue and move your question to one of the other support areas. Thanks!

https://gitter.im/vuejs/vue
http://forum.vuejs.org/

Scott

**Comment by yyx990803** [comment]
This doesn't seem like a bug, so I'm closing it - please post similar questions to the forum instead.

**Comment by JonasDoebertin** [comment]
@ardoramor Did you find a solution for this?
