### ISSUE TITLE
v-model with attribute lazy

### ISSUE THREAD

**Issue by PavelCSS** [vuejs/vue#2083]
v-model with attribute lazy is activated twice when blur and change. I think enough to a change event?!

**Comment by ludo237** [comment]
Could you provide an example please?

**Comment by PavelCSS** [comment]
when you first add the date watcher activated twice
http://codepen.io/PavelCSS/pen/obzeOz?editors=101

**Comment by ludo237** [comment]
I don't think that I've understand you issue very well. To be honest it seems to me that the watch callback lacks in logic. 

Your original pen shows that as soon as the input got focus the alert get a +1. But that's why the watch is missing some logic.

Try this.

```HTML
<div id="demo">
  <p>{{alert}}</p>
  <p>Old Val: {{ old }}</p>
  <p>New Val: {{ new }}</p>
  <hr />
  <input id="datepicker" v-model="message" lazy>
</div>
```


```Javascript
  var demo = new Vue({
    el: '#demo',
    data: {
      message: null,
      alert : 0,
      old: 0,
      new: 0,
    },
    watch : {
      'message' : function(newVal, oldVal) {
        if(oldVal !== null)
        {
          this.alert = this.alert + 1;
          this.old = oldVal;
          this.new = newVal;
        }
      }
    }
  });

$(function() {
  $( "#datepicker" ).datepicker();
});
```

[Code Pen for Reference](http://codepen.io/anon/pen/KVgXMY)

**Comment by PavelCSS** [comment]
It does not work if the value will be written or inserted manually

**Comment by ludo237** [comment]
@PavelCSS It was a silly solution to point out that the problem is how you are implementing the `message` callback
