### ISSUE TITLE
css animations when leave bug

### ISSUE THREAD

**Issue by Teddy-Zhu** [vuejs/vue#2096]
when i add `transition` attribution into Dom class ,the dom will be not removed after `animationend`,
in fact by javascript hooks log ,i found   the `afterLeave` function  not run  after `leave`
sorry for my bad english.
you  can see the below demo:
compare 
http://jsfiddle.net/teddyzhu/5zer9try/
with 
http://jsfiddle.net/5zer9try/2/

is it a bug or something wrong ?

test it in OS X 10.11.2  and Chrome 47.0.2526.106 (64-bit)

**Comment by pespantelis** [comment]
You should define CSS rules for `.expand-transition`, `.expand-enter` and `.expand-leave` classes.
http://vuejs.org/guide/transitions.html#CSS_Transitions

http://jsfiddle.net/5zer9try/1/

**Comment by Teddy-Zhu** [comment]
i defined the class *-enter and *-leave but they only have `animation` 
 in your example ,you add `opacity: 0;` into the enter and leave class 
can i only use CSS Animations ?

**Comment by Teddy-Zhu** [comment]
@pespantelis  you can compare  http://jsfiddle.net/teddyzhu/5zer9try/ and http://jsfiddle.net/5zer9try/2/

**Comment by yyx990803** [comment]
This is because Vue cannot tell whether you want the transition to end on `transitionend` event or the `animationend` event.

I've added the ability to manually specify the transition type in f04b396a7a46a19c24a16406d1c05b7e6a7f8397 - you can do

``` js
fade: {
  type: 'animation'
}
```

to let Vue know it should end the transition when the CSS animation finishes. This will be out in next patch and if you want to use it now you have to build from dev branch yourself.

**Comment by Teddy-Zhu** [comment]
@yyx990803  ok ,i see,thank you very much,this made me crazy before
