### ISSUE TITLE
slot的默认显示问题

### ISSUE THREAD

**Issue by lrdbzs** [vuejs/vue#2144]
如果directive定义了
```html
<div>
<slot name="abc">默认显示值</slot>
</div>
```
--------
使用的时候
```html
<component>
<div slot="abc" v-if="false">替换的内容</div>
</component>
```
这样的话，“默认显示值”的文字就不出现了。我是希望当v-if="false"的时候显示默认值

**Comment by amirrustam** [comment]
@lrdbzs myself and many others would be glad to help you if you could potentially translate these few lines into English. If that's hard, then also know that the community forum has dedicated sections for Chinese and Japanese (sorry I'm not familiar with the characters to differentiate) speaking members:
- [中文 - Chinese user forum](http://forum.vuejs.org/category/10/中文)
- [日本語 - Japanese user forum](http://forum.vuejs.org/category/11/日本語)

Otherwise, I hope someone else can assist you.

**Comment by mage3k** [comment]
@lrdbzs  取反就好了吧

**Comment by xiaolongyuan** [comment]
低级问题不要提 关掉吧

**Comment by yyx990803** [comment]
@xiaolongyuan 这个 issue 是个合理问题。当外部插入的内容带有 v-if 的时候不管 v-if 的值是真是假，fallback 内容都不会显示。

**Comment by AnyGong** [comment]
@yyx990803 +1 我今天也需要用到这样的状况，可以加进去吗？

**Comment by xiaolongyuan** [comment]
@yyx990803 是的 仔细一看 这个还真是挺蛋疼的
@lrdbzs sorry 没有仔细看, hack 一下
```
<component>
<div slot="abc" v-if="conditions">替换的内容</div>
<div v-else>默认显示值</div>
</component>
```
当然 如果使用到到组件作用域那会很蛋疼

@mage3k 认真看下 我开始也大意了 
```
<component>
<div slot="abc" v-if="true">替换的内容</div>
</component>
```
内容变成了  "替换的内容"

**Comment by lrdbzs** [comment]
@xiaolongyuan
没关系，是我用例写得不清晰，让大家误会了。
原来写了个通用的组件，但少数地方使用时，需要替换掉通用组件的一部分。v-if,v-else是我目前的解决办法，只是感觉有点代码臃肿。
