### ISSUE TITLE
Associate multiple events

### ISSUE THREAD

**Issue by brunocascio** [vuejs/vue#2153]
Hi!

I need associate some events to one function. Actually my code is this:

```html
<button 
  type="button" 
  class="btn btn-lg btn-default"
  v-touch:press="handle(positions.LEFT, $event)"
  v-touch:tap="handle(positions.LEFT, $event)"
  v-touch:pressup="handle(positions.RELEASE_LEFT, $event)">
 LEFT
</button>
```

I would like to code it like this:

```html
<button 
  type="button" 
  class="btn btn-lg btn-default"
  v-touch="handle(positions.LEFT, $event)">
 LEFT
</button>
```

Then in my `handle(pos, event)` function:

```js
handle: function(position, event) {
  this.position = position;
  if (event.type == 'tap') {
    this._handleTap();
  } else if (event.type == 'press') {
    this._handlePress();
  } else {
    this._release();
  }
},
```

How to i make it?

**Comment by amirrustam** [comment]
@brunocascio In the future please ask questions like this within the community [forums](http://forum.vuejs.org). The issues section is for reporting bugs and discussing the development of the project. Please read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines)

It's hard to give you an optimal solution without knowing what you are actually building, but here is a quick (not the prettiest) potential solution:

```javascript
<button 
  type="button"
  v-touch="press:handle, tap:handle, pressup:handle" 
  value="LEFT">
LEFT
</button>
```
Instead of specifying `position.<DIRECTION>`, you can just use the button `value`:

```javascript
handle: function (event) {
  this.position = event.target.value;
  // now you have both the event and position to do whatever you like.
}
```

**Comment by brunocascio** [comment]
Okey thanks and sorry!

Regards!

**Comment by amirrustam** [comment]
@brunocascio nothing to be sorry about. Feel free to ask and get help anytime in the forums. Always glad to help :)

**Comment by brunocascio** [comment]
Really thanks @amirrustam. The code doesn't work, but is an error of vue-touch library. I'll open a pull-request to contribute. :)

**Comment by amirrustam** [comment]
@brunocascio Fantastic :+1:
