### ISSUE TITLE
Is there a solid reason for having a non-CSP distribution?

### ISSUE THREAD

**Issue by taoeffect** [vuejs/vue#2216]
Couldn't find much in the docs that explains reason for why there exists (by default) a non-CSP version of Vue.js. This seems like it adds extra work to the team to maintain two separate versions, and if they both do the same thing, but one is more secure than another, then I don't see why it makes sense to have the less secure version around.

**Comment by simplesmiler** [comment]
I'd like to know the answer for sure, but my guess is "performance".

**Comment by taoeffect** [comment]
> I'd like to know the answer for sure, but my guess is "performance".

I'm curious if that's the case and if so what the difference actually is. Still, security trumps performance as far as defaults go, so it would make more sense to have a "fast insecure edition" as the non-default.

**Comment by yyx990803** [comment]
First, the reason why it's not the default: perf and size. The CSP build needs a full blown parser/evaluator which makes the dist file 60% larger.

Second: non-CSP compliant != insecure. It depends on how Vue is used. The part where Vue is non-CPS-compliant is its expression parser which uses `new Function()` to generate expression getters. For this to become insecure, the user would have to be using Vue to compile non-trusted HTML content in the first place. However this is basically the same as rendering arbitrary untrusted HTML, and if the user is doing this he is already busted no matter how Vue generates expression getters, because he is busted even if Vue is CSP-compliant.

**Comment by taoeffect** [comment]
@yyx990803 Could this issue then be re-opened and turned into a request for a documentation update that shows examples of that situation (so that users know what to avoid in general, and perhaps more of an elaboration of the sorts of situations where they would prefer the CSP version)?

**Comment by taoeffect** [comment]
(And thanks for that explanation btw!)

**Comment by yyx990803** [comment]
@taoeffect feel free to open an issue (or better yet, a pull request) at https://github.com/vuejs/vuejs.org !
