### ISSUE TITLE
Named slots lose classes

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue#2306]
This might be intentional, but is never mentioned in the docs.

The use case is in the repro: https://jsfiddle.net/simplesmiler/ersbymbu/
- Component defines layout (centering with `margin: 0 auto`)
- Content defines the width

This particular use case can be solved using `.modal-component > *` instead of `.modal-slot`.

I think it would be better if **named** slots followed the rules of normal instances vs fragment instances. I.e. if content for the named slot is a normal instance, then slot attributes (including styles, classes, directives, etc) are merged onto the instance root.

Open for discussion.

**Comment by simplesmiler** [comment]
Related to https://github.com/vuejs/vue/issues/2128
> ... the only directives respected on `<slot>`s are terminal directives like `v-if`. Normal ones ... are not copied onto the inserted elements. This should be mitigated once we have programatic access to the slots. For now, you can wrap the `<slot>` in an additional element ...

Except for the cases where this will not work, like with `margin: auto` and fixed width.

---

Related to https://github.com/vuejs/vue/issues/1281
`.modal-component > [slot="content"]` is pretty much `.modal-slot` except for the specifity.

**Comment by yyx990803** [comment]
It seems `[slot="content"]` serves the purpose as a hook for styling the inserted slot content - are there any particular use case where merging directives would be useful? In general I want to limit what a component can do to inserted content - it's compiled and inserted by the parent, the child just displays it, but doesn't modify it.

**Comment by simplesmiler** [comment]
A potential use case I've stumbled upon recently is detecting changes in dimensions of the slotted element for layout purposes (and in general, detecting when an element enters or leaves the slot). I worked around this by exposing a method and detecting changes on the other side.

I guess programmatic slot API would solve that too. I think the issue can be closed for now and reviewed when the API lands.

**Comment by dustindowell22** [comment]
I want to add classes to slots for ease of styling. I have existing CSS components that I use on other components that I also want to use on this component that happens to have slots. My CSS components use variant classes to modify the look of an element. 

`class='button -blue'`
`class='button -red -shiny'`

Because of how I structure my CSS it's difficult to work around a div you can't style using classes. I have to copy all of my styles to the attribute selector in this case because I can't use any variant classes.

I really hope you decide to add classes to named slots. This would help me a ton. And thanks for all the work on Vue! It's great!

**Comment by danielsdeboer** [comment]
I ended up making a bunch of components to drop into slots. So I can do something like

```
<grid-item>
    <header-slight slot="header">header content</header-slight>

    <data-panel slot="body">
        <p>stuff</p>
    </data-panel>
</grid-item>
```

with a mixin to provide access to common components. I can set the styling in the `<data-panel>` component and drop it in where I need it instead of having to remember the exact styling of `<div class="panel is-mobile">` and all that stuff.

For my use case that's a decent compromise, my slotted component doesn't need to know about what's being slotted and I don't have to keep dropping the same classes into my components all the time.

**Comment by app-sparkler** [comment]
## This hack worked for me :

I have a `bootstrap panel component` that works with `slots - for panel-heading, panel-title, panel-body and panel-footer`.  This is what it looks like (its in Jade - you can convert it @ [http://html2jade.org] (http://html2jade.org)

**Comment by anlek** [comment]
I believe you can do:
```javascript
 div.panel-body(:v-bind="panelTitleConfig")
    slot(name="panel-body")
```

That way, you can send any property in panelTitleConfig such as `data-title="bob"` and it will show up in the div.panel-body.

(You can see this in the [vue docs](https://vuejs.org/v2/guide/components-props.html#Disabling-Attribute-Inheritance) with the `$attrs` value)
