### ISSUE TITLE
Number property disappears on render

### ISSUE THREAD

**Issue by theshaunwalker** [vuejs/vue#2386]
I'm trying to force `v-model` input to be only numbers, which I think http://vuejs.org/guide/forms.html#number is meant for.

But when I add the `number` property to an input, it disappears when its rendered. Have replicated it in the JS fiddle below.

https://jsfiddle.net/79uo6946/

Am I using this incorrectly?

**Comment by yyx990803** [comment]
The `number` param for `v-model` **converts user input to numbers when saving it to the data object in JavaScript**. It doesn't restrict what the user can input. It's removed because it's a special attribute provided by Vue.js.

If you want to physically restrict what the user can input, use `type="number"`.

**Comment by theshaunwalker** [comment]
Apologies I wasnt clear enough, I know it doesnt restrict what the user can actually input. But the input wasnt being converted to numbers when saving the data to the Vue instance, it would keep string characters in the value and result in `NaN` errors when trying to do math with them.

**Comment by yyx990803** [comment]
Well, it only converts input to number if it can. If the input cannot be parsed into a valid number, it will be saved as-is.
