### ISSUE TITLE
FilterBy not

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#2402]
Hi, I would like to request a`not` key option for the FilterBy filter. Currently it's only possible to filter by positive values and for negative would require a custom filter.  Ex: A list of products with prices, being some of them free set with `price = 0`. A list of commercial and free products could look like this:

```
// free products
...<li v-for="prod in products | filterBy 0 in 'price'"></li>
// commercial products
...<li v-for="prod in products | customFilter"></li>
```

With the new option we could just add `not` making the code much easier to read and understand.
```
...<li v-for="prod in products | filterBy 0 in 'price'"></li>
...<li v-for="prod in products | filterBy 0 not in 'price'"></li>
```

Thanks for considering.

**Comment by jbrialon** [comment]
👍

**Comment by yyx990803** [comment]
I think using `filterBy` for this specific use case if probably wrong, because filterBy is primarily used for string inclusion filtering: an item with a price like `0.5` will show up in your "free" list in this case... it's probably better to use two custom filters for this case.

On the suggestion of adding the `not` keyword - I really would like to avoid making the array filter syntax more complex - in fact today I'd encourage users to use computed properties whenever possible instead of using array filters, because computed properties give you the full power of JavaScript to do whatever you want (and gives a cached variable so you can easily get the length of the filtered result).

**Comment by miljan-aleksic** [comment]
Accepted. Thanks for the explanation :)
