### ISSUE TITLE
Why was "Vue.config.prefix" removed?

### ISSUE THREAD

**Issue by paceband** [vuejs/vue#2415]
Hi,
Is there a reason why was "Vue.config.prefix" removed? Performance issues?
In order to have our html W3C compliant, we could set it like this:
Vue.config.prefix = "data-v";
Or do you have a nice way to make it work? 
Maybe using a jQuery selector that would change all "data-v-" by "v-" in the init event?
Any ideas?
Thanks

**Comment by sirlancelot** [comment]
You could probably do so during the "beforeCompile" event, which is fired just before the element goes through Vue's compilation.

**Comment by yyx990803** [comment]
Vue directives are removed in the rendered markup, so your eventual markup will be W3C compliant.

**Comment by Haeresis** [comment]
This tips for « v- » is not anymore relevant « https://github.com/vuejs/vue/issues/221 » for Windows phone and what yyx990803 said here « https://github.com/vuejs/vue/issues/273#issuecomment-43408252 » is not relevant anymore too...

So, how I could use « data-v-* » instruction to keep « source » from server W3C Compliant in order to pass this tests for example :  https://validator.w3.org/ ?
