### ISSUE TITLE
Something about v-ref inside v-for

### ISSUE THREAD

**Issue by zyf0330** [vuejs/vue#2416]
@yyx990803 I have the same problem. And I think you should let developers decide how to name for v-ref. Developer will solve the conflict of v-ref name. Let's see below code.
Situation 1:
```
<div v-for="item in items">
  <comp v-ref:nested{{item}} :value="item"></comp>
</div>
```
We can use $refs.nested{{index}} to name them.

Situation 2:
```
<div v-for="item in items">
  <div v-for="sub in item.subs">
    <comp v-ref:nested{{item.sub}}></comp>
  </div>
</div>
```

What we need to do is add a feature to make `v-ref` accept variable.
How about that?

**Comment by yyx990803** [comment]
As I mentioned in the previous issue, `v-ref` inside `v-for` is a rabbit hole, supporting it leads to more problems than convenience when you can just give your component a class name and do `this.$el.querySelectorAll('...')`.

Also your proposed syntax won't work because mustache tags in Vue templates do not work that way: they can only appear inside attribute values or in plain text.

**Comment by zyf0330** [comment]
Ok, I will use querySelectorAll to replace, hope not to meet problem of compatibility.
I don't know the deeper detail of v-for or v-ref, just an idea from JSP Tag.
