### ISSUE TITLE
How to access global functions in component markup

### ISSUE THREAD

**Issue by ajorias** [vuejs/vue#2417]
I'm not able to access global functions in the markup of a component.

`
var mySingleton =
{
	myFunction : function()
	{
	}
}
`

`<my_component v-on:click="mySingleton.myFunction()"></my_component>`

mySingleton will be UNDEFINED because of:

`
(function(scope
/**/) {
return  scope.window.mySingleton.myFunction();
})
`

If I try to access via 

`<my_component` v-on:click="window.mySingleton.myFunction()""></my_component>`

It is still UNDEFINED because of:

`(function(scope
/**/) {
return  scope.window.mySingleton.myFunction();
})
`

Shouldn't at least case 2 work so that vue does not prepend `scope.` because I try to access `window.` ?

**Comment by Nirazul** [comment]
You can always define a component-method and do there whatever you want. You could also expose the window reference within the component's data.
Generally, it's a good thing that you can't access stuff that is not part of your scope.

**Comment by ajorias** [comment]
Yes, in a function is works as expected. But sometimes it is convenient to use it directly in the markup.

Declaring it in data works, but I do not want my singletons (complex services) to be 'reactivated'.

Regarding you concern about the scope: yes, but singletons provide generic and globally available services and as such in our case it is designed in a way that they can be used from everywhere.

I'm just wondering why vue prepends `scope.` to `window.` at all. I have the feeling (without going into the vue source) that `window.` should be some kind of exception (unless vue is dogmatic about accessing `window.` scope from the component markup).

**Comment by yyx990803** [comment]
Because implicitly falling back to globals will be a maintainability nightmare. When you look at a template you will have no idea whether a variable belongs to the component, or some globals defined by someone  you have no idea where.

**Comment by ajorias** [comment]
Understood. So what is your recommended way to access singletons from component markup without adding them to data (which would make them reactive and this is not wanted). In fact no reactivity here is intended.

**Comment by arisliang** [comment]
So what's the recommended way? Reference of a global function should be fairly easy, as is plain javascript.

**Comment by ColinLaws** [comment]
I've found that questions about conveniently accessing objects such as singletons always gets shot down in the reactive front-end community because of the principles enforced by the framework. Vue does so much to try and stop you from making bad code that it makes it hard to work with sometimes.

I never understood the idea of a maintainability from this point of view, because 95% of what I want to make a globally accessible singleton instance is stuff like lodash, jQuery, momentjs, etc. We aren't just sticking random objects onto the window and using them. Instead, you only force things to the window that make sense to be there, such as helpers (lodash, jquery, you get it).

I guess the answer is probably just to do an import every time you want that object (tons of duplicated imports, yugh), but that seems the best way to me. And if you need some kind of shared state, I would suggest using VueX. 

When it comes down to it, the Vue and collaborators tend to ignore these questions because they've answered it so many times. If people are sick of answering questions about design patterns with Vue, then just post an example on the docs. There's little to no talk about the actual patterns you should implement with Vue in their docs.

**Comment by JounQin** [comment]
`Vue.prototype.whatever = yourGreatLibrary` should work.

https://jsbin.com/pemugaketi

**Comment by juanvillegas** [comment]
Or you could as well do `Vue.prototype.window_portal = window;` ;)

**Comment by xianshenglu** [comment]
But, if I want to do something like
```vue
 <el-checkbox
      v-model="value"
      label="test"
      @change="Object.assign(config, defaultConf)"
    ></el-checkbox>
```
Then I have to do ?
```js
Vue.prototype.Object=Object
// and next time
Vue.prototype.Array=Array
//....
```
Is this mode good?

Or I can do this by:

```vue 
<template>
 <el-checkbox
      v-model="value"
      label="test"
      @change="setDefault"
    ></el-checkbox>
</template>
//...
  setDefault(){
      Object.assign(this.config, this.defaultConf)
  }
//...
```
But isn't this too troublesome? just one line code but I have to write 3 lines more? and what troubles me is that I have to think of  a new method name ...

So, I was seeking for a better recommended way? Anyone  can help?

**Comment by xianshenglu** [comment]
your solution is like `vm.Object=Object`.  I think it's not better than `Vue.prototype.Object=Object`.

**Comment by juanvillegas** [comment]
@xianshenglu if you are only using setDefault in one component, I would do like in your second example as it adds readability and its more clear to other developers reading your code.
If this is something you will use across the app, I would consider writing a little private library, loading it into the Vue.prototype object and then use it. Like so:

`Vue.prototype.MyClassThatDoesThings = MyClassThatDoesThings
`

Then, in your component's html:

`@change = MyClassThatDoesThings.setDefault(...)`

**Comment by ithieund** [comment]
Try this
Vue.prototype.global = window;

Then you can use global variable in Vue template like this
@change="global.Object.assign(A, B)"
@change="global.YourClass.yourFunction()"

Happy coding!

**Comment by juanvillegas** [comment]
Why not just Vue.prototype.window = window...?
