### ISSUE TITLE
Directive update method: bug or wrong example?

### ISSUE THREAD

**Issue by vladra** [vuejs/vue#2505]
Spent some time building select2 using vue directives, before I realised that the example either not correct, or bug is present.

Accordingly to the example in the documentation I should use `this.set(this.el.value)` to trigger update method of directive. But using this approach trigger event is not fired at all.

If I will use `this.vm.selected = this.el.value` - update method of the directive is fired properly, but on initial render it is fired twice in a row.

So if I [change selected here](https://jsfiddle.net/vladra/0mnrfLf7/) (this code is used in documentation example), `Update triggered` console event is not fired on select change.

And if I [change selected here](https://jsfiddle.net/vladra/cnu0jhv4/), I can see `Update triggered` message in console. But it is triggering twice on initial render.

Let me know please if it is working as expected and which approach is correct. Clearly I need initial event run only once, and events running on each select chane event.

Thanks!

**Comment by vladra** [comment]
Small update. It was triggering twice because of select2 plugin trigger method. So this approach works perfectly as far as I see:

https://jsfiddle.net/vladra/1esddco7/

**Comment by simplesmiler** [comment]
This does not look like a bug to me. As far as I can say `this.set` does not trigger the `update` hook by design, because otherwise there would a great risk of getting stuck in an infinite loop. The `update` is called whenever the value changes **outside** of the scope of the directive

Regarding accessing `vm` from the directive, you should never do it, because it breaks the contract of "directive may only change the expression that was passed to it", and makes things hard to debug. It also makes you directive dependent on the exact structure of the component it was applied in.

**Comment by vladra** [comment]
Thanks for an update. I've just started learning vue, it is helpful for me.

When you say that values should be changed outside of scope of the directive, what do you mean? This was initial approach I've tried to implement, but I was not able to find solution.

Select2 setup (including event) happens inside directive, so I just dont see how to track selected value inside component (which is using directive). Also accessing select2 built in functions would be a great feature in case I need some special functionality (for example reset selected value).

All together it looks like I shouldn't use directives for this kind of functionality (integrating some third party jquery libs).

**Comment by simplesmiler** [comment]
I meant that the `update` is called when someone else changes the value, as opposed to the directive itself changing the value with `this.set`. See the [example](https://jsfiddle.net/simplesmiler/0mnrfLf7/1/).

> it looks like I shouldn't use directives for this kind of functionality

On the contrary, directives are the great tool for integrating third-party libraries that operate the DOM.

---

By the way, Vue has a [gitter channel](https://gitter.im/vuejs/vue) and a [forum](https://forum.vuejs.org/), where you can get more support.

**Comment by fullfs** [comment]
@vladra You may also check out made up vue.js+select2 modules and examples:
http://vuejs.org/examples/select2.html
https://github.com/halupi/vue-select2
https://github.com/Haixing-Hu/vue-select

**Comment by Mat-Moo** [comment]
Or go native :) http://sagalbot.github.io/vue-select/

**Comment by vladra** [comment]
@simplesmiler If directives are great for integrating third party libs, how this integration should look like (in terms of select2 at least). It seems that I should change value in component, but the library who changes value is in directive. This is kinda contradiction :)

@fullfs Thanks for the links. First link to official documentation is the one I'm having problem with actually.

@Mat-Moo Thanks, this is really helpful, will check source.

Thanks for help everyone. Since this is not a bug I think this issue should be closed.

**Comment by simplesmiler** [comment]
@vladra let me try to explain.

There are actually two values. First one is "viewmodel value", second is "DOM value". First one changes when you do something like `this.selected = 1`, second changes when you pick an element from the select box UI. Directives are the means of synchronising these two values.

When directive thinks that the DOM value has changed, it calls `this.set` to tell Vue that viewmodel value should change too.

When someone else (but this directive) changes the viewmodel value, Vue calls the directive's `update`, so that directive can update the DOM value.
