### ISSUE TITLE
orderBy mutlitple parameters [fetaure request]

### ISSUE THREAD

**Issue by dcrystalj** [vuejs/vue#2518]
it would be really nice to have option for sorting like this ```user in users | orderBy 'name' 'lastName'```. if multiple users have same name they get sorted by lastname

**Comment by posva** [comment]
Hi

Thanks for the feature request!
IMO the multi-field sorting is something usual and should be implemented. The impact on size is minimal and is not a breaking change
I'm implementing the feature asap tomorrow :smile:

**Comment by rhyzx** [comment]
@posva @yyx990803 how about supporting both key and custom sort fn like `items | sortBy myComparator`, it should be more flexiable in my opinion :smiley:

**Comment by posva** [comment]
@rhyzx  I'd like to but we need to add it as a last parameter in order to be safe from a breaking change :cry: 
We can also add it as an optional first parameter but it may become harder to understand (as a filter)

Here's what I've done so far: https://github.com/posva/vue/commit/3a55f3c1e571af3deaafd1368cff02cd4744b190
At the moment I'm breaking the grid e2e example and removing the ability to use the filter with null as a parameter, although imo there's no reason to call the filter manually with `null`
I'll try to fix it this evening

**Comment by posva** [comment]
@rhyzx About the comparator function I think this should be another filter called `sort`. `orderBy` orders by keys while sort should be simplier. I'm not sure if it should be added to the main repo

**Comment by dcrystalj** [comment]
Thank you for not ignoring this request and all the effort you have put into it! 
Passing custom sorting comparator like @rhyzx said makes sense as well. I hope both features will be included in the release one day.

**Comment by posva** [comment]
@dcrystalj I appreciate you support :smile: . I've been a bit slow and I'm sorry, next time I'll handle a request faster :muscle: . As for the custom comparator I think this should be included in another filter named `sort` because making the `orderBy` filter more complex isn't a good idea. Here is the code for the sort filter: https://jsfiddle.net/posva/5ky7ec1t. By default it compares by string though as that is the default behaviour for `Array::sort`. The code have been done in about 5 minutes :sweat_smile: and it can be improved.

**Comment by 349989153** [comment]
It's very nice to have multiple fields to be sorted by the ``orderBy`` in the latest version.
Can we go further, I mean, multiple fields with multiple sort order like:
``user in users | orderBy 'name' -1 'lastName' 1``

Or maybe change the ``orderBy`` into ``orderBy chain``:
``user in users | orderBy 'name' -1 | orderBy 'lastName' 1``

**Comment by janbaykara** [comment]
@349989153 Any update on that suggestion? It'd be very welcome in a project I'm working on.

**Comment by posva** [comment]
@janbaykara This would introduce a much more complicated filter for a very specific use case (tables)
I recommend you use a computed property and order yourself or using [lodash](https://lodash.com/docs#orderBy):

```javascript
      const sort = this.orders.reduce((sorting, {column, order}) => {
        sorting[0].push(column)
        sorting[1].push(order)
        return sorting
      }, [[], []])
      return _.orderBy(this.chapters, ...sort)
```

`orders` being an array specifying which properties shall be used to sort:
```javascript
orders: [
        {
          column: '_id',
          order: 'desc'
        },
        {
          column: 'name',
          order: 'asc'
        }
      ]
```
This will lend to: `_.orderBy(this.chapters, ['_id', 'name'], ['desc', 'asc'])`

**Comment by RSamal** [comment]
return _.orderBy(this.chapters, ...sort) I am getting ReferenceError: _ is not defined
    at VueComponent. Any suggestion I tried to do npm install underscore but that did not fix the issue.

**Comment by Akryum** [comment]
@RSamal You need to include the library in the page or import it if you use a build tool:

```javascript
import _ from 'underscore'
```

Or if you want to use lodash (recommended):

```javascript
import _ from 'lodash'
```
