### ISSUE TITLE
$data replacement doesn't trigger change detection

### ISSUE THREAD

**Issue by oaleynik** [vuejs/vue#2520]
### Vue.js version
1.0.18

### Reproduction Link
http://jsfiddle.net/6byd5w3q/3/

### Steps to reproduce
1. Create simple component `my-component`
2. Pass props object with single property `myProp`
3. Pass method `update$Data` which sets `this.$data = {myProp: 'new value'}`
4. Pass template which contains input field, which is binded to myProp and button which has click handler binded to `update$Data`
5. Execute `update$Data` by pressing on the button 

### What is Expected?
`myProp` should be updated 

### What is actually happening?
`myProp` is not updated

### Extra Info
Works in 1.0.17 and bellow.

Possible cause: https://github.com/vuejs/vue/commit/d1788b98ac8dce4352e9f78810d13380449bd321#diff-b994c9d50c338882ce8ff1f2b6e6b5b5R107

**Comment by FadyMak** [comment]
Hi @oaleynik thanks for reporting this! As referenced in [this commit](https://github.com/vuejs/vue/commit/d1788b98ac8dce4352e9f78810d13380449bd321?diff=split), the message specifies that:

> No need to merge props into the data object. they should just be defined as reactive properties on the vm instance.

For that reason your code would work in 1.0.17 and not 1.0.18: the props are no longer merged in the data object. Since the data object is not initialized with a **url** property, Vue will not be able to detect the change (see [here](http://vuejs.org/guide/reactivity.html#Change-Detection-Caveats))

Have a look at this fiddle which hopefully accomplishes what you are trying: http://jsfiddle.net/fr79unq7/

(if not please feel free to re-open this issue as this is an intended affect it seems)

**Comment by yyx990803** [comment]
This is an unintentional breaking change - but let me explain:

Previously (in <1.0.17) when you define props, they are merged onto the instance's `$data` object. However, this is technically not correct because props are not part of data. As the documentation states: `vm.$data` points to the object passed in the `data` option (or returned from the `data` function). `vm.$data` should only contain the properties defined in `data`, not in `props`.

In 1.0.18, props are now only defined on the vm instance itself, not on `$data` anymore, therefore swapping `$data` would not affect props (technically, the doc never suggested it should work). You should always directly set the prop on the vm instance instead. If you need to set multiple of them, simply call `Vue.util.extend(this, { ...newProps })`.

I don't think merging props into data offers any practical usage, so this is unlikely to be reverted - but let me know if you have valid use case that specifically depend on this behavior.

**Comment by oaleynik** [comment]
@FadyMak thank you!

@yyx990803 it makes total sense, and to be honest, I had the same [way of thinking](https://github.com/imgix/motif/issues/2#issuecomment-198863793). I didn't find mentions about this in release notes and the fact that 1.0.18 is the patch release made me debating with myself - was it intentional or not. So I submitted issue and PR just "in case." 

So, since 1.0.18 `props` is the declarative way of passing initial component state (or its configuration), which is way cleaner and easier to follow.

Thanks for clarification!

**Comment by imaia** [comment]
I had a problem in my code because of this change, but it seems fair. Thanks for the explanation.
