### ISSUE TITLE
Not working "$parent" in "v-for" directive for "partial" template

### ISSUE THREAD

**Issue by PavelCSS** [vuejs/vue#2532]
What could be the problem or what am I doing wrong? https://jsfiddle.net/ZiBY/6euwb7x6/

**Comment by fullfs** [comment]
@PavelCSS Hello! I guess using `$parent` inside template string for calling a function is not quite correct :) You could do something like that: https://jsfiddle.net/6euwb7x6/1/
Though Vue considering `$parent.msg()` expression incorrect. It could be a bug.

Also, please note you could ask for tips in [Gitter](https://gitter.im/vuejs/vue) or [the official forum](http://forum.vuejs.org/).

**Comment by yyx990803** [comment]
`v-for` creates an iteration scope where `$parent` points to the outer scope - so in this case `$parent` is pointing to the child component. You will need to do `$parent.$parent` to reference the parent component.

This is something I've overlooked when assigning the $parent scope pointer - since this is an undocumented feature, it will probably be changed to `$outer` to avoid confusion. However, at the same time as @fullfs suggested, you should avoid directly relying on `$parent` in your child components and pass down data using props instead.
