### ISSUE TITLE
IE v-else <template> + table elements problem

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue#2601]
### Vue.js version
1.0.20

### Reproduction Link
https://jsfiddle.net/dnfskk5q/

### Steps to reproduce
Start example

### What is Expected?
``ok``

### What is actually happening?
```
ok
not ok
```

``<v-else template>`` with table elements inner doenst work in ie10,  I don't check over version.

**Comment by azamat-sharapov** [comment]
IE does not support `<template>`, put `v-if/else` on `tbody` instead.

**Comment by AStaroverov** [comment]
How i understand, ``<template>`` never paste in the dom, it always cut from component template or im not right?

**Comment by simplesmiler** [comment]
As a rule, `<table>` can only directly contain `<tr>`, `<thead>`, `<tbody>` and `<tfoot>`. Although having `<template>` directly inside of a `<table>` may appear to work in some cases, you should never rely on it.

**Comment by Twiknight** [comment]
Can be reproduced with MS-Edge.
It works just similar to IE in many ways

**Comment by azamat-sharapov** [comment]
http://caniuse.com/#feat=template
http://forum.vuejs.org/topic/2088/table-and-template-on-ie

**Comment by AStaroverov** [comment]
ok, thanks for fast answer.

**Comment by simplesmiler** [comment]
@azamat-sharapov fair point about the standard in the forum topic though. Looking into juicy-table-repeat.

**Comment by simplesmiler** [comment]
@azamat-sharapov either I did not look close enough, or juicy-table-repeat can only solve simple case of "tr per row", which can be more solved with `<tr v-for="row in rows">` without any issues.

**Comment by yyx990803** [comment]
Details have been explained - You can have multiple tbody inside table for this specific case though.

**Comment by azamat-sharapov** [comment]
@simplesmiler what I originally needed at that time was repeating several `tr`s on each `v-for` iteration, which can't be solved with `<tr v-for="row in rows">`. I didn't look at juicy-table-repeat too much into detail, but I thought it could be useful piece of code to do something custom to get `<template>` work in `<table>`. But as soon as somebody told me I could use multiple `<tbody>`s, it just solved my issue :)
I agree, that juicy-table-repeat might be not much help, because it looks like messing much with DOM and might not play well with Vue.
