### ISSUE TITLE
Ability to set object paths outside vm

### ISSUE THREAD

**Issue by azamat-sharapov** [vuejs/vue#2612]
### Feature request

When there are long object paths to set, `vm.$set()` comes handy: `vm.$set('a.b.c', val)`. But this works only if you are setting path on `vm`, not outside of it. If your app is state-managed via Vuex or similar library, these kind of tasks introduce verbosity:
```
if (!state.a.hasOwnProperty(b)) {
  Vue.set(state.a, b, {})
}

Vue.set(state.a[b], 'c', val)
```

Unfortunately, `Vue.set()` does not accept keypath as a second argument, it accepts single key.
You may think, that I could initiate whole object structure, but it isn't always possible and/or not best choice. Sometimes we add dynamic sub-objects into object and setting path easy like following would be useful:
```
Vue.setPath(state.a, 'b.c', val)
```

If you think this shouldn't be in Vue core, maybe it could go into Vuex core as helper?
Or, any good workaround for this? 
Thanks

**Comment by yyx990803** [comment]
In general, my recommendation is that you should avoid using `Vue.set` as much as you can. Always initialize your data structures, and only resort to `Vue.set` when you absolutely have to.

The design that `Vue.set` only supporting a single key is intentionally trying to push you away from dynamically creating nested paths at runtime. Supporting paths doesn't make it any more powerful (since you can always manually create the structure), but easier to be abused. In 2.0, `vm.$set()` (which supports paths) is also being removed.
