### ISSUE TITLE
表单input输入的为数字，却转为了字符串

### ISSUE THREAD

**Issue by ohohco** [vuejs/vue#2699]
```
<template>
  <input v-model="data.price" type="number"/>
  {{data | json}}
</template>
<script>
   ...
   data : {
     return {
       data: {price: 0}
     } 
  }
</script>
```
`input`我输入了数字比如`55`， 实际打印为`{price: "55"}`,  却不是{price: 55}

**Comment by posva** [comment]
Hi!

Not sure of what you're saying but if you want a number instead of a string, you shoud add number to the input: http://vuejs.org/guide/forms.html#number:

```html
<template>
  <input v-model="data.price" number type="number"/>
  {{data | json}}
</template>
```

Please, next time make sure to sure to ask the question on the [forums](forum.vuejs.org) or the [gitter chat](https://gitter.im/vuejs/vue). You'll get faster feedback. We try to questions out of issues :smile:
