### ISSUE TITLE
Bind is unable to access data when called on component element with replace: false.

### ISSUE THREAD

**Issue by blefevre** [vuejs/vue#2700]
I'm unable to bind directly on a Component element with `replace: false` set. 
E.g: `<comp v-bind:class="{'expanded': expand}" />`

The class is never applied even though `expand` is true.  
However, `<comp v-bind:class="{'expanded': true}" />` does apply the class.

See: https://jsfiddle.net/8rczqdee/4/

**Comment by FadyMak** [comment]
Hey there! The issue doesn't seem to be reproducible in the Fiddle you provided, since removing the `replace: false` does not add the class.

Anyhow, this doesn't seem to be the issue - instead you should take a look at the [Compilation Scope section](http://vuejs.org/guide/components.html#Compilation-Scope) in the VueJs Guide. You are trying to bind to a child property from within the parent's scope. Instead you might want to try something like this:

https://jsfiddle.net/p9aj0s55/

I hope this helps! If you feel this doesn't solve your issue, please feel free to reopen it :)

**Comment by stormhouse** [comment]
Or you can move `expand ` to it's parent scope,  try it like this:
[https://jsfiddle.net/avalon_api/d4532zat/1/](https://jsfiddle.net/avalon_api/d4532zat/1/)
