### ISSUE TITLE
Slot: access scope variables

### ISSUE THREAD

**Issue by nablex** [vuejs/vue#2704]
Suppose (as a simplified example) I have a "picker" component called "my-picker":

```xml
<template id="my-picker"
    <div v-for='item in items' v-on:click="this.$emit('activate', item)">
        <slot><button>{{ item.name }}</button></slot>
    </div>
</template>
```

Obviously this is a contrived example that oversimplifies the component but in this example suppose I want to override the default slot with something else, for example a clickable image.

```xml
<my-picker>
    <img :src="item.name + '.png'"/>
</my-picker>
```

The problem here is obviously that I don't have access to the item that is currently selected in the for loop. The same goes for other things that are available in that scope.

What I currently have as a workaround is two additional directives:

- v-store: allows you to store something, either with an argument (named storage) or without (default name)
- v-inject: allows you to inject values that have been stored, again either named or unnamed

What I do then for example is in the original component:

```xml
<template id="my-picker"
    <div v-for='item in items' v-on:click="this.$emit('activate', item)" v-store="item" v-store:next="next">
        <slot><button>{{ item.name }}</button></slot>
    </div>
</template>
```

In this example the "next" is a scope function to scroll for example (simply there as an example of the named storage).

In the replacement I do this:

```xml
<my-picker>
    <img v-inject:goNext.literal="goNext" v-inject.literal="myItem" :src="myItem.name + '.png' v-on:click="goNext"/>
</my-picker>
```

This works pretty well but there are some edge cases and it all feels a bit heavy handed. All we want is to be able to replace slots completely while being able to (specifically, not generally) access items in the scope of the original template.

Did we miss some crucial feature that already allows this or can this be added?

**Comment by simplesmiler** [comment]
You can achieve similar behavior by passing an `item` component as a prop instead of using slots: https://jsfiddle.net/simplesmiler/5p420nbe/

**Comment by yyx990803** [comment]
^ @simplesmiler 's solution is what is best available in the current version of Vue.

If you think about it like JavaScript, it's the difference between passing a value already evaluated in the parent scope vs. passing a function that takes some arguments from the child scope and then return the value.

This will be addressed in a future version, but I don't intend to introduce other sub-optimal solutions for now.

**Comment by nablex** [comment]
The alternative method is indeed a clean solution in some situations but the problem there is that the naming of the component has to be in line with what the wrapper component is offering.

This will lead to a lot of superfluous component generation and worse, when reusing an existing component you may need to wrap it in a new one to get the naming correct.

I look forward to said future version!

**Comment by mohamedelaazioui** [comment]
Just as an update: we've removed most of the corner cases from the directive implementations though they can probably be optimized with more intimate knowledge of the core. I think it is a cleaner solution than the component approach proposed above because in the directive case the component simply exposes additional data/methods/... much like it already exposes slots/props/... to anyone using the component. It is as much part of the API of the component as is the rest: it has to be pro-actively shared by the component with a specific name, you can not access any random state.

In our case we have built a "list" component that allows you to do anything from an image slider to button picker to actual data lists with optional lazy loading, windowing, multi select,... But such functionality requires outside access to specify how it should work in some cases, for example which parts have to be interactive (e.g. clickable), or for example if you want to add swipe support.

For example a slider with a window set to a fixed size of 2 with a scroll size of 1 (the default selector is not windowed). As you can see in this example we want to scope which part has the mouse-click interaction and we add swipe support to trigger previous & next browsing functionality.

```xml
<n-list v-on:activate="showDetails" :items="items" :selector="new Window(2, 1)" class="carousel">
	<div v-inject="item" v-inject:next="next" v-inject:previous="previous" v-inject:toggle="toggle">
		<n-img :src="item.attachments[0].url" v-touch:swipeLeft="next" v-touch:swipeRight="previous" v-on:click="toggle(item)"></n-img>
		<span class="caption">{{ item.name | translate }}</span>
		<div class="actions"><button class="remove" v-on:click="remove(item)">Remove</button></div>
	</div>
</n-list>
```

**Comment by akshara** [comment]
Just as an update: we've removed most of the corner cases from the directive implementations though they can probably be optimized with more intimate knowledge of the core. I think it is a cleaner solution than the component approach proposed above because in the directive case the component simply exposes additional data/methods/... much like it already exposes slots/props/... to anyone using the component. It is as much part of the API of the component as is the rest: it has to be pro-actively shared by the component with a specific name, you can not access any random state.

In our case we have built a "list" component that allows you to do anything from an image slider to button picker to actual data lists with optional lazy loading, windowing, multi select,... But such functionality requires outside access to specify how it should work in some cases, for example which parts have to be interactive (e.g. clickable), or for example if you want to add swipe support.

For example a slider with a window set to a fixed size of 2 with a scroll size of 1 (the default selector is not windowed). As you can see in this example we want to scope which part has the mouse-click interaction and we add swipe support to trigger previous & next browsing functionality.

```xml
<n-list v-on:activate="showDetails" :items="items" :selector="new Window(2, 1)" class="carousel">
    <div v-inject="item" v-inject:next="next" v-inject:previous="previous" v-inject:toggle="toggle">
        <n-img :src="item.attachments[0].url" v-touch:swipeLeft="next" v-touch:swipeRight="previous" v-on:click="toggle(item)"></n-img>
        <span class="caption">{{ item.name | translate }}</span>
        <div class="actions"><button class="remove" v-on:click="remove(item)">Remove</button></div>
    </div>
</n-list>
```

**Comment by nablex** [comment]
Just as an update: we've removed most of the corner cases from the directive implementations though they can probably be optimized with more intimate knowledge of the core. I think it is a cleaner solution than the component approach proposed above because in the directive case the component simply exposes additional data/methods/... much like it already exposes slots/props/... to anyone using the component. It is as much part of the API of the component as is the rest: it has to be pro-actively shared by the component with a specific name, you can not access any random state.

In our case we have built a "list" component that allows you to do anything from an image slider to button picker to actual data lists with optional lazy loading, windowing, multi select,... But such functionality requires outside access to specify how it should work in some cases, for example which parts have to be interactive (e.g. clickable), or for example if you want to add swipe support.

For example a slider with a window set to a fixed size of 2 with a scroll size of 1 (the default selector is not windowed). As you can see in this example we want to scope which part has the mouse-click interaction and we add swipe support to trigger previous & next browsing functionality.

```xml
<n-list v-on:activate="showDetails" :items="items" :selector="new Window(2, 1)" class="carousel">
    <div v-inject="item" v-inject:next="next" v-inject:previous="previous" v-inject:toggle="toggle">
        <n-img :src="item.attachments[0].url" v-touch:swipeLeft="next" v-touch:swipeRight="previous" v-on:click="toggle(item)"></n-img>
        <span class="caption">{{ item.name | translate }}</span>
        <div class="actions"><button class="remove" v-on:click="remove(item)">Remove</button></div>
    </div>
</n-list>
```

**Comment by decademoon** [comment]
@simplesmiler Wow I did not know that `<component>` can reference a component specified inside a prop, I thought it had to reference a predefined component inside `$options.components`.

**Comment by Nirazul** [comment]
@simplesmiler I thought that `:is` only accepts a string. This should definitely be in the docs, as this looks really helpful in some situations!

**Comment by decademoon** [comment]
How will this be addressed in Vue 2.0?

**Comment by atian25** [comment]
hei, @nablex where can I find `v-inject`?

**Comment by aristidesfl** [comment]
Do you seen any problem in using `Vue.extend(item)` instead of `$options.components.item`?
https://jsfiddle.net/jbrdxg5b/

**Comment by blocka** [comment]
Now that vue 2.0 is getting really close, it would be nice to know what there is to offer as far as this.

My current pattern is to pass a function in as a prop and render with that function:

```
<ComponentWithDataIWant render={data => <div>{JSON.stringify(data)</div>}></ComponentWithDataIWant>
```

This is similar to the "function as child" pattern in react, conceptually, although it would be great if there was first-class support, like react has.

```
<ComponentWithDataIWant>
{{data => <div>{JSON.stringify(data)</div>}}
</ComponentWithDataIWant>
```

**Comment by tsalkakis-d** [comment]
How about adding the functionality of props inside slots?
`<slot :name="item.name"></slot>`
It's like using the prop component, only simpler and shorter.

**Comment by rayrutjes** [comment]
I'd be really interested to know if @simplesmiler solution here https://jsfiddle.net/simplesmiler/5p420nbe/ is still the more elegant way to go about this in Vue.js 2

The ability to be able to create a dynamic slots is key to good component re-usability, I think this topic deserves a little section in the documentation ;)

Current docs made me believe the only way to achieve this was by using some custom logic inside the render function.

**Comment by svedova** [comment]
@rayrutjes I used @tsalkakis-d's solution. It is actually quite elegant and simple. I have a component where I pass a list of users, and created a slot like `<slot :name="'user' + userId"></slot>` where userId is the id of the user which is currently in the loop. From the parent component, I simply specify `<span :slot="'user' + userId">here is my data<span>` and voila, we're done.

**Comment by blocka** [comment]
This is now implemented in 2.1.0...no need for bespoke solutions

**Comment by svedova** [comment]
Oh, apparently there are now scoped slots. Good. Everyday there is a new feature here on vue :)

**Comment by aristidesfl** [comment]
Vue removes 2 way filters, adds scoped slots.. strange decisions.

**Comment by rayrutjes** [comment]
> This is now implemented in 2.1.0...no need for bespoke solutions
@blocka are you saying we can now loop over non named slots?

**Comment by blocka** [comment]
Come again? You can't have more then one non named slot by definition.

**Comment by aqhjh** [comment]
how to use slot and v-model
