### ISSUE TITLE
Why not using HTML5 data-* attributes

### ISSUE THREAD

**Issue by SeriousM** [vuejs/vue#273]
Hi, is there a good reason why you don't go with the [`data-*`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#data-*) attributes and invent your own standard with `v-*`?

From https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes:

> In addition, search crawlers do not index data attributes' values.

**Comment by MinonHeart** [comment]
It casue an error when I use use ```Vue.config({ prefix: 'data'})``` to overwrite ```v-*``` (Vue 1.0.16 csp), and I found noting related to this in document.

**Comment by yyx990803** [comment]
@MinonHeart you are looking at an old issue and that config option has been deprecated long time ago. The short answer is you can no longer configure the prefix, because `v-` attributes are removed when rendered anyway.

**Comment by xMort** [comment]
I would welcome this feature. Any attribute that is not in HTML specification or starts with _data-*_ prefix is not valid. Your IDE will also complain about this and I don't like warnings in my code :(

Here is simple demo in the latest IntelliJ IDEA
![image](https://cloud.githubusercontent.com/assets/1880148/14915831/1de26a84-0e16-11e6-8271-99e8ae069066.png)

**Comment by posva** [comment]
@xMort Actually it's valid HTML but there're a lot of IDEs and editors that does not respect the spec. I couldn't find the spec so I couldn't share it 😢 , sorry

**Comment by alanondra** [comment]
>Actually it's valid HTML but there're a lot of IDEs and editors that does not respect the spec.

No, it's not. All custom attributes not belonging to a declared XML namespace must be prefixed with `data-` and must be `[a-z]+(-[a-z]+)*`.

**Comment by FibreFoX** [comment]
Am i right, that these specs are the ones talked about?
XML-Spec: https://www.w3.org/TR/2011/WD-html5-20110525/infrastructure.html#xml-compatible
HTML-Spec: https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes

**Comment by yyx990803** [comment]
Note the difference between **valid HTML syntax** vs **fully-valid HTML**. The former means it adheres to the syntax constraints laid out in the spec, and only the syntax; the latter entails following the spec to every extreme detail, e.g. if an element doesn't have a certain attribute then you cannot use it on that element.

At the syntax level attribute names are defined [as follows](https://www.w3.org/TR/html5/syntax.html#attributes-0):

> Attributes have a name and a value. Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, U+0022 QUOTATION MARK ("), U+0027 APOSTROPHE ('), ">" (U+003E), "/" (U+002F), and "=" (U+003D) characters, the control characters, and any characters that are not defined by Unicode.

So all Vue templates are valid HTML at the syntax level. We have practical reasons to do that because it enables any spec-compliant HTML parser to be able to parse Vue templates - this makes it possible to reuse excellent HTML-based tools already out there in all aspects of tooling. However, it is my opinion that **striving for fully-valid HTML in a templating syntax is completely pointless**, because the template is not what eventually gets rendered in the browser. Making your templates fully valid HTML has zero practical benefits except for maybe getting rid of the warnings from your overly-rigorous IDE.

**Comment by alanondra** [comment]
And it is my opinion that a page's first render (before any JS events fire) should be free of broken HTML in the event that the dependent Javascript fails to render or clean up its mess. Few things are uglier than seeing a JS framework fail to render and having a jumbled mess of template tag soup and half-functioning elements. Then there's the idea that [adding exclusive attributes/prefixes adds an additional attack vector](http://www.slideshare.net/x00mario/es6-en). Then again, I may be in a [minority position](https://www.christianheilmann.com/2015/02/18/progressive-enhancement-is-not-about-javascript-availability/) these days.

**Comment by Grimy** [comment]
> Note the difference between valid HTML syntax vs fully-valid HTML.

The spec makes no such distinction. There’s only one conforming class for documents (2.2.1):

> Conforming documents are those that comply with all the conformance criteria for documents.

One of these conformance criteria is (3.2.1):

> Authors must not use elements, attributes, or attribute values that are not permitted by this specification

This means that documents using the `v-model` attribute are non-conforming. However, this may not matter: conforming user-agents are still required to parse the `v-model` attribute as intended.

**Comment by FibreFoX** [comment]
Maybe it would be a good idea to document this design-decision somewhere inside the vue-documentation. As the attributes are not "XML-attribute"-compatible (because they are containing the colon sign U+003A) this must have been decided sometime in the past.

Any relation to some specs for HTML5 would be nice, there seems a lot of confusion about this whole "data-" thing. Don't get me wrong, I used to understand HTML differently, but it seems to "just work" inside the browsers ... but fails for syntax-checker even like the [w3c-markup checker](https://validator.w3.org/). I tried some dummy website of mine, how the syntax checker sees some `v-on:click` and attributes, and it fails with errors like `Attribute v-if not allowed on element div at this point.`.

Could we (developers) please have some references where the design-decision are coming from?
(and yes, it feels a bit odd to "discuss" this on some closed issue ...)

**Comment by Haeresis** [comment]
I understand what @yyx990803 said when he say : 

- Vue template respect the **valid HTML syntax**
- The output of Vue (e.g. generating it from SSR) respect the **fully-valid HTML** to allows all indexer to correctly understand the code OK.

Fine.

So what about `server-rendered="true"` property that is generated at the final HTML render ? That is the only thing that not allows my page to be **fully-valid HTML**.

What is the exact role of `server-rendered="true"` ? Could not be a way to generate it into `data-server-rendered="true"` ?

If I remove it like that using `response.send(renderer.renderToString(...).replace('server-rendered="true"', ""))`, which side-effect after ?

And how remove it with the `renderer.renderToStream` method because this is « lost » into chunck part.

**Comment by assunluis80** [comment]
WTF! Just make the things RIGHT. And give the dev the possibility to use data-v-* instead of your v-* which IS NOT A VALID HTML!!!

**Comment by yyx990803** [comment]
@assunluis80 thanks for commenting on a 3 year old issue in a completely non-constructive fashion.
