### ISSUE TITLE
Children components destroyed before animation ends on parent

### ISSUE THREAD

**Issue by lbineau** [vuejs/vue#2733]
### Vue.js version
1.0.20

### Reproduction Link
http://codepen.io/lbineau/pen/eZLezN

### Steps to reproduce
- Parent component (Foo)
- Child components (Bar)
- Trigger a transition on Foo
- Look for destroyed trigger in both parent and child component

### What is Expected?
Children components should be destroyed after transition ends on parent

### What is actually happening?
Children components trigger destroyed before transition ends on parent

Is it something normal ? Because I would want the children component continue to be updated during the transition out.
Thank you

**Comment by yyx990803** [comment]
Vue actually intentionally prevents a component in a destroy transition from updating because it would look weird from a UX perspective.

Also from the programming perspective, transitions should ideally be fire and forget. The moment a component is sent on a destroying transition, it should be considered destroyed. If there's anything you'd like to do when the transition finishes, it should be done in the transition's `afterLeave` hook.

This is likely a wontfix, but feel free to provide more information on the specific use case.
