### ISSUE TITLE
Watch Array fires when updated with same value

### ISSUE THREAD

**Issue by kvdmolen** [vuejs/vue#2775]
## Problem
When an `Array` is updated, for example using `$set()`, the `$watch` is fired, also when the Array is the same. This is not the case for `String`.

## Example
https://jsfiddle.net/2p4yp4cb/1/

```js
new Vue({
    el: '#app',
    data: {
        array: [],
    },
    watch: {
        "array": function(){
            // Always fires
        },
    },
    methods: {
        set: function(){
            this.$set("array", [])
        }
    }
});
```
## Expected

I would expect `$watch` to only update when the actual value is updated.

## Proposal

Perhaps an extra option `compare: true` could be useful for Objects and Arrays?

## Version
1.0.21

**Comment by indus** [comment]
Because an Array is not a primitiv value the two Arrays are not the "same value". If you store a reference to a single Array and use it in the $set function nothing happens (as you would have expected): https://jsfiddle.net/2p4yp4cb/4/

And I think a boolean value can´t express all possible forms of comparison either. It would get overcomplicated really fast: ```compare: "identity" | "shallow" | "deep" | customFn(a, b) {}```

**Comment by azamat-sharapov** [comment]
You can watch array's length prop.

**Comment by yyx990803** [comment]
What you are asking for is basically a diff between the values, which is expensive, and in most cases indicating that you are approaching the problem from a wrong angle. In most cases you shouldn't need to care about the detailed difference between the values when working on UI.

If you do need diffing for legit reasons, you will have to implement that yourself - as @indus pointed out, structural diffing is not a trivial problem.
