### ISSUE TITLE
V 2.0 performance compared: Am i missing something?

### ISSUE THREAD

**Issue by boussou** [vuejs/vue#2787]
(Since the other issue was closed)

V2 is announced as **faster**.  I re-built the Circle benchmark to test it (it's on Evan's fiddles)

- v0.10 http://jsfiddle.net/azimuth/4u9pLhy3/4/
- v2.0 http://jsfiddle.net/azimuth/tofnsu5e/4/

It is not obvious that 2.0 is faster ;-(
Am I missing something?

**Comment by smolinari** [comment]
2.0 is still alpha. I'd wait to be making this benchmark, until it is GA or at least when it is at an RC stage. :smile: 

Scott

**Comment by rigor789** [comment]
Not sure what you get, but for me vue v2.0 is at least 2ms faster than vue v0.10. Also it's alpha so things will probably change :)

**Comment by smolinari** [comment]
Yeah, and a proper comparison should be against 1.0.21.

Scott

**Comment by boussou** [comment]
I got old apps that are still using v0.10 and v0.12.
i'll upgraded when I'll be forced to do so.

besides, I don't see why it should necessarily be against 1.0.21.
You people still believe that a higher version number means **better**.
Sometimes it just means "Bloated++" (I am not talking about vue).

**Comment by phanan** [comment]
As the issue list of this repo is exclusively for bug reports and feature requests, I'm going to close this "issue." You guys can continue discussing about benchmarks in the forum, or gitter.

**Comment by boussou** [comment]
I won't. 

Because to me, performance as it is "advertized" is a feature.

**Comment by jonagoldman** [comment]
@boussou performance for version 2.0, not for the alpha, not for the beta.
besides that, you are talking "advertized" like you have paid for something.

**Comment by boussou** [comment]
Did you see the quotes?

**Comment by yyx990803** [comment]
@boussou you seem to have some serious misunderstanding of how benchmarks work...

On my machine, the Vue 2.0 version runs almost as fast as the **raw js** version. What does that mean? That means the **overhead from the framework** is already almost negligible in this specific benchmark. No matter how "fast" a framework is, it cannot magically make the browser itself faster. If it takes the browser itself 6ms to move 100 circles, then it's impossible for Vue to make it 5ms.

The reason you are not seeing big improvements from previous versions of Vue is because **Vue was already that fast in previous versions**. So basically, this specific benchmark is a very bad choice for measuring perf improvements between Vue versions.

Also, never draw conclusions from a single micro-benchmark, because most benchmarks test a very narrow scenario that cannot reflect the overall performance of the framework. In most cases they are also very different from the typical usage patterns in real applications.

If you are really interested, you should be looking at the `benchmarks` folder in the next branch and compare those.

**Comment by boussou** [comment]
Evan,
I know you are the creator of Vue, but please stay away from a condescending attitude.
I am a promoter of Vue for several years, because it is a smart piece of code.

That's obvious that a framework cannot run as fast as the raw js version (Unless using special browser feature). Indeed what I wanted to see here **IS** the overhead from the framework and the performance gain of the incoming 2.0. 

I really believe that Vue.js is very fast, faster than angular. And moreover it is far easier to maintain (despite the numerous API changes during the 0.x versions. but that's the meaning of the zero ;-)
I can also say that the angular version, because it is hacky, is "unfair" vs vue version which uses **real composents** and **calculated** fields. Still vue is faster.

Ok, benchmarks are always wrong, because of the benchmarking protocol, the env, etc.
ie I always run each on a new tab.
Yet we need **numbers** to compare. I think here absolute values are useless, but relative values are informative. And I think that's always better than following blindly the "trends".

**Comment by yyx990803** [comment]
What I did was explaining why it's a bad benchmark choice to measure Vue 2.0 perf. Now before you complain about my attitude, take a minute to reflect on your own entitled attitude of "I demand proof that Vue 2.0 is indeed faster". Respect needs to be mutual and I only pay respect to where it's due.

**Comment by boussou** [comment]
^_^

I'll leave you the last word as a sign of respect then.
