### ISSUE TITLE
v-model does not update value when external input/change event is fired on a checkbox

### ISSUE THREAD

**Issue by djam90** [vuejs/vue#2804]
### Problem
A checkbox input with v-model does not update the value when an "input" or "change" event was triggered externally, whereas this does work with a text input element.

### Vue.js version
1.0.21

### Reproduction Link
http://jsfiddle.net/7ud6jL42/3

### Steps to reproduce
Click the button titled "Uncheck the checkbox" and the button titled "Fill text".

### What is Expected?
The value of `foo` should change to false and the value of `bar` should change to "foobar".

### What is actually happening?
The value of `foo` stays false whereas the value of `bar` changes to "foobar". It appears that the v-model does not pick up the fired "input" or "change" event on a checkbox input element but it does on a text input element.

**Comment by yyx990803** [comment]
This is a jQuery problem, `trigger` doesn't dispatch native events in some cases. See: http://stackoverflow.com/questions/21290775/jquery-el-triggerchange-doesnt-fire-native-listeners

**Comment by simplesmiler** [comment]
I will add another note: `checkbox` does not emit `input` event, only `change`.

**Comment by flyyang** [comment]
Sorry for buzz..

After reading this i have no clue on how to update the v-model when i update the checkbox by JavaScript.

I tried the document.

http://vuejs.org/guide/forms.html#Radio

With code like this.

```
var example4= document.getElementById("example-4")
example4.firstElementChild.checked=true
```

The v-model not updated accordingly. 

What should i do without jQuery?

**Comment by posva** [comment]
@flyyang You should directly update the model and never change the element variables manually

**Comment by texelate** [comment]
@yyx990803 Thanks for this — you saved me some headaches.

**Comment by mykeels** [comment]
Just in case someone else stumbles upon this, you can make sure the model is updated by using:

```js
elem.dispatchEvent(new Event('input')) 
```

for `<input>` and `<textarea>`

or

```js
elem.dispatchEvent(new Event('change')) 
```

for `<select>` elements

**Comment by atilkan** [comment]
@mykeels nice, where do you write these.

**Comment by mykeels** [comment]
I think it can be anywhere @atilkan, as long as you have a direct reference to the element in question. Placing a `ref` attribute on the element in question should work.

E.g. in this vue component ...

```html
<template>
  <input type="checkbox" ref="checkbox" />
</template>

<script>
  export default {
    mounted () {
      //you can directly reference the checkbox via its ref attribute value:
     console.log(this.$refs.checkbox)
   }
  }
</script>
```

---

You could also reference it from a different component directly (not advisable) if you have direct access to this component like:

```html
<template>
  <div>
    <MyCheckbox ref="myCheckbox" />
  </div>
</template>

<script>
  import MyCheckbox from './path/to/checkbox.vue'
  export default {
    components: {
      MyCheckbox
    },
    mounted () {
      const myCheckbox = this.$refs.myCheckbox //references the MyCheckbox component
      const checkboxElement = myCheckbox.$refs.checkbox //references the input[type='checkbox'] within the MyCheckbox component
      checkboxElement.dispatchEvent(new Event('change')) //to trigger the "change" event
    }
  }
</script>
```

---

If you must trigger the event from an external component, I'd suggest using vue's event emitters rather than a direct reference, to keep your components clean.

---

Also, it looks like the fiddle link doesn't work anymore @djam90 ... the [URL](https://rawgit.com/yyx990803/vue/master/dist/vue.js) for the vue script is broken.

**Comment by devtalcorp** [comment]
I got the 'input' event emit to happen when the checkbox value changes by using a computed for the template input.
```
            inputValue() {
                this.$emit('input', this.value);
                return this.value;
            }
```

**Comment by huuthang1993** [comment]
@mykeels update his answer : 
use `elem.dispatchEvent(new Event('change'))`  for check box and radio input.

**Comment by Sigma-90** [comment]
I think this should be re-opened, the issue is still present and is actually not releated to jQuery, which was the argument given for closing this. Vue not being able to react as expected to externally invoked events is especially problemeatic when we are talking about things like Selenium-driven regression testing, cross-app interaction for Vue-based Widgets, and many other things.

Check out this fiddle to see the problem in action:
https://jsfiddle.net/Sigma90/f9j5a8ny/58/

The first checkbox uses "v-bind:checked" and "v-on:change", the second one uses "v-model". Calling "dispatchEvent(new Event('change'))" on the first one changes the data, the same operation on the second one does nothing, despite the fact that the documentation and the previous commenter both state that the change event should work.

**Comment by Ethanjfobrien** [comment]
this is also causing the vue-test-utils setValue method to fail tests where the element's binding breaks after calling setValue (which uses trigger under the hood: https://vue-test-utils.vuejs.org/api/wrapper/#setvalue)

**Comment by Or-toolszion** [comment]
> I will add another note: `checkbox` does not emit `input` event, only `change`.





https://jquerys.space/questions/identify-updated-selections-in-a-dropdown-menu-using-jquery
