### ISSUE TITLE
[Vue parser]: Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead.

### ISSUE THREAD

**Issue by zwl1619** [vuejs/vue#2812]
I change vuejs 1.0 to 2.0,there is an error like this:
```
[Vue parser]: Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead.
```
What might be the problem?

**Comment by yyx990803** [comment]
As the message suggests: change `<div id="{{ id }}">` to `<div :id="id">`.

Please do not use issues to ask simple questions like this in the future.

**Comment by zwl1619** [comment]
ok,谢谢。

**Comment by teckel12** [comment]
But it doesn't work.  Trying to do the following:

`<div v-for="unit in board.units" id="col{{$index}}">`

But getting the error: "Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead." 

What should be simple, Vue is making complicated and unknown.

**Comment by zjhiphop** [comment]
Got same problem, not found solution yet.

**Comment by yyx990803** [comment]
@teckel12 maybe if you've read the [docs](http://vuejs.org/guide/syntax.html) you will find that it's not complicated nor unknown.

**Comment by phanan** [comment]
@teckel12 @zjhiphop It's actually very simple as long as you read the doc, or at least the [migration guide](http://vuejs.org/guide/migration.html#v-for-Argument-Order-for-Objects). Normally I'm not a fan of using the issue list for support, but since you were saying it was complicated/unknown, [here's a fiddle](https://jsfiddle.net/phanan/arhz8e8t/). Please note, though, that just because it's doable doesn't mean you should do it – setting ID's on the fly is often unnecessary.

---

To keep the issue list clean, I'm locking this from further discussion. You're welcome to open a thread on [our very active forum](http://forum.vuejs.org/). 😃
