### ISSUE TITLE
feature request: control the two-way binding for v-model

### ISSUE THREAD

**Issue by kazupon** [vuejs/vue#2845]
sometimes, we want to control two-way binding of v-model with bind the value (`false` or `true`) to a dynamic property on the Vue instance.
related issue: https://github.com/vuejs/vue-validator/issues/149

### use-cases
form field validation

### case1: vue-validator
```html
<validator name="validation1">
  <input type="text" :sync="$validation1.username.valid" v-model="user.name" v-validate:username="{ minlength: { rule: 32 } }">
</validator>
```

### case2: user custom validation
```html
<input type="text" :sync="valid" v-model="user.name" @input="onInputValidator">
```

```js
new Vue({
  ...
  data: {
    user: {
      name: ''
    },
    valid: false
  },
  methods: {
    onInputValidator: function (e) {
      this.valid = e.target.value.length > 32
    }
  }
})
```

### spec
- if `sync` attribute value is `true`, two-way binding of v-model become enable. data **is updated** when occured user input events,
- if `sync` attribute value is `false`, two-way binding of v-model become disable. data **is not updated** when occured user input events,

**Comment by yyx990803** [comment]
To be honest I don't like this idea: the vm state has nothing to do with whether the validation failed or not. Suppose we implement this, now when a validation fails, the vm will have the last valid value, but that value is hardly useful because it may be incomplete, and is not what the user is seeing on the screen.

Basically, I didn't see a convincing use case in vuejs/vue-validator#149 to warrant yet another extension to `v-model`, which in itself is already quite complex.

BTW - in 2.0, I think the better way to handle validation is shipping a `<validated-input>` component that works with `v-model`.

**Comment by kazupon** [comment]
Thanks feedback.
I got it. :)
