### ISSUE TITLE
Videos with the autoplay attribute are played twice.

### ISSUE THREAD

**Issue by manudurgoni** [vuejs/vue#2851]
Hello,

this is a really strange bug. 

When I have a video with the autoplay attribute in a template :

```
var Foo = Vue.extend({
    template: '<video autoplay controls src="http://vjs.zencdn.net/v/oceans.mp4"></video>'
})
```
There is one video tag in the dom, but it looks like two videos play simultaneously. 

Let me explain, if you try to pause the video, it works for the video in the dom. But there's another (invisible) video that is still playing.

If I do that :

```
var Foo = Vue.extend({
    template: "<video autoplay controls :src=\"'http://vjs.zencdn.net/v/oceans.mp4'\"></video>"
})
```

No problems.

Any ideas of what happens ?

### Reproduction Link

https://jsfiddle.net/cLc0s9aj/8/

### Vue.js & vue-router.js version
1.0.22, 0.7.13

PS: sorry for my poor English!

**Comment by phanan** [comment]
This is not a Vue problem per-se. Take a look at this bin: https://jsbin.com/nuqoxuheba/edit?html,output. You'll notice that it suffers from the same problem. 

My best take to explain this would be: When you create a `video` element with `autoplay` attribute set to `true`, it's loaded into memory and played right away, hence the "invisible" video. The reason why the second video doesn't suffer from this "bug" is, actually the `src` is invalid, and only becomes valid after Vue's interoperation.

**Comment by yyx990803** [comment]
When parsing the template, Vue creates a cached version of it in memory without attaching it to the DOM. It seems the `autoplay` attribute makes the video play even if it's not in DOM, and unfortunately there's not much we can do in Vue 1.x to deal with that. For now what you can do is instead of autoplay, start the video in the component's `ready` hook.

Note this won't happen in Vue 2.0 because we no longer cache real template fragments.

**Comment by manudurgoni** [comment]
Thanks a lot for the explanation 👍 .

**Comment by nicoladl** [comment]
I have the same issue with Vue v2.4.4 and Nuxt
https://github.com/nuxt/nuxt.js/issues/2391
