### ISSUE TITLE
filterBy issue with $index in new list

### ISSUE THREAD

**Issue by grelu** [vuejs/vue#2860]
### Vue.js version
1.0.23

When I filtering my users (by filterBy), the $index don't move with a user. So, when I editing the user, it's an other user is printing (sorry for my english...).

`v-for='personne in personnes |filterBy searchNom'><br/>
                <span class='cursor' v-on:click="editer($index)">{{ personne.Nom }} </span>`

Thanks your help

**Comment by artfuld** [comment]
Could it be that the method editer is using the index-id without filtering personnes first?
Cause $index is just the row of the current object, you probably should do something like on:clik="editer(personne.ID)" instead and get the user by ID.

**Comment by grelu** [comment]
Don't work.

It's not possible to use $index with filterBy for select a user ?
I use personne.Id for the back-end, yes. But in html view, i want just use $index of vuejs.

This is my method "editer" 

`

		  editer: function(index) {

				this.inputNom = this.personnes[index].Nom;

				this.inputPrenom = this.personnes[index].Prenom;

				this.inputId = this.personnes[index].Id;

				this.vider = true;

				var object = this.$els.modif;

				Vue.nextTick(function() {

					object.focus();

				});	

		  },
`

**Comment by phanan** [comment]
Can you provide a js bin?

**Comment by artfuld** [comment]
If you change 
on:click="editer(personne)"
and then 
editer: function(pers) {
this.inputNom = pers.Nom;
this.inputPrenom = pers.Prenom;
this.inputId = pers.Id;
....

That should work.

If I'm correct, $index is only the number of the current row, so if you have a list with the people
A, C, B
And you sort it in your list
A = $index 0
B = $index 1
C = $index 2

But in the backside it's
A = $index 0
C = $index 1
B = $index 2

That's why the $index does not correlate.

**Comment by grelu** [comment]
Yes, it's ok, thanks you artfuld !!

**Comment by phanan** [comment]
Great, thanks @artfuld. I'm going ahead to close this now.
