### ISSUE TITLE
Merging data reactively

### ISSUE THREAD

**Issue by bopjesvla** [vuejs/vue#2897]
There seems to be no way to use Vue's merge strategies when assigning new data to a mounted instance. Mixins and `vm.$options = Vue.util.mergeOptions(vm.$options, {data: x => newData}, vm)` aren't reactive.

Something like `vm.$merge(newData)` or `vm.$mixin({data: newData})` would be nice. The ability to add mixins on the fly would make Vue very flexible (`vm.$mixin({computed: {x: newFn}})` would be a neat way to reactively change `computed` functions, for example), but `$merge` is probably much easier to implement.

**Comment by yyx990803** [comment]
I don't like the idea of runtime mixins, because it makes your components' behavior unpredictable depending on when mixins are applied.

Merging data and merging options are totally different concepts. Data is per-instance state, options is like the class definition of your component.

As for merging data, it is recommended to just replace the original object with the new data:

``` js
vm.$data = Object.assign({}, vm.$data, newData)
```

**Comment by danieldiekmeier** [comment]
If anyone lands here after a Google search: Replacing root $data is not supported in Vue 2. See this comment: https://github.com/vuejs/vue/issues/2898#issuecomment-226570747

**Comment by sirlancelot** [comment]
Or the documentation: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by danieldiekmeier** [comment]
@sirlancelot It says nothing about replacing the root `$data` on there, but thanks!

**Comment by sirlancelot** [comment]
Second paragraph under the Change Detection Caveats section.

**Comment by danieldiekmeier** [comment]
Oh, I see. Sorry, that‘s not what I meant, I was talking about Evan‘s answer, not the original question.

Because if you do

```
vm.$data = Object.assign({}, vm.$data, newData)
```

in Vue 2, it will throw an error explaining that _replacing_ (not adding to) the root state is not allowed. That‘s not the same thing, and the _replacing_ part is not explained in the docs.
