### ISSUE TITLE
Replacing root data causes mayhem

### ISSUE THREAD

**Issue by bopjesvla** [vuejs/vue#2898]
https://jsfiddle.net/evq3w04e/1/

**Comment by FadyMak** [comment]
Could you provide some more details as to what you're expecting? In general you shouldn't be replacing the root data but instead update the properties within it.

**Comment by yyx990803** [comment]
Before this is fixed - I'd suggest avoid accessing `$root` properties like this. Either pass props, or reference via an object nested under `$root`:

``` html
{{ $root.sharedState.msg }}
```

``` js
$root.sharedState =  { msg: 'xxx' }
```

**Comment by bopjesvla** [comment]
Alright, thanks. In case you were wondering, this caused my misconceptions about instance data in #2897.

**Comment by yyx990803** [comment]
After some thinking - I believe replacing instance `$data` is something that users should simply avoid doing. It makes the reactive properties on the vm instance indeterministic. In 2.0, this will be prohibited and users should always trigger changes by setting a proxied property on the vm instead of `$data`.

For this particular use case, it will be a wontfix for 1.x since there is a pretty straight workaround.

**Comment by nonDeath** [comment]
@yyx990803 you have any examples about this? 

Now i trying to compose with a mixin but, my approach is pourly designed yet.

In some place on my mixin i need to reach $vm.data elements to extends some common behavior, but this is not posible, instead i define a mixin private object to share behavior and data between the component and the mixin.
