### ISSUE TITLE
some question about props coerce

### ISSUE THREAD

**Issue by bulesyk** [vuejs/vue#2963]
https://jsfiddle.net/Lrk9sxjf/73/

some test of props coerce 
i clicked alert
the info.show become true
but components info.show doesn't become true
if i remove coerce
everything is ok
or i give parent info.show true 
everything is ok
why this?
it looks like coerce doesn't work well

**Comment by simplesmiler** [comment]
This is because you mutate the existing object, and `coerce` only executes when the reference has changed, similar to shallow watch.
The solution is to either use a computed prop instead of coerce, or to make sure that you change the reference instead of mutating: `@click="$parent.info={show:true}"`.
