### ISSUE TITLE
Possible regression: Changing the property of a prop of arrays with objects does not render.

### ISSUE THREAD

**Issue by grandnasty** [vuejs/vue#3071]
Reproduced: https://jsfiddle.net/g8u9x8g2/5/

Situation: Passing a computed array with objects as a prop to child component. Trying to change a property in the prop does not yield a render update in latest version. It did before.

In version .16: When clicking the button the name is changed to Test
In version .24: When clicking the button the data is updated but the change is not rendered

** Could be that this should never have worked and I'm doing it the wrong way. If so, apologies! :)

**Comment by yyx990803** [comment]
Why not just use a normal data property?

It is in general a bad idea to mutate objects created within computed properties, since these objects are temporary and re-created every time the computed property is re-computed. The only case where you should expect mutation to work is if the computed property is returning original data objects by reference (instead of creating new ones).
