### ISSUE TITLE
Possible bug. v-if, transitions, and duplicating component.

### ISSUE THREAD

**Issue by dustindowell22** [vuejs/vue#3080]
I tried posting on the Vue Discussion forum first but I never got a confirmation email.

I whipped up a demo showing the problem here:
http://codepen.io/dustindowell/pen/dXMmpj

Vue 1.0.24

Click 'login' to open the component, click close to toggle (it won't actually toggle), click close again and it will duplicate. Each toggle will make a new component. I saw a simmilar issue with `v-for` so I'm not sure if this is a duplicate.

This is all caused from a misnamed transition, `modalllllll` rather than `modal`. Fixing the name prevents the duplication from happening.

Is this a bug or is there a reason for this behavior? It was an odd bug to track down. I expected it to be more complicated than a simple typo, but I eventually found it.

**Comment by yyx990803** [comment]
This is technically not a bug, because the root cause is the wrong transition name. Vue waits for the `transitionend` event to determine when the transition has ended, but since there are no matching CSS classes applied, no transition is triggered, thus the transition essentially "never ends", preventing Vue from removing the element.

In 2.0 there will be an auto-timeout, however it's still rather hard to detect that you've misspelled the transition name.

**Comment by onkar-rentomojo** [comment]
The issue still exists in vue2 and vue3 as well. We have defined CSS classes as well still the elements are getting duplicated. When we remove transition, it works fine.
