### ISSUE TITLE
Ignore some custom HTML components

### ISSUE THREAD

**Issue by EmilMoe** [vuejs/vue#3090]
I have been searching all over the web (I think, but hopefully not) for an answer. I have set up a UI framework, that uses some custom HTML tags for CSS only, so they don't have any Vue attached. I would like Vue to ignore those, so I don't have to skip all those lines of warnings in my debug console.

Is this possible or do I have to create an empty component for each one?

**Comment by yyx990803** [comment]
Hmm, probably need an extra config option for this. Something like `Vue.config.ignoredElements`?

**Comment by EmilMoe** [comment]
Yeah that would be nice or a property like components, but IgnoredElements {} but I guess the config makes sense as it's not something a component should be able to do too.

**Comment by yyx990803** [comment]
Already implemented in 2.0 - will ship in 1.1.

**Comment by EmilMoe** [comment]
Perfect

**Comment by jvmccarthy** [comment]
@yyx990803 thanks for this and congrats on releasing Vue 2.0! Would you consider a PR to document this? I went to the docs first to see if there was a config option and then came here. I can understand if you want to keep the docs on config to a minimum.

Also, can this be initialized as an empty array instead of null? That way users can just push custom element names without having to check and initialize the variable.

**Comment by fenduru** [comment]
How is this intended to work for reusable components? For instance, say I have a 3rd party component:

```
// third-party-component.js
export default {
  template: '<custom-element>Hello world</custom-element>'
}
```

In order for this to not warn, the user needs to know about my implementation details:

```
// app.js
import ThirdPartyComponent from 'third-party-component.js';

Vue.config.ignoredElements = ['custom-element']

new Vue({
  el: '#root',
  template: '<third-party-component></third-party-component>',
  components: { ThirdPartyComponent }
});
```

The alternative is that a third party module modifies global config state, which seems to be an anti-pattern (similar to how it is better for modules to export component configs rather than `Vue.component()` them)

**Comment by SpinyMan** [comment]
And how to ignore `template` tag? Example: I use standard vue component that contains own `template` and other logic. But in the same time on the page other `template` tag exists and vue tries to parse it... How to avoid it?
```
<div id="app">
    <template class="bla-bla">
        <div><h1></h1></div>
    </template>
    <my-component></my-component>
</div>
```

**Comment by SpinyMan** [comment]
Template tag was already there and we decided to enforce our application by Vue. So after preparation (Vue injection) our application became broken... So we need `template` in this case and we couldn't drop it out... Any ideas?
