### ISSUE TITLE
[2.0.0.-alpha] Bug in <select multiple>

### ISSUE THREAD

**Issue by iLexN** [vuejs/vue#3191]
### Vue.js version
2.0.0.-alpha

### Reproduction Link

https://jsfiddle.net/ncLrLh6z/6/

### Steps to reproduce
Click 'Get' button.

### What is Expected?
no js error

### What is actually happening?
[Vue warn]: Error during component render (found in root instance)
console.error('[Vue warn]: ' + msg + (vm ? formatComponentName(vm) : ''));
vue.js (line 2168)
TypeError: value.indexOf is not a function
option.selected = value.indexOf(getValue(option)) > -1;

**Comment by LinusBorg** [comment]
The error appears because you initialized `b` as an emtpy tring in your data: `b: ''`, but you use it as an array in v-for: `v-for="value in b"`. Initialize it as an empty array instead, then v-for has nothing to complain about.

Working version wiht `b: []` https://jsfiddle.net/Linusborg/ncLrLh6z/9/

**Comment by LinusBorg** [comment]
Ok, I havbe to correct myself:

The reason is not the iitial value of `b` (though initializing it as an empty array would be better), the problem is the initial value of `make`:

Since the `<select>` has the `multiple` attribute, `make` should be an array.

Working jsfiddle: https://jsfiddle.net/Linusborg/ncLrLh6z/12/

So this is still not a bug, technically, but I will re-open the issue to evaluate how to improve this, mabe with a Vue-Warn in dev mode.
