### ISSUE TITLE
v-model value don't change with SELECT value in JqueryUI

### ISSUE THREAD

**Issue by MonKong** [vuejs/vue#3192]
There are two "select". 
display "select" created by JqueryUI ,and real select hidden by JqueryUI.

Problem:
` v-model` bind with real select ,display "select" change, real select's value also change(see in console),but `v-model` value don't change!?

I force show the real select and change its value by mouse,`v-model` value change.

`v-model` how to work with select in JqueryUI ?

**Comment by LinusBorg** [comment]
Hello @MonKong 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
