### ISSUE TITLE
How to update nested array

### ISSUE THREAD

**Issue by languanghao** [vuejs/vue#3206]
### Vue.js version
1.0.26

### What is actually happening?

I have some data like this
[gist](https://gist.github.com/languanghao/28c9c76288f17efe96947654394384c9)

Now I want to set the 'open' property of each item to control the dom show or hide. But Vue can only detect change of 'Root' node, other nodes like 'level 1-1' won't update dom.

I also tried use **tree.children.$set()** method, but nothing happend.

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
