### ISSUE TITLE
web workers

### ISSUE THREAD

**Issue by wormen** [vuejs/vue#3226]
tell me how to run Vue in  web workers
now he's not working because in web workers there is no window object

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or StackOverflow. Thanks.

**Comment by matthiasg** [comment]
@wormen did you find a way ? It seems it isn't possible just yet and its feasibility depends on the way the vdom is used after binding to actual dom nodes. It also imposes some code splitting since even if vue were capable of rendering from the web worker, any legacy e.g jquery stuff or other libraries would still have to render in the ui thread.

PS: I know this should be discussed on the Gitter chat room or forum or stackoverflow, but nobody answered there as far as I could find. At least not when the question was posted on Gitter.

**Comment by wormen** [comment]
@matthiasg Yes, I found a solution to his problem, but with VueJS has nothing to do

**Comment by matthiasg** [comment]
@wormen May I ask whether you are still using/considering Vue ? If not, is it because you the vue community wasn't responsive to your inquiry or because you needed rendering inside of web workers and had to look elsewhere?

**Comment by andreiglingeanu** [comment]
@matthiasg What's the point of doing rendering inside workers? Am I missing something very obvious or you're just having something super complex to render out?

**Comment by wormen** [comment]
@matthiasg the functionality, which I would like to take advantage of VueJS in web workers, I wrote myself as VueJS not use in web workers

**Comment by matthiasg** [comment]
@andreiglingeanu personally I don't need it right now, but I did investigate since some DOM updates and other interactions in angular took a few ms which interfered with scrolling speed and caused intermittent slow downs. we ourselves are planning to move our product from Angular 1 to vue in the next few weeks and do need SSR but not necessarily web workers yet.

But we are interested in potentially rendering inside a service worker as an experimental option which would require a similar architecture. The idea being that the server could push certain data updates to dormant devices every once in a while and the service worker would use that to pre-render the matching HTML. When the client requested the html it would already be pre-filled with more up-to-date data and make full use of streaming rendering.

**Comment by andreiglingeanu** [comment]
@matthiasg Hm, you'll then have to set HTML to the actual DOM via some sort of `v-html` directive, no? I'm not sure if that's a more faster approach...

**Comment by matthiasg** [comment]
@andreiglingeanu there a a number of projects / blog posts discussing the merits with some example implementations. basically the render into the vdom in the worker then transmit the patch to the ui thread which then applies it to the actual dom and the dom event handlers forward to the web worker. there is more work total but spread across two threads (which most even low level phones have cores for) and the ui thread is not blocked easily by xmlhttprequest parsing etc. 

but as I said its not a priority right now for us either. I am interested in seeing vue succeed though and was concerned that @wormen's question went totally without response of any kind. I am glad he found another solution for his issue of course

**Comment by benmo1602** [comment]
I imported the Worker file globally in index.html and stored it in Static.
