### ISSUE TITLE
how to bind event in two way at a time?

### ISSUE THREAD

**Issue by anrananran** [vuejs/vue#3232]
请问怎样才能将v-on:click='dosomething'和v-on:keydown.enter='dosomething'这2个绑定写到一块？

**Comment by LinusBorg** [comment]
Hello @anrananran 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
