### ISSUE TITLE
1.0.26-csp in chrome extension has problem

### ISSUE THREAD

**Issue by seveniu** [vuejs/vue#3235]
### Vue.js version
1.0.26-csp

### Reproduction Link
[jsfiddle](https://jsfiddle.net/seveniu/hsa79qn6/3/)

### Steps to reproduce
jsfiddle case
console log warn : Invalid expression. Generated function body: scope.message when

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by LinusBorg** [comment]
Thank for the fiddle, we will have a look.

**Comment by ktsn** [comment]
It seems to be a notevil's problem?
When I run the jsfiddle, the error is thrown in notevil at [this line](https://github.com/mmckegg/notevil/blob/master/index.js#L31). The `parse` function imported from esprima is undefined.

In further investigation, the error is only thrown when I load requirejs. Without requirejs, we can use Vue v1.0.26-csp expectedly.

I guess the loading of esprima is delayed by requirejs but notevil is executed immediately, then notevil fails import the parse function.
This is because notevil seems not to support to AMD style loading.

**Comment by LinusBorg** [comment]
Closed for the reason @ktsn explained.
