### ISSUE TITLE
v-for: first rendering has different behaviour to next, by changing data

### ISSUE THREAD

**Issue by giuseppeannunziata** [vuejs/vue#3257]
### Vue.js version
1.0.24

### Reproduction Link
https://jsfiddle.net/gannunziata/7hcn13wm/14/

### Steps to reproduce
NOTE: All this work correctly if I use track-by="$index" into v-for directive. But behaviour without this directive is un-predictive bethween first run and next changes on data.
1. On the first run, render all list by values on choices
2. delete last element (a1)
3. type into input box "a1" and press enter

### What is Expected?
On the first run AND on delete/insert a1 I expect this rendered list:
N.2: a2 => choice a2 - count: 41  
N.3: a1 => choice a1 - count: 13

### What is actually happening?
The list rendered on the first run and after inserted something into list must be rendered at same way;
First run is:
N.1: a1 => choice a1 - count: 13
N.2: a2 => choice a2 - count: 41
N.3: a1 => choice a1 - count: 13

after delete/insert "a1" value I obtain:
N.2: a2 => choice a2 - count: 41  
N.3: a1 => choice a1 - count: 13

**Comment by LinusBorg** [comment]
Hello @giuseppeannunziata 

Thank you for filing this issue.

However, this is not a bug. Due to the way Vue (and in particular, `v-for`) works, arrays with duplicate entries can lead to odd behaviour like what you are observing when not tracking by index.

Vue even warns you about it:
> [Vue warn]: Duplicate value found in v-for="c in choices": "a1". Use track-by="$index" if you are expecting duplicate values.

And the docs for `track-by $index` say:

>  This mode can also handle duplicate values in the source array.

So: use `track-by="$index"`
