### ISSUE TITLE
:track-by with function

### ISSUE THREAD

**Issue by NeonPaul** [vuejs/vue#3272]
It would be nice if, when evaluating `:track-by` in `v-for="item in items"`, we can have access to the `item` object in order to inspect it and return an appropriate track field.
This would be useful when iterating over a collection that contains two or more different types of objects, with each type having a different id field.
### Vue.js version

1.0.26
### Reproduction Link

https://jsfiddle.net/yMv7y/1615/ - A contrived example but hopefully simple enough to demonstrate what I mean.

**Comment by chrisvfritz** [comment]
@NeonPaul You may be interested to know that this is already possible with 2.0's equivalent for `track-by`, which is `key`, because it acts more like any other attribute. Also in the meantime for 1.0, you can accomplish what you want with [some Vue-ception](https://jsfiddle.net/chrisvfritz/mezk9h45/). 😲  😜

**Comment by danielsamuels** [comment]
Given that 2.0 is now released, can this issue be considered resolved?

**Comment by chrisvfritz** [comment]
@danielsamuels Possibly. It's still a feature that could be added in Vue 1.1, but if we've made the migration as easy as we're trying to, then there may not be much demand for it.
