### ISSUE TITLE
在vue v1.0.26 出现 Error when evaluating expression "Number(codesOFF)": TypeError: scope.Number is not a function

### ISSUE THREAD

**Issue by Baiang** [vuejs/vue#3332]
在vue v1.0.26 出现 Error when evaluating expression "Number(codesOFF)": TypeError: scope.Number is not a function
`data: {
  codesOFF: true
}`

`{{Number(codesOFF)}}`

**Comment by iagafonov** [comment]
@Baiang. As I understand, Vue can not rely on the global scoped names, because template compilation step does't know about run-time component data properties that can redefine global ones.
You should define method in component definition and use in like so:
`methods: {
  toNumber: function (v) { return Number(v) }
}`
and use it in template
`{{toNumber(codesOFF)}}`
or simply
`{{+codesOFF}}`Фs I understand, Vue can not rely on the global scoped names, because template compilation step does't know about run-time component data properties that can redefine global ones.
You should define method in component definition and use in like so:
`methods: {
  toNumber: function (v) { return Number(v) }
}`
and use it in template
`{{toNumber(codesOFF)}}`
or simply
`{{+codesOFF}}`
