### ISSUE TITLE
Control the list rendering of 'v-for'

### ISSUE THREAD

**Issue by Erichain** [vuejs/vue#3342]
### In Angular, we can control list rendering with `ng-repeat-start` and `ng-repeat-end`, but in Vue, how can we control the list rendering ?

Say, there is a table as following:

![](https://sfault-image.b0.upaiyun.com/383/905/3839053499-57971e269c59c)

so, how can we use `v-for` to achieve this?

or, can Vue add a feature to achieve this ?

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by vinicius73** [comment]
```html
<template v-for="...">
  <li>{{ ... }}</li>
  <li v-if="...">...</li>
</template>
```

Ref: http://vuejs.org/guide/conditional.html#Template-v-if
