### ISSUE TITLE
When I use the track-by in <select>

### ISSUE THREAD

**Issue by zce** [vuejs/vue#3349]
https://jsfiddle.net/iceStone/e5a0sjbf/6/

**Comment by LinusBorg** [comment]
Hi @zce 

I can only guess you refer to the fact that when switching cities, a wrong "sub" will be selected.

This is expected behaviour when using track-by="$index", the docs warn about this.

**Solution:**
A) don't use track-by. Nothing bad about if oyu don't render hundrets of items.
B) track-by an actual unique poperty. In this case: name: https://jsfiddle.net/e5a0sjbf/7/

**Comment by zce** [comment]
@LinusBorg thanks
