### ISSUE TITLE
Access transition hooks on a per component basis

### ISSUE THREAD

**Issue by dan-gamble** [vuejs/vue#3352]
I know you can access transition hooks by: 

```
Vue.transition('fade', {
  beforeEnter (el) {
    console.log('beforeEnter', el)
  },
  enter (el) {
    console.log('enter', el)
  },
  afterEnter (el) {
    console.log('afterEnter', el)
  },
  enterCancelled (el) {
    // handle cancellation
  },

  beforeLeave (el) {
    console.log('beforeLeave', el)
  },
  leave (el) {
    console.log('leave', el)
  },
  afterLeave (el) {
    console.log('afterLeave', el)
  },
  leaveCancelled (el) {
    // handle cancellation
  }

})
```

But we use `vue-router` and have: `<Router-view transition="fade" transition-mode="out-in"></Router-view>`

What we want to do is initialise some javascript on `afterEnter` but only some of the pages need this. I could set up a 2nd transition with hooks `Vue.transition('fadeWithInit', {...})` but this means i need to duplicate my CSS and all the functionality from the other `Vue.transition('fade', {...})` as well.

It would be nice if we could access the hooks in a component level like:

```
<script>
  export default {
    data () {
      return {...}
    },

    transition: {
      'fade': {
        afterEnter () {
          ...initialise javascript here and inherit all the other hooks
        }
      }
    }
  }
             
</script>
```

**Comment by simplesmiler** [comment]
In 2.0 transition system is reworked into a dedicated built-in components `<transition>` and `<transition-group>`, and hooks are now just custom events on these elements.

In 1.x you can do something similar, and emit custom events on the element that the transition is applied to: https://jsfiddle.net/simplesmiler/bdfgkejx/1/

Note that you can listen for these events on the element the `transition` is defined on (which is closer to how 2.0 implements it), or on the root element of the component that is being transitioned (which is how I did it in the example):
- In the first case you won't be able to access the instance itself directly because the event handler would be defined in the parent scope.
- In the second case you won't be able to listen for leave events, because by the time the `beforeLeave` is fired, the instance is already in the process of being destroyed, and the listener is already dismantled.

Also note that I also enabled the `transitionOnLoad` router option.

Does this cover your use case?

**Comment by dan-gamble** [comment]
Looks awesome to me, thanks :+1:
