### ISSUE TITLE
Prop with defined "type" and "default" set prop to undefined when invalid data is passed

### ISSUE THREAD

**Issue by diverted247** [vuejs/vue#3358]
### Vue.js version
1.0.26

https://jsbin.com/sozesub/10/edit?html,js,console,output

Create a component with a prop with both a "type" and "default" value.

When an invalid type is passed, undefined is set for value rather than the default.

Feels like props should remain with default values when improper data is passed when they are "type" restricted.

**Comment by LinusBorg** [comment]
I would say that this behaviour is intentional and rightly so.

While it may seem to you, the developer, be practical to prevent errors from invalid types by overriding them with a default, it will/can lead to stange behaviour for users - "the app does not show any errors, but somehow the value X simply changed".

If it's undefined, you have the possibility to handle the error in the component explicitly  (*'oops, somethign went wrong'*)

Does that make sense to you?

**Comment by diverted247** [comment]
Feels like this should be denoted in docs as ```undefined``` here is really of an error. I swapped back to debugging version and error was shown in console for invalid props. 

Thanks
