### ISSUE TITLE
iterate child component or iterate in child component ?

### ISSUE THREAD

**Issue by sirzxj** [vuejs/vue#3366]
* 1.iterate child component 
```
// use Item component in parent component
<Item v-for="item in items></Item>
```
* 2.iterate in child component

```
// this is an Item component 
<div v-for="item in items"></div>
```

which one is best practice ?

**Comment by LinusBorg** [comment]
Hello @sirzxj 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
