### ISSUE TITLE
v-if partial compilation caching disable

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue#3380]
Hi, Vuejs team,
I have following scenario: I use the v-if to dynamically compile and insert the partial html into DOM.
Everytime, v-if toggled to true, the contents of the partial will change. Unfortunately, it seems the next compilation behaves strange: "the changed part NOT compiled".
I have read the document http://vuejs.org/guide/conditional.html#v-if-vs-v-show
it says: 
"
v-if is also lazy: if the condition is false on initial render, it will not do anything - **partial compilation won’t start until the condition becomes true for the first time (and the compilation is subsequently cached)**.
"
My question is: Is there a method to disable the cache( force v-if to compile everytime when condition is truthy)?
Otherwise, if we can not, can you set this as a feature request?

Thanks~!

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by cnweibo** [comment]
@LinusBorg , I have created a little complex fiddle to demonstrate that concept: v-if  the second time truthy, v-if will not compile customized component, please check

https://jsfiddle.net/matiascx/d1ea22nc/6/
