### ISSUE TITLE
propsData looses reference to its passed data

### ISSUE THREAD

**Issue by janschoenherr** [vuejs/vue#3409]
### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/srepomk6/

As shown in the fiddle: Updating the data only propagates to the instance that is instantiated as component element. It should probably update both components.
This only happens if replacing the object itself.

Just noticed that this is true for the `data` property too: http://jsfiddle.net/f7p2441n/

**Comment by prog-rajkamal** [comment]
IMO, `data` and `propsData` are meant to work this way. 

The purpose of both of them is to provide initialize data. Hence they are no longer used after initialization.

**Comment by phanan** [comment]
What @prog-rajkamal said. You access the properties of the `data` object, not `data` itself, as Vue doesn't watch it.

**Comment by janschoenherr** [comment]
I thought this is two way data-binding?

Why does it work for a elements component, but not for a component instantiated via code?

@phanan Maybe I should not have named the key `data`, I have updated the fiddle.

**Comment by LinusBorg** [comment]
I'm not sure about the first case with `propsData`, it look like a bug a tfirst glance.

But in the second case concerning `data`hwne you change `this.someData = { foo: 'updated'}`, this would replace the whole object that the component's `$data `would refer to, which is *not* advised and can lead to unepected results.

**Comment by LinusBorg** [comment]
This is not a bug, but expected behaviour. I'll try to explain, bear with me:

The object `{foo: 'This will not be updated' }` itself *is* reactive. Changes to this object will be applied reactively: https://jsfiddle.net/Linusborg/hpm2hps7/1/

But you *replace* this entire object. And When you initialize the component's props through 'propsData', there's no expression for Vue to parse (:prop="someData"), so it cannot know where this object "came from". it cannot "see" that the object that was passed to propsData came from `this.someData`.
