### ISSUE TITLE
Should transition listen to the v-show set in the component root?

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#3431]
I am not sure if it's the best way to go, but I thought that leaving the transition wrapper outside the components would leave more freedom to integrate it as required (for example with or without keep-alive, custom events callbacks, etc).

With that in mind and taking as example a modal component it would usually have a show prop used to control the modal display. Transition expects v-show to know when to start and to avoid this kind of code `<modal v-show="show" :show="show" />` the v-show would be set in the component root directly. The final code with transition would be simple as

```
<transition>
  <modal show="show" />
<transition>
```

But that would not work as transition expects v-show right there. There is a jsfiddle that illustrate the issue (just ignore the badly implemented transition css...).

I see two ways to solve this:

1. Make transition be aware of v-show set on the root it self
2. Make available some event or way to trigger a transition programatically. That way from the compnent it self we could decide when that should happen.

### Vue.js version
2.0.0-rc1

### Reproduction Link
https://jsfiddle.net/miljan/8Lca03gb/

### Steps to reproduce
Try opening the modal

### What is Expected?
To open with a transition, which does happen if you set v-show again in the component declaration.

### What is actually happening?
It opens without a transition.

**Comment by yyx990803** [comment]
@miljan-aleksic FYI, I implemented support for this but decided to revert it. The point is that `<transition>` should be wrapping the direct node that is being manipulated by `v-show` or `v-if`. When you use `v-show` or `v-if` inside the component, it becomes indirect and imo ends up being harder to reason about.

So there are two options for the use case:

1. Use both `<transition>` and `v-show` in the parent scope.

2. Use both `<transition>` and `v-show` inside the child component. In this case you can also allow the user to pass in props to customize the transition.

**Comment by miljan-aleksic** [comment]
I was playing around with the changes and it introduced some new bugs difficult to confirm, plus during the process I had the chance to experiment more with the different configurations. Keeping the transitions direct gives you full power over the overall process which in more complex components could be necessary.

I totally agree with your decision and thanks for letting me know, @yyx990803.

**Comment by ColinLaws** [comment]
I'm having a hard time understanding why you don't allow for transitions to observe the root element of components for determining if the transition should be applied. This is making it increasingly difficult for me to write DRY code. I have components that are all responsible for their own visibility, so transition is not picking up on it.

Placing the transition inside the component does not work for my case, because I only want a single instance of a collection of components to be displayed.

This is a simplified representation of what my code looks like. I have a group of window components that share a single column. Each window is responsible for its own visible state like I said, so this is making it difficult to control the windows using a transition because I can't take advantage of the transition's amazing mode feature.
```html
    <transition name="fade">
        <my-window-component></my-window-component>

        <my-window-component></my-window-component>
    </transition>
```
This is what my window component looks like. The visibility is set on the root element.
```html
    <template>
        <div v-show="active">
            ...
        </div>
    </template>
```

I understand this is really a matter of opinion on the structure of code, and maybe I'm a rare case. Any suggestions would be appreciated, but I do feel that it should at least be an option on the transition element to render transitions based on the root element of components. If you assume you will always have a v-show on components, then you are assuming visibility is always controlled by the component that transition based elements exist in. Sorry if that's a bit of a rant. I will continue to explore solutions. Thanks!
