### ISSUE TITLE
[2.0] Backticks in class attribute not correctly compiled

### ISSUE THREAD

**Issue by robinvdvleuten** [vuejs/vue#3456]
### Vue.js version
2.0.0-rc.2

### Reproduction Link
https://github.com/robinvdvleuten/vue-bug

### Steps to reproduce
Clone and install repository then run `npm run build` to get uglify error.

### What is Expected?
I expect that the backtick expression is correctly compiled to ES5 Javascript.

### What is actually happening?
If I have the following Vue component:
```vue
<template>
  <div id="app" :class="{ [`class-${test}`]: true }">
    Hello, Vue 2.0!
  </div>
</template>

<script>
  export default {
    data () {
      return {
        property: 'test'
      }
    }
  }
</script>
```

The template parser doesn't seem to recognize the expression and generates the following (reproducible by running `npm run build:without-uglify`):

```js
module.exports={render:function(){with(this) {
  return _h('div', {
    class: {
      [`class-${test}`]: true
    },
    attrs: {
      "id": "app"
    }
  }, ["\n  Hello, Vue 2.0!\n"])
}},staticRenderFns: []}
```

Which causes Uglify to throw the error;

```bash
ERROR in bundle.js from UglifyJs
Unexpected character '`' [bundle.js:5089,7]
```

**Comment by LinusBorg** [comment]
Javascript Expressions in templates are not run through babel.

**Comment by robinvdvleuten** [comment]
Why not? In vue 1.0 this was working without problems

**Comment by LinusBorg** [comment]
Ok, reopening this. It actually works with the stzandalone build: https://jsfiddle.net/Linusborg/chw886jk/

So it should work with runtime-only and precomiled templates. Seems like a bug indeed.

Sorry for the premature close.

**Comment by yyx990803** [comment]
In 1.0, this works because 1.0 templates are preserved as strings during compilation and the contained expressions only get compiled into JavaScript functions in the browser, so it doesn't interact with UglifyJS at all.

In 2.0 templates are compiled into functions and thus will be processed by UglifyJS - however, this specific error is caused by UglifyJS not being able to handle ES2015 syntax, but a bug in Vue itself.

In the future we will add babel transpile support to render functions in `vue-loader` and `vueify`.

**Comment by robinvdvleuten** [comment]
@yyx990803 thanks for the explanation! I've fixed it by moving the class generation to a component's method.
