### ISSUE TITLE
[Vue warn]: Error when evaluating expression str.split

### ISSUE THREAD

**Issue by zzzeep** [vuejs/vue#3463]
I got the expected result with a warn, is it wrong ?
```
<div>{{ user.add_time.split(' ')[0] }}</div>

[Vue warn]: Error when evaluating expression "user.add_time.split(' ')[0]": TypeError: Cannot read property 'split' of undefined
```

**Comment by LinusBorg** [comment]
`user.add_time` is undefined. maybe because `user` is not available at the moment of initial render?

Anyway, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by zzzeep** [comment]
`user.add_time = "2016-11-11 10:00:00"`
 `<div>{{ user.add_time.split(' ')[0] }}</div> => <div>2016-11-11</div>`

I got the RIGHT result, but there is a warn in my console, why?

**Comment by LinusBorg** [comment]
> Anyway, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.
