### ISSUE TITLE
[2.0.0-rc.2] the native dom event listening can't not work on <component :is=""> while it's functional component

### ISSUE THREAD

**Issue by baiyaaaaa** [vuejs/vue#3480]
### Vue.js version
[2.0.0-rc.2]

### Reproduction Link
https://jsfiddle.net/WhiteCusp/n6cee6vt/

### Steps to reproduce
click the list item

### What is Expected?
alert('click')

### What is actually happening?
do not alert anything

**Comment by LinusBorg** [comment]
* The functional component receives the data object that was passed to it through `ctx.data`
* In this object, there's the click.native event:
`{ nativeOn: { click: handleClick($event) } }`
* you have to pass that to the render functions second argument youself, otherwise the event won't be registered
* also, since we want this event to register on a normal `li` element, it would have to be under the `on` key, not the `nativeOn` key (only required when rendering a component)

So two things to do:
a. pass a properly data object to the render function (https://jsfiddle.net/Linusborg/n6cee6vt/1/), or:
b. Pass ctx.data to the render function and change the listener in the parent to `@click="handlClick: https://jsfiddle.net/Linusborg/1ko2er5z/1/

**Comment by baiyaaaaa** [comment]
@LinusBorg Hey，i can't find a best way to achieve custom template in custom component，can u show me a best practise of that? Thanks~

**Comment by LinusBorg** [comment]
However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
