### ISSUE TITLE
Defining an instance property fails between requests in SSR

### ISSUE THREAD

**Issue by cemelo** [vuejs/vue#3508]
### Vue.js version
2.0.0-rc.3

### Steps to reproduce
The problem can be reproduced using `vue-hackernews-2.0`. In `src/app.js`, inserting the following code results in the error stated later:

`Object.defineProperty(Vue.prototype, '$prop', {
  get() { return 'This property is present in every instance.' }
})`

### What is Expected?
The property `$prop` should be present in every Vue component.

### What is actually happening?
After the first request, the following error occurs:
`TypeError: Cannot redefine property: $prop`

According to the `vue-server-renderer` documentation, the SSR should use Node.js' `vm` module and provide a discrete state between requests, thus, `$prop` shouldn't be defined in the second request.

In my use case, for instance, it became a problem when creating a plugin that provides some reactive properties to the app components. That doesn't seems to occur when the plugin is defined as an UMD module in a different npm package.

**Comment by yyx990803** [comment]
This is because Vue itself is externalized: https://github.com/vuejs/vue/tree/next/packages/vue-server-renderer#externals

Basically, you want to make sure any global modifications you make to the global Vue singleton is done only once. Calls like `Vue.use(VueRouter)` are fine because Vue internally avoids duplicate plugin installation.
