### ISSUE TITLE
Checkbox checked state issue

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue#3523]
### Vue.js version
2.0.0-rc3

### Reproduction Link
https://jsfiddle.net/miljan/9fzmq8qy/

### Steps to reproduce
Toggle the Checkbox 1, it will update the data state, but not it checked state.
Toggle the Checkbox 2, it will update its checked sate ignoring the data checked state.

### What is Expected?
I expect the checkbox to accurately relfect the component data. In a scenario where we have a Table component which rows renders a checkbox for each and on click emits an event to update the selected state (being this passed as prop), both exposed examples in the fiddle would fail. Checkbox 1 because would show no visual state change and Checkbox 2 because even without firing any event would show a falsy visual state change.

**Comment by LinusBorg** [comment]
Why do you call `event.preventDefault()`? This keeps the checkbox from toggling.

https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

When I remove that, everythign works fine. Also, why not use the change event?

**Comment by miljan-aleksic** [comment]
@LinusBorg, because without those the checkbox would be swithing to checked even if the state is false. Check the Checkbox 2 example, it doesn't have any prevent but changing the checked state on each click, while the real state is not getting changed.

I'm using `click` event for the prevent as on change the checkbox already changed its status.

If my component relies on a prop value (false by defult) to set an checkbox checked state, the checkbox should remain unchecked until the prop value change. As you can see in the fiddle, that's not the case.

**Comment by LinusBorg** [comment]
Well, Vue *does* correctly update the input's attribute, but the GUI does not switch:

![image](https://cloud.githubusercontent.com/assets/1444526/17970516/547a4724-6ad7-11e6-9654-220806c42677.png)

**Comment by miljan-aleksic** [comment]
I don't know... if you set a log in the render function, despite the preventDefault workaround, those get called and you can see the state did trully changed, but not the GUI as you said. But this is all virtual dom, so if Vue wants to render a Checkbox with checked value, the GUI is not on the way. The impression is that Vue thinks there is nothing to change, and keeps using the cached dom.

**Comment by LinusBorg** [comment]
what I mean is, as demonstrated in the screenshot above, when you switch the value to `false`, Vue correctly removes the `checked` attribute (1st Screenshot), and when you switch to `true`, Vue correctly sets the `checked` attribute again.

But the browser's GUI seems to screw up, because event though Vue correctly removes the `checked` attribute when the value switches to `false` (which happens async, so after the function with `e.preventDefault()` ended), the GUI is still displays a checked checkbox.

**Comment by LinusBorg** [comment]
Okay so I did some debugging - of the browser behaviour. the problem is the behaviour of `e.preventDefault()`. Add debuggers before `e.preventDefault()` and then step along.

* it does not actually prevent the unchecking of the box immediatly. as soon as the click event starts, the checkbox becomes unchecked
* it does not even revert that once it's called - after `e.preventDefault()` is called, the box is *still* unchecked
* in fact, the box stays unchecked until the complete call stack - including the DOM update by Vue - is done. only then does the browser (Chrome) revert the GUI status back and makes the box on the screen checked.

So I would say this is not a Vue bug per se, but an odd browser behaviour that would have to be wqorked around....

**Comment by miljan-aleksic** [comment]
Thanks for looking into it. Do you consider this possible workaround should be done by Vue or the implementation?

**Comment by LinusBorg** [comment]
That I could tell you if I knew that a workaround would look like ...

**Comment by miljan-aleksic** [comment]
@LinusBorg, a workaround that is working fine so far in Chrome in Mozilla.

```js
domProps: {
  checked: checked
},
on: {
  click: e => {
    // ensure the browser doesnt apply
    // the checked state on click
    e.target.checked = checked
  }
}
```

**Comment by LinusBorg** [comment]
Great, works for me too, and also tested it in Safari.

**Comment by LinusBorg** [comment]
@miljan-aleksic I will not label this a bug, as it seems to be more because of the browser behaviour and the workaround can be implemented easy enough.

Will keep it open for discussion though, to see weither we can come up with a clever way to catch this in Vue itself somehow. But honestly, I doubt it.

**Comment by miljan-aleksic** [comment]
Yes, tough call. If doesn't get into the core, perhaps we could document as a hint it in the Render Functions examples.

**Comment by yyx990803** [comment]
The first checkbox is expected behavior because you are calling `e.preventDefault()`.

The second checkbox is working as intended because you are emitting the wrong event name. It works when the event name is fixed.

**Comment by mattrummler** [comment]
Hello

Please repost one or both of your fiddles if possible @miljan-aleksic @LinusBorg .

I am seeing a problem currently that sounds very much like what is being described here.
Unfortunately the fiddles are both gone so I can't see any code and the workaround mentioned by @miljan-aleksic does not make sense to me out of context (also I don't really understand render functions so that's probably part of my weakness here).
Additionally, I don't see how I could have an event name be wrong... I have a v-on: click="clicked" event in the template and in the component there is a clicked(){} method in the methods: {} object.
The event fires the method in the component definition and it must work as everything else I'd expect is occuring.
Here is a more exact description of the problem:

1. There is a vertical list of tasks, one task is below the next, etc... each task has a checkbox to it's right
2. When a user checks a checkbox to indicate task completion, that task should disappear (there is a Vuex implementation which triggers the change across the entire application so this task will disappear from all such lists... and it does)
3. The next task in the list moves, or otherwise appears in the spot the old task was
4. The checkbox accompanying the next task appears checked, even though it certainly should not be 
(in fact the checkbox from the previous task never actually seems to disappear... instead it seems to hang around while the task text changes next to it)

If the above is the same problem then there's no need for me to try to show a reproducible example.
If it is not please let me know, and I will make an effort to make a fiddle to show the problem time permitting (the application this is in is complex so if reproducing it is not trivial then I may not reasonably be able to reproduce it).

Questions:
1- @yyx990803 (thanks for creating Vue, it's a better alternative to angular et al), what event name is he misusing?
2- @miljan-aleksic @LinusBorg Could you share how the work around could be reproduced without render functions?

NOTE: I am currently using event.preventDefault() just to not have a checked checkbox hanging around but it's less than ideal considering that the checkbox never appears checked, (maybe I will resort to buttons instead of checkboxes... or even images that I swap out manually)

Thank you all in advance!

**Comment by LinusBorg** [comment]
It doesn't really sound like the same problem, it sounds like you didn't key your list items. 

You should start a thread on forum.vuejs.org, we can continue there if necessary. closed issues are the place for this.

**Comment by mattrummler** [comment]
As in they didn't all have unique ID's?
I'll try that again in case there was some caching issue etc... but that didn't resolve the issue when I added unique id's to each checkbox previously... 
hmmm or maybe it needs to be @ a higher level... (there are multiple elements in the vue components template...).
I'll try keying other (and if needed all) of the elements.

Thank you for the thoughts and I apologize for commenting on a closed issue.
If this doesn't resolve the problem I'll start a thread on the forum, (and create a fiddle that illustrates the problem).

Thanks again
