### ISSUE TITLE
checkbox ':false-value' logic has some problem

### ISSUE THREAD

**Issue by languanghao** [vuejs/vue#3548]
### Vue.js version
1.0.23

### Reproduction Link

https://jsfiddle.net/z3xc9sc6/

### Steps to reproduce
If set the ':false-value' on the checkbox, and the 'v-model' property is 'false' like value(eg: null, 0 ...), when the checkbox init, the v-model property will be set 'false'. I think the 'v-model' propery should set the value of ':false-value' instead of 'false'.

If user do 'check'/'uncheck' action, then the ':false-value' works fine.

### What is Expected?

I think the 'v-model' propery should set the value of ':false-value' instead of 'false'.

**Comment by LinusBorg** [comment]
In Vue, the data determines what what the UI looks like, not the other way around.

* In the `data`, `a: null`, so the `checked` attribute is not set.
* Vue will in this case *not* write back the `false-value` to the data. This is expected behavior. if you want `a` to have the value of `b` initially, then do that in `ready()`
