### ISSUE TITLE
Databind problems in object array properties 

### ISSUE THREAD

**Issue by xereda** [vuejs/vue#3567]
### Vue.js version
2.0.0-rc.4

### Reproduction Link
https://jsbin.com/wapikej/edit?html,js,console,output

### Steps to reproduce
On and off the checkboxes.

### What is Expected?
Correct databind when the object array is changed (changed checkbox to true / false)

### What is actually happening?
The bind does not occur in objects that do not have the property "Selected".

**Comment by LinusBorg** [comment]
If you don't properly initialize your data, reactivity can't reliably work.

**Comment by xereda** [comment]
But in the current version this is not something mandatory.

**Comment by vinicius73** [comment]
@LinusBorg This behavior is expected, however as said by @xereda works normally in V1
It is a property of an object, the code needed to "solve" this issue will take part of the facility already provided by VueJS

**Comment by yyx990803** [comment]
@xereda this is required in 2.0 - `v-model` no longer implicit create non-existent paths for you. This is an intentional decision - although we want to let users be lazy, we also want them to write maintainable code. Although you **can** use NoSQL without a Schema, what do you feel when you have to maintain another persons database that has no schema at all?

**Comment by xereda** [comment]
Accepted Arguments. Thanks for the return of all involved.

**Comment by amigo** [comment]
Evan, "intentional" sounds like "intentional murder". We are people and  we are lazy. Life is not so long so for mirroring whole schema. Looks pretty weird on the background of native javascript objects. #3987
