### ISSUE TITLE
Template escape using function constructor

### ISSUE THREAD

**Issue by bahmutov** [vuejs/vue#3592]
Here is the escape
```
<p>Hello, {{ this.constructor.constructor('alert("oops")')`` }}</p>
```

### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/yvt7eckL/1/

### Steps to reproduce
Open the jsfiddle

### What is Expected?
No alert boxes

### What is actually happening?
Alert box pops up

**Comment by fnlctrl** [comment]
Interesting hack indeed... but I think it would only work when you type it yourself inside the template, and won't work if binding from data
http://jsfiddle.net/93zqtbkx/

**Comment by bahmutov** [comment]
Yup, the bind expressions are simpler and do not have computation (like I am forcing using "+" in my example). The danger for template expressions is when Vue (or Angular, since it is broken the same way) is combined with some server side templating like Jade that injects other parts on the page, like logged in user name. Then Jade template variable can put malicious content like above with braces, tricking Vue to execute it. See the stack of slides below this slide in the presentation http://slides.com/bahmutov/secure-front-end-from-node#/4/2

**Comment by bahmutov** [comment]
BTW, Vue 2 server-side rendering is broken same way, and allows arbitrary code execution.
```js
var app = new Vue({
  template: "<p> Hello {{ this.constructor.constructor('console.log(\"home is\", process.env.HOME)')`` }} </p>"
})
```

**Comment by fnlctrl** [comment]
Hmm.. It's true that one may use template engines + vue and create security loopholes, but I doubt if there's much to be done at vue's end (without great efforts), but PRs are always welcome :smile:.

In my opinion this should be solved by a framework-agnostic tool or plugin for these template engines, and it should be recommended (or even enforced) for anyone who uses them with vue (or ng or whatever front-end framework).

**Comment by bahmutov** [comment]
The solution that vue and any other framework should put as a big disclaimer is for users to set strict content security policy and disallow inline scripts.

**Comment by yyx990803** [comment]
This has been discussed long ago - the issue here is that **the moment you use Vue or any other client side framework to compile a template potentially generated by a malicious 3rd party, you are already busted.** There are simply too many ways to get around the system when you need to evaluate arbitrary content - all XSS loopholes apply, and it is simply impractical for the framework to take on that responsibility for the user.

In practice, the simple rule is **you should always be able to trust the template you pass to Vue**. That's it.
