### ISSUE TITLE
$log

### ISSUE THREAD

**Issue by sailengsi** [vuejs/vue#3600]
$log方法目前是只能打印出来纯净的数据，并没有返回，建议增加此功能。
$log method is currently only print out the pure data, and did not return, it is recommended to add this feature.

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.


Thank you.

**Comment by fnlctrl** [comment]
@LinusBorg OP was asking for a feature that $log should also return the data...though he didn't make it clear in English...

@sailengsi  Since `$log` is deprecated in 2.0, it's not going to get new features.
Though it's very easy to write your own $log if you want:

```js
Vue.prototype.$log = function() {/* Your own implementation */}
```

Copy and modify the original code if you need to:
https://github.com/vuejs/vue/blob/dev/src/instance/api/data.js#L155-L187

**Comment by sailengsi** [comment]
@fnlctrl Thank you, has been modified.
