### ISSUE TITLE
computed has an error

### ISSUE THREAD

**Issue by draguo** [vuejs/vue#3612]
## Vue.js version

1.0.26
## Demo
[jsfiddle](https://jsfiddle.net/zu4r9xw6/3/)  
or  
[test](http://casarover.com/test)  
 
## result   
click the button then the result will has error
left is  ios 9.3.4  iphone 6 plus right is android phone
![result](http://i2.buimg.com/4851/05693b7fd1df5c67.jpg)

### has error
ios 9.3.3 and 9.3.4   iphone 6s plus or iphone 5s
### no error
ios 8.2  iphone 6 ，some android phone，PC chrome

from #3545

**Comment by posva** [comment]
I don't have a device to test it. Does this https://jsfiddle.net/bzyyvafg/ work?

**Comment by sqal** [comment]
@posva Yeah it works I just wanted to post the same example. For in breaks the app because OP doesn't use `hasOwnProperty` check and is looping over inherited properties which you definitely want to avoid. I recommend to start using Eslint and follow good JS practices - https://github.com/airbnb/javascript

**Comment by posva** [comment]
Then I'm closing this 🙂

**Comment by draguo** [comment]
it works. thanks
