### ISSUE TITLE
DOM node replacement (with v-if) overlaps with the previous node

### ISSUE THREAD

**Issue by clegendre** [vuejs/vue#3616]
Vue Version : 2.0.0-rc.4
Repro : https://jsfiddle.net/p9mcn2tp/3/

When there are two sibling components that toggle each other, the second one that appears seems to have some properties of the previous one.

**Comment by chrisvfritz** [comment]
It looks like the element is being patched for efficiency, instead of replaced, which is somehow proactively triggering the previous click event. If you need an immediate fix, you can add unique `key` attributes to each component to instruct the virtual DOM that each of these elements are completely separate entities.

**Comment by yyx990803** [comment]
This doesn't seem to be related to Vue - see https://jsfiddle.net/mf4p8jb2/ - in this fiddle, even a button without `type="submit"` would submit the form. In your original fiddle, Vue is rendering the second button correctly without `type="submit"`.

**Comment by clegendre** [comment]
In my example if you click on the second button, the form is not submitted, while the first one triggers the submit. 
@chrisvfritz seems to have found the source of the bug. 
You should reopen this issue.

**Comment by yyx990803** [comment]
@clegendre can you clarify what is your expected behavior? (which, btw, is required for a proper bug report per issue reporting guidelines) What I am seeing is that clicking the first button submits the form, which I assume is what you think is a bug, but in my fiddle I am showing you that is happening without Vue being involved at all, it's just how the browser works. If that's not what your issue is about, then you should've provided proper explanation.

**Comment by clegendre** [comment]
I update your fiddle : https://jsfiddle.net/mf4p8jb2/1/
In this update the button "b" is now of type "button", which is the same as in my example.
In this case, a button type="button" does not submit the form, and this is just how the browser works too.

My explanation is the following: in my example, the button of type="button" does submit the form because it is replaced by the direct sibbling in the hierarchy which is a button of type="submit".

**Comment by yyx990803** [comment]
Okay, that makes sense. This is indeed a bug.

**Comment by yyx990803** [comment]
Upon further investigation, I'm not sure if there's anything Vue can do about this. Surprisingly, the browser seems to determine form submission by the type of the button that triggered the event **when the event reaches the form element** rather then the type **when the event was triggered**. Vue patches the button in-place when they are toggled, and this happens **after the event was triggered, but before the event reaches the form element**.

The only way to get around this is changing how Vue's async queueing works by ditching MutationObserver, but I don't think that's worth it, since it can be easily worked around by keying the two buttons.

**Comment by clegendre** [comment]
Sorry to "reopen" this issue, but there is another repro link, which doesn't involves a form at all.
https://jsfiddle.net/mf4p8jb2/2/

In this sample, the button **c** toggles the apparition of the button **b**. But the effetct of the button **c** is applied to the button **b**.

This is ok when the `key ` attribute is applied on both components but this is not very intuitive.

Thank you for your help.
