### ISSUE TITLE
computed property not reactive to changed dependency in if 

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue#3640]
### Vue.js version
2.0.0-rc.4

### Reproduction Link

https://jsfiddle.net/oldpig/t9hjjpg1/1/

### Steps to reproduce
Click 'Toggle' button

### What is Expected?
The message should be toggled on each click.

### What is actually happening?
Nothing happens.
The `tipStyleObject` computed property does not react to changed `this.showTip`.

If you uncomment line 11, then it works as expected.

**Comment by yyx990803** [comment]
This is expected behavior. refs are not reactive, you should depend on showTip.

**Comment by Centaur** [comment]
Shrug.  There **IS** a `this.showTip` dependency in the code.

**Comment by yyx990803** [comment]
The reason: `refs` are only calculated after the initial render, so `$refs.tip` will not be present when the computed property is first evaluated. And because they are not reactive, the computed property never gets re-evaluated.

Again, this is expected behavior and I don't see the point of wrapping it with `if (this.$refs.tip)` anyway.
