### ISSUE TITLE
webpack  require templete/style external files not work for Vue+Vue-router?

### ISSUE THREAD

**Issue by Dreampie** [vuejs/vue#3661]
https://github.com/Dreampie/resty-cms/blob/master/src/app.js

```
new Vue({
  router,
  template: require('./app.template'),
  style: require('./app.style')
}).$mount('#app')
```

Warning:
```
vue.common.js:2527 [Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build. (found in root instance)
```

`npm run dev` not show view

**Comment by fnlctrl** [comment]
As the warning suggests, you should be using the compiler-included build, 
so change `import Vue from "vue";` to `import Vue from "vue/dist/vue";` should work.

You can wait for the 2.0 migration guide for more info.

**Comment by prog-rajkamal** [comment]
@Dreampie @fnlctrl 

for standalone build, add the following alias to your webpack config:

      // ...
     resolve: {
     alias: {vue: 'vue/dist/vue.js'}
     },
      // ....


**Do NOT do import Vue from 'vue/dist/vue' - since some tools or 3rd party libraries may import vue as well, this may cause the app to load both the runtime and standalone builds at the same time and lead to errors.**

[Source: Vue 2 Starter Resources](https://github.com/vuejs/vue/wiki/Vue-2.0-RC-Starter-Resources#standalone-vs-runtime-builds)

**Comment by Dreampie** [comment]
thanks,it's ok

**Comment by fnlctrl** [comment]
@prog-rajkamal Thanks for the heads up!
