### ISSUE TITLE
Add custom v-model modifiers

### ISSUE THREAD

**Issue by ecmel** [vuejs/vue#3666]
We have `.lazy`, `.number`, `.trim` and `.undef` is on the way.

Apart from `.lazy` they all work like two-way filters.

Since 2.0 does not support 2 way filters, may be there should be a new api to add custom v-model modifiers to fulfill the same need.

**Comment by posva** [comment]
I'd use computed properties for that purpose

**Comment by aristidesfl** [comment]
@posva computed properties are not reusable.

**Comment by posva** [comment]
Almost everything is reusable through a mixin.
You can use a function that generates a mixin. This way you can bind a the
computed property dynamically. I cannot put that example on a fiddle now
but I would do it ASAP.
However, I agree it's a very common use case for inputs to have
transformations applied. A proper api or at least an explanation on the
guide is necessary

**Comment by aristidesfl** [comment]
> Almost everything is reusable through a mixin.
You can use a function that generates a mixin. This way you can bind a the
computed property dynamically. I cannot put that example on a fiddle now
but I would do it ASAP.
However, I agree it's a very common use case for inputs to have
transformations applied. A proper api or at least an explanation on the
guide is necessary

Put in another way, computed properties are not reusable. You can use factory functions + mixins as a **work around**, but the usability and readability doesn't compare.

**Comment by ecmel** [comment]
For my project, I badly needed this feature so I used the recommended custom input approach:

InputCustom.js
```
define(function () {
  return Vue.extend({
    data: function () {
      return {
        focused: false
      };
    },
    template: '<input @focus="onFocus" @blur="onBlur" @input="onInput" @change="setDisplayValue">',
    props: ['value'],
    watch: {
      value: function () {
        if (!this.focused) {
          this.setDisplayValue();
        }
      }
    },
    mounted: function () {
      this.setDisplayValue();
    },
    methods: {
      onInput: function () {
        this.$emit('input', this.parse(this.$el.value));
      },
      onFocus: function () {
        this.focused = true;
      },
      onBlur: function () {
        this.focused = false;
        this.setDisplayValue();
      },
      setDisplayValue: function () {
        this.$el.value = this.format(this.value);
      }
    }
  });
});
```

InputText.js
```
define(['js/InputCustom'], function (InputCustom) {
  return InputCustom.extend({
    methods: {
      parse: function (val) {
        val = val.trim();
        return val === '' ? null : val;
      },
      format: function (val) {
        return val === null ? '' : val;
      }
    }
  });
});
```

In my opinion, this approach is very convenient and I decided not to use any v-model modifiers at all including `.lazy`.

**Comment by yyx990803** [comment]
For more customized use cases that built-in modifiers cannot support, what @ecmel mentioned is the recommended approach. We will document that in more details in the official guide.

**Comment by aristidesfl** [comment]
The idea of this feature proposal is to take advantage of the existing `v-model` directive, which already works with every `input` element. To save the work of writing *InputCustom.js* in every project, because that has been done in `v-model`, having only to write the equivalent of *InputText.js* in a custom modifier, which contains all the logic which needs to be modified most of the times. The fact that `v-model` already ships with modifiers proves that it is an intuitive and desirable pattern. It is only natural to facilitate the creation of custom modifiers, to save the work of creating custom elements and manually implementing dom/model binding all the time. 

If it makes sense from the API perspective, would be interesting to know what are technical aspects which are driving the decision of not offer this feature.

**Comment by restored18** [comment]
Any chance we can get this issue reopened? A common use case for me is the need to automatically format data in a field as it's being typed in. Something like taking '101216' and turning it into '10/12/16'. Being able to create a custom v-model modifier would greatly simplify my code since I could write v-model.date instead of having to build a custom input component with props and events.

**Comment by ecmel** [comment]
After using vue js for a while now in my project, I think this issue should indeed be reopened. 

At least we need an `undef` modifier.

**Comment by rhyek** [comment]
I agree that this issue should be reopened. Not sure what `undef` was supposed to do, but I would like a `v-model` modifier that sets my variable to `null` in case the input's trimmed value is an empty string.

I'd love to be able to do that myself in a straightforward way.

**Comment by aristidesfl** [comment]
Functionality more redundant than this has been added for example with https://github.com/vuejs/vue/issues/5194 . From the outside, Vue appears to slowly be compromising some of its principles in favour of conventions and practices promoted by the react community, and deviating from the qualities which made it stand out in the first place. Would be interesting to know if this is a conscious decision with the intention to make migration from react easier, or just coincidence.

**Comment by ecmel** [comment]
Writing custom components is fine but if you want to use a 3rd party custom component like https://github.com/text-mask/text-mask there is no straight forward way to sanitize the masked input to model values except using computed properties.

**Comment by tobei** [comment]
So, I just want to use an HTML standard input[type=date] field to edit a date type in my model and this wonderfully powerfull and extensible framework can't do that out of the box? Can't read the date into the field, overwrite my date with a string in my data after I select a date. This solution could be written in two lines with two-way filters or with modifier.

But the best solution at all would be to just support it natively as they do for checkbox and other standard input field, why is "date" a special thing?

**Comment by newms87** [comment]
+1 for custom modifiers. Seems like a no brainer, unless there is a good reason not to? 

Masking input and parsing the value for application use is a very common practice, and making some "syntatic sugar" like v-model.lazy.currency="amount" would be amazing!

**Comment by Chalkin** [comment]
1+ for custom modifiers.
I have a simple radio input with true|false values which evaluate to strings - But I need them as an boolean - computed properties will not be smart in this case since I need to reimplement a computed property for every radio input. E.g. Having 100 radio inputs will result in 100 computed properties

**Comment by maxapps** [comment]
+1 for custom modifiers but I agree with tobei -- input[type=date] should work automagically.

**Comment by mahesh29** [comment]
+1 for custom modifiers.

I come from an Angular background, and just started with vue, and saw this thread. 

I feel it would really help having something like Angular's parsers and formatters, in Vue too. If I could do something like v-model.dateFormat and result in something like mm/dd/yyyy, it would be really cool.

**Comment by coderjz** [comment]
+1 for custom v-model modifiers.

In my case I loop over a few nested objects retrieved in JSON, and use a single HTML template (rather than a template per object).  In this case I believe computed properties don't work?

I'm currently putting in custom conversion methods between the server format and v-model format when fetching and sending data, but would love for something just "built-in" that I could pass the functions to.

**Comment by johnleider** [comment]
+1 to this. It used to be available before 2.2. You could access the property through,

```this.$vnode.data.directives```

It was removed with the addition of custom model input values, but was a very useful features and should be back in the framework.

**Comment by matthew-inamdar** [comment]
+1 for this.

Custom v-model modifiers would be great!

**Comment by grzegorztomasiak** [comment]
#metoo

**Comment by asolopovas** [comment]
+1

**Comment by webnoob** [comment]
+1 in 2018 as well ...

**Comment by Mushr0000m** [comment]
+1 It's a necessary feature for DRY code in my opinion. Right now I have to create 10 watchers that does the same thing for a form with a lot of input. A custom modifier would solve everything.

**Comment by emadgh** [comment]
+1 I just started vue and already need these type of two way filters ...

**Comment by samayo** [comment]
+1 definitely needed

**Comment by mt89vein** [comment]
+1

**Comment by nickmessing** [comment]
You can build helpers like [this](https://codepan.net/gist/2e03f69c36376661985c81a523fb2f5c) for most use-cases IMO

**Comment by bbugh** [comment]
@nickmessing that doesn't cover the (really useful) use case being described here, which is in-place modification of the input text. If you have an input box that you want to always be formatted like a phone, you'd have `<input v-model.phone="some_date">`. When the user entered text, it would automatically format it. 

This seems like such a basic feature and it's more difficult than it should be right now. The behavior already exists in the framework, but for some reason it's restricted to framework-only code. We want to be able to add a custom modifier that would do this, which is reusable across components and projects, just like filters and directives are right now.

**Comment by phoet** [comment]
@bbugh totally agree, i'm having a similar case with formatting IBANs and it would be such a nice and declerative way to simply put `v-model.iban="payment.iban"` in there...

@franciscolourenco maybe someone could put some reasoning behind why this should not be supported by the framework so that it becomes more obvious.

**Comment by IharKrasnik** [comment]
+1 for custom modifiers, there are plenty of use-cases that could be accomplished with this feature

In our application there are few different inputs to format currencies, we always store cents amount in model, but display nicely formatted dollars amounts in inputs (so 123456 in model shown as $1,234.56)  `<input v-model.dollars="cents" />`

Other use-case is sanitizing and unescaping html fields in order to prevent XSS atacks (Model stores "A &amp; B" while input shows "A & B") `<input v-model.html="text" />`

**Comment by orangevinz** [comment]
+1

**Comment by iStyx** [comment]
+1 for custom modifiers.
I was really surprised that I can't do something like `v-model.trim.uppercase=...`

**Comment by magisters-org** [comment]
+1

**Comment by rkingon** [comment]
+1

**Comment by lusarz** [comment]
+1

**Comment by Gotterbild** [comment]
+1 
Native `v-model` input modifiers would be a great feature. As people mention here, there are a lot of use cases. I had a need of date and currency modifiers for all projects I've been working on.

**Comment by phoet** [comment]
should we open an issue here? https://github.com/vuejs/rfcs

**Comment by rkingon** [comment]
i have already +1 this, but want to throw a note for people who need something “now”

while modifier is way more effecient, i have been able to achieve the same effect using a transparent input/component with a computed getter/setter field. 

i can share an example if someone needs it

**Comment by yyx990803** [comment]
We did not implement this because there are many things to be considered in this seemingly easy feature:

- The built-in modifiers are in fact compile-time hints that generates different compiled code. Custom modifiers likely need to be defined using a runtime config, which is a different mechanism.

- For runtime config, what kind of API should we expose for this?

- We had two-way filters in the past. A two-way value transform requires the user to implement impeccable logic so that the two-way binding can stabilize. Otherwise you risk putting your entire app in an infinite loop for edge cases.

  - The reason we have `.number` and `.trim` is because they are in-fact one-way transforms (only applied when syncing DOM value to component data) and thus guaranteed to stabilize.

- How should custom modifiers behave when `v-model` is used on a component?

All of these questions are unanswered and makes the request more complex than it seems. This is why I agree it would be a good candidate for a proper RFC if anyone really want this feature.

**Comment by Gotterbild** [comment]
@rkingon There is already an example in https://github.com/vuejs/vue/issues/3666#issuecomment-249583603, but if yours is different/better, just post it. It can be useful for novices.

**Comment by rkingon** [comment]
@Gotterbild i did miss that sample, but it is widely over complicated in later versions of Vue (that could have been pre transparent component support)

here is a very simple one I have that just converts a percent to decimal (ie: 4.5 -> .045) & vice versa ("view" value and "model" value)

```html
<template>
	<input type="number" v-on="listeners" v-model="innerValue">
</template>

<script>

	export default {
		props: ['value'],
		computed: {
			listeners () {
				const { input, ...listeners } = this.$listeners
				return listeners
			},
			innerValue: {
				get () {
					return (this.value) ? `${(this.value * 100)}` : ''
				},
				set (_val) {
					const val = (_val) ? (_val / 100) : ''
					this.$emit('input', val)
				}
			}
		}
	}

</script>
```

this is more simple than the above since you do not have to respecify all of the focus/blur/etc

**Comment by phoet** [comment]
@yyx990803 thanks for giving more background information on this topic.

for my use-cases, i do not "need" custom modifieres. it's just that from a consumers-perspective, it would make sense that vue has a way to build your own. it basically has that for everything, except modifieres 😄 

while i could find ways to create something that properly encapsulates my transformation logic and that i could reuse, i think that having a proper API for such use-cases would open up a much broader way of sharing common code through a collection of "best-practice modifiers".

**Comment by Christhofernatalius** [comment]
I came here because I was looking to make modifier to convert string to uppercase
I wanted to create it like `v-model.uppercase="username"`

I ended up using custom directive
```
Vue.directive('uppercase', {
	update (el) {
		el.value = el.value.toUpperCase()
	},
})
```

`<input type="text" v-model="username" v-uppercase>`

Custom directives should be enough for an alternative. 
Or is there something that only possible with custom v-model modifier?

**Comment by rkingon** [comment]
@Christhofernatalius considering `v-model` is simply a directive, couldn't you eliminate the `v-model` in favor of the custom directive? this way you're not updating twice?

**Comment by Christhofernatalius** [comment]
> @Christhofernatalius considering `v-model` is simply a directive, couldn't you eliminate the `v-model` in favor of the custom directive? this way you're not updating twice?

Is it updating twice?
So, if I don't use v-model, then I need to also add bind and unbind hook for input listener, and update username value?

**Comment by rkingon** [comment]
i haven't tried it, merely speculation -- i suppose the idea of two directives to update one value just feels a bit funny to me, but if you've checked it out, i don't see anything wrong with it.

my component workaround has limitations too, which is why i'm still in favor of a modifier -- ie: it requires an element, more rendering time, & only works as a component in how that component is defined (ie: an input field) vs being able to even simply use it on some arbitrary component/element which is the power of a directive.

two ways to skin the cat, nice to have options :)

**Comment by rightaway** [comment]
Is there an RFC for this?

**Comment by phoet** [comment]
i don't think so

**Comment by rightaway** [comment]
I could create it but does it just mean adding an issue in that RFC repo or something else?

**Comment by phoet** [comment]
https://github.com/vuejs/rfcs#what-the-process-is does this answer your question?

**Comment by jeankvd** [comment]
Can this be reopened please? A custom directive may work in some cases but behavior can be funny, example:

`
Vue.directive('number', {
  update: function(el, binding, vnode) {
    el.value = el.value.replace(/[^\d.]/g, '');
  },
});
`

If you add this directive (along with a v-model) and type letters really fast every other keystrokes the `v-model` will get out of sync with `el.value`. And since you cannot modify the binding object you receive there is no way to "reimplement" v-model inside this directive

**Comment by rkingon** [comment]
@jeankvd I know it feels like overkill, but a wrapper component is going to be the most reliable (see example above).

a wrapper component will allow you to "do more" as well. In your "number" example, ideally, the v-model actually becomes a `Number`. In your approach, it is still a `String`.

What if you want to customize the empty value? Empty String? Null? Undefined? -- you can pass in a prop for `emptyValue` and set it as such. 

While once an advocate for this, I realized shortly after modifiers have way too many limitations and just having a component is far superior (at least imo).
