### ISSUE TITLE
v-model with components doesn't allow using the value attribute for building custom checkboxes and radio buttons

### ISSUE THREAD

**Issue by asselin** [vuejs/vue#3674]
Goal is to create a custom component that provides additional features for checkboxes (e.g. custom icons for the checked and non-checked states) that works identically to standard checkboxes.

Standard checkboxes allow you to group multiple checkboxes together using an array for the v-model and the value attribute to specify what to append to the array when checked.  i.e.

````
<input type="checkbox" id="jack" value="Jack" v-model="checkedNames">
<label for="jack">Jack</label>
<input type="checkbox" id="john" value="John" v-model="checkedNames">
<label for="john">John</label>
````

The same thing can't be accomplished with components however.  If you try to use v-model and value together on a custom component, e.g.

````
    <bo-checkbox v-model='chk2' value="Jack">
      Custom Jack
    </bo-checkbox>
    <bo-checkbox v-model='chk2' value="John">
      Custom John
    </bo-checkbox>
````

`value` is overwritten by the `v-model` directive to pass into the component the value of `chk2`.  As a workaround, you can use a different attribute name (e.g. bo-value instead of value):

````
    <bo-checkbox v-model='chk2' bo-value="Jack">
      Custom Jack
    </bo-checkbox>
    <bo-checkbox v-model='chk2' bo-value="John">
      Custom John
    </bo-checkbox>
````

The downside is that that isn't the same syntax as a standard checkbox.

REQUEST: Consider renaming the prop that v-model uses to pass the value to the component so that it doesn't collide with the other usage of the `value` attribute.

**Comment by asselin** [comment]
Note: Tested on 2.0 RC6

**Comment by posva** [comment]
It makes sense to use `value` as the prop used by v-model because that's what you're changing, the value. You should instead use a different prop name for specific values like `checked-value`, `chekbox-value`, `option-value`, or something more generic like `input-value`.

I doubt we change the name of the prop as that will be a breaking change and there's no real advantage about changing it.
Furthermore, `v-model` is just syntax sugar that uses `value` as its prop but you can create your own directive to handle a different prop name to have that syntax sugar adapted to your preferences.

**Comment by yyx990803** [comment]
I think what's more important is not having the usage align with normal `v-model`, but rather making sure it's consistent across all the components you write. So if all of your custom form components use `bo-value`, that seems easy enough to remember.

**Comment by ksurakka** [comment]
This is an old thread already, but could there be some way to override the default `v-model` attribute per component, then it wouldn't be a breaking change but would make it possible to keep `v-model` usage in align.
