### ISSUE TITLE
v-if not working when used with v-for in child component

### ISSUE THREAD

**Issue by 7KVZw8C** [vuejs/vue#3684]
https://jsfiddle.net/vehj65vv/4/

**Comment by sqal** [comment]
```
v-if="member.channelName !== channelName"
```

channelName is undefined in your case. You forgot to add it data object

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

It does work: https://jsfiddle.net/posva/gw02w42o/
But as a side note I recommend you using a computed to filter the array first instead of using an if 😉
