### ISSUE TITLE
Computed property not updating properly

### ISSUE THREAD

**Issue by jws305** [vuejs/vue#370]
When I compute a value that is a conjunction of two boolean values in the data object, the result does not update when it should.

When I access the getters of the boolean values before returning the result, I get the expected value.

http://jsfiddle.net/XAbet/

Click the A and B button and notice the "A and B" value remains false.  Doing the same with C and D works as expected.

**Comment by yacinehmito** [comment]
I stumbled on the same issue. In case you're wandering here, this the real reason: the `&&` operator in JS is lazy. This means that in `x && y`, if `x` is `false` it will immediately return and will not look at `y`. Indeed, whatever the value of `y`, the result will be `false`.

In the fiddle provided above, `aAndB` is returning `this.a && this.b`. Because `this.a` starts at false, `this.b` is never called, meaning Vue will not register `b` as a dependency of `aAndB`.
However in `cAndD`, both`this.c` and `this.d` are called anytime the property is computed because they are used in an assignment. Only then will we return `c && d`, meaning that the laziness of `&&` will never cause us trouble.

**Comment by Glidias** [comment]
This is one of the caveats with Vue, since it does runtime dependency getter access tracking to determine dependencies for a computed property. It means all such boolean considerations must be seperated out first into seperate variables before stringing them with a `&&` or `||` operator to avoid this caveat. This does make your codebase much more long-winded than it should since you can't conveniently string the conditions into a single line.

My ideal Vue would be a seperate JS compiler/macro-preprocessor engine that would analyse your computed function's expressions and pre-compute an AST tree  (to detect any expressions for CIdent/Data accesses, and then already precompute these bindings already for your Vue/Vue components/modules/stores. This also avoids the overhead of pre-processing dependencies with getters at runtime.  However, this is easier said than done in particularly tricky cases where indirect function calls from/to different computed getters/setters and methods, may retrieve multiple dependencies across multiple functions... It's hard to do this even with a Haxe macro and it's accompanying AST. Thus, in the end (often at the cost of more boilerplate), i often resort to manually listing out such dependencies manually in codebases where where it's neede for Vue to reflect on it, prior to processigng those conditionals.

**Comment by yacinehmito** [comment]
In the case of Javascript ahead-of-time dependency tracking is doomed to fail. You can't know in advance which property will be accessed because property names are just strings. They can be the result of arbitrary computations, including network calls.

**Comment by simplesmiler** [comment]
Just want to point out, that this is a very old issue, and it has been fixed long time ago.
This has been working as expected at least since Vue 1.0: http://jsfiddle.net/XAbet/16/

**Comment by Twoody** [comment]
@cecchi appears your comment did not age well... To those reading, this is why we summarize the solution (or screen caps) instead of just posting links.
