### ISSUE TITLE
2.0 rc-7 toString() expression not works inside mustache  {{}}

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue#3763]
Hello ! I am very new Vue. Sorry if I miss something in documentation. 

I have a very simple template witch is not working as expected. I do not know exactly context of this.toString() but it is not vm.$data. 

```javascript
<div id="app">
    {{ this.toString() }} <!--should return $data.toString() but not works -->
</div>
```

**Comment by LinusBorg** [comment]
the template has not `this` context.

It simply has access to all properties and methods of the vm as variables. $data is one of those properties.
```html
<div id="app">
    {{ $data.toString() }}
</div>
```

**Comment by alexey2baranov** [comment]
Thanks for quik answer! maybe my English is too bad. Maybe you should wright this line in manual more clear

> These expressions will be evaluated as JavaScript in the **data** scope of the owner Vue instance.

**Comment by fnlctrl** [comment]
@LinusBorg
> the template has not this context.
It actually has... so it can access methods, $options etc. $data is on `this`, so the docs were correct.
http://jsfiddle.net/r9kojstk/

Since `this` is an object, using `this.toString()` simply gives `[object Object]`

**Comment by chrisvfritz** [comment]
And to add a little more info, Vue internally uses the `with` keyword to extend the scope chain to the Vue instance within templates. That means all properties on the instance should be accessed directly instead of under `this`. [Here's an example](https://jsfiddle.net/chrisvfritz/eLog1s95/) to demonstrate what Vue is doing.

For troubleshooting purposes, I recommend instead using `console.log(this)` within a lifecycle hook or method. Then you'll be able to inspect and explore the entire instance in an interface made for the job.
