### ISSUE TITLE
can not bind any event.eg: webkitAnimationEnd

### ISSUE THREAD

**Issue by WebGuHui** [vuejs/vue#3764]
Because the directive of the lower case

![image](https://cloud.githubusercontent.com/assets/11729740/18822306/fb960a76-83e0-11e6-81fc-5674235214f1.png)

### Vue.js version
1.0.26

**Comment by yyx990803** [comment]
You are looking at the wrong source code, that's for element directives.

This is a wontfix because:

1. HTML attributes are lower-cased by the browser before Vue can parse them, there's no way around this.

2. all standard-compliant events are lower case, this is a non-standard events that will not be supported.

3. Vue 2.0 doesn't have this problem when using string templates.
