### ISSUE TITLE
Dynamic transitions attributes do not complete their life cycle properly

### ISSUE THREAD

**Issue by GianlucaGuarini** [vuejs/vue#3784]
### Vue.js version
1.0.27

### Reproduction Link
http://jsfiddle.net/gianlucaguarini/5sH6A/701/

### Steps to reproduce
See the demo provided before

### What is Expected?
The v-show directive should display properly the DOM nodes when the transition ends

### What is actually happening?
Nothing is shown

**Comment by yyx990803** [comment]
Seems like you are using `v-for` just for the sake a transition effects? Suggested usage: http://jsfiddle.net/yyx990803/e3uw9t8c/1/

Similar to an earlier issue where you used `v-for` and `v-if` together on the same element, instead think from the source of the `v-for`. This will most of the time yield correct outcome.

This will be a wontfix for 1.x since there's no equivalent usage in 2.0 and has a workaround.

**Comment by GianlucaGuarini** [comment]
@yyx990803 thanks for you help but your workaround didn't work in my case. Of course the timers in my demo were just for demo purpose, in a real world usage I have to deal with user events that could be a lot more complicate than my jsfiddle above.
I get many flickering problems and js errors implementing your hack so I decided to switch to a more reliable solution just using css classes without counting on the vue transitions. I am looking forward to using Vue 2 hoping things will get better. Good luck
