### ISSUE TITLE
checkbox in v-for with v-model bindings on object is not two-ways

### ISSUE THREAD

**Issue by alexcode** [vuejs/vue#3785]
### Vue.js version
v2.0.0-rc.7

### Reproduction Link

Here are two simple identical fiddle with a v-for and checkbox v-model bindings. AFAIK the syntax has not change in the two versions, therefore I suspect this is an unwanted behavior.

Vue1.0: https://jsfiddle.net/v18kzzwo/4/
Vue2.0: https://jsfiddle.net/u3a8xqfL/2/

### Steps to reproduce
Click on the checkboxes in both fiddle.

### What is Expected?
I would expect in v2.0 that the state of the bind model to update like it does in v1.0

### What is actually happening?
In v2.0 the v-model binding for object seems only one-way, thus not updating when changed in the view.

**Comment by posva** [comment]
FYI you're binding to a boolean, not an object.
It looks like you're binding to the value itself, so basically you're doing the same as `v-model="true"`. I think this is intended as that'd be how js behaves: passing a copy of a boolean instead of a reference

You can get this working by using the key and binding to the actual property: https://jsfiddle.net/u3a8xqfL/2/

**Comment by yyx990803** [comment]
This is intended behavior in 2.0. It was mentioned in the comparison issue. We'll make sure it's in the migration guide.
