### ISSUE TITLE
Whole DOM gets rerendered on attribute change

### ISSUE THREAD

**Issue by danieldiekmeier** [vuejs/vue#3804]
### Vue.js version
2.0.0-rc.8

### Reproduction Link
http://codepen.io/danieldiekmeier/pen/bwRjQO?editors=1011

### Steps to reproduce
In the provided CodePen, open the console, then click the `Toggle` button above the list.

In the console, you will see that the list of `Item`s gets rerendered on every toggle of the `flag` attribute.

### What is Expected?
Only rerender the parts of the DOM that rely on data that changed. If this isn't possible, maybe advice on how to refactor to avoid this situation.

### What is actually happening?
The whole DOM rerenders, including expensive rendering of long lists. This is not so bad in the example, because it's only ten `Item`s, but I'm working on an app where it could be several thousand elements, and I'd really like to keep it *snappy*.

**Comment by LinusBorg** [comment]
Hi Danjel,

You kind of misunderstand what is happening:

* Whenever *any* reactive data changes, the render function is called - that's true, **but**:
* this function only creates a new *virtual DOM*
* Vue then diffs this new vDOM against the old one, and only changes the DOM where the two differ.
* Since the whole vDOM diffing is incredibly fast (it's just Javascript) compared to actual DOM updates, this is a ver cheap operation.

You can actually verify this in Chrome DevTools with your own codepen:

* right click the toggle button in your demo and inspect the element
* then left click the button to make it toggle.
* in the devtools elements tab, you will see:
  * the `<button>` element highlight, because it's being changed by Vue.
  * the list under the button does not get highlighted, because it's not being re-rendered.

**Comment by LinusBorg** [comment]
And a sidenote about performance of huge lists:

If you want to further optimize this, you could extract the list into its own child component, which only depends on the list data. 

In that case, Vue would not even re-render the vDOM for this child component when you click the toggle button. Instead, it would re-use its current vDOM, because Vue understands that this child component does not depend on the data which the toggle button changed.

**Comment by danieldiekmeier** [comment]
Oh, that explains a lot! Thanks! I'll definitely keep that in mind. 😎

You're of course absolutely right: There is no actual rerendering taking place.

Still, my *initial* rendering is taking quite a while. But I guess there's nothing I can do about it, because the DOM is slow, and Vue needs to create all the DOM nodes first?

**Comment by LinusBorg** [comment]
> Still, my initial rendering is taking quite a while. But I guess there's nothing I can do about it, because the DOM is slow, and Vue needs to create all the DOM nodes first?

That's correct.

**Comment by ginkosen** [comment]
@LinusBorg I have same issues , did you slove this problem? Thx;

**Comment by LinusBorg** [comment]
I did not intend to solve anything, so: no.

This is a closed issue, you will be better off describing your specific situation on the forum: forum.vuejs.org

I can see what I can do once you post there.
