### ISSUE TITLE
Render function of a functional component has parent set incorrectly

### ISSUE THREAD

**Issue by asselin** [vuejs/vue#3805]
### Vue.js version
v2.0.0-rc.8

### Reproduction Link

http://jsfiddle.net/asselin/223m0uzt/7/

This fiddle shows 2 implementations of `bo-switch`.  `BoSwitch` is implemented as a functional component, and exhibits the issue. `BoSwitch2` is implemented as a normal component, and shows that normal components don't have the issue.

### Steps to reproduce

I have an `App` component with the following template:

````
  <div id="app">
    <bo-radiogroup>
      <bo-switch>
          Switch1
      </bo-switch>
    </bo-radiogroup>
  </div>
````

If I implement `bo-switch` as a functional component instead of a regular component, then it's context.parent will be set to the instance of `App` instead of the instance of `bo-radiogroup`.

### What is Expected?

If `bo-switch` is implemented as a normal component, then in it's `beforeMount` and `render` functions, it will have `this.parent` set to the instance of `bo-radiogroup`.  I expect that if `bo-switch` is implemented as a functional component that `context.parent` would also be the `bo-radiogroup`.

### What is actually happening?

In the render function of `bo-switch` `context.parent` is set to the component instance of `App` instead.

**Comment by yyx990803** [comment]
Unfortunately this is expected behavior (can be confusing, I know) - basically, it's impossible to have access to `<bo-radiogroup>` inside the render function if `<bo-switch>` is functional, because functional components are **eager**. Its render function is called directly in `App`'s render function, before any child component instances are created. Stateful components are instantiated in a parent-to-child order so child components have access to its parent instance.

**Comment by asselin** [comment]
@yyx990803, would it be possible to document this in the functional section of the component documentation?

**Comment by yyx990803** [comment]
@asselin yes, /cc @chrisvfritz

**Comment by chrisvfritz** [comment]
It shall be done!

**Comment by asselin** [comment]
Thank you guys!
