### ISSUE TITLE
Passing JSON objects as properties no longer works in Vue2

### ISSUE THREAD

**Issue by Francismori7** [vuejs/vue#3829]
### Vue.js version
2.0.1

### Reproduction Link

```
<div id="app" :user='{!! auth()->user() !}}'></div>
```

### Steps to reproduce
So I'm using Laravel and I'm trying to pass a property of my currently logged in user, which worked properly in Vue 1.0. Now, I get this in my source output:

`<div id="app" :user='{"id":26,"name":"Francis Morissette","city":"N\/A","avatar":null,"email":"morissette.francis@gmail.com","created_at":"2016-09-29 20:13:00","updated_at":"2016-09-29 20:16:07"}'></div>`

This seems correct, however the property is `undefined` when checking in Vue devtools.

### What is Expected?
I expect to be able to pass my JSON objects to my components, or even my Vue instance, but using property bindings.

### What is actually happening?
I get an `undefined` property.

**Comment by craigpaul** [comment]
Correct me if I'm wrong, but I believe in Vue 2 on the root instance you can use propsData now. Check that out here - http://vuejs.org/api/#propsData . As for passing it into a component, you would be doing it correctly. Mind posting your Vue specific code just to verify?

**Comment by Francismori7** [comment]
True, but propsData would need to be used in my javascript files, which are not part of my server side views (meaning I cannot output my variables there).

```
const app = new Vue({
    el: '#app',

    props: [
        'user'
    ]
});
```

Simple as that.

**Comment by craigpaul** [comment]
I haven't tried using propsData myself personally, but I believe strictly using props on the root instance has been deprecated. See here https://github.com/vuejs/vue/issues/2873

"root instance can no longer use template props (use propsData instead)"

Now, as a solution, what I do in my Laravel/Vue apps is include my data in an external "store" aka a script tag. If you take a look at Laravel 5.3's default bootstrap file you'll see the Laravel.csrfToken reference. You could follow that same pattern and include your user in the root instance's data object instead of props/propsData.

Ps. Sorry for the poor formatting, I'm writing this on my phone.

**Comment by Francismori7** [comment]
@craigpaul This was actually my workaround for now 👍 

```
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
            'user' => auth()->user(),
        ]); ?>;
    </script>
```

**Comment by fnlctrl** [comment]
As @craigpaul pointed out, passing props to root instance in templates is deprecated in 2.0, please use `propsData` instead. 
@Francismori7 Glad you found a workaround!

**Comment by Francismori7** [comment]
@fnlctrl how does one use propsData?

**Comment by fnlctrl** [comment]
http://vuejs.org/api/#propsData

> True, but propsData would need to be used in my javascript files, which are not part of my server side views (meaning I cannot output my variables there).
I saw @craigpaul suggested `propsData` and you replied.... so I thought you knew?
