### ISSUE TITLE
computed property is not updated when its dependencies are binded with inline data

### ISSUE THREAD

**Issue by iraklisg** [vuejs/vue#3836]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/3xgv2e3n/2/

### Steps to reproduce
Replace `my_tasks` in `<task-list :tasks="my_tasks"></task-list>` with an inline list e.g. `[{body: 'Hello all', completed: false},{body: 'Goodbye all', completed: false}]`

### What is Expected?
It is expected the remaining computed property to be updated when user clicks on a task (i.e toggle its complete state from `false` to `true` and vice-versa), as it happens in case of binding the `my_tasks` data with `tasks` prop

### What is actually happening?
The computed property is not re-evaluated when its dependency (i.e. task.completed ) changes. 
Note that the JSfiddle code works fine with Vue 1.0.26, when replacing the  `my_tasks` with an inline list `[{/*...*/},{/*...*/}, /*...*/]`

**Comment by LinusBorg** [comment]
Can't check the repro right now, but this could be because migrating props is an anti pattern in 2.0: http://vuejs.org/guide/migration.html#Prop-Mutation-deprecated

**Comment by yyx990803** [comment]
Inline props are same as an immutable value, because every time the parent re-renders, the mutated child prop will be reset back to the inline value. Relying on reactively mutating an inline prop is a usage that no longer makes sense, therefore these inline values are not made reactive.

**Comment by zuomingcai** [comment]
when we declare a component in the template,we may want to set a initial value for its attributes but not to bind it to a parent variable.can vuejs support :prop.once ? it is much more convenient to set a initial value in template than in js code.

**Comment by LinusBorg** [comment]
This is a closed issue.

Also, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
