### ISSUE TITLE
Vue does not refuse invalid prop values

### ISSUE THREAD

**Issue by wonderful-panda** [vuejs/vue#3839]
### Vue.js version
2.0.1

### Reproduction Link
https://jsfiddle.net/ncsh5yse/1/
https://jsfiddle.net/ncsh5yse/2/

### Steps to reproduce
Just open above link

### What is Expected?
No text is shown

### What is actually happening?
Text `why this value is not rejected ?` is shown

### Description
Document says "When a prop validation fails, Vue will refuse to set the value", and v1.0.x behaves so.
But v2.0.1 does not refuse invalid prop values (only shows warning).

**Comment by yyx990803** [comment]
After some investigation, I decided to keep the current 2.0 behavior because:

- By not changing the value in any way, prop validation simply produces warnings as the only side effect. This makes it possible to entirely strip related code in production mode and preserve consistent behavior between dev/prod. Prop validation can be quite expensive so this is a perf sensitive case.

- There doesn't seem to be a very strong advantage of setting invalid value to `undefined` to justify the perf loss in prod mode.

Consider this a 2.0 breaking change, and we will update the documentation accordingly.
