### ISSUE TITLE
Can't seem to bind value property for inputs.

### ISSUE THREAD

**Issue by somazx** [vuejs/vue#3937]
The following works:
 ` <input v-model="message" :name="message">`
and results in the following when I enter foobar into the field:
`<input name="foobar">`

However try the same thing with the value property and it doesn't.
 ` <input v-model="message" :value="message">`
results:
`<input>`

**Comment by yyx990803** [comment]
Why are you using `:value` when you are already using `v-model`? `v-model` already binds the value for you.

Also, the `value` is bound as a property instead of an attribute, so it doesn't show up in the markup.

**Comment by somazx** [comment]
I want the element on the input showing the current value.

**Comment by simplesmiler** [comment]
@somazx as Evan said, value is bound as a property, not as an attribute. This is because value attribute does not reflect the current value of the input, it reflects the initial value. And submitting the html form takes the current value, not the initial one, so just having `v-model` and `:name` will work correctly.

**Comment by somazx** [comment]
@simplesmiler @yyx990803 Ohhhhh! Thank you for explaining that. Now I understand! Sorry about that.
