### ISSUE TITLE
[2.0] data attribute point to a function defination

### ISSUE THREAD

**Issue by rockkratos** [vuejs/vue#3944]
Hi,

I want to set a data attribute point to a function definition which is set in methods. 
Just like the below. Is there any possible? 

```
data() {
  return {
    handler: this.methods.handler
  };
},

methods: {
  handler() {
    console.log('*****');
  }
}
```

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You probably don't need to add it to the data because it's already on the methods. You'll need to add a bit more context **on the forum post or StackOverflow question** so people can help you better solve the problem
