### ISSUE TITLE
How include <script> tag in template component ?

### ISSUE THREAD

**Issue by tronghiep92** [vuejs/vue#4005]
Hi guys,

I want to include scipts only in page Contact.vue
```
<template>
 <div id="map"></div>
 <script
    src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY">
 </script>
</template>
```

With mode `developer` it work, but in `production` it not working and removed `<script>`?

Please help me?
Tks!!

**Comment by LinusBorg** [comment]
Hello @tronghiep92 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
