### ISSUE TITLE
Suggestion for schema management

### ISSUE THREAD

**Issue by MarcTe** [vuejs/vue#4009]
Hi, I know, this project is a frontend, but as it is based on many-components-for-creating-one-form,
and because Vue.js is a good innovation pole, I would like to raise the feature of schema management, or cooperation to one. I am however not technical in JS enough for coding this project.

As I am also interested in Meteor, I already sent the same message to aldeed (the Simple Schema package maintainer)

I think it could be a good lever in an object oriented frontends, that would improve everything fast.

A Word file is enclosed, let me know if you prefer another format.
Updated version in next post.

Thanks
Marc

**Comment by MarcTe** [comment]
Here is an updated version.

[Suggestions for Simple Schema.docx](https://github.com/vuejs/vue/files/545201/Suggestions.for.Simple.Schema.docx)

**Comment by yyx990803** [comment]
Hi @MarcTe , thanks for the proposal, however I don't think an issue is the best place for this discussion because:

1. The proposal doesn't include any concrete implementation suggestions for Vue yet;
2. It involves the server-side and the data layer which are out of scope for this repo (e.g. Meteor, Apollo)

Feel free to submit this to the [forum](https://forum.vuejs.org) and invite members from the Meteor/Apollo community to join the discussion.
