### ISSUE TITLE
Transition class bind null values has DOMException in addClass function.

### ISSUE THREAD

**Issue by sean220** [vuejs/vue#4050]
### Vue.js version

2.0.1

```
<transition :enter-active-class="animatedIn" >
```

When 'animateIn' bind value is empty string or null,addClass function has exception:

```
vue.js:4540 Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty
```

Semantically,Binding a null value is intended to remove the transition effect.
Should a null check be made in addClass function or the transition should be ignored in the case of null values?

**Comment by phanan** [comment]
IMHO a warning should suffice. I'll try a PR.

**Comment by phanan** [comment]
Actually I can't reproduce this. Can you provide a fiddle?

**Comment by sean220** [comment]
[jsfiddle repro](https://jsfiddle.net/ms9xmduu/)

**Comment by phanan** [comment]
Thanks. IMHO the `addClass` and `removeClass` functions should check for falsy values and warn if in development. Will work on a PR.

**Comment by yyx990803** [comment]
What do you mean by "cancel"? Are you trying to interrupt an ongoing animation and make it snap to the end state, or to "turn off" the transition so that it doesn't trigger anymore?

In either case, setting the bound class to `null` or empty string is the wrong way to do it. There's no way to "interrupt" an already triggered transition, but you can revert it by toggling the state controlling the element inside.

As for "turning off", we could probably add a `disabled` prop for transition components. For now the workaround is just using `v-if`to toggle between a transition-wrapped and non-transition-wrapped version of the same element.

**Comment by sean220** [comment]
For my case, It is turn off the transition effect,But at some point, Instead of remove the entire effect use 'v-if', May I just remove one of enter or leave effect? @yyx990803
