### ISSUE TITLE
vue2.0.3 with createElement not work well with transition component

### ISSUE THREAD

**Issue by Jokcy** [vuejs/vue#4074]
### Vue.js version
2.0.3

### Reproduction Link
http://jsbin.com/tunutuwazo/edit?html,css,js,console,output

### Steps to reproduce
click "click me" button don't show transition

### What is Expected?
show fade transition

### What is actually happening?
don't show transition

Transition also not working with babel-plugin-transform-vue-jsx3.1.0, I make the render funtion as what compiled from jsx, what should I do?

**Comment by fnlctrl** [comment]
You're not using the correct createElement syntax.
Fixed: http://jsbin.com/bulikiyegu/3/edit?html,css,js,console,output

1. Transition names should be specified by:
```
attrs: {
  name: "fade"
}
```

2. `v-show` should be translated into 
```
directives: [{
  name: 'show',
  value: this.show
}],
```

` babel-plugin-transform-vue-jsx` works fine here. If you can provide a code snippet (since it's not possible to put in jsbin), please follow up in this issue.

**Comment by Jokcy** [comment]
@fnlctrl I found this on the readme of babel-plugin-transform-vue-jsx

>Note that built-in Vue directives are not supported when using JSX

So I never use v-show in jsx, I guess if built-in directives is supported in jsx, you should update the readme

**Comment by fnlctrl** [comment]
Actually `v-show` is the only built-in directive that works in jsx... I'll make a PR to the repo.

**Comment by Jokcy** [comment]
🙃that will be good
