### ISSUE TITLE
Cannot get built in directives using Vue.directive(directiveName) in Vue 2.0

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue#4100]
Not sure if this is a bug report or a feature request - it was possible in Vue 1, but doesn't seem to be in Vue 2.

In Vue 1.0, you could get the object representing a built-in directive using `Vue.directive()`:

```js
Vue.directive('for'); // an object
```

This was useful for extending built in directives. For example, `v-paginated-for`:

```js
const forDirective = Vue.directive('for');
const forPaginatedDirective = Object.assign({}, forDirective, {
  bind() {
    const inMatch = this.expression.match(/(.*) (?:in|of) (.*)/);
    
    const subset = this.vm[inMatch[2]].slice(0, 10);
    this.vm.$set(`${inMatch[2]}Paginated`, subset);
    this.expression += 'Paginated';
    forDirective.bind.call(this);
  }
});
Vue.directive('paginated-for', forPaginatedDirective);
```

(untested and [very] minimal code sample)

In Vue 2.0, `Vue.directive('for')` returns undefined.

Is what I was doing possible in Vue 2.0? Or is this a case of why-would-you-even-do-that?

**Comment by yyx990803** [comment]
It's true that this is not possible in 2.0 - because in 2.0 `v-for` is compiled into a JavaScript loop in the render function. There's no runtime definition for it.

The usage you posted seems a bit hacky - I'm sure the equivalent can be achieved from a more data-driven approach rather than patching built-in directives, but that's another topic. Feel free to open a discussion on the forum.
