### ISSUE TITLE
Error: read property of null

### ISSUE THREAD

**Issue by DiHuang1986** [vuejs/vue#4123]
when render a deep property of one object, if one part of the chain is null, the whole project will be suspended and break by `Cannot read property '' of null`. 
reproduce is follows:
[jsfiddle](http://jsfiddle.net/vm0bfku0/9/)
no list is rendered because one name is null, you can see the error in console.

while using angular, `{{ people.name.firstName }}` if `name` or `people` is null, the result will be empty, but vue can not handle this expression.
i can do `<span v-if='people && people.name'>{{ people.name.firstName }}</span>` but this solution is not pretty. 

i tried Vue.config.silent, but that is not supposed to solve this problem.

is there any better way to render deep object?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
Vue doesn't have those angular magics, what you're writing will be executed as plain javascript, so errors will be thrown if you're trying to access properties of null/undefined.
Therefore, the solution is simply just what you would do in javascript: `person.name && person.name.firstName`, which is translated to `<span v-if='people && people.name'>{{ people.name.firstName }}</span>`. 
If you'd like to try jsx instead of templates, you can easily use 3rd party libs to get deep object's property, namely [lodash's `_.get`](https://lodash.com/docs/4.16.6#get), and it can be written as `<span>{ _.get(people, 'name.firstName')}</span>`.

**Comment by LinusBorg** [comment]
or, to use get in templates:
```
import get from 'lodash.get'

Vue.prototype.$get = get
```
