### ISSUE TITLE
Transition behave different when writing enter and leave-active in a single rule?

### ISSUE THREAD

**Issue by reverland** [vuejs/vue#4154]
### Vue.js version
2.0.3

### Reproduction Link

http://codepen.io/reverland/pen/ZBGKoW
### Steps to reproduce

the left accordion behaves normally, however, when I write enter and leave-active in a single rule, 
it'll lost enter transition

### What is Expected?

all left or right behaves the same

### What is actually happening?

the right one just have leave transition

**Comment by HerringtonDarkholme** [comment]
This is an expected behavior.

According to the [doc](https://vuejs.org/v2/guide/transitions.html#Transition-Classes), 

> v-enter: removed after one frame.
v-enter-active:  removed when transition/animation finishes.

And these two classes are applied at the same time.

Your `.collapse-useless-enter-active` is defined after `.collapse-useless-enter`, and they are applied at the same time. So enter-active wins the css rule and `max-height` is kept as 800px. So no transition.

Fixed:  http://codepen.io/anon/pen/zovQpG
