### ISSUE TITLE
Multiple components in dynamic components can't call hook detached.

### ISSUE THREAD

**Issue by SidKwok** [vuejs/vue#4162]
### Vue.js version
1.0.26

### Reproduction Link
http://jsfiddle.net/df4Lnuw6/37/

### Steps to reproduce
1. dynamic component
2. I have two dynamic components called A and B. And I also define a common component called C, D. Their connections are: 
root--A--C--D
      |--B--D

### What is Expected?
each component's hooks 'attached' and 'detached' will be called in a proper way.

### What is actually happening?
In this connection: root--A--C--D
D's `detached` was never called.

Is it a bug or just some kind of rules I missed?

**Comment by posva** [comment]
What you're actually looking for are lifecycle hooks like the `destroyed` hook. 
`detached` isn't a lifecycle hook, it's triggered when `$remove`ing a component. The problem here is that once the detached hook is called on the parent component, children vm don't have an `$el` anymore nor `$children` and therefore the `detached` hook can only be called on the first level children of a detached component.

**Comment by SidKwok** [comment]
Thanks for you reply, I think it solved my problem perfectly.
