### ISSUE TITLE
Redistribute content, given with <slot> 

### ISSUE THREAD

**Issue by SkyKilla** [vuejs/vue#4169]
Experienced real trouble migrating to Vue 2
because:
##  #Duplicate Slots removed

How it works in Vue 1.x
https://jsfiddle.net/Yenisey/hchx3v1o/

Consider, there must be API method, or some other way to clone this.$slots.default

**Comment by LinusBorg** [comment]
Hello @SkyKilla 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by SkyKilla** [comment]
> However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug 
> reports` and feature requests (as outlined in our Contributing Guide).

Feature request - that's exact what it was:
>>....API method, or some other way to clone

**Comment by LinusBorg** [comment]
Sorry, but your two-sentence issue could easily be mistaken for a question (how to do this in Vue2?) So have you asked about how to do this in Vue 2? I must ahve missed that post on SO / the forum, please refer me to it.

Hint: An answer might be to clone the vNodes of $slot in a render function.

If you actually want to request a feature, please open another issue, in which you describe the general usecase of what you want to do - I won't digg through a 140 LoC jsfiddle to find out what exactly your feature should look like.

**Comment by SkyKilla** [comment]
Please refer to our discussion once again (I update it)
https://forum.vuejs.org/t/vue-2-v-for-in-slot-duplicate-presence-of-slot-default/1734
Thanks for patienсe, and have a good day!
