### ISSUE TITLE
Style blink issue of SSR

### ISSUE THREAD

**Issue by JiayangShen** [vuejs/vue#4186]
VUE Version: 2.x

Server Side Rendering(SSR) is a great feature of VUE 2. However, I found a issue. SSR does not output styles in .vue file to the first screen page. Though we can extract styles in .vue files to one external large size .css file, for a large SPA, it does not suitable to do this way. Because large size css file will block the other assets  in the page from downloading.

Is there any solution for this issue?

**Comment by yyx990803** [comment]
You should be using extraction any way, because if you don't, the styles are inlined as strings in your JavaScript. The payload/blocking factor is the same. BTW - I don't think large CSS blocks downloading other assets, it only blocks rendering.

This concern can be solved with code splitting + fallback loader for the extract text plugin (additional style chunks would be inserted dynamically when async chunks are loaded), but at the moment best practices for SSR + code splitting is something that still needs to be worked on. We will be updating the [vue-hackernews-2.0 demo](https://github.com/vuejs/vue-hackernews-2.0) in the future once we settle on a good solution.

**Comment by JiayangShen** [comment]
@yyx990803 Thanks for you reply! Actually, My project is a large SPA based on VUE 2.x, code splitting is neccesary and is the best practice. Every page is a .vue file that downloaded on demand using code splitting. It works very well on browser, stylesheets and other parts in each .vue file are compiled into a js file. But for ssr, it doesn't. The first screen render will blink for no styles for it. Currently, I only have to extract all styles in all pages into one large css file and include it in the html file to solve this problem..

**Comment by ZeroDark1991** [comment]
I'm facing the same issue, does it have better solution now?@JiayangShen

**Comment by dongqudamage** [comment]
我面临同样的问题，现在有更好的解决方案吗？@JiayangShen
