### ISSUE TITLE
Case-sensitive attribute names don't work with v-bind

### ISSUE THREAD

**Issue by vote539** [vuejs/vue#4212]
### Vue.js version
2.0.5

### Reproduction Link
http://jsfiddle.net/df4Lnuw6/45/

### What is Expected?
Vue should create attributes having case consistent with that in the template.

### What is actually happening?
Vue creates attributes that are the lowercased version from the template.

This problem is only noticeable when using the subset of tags that are case-sensitive, like the <svg> tag.  For example, consider the "viewBox" attribute.  In the demo linked above, Vue produces the attribute "viewbox" instead of "viewBox", causing the SVG to be rendered incorrectly (tested in Firefox and Chrome).

**Comment by simplesmiler** [comment]
It happens because browser mangles the casing before Vue has a chance to do it's thing.

In 1.x the `.camel` modifier was introduced to address this issue: https://github.com/vuejs/vue/issues/2250
It does not appear to have made it's way to 2.0, but in 2.0 there's another semi-workaround. If the template comes from the string, and not from the DOM, then Vue is able to process it before the browser: http://jsfiddle.net/df4Lnuw6/47/

**Comment by vote539** [comment]
Thanks for the quick reply and the workaround!

**Comment by yyx990803** [comment]
`.camel` will be back in 2.1.0, but still, it's recommended to use string templates if you can.
