### ISSUE TITLE
vue-functional-compoent

### ISSUE THREAD

**Issue by lin-xi** [vuejs/vue#4234]
https://github.com/Jokcy/vue-functional-compoent
`
import Vue from 'vue'
import functionalComponentFactory from 'vue-functional-component'
const makeFunctionalComponent = functionalComponentFactory(Vue)

// make sure your component is declared at global
makeFunctionalComponent('name', {config})
`
this is not working in vue 2, how to do this in vue 2

thank you very much!

**Comment by yyx990803** [comment]
Please open issue at that repo instead...

**Comment by lin-xi** [comment]
`
let MessageConstructor = Vue.extend(require('./main.vue'));
instance = new MessageConstructor({
    data: options
  });
  instance.id = id;
  instance.vm = instance.$mount();
  document.body.appendChild(instance.vm.$el);
  instance.vm.visible = true;
  instance.dom = instance.vm.$el;
  instance.dom.style.zIndex = PopupManager.nextZIndex();
  instances.push(instance);
`
I found that if main.vue requires other components, this code will throw exceptions, other components will not be correctlly rendered, what can i do to make this code run,  with the main.vue requires other components

thank you,  yyx!

**Comment by LinusBorg** [comment]
Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
