### ISSUE TITLE
Are the directives (v-show and v-if) not overriding the class?

### ISSUE THREAD

**Issue by inventti-leonardo** [vuejs/vue#4238]
[https://jsfiddle.net/fstxdync/1/](https://jsfiddle.net/fstxdync/1/)

:(

**Comment by defcc** [comment]
Thanks @inventti-leonardo . It's an expected behavior for v-if, because v-if directive just checks the expression and do the conditional rendering. As for v-show, the current behavior is that it only toggles the **style.display** property, maybe there should be an improvement.

**Comment by yyx990803** [comment]
Is there any reason you need the `hidden` class and `v-show` on the element at the same time? If you want the element's visibility to be controlled by `v-show`, just let `v-show` do its job - I don't see the point of having the `hidden` class at all.

**Comment by inventti-leonardo** [comment]
I'm bit confused, I was thinked that behavior of v-show is equivalent to css:

`<p class="hidden" style="display: block">Show</p>`
`<p class="hidden" v-show="true">Not show</p>`

I have been do this, to ensure that some elements not show on initial load (using other libs, not vue), I'm migrating to vue right now :)

**Comment by yyx990803** [comment]
No, because depending on different elements, there could be different default `display` properly, `block` is not the only possible value. Also, `v-show` has to take into account inline display properties like `style="display: inline" v-show="xxx"`.

For your use case, you should probably use [v-cloak](https://vuejs.org/v2/api/#v-cloak) instead - it gets removed once Vue finishes rendering.
