### ISSUE TITLE
test confusion

### ISSUE THREAD

**Issue by zzz6519003** [vuejs/vue#4249]
```js
  it('with key modifier', function (done) {
    new Vue({
      el: el,
      template: '<a v-on:keyup.enter="test">{{a}}</a>',
      data: {a: 1},
      methods: {
        test: function () {
          this.a++
        }
      }
    })
    var a = el.firstChild
    trigger(a, 'keyup', function (e) {
      e.keyCode = 13
    })
    _.nextTick(function () {
      expect(a.textContent).toBe('2')
      done()
    })
  })

```
what is `      e.keyCode = 13` doing? the keycode 13 represent the enter key right?

should I just ask on gitter sorry for disrupting

**Comment by HerringtonDarkholme** [comment]
Thanks for supporting Vue.

Rather than gitter, you might ask Bing (or Google). http://www.w3schools.com/jsref/event_key_keycode.asp http://stackoverflow.com/questions/6086686/keycode-13-is-for-which-key

It mocks a `keyup` event, and the mocked event is supposed to stand for pressing enter key. So the Vue instance in test should execute `test` callback.

**Comment by zzz6519003** [comment]
what does the `with key modifier` mean?  I don't get it

**Comment by zzz6519003** [comment]
the test name
