### ISSUE TITLE
Computed property got from data property with increment operator does not keep update

### ISSUE THREAD

**Issue by hyiso** [vuejs/vue#4286]
Yesterday I occasionally found this [discussion](https://forum.vuejs.org/t/computed/3273/3).
Copy it as follow:
```
var vm = new Vue({
     el : "",
     data: {
          a: 1
     },
     computed: {
          mul: function() {
                 return this.a ++
          }
     }
});
console.log('vm.a =' + vm.a);  //=1
console.log('vm.mul = ' + vm.mul);  //=1
console.log('vm.a =' + vm.a); //=2
console.log('vm.mul = ' + vm.mul);  //=1
```
The last line `console.log('vm.mul = ' + vm.mul)` was supposed to be `2` but got `1` instead.
I've also created a [live demo on jsfiddle](https://jsfiddle.net/shsq474s/4/).
This exists both in 2.x and 1.x
I digged into the code and then found the reason and the solution.

Maybe I should give it a pull request, but i don't know whether i need to fix it only in 2.x or both.

**Comment by HerringtonDarkholme** [comment]
I believe the problem is the original author does not understand Vue's reactivity system. If one wants to update a property, he/she must assign a new value to it. increment operator is simply not supported by vue. For the code in problem, the author can change it to `this.a += 1`. (As a side not, side effect in getter is bad practice.)

Thanks for your effort to fix this, but as discussed under the pull request, it might introduce **unpredictable** breaking change to user code. And we cannot roll out a migration guide for this breaking change.

**Comment by hyiso** [comment]
Yes, I think this scenario is a bad usage. 
one can just use following code to keep `mul` with `a` and then call `increment` anywhere else. 
```var vm = new Vue({
     data: {
          a: 1
     },
     computed: {
          mul: function() {
                 return this.a
          }
     },
     methods: {
        increment: function(){
            this.a += 1
        }
    }
});
```

**Comment by yyx990803** [comment]
As stated elsewhere, computed getters should not produce side effects.
