### ISSUE TITLE
[2.1.0+] Can't mount to jsdom's element

### ISSUE THREAD

**Issue by rwu823** [vuejs/vue#4304]
Everything works fine before upgrade to `v2.1.0`

**Comment by yyx990803** [comment]
Can you provide a repro?

**Comment by rwu823** [comment]
|               | Vue `v2.0.8` | Vue `v2.1.0+` | Travis CI                                |
| ------------- | ------------ | ------------- | ---------------------------------------- |
| **Node** `v6` | Pass         | Pass          | log                                      |
| **Node** `v7` | Pass         | Fail          | [log](https://travis-ci.org/cepave-f2e/vue-owl-ui/builds/178495484) |

**Comment by yyx990803** [comment]
One thing I noticed is that in jsdom + Node 7, `Object.prototype.toString.call(window)` is now `[object Object]` instead of `[object global]` (in Node 6). This makes Vue think it is in Node rather than in the browser... not sure how the tests were passing for 2.0.8 though.

I adjusted the in browser detection and you could try building from the `dev` branch to see if the tests would pass in Node 7.

**Comment by rwu823** [comment]
@yyx990803 

This detection is working great and tests would be passed in Node 7.

https://github.com/vuejs/vue/commit/e89830230c5747fbe1b70bb4e6c423c3ec2934cc?diff=split#diff-e7a9d17ad709614e8b8a17f648323d39R10

Thanks again Evan 💯
