### ISSUE TITLE
HTML codes render inconsistently

### ISSUE THREAD

**Issue by znck** [vuejs/vue#4309]
### Vue.js version
2.0.2

### Reproduction Link

https://jsfiddle.net/znck/6fg8d5ag/

### Steps to reproduce
Add `{{ '&#x1f600;' }}` and `{{ x }}` to template where `x` is computed property or data (and set to `'&#x1f600;'`) renders differently.

### What is Expected?
Both should render an emoticon.

### What is actually happening?
String renders to emoticon while variable renders to text.

**Comment by simplesmiler** [comment]
In fact it's working correctly.

`&#x1f600;` in the DOM gets parsed by the browser into a literal emoji before Vue has access to it. Thus Vue sees literal emoji in the template, and outputs emoji. It also does entity encoding, but it does not change anything in this case.

`&#x1f600;` in the script is not parsed by the browser. Thus Vue sees literal `&#x1f600;` in the template   and outputs `&#x1f600;`. But because of the entity encoding, it becomes literal ` &amp;#x1f600;`, which would be displayed as `&#x1f600;` after being parsed by the browser.
