### ISSUE TITLE
Text input binding is not work correctly for Korean

### ISSUE THREAD

**Issue by choyongjoon** [vuejs/vue#4330]
### Vue.js version
2.0.2

### Reproduction Link
http://jsfiddle.net/oh1arwsb/

### Steps to reproduce
Type some Korean into the input (ex. `안녕하세요`)

### What is Expected?
(Shown in input, Updated in data) 
(`ㅇ`, `ㅇ`)
(`아`, `아`)
(`안`, `안`)
(`안ㄴ`, `안ㄴ`)

### What is actually happening?
(Shown in input, Updated in data) 
(`ㅇ`, )
(`아`, )
(`안`, )
(`안ㄴ`, `안`)

As you see in the logs, `input` event show expected result. 
And `compositionend` event is not enough for Korean.

In React, it works alright.

**Comment by yyx990803** [comment]
Are you expecting the binding to be updated during composition? This is an intentional decision: `v-model` does not update the state until the end of a composition. For languages like Chinese, when people are composing with PinYin, it will fill the input with a lot of useless text.

Is it particularly important to update the state during composition? I doubt this makes a big difference from a UX perspective.

**Comment by choyongjoon** [comment]
I'd prefer updating during composition for Korean. But I understand your design decision. In react, there is an opposite issue ["Change event fires too many times when inputing Chinese characters"](https://github.com/facebook/react/issues/3926). It's not that important to change.

But the guide should inform that the binding will not update during composition. In [the guide](https://vuejs.org/v2/guide/forms.html#lazy), 

> By default, `v-model` syncs the input with the data after each `input` event.

So people who wants to update during composition can use the `input` event without `v-model`.

**Comment by yyx990803** [comment]
@choyongjoon makes sense, tracking in https://github.com/vuejs/vuejs.org/issues/616 Thanks for the suggestion!
