### ISSUE TITLE
Getter/Setter syntax

### ISSUE THREAD

**Issue by thejameskyle** [vuejs/vue#4409]
Thought I'd write this up since it came up on Reddit.

It would be cool if Vue made use of ES5 getters/setters on objects instead of the way computed props work today.

Either:

```js
var vm = new Vue({
  data: { a: 1 },
  computed: {
    // get only, just need a function
    get aDouble() {
      return this.a * 2
    },
    // both get and set
    get aPlus() {
      return this.a + 1
    },
    set aPlus(v) {
      this.a = v - 1
    }
  }
})
```

Or even just:

```js
var vm = new Vue({
  data: { a: 1 },
  // get only, just need a function
  get aDouble() {
    return this.a * 2
  },
  // both get and set
  get aPlus() {
    return this.a + 1
  },
  set aPlus(v) {
    this.a = v - 1
  }
})
```

Using `Object.getOwnPropertyDescriptors(instance)` you can get these getters and setters and apply the [watching logic being done here](https://github.com/vuejs/vue/blob/4da64ee2ae1aef91d70a2bdbe762fbf6a6230e72/src/core/instance/state.js#L112-L148).

This will also make it easier to integrate with type systems like Flow in the future (Flow understands the syntax but doesn't type check getters/setters).

**Comment by yyx990803** [comment]
The primary concern I have with this is that there is an intrinsic misalignment between the Vue options object and general type checking systems. To Vue internals, the options object is a meta object that can contain more information than a plain ES2015 class.

I assume if we keep the `computed` nesting, even using literal get/set doesn't help Flow understand it because `this` inside the getter would be the `computed` object instead of the Vue instance, right? So the only way to make Flow potentially play nice with it is removing the nesting.

But the nesting is useful to Vue in a lot of cases - for example, the options nesting allows them to be merged with different strategies during component extensions, and enables userland composition, e.g. in Vuex:

``` js
computed: {
  ...mapState({
    count => state => state.count
  })
}
```

With the literal getter/setters, there's quite a bit of indirection for such use cases. It's even harder without nesting.

---

Alternatively, if a Vue user is serious about getting proper class-based type checking, [vue-class-component](https://github.com/vuejs/vue-class-component) is probably the way to go.

**Comment by thejameskyle** [comment]
Sometime in the future Flow will add a syntax for adding the type of `this` in functions (simple semantics, but is hard to implement), but the problem is more around how does the `foo` in:

```js
let instance = new Vue({
  computed: {
    foo() {...}
  }
});
```

Become `instance.foo`?

With getters/setters at the top-level it's pretty natural, but being nested the way they are you have to do weird stuff with mapping props into an intersection type (I'd have to spend some time working it out) in order to get correct types.

**Comment by smolinari** [comment]
🍿 👍  😄 

Scott

**Comment by yyx990803** [comment]
Closing since I don't think it's worth it to introduce an alternative syntax just for type checking purposes (plus losing some of the composition flexibility), especially when a more full-fledged approach is available via `vue-class-component` if type checking is strongly desired.

We may revisit this when ES classes become expressive enough to be used as the default for defining components.
