### ISSUE TITLE
Chunked Transition Group filtering

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vue#4446]
Is there any good way to transition a chunked list

im using animate css but it seems it doesn't work flawlessly

im also using mode="out-in" in transition group is this supported?

the list will be chunked by 3 and so on and add row class per chunk and 3 columns

![image](https://cloud.githubusercontent.com/assets/19868205/21085934/8f348944-c052-11e6-8767-e828c23f0f72.png)

but the transitioning between components doesnt work properly like this

![image](https://cloud.githubusercontent.com/assets/19868205/21085950/b3ca988e-c052-11e6-821e-6acaa951e9d5.png)

This is the snippet of my code in my main layout
```
    <transition-group  style="margin-bottom: 1rem;" v-for="data3 in dataList"
                      class="row" mode="in-out"
                      enter-active-class="animated bounceInRight"
                      leave-active-class="animated bounceOutRight">

      <div class="col-xs-12 col-md-4" v-for="data in data3" :key="data['.key']">
        <md-card md-with-hover>
          <slot :data="data"></slot>
        </md-card>
      </div>

    </transition-group>


```
using this computed propert for filtering and search
```
      dataList() {
        let items = this.list;
        if(items && this.search && this.searchKey) {
          let regExp = new RegExp(`${this.search}`,'i');
          items = _.filter(items, item => {
             return regExp.test(item[this.searchKey])
          });
        }
        return _.chunk(items, 3);
      },
```

**Comment by LinusBorg** [comment]
Hello @DevEclipse 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
