### ISSUE TITLE
how i dynamic change component's level (it parent or host in dom tree) for itself on hook method (e.g. created、mounted etc.. )？

### ISSUE THREAD

**Issue by junhwong** [vuejs/vue#4448]
how i dynamic change component's level (it parent or host in dom tree) for itself on hook method (e.g. created、mounted etc.. )？

-----

I want define a component **popover** , it render to root(document.body) not in it parent.
```html
<script>
export default {
   name:  'test'
   // ...
}
</script>
<template>
<div>
...
<popover>show</popover>
</div>
</template>
```

implements **popover**  not is **test**'s child.

**Comment by LinusBorg** [comment]
Hello @jinhwong

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
