### ISSUE TITLE
How can I set candidate background image when background image can not be found(404)?

### ISSUE THREAD

**Issue by komajunjun** [vuejs/vue#4451]
When the background image can **not** be found, I use **onerror** to set the **candidate** background image, but it doesn't work. What's wrong?
`		<div class="header" v-bind:style="{ backgroundImage: 'url(' + schedule.courseLogo + ')' }" onerror="this.style.backgroundImage='url(&quot;../images/course-default.jpg&quot;)'">
			<div class="title text-shadow-none">{{schedule.courseName}}</div>
		</div>`

**Comment by LinusBorg** [comment]
Hello @komajunjun 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by komajunjun** [comment]
thank @LinusBorg , I have asked the question on [quora](https://www.quora.com/unanswered/How-can-I-set-candidate-background-image-when-background-image-can-not-be-found-404), can you answer my question there, thanks in advance.

**Comment by LinusBorg** [comment]
No, I'm not on quora.

**Comment by JounQin** [comment]
Notice this code: 
```
"url(../images/course-default.jpg)"
```

The image won't be loaded automatically by webpack, you should require/import it by yourself as a data property of vm, then you can use it in your template.

**Comment by komajunjun** [comment]
@JounQin do you mean that I should require/import url firstly?
