### ISSUE TITLE
Allow parent component to pass its scope to nested children

### ISSUE THREAD

**Issue by alidcastano** [vuejs/vue#4470]
Let's say I have an editor component and a button component. When you click the button, it needs to toggle changes in the markup state of the editor. 

Currently, you can access the parent with the `$parent` instance property, as shown below:

```
// index.vue
<editor>
  <btn for="strong"> Bold </btn>
</editor>

// btn.vue
<template>
<button @click="toggle"><slot /> </button>
</template>

<script>
....
  methods: {
    toggle() {
      this.$parent.toggle()
    }
  }
</script>
```

However, this solution feels like an antipattern.

The intended usage would be more explicit and less prone to errors if you could pass the parent instance to the child component.

For example, Emberjs does it like this:

```
{{#editor as |parent|}}
  {{btn for="strong" parent=parent}}
{{/editor}}
```

There are many other situations where you need the child component to access parent context, but, as far as I know, nothing like this exist. What do you think about vuejs supporting such a feature?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.  [Custom Events](http://vuejs.org/v2/guide/components.html#Custom-Events) is designed for direct parent-child communication, and passing parent reference to child is considered an anti-pattern in vue (no matter in what way), since it couples parent and children's implementation.
