### ISSUE TITLE
Not autoprefix `animationend/transitionend` correctly

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue#4480]
### Vue.js version
2.1.6

### Reproduction Link
https://jsfiddle.net/JounQin/008rt0qf/embedded/

### Steps to reproduce
open it with iOS 8.4- (http://caniuse.com/#search=animationend)

### What is Expected?
`alert('animationend')`

### What is actually happening?
It does not `alert('animationend')`

Maybe the reason is the correct event name should be `webkitAnimationEnd/webkitTransitionEnd` ?

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting the issue.
While I do not have iOS device to reproduce the problem, I believe Vue has already handled prefix problem in `transition` builtin component. https://github.com/vuejs/vue/blob/4b8eb75c7a5544a1f65ebd679fd89639208d5976/src/platforms/web/runtime/transition-util.js#L18

Because you used `native`, the compiled render function looks like this.

```ts
function render(h) {
    return h('comp', {
       nativeOn: {"animationend":function($event){animationend($event)}}
     })
}
```
You have to manually prefix the event in native modifier, because Vue has no knowledge of what your event is in native binding. So auto prefixing isn't available. Or you can use a `transition` component as mentioned before.

**Comment by yyx990803** [comment]
This is expected - Vue doesn't autoprefix events directly bound with `v-on` for you.

**Comment by JounQin** [comment]
@yyx990803 thx, can you export the autoprefix method to `Vue.util` ? So that we can handle it quickly by ourselves and there's no need to write similar codes again.
