### ISSUE TITLE
typeof of component

### ISSUE THREAD

**Issue by owl1n** [vuejs/vue#4523]
hello everyone.
i'm tired. i have two components. One component for select2, and second - just simple component with template, data and methods. If i'am tryed call console.log(this) via methods in my components, then select2 return "VueComponent...", but second component just return "Object'. What this? How i can fix? In second component i cant use $http, $emit. I havent access to synced props and data...

**Comment by LinusBorg** [comment]
Hi @owl1n 

Even though you are tired, I have to close this.

Your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
