### ISSUE TITLE
vue-cli can not build the prefix of @keyframes

### ISSUE THREAD

**Issue by wikibady** [vuejs/vue#4531]
I'm coding css3 animations with vue-cli ,but when I add 

````
@-webkit-keyframes border{
      to{
          stroke-dashoffset: 0;
      }
  }
  
  @keyframes border{
      to{
          stroke-dashoffset: 0;
      }
  }
````
in the <style></style> of my xxx.vue,and run the project with ```` npm run dev ````,it just remains 
````
@keyframes border{
      to{
          stroke-dashoffset: 0;
      }
  }
````
How do I solve it?

**Comment by sqal** [comment]
Autoprefixer removes  -webkit- perfix because `browsers` option is set to use only last 2 browsers and they don't need this prefix anymore [(source)](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L96) If you need to support older browsers, you should adjust it to your needs. https://github.com/postcss/autoprefixer#browsers

**Comment by fnlctrl** [comment]
^ as above, thanks for the explanation @sqal
