### ISSUE TITLE
Do we have any way of using v-with like a two-way binding?

### ISSUE THREAD

**Issue by thelinuxlich** [vuejs/vue#455]
I got a case where I need to update the $parent binding inside the component that is using it with v-with

**Comment by tancredi** [comment]
@yyx990803 I had hugely appreciated that being reverted when this discussion took place, although I've noticed in has been reverted back again in newer versions.

The thing is, while the v-model directive is still escaping this logic (And not made re-adaptable to custom components), it's impossible now to create custom components that behave like form inputs by manipulating a referenced value in the parent scope.

Let's take the example of someone wanting to create an On / Off switch or a multiple choice with different markdown from a select.

Why is this:

```html
<select v-model='myTwoWayValue'></select>
```

possible using default HTML inputs, while nothing like this:

```html
<my-custom-switch value='myTwoWayValue'></my-custom-switch>
```

is not allowed?

I do understand the reasoning and philosophy behind a one directional data flow - but again, this approach doesn't really allow anyone to adopt different patterns, with the only exception of form inputs which still behave like two-way binding custom components and sort of escape this rule.

I don't mean to be annoying by re-opening this conversation, but since I'm still using Vue.js as I've been for very long time and I'm a great supporter, one of the things I always appreciated of it is its aspect of being unopinionated and versatile.

Vue.js presented from the start as a lightweight VM class that doesn't try to enforce upon you a monolithic architecture - allowing you to be truly modular in however you wish to structure tour application and escaping the framework hell / feature war.

This feels a bit like a step back into trying to impose a philosophy by limiting choice, which is really not what I'd expect from Vue.js.

**Comment by just-nobody** [comment]
Custom components can use `v-model` to work as native inputs. See the docs here: http://vuejs.org/guide/components.html#Form-Input-Components-using-Custom-Events

In essence:
1. Your component accepts a `value` prop
2. When the component's value changes, emit an `input` event

Then, when the parent uses `v-model` on the component, the value updates.

**Comment by tancredi** [comment]
Oh - I didn't spot that - guess I've pulled such an elaborate rant all for nothing - sorry @yyx990803 , this is actually quite a nice implementation (Still really liked the two way data binding syntax that has been present for a few sub versions, though).
