### ISSUE TITLE
Cannot set property 'isRootInsert' of undefined

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue#4589]
### Vue.js version
2.1.7

### Reproduction Link
repo https://github.com/vuetifyjs/docs.git#2.1.7-update

### Steps to reproduce
Install deps, run dev, navigate to any view that uses a top level component with a default slot, layouts for example.

### What is Expected?
The view to load

### What is actually happening?
Error Cannot set property 'isRootInsert' of undefined

### Additional
I've been following https://github.com/vuejs/vue/issues/4584 and pulled down the updated patch and tested it with no difference in results.

**Comment by sqal** [comment]
It really looks like it's the same issue as #4584 Everything works fine in your code to this point:

DocView.vue

```js
<template lang="pug">
  div.view
    section
      section-def
        dt(slot="title" v-html="doc.title")
        dd(slot="desc" v-html="doc.desc")
    section
      section-header Examples
```

but when you add `<slot>` after that it breaks with isRootInsert error.

**Comment by johnleider** [comment]
Correct. It also only breaks because the slotted components have slots of their own. Notice the named slot which contains a component with no slot, it works just fine.

**Comment by yyx990803** [comment]
Since the patch was in the codegen, you will need to use updated `vue-template-compiler` as well. I cloned your repo and tested locally using everything from my local branch and it seems to be working correctly (at least the Layout view), so I think it is indeed caused by the same bug.

If you want to test it yourself, you can clone the Vue repo, build everything and link `vue` and `vue-template-compiler` and `vue-server-renderer` into your project.

**Comment by johnleider** [comment]
Thanks Evan, didn't think about those packages as well. Appreciate all the help.
