### ISSUE TITLE
Returning vue instance from filter function (Vue.js 2)

### ISSUE THREAD

**Issue by ugros** [vuejs/vue#4601]
I'm getting this error:
`TypeError: Converting circular structure to JSON`
while trying to return vue instance from filter function.

Having this ability would be very nice for intl purposes (with dynamic locale switch), realtime relative time rendering, etc.

Not sure if this is intended, not-supported, or just a bug.

Related issue with more details:
http://stackoverflow.com/questions/41380292/return-vue-instance-from-vue-js-filter-vue-js-2

**Comment by LinusBorg** [comment]
Surely not a bug, and  I have no idea how you think that *should* work. filters should return something that returns a string when stringified, so it can be printed to the document.

Making filters optionally render a child component (which I believe you are trying to do) would be a completely new behaviour.

You also do this only because you want to trigger a re-render when you change the locale. Creating components for each localized string seems like a dirty workaround.

I would rather use a mixin that registers a lister with an [event bus](https://vuejs.org/v2/guide/components.html#Non-Parent-Child-Communication) (one of the rare occations that this seems useful), and have the callback  call $forceUpdate() on the component.

**Comment by ugros** [comment]
Thanks for the answear!

> You also do this only because you want to trigger a re-render when you change the locale. Creating components for each localized string seems like a dirty workaround.

The only time it creates new components is when user manually changes the language, which is very rare and I don't think that's a performance problem.

> I would rather use a mixin that registers a lister with an event bus (one of the rare occations that this seems useful), and have the callback call $forceUpdate() on the component.

If I understand it right, it would look like this:
I create a bus. 
Dynamic changes (for example locale changes) trigger an event on a bus.
I import this bus to every component that needs an intl, attach new event listener to this bus with callback that calls `$forceUpdate()`

Well, this solution doesn't seem optimal, both performance-wise and code-wise.

**Comment by LinusBorg** [comment]
My comment about this being a dirty hack is not about performance, it's about clean responsibilities: filters don't render on-the-fly components, they transform stuff into strings. 

About your worries with the bus: 

1. Code-wise: Put the bus into a module, export a mixin from this module which encapsulated all the event work registration etc. 

Then it's a question of `mixins: [i18n-update]` to make a component adapt the behaviour. 

2. Perfomance- wise: if you have a lot of i18n all over your app, you will have to re-render pretty much everything anyway. If the need for i18n is small, then create some component to handle this instead of a filter. 

`<translate>{{message}}</translate>`

**Comment by ugros** [comment]
Alright, what I ended up doing was:

1. create a module that exports bus ( `new Vue()` )
2. import bus into my `<locale-switch>` component. This component has a method `setLanguage(lang)`,
that adjusts my Vue.config.lang and emits 'locale_change' event.
3. import bus into my main <app> component, and register event listener on the bus like this:
```
    created() {
      bus.$on('locale_change', () => {
        this.$forceUpdate();
      });
    }
```

But this still doesn't work as expected, since `$forceUpdate()` only updates the main <app> component and not it's children.

Can I somehow explicitly update <app> component AND it's children? Something like `$forceupdate({ children: true })` ?

Thanks!

**Comment by yyx990803** [comment]
The original usage is not supported, and how to implement i18n should be discussed elsewhere, thanks!
