### ISSUE TITLE
Ability to abort transition between dynamic components using javascript hooks

### ISSUE THREAD

**Issue by tillsanders** [vuejs/vue#4612]
I'm building a cordova app using vue.js and vue-router. In order for it to feel more like a **native** app, I'm trying to support swiping from left to right, to go back to the previous view. 

I have prepared an example here: http://jsfiddle.net/tillsanders/hzkq20yt/10/ 

Just run this fiddle, drag the view *foo* to the right and let go. Behind *foo*, *bar* is already waiting – I'm sure, you have seen this before in many native apps. Take facebook, for example: 

![img](https://cloud.githubusercontent.com/assets/1533846/21570787/955fdcee-cec9-11e6-889e-634d43fa79b8.png)

Thanks to the [transition hooks](https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks), this already works (more or less 😉). But what if the user stops swiping to early or with little to no velocity? You would expect the view/*foo* to slide back into its original position, because you probably intended to cancel the navigation. Unfortunately, there is no way for me to cancel the transition inside the hooks. So all I can do is sliding the view back into its original position, then *bar* appears, and then I immediately navigate back to 'foo' (ll. 65 - 78 in the fiddle). This is of course a really nasty workaround.

What I would need for this to work is something like an `abort()` function in the transition hooks:

```js
onLeave(element, done, abort) {
    // ...
        // If the swipe was short and at a low speed, we cancel it and revert to the original position
        if(remainingDistancePercent < 15 && event.velocityX < 0.1) {
            // Cancel routing and revert to original position
            element.css({
                transition: 'transform 500ms ease-out',
                transform: 'translate3d(0, 0, 0)'
            })
            abort() // ideally, this would wait for above css transitions to finish
        }
    // ...
}
```

*(I thought about whether this is an issue with vue-router or vue.js and I thought the reason vue-router doesn't offer this functionality is because vue.js doesn't. I'm sorry if this is not the case and I should have posted it in the vue-router repository!)*

**Comment by lunelson** [comment]
There is a `v-on:leave-cancelled` hook, but I think you'd need to manage animation purely in JS, and from an Object in a higher scope, like an instance of GSAP e.g. `new Tween()` which would give you options to cancel or reverse animations

**Comment by lunelson** [comment]
Otherwise maybe this has insight in to how you could dig in stop/reverse your CSS transitions before they finish https://css-tricks.com/controlling-css-animations-transitions-javascript/

**Comment by tillsanders** [comment]
Hey @lunelson,
thank you for your reply. Unfortunately, the problem is not how to stop/reverse the animation/transition. That works very well already. The problem is that when the transition (or the reversed transition, I should say) is finished, vue.js will still show the component I've stopped transitioning to. 
To see what I mean, just play the fiddle: http://jsfiddle.net/tillsanders/hzkq20yt/10/
Drag `foo` just a little to the right. Then let go. The component slides back into its original position. But then vue.js replaces it with `bar`. I can replace it in turn with `foo`, but for a split second, you will see `bar`none the less.

**Comment by lunelson** [comment]
@tillsanders maybe I'm still underestimating this problem, but it seems to me, the reason you are getting `bar` appearing is because you are calling `done()` even though you aborted the transition... what if you just don't call the `done` function? 

Also, there are the `leaveCancelled` and `enterCancelled` hooks https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

**Comment by tillsanders** [comment]
@lunelson Unfortunately, not calling `done()` doesn't work. You can see for yourself here: http://jsfiddle.net/tillsanders/hzkq20yt/11/ The result is that bar doesn't disappear and the router just keeps waiting for the transition to finish.

And for the hooks: I don't understand, how I would make use of them. I can't call them to cancel the transition. They just allow me to *react* to cancelled transitions. My problem is how to cancel transitions manually in the first place.

**Comment by nkovacs** [comment]
The problem is that there's nothing left to abort by that point. When you call `$router.push`, the router transition is completed immediately, the router-view re-renders itself with the new component, and the transition hooks are only for animating the old child out and the new one in. That's handled by the transition component, from the router-view's point of view,  the change already happened.

You can see that the url changes immediately after you start dragging, and the old component will be removed as soon as you call done (that's why you had to use keep-alive as a workaround to get the old instance back when you go back).

**Comment by lunelson** [comment]
Aha, so does this mean that cancelling the transition in the given example would require triggering [`router.back()`](https://router.vuejs.org/en/api/router-instance.html) as well?

**Comment by nkovacs** [comment]
That won't actually cancel the transition. When you start dragging, foo is only kept in the dom because its leave animation hasn't completed yet. But you have to call done eventually to complete it, and then foo is removed from the dom. Then if you call router.back(), bar is removed and foo is reinserted. Because of the keep-alive you get the old foo back, not a new one.

What I tried to do a while ago was a page transition similar to android's swipeable tab views, but I couldn't do it with vue-router. It would require preloading the other two pages (since you can swipe left and right), and then only confirming the navigation when you let go (and when the animation is finished, removing the two other pages from the dom).

**Comment by lunelson** [comment]
I wonder if it's possible to implement this as a component that uses the router's API, i.e. triggering `router.push`, reacting to `router.back` etc., but *in place of* the `<router-view>` component, allowing a different handling of the loading and unloading of views?

**Comment by nkovacs** [comment]
I don't think so, you'd need an API in the router to preload a component but not replace the currently loaded component with it.

**Comment by lunelson** [comment]
I guess I'm being more simplistic, I'm not thinking about full routes that load pages; but imagining a component that contains all the pieces and that if you're using History (non-hash) routes you could still push and pop hashes to the router, and coordinate the state of your component to that. Dunno, it needs more thought 🤔

**Comment by newbie78** [comment]
hi all
as I understand it the problem is that sometimes done() fires before this.$router.back(). I did it 3-5 times to repeat it on original fiddle. if done() to put above this.$router.back() you can see the problem on every run (http://jsfiddle.net/hzkq20yt/16/). if you set the delay for done() then the problem disappears (http://jsfiddle.net/hzkq20yt/14/) but that looks like a dirty hack.

**Comment by yyx990803** [comment]
Sorry for letting this sit and this reply is probably too late - but ultimately I think this type of app-like navigation really begs for a dedicated card-stack based, touch-aware navigation solution. `vue-router` is still largely designed around the "nested boxes" desktop navigation model. The built-in transition system is really meant for fire-and-forget state toggle animations, just adding `abort` wouldn't be an answer to the root problem.
