### ISSUE TITLE
setTimeout within component create, potentially being overwritten

### ISSUE THREAD

**Issue by nonadmin** [vuejs/vue#4618]
### Vue.js version
2.1.8
### Vuex version
2.1.1

### Reproduction Link
https://jsfiddle.net/dL2sr6L3/1/

### Steps to reproduce
Create several new alerts using the button

### What is Expected?
The alerts should each be removed after 3 seconds

### What is actually happening?
Only every two alerts is removed

I'm not sure if this is a vuex or vuejs issue.  Basically I have a global alerts system using vuex for storage.  I've tried a few different ways of automatically clearing the alerts.  The demo creates a setTimeout when the alert component is created.  setTimeout will $emit after 3 seconds, emit is picked up by the parent which issues the delete to vuex.

**Comment by yyx990803** [comment]
This is actually because the `v-for` component dont' have explicit keys - so when the first alert is removed, the last component instance is removed instead (thus its timer becomes "eaten").

Fixed: https://jsfiddle.net/dL2sr6L3/3/

Maybe we should give `key` warnings on `v-for` with components in the future.

**Comment by nonadmin** [comment]
Oh wow, what a simple fix.  Thank you!
