### ISSUE TITLE
".vue" file:if a string variable include `</script>`, it will alert a `Module build failed: SyntaxError`

### ISSUE THREAD

**Issue by lanbomo** [vuejs/vue#4625]
I use vue-cli to establish my project with webpack template.
But in the `.vue` file, when a js variable include `</script>`, it will alert a error`Module build failed: SyntaxError: E:/projects/src/components/Highlighter.vue: Unterminated string constant`
The code in the `.vue` file like this:
```js
export default {
  name: 'hello',
  data () {
    return {
      html: `
      <!DOCTYPE html>
        <html lang="zh-cn">
        <head>
            <meta charset="utf-8">
            <meta name=viewport content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
            <title>highlighter-html</title>
        </head>
        <body>
            <div id="app"></div>
            <!-- built files will be auto injected -->
        <script type="text/javascript" src="/app.js"></script></body>
        </html>
        `
    }
  }
}
```
Finally, I found it happed because it include `</script>`. And I try to write a variable include it, like this:
```js
let s = '</script>'
export default {
  name: 'hello',
  data () {
    return {
      
    }
  }
}
```
It alert again.
Is this a bug?
I use the Vue at version 2.1.0

Thanks

**Comment by cheneyliu** [comment]
I remember the `.vue` file, in html template can not include `<script>` tags, you should look vue-cli created simple demo!

**Comment by yyx990803** [comment]
This is because `*.vue` files are parsed using HTML parsing rules. When parsing HTML, the parser encounters `</script>` and it's considered ending the current script block. In fact if you do the same in an HTML file and let the browser parse it, you also get a syntax error.

You can escape the closing script as `'<\/script>'` to get around this. We will add a note to the Vue file documentation.
