### ISSUE TITLE
Timing gap between transitions

### ISSUE THREAD

**Issue by softomatix** [vuejs/vue#4641]
The #4510 is not resolved. Gap still occurs in the repro.

**Comment by posva** [comment]
It was solved in 2.1.7 but reverted in 2.1.8 because it introduced a breaking change in transitions: As you can see, your example works with 2.1.7: https://jsfiddle.net/posva/m1e7xpov/
You just need to use a different classname: https://jsfiddle.net/posva/8p4nnfsg/ (2.1.8)

You'll find more details in the release notes https://github.com/vuejs/vue/releases/tag/v2.1.8

**Comment by softomatix** [comment]
@posva, Got it! Thank you very much for the explanation. Unfortunately, nothing was mentioned about it in the #4510. I believe the documentation will be updated soon as well. Anyway, thanks for fixing this! 👍
