### ISSUE TITLE
Uncaught TypeError: arr[i] is not a function

### ISSUE THREAD

**Issue by rorc** [vuejs/vue#4647]
https://jsfiddle.net/rorc/jdauyt94/1/

1. Choose Approved
2. Choose Reason 3
3. Open console and try to choose steps

**Comment by rorc** [comment]
@posva This error in core of vue. I described well the problem...

**Comment by rorc** [comment]
@posva Just try to going by steps 1, 2, 3.

**Comment by posva** [comment]
you're not describing a problem, you're just enumerating the steps to get an error. There may be a bug, but please take the time and effort to report it properly.

**Comment by rorc** [comment]
As i understand, i must write words is that it is written in the code?

**Comment by rorc** [comment]
After changing select field (`v-model`) programmatically in function (`this.order.status_id = 3`) and after trying chose another select (which shows only if parent div in dom), we catch the error in console....

**Comment by rorc** [comment]
Why u close this issue so giddily and fast without try to see and understand? 😃
This can be really bug...

**Comment by posva** [comment]
> I'm closing this because you're not providing enough information and therefore your post looks more like a StackOverflow question than an issue report.
However, if you find out there's actually a bug, open a new issue with a minimal reproduction 🙂 

I think you should read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) 

After some debugging I found the real issue: the event `@change` is being triggered after the element is removed (due to the englobbing `v-if`). I have to go. I'll open another issue with a shorter and simpler repro when coming back

**Comment by rorc** [comment]
@posva Ok, thanks, i will waiting 😄
