### ISSUE TITLE
Maybe slot is not a good idea, It's not so flexible especially with the

### ISSUE THREAD

**Issue by ash0080** [vuejs/vue#4711]

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. **The issue list only accepts bug reports and feature requests.**

Also note it's pointless to raise discussions along the lines of "maybe feature X is not a good idea" - Vue is relied upon by tens of thousands of users and an existing feature cannot simply be changed or removed because "it may not be a good idea".
