### ISSUE TITLE
Call event from child elements of contenteditable div

### ISSUE THREAD

**Issue by subha-py** [vuejs/vue#4718]
Hi,
This is my code .
How can I call keypress,keyup and keydown events of child elements of a contenteditable div in vuejs?

[stackoverflow_contenteditable (copy).txt](https://github.com/vuejs/vue/files/707683/stackoverflow_contenteditable.copy.txt)

This is the stack overflow link -[here]( http://stackoverflow.com/questions/41636596/how-to-call-keypress-event-in-span-tags-inside-contenteditable-true-div-in-vuejs)

**Comment by LinusBorg** [comment]
Hello @subha-py 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
