### ISSUE TITLE
Disabling warnings about inline value attributes for v-model

### ISSUE THREAD

**Issue by HenriMorlaye** [vuejs/vue#4733]
Hi,

Forms generated by Phoenix HTML helpers have an inline value (like on Rails). I use Vue.js on those forms by creating the View Model data on the fly by introspecting the form inputs and values. I works fine but these warnings are no longer necessary in my case. I wonder if there could be a way to disable them?

**Comment by danieldiekmeier** [comment]
First off: You can disable all logs and warnings by setting `Vue.config.silent = true`. See here: https://vuejs.org/v2/api/#silent – But I understand that this is probably not what you want, because it will hide ALL warnings.

**However**, I would also welcome a way to exclusively turn off the warnings about the `value` attribute.

My use case is that I generate my HTML code with Python/Flask/WTForms. I only use Vue for some optional nice things, but would like to keep JavaScript as optional as possible. By using the `value` attribute, I can provide default values for *everyone*, not only people with JavaScript activated. I still provide an Object (with the same values) to Vue, so I don't need the warning.

**Comment by phanan** [comment]
This makes sense to me. IMO if the user explicitly uses `v-model` with provided `data` option, he should know by fact that the input should take its value from there instead of inline.
