### ISSUE TITLE
2.0 feedback

### ISSUE THREAD

**Issue by amostajo** [vuejs/vue#4776]
I have been using Vue prior version 1.0, having released various components for the community, such as a TreeView and Form components.

I have been a fan and only had not less but high praise of Vue's simplicity and power. It was versatile, its two way binding between components was such a strong feature for complex applications, that for me had not competition.

I have been struggling to convert many of my clients' apps and my public repos into Vue 2.0 because of all the restrictions and limitations that have been applied to the project. I have to say that I am very disappointed of what Vue has become in terms of development (the process of debugging is buggy). Two way binding is now restricted due to mutation warning nonsense, event system should have been improved not replaced completely.

I feel that Vue 1.0 was going in the right direction, following the same vision that started the project, simplicity yet versatile, perfect alternative for the likes of AngularJS, ReactJS and such, but Vue 2.0 doesn't feel like that, seems like its going into a different direction, I think it is try to mimic the others instead of staying something different, feels like the direction was changed by all the contributors to make it work more like Angular, react and such and was de-railed from the path it was going to.

I hope Evan You can rework this for version 3 and put Vue back to the path and vision from older versions, where simplicity was key. I am seriously considering sticking with Vue 1.0 for when developing complex applications.

Just my humble opinion, best regards to all.

**Comment by yyx990803** [comment]
Thanks for the feedback. I'm sorry about your disappointment, but the design process for 2.0 was pretty open during the alpha/beta phases and the community had plenty of feedback (and many of them affected the outcome) before the final was released. It's simply a bit late for such feedback at this point. The two-way binding change has been discussed many times during the 2.0 design process and I don't really feel like repeating the same thing over and over again. Short story is that we've found it to be less maintainable and less flexible than the "props down, events up" pattern recommended in 2.0.

Also, it's not particularly constructive to go from "I don't like the removal of a particular feature" to "the project has lost its way". While I respect your personal impression, I tend to believe otherwise based on the combined feedback from the community as a whole. Overall I believe 2.0 is a clear improvement over 1.0 and we don't plan to bring breaking changes to "fix it" in the foreseeable future.

P.S. please note the contribution guidelines explicitly stated that issues are not fit for general feedback like this. It's better to post this to the forums.

**Comment by amostajo** [comment]
Thank you for reply Evan!

**Comment by smolinari** [comment]
As an example of success with Vue 2.0, the dev of [Quasar framework](http://quasar-framework.org/) did a refactor to get his framework working with Vue 2.0. It only took him 3 weeks to refactor all of Quasar using the [well written migration guide](https://vuejs.org/v2/guide/migration.html). He said there were some rough patches to get through, but he also said, "not upgrading to Vue 2 is like keeping a toy as opposed to a spaceship". So, I can safely say, your efforts to get going with Vue 2.0 will be well worth it.

Scott
