### ISSUE TITLE
Custom plugin is not imported into the production mode

### ISSUE THREAD

**Issue by leonardovilarinho** [vuejs/vue#4777]
Hello, I have two plugins that I made in the project, registered it as a package of npm and installed as a dependency, but when I run the ` npm run build` pops up the error:

    Unexpected token (Acl)

ACL is one of those plugins. I copied the plugins to a folder within the src and I imported the plugin that folder then it worked, but how do I import from npm and work?

The problem is definitely in the plugin, follow the link of the two (the file are in the src folder):

[MultiLanguage plugin](https://github.com/leonardovilarinho/vue-multilanguage)

[Acl plugin](https://github.com/leonardovilarinho/vue-acl)

Thank

**Comment by LinusBorg** [comment]
Hello @leonardovilarinho 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

---

Hint: it has probably to do with the fact that babel-loader doesn't convert files from `node_modules` to ES5, and your plugins use in ES6 classes. That's why it works when the files are in `/src`
