### ISSUE TITLE
Values for unrelated inputs reseted

### ISSUE THREAD

**Issue by sleewoo** [vuejs/vue#4790]
### Vue.js version
2.1.10

### Reproduction Link

https://jsfiddle.net/oranvbt7/

### Steps to reproduce
Type something into `x` field then click checkbox

### What is Expected?
`x` field to keep it's value 

### What is actually happening?
`x` field value is reseted

**Comment by HerringtonDarkholme** [comment]
Every rendering will **faithfully** patch real dom against the virtual dom render function returns. 

In this case, the returning virtual dom will be something like `<input name="x" value="">`, so Vue correctly resets the input value. Because your template `<input :value="x">` is single way, changing content in input will not update data in model. You might need two way binding `v-model` to update vm.

```vue
x: <input type="text" name="x" v-model="x">
```

fixed: https://jsfiddle.net/oranvbt7/1/

**Comment by FFX01** [comment]
@HerringtonDarkholme 

Came here to say exactly that. The `x` variable in the `data` method is not being changed when the input value is changed. Therefore, `x` is never reset. `x` was never set to begin with. You need to use the `v-model` directive to bind input values to your data model.

**Comment by sleewoo** [comment]
makes sense, thanks
