### ISSUE TITLE
Minor bug with Boolean props casting: undefined => false

### ISSUE THREAD

**Issue by frankdiox** [vuejs/vue#4792]
### Vue.js version
2.1.10

### Reproduction Link
https://jsfiddle.net/nymhjosc/

### Steps to reproduce
Simply omit a Boolean prop and the value will be casted to `false`. 

### What is Expected?
I'd expect to have an `undefined` property just to know that the user didn't provide it (since it is not a required prop). Basically, I would expect both `myProp` and `missingProp` in the previous example to be the same.

### What is actually happening?
When the prop is not provided its content is casted to `false`. Also, some other values like `''` are casted to `true` (somewhat related to #4538) but I guess this is intended. I'm using `default: undefined` for now.

**Comment by posva** [comment]
Since you give the prop a Boolean type, it's normal to have a `false` value for the missing prop. What bothers me more is the `undefined` value passed to a `Boolean` prop not being cast to a boolean or getting an error. The same happens with `null`

**Comment by znck** [comment]
@posva Sometimes `undefined` is required. 

I use it for modals so parent can control the state of modal with prop a value and if prop is undefined then parent can trigger by `open` event.

**Comment by posva** [comment]
@znck Yeah, I cannot remind where I read something similar, but being able to explicitly pass `undefined` to any type of prop is probably a feature

**Comment by znck** [comment]
>  being able to explicitly pass `undefined` to any type of prop is probably a feature
Passing `undefined` works, the bug is when a prop is not provided by user component then naturally it is expected to be `undefined`.

**Comment by posva** [comment]
No, because we're asking for a `Boolean` type, so a missing prop is false. To keep `undefined` when the prop is missing we can just use a `null` type

**Comment by simplesmiler** [comment]
@znck yeah, but what is the purpose of "default" then, when would it be called?

**Comment by frankdiox** [comment]
@posva Honestly, the same way a missing `String` prop does not become `''`, I would expect a missing `Boolean` to be `undefined` and not `false`. But I guess it's a matter of opinion.

And the other thing I pointed out
> some other values like `''` are casted to true

is also kind of weird to me. In JavaScript an empty string is a falsy value.

**Comment by yyx990803** [comment]
The boolean casting follows the same rule of a boolean attribute: presence of any value are casted to true, absence means false.

Personally I think it's a bad idea to differentiate a "3rd state" for boolean props.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:48809 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWmiR-0032bT-PR
	for greg@biomassiv.es; Thu, 26 Jan 2017 10:16:03 -0600
Date: Thu, 26 Jan 2017 03:25:59 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485429959;
	bh=Vx+eSiSjoCiAui9dL/+PJYQaCHM10R3xIx5BGrGNj+I=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Pj6teuR0HRArPNreEWzfTYgPQPpzakXCoKBR3+T131ps3CkPdI3SMJwljgOqc1KjH
	 fOs0EuKx7cJ0RKeG+LzqbkWHsDv3ydhVIpVX1fBu28JmZ0pg1s9NeqrIhZ7e9om3MI
	 mNFb20sOM/XH1Fa9Hl/ikrZXM7sr925NM3/6o9wU=

**Comment by realcarbonneau** [comment]
Although I highly respect all of your opinions and knowledge, I would like to present a different view.

As a developer, I may want to know if a Boolean prop was defined or not.  
Here are two examples: 
1) As a component developer for external use, I may want to build some logic to determine if the property was defined or not for various internal checks and robustness. And, it is not realistic to impose the use of :my-bool="undefined", especially when trying to make a component robust and flexible.  Fortunately, there is a workaround that does not impose external changes, that is to explicity set the default to undefined: `boolProp: {type: Boolean, default: undefined}`

2) A multi-value prop that includes a boolean value may be desired.  For example `happyIcon: [Boolean, String]`.  This simplifies the usage of the component (which assumes happy by default) with the following example scenarios for the prop:
a) false: no icon displayed
b) undefined, defined or true: display the default icon
c) string: custom icon name

However, since vue forces undefined to false, I cannot manage case b since I cannot observe the undefined state and would be forced to add a second prop, thus requiring two props (Boolean and String) to do something that could be done with one.  Additionally, I cannot just ask the user to pass a string "false" or "true" in the string since this could be an icon name.

Since undefined is fasly, there is no negative impact in keeping it, however, there is a loss of functionality by removing it.

As an additional irritant, if I define a Boolean and String prop with undefined as a default and the prop is defined, the component receive an empty string instead of the expected true value.  (Maybe I should submit this as a seperate issue?)
```
    bsu: { 
      type: [Boolean, String], 
      default: undefined
    },
```

See the following jsfiddle for the examples: https://jsfiddle.net/realcarbonneau/yrm6p5dp/34/

**Comment by vincerubinetti** [comment]
The main use case I can see for having a third state for a boolean is HTML attributes:

`<div data-blah="true">`
`<div data-blah="false">`
`<div>`

**Comment by bryanmylee** [comment]
I'm just getting started with Vue and this behaviour was definitely a surprise to me.

I'm using the composition API with the `defineProps<{ open?: boolean | undefined }>()` macro, and I expected `open` to be `undefined` if omitted.

It's weird that `props.open` is typed as `boolean` instead of `boolean | undefined`, but I guess I'll just have to get used to that footgun.

**Comment by mrweiner** [comment]
Chiming in years later to say that this confounded me as well. Since we are using https://github.com/gcanti/fp-ts, I opted to make the prop an Option type, which essentially provides the desired functionality. 
```
const props = defineProps({
  forceIsVisible: {
    type: Object as () => O.Option<boolean>,
    required: false,
    default: O.none,
  },
});
```

Doubt it's worth installing this package just for this but it does the trick.

**Comment by klapAtGitHub** [comment]
I'd vote for undefined as default value for 2 reasons:)
  - other types (number, string and object) default to undefined. So the boolean should not be an exception.
  - if a prop can be marked as optional (not required), it sounds for me like a nullable prop. And I think it should be possible to know if it has been omitted, instead of changing it to any valid value. This could disguise errors, I think. But I understand the other arguments as well.

However, the workaround from frandiox works well (explicitely specifying an undefined or null as default value).
```
aBooleanProp: {
    type: Boolean,
    default: null
}
```
Is that the recommended and save way to handle optional boolean props?
Or should I use a wrapper object for optional types as mrwiner suggested?

**Comment by matthew-dean** [comment]
This is still a bizarre part of Vue's API, and violates the Law of Least Surprise.

Take this statement by @yyx990803:

> The boolean casting follows the same rule of a boolean attribute: presence of any value are casted to true, absence means false.

> Personally I think it's a bad idea to differentiate a "3rd state" for boolean props.

String attributes in HTML are the same way. Open up Chrome, inspect an element, and select `Properties`. You will see no `undefined` values! If it's a string, it will default to `""`. If it's a number, it will default to `0` or `-1` (depending on type). If it's a boolean, it's `true` or `false`.

It's absolutely counter-intuitive to treat booleans differently. Either _all_ Vue properties should have default values, by default, or none should.

More importantly, though, from a component perspective, is this statement by @realcarbonneau:

> As a developer, I may want to know if a Boolean prop was defined or not

Because these are developer-to-developer JavaScript and TypeScript interfaces, while it may seem a "bad idea to differentiate a 3rd state for boolean props", this is a core staple of the JavaScript / TypeScript language itself.

In fact, this gets even more off-kilter when TypeScript support was increased for Vue, and you have interfaces like this:
```ts
interface Props {
  name?: string
  isCool?: boolean
}
```
In TypeScript, both of these properties are defined as optional, which _means automatically_ that their respective values are `string | undefined` and `boolean | undefined`. Despite the syntax being exactly the same, Vue's TypeScript implementation handles the interface inconsistently, defining `name` as `string | undefined` (instead of `string`) and defines `isCool` as `boolean`.

So, there's little rational reason why booleans not only behave inconsistently from an HTML perspective, and not only behave inconsistently from a Vue perspective, but also behave inconsistently from a JavaScript and TypeScript perspective. It really is a complete oddity in this legacy behavior.

**Comment by IcyFoxe** [comment]
I just had this same issue today.

If I define a prop as `someProp?: string` and it will be undefined, when no attribute is passed to the prop.
So why doesn't `someProp?: boolean` behave the same way??

Worst part is that TypeScript understands it exactly as that - boolean or undefined, but in reality it's always boolean.

**Comment by Waujito** [comment]
My example of undefined usage in boolean props: Imagine a component that have local state and I want to add the ability for a top-level component to use its own state management. I solve this problem by injecting the top-level state prop to the props of the component and converting this prop toRef(). So via `computed()` I can easily manage the state with local and external ref().

```js
const props = defineProps<{refState?: string}>();

const propsRefs = toRefs(props);

// Escape Ref<string|undefined> | undefined
const refState: ComputedRef<string | undefined> = computed(
  () => propsRefs.refState?.value
);
const localState = ref(false);

// 
const dropdownShown: WritableComputedRef<string> = computed({
  get: () => refState.value ?? localState.value,
  set: (b) =>
    (refState.value === undefined && (localState.value = b)) || emit("stateChanged", b),
});
```

The example above works completly fine, but until the state is not a boolean type. Vue enforces `refState` to `false`, so I need to use something like `refState?: {state: boolean}` or `refState?: "true"|"false"` which is a little complicated.

So converting from undefined to false in boolean props is a really weird decision. Waiting for fix.

**Comment by matthew-dean** [comment]
> If I define a prop as someProp?: string and it will be undefined, when no attribute is passed to the prop,
why doesn't someProp?: boolean behave the same way??

It's a part of the Vue API that makes zero rational sense. In JavaScript (and TypeScript), Booleans are not a different kind of primitive from other primitives.

**Comment by zernonia** [comment]
Yup this issue is quite prominent when building `radix-vue`, where we expose the Props & Emits type for dev to build wrapper component around it. It makes it super hard to build wrapper components, as I cant expect the dev to always define the props with `withDefaults` and manually set those boolean props to `undefined`.

Also, by casting the `boolean` to `false` really surprised me as I'm expecting the type to be `undefined` (explained by above comment nicely). I gotta agree with @matthew-dean  in terms of violating  `Law of Least Surprise`.

**Comment by dondevi** [comment]
Here is a hack to solve the problem:

```ts
app.mixin({
  beforeCreate() {
    /**
     * Fix default value to `undefined` of Boolean props when inheriting
     */
    Object.keys(this.$props).forEach((key) => {
      const prop = this.$props[key];
      const type = this.$.type.props[key];
      if (type && prop === false && !('default' in type)) {
        /**
         * @hack `props` is readonly, use `props.__v_raw` to get a mutable `Proxy`
         */
        this.$props.__v_raw[key] = undefined;
      }
    });
  },
});
```

**Comment by sadeghbarati** [comment]
Make **Runtime Props Validation** Optional Please 🙏 

Instead show "Vite Error Overlay" on screen 

With Casting Props in runtime we would never have **Complex Types** or **Entire Props Type Object** support for `defineProps/emits` macro

**Comment by dondevi** [comment]
> @dondevi Thank you SO MUCH for fixing this!
> 
> EDIT: Your code comment says "Fix default value to `undefined` of Boolean props when inheriting"... does this not set boolean props to `undefined` in all cases?

Because of the `beforeCreate()` hook, for all component instances, as long as a prop value is `false`, and it's type object missing `default` field, it means that value is not from `withDefaults()`, so we  could reset it to `undefined`.

**Comment by dondevi** [comment]
> @dondevi Wait a minute... I think your logic is flawed....
> 
> If I have a component like this:
> 
> ```
> <script setup lang="ts">
> defineProps<{
>   bool?: boolean
> }>()
> </script>
> ```
> 
> ... then it has no `default` value set. And if I then explicitly set `bool` to `false`, then will your code not set it to `undefined`? 🤔 You're assuming that any `false` value is not explicit, which may not be the case. I don't think this can solve the issue.

@matthew-dean Thanks for pointing it out, it won't cover all scenarios as it's a hack to attract good ideas.

**Comment by dondevi** [comment]
@matthew-dean A better solution:

```ts
/**
 * @hack Prevent vue's behavior of casting boolean default value to false
 * @since vue 3.3+
 * 
 * @see {@link vuejs/core/packages/runtime-core/src/componentProps.ts:484#resolvePropValue} - boolean casting
 */
app.mixin({
  beforeCreate(this: ComponentPublicInstance) {
    const { props, type, vnode } = this.$;
    const types = Object.entries(type.props || {}) as Array<[string, any]>;

    for (const [key, prop] of types) {
      const raw = vnode.props?.[key];
      const value = props[key];
      if (
        ([] as unknown[]).concat(prop.type).includes(Boolean) // Has boolean type
        && prop.required !== true && !('default' in prop) // Optional without default
        && raw === undefined && value === false // Casted to false by vue
      ) {
        /**
         * Reset boolean props value to undefined
         * @hack `props` is readonly, use `props.__v_raw` to get a mutable `Proxy`
         */
        (props as any).__v_raw[key] = undefined;
      }
    }
  },
});
```

**Comment by tmdkamins** [comment]
This definitely violates principle of least surprise when all (?) other types default to undefined when not specified. But changing this behavior would be a breaking change and is not going to happen in Vue 3. See comment from core dev: https://github.com/vuejs/core/issues/9882#issuecomment-1864689351

A couple workarounds:
1. Use `Boolean` (big B) instead of `boolean`.
2. Provide a default value (`withDefaults`) of `undefined`.

Either of these seem to elicit the expected behavior.

**Comment by dondevi** [comment]
I have to do it for this kind of scene:
> Though props in QInput have default value, but they can't extend by ts

```vue
<template>
  <q-input
    v-bind="props"
    ...
  />
</template>

<script lang="ts" setup>
import { QInput, QInputProps } from 'quasar';

interface Props extends QInputProps {
  ...
}

const props = defineProps<Props>();
</script>
```

**Comment by reinaldomendes** [comment]
Why vue core function resolvePropValue doesn't check opt.required instead casting every boolean prop?

```diff
diff --git a/dist/vue.esm-browser.js b/dist/vue.esm-browser.js
index 41e2d441bc75a4d11664c3fb7212eb0355eedb8c..2b3d1567b3415976293603ee73fa57063d54a17f 100644
--- a/dist/vue.esm-browser.js
+++ b/dist/vue.esm-browser.js
@@ -5754,7 +5754,7 @@ function resolvePropValue(options, props, key, value, instance, isAbsent) {
       }
     }
     if (opt[0 /* shouldCast */]) {
-      if (isAbsent && !hasDefault) {
+      if (isAbsent && !hasDefault && opt.required) {
         value = false;
       } else if (opt[1 /* shouldCastTrue */] && (value === "" || value === hyphenate(key))) {
         value = true;
` ``

**Comment by guaijie** [comment]
> The boolean casting follows the same rule of a boolean attribute: presence of any value are casted to true, absence means false.
> 
> Personally I think it's a bad idea to differentiate a "3rd state" for boolean props.

你都理解错了好吧，官方文档上说的是 attr 是 boolean 的话，如果没传默认就是 false。包含 boolean 类型和只是 boolean 类型是两种完全不同的表述好吧

```ts
// 我指定的类型里包含 boolean 类型，又不只是 boolean 类型，这两者表述是有明显差别的好吧，你自己错误的理解了官方文档，却还不听取广大开发者的建议。

type Prop = {
  prop1?: boolean | string
  prop2: boolean // 这个不传默认为 false 才是合理的好吧
}
```

**Comment by vincerubinetti** [comment]
> Personally I think it's a bad idea to differentiate a "3rd state" for boolean props.

Example: Flag that can be true or false, or omitted to use an internal, derived default, like the `<AppLink>` component below.

```vue
<script setup lang="ts">
type Props = {
  /** internal route or external url to link to */
  to: string;
  /** force new tab or not */
  newTab?: boolean;
};

//                   👇 shouldn't be needed
const { to, newTab = undefined } = defineProps<Props>();

defineSlots<Slots>();

/** is link to internal route or external url */
const external = computed(() =>
  ["https:", "http:", "mailto:"].some((prefix) => to.startsWith(prefix)),
);

const component = computed(() =>
  to ? (external.value ? "a" : "router-link") : "span",
);

const toAttr = computed(() => (external.value ? "href" : "to"));

const target = computed(() => ((newTab ?? external.value) ? "_blank" : ""));
</script>
```

The example above uses the new Vue 3.5 reactive props restructure capability. I got really thrown off that, without the `= undefined` default, `newTab` was defaulting to false. Then I re-stumbled across this issue and realized the new functionality is probably just being kept consistent with the old `withDefaults` behavior. And at least the TypeScript was correctly being shown as being forced to `boolean`.

But all this _really_ goes against expectations. And JavaScript convention, I'd argue. The `=` default is [only supposed to be set when `undefined` is passed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), not `null` or `false` or anything else falsey.

It also goes against the typing that I explicitly established. `newTab: boolean | undefined` magically became something else I didn't tell it to do.

But perhaps most importantly, `boolean` is the only thing this is applied to??? e.g `id?: string;` stays `string | undefined`, `value?: number` stays `number | undefined`.

@yyx990803 I greatly respect your work and design decisions, but in this specific case it was the wrong call. _Please_ consider making a breaking change in Vue 4 to fix this.

**Comment by reinaldomendes** [comment]
> Personally I think it's a bad idea to differentiate a "3rd state" for boolean props.

The main problem is not having a "3rd state" the problem is having  `opposite` state of defined as default.

```vue 
<script setup>
type Props = {
  /** internal route or external url to link to */
  to: string;
  /** force new tab or not */
  isActive?: boolean;
};
const props = withDefaults(defineProps<Props>({
   isActive: true
}))

console.log (props.isActive)
/*
*  The props.isActive becames 'false' when attribute 'is-active' is absent
*
* This is the oposite of expected behavior `withDefaults` explicity sets defaults to `true` 
*/



</script>

**Comment by reinaldomendes** [comment]
> The boolean casting follows the same rule of a boolean attribute: presence of any value are casted to true, absence means false.
> 
> Personally I think it's a bad idea to differentiate a "3rd state" for boolean props.

> Personally I think it's a bad idea to differentiate a "3rd state" for boolean props.

The problem is not only about having a "3rd state", but the issue is that the current behavior cause the  `opposite` value of defined from the default  when the default value is `true`.

As mentioned by [vincerubinetti](https://github.com/vincerubinetti), why boolean is the only thing this is applied too??

```vue 
<script setup>
type Props = {
  /** internal route or external url to link to */
  to: string;
  /**is Active or not default is true*/
  isActive?: boolean;
};
const props = withDefaults(defineProps<Props>({
   isActive: true // explicity set default as true
}))

console.log (props.isActive) //false ? Why?
/*
*  The props.isActive becames 'false' when attribute 'is-active' is absent
*
* This is the oposite of expected behavior `withDefaults` explicity sets defaults to `true` 
*/



</script>

**Comment by vad1ym** [comment]
Dirty but flexible hack I’m using, in case someone needs it

```ts
const props = defineProps<{
  flag?: boolean
  hackedFlag?: ReturnType<() => boolean>
}>()

console.log(props.flag) // false
console.log(props.hackedFlag) // undefined
```

**Comment by mshamaseen** [comment]
I was trying to make a wrapper to a third-party component, but the issue of auto-casting to boolean was brutal.

```
<template>
    <InputNumber v-model="model" v-bind="props"/>
    <field-error v-if="name" :name="name"/>
</template>

<script setup lang="ts">
import InputNumber, {type InputNumberProps} from 'primevue/inputnumber';
import FieldError from "@components/FieldError.vue";
import {computed, useAttrs} from "vue";

const props = defineProps<InputNumberProps>()

let model = defineModel('modelValue', {type: Number})

</script>
```

Here, I'll never be able to get the default values from InputNumber, because all undefined boolean-type props will be casted to false and explicitly passed to the component as false instead of undefined.

Forcing the dev to give a default value to all undefined values to undefined again is unreasonable; there should be a way to turn-off this behaviour by using an option.

temp workaround:
```
const unprocessedAttrs = getCurrentInstance()?.vnode.props ?? {}
```
