### ISSUE TITLE
view not change when dispatch action, it only work when have 2 dispatch

### ISSUE THREAD

**Issue by lyquocnam** [vuejs/vue#4799]
hi author, i tested many times with this.
this happend when i dispatch action in methods and inside firebase method.

Please see my demo video about this issue, i dont know how to explain more exactly.
[VIDEO HERE](https://youtu.be/QR9YwfHQReE)
my projecy [HERE](https://github.com/lyquocnam/vue-firebase)

**Comment by LinusBorg** [comment]
Hello @lyquocnam 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
