### ISSUE TITLE
Problem with component rendering

### ISSUE THREAD

**Issue by TheFbler** [vuejs/vue#4820]
### Vue.js version
2.1

### What's happening
I load an object from the server with axios in the vuex store and an computed property in the vue file. Now when i want to open that vue component i get the following stack trace in the chrome console:

[Vue warn]: Error when rendering component <TableDetails> at C:\dev\Project\client\src\app\tables\Table.Details.vue: 
TypeError: Cannot read property 'name' of null
    at Proxy.render (eval at 341 (0.f09f510….hot-update.js:13), <anonymous>:43:42)
    at VueComponent.Vue._render (eval at <anonymous> (app.js:612), <anonymous>:2216:22)
    at VueComponent.updateComponent (eval at <anonymous> (app.js:612), <anonymous>:2609:21)
    at Watcher.get (eval at <anonymous> (app.js:612), <anonymous>:2934:27)
    at Watcher.run (eval at <anonymous> (app.js:612), <anonymous>:3003:22)
    at flushSchedulerQueue (eval at <anonymous> (app.js:612), <anonymous>:2807:13)
    at Array.eval (eval at <anonymous> (app.js:612), <anonymous>:473:20)
    at nextTickHandler (eval at <anonymous> (app.js:612), <anonymous>:422:16)

caused by this part of code:

<code><a href="#systemmoduleDetailsmark" data-toggle="tooltip" title="Systemmodul-Name" @click="goToSystemmodule(data.systemModule.id)">{{ data.systemModule.name }}</a></code>

in this line:

<code><a href="#systemmoduleDetailsmark" data-toggle="tooltip" title="Systemmodul-Name" @click="goToSystemmodule(data.systemModule.id)">{{ data.systemModule.name }}</a>{{ config.separator }} <span data-toggle="tooltip" title="Tabelle-ID">{{ data.tableId }}</span>{{ config.separator }} <span data-toggle="tooltip" title="Tabelle-Name">{{ data.name }}</span>{{ config.separator }} <span data-toggle="tooltip" title="Alias">{{ data.alias }}</span></code>

### What is Expected?
I would except that maybe the component doesnt show up and i have to deal with making the user understand that an error occured.

### What is actually happening?
But actually the complete program freezes in the browser. But when i click on a button for example the code behind it runs. I see every logger in the console but nothing on the screen changes.

**Comment by posva** [comment]
Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

---

You're simply trying to access a property of a `null` object with `data.systemModule.name`. You should make something like `{{ data.systemModule && data.systemModule.name }}` or use a computed property that makes sure to access an existing object
