### ISSUE TITLE
Warns in vue2

### ISSUE THREAD

**Issue by cmzz** [vuejs/vue#4822]
### Vue.js version
2.1.10

### Reproduction Link
[Vue warn]: Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

**Comment by posva** [comment]
Thank your for your interest in this project.
Please read the [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) before opening new issues.

---

The warning is pretty clear. If the warning is being triggered in an unexpected scenario, please provide a repro and give a bit more details about the expected behaviour
