### ISSUE TITLE
Add public API to eval Vue expression

### ISSUE THREAD

**Issue by sellvana** [vuejs/vue#4850]
Hello, I didn't find how to evaluate an expression, as it would be in template. 

Something like `this.$eval('value|filter')` - don't think that should be very hard, but could be really useful!

Thanks!

**Comment by blake-newman** [comment]
This seems to be advocating the use of `eval`. 

The reason expressions like this work in templates is because they are compiled to normal JS before execution. Using helper methods available to render functions. 

This above solution to work at runtime would need the use of `eval` which is a no go. 

What you want to do is.to add a computed property. That evaluates the expression and keeps track of the dependency tree. 

Also for your information, filters evaluates to simple functional calls. `value|filter` can be represented in code as `this.$filters.filter(value)`

**Comment by sellvana** [comment]
Thanks for the response. I needed it because I'd like to supply a simple custom expressions from PHP configuration. I have found a different solution.

**Comment by hunterae** [comment]
@sellvana : what was the solution you found?

**Comment by scramatte** [comment]
I'm interested into this too ... @sellvana : what what the solution you found?
