### ISSUE TITLE
Vuejs screwing up the selected option in a select component

### ISSUE THREAD

**Issue by tiagomatosweb** [vuejs/vue#4897]
Hi all, 

I think it is a bug!

I'm passing data from parent to child component in order to select a default option in a select element. This select, which is in the child component, is populated by the child component itself and the default value should come from the parent.

So, once everything renders the select is not marked the default option according to the parent value, also, the parent value is being deleted. 

App.vue
```
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <h1></h1>

    <h4>Example 1</h4>
    <user :account="account"></user>
  </div>
</template>

<script>
import user from './User.vue'

export default {
  name: 'app',

  components: {user},

  created() {
    this.getAccount();
  },

  data () {
    return {
      account: {
        id: '',
        name: ''
      }
    }
  },

  methods: {
    getAccount() {
      this.$http.get('account.json')
      .then((res) => {
        this.account.id = res.body.id
      })
    }
  }
}
</script>
```

User.vue
```
<template>
  <div>
    {{ account }}<br>
    <select v-model="account.id">
    <option value="">Choose</option>
    <option v-for="(user, index) in users" :value="user.id">{{ user.name }}</option>
  </select>

  </div>
</template>

<script>
export default {
  props: {
    account: {
      type: Object,
      required: true
    }
  },

  created() {
    this.getUsers();
  },

  data() {
    return {
      users: [],
    }
  },

  methods: {
    getUsers() {
      this.$http.get('https://jsonplaceholder.typicode.com/users')
      .then((res) => {
        this.users = res.body;
      })
    }
  }
}
</script>

```

I made a package using https://github.com/vuejs-templates/webpack in order to facilitate your help. You can download the package [here](https://www.sendspace.com/file/obvex1)

**Comment by Kingwl** [comment]
this is not a bug
the value of your default option is ''
and the account.id is not equal ''
https://jsfiddle.net/Lnd2sL1v/2/

**Comment by tiagomatosweb** [comment]
Thank you for your reply!

In the getAccount() method I set the value of account.id. So, account.id will change when the promise is done. This should change all the way down within child component and select the right value in the select, right?
I'm experiencing this in local and the final result looks like this
http://jobs.tiagomatos.com/vuejs/example1.png

**Comment by Kingwl** [comment]
yes you can look this example https://jsfiddle.net/Lnd2sL1v/3/
and I think you should not modify the props (v-model) in child component
you should emit a event to parent component
change value on parent component and pass it to child

**Comment by tiagomatosweb** [comment]
Thats all I want, but here in my local it doesn't work. Actually the child select element seems to change the account.id because of the two-way data binding (not sure). Thus, the account.id is being deleted as you can see in the screenshot I provided before. Why does it happen?

Why should I use emit instead of change the value straight from the child component?

As a workaround, I just did

Force selected in the select element and using onChange
```
<select @change="onChange($event.target.value)">
      <option value="">Choose</option>
      <option v-for="(user, index) in users" :value="user.id" :selected="user.id == account.id">{{ user.name }}</option>
    </select>

```

Then when the select changes
```
onChange(value) {
      this.account.id = value;
}
```

Is that acceptable?

Thanks a lot for your help.

**Comment by ridewn** [comment]
> Why should I use emit instead of change the value straight from the child component?

This is recommended in Vue 2 since the .once and .sync modifiers for bindings are deprecated from Vue 1. From the migration guide from Vue 1 to Vue 2:

> Props are now always one-way down. To produce side effects in the parent scope, a component needs to explicitly emit an event instead of relying on implicit binding.

Also if you are directly modifying the prop being passed down (this doesn't count for object properties), Vue will throw a warning:

> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value.

Going back to your initial problem, the reason the User component isn't updating the App (parent) component correctly is because there is no event telling the child component to update the parent.

Take a look at this fiddle: https://jsfiddle.net/j6tqyt97/4/

There's a bit going on there from what your User and App components do. Firstly, the User component inside the App has a v-model directive. This is possible since the User component emits an input event (in the onChange method). That means whatever data is passed with the event will update whatever data is set in the v-model (in this case the account). Now inside of the User component itself, there is a v-model and change event on the select element. The v-model keeps track of the currently selected user id. There is also a computed property called selectedAccount that returns the user that matches the currently selected id. Lastly, the onChange method emits an input event with the selectedAccount prop as data to update the account in the App component.

A small note - notice how the only time the account prop is being used in the User component is in the created method, ```this.selected = this.account.id```, if you only plan to use the account id in the User component, you might consider passing that as the prop instead of the whole object.

I think you should definitely read through the Vue documentation if you haven't already, as it seems you're a bit confused on how [props / data binding](http://vuejs.org/v2/guide/components.html#Props) work. After you get more familiar with that I'd also recommend looking into [Vuex](http://vuex.vuejs.org/en/intro.html), as it makes handling your applications state much easier.

**Comment by yyx990803** [comment]
If this is not a bug, please conduct further discussions elsewhere. Thanks.

**Comment by tiagomatosweb** [comment]
@ridewn, thank you for your complete answer.
I just read again the props section and yes, I was in the wrong path. The reason that I was trying to change the parent state inside a child component was because I saw this in the doc as my prop is an object.

> Note that objects and arrays in JavaScript are passed by reference, so if the prop is an array or object, mutating the object or array itself inside the child will affect parent state.

But still, I have to agree that in a long way down things can get harder to maintain.

So, to sum up I refactored my code to the following.

The User component
```
<template>
<select @change="onChange($event.target.value)">
      <option value="">Choose</option>
      <option v-for="(user, index) in users" :value="user.id" :selected="user.id == useId">{{ user.name }}</option>
    </select>
</template>

props: ['account'],

computed: {
   useId() {
      return this.account.id;
   }
}

methods: {
   onChange(value) {
      this.$emit('user', value);
   }
}
```

And then in the parent component
```
<template>
<user :account="account" @user="changeUser"></user>
</template>

data() {
   return {
       account: { id: '', name: ''}
   }
}
methods: {
   changeUser(value) {
      this.account.id = value;
   }
}
```

I think it follows now what it should be, isn't it?
