### ISSUE TITLE
Transition Group Move Class doesn't work with display flex

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue#4913]
https://jsfiddle.net/RalphChristianEclipse/z11fe07p/715/
#4900 
i think this is the same issue ?

### Vue.js version
2.1.10

### Reproduction Link
  - No Vue Components Used
  https://jsfiddle.net/RalphChristianEclipse/9L8gvuej/5/
  - Vue Material used
https://jsfiddle.net/RalphChristianEclipse/9L8gvuej/7/

#### No Vue Components Used Steps: 
- Create transition group with display: flex
- Create an array that will be used as a test
- Assign card-move class to move-class of transition-group
- Create a div element that uses v-for to list down all the test elements in array
- Add a click event handler for removing an item
 #### Vue Material Used Steps: 
- Create a transtion group with class md-layout
- Create an array for test
- Assign card-move class to move-class of transition-group
- Create another md-layout inside the transition-group with md-flex-{type}="33" 
- Add a click.native handler for md-layout that removes items
- create an md-card that uses v-for to list down the elements of the test array

### What is Expected?
- Smooth moving transition when changing positions
### What is actually happening?
- No Moving Transition happens

I'm also doing this with an empty array and firebase will push elements in realtime

The documentation states when items are in display: flex move-class will be appended when changes in array position happens or removals

**Comment by posva** [comment]
Please, take the time to read the docs a bit more before opening issues and use the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) to ask questions...

Use this: https://vuejs.org/v2/guide/transitions.html
Here's a _working_ version https://jsfiddle.net/wtt1oh6f/

**Comment by ralphchristianeclipse** [comment]
why close the issue i don't have problems on the enter-active-class or leave-active-class

im using animate.css for that purpose

the title says it all the move-class is not used while removing items

**Comment by posva** [comment]
I'm closing it because you keep doing the same thing: asking questions without taking into account others' time
Here's the fiddle with moving animations: https://jsfiddle.net/posva/L717s024/

The fiddle you posted wasn't even changing the order of the list. I'd have expected you to at least try out shuffling the array and test things like in the [guide](https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions).

**Comment by ralphchristianeclipse** [comment]
@posva 
There is a question but about the reference on the issue about empty arrays which i think maybe the cause

but the thing here its the move class that is not appended using move-class attribute

**Comment by ralphchristianeclipse** [comment]
@posva 

![image](https://cloud.githubusercontent.com/assets/25447231/22867908/b1eb483e-f1ca-11e6-8ad1-11942bbda8a3.png)

You can check out the image here and look closely that move-class attribute is not apended to other elements also

**Comment by ralphchristianeclipse** [comment]
@posva 
See the difference here on the main example about transition-group move class 

![image](https://cloud.githubusercontent.com/assets/25447231/22867946/02d11d6e-f1cb-11e6-94d0-2b0b36a4ff1e.png)

**Comment by ralphchristianeclipse** [comment]
don't know but i'm doing it in development with hot reloading it works when hot reloaded but when i reload manually it doesn't work again

**Comment by posva** [comment]
> the classes that's appended are enter, active, leave and to classes only not the move class

The move class is not appended when entering or leaving: https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions
Basically, you need something like `position: absolute` like in the examples

I'm locking this because you're not following the [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) and wasting time for anyone reading the issue (including yourself).

It's not the first, nor the second time you have disguised questions as issues in vue repos, so please, next time take the time to make sure there's a bug by reading a bit more the docs and seeking for help in forums. Thanks
