### ISSUE TITLE
Some times $dispatch not work

### ISSUE THREAD

**Issue by yangmingshan** [vuejs/vue#4919]
### Vue.js version
1.0.28

### Reproduction Link
https://jsfiddle.net/yangmingshan/4jc2fcxg/

### Steps to reproduce
Double-click +1 button in short time

### What is Expected?
The number add 2

### What is actually happening?
The number ony add 1

In second click child component $parent is null, don't know why

**Comment by posva** [comment]
Since the v-for loop is removing the element and inserting a new one, the child is unable to dispatch a message. Here's a version where you can see the count reset after the timeout: https://jsfiddle.net/posva/31p5uq56/

I'm not sure it's a bug because the component has no way of knowing if a setTimeout has been set up. Even if we save the current parent somewhere, if the parent of the child element also changes in that frame of time, we will end up in the same situation, which is your case here.

**Comment by yangmingshan** [comment]
I know it's a terrible case, But I don't know it's a bug or not, so I point out. Thanks for your explain, I don't mind if you close this issue

**Comment by posva** [comment]
Actually, the repro was great: it was short and let me find the cause very quickly.
Thanks for pointing it out 🙂
