### ISSUE TITLE
vue2.1.10  Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by wgq837051** [vuejs/vue#4940]
### Vue.js version
2.1.10
build vue2.1.10 project by vue-cli , when npm run dev ,
![untext](https://cloud.githubusercontent.com/assets/6071212/23009134/28ad9680-f44f-11e6-8636-5be68a7872d6.png)
App.vue content
`
<template>
<section>
  <div class="highlight" slot="highlight">
    <pre>
        <div class="hljs language-html"> <span class="hljs-tag">&lt;</span>
           
      </div>
  </pre>
</div>
</section></template>
<script>
  
  export default {
    data() {
      return {
        value1: true,
       
      }
    }
  };
</script>
`
but when App.vue content is 
`
<template>
<section>
  <div class="highlight" slot="highlight">
    <pre>
        <div class="hljs language-html"> 
           
      </div>
  </pre>
</div>
</section></template>
<script>
  
  export default {
    data() {
      return {
        value1: true,
       
      }
    }
  };
</script>
`
The following only less than the above `<span class="hljs-tag">&lt;</span>`

**Comment by fnlctrl** [comment]
Please don't open an issue twice. The previous one was closed because it does not conform to the 
[Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines).  Please use  [gitter](https://gitter.im/vuejs/vue) or [forum](https://forum.vuejs.org/) or [stackoverflow](https://stackoverflow.com)to ask questions.
