### ISSUE TITLE
Mixin data not overriding data from vm

### ISSUE THREAD

**Issue by docmattman** [vuejs/vue#4960]
I'm not sure if this is a bug or by design, but I can't get a mixin to override data from a vm.  The mixin is able to add extra data that the original vm doesn't have, but it won't override existing data (which is what I'm trying to accomplish).  I make a fiddle here to show it:

https://jsfiddle.net/8v9sfxok/

```
var mixin = {
	data: function() {
  	return {
      foo: 'boo',
      test: 'blah'
    }
  }
}

var vm = new Vue({
  el: '#vue-instance',
  mixins: [mixin],
  data: function() {
  	return {
      foo: 'bar'
    }
  }
});
```

`foo` still equals "bar" instead of "boo" (from the mixin).  Is this the intended behavior for mixins?  Is there another way to accomplish this?

**Comment by posva** [comment]
Hi, yes, it's indeed intended behaviour. After all imagine a global mixin overriding your local component data 😄 

You can use https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies to override the behaviour but I wouldn't recommend you that because that could potentially mess up plugins.

You should ask the questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Feel free to put the solution here once you found one
