### ISSUE TITLE
Allow SSR keep whitespace anywhere

### ISSUE THREAD

**Issue by baoti** [vuejs/vue#4965]
I have a feature request, to support SSR with non-vue server renderer, e.g. django template, Smarty template.

Simple example: https://jsfiddle.net/yz5hw1ou/

```
<div id="app" server-rendered="true">
  <span></span>
</div>
```

Will cause a warn say not matching, because of leading and tailing whitespaces.

**Comment by yyx990803** [comment]
SSR hydration requires the client side DOM to be generated by Vue's server renderer. This is not something that's easy to change and honestly I don't see the benefit being worth the effort. If anything, you should be trying to generate Vue-compliant markup instead of asking Vue to cater to your non-compliant markup...

**Comment by baoti** [comment]
I saw one option `preserveWhitespace`, May one other option to control keeping any whitespace when parsing html.
Those template engines may can remove whitespace, but action different from vue.

**Comment by PierBover** [comment]
I'm trying to render markup on the server without Vue and stumbled upon this problem when hydrating.

It would be great if Vue could ignore whitespace when matching server-rendered markup, but I guess removing whitespace from the rendered string before serving the request could also be a viable option.

For example with Go: https://github.com/tdewolff/minify#whitespace-removal
