### ISSUE TITLE
The directive can‘t update value to v-model  since i update vue to 2.0

### ISSUE THREAD

**Issue by 327326724** [vuejs/vue#4980]
```js
import Vue from 'vue'
export default {
  bind: function (el, binding, vnode) {
    let instance
    let defaultConfig = {
      theme: 'ios',
      lang: 'zh',
      display: 'bottom',
      focusOnClose: false,
      onSet: function (event, inst) {
        Vue.set(vnode.context, binding.exexpression, event.valueText);
      }
    };
    defaultConfig = Object.assign({}, defaultConfig, vnode.context[binding.arg])
    instance = mobiscroll.datetime(el, defaultConfig)
    vnode.context.$watch(binding.arg, (newVal) => {
      if(newVal){
        instance.option(newVal)
      }
    })
  },
  update: function (el, binding, vnode) {
    if(binding.value){
      el.value = binding.value
    }
  },
  unbind: function () {}
}
```
```html
<input type="text" placeholder="请选择时间" v-mobidatetime:startConfig="orderDto.startTime" readonly/>
```
```js
data () {
      return {
        orderDto:{
          startTime:''
        },
       startConfig: {
          dateFormat: 'yy-mm-dd',
          timeWheels: 'HHii',
          steps: {
            minute: 10,
            zeroBased: true
          }
        },
      }
    },
```

**Comment by posva** [comment]
Please, make sure to read our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md). Issues are for bug reports and feature requests only.

We encourage you to ask questions on the [forum ](http://forum.vuejs.org), [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there. Come back open a new issue if you find out there's a real issue.

Closing because you simply posted your component expecting us to fix it for you.
In case you don't know about it, we have a migration guide to help out people who are in the same situation as you: https://vuejs.org/v2/guide/migration.html

**Comment by 327326724** [comment]
no one to help...
https://forum.vuejs.org/t/how-to-update-the-v-model-with-a-directive/6841?u=327326724
