### ISSUE TITLE
How to properly update whole array-type property?

### ISSUE THREAD

**Issue by mityukov** [vuejs/vue#5028]
I have an array-type property, say, `dashboards`, initially initialized with an empty array:
```
  data() {
        return {
            title: 'loading…',
            dashboards: []
        };
    },
```

Then, I have the following lifecycle method:

```
created() {
        this.$http.get(this.dataUrl).then(res => {
            console.log(res.body);
            this.dashboards = res.body.data;
            this.title = res.body.subtitle;
        });
}
```

finally, here's the template:
```
    <div class="Dashboards-list">
        <dash-table
            :title="title"
            :passed-data="dashboards"
        ></dash-table>
    </div>
```

Component is rendered initially, with the dummy `title` and empty `dashboards` array.

However, the component is not re-rendered after the actual data is received from server. I've read that "Reactivity in depth" part of the guide as well as "rendering lists" note. Still, can't figure out how to update whole array properly. After googling around, it looks that the problem does not exist at all… :/

**Comment by LinusBorg** [comment]
Hello @mityukov 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by mityukov** [comment]
Well, I would probably not ask in the issue tracker, but I've seen couple of screencast, and those folks simply assigned new data to array-type property. So, it's quite unusual that it doesn't work in my case.

**Comment by xiaohan2013** [comment]
@mityukov  i encouter similar issue.use $foreUpdate work well. Hope work for you!
