### ISSUE TITLE
How can I pass the slot options to the Vue constructor?

### ISSUE THREAD

**Issue by muyi0327** [vuejs/vue#5041]
How can I pass the slot options to the Vue constructor?

**Comment by LinusBorg** [comment]
You can't. it wouldn't make sense, because a main instance can't have slot contents, since slot content come from the parent.

Also: Your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
