### ISSUE TITLE
<select> strange behavior on Iphone

### ISSUE THREAD

**Issue by boris-graeff** [vuejs/vue#5064]
### Vue.js version
2.1.10

### Reproduction Link
https://vuejs.org/v2/guide/forms.html#Select

### Reproduction gif
[https://gifyu.com/images/bug-select2.gif](https://gifyu.com/images/bug-select2.gif)

### Steps to reproduce

Open reproduction link with an Iphone (tested with Safari and Chrome)
Click on select (simple select example)

### What is Expected?

First option (A) can be directly selected

### What is actually happening?

To select the first option I have to select another one before

Is it a bug in iOS or vue issue ?

**Comment by posva** [comment]
I think it's not a bug, it looks like iOS isn't firing any onChange event. I'm launching the simulator to test it but it should work if you click **on A**

**Comment by posva** [comment]
Oh, clicking on A does nothing...
you can add a disabled option to match the non selected state:

```html
<select v-model="selected">
  <option v-if="selected === null" :value="null" disabled></option>
  <option>A</option>
  <option>B</option>
  <option>C</option>
</select>
```

**Comment by boris-graeff** [comment]
With style='display: none' works well on FF / Chrome
Not perfect but acceptable on Safari / IE (empty space) : [https://ibb.co/cOCfFa](https://ibb.co/cOCfFa)

**Comment by chrisvfritz** [comment]
@posva Hmm, this [came up on the docs](https://github.com/vuejs/vuejs.org/issues/683#issuecomment-270546017) as well and I decided then not to update the example, thinking it's a bug for iOS to fix. I'm still leaning in that direction, since the behavior has nothing to do with Vue, but I could probably be convinced otherwise. 😕

**Comment by posva** [comment]
I think it's a good practice to add a non-selected option (value = null) to selects that have a v-model because it works as a fallback when no option is selected and the browser doesn't display another option as selected while it really isn't:
![screenflow](https://cloud.githubusercontent.com/assets/664177/23603815/e597f136-0256-11e7-9af7-19352246a992.gif)

```html
<form  @submit.prevent>
<select required v-model="value">
  <option :value="null" disabled>None</option>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
<input type="submit">
</form>
```
We can also use an empty string for the value which may be better

**Comment by yyx990803** [comment]
I don't really think there's much we can do about this in Vue core :/
I guess as suggested, we can add a tip block in the docs to recommend always having a default selected option.
