### ISSUE TITLE
Performance degradation when using Components

### ISSUE THREAD

**Issue by fenduru** [vuejs/vue#5070]
### Vue.js version
2.2.1

### Reproduction Link

https://jsfiddle.net/50wL7mdz/18262/

### Steps to reproduce

Render a collection of items using Components (functional or not), and compare to rendering a collection of items using a `<div>`

### What is Expected?

I expected that a functional component would perform closely to a `<div>` inlined in a template, and that a stateful component would have some overhead when initializing, but not when adding an item to the collection.

### What is actually happening?

In the reproducer, updating the list when using the inline template takes ~0.5ms, which is significantly faster than functional components (~1.2ms), and even more so than normal stateful components (~2.8ms).

I'm surprised that the stateful component is so slow because none of its reactive bits are updating (the `updated` hook is not triggered for the SimpleItem component in the reproducer)

I am working on a virtualized datagrid where I'm running into this problem. I have a `<cell>` component, however using it makes scrolling noticeably slower. If I copy the `<cell>` template directly into the parent component, performance is unbelievably fast, however this is not desirable as I need the ability to swap in different `<cell>` components.

**Comment by fnlctrl** [comment]
Functional components do have a little overhead, but there's something that can be optimized in your original fiddle. 


1. The functional variant and the inline one isn't strictly equal - by having an extra prop. So I remove the prop and used ctx.children instead, to make it the equivalent of the inline one.
Also, there is an empty object literal that's created on every render, so I removed it too. FYI the second parameter of `h` can be omitted.
```js
const FunctionalItem = {
  functional: true,
  render: function(h, ctx) {
    return h('div',ctx.data, ctx.children);
  }
};
```

2. Another big performance issue in your original fiddle is that the `key` isn't actually applied, because it's in `ctx.data` and wasn't passed to the rendered `div`.
So I fixed it to be `h('div',ctx.data, ctx.children)`

The updated fiddle: https://jsfiddle.net/mxt8ebxh/
After the changes, the functional items list's update times are much closer to the inline one (almost the same except for some fluctuations):
![image](https://cloud.githubusercontent.com/assets/5557143/23525096/3a443df2-ffc8-11e6-9a8d-bf51643fc96a.png)

@chrisvfritz Maybe some notes can be added the docs? Like "Don't forget to actually pass the key to the rendered node" or something.

**Comment by fenduru** [comment]
@fnlctrl This is a big improvement and explains the discrepency between the functional component and the inline one. Thanks!

I'm still very surprised at how slow the stateful example is though, given the fact that it seems to be smart enough to know it doesn't need to be updated.

I included the functional example for comparison, however I would really like to be able to build my item component with templates, computed properties, etc. In the data grid I am working on the cell components are "functional" in the sense that they will only change when their props change.

It seems now the only way to get these performance characteristics would be to have functional components all the way down the tree? i.e. if my functional component uses a non-functional component in its render function then I will lose perf again, correct?

**Comment by fnlctrl** [comment]
> I'm still very surprised at how slow the stateful example is though, given the fact that it seems to be smart enough to know it doesn't need to be updated.

Stateful components have the biggest overhead of creating instances. In the fiddle, though most components are updated, a new one must always be created.

> I included the functional example for comparison, however I would really like to be able to build my item component with templates

Functional component support for vue-loader is being developed by @blake-newman (allowing us to write templates for functional components :D), though there's no ETA for this.

> if my functional component uses a non-functional component in its render function then I will lose perf again, correct?

Sadly, it's true. Though perfs can be improved a bit if you always key the non-functional components.

**Comment by fenduru** [comment]
> Stateful components have the biggest overhead of creating instances. In the fiddle, though most components are updated, a new one must always be created.

None of the components are being updated, actually (at least not according to the `updated` hook). Additionally, if the size of the list starts off at 1, it takes ~0.5ms to prepend an item (compared to the 2.8ms when prepending to the 500 item list). So what would be taking the extra 2.3ms? The only thing that seems like it wouldn't be reactive would be the `v-for` having to figure out matching keys, but that seems like it should take at most the amount of time that the functional example takes (~0.6ms). So If the number was closer to 1ms I wouldn't be surprised, but 2.8ms seems like there is something else going on behind the scenes.

Here's an updated [fiddle](https://jsfiddle.net/50wL7mdz/18268/) with a log in the `updated` hook for the SimpleItem and starting the list at size 1

**Comment by fnlctrl** [comment]
> None of the components are being updated, actually (at least not according to the updated hook). 

They are actually being updated, you can check it by adding a `created` hook to the list item:
Though I'm not sure why `updated` hooks aren't called..
![image](https://cloud.githubusercontent.com/assets/5557143/23527641/c9625ba0-ffd1-11e6-98aa-eed1b9d238fd.png)


This is what happens on every click of `prepend`
![image](https://cloud.githubusercontent.com/assets/5557143/23527752/2a6cc9a8-ffd2-11e6-9312-0cb8da3a5e55.png)
Don't know if there could be improvements.. I'm not very familiar with the code.

**Comment by fenduru** [comment]
The created hook is being called for the new item that got prepended (this is correct, we added 1 item and `created` was called once). The rest of the items aren't being updated (the DOM doesn't update and the updated hook isn't called), yet their presence is causing a perf hit.

I was trying to dig around in the code, but haven't figured out where the crux of the difference between the stateful/stateless component rendering is yet.

**Comment by posva** [comment]
Use the production build when benchmarking, please

**Comment by fenduru** [comment]
@posva I had tried both with similar results. Forgot to switch it back in my fiddle, my bad.

Anyway, I've been diving into this a bit more and the primary difference seems to be the invocation of `prepatch` for the stateful components. I'll have to mess around with it a bit more, but I have a hunch that in certain scenarios (like this one) there should be enough information available to know that no actual updates are happening to its parent/element/children, so we might be able to avoid a lot of that.

I did a quick and dirty test where I immediately returned from prepatch for my item components, and this brought the nonfunctional update time to roughly the same as the functional update time.

**Comment by yyx990803** [comment]
Well, this is expected because whether a stateful component needs to be updated still needs to be calculated by comparing its previous props vs. next props. Resolving, validating and comparing props still has a cost. The good thing is that this cost remains constant no matter how complex the component's template / render function is.

Anyway, I'd consider several milliseconds overhead for 500 components acceptable. It may be possible to improve it, but not a very high priority imo.

**Comment by fenduru** [comment]
@yyx990803 Why do props need to be compared when the reactivity system has already allowed us to avoid calling `render` on those components?

**Comment by yyx990803** [comment]
Because that's how the reactivity system knows it...

**Comment by Nandiin** [comment]
@fnlctrl @fenduru Can you please further explain this ?
> if my functional component uses a non-functional component in its render function then I will lose perf again

I can see that non-functional component inside function component would be slower then a pure functional component tree. But does it hold true when the comparision goes between non-functional inside functional and non-functional inside non-functional ?

```JSX
// A
<Functional>
   <AnotherFunctional/>
</Functional>

// B
<Functional>
  <NonFunctional/>
</Functional>

// C
<NonFunctional>
  <AnotherNonFunctional/>
</NonFunctional>
```
Am I correct to conclude that performance is: A > B > C ? ( assuming components in all three cases do same job regarding their structural position)
Or is it A > B = C since `performance gain from functional component is lost in case B` ?
