### ISSUE TITLE
how to pass propsData to async component

### ISSUE THREAD

**Issue by maple-leaf** [vuejs/vue#5078]
```
// ayncA.js
import Vue from 'vue';

export default Vue.component('async-a', function(resolve, reject) {
    require(['./A'], (A) => {
        resolve(A.default);  // how to pass props to A??
    });
});

```
```
// A.js
import Vue from 'vue';

export default Vue.extend({
    template: `msg: ${msg}`,
    props: ['msg']
});
```
```
// App.js
import Vue from 'vue';
import AsyncA from './asyncA';
new Vue({
    el: '#app',
    components: {
        'async-a': AsyncA
    },
    template: '<async-a msg="msg"></async-a>',
    data() {
         return { msg: "come from app"}
    }
});
```

As the code above showed, I can pass props to `async-a`, but the 'real' component `A` will not get `msg` prop. 
My question is similar to [http://stackoverflow.com/questions/38344091/vuejs-can-we-give-props-to-async-component-via-dynamic-component-pattern-compo](http://stackoverflow.com/questions/38344091/vuejs-can-we-give-props-to-async-component-via-dynamic-component-pattern-compo), but the accepted answer doesn't look like a best way.

**Comment by simplesmiler** [comment]
1. You are using es6 string interpolation for the template, which inserts the value immediately when defining the component. Instead you should use [Vue template syntax](https://vuejs.org/v2/guide/syntax.html#Interpolations):
``` js
template: 'msg: {{msg}}'
```
2. You forgot to [bind](https://vuejs.org/v2/guide/components.html#Dynamic-Props) the `msg`:
``` html
<async-a :msg="msg"></async-a>
```

Closing, because this was a usage question, and we encourage you to ask questions on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue tracker is reserved for bug reports and feature requests.
