### ISSUE TITLE
Vue-template-compiler strange behavior

### ISSUE THREAD

**Issue by exdis** [vuejs/vue#5086]
Some strange things occur when I am trying to compile this template:

```html
<span class="checkbox checkbox_size_s">
    <span class="checkbox__box">
        <input class="checkbox__control" type="checkbox"/>
        <i class="checkbox__tick"></i>
    </span>
    <label class="checkbox__label">Label</label>
</span>
```

Render function:

`with(this){return _m(0)}`

You can check result of compilation here https://runkit.com/exdis/58b9b7d8a97071001491ac7b

vue-template-compiler version: 2.2.1

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

---

Everything looks right to me. The content is static and that's why there's a `staticRenderFns` property. The `_m` basically renders the first element of that array

**Comment by LinusBorg** [comment]
If I'm not mistaken, that is simply because your whole template is static, so vue-loader extracted it all into a so-called `staticRenderFn` - which in the render function, is accessed via the shortcut `_m`

basically, it catches this template because it can never change.

**Comment by exdis** [comment]
Thanks guys! I am just forgot to pass `staticRenderFns` to component and spent a lot of time to figure out what I am doing wrong.
