### ISSUE TITLE
Configuration for empty VNode not to render to <!---->

### ISSUE THREAD

**Issue by xtongs** [vuejs/vue#5117]
I have been working on an [infinite scroll list plugin](https://github.com/xtongs/vue-recyclist) for Vue.js 2.1+. 
It basically use 'v-if' to implement DOM recycling, meaning that when the list gets long enough,
there will still only be limited DOMs exists so that scrolling performance remains good.

The idea comes from this article [Complexities of an Infinite Scroller](https://developers.google.com/web/updates/2016/07/infinite-scroller),
I found it will be useful if the idea can be implemented with Vue, so there comes out this plugin.

So far it works pretty well, with scoped slots, it's highly customizable.
But there is this tiny problem, empty VNode will be rendered to this `<!---->` html comment string. 
This is definitely not a bug, and I found the empty comment string is used for Vue unit test.

However, when developing and inspecting elements, the developer tools panel is full of `<!---->`s.
![image](https://cloud.githubusercontent.com/assets/512685/23645532/8c73a144-0347-11e7-8a56-48d57538da16.png)
Check out the [repo](https://github.com/xtongs/vue-recyclist) and [example page](https://xtongs.github.io/vue-recyclist).

It seems have no influence on performance, only a little annoying to developers.
So is there any way to get rid of these empty comments?

**Comment by yyx990803** [comment]
`v-if` is usually used for elements in a relatively stable node structure, rendering it to empty comment tags makes vnode lists diffing more efficient as the lists are more "stable", and it avoids some edge cases when elements are not keyed. In your case it doesn't seem to cause any real issue other than small inspection annoyance, so unfortunately I don't think we would change this behavior.

For virtual scrolling lists, it maybe a better idea to use a computed property to return a subset of the items that needs to be rendered, e.g. `v-for="item in displayedItems"` instead of using a `v-if` on each item.

**Comment by xtongs** [comment]
Thanks Evan! As you suggested, I removed `v-if` and added a computed subset property, and now it works smooth and tidy!

**Comment by adyz** [comment]
Hi,

I ended up on this issue because I also have some vuejs comments inside my div and the CSS selector `div:empty { padding:0; }` does not work with comments, only if they are inline https://css-tricks.com/almanac/selectors/e/empty/#article-header-id-1

I read Evan's comment and i'll find a workaround, but just to be sure, is there any change since the issue reported here regarding this subject?


Thank you, 
Adrian


PS: I love Vue (sound funny)

**Comment by syuilo** [comment]
I have same issue. `:empty` css selector does not work.

**Comment by dallanlee** [comment]
Disappointing that no one (looking at you, @yyx990803) addresses the fact that this makes using the `:empty` CSS pseudo selector unusable. What's the workaround?

**Comment by TimWeidner** [comment]
> Disappointing that no one (looking at you, @yyx990803) addresses the fact that this makes using the `:empty` CSS pseudo selector unusable. What's the workaround?

You could just set a class to the parent if none of the elements are shown and check for the class in CSS.
Also please don't necro this issue, it has been closed for over three years.

**Comment by vaheqelyan** [comment]
It's almost 2024, and this issue still exists.

**Comment by TimWeidner** [comment]
> It's almost 2024, and this issue still exists.

Yes. That's because it's largely irrelevant. Even more so than 3 years ago when I last had to tell somebody to not necro this issue that had been inactive and closed for 3 years.
At this point you should be using the official Vue Dev Tools anyway, which allow you to look at all the mounted components and their respective properties and everything.

If you have any new reason to want this functionality, please feel free to open a new issue and reference this one.
