### ISSUE TITLE
Select as transition element doesn't display its correct v-model value upon transitioning in

### ISSUE THREAD

**Issue by Gawdl3y** [vuejs/vue#5124]
### Vue.js version
2.2.1

### Reproduction link
- https://jsfiddle.net/06b2247d/17/ (transition)
- https://jsfiddle.net/06b2247d/18/ (no transition, not affected)

### Steps to reproduce
- Take note of what tag was selected upon initial run (logged to console)
- Switch sources
- Take note of what tag was selected (logged to console)

#### What is expected?
The tag that was logged should be the one that is displayed in the selection box in both cases.

#### What is actually happening?
The selection box displays the first option upon first load or switching sources, rather than the one that was actually selected.

**Comment by yyx990803** [comment]
This is because browsers reset a `<select>` element's selected option whenever it is inserted into the DOM... I'm not sure why they do it, but I think this has to be worked around in userland. A simple fix is updating `tagChoice` in the `enter` hook of the transition (when the `<select>` element has just been inserted into the DOM): https://jsfiddle.net/8qfqm8ht/

**Comment by Gawdl3y** [comment]
Thanks for the info.
