### ISSUE TITLE
The "why" is missing from the introduction

### ISSUE THREAD

**Issue by neokio** [vuejs/vue#5137]
I've been a full-stack LAMP guy for more than 10 years. For the last 2 years, I've repeatedly heard "Check out Vue!", and have spent maybe 45 minutes in total reading the guides and studying the examples on vue.org. And every time, I think the same thing: "Ok, another Javascript UI library, like Angular or React. How could this help anyone? What am I not seeing? WHY do people use Javascript UI libraries?"

What makes this ...

```html
<div id="app">
  <p>{{ message }}</p>
</div>
```
```javascript
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```
... better than this ...

```html
<div id="app">
  <p><?= $message =></p>
</div>
```
```php
$message = 'Hello PHP';
```

... or this ...

```html
<div id="app">
  <p></p>
</div>
```
```javascript
$('#app p').html('Hello jQuery');
```
?

The intro guide  is written from the perspective of someone who has forgotten what's it's like to NOT use a Javascript UI library. There's no context, no sense of what problems they solve, comparing the benefits versus other approaches, etc.

This project has 45,857 stars, which means I'm standing in a room with 45,857 people who see something that I'm not seeing. Maybe it's not up to Vue.org to educate people on what makes a Javascript UI library useful. Unfortunately, to the best of my searching, no one else has taken this on to any effect.

My suggestions is to expand the scope of the Introduction, including a section that covers the "Why", written as one would describe color to a blind person. Otherwise, you're just preaching to the converted (which may or may not be your goal).

**Comment by yyx990803** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests.

Your suggestion should probably be posted to https://github.com/vuejs/vuejs.org - but still, I personally think you are indeed missing something very obvious, and the main reason is that all those who "get it" probably have already built apps using the techniques you mentioned. Ask yourself "what happens when things need to change?", and try to replicate the [TodoMVC example](https://github.com/vuejs/vue/blob/dev/examples/todomvc/app.js) using plain jQuery. I'm sure you will understand it better.

**Comment by ralphchristianeclipse** [comment]
@neokio its an MVVM Framework easily binds javascript to html

Think of this all the 

 The less the syntax the more you code

Also it helps you refactor and reuse code

**Comment by LinusBorg** [comment]
Btw. you are welcome to discuss this on forum.vuejs.org - the issue tracker is simply the wrong place for this.

**Comment by smolinari** [comment]
It is the difference between Vue being handled in the browser and PHP being handled on the server. It is the difference between a very smart or a not-as-smart client. It is the difference between needing only an API to serve the application and not needing server-side rendering for each page (although Vue also supports server-side rendering). It is the difference between having a UI manipulated based on data changes or a UI based on DOM manipulations due so some data changes ( aka the suggestion to try doing the to-do list with jQuery from @yyx990803). It is the difference between having structure (HTML), behavior(JS) and design (CSS) [all in one file,](https://vuejs.org/v2/guide/single-file-components.html) instead of spread out all over the place. In fact, if you add [GraphQL](http://graphql.org/learn/), you can even have the actual data retrieval and manipulation also within that same file. It is the difference of being able to create mobile or desktop apps with the same or very similar code base, (and the appropriate wrappers like [Cordova](https://cordova.apache.org/) or [Electron](https://electron.atom.io/)) and only dreaming of making desktop or mobile apps. 

I probably missed something, but that was off the top of my head. 😄 

Scott
