### ISSUE TITLE
更新到2.2.1 定义自定义指令 在使用自定义指令后在谷歌浏览器下 出现警告

### ISSUE THREAD

**Issue by ashersmtll** [vuejs/vue#5142]
更新后 定义自定义指令 在使用自定义指令后在谷歌浏览器下 出现警告：
Property or method "v" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by ccforward** [comment]
Please show your code in http://jsfiddle.net

**Comment by infynity** [comment]
same problem

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by ashersmtll** [comment]
https://jsfiddle.net/varec3vx/#&togetherjs=A15swabImB

代码在这里 但是 这样写，放在HTML 中用谷歌浏览器打开 又没有警告 正常的。项目中按照模块加载 又会出错

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.

Your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

You should ask it on the [forum ](http://forum.vuejs.org), [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue). Come back open a new issue if you find out there's a real issue

Thanks!

---

http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js
