### ISSUE TITLE
Reactivity with render function components triggers entire re-render of tree

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue#5155]
### Vue.js version
2.2.1

### Reproduction Link
http://codepen.io/johnjleider/pen/GWWpPK?editors=1111

### Steps to reproduce
Create a chain of render components and update one with a bound style value.

### What is Expected?
Re-render of component

### What is actually happening?
Re-rendering of entire component chain.

I ran into this while testing resizing a div by mouse move. I replaced the style object with explicitly assigning the values through $refs, and the performance change was quite substantial.
![selection_070](https://cloud.githubusercontent.com/assets/9064066/23771500/2ae92670-04e5-11e7-8e60-e68ddc147391.png)
![selection_069](https://cloud.githubusercontent.com/assets/9064066/23771504/2ed105be-04e5-11e7-9265-d6b05cd182d8.png)

This obviously has to do with reactivity, but I wasn't sure if this is intentional.

**Comment by LinusBorg** [comment]
That's not a bug, it's expected behaviour because of the slots that you use.

When the root component re-renders, it passes the slot nodes again to the child component, and now that component has to re-render too, because Vue can't be sure that you haven't decided to implement some logic that reacts to these new vnodes it received in `this.$slots`

**Comment by johnleider** [comment]
Is there a better way to handle this?
