### ISSUE TITLE
Binding an array to an input field

### ISSUE THREAD

**Issue by akaspick** [vuejs/vue#5193]
### Vue.js version
2.2.4

### Steps to reproduce

```<input type="hidden" v-model="arrayData">```

```
arrayData: function() {
   return [1,2,3];
}
```

### What is Expected?

Earlier versions of vue (2.1.9) would set the value of the input field to ```[1,2,3]```, but now the value is set to ```1,2,3```.  Which is the valid representation of an array?  JSON decoding does not work with the latter format.

**Comment by posva** [comment]
As a side note v-model with a hidden input doesn't make sense, you probably want to bind `value`, in which case, it was always binding `1,2,3`: http://jsfiddle.net/o5yb3nhz/
IMO this change makes it more consistent even if it's a breaking change in your specific case because it was never advised to be so

Repro: http://jsfiddle.net/2xksgvpc/

**Comment by akaspick** [comment]
@posva Ok, great.  I'll go with the "proper" format then.  Thanks.
