### ISSUE TITLE
Better TSX render() support

### ISSUE THREAD

**Issue by notoriousb1t** [vuejs/vue#5262]
### What problem does this feature solve?
TypeScript introduced jsxFactory four months ago to allow TSX to specify a variable to act as the createElement.  This works correctly when rendering a single element, but does not map properly when an element has more than one child.

**Works**
```ts
render(h) {
     return <div>{this.text}</div>;
}
```

**Breaks**
```ts
render(h) {
     return <div><small>prefix</small> {this.text}</div>;
}
```

I have worked around this issue by preprocessing my vue components like so, but that is a difficult ask for some:

```ts
/** This attempts to bridge the gap between React and Vue render() */
export const fixRenderFunction = (options: Vue.ComponentOptions<any>) => {
    if (options.render) {
        const orender = options.render;
        options.render = function(h) {
            const self = this;
            const f = function (tagName: string, attr: {}) {
                return h.apply(self, [tagName, attr, Array.prototype.slice(arguments, 2)]);
            }
            return orender.call(self, f);
        }
    }
}
```

### What does the proposed API look like?
I think that if createElement had an overload that supported variardic VNodes, it would make these map up nicely and make support for TSX better in VueJS

**Change in typings**
```ts
export type CreateElement = {
  /* ... */ 

  (tag: string, data: VNodeData, ...children: (VNode | string | VNodeChildren)): VNode; 

  /* ... */ 
}
```

**Usage**
```ts
render(h) {
    return h('div', null, h('small', null, 'prefix'), this.text)
}
```

I am willing to do the legwork (Pull Request) to make this possible

**Comment by posva** [comment]
Can't the TSX loader be fixed instead to support arrays?

**Comment by notoriousb1t** [comment]
I think that adding this overload to VueJS is more reasonable than trying to get this added as a config option to the TypeScript compiler. 

That is especially true since React, Inferno, and others all use the variardic signature.  That is, **VueJS is the outlier for JSX** and they would have to add a library specific option to a language compiler.

I think this should amount to three to five lines of code and a small documentation change

**Comment by posva** [comment]
I understand that but, even if right now Vue is different from React in terms of render fn args, that may not be the case in the future: Other libs (like Mithrill, and probably other) have or will adapt the array syntax instead of the variadic one as it makes more sense and is simpler to use. There're also other vdom engines that use the array syntax instead: https://github.com/Matt-Esch/virtual-dom, https://github.com/livoras/simple-virtual-dom

To put it in a nutshell, now that we can, we should keep the array syntax because it's better and we should throw away the variadic syntax. This will prevent the whole js community to keep that old bad syntax as a backwards compatibility. Javascript is already holding a lot of that, so I think it's better not to add that as well to libs while we can

**Comment by notoriousb1t** [comment]
What are the arguments against variardic?  Other than being ugly, I don't know of any issues using that syntax, whereas array style I know would take a hit in garbage collection after repeated calls.  That is, creating an array every time render is called would have an adverse (but probably marginal) effect on performance in a very large application.

I'm trying to understand your position better, since I am suggesting adding an additional signature, not replacing the existing behavior.

**Comment by posva** [comment]
>  I know would take a hit in garbage collection after repeated calls. That is, creating an array every time render is called would have an adverse (but probably marginal) effect on performance in a very large application

I'd love to see some numbers on that

> I'm trying to understand your position better, since I am suggesting adding an additional signature, not replacing the existing behavior

I see that. What I'm trying to do is to understand what is better, and the array syntax is simpler and more straightforward because of 3 args vs N args. My idea is that we should try to push only one syntax forward and adapt onto that one. Keeping backwards compatibility with the other one is up to the libs using it, but I think it should be avoided as much as possible because JS is full of backward compatibility things

**Comment by notoriousb1t** [comment]
The part I don't understand is the notion that using variardic is somehow old and deprecated by the JS community as a whole.  The fact that React is still using it tells me otherwise.  Treating it as backward compatible implies such.  My understanding at this point in time is that they are alternative syntaxes, both valid in their own right.

That being said, I will put in an issue with TypeScript to see if they will add support for that for JSX.  Do you know of any other significant libraries that use three arg syntax for render outside of what is listed above?

As an aside I did run numbers on three arg vs variardic, and I was surprised by the results.  Chrome consistently runs slightly better with three arg.  Everything else I tested gave me mixed results (Safari, FireFox, Safari Mobile).  In very naive cases (numeric arrays), three-arg was always better

https://jsperf.com/args-vs-array-for-render/1

**Comment by posva** [comment]
> The part I don't understand is the notion that using variardic is somehow old and deprecated by the JS community as a whole

No, I didn't said that, sorry if it looked like it. It's because the array syntax is better that we should deprecate the other one and use the array one everywhere.

About other libraries, I simply googled virtual dom github and all libs I looked from top results had the array syntax

**Comment by druppy** [comment]
It the array syntax also more type script friendly, it we want typescript to help us validate the structure ?

**Comment by notoriousb1t** [comment]
TypeScript is capable of type-checking either equally, so that isn't a concern.

Looking at those two examples and Vue, they have unique APIs.  That is, there is nothing standardized between the three.  Compare that to React, Inferno, etc.  They are more or less drop-ins. 😦

**Comment by posva** [comment]
the 2nd argument differs from one impl to another, but the first is always the tag while the 3rd is an array of children

**Comment by rayrutjes** [comment]
Using Rollup with Buble, it took me some debugging time to realize that the transpiled JSX did not meet the createElement signature.

What is the conclusion here, and what do we need to move forward?

**Comment by Nasdan** [comment]
Other approach could be this one:

- Instead of using TSX transpiler, lets `preserve` or keep the JSX as output to be consumed by e.g. [`babel`](https://babeljs.io/):

### ./tsconfig.json
```diff
{
  "compilerOptions": {
    ...
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
-   "jsx": "react",
-   "jsxFactory": "h"
+   "jsx": "preserve"
  },
  ...
}

```

- Now, we can use [`babel-plugin-transform-vue-jsx`](https://github.com/vuejs/babel-plugin-transform-vue-jsx#usage) to transpile `jsx`.

- For example, if you use [`webpack`](https://github.com/webpack/webpack), you can install [`awesome-typescript-loader`](https://github.com/s-panferov/awesome-typescript-loader) and transpile `.ts/.tsx` to ES6 using `TypeScript` and ES6 `.js/.jsx` to ES5 using [`babel`](https://babeljs.io/) :

### ./tsconfig.json
```diff
{
  "compilerOptions": {
+   "target": "es6",
+   "module": "es6",
+   "moduleResolution": "node",
    "declaration": false,
    "noImplicitAny": false,
    "sourceMap": true,
    "noLib": false,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
-   "jsx": "react",
-   "jsxFactory": "h"
+   "jsx": "preserve"
  },
  ...
}

```

### ./.babelrc
```javascript
{
  "presets": [
    "env"
  ],
  "plugins": [
    "transform-vue-jsx"
  ]
}

```

### ./webpack.config.js
```diff
...

  resolve: {
    extensions: ['.js', '.ts', '.tsx'],
  },
  entry: {
    app: './main.tsx',
    vendor: [
      'vue',
    ],
  },

  ...

  module: {
    rules: [
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'awesome-typescript-loader',
          options: {
+           useBabel: true,
          },
        },
      },
  ...

```

We have some samples working with that in [Lemoncode/vuejs-by-sample](https://github.com/Lemoncode/vuejs-by-sample) repository.
In particular, the previous configuration is in [Lemoncode/vuejs-by-sample/03 Render](https://github.com/Lemoncode/vuejs-by-sample/tree/master/03%20Render) sample and it's explained step by step.

**Comment by notoriousb1t** [comment]
I think it would be better if TypeScript + VueJS could work together directly, but I'm currently happy with using the babel jsx plugin and the vue-class-component packages.  It does seem like a lot of toolchain for the job, but it appears to work with no issues.

I've put together a starter project for single file components with those packages: https://github.com/notoriousb1t/vuejs-typestyle-seed

**Comment by Emeegeemee** [comment]
If your in the same position as me and can't use babel. I found that you are able to modify the $createElement property in the beforeCreated hook using a global plugin like so:

```typescript
const plugin = {
  install(vue) {
    vue.mixin(vue.extend({
      beforeCreate() {
        const originalCreateElement = this.$createElement;
        this.$createElement = (tag: any, data: any, ...children: any[]) =>
            originalCreateElement(tag, data, children);
      },
    }));
  },
};
```

**Comment by chanlito** [comment]
Hi, guys this might seems out of nowhere but can we write vue component inside a .tsx file?

**Comment by LinusBorg** [comment]
You're right it's coming out of nowhere. We have a forum and chat for questions.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
