### ISSUE TITLE
v-html not work in svg text tag on ios8.4 safari

### ISSUE THREAD

**Issue by jinphen** [vuejs/vue#5310]
### Version
2.1.8

### Reproduction link
[https://jsfiddle.net/czm8m265/](https://jsfiddle.net/czm8m265/)

### Steps to reproduce
use ios8.4 safari open the jsfiddle https://jsfiddle.net/czm8m265/

### What is expected?
v-html rending the message

### What is actually happening?
v-html not rending the message

**Comment by yyx990803** [comment]
Technically SVG is *not* HTML, it's only embedded inside HTML. Per the specs SVG doesn't actually support `innerHTML` - it works in some browsers (like desktop Chrome), but not all. I'd suggest avoid using `v-html` with SVG.

**Comment by dhavyd** [comment]
Hi! Thanks for this answer. I've running on the same problem, but on Microsoft Edge... What do you suggest if a need to create an SVG in "realtime" through VueJS, and then bind som HTML to it?

Ex:
`myVar = '20:00&nbsp;&nbsp;Some title'`
`<svg>`
`<text>{{myVar}}</text>`
`</svg>`

As it is today, `&nbsp;` will be escaped and visible in the page.

Since innerHtml isn't a part of SVG specs, as you pointed out, I'm forced to use brackets to insert my value. If it's possible to "turn off" the HTML escaping in some contexts, it should solve this issue. Is there a way to do that or what do you suggest I should do?
