### ISSUE TITLE
Improvement when used in nw.js multi window environment

### ISSUE THREAD

**Issue by kailniris** [vuejs/vue#5356]
### Version
2.2.6

### Reproduction link
[https://github.com/kailniris/vue-multi-window](https://github.com/kailniris/vue-multi-window)

### Steps to reproduce
1. clone repo
2. npm run dev
3. Start the app in nw.js sdk *
4. press the 'Open sub window button' some times to open new windows

step 3:
- Start the app in nw.js sdk
- download nw.js https://dl.nwjs.io/v0.21.4/nwjs-sdk-v0.21.4-win-x64.zip
- create a shortcut with this target C:\path\to\nw.exe C:\path\to\vue-multi-window\package
- after the main window loaded open devtools and start record allocation timeline

### What is expected?
No memory leak happens when a sub window is opened then closed.

### What is actually happening?
With every window the memory consumation is grown by 10mb aprox. A memory leak happens every time a window is opened and closed.

**Comment by kailniris** [comment]
![profile](https://cloud.githubusercontent.com/assets/19587188/24578762/ada0ccd0-16e7-11e7-9308-c7d0c48d9fe0.jpg)

profiling after 5 windows are opened and closed

**Comment by yyx990803** [comment]
Why do you think this is a Vue issue rather than a nw.js issue or problem in your implementation?

**Comment by kailniris** [comment]
I am trying to get a stable implementation for months. Nw.js does not produce memory leaks without this implementation. So I tough maybe Vue does not remove deps from the observer when the instance is destroyed and this way the gc can't remove the window. If you have any suggestion i will change the implementation.

Also I noticed when a global state is not observed by the vm in the sub window the window after closed can be properly gc-d.

**Comment by nicmitchell** [comment]
When you say "NW.js does not produce memory leads without this implementation", have you tried using a different view framework to rule out it being an NW.js issue?

I worked on a team using NW.js for over a year and we struggled with memory leaks and performance issues using Backbone on a regular basis. New windows exacerbate the problem significantly.

**Comment by kailniris** [comment]
Before Vue I used a framework-less solution so I can't answer this part of the question. What I ment was without Vue I did not experienced any memory leaks. I wrote a test case where I open and close windows constantly but no memory leak happened. Even if i use Vue in windows without global state or using multiple instances in the same window with the same global state from the same window the memory leak won't happen. The memory leak only happens when global state from other window is used.
I tried to figure it out what could be a problem but I am not familiar with Vue internals. That's why I am asking for help here because I really like to use this feature.

**Comment by rogerwang** [comment]
@nicmitchell using a different view framework doesn't rule it out. The real root cause should be pinpointed by looking into the JS object references with devtools and find out why the references are held.

There may be integration issues between other JS frameworks with NW too. NW apps works in a [multi-context environment](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/) by default, which is different from what one could expect from browser, which is single context and objects don't refer to each other between them. This can trigger issues in applications or frameworks especially when navigation or window opening is involved, as the context in the background page is living as long as the app doesn't quit.

Besides the default mode, NW provides a 'mixed context' mode which work in the same way as browsers. It is recommended for people who find multi context mode is hard and there is no real benefit from the background page in their usage scenario.

**Comment by kailniris** [comment]
Let me close this issue. This is a niche case and a bad practice anyway.
