### ISSUE TITLE
VDom throwing error during $destroy if root node was replaced

### ISSUE THREAD

**Issue by FranzSkuffka** [vuejs/vue#5519]
### Version
2.2.6

### Reproduction link
[https://github.com/FranzSkuffka/vue-medium-editor/blob/playground/src/App.vue](https://github.com/FranzSkuffka/vue-medium-editor/blob/playground/src/App.vue)

### Steps to reproduce
1. create component as in https://github.com/FranzSkuffka/vue-medium-editor/blob/master/vue-medium-editor.js#L39 - note that the original root element is replaced.
2. tear down component using v-if as in https://github.com/FranzSkuffka/vue-medium-editor/blob/playground/src/App.vue

### What is expected?
The component is destroyed without errors.

### What is actually happening?
The component throws the error:
`DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

And the rest of the teardown process is interrupted, leading, among other problems, to the component still living and still-attached event listeners.

---
The vue-medium-editor plugin requires a runtime-custom tag at the root of the component in order to function properly. The users would like to use custom elements which can either display is block, inline or inline-block elements. The layout for inline-elements break if we use a simple div as a wrapper.

I tried the following approaches without success
- replace the new element with the original element
- overwrite the $destroy hook
- Use earlier hooks to insert the the element before mounting
- replace the tag name in the template string during runtime

Halp!

**Comment by yyx990803** [comment]
This is expected behavior. You should not tamper with the DOM generated by Vue, especially the root element.

For your use case, use a render function instead of template:

``` js
render (h) {
  return h(this.customTag || 'div', {
    domProps: {
      innerHTML: this.text
    }
  })
}
```

**Comment by onlyurei** [comment]
@FranzSkuffka @yyx990803 I encountered a very similar problem when using Vue to [wrap](https://github.com/xkjyeah/vue-google-maps/issues/39) the [Google Maps OverlayView](https://developers.google.com/maps/documentation/javascript/examples/overlay-simple) elements. 

Initially I didn't set the `:key` attribute on the wrapping node (used with `v-for`), and the OverlayView DOM nodes on the rendered Google Map randomly and wrongly got re-rendered when the underlying observed array changed (new items pushed, existing items' own array got new items pushed).

Then I realized I need to set a `:key` to help Vue map the DOM nodes to the data array. I first tried to use a `String` type uuid of each item as the value for the `:key`, then I encountered the same error this issue mentioned. The situation is similar because the mounted DOM node for this wrapper component got "tampered" as required by the Google Maps API, specifically the root node's `position` style property is changed to `absolute`, and `left` and `top` changed to the appropriate ones for them to display on the map correctly based on the item's `lat` and `lng`.

Then I changed to use a POJO `{ location: { lat: <Number>, lng: <Number> } }` as the value for the `:key`, both issues are solved: DOM nodes are updated correctly with underlying array change, and no longer seeing the exception mentioned in this issue `DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`.

I guess because the `:key` is a POJO, which is an instance of Object, that's not passed around by value (initially I used String), but by reference, helped to work around the issue?

**Comment by FranzSkuffka** [comment]
Thank you for the bump. Actually, my issue was super easy to resolve. But currently I am tackling a similar issue so your information might be valuable.

**Comment by onlyurei** [comment]
Now it throws "**vue.common.js:462 [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.**" warning in[ v2.4.1](https://github.com/vuejs/vue/releases/tag/v2.4.1).

**Comment by FranzSkuffka** [comment]
hhmmmm

**Comment by xiaomingdexian** [comment]
@onlyurei Hello , I met the same issue with you on Baidu Map.And may I ask you how you resolve it now?
I mean how can make it no warning.
