### ISSUE TITLE
Binding length of one object from $data to another object

### ISSUE THREAD

**Issue by sumitridhal** [vuejs/vue#5550]
### Version
2.1.10

### Reproduction link
[https://codepen.io/sumitridhal/pen/JNWWvW?editors=1010](https://codepen.io/sumitridhal/pen/JNWWvW?editors=1010)

### Steps to reproduce
1. open codepen link
2. check console.log
3. change `this.options.availableOptions[3].value`

### What is expected?
While creating custom select input and binding the last value to items object in data.

```html
 <select class="form-control xsmall" v-
model="options.limit.value">
  <option v-for="option in options.availableOptions" v-bind:value="option.value">
    {{ option.name }}
  </option>
</select>
```

the object in options array 
```
{
          id: "4",
          name: "All",
          value: null
        }
```
should bound to length of items.

```
var app = new Vue({
  // app initial state
  data: {
    title: "VueJS 2.1x CURD Application",
    items: v_items,
    
    options: {
      availableOptions: [
        {
          id: "1",
          name: "5",
          value: 5
        },
        {
          id: "2",
          name: "10",
          value: 10
        },
        {
          id: "3",
          name: "15",
          value: 15
        },
        {
          id: "4",
          name: "All",
          value: null
        }
      ],
      limit: {
        id: "1",
        name: "5",
        value: 5
      } //This sets the default value of the select in the ui
    }
  }
})
```

### What is actually happening?
Uncaught TypeError: Cannot read property 'length' of undefined

---
the value for ``` { id: "4", name: "All",  value: null }``` should always bind with items length

**Comment by sumitridhal** [comment]
Can't use 
```
{
          id: "4",
          name: "All",
          value: this.items.length
        }
```

**Comment by sumitridhal** [comment]
mounted function can bind data for single time but not while keep on adding data into items object
```
//mounted
  mounted : function(){
        let self = this;
        let itemSize = self.items.length;
        self.options.availableOptions[3].value = itemSize;
  }
```

**Comment by posva** [comment]
Thank you for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org), [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there. Come back open a new issue if you find out there's a real issue
