### ISSUE TITLE
ssr error instanceof Error is false

### ISSUE THREAD

**Issue by lonelyclick** [vuejs/vue#5570]
### Version
2.3.0

### Reproduction link
[https://jsbin.com/hisubahepa/1/edit?html,js,output](https://jsbin.com/hisubahepa/1/edit?html,js,output)

### Steps to reproduce
I use vue-server-render, found out vm.runNewContext result: `error instanceof is Error === false`

Then cause koa error，https://github.com/koajs/koa/blob/master/lib/context.js#L107 

I think we should add Error at: https://github.com/vuejs/vue/blob/dev/src/server/bundle-renderer/create-bundle-runner.js#L18

### What is expected?
`error instanceof Error === true`

### What is actually happening?
`error instanceof Error === false`

**Comment by HerringtonDarkholme** [comment]
This is a known behavior in SSR. You can turn off `runInNewContext` to correct this. (Personally I recommend to do so for any non-trivial project for performance.)

Please refer to official SSR guide. https://ssr.vuejs.org/en/bundle-renderer.html

I wonder whether the fix is appropriate. Since patching builtin will never be enough until we copy the whole context. But this breaks our original point for `runInNewContext`.

**Comment by lonelyclick** [comment]
@HerringtonDarkholme 
In my case, `runInNewContext` is `false`, The real problem is that the vm.runInnewContext output of the `Error` is a different thing, just like `iframe.window.arr instanceof Array === false`

**Comment by yyx990803** [comment]
@lonelyclick this will be fixed in the next version by using `runInThisContext` instead with `runInNewContext: false`. The current 2.3.0 behavior (evaluate the bundle once in a separate context) will be available under `runInNewContext: 'once'`.

**Comment by HerringtonDarkholme** [comment]
`runInThisContext` is significantly faster! Looking forward to the new release!
