### ISSUE TITLE
iPad/iPhone crashing on the big page

### ISSUE THREAD

**Issue by bububo** [vuejs/vue#5613]
### Version
2.3.2

### Reproduction link
[https://codepen.io/Bububo/full/qmPPOE](https://codepen.io/Bububo/full/qmPPOE)

### Steps to reproduce
iPhone 6 plus and iPad 3 are crashing on the big pages. iPhone 6s and iPad air 2 work ok.
I see this issue if I use a following javascript and div#app contains about 3000 DOM nodes or more.

```
new Vue({
	data() {
		return {
			test: 'test',
		}
	},
	

}).$mount('#app');
```

### What is expected?
The user can see the page.

### What is actually happening?
Crash. Message: A problem repeatedly occured on  {url}

---
iPhone 6s and iPad air 2 work ok.

**Comment by posva** [comment]
It worked fine when I tested on the simulator (this kind of errors should also appear on the simulator)... Vue didn't even seem to have an impact on the speed of the page. If you manage to have a js stack trace from safari we may have a look but it looks like something related to your device
For big amount of content, you may want to use something like  https://github.com/Akryum/vue-virtual-scroller But It doesn't look like the error you have

**Comment by bububo** [comment]
@posva 
It is crashing on the simulator also. I've tested on www.browserstack.com (iphone 6s safari)
Screenshot http://prntscr.com/f4dlt7

**Comment by panuchka** [comment]
We are having this issue as well on one site with (at least) iPad model A1416. It's really hard to debug since the dev tools also crash. I can reproduce the problem with the codepen example provided by @bububo using the latest Vue version.

I reckon the problem lies when Vue hooks to the dom. On another website it barely works and Vue takes almost 30 seconds to initialize on the iPad. I'm afraid that with a couple more components introduced to the page it too will crash.

Can you please reopen this issue and investigate? @posva

**Comment by ermand** [comment]
Hi, we are having the same issue with Vue in the pages where we have a lot of components rendered, such as a list of `<product></product>`. It works fine on some phones and on some others it throws this error. I can reproduce it via Browserstack anytime. Here is a printscreen
<img width="349" alt="image" src="https://user-images.githubusercontent.com/2822729/31457704-da480ffa-aebd-11e7-9d3d-bfeeaf13293b.png">

@posva Can you please reopen this issue? 
Thanks in advance

**Comment by ermand** [comment]
I have found the issue in our case, seems to be `inline-template`. After we moved the template into the `.vue` file, everything works fine now :)
