### ISSUE TITLE
npm update is not working.

### ISSUE THREAD

**Issue by bramu** [vuejs/vue#5705]
Hello,

How to upgrade from vue2.2 to vue 2.3 I am trying to do npm update and all but package.json is not updated. Is it something I have to edit manually? I hope there is something npm update --save. Can someone please help me with this?

**Comment by Atinux** [comment]
Hi @bramu 

It depends how you specified `vue` dependency in your `package.json`.

See https://docs.npmjs.com/cli/update

You can update it manually in your package.json and then run `npm install`.

I recommend you to use https://yarnpkg.com/lang/en/ or https://www.npmjs.com/package/npm-check-updates

**Comment by LinusBorg** [comment]
Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
