### ISSUE TITLE
Watch conflicts

### ISSUE THREAD

**Issue by shenron** [vuejs/vue#5740]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/nf4fv4on/](https://jsfiddle.net/nf4fv4on/)

### Steps to reproduce
When a component is declared, if there are two array (one in props and an other in data) the change of one emit change of all.

- If I push something in the array in data :
https://jsfiddle.net/nf4fv4on/

- If I push nothing it works
https://jsfiddle.net/nf4fv4on/1/

### What is expected?
The users props parameters is never updated, so no `watch` event should be catch.

### What is actually happening?
The users props parameters emit a change.

**Comment by maiff** [comment]
This is my [changing](https://jsfiddle.net/nf4fv4on/4/). I attach a name to props that named users. and everything goes right.But I don't the reason.

**Comment by shenron** [comment]
Thank you ! It's a quick fix for the moment.

**Comment by yyx990803** [comment]
To understand this you need to first understand how Vue 2 performs updates: templates are first compiled into render functions, and render functions are called every time the component is updated.

Now since you are using an inline literal as a prop value (`:users="['Bulma1', 'Goten1']"`), a new literal Array will be created every time the parent component re-renders. And this causes the prop watcher to fire every time, too.

The solution is avoid using inline literals but use a constant value instead: https://jsfiddle.net/nf4fv4on/5/

**Comment by shenron** [comment]
OK, thank you for these explanations.
