### ISSUE TITLE
binding on select option change not working

### ISSUE THREAD

**Issue by jpvoisin** [vuejs/vue#5750]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/duvguoyy/1/](https://jsfiddle.net/duvguoyy/1/)

### Steps to reproduce
Select an Aircon Brand, you can see that the `<pre/>` tag I've made to check all the values of my datas: 			form_submissions, hasn't been updated as expected.

But when you just focus in and focus out the input number bellow the Aircon Brand: Area, the select has been bind, and my `<pre/>` has been populated.

It's making the same for my children selects.

### What is expected?
When I change a value from a select box with a `v-model="arr[index]"`, it should be binded by vuejs.

### What is actually happening?
It's working only after I've focus in and focus out an input text (or number), it should work whenever I change a value on a select box.

**Comment by yyx990803** [comment]
The current behavior is that `v-model` does not create reactive fields that do not exist for you, so although the value is being set, they don't trigger updates. The design encourages you to declare your model fields upfront instead of using an empty object.

However when using dynamic path segments in the binding it seems impractical to declare the fields beforehand, so I've added a patch that makes your code work in d333a49.

That said, it seems better to use an Array for `form_submissions` here (which already works in current version).
