### ISSUE TITLE
Missing named slots in children components of functional component

### ISSUE THREAD

**Issue by YunSun-CN** [vuejs/vue#5759]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/xpzybupo/](https://jsfiddle.net/xpzybupo/)

### Steps to reproduce
You can see the console for details.

### What is expected?
Named slots should be accessible from children components of functional component.

### What is actually happening?
this.$slots only show the default slot and missing other named slots.

**Comment by yyx990803** [comment]
This is actually intended behavior, because name slots resolution follows a rule: they only work if the children nodes and the parent component node are created in the same rendering context.

In your case, `children` are created in the context of the root instance, and `MessageComponent` is created in the context of the functional component, so the slot names are ignored.

There's one hack to work around this: use the root instance's `$createElement` to create `MessageComponent` instead, so that it is in the same rendering context with the `children` nodes: https://jsfiddle.net/xpzybupo/1/
