### ISSUE TITLE
One-way data flow might be broken

### ISSUE THREAD

**Issue by theosherman** [vuejs/vue#5799]
### Version
2.3.3

### Reproduction link
[https://jsfiddle.net/mhfcrgqv/2/](https://jsfiddle.net/mhfcrgqv/2/)

### Steps to reproduce
Pass an object (not a regular string or int property) as a prop to a child component. Mutate the properties of the object inside the child component. The mutations will also occur in the parent component. Check out the fiddle.

### What is expected?
The properties inside the form object should not get mutated in the parent component. It should only get mutated in the child component for a one-way data flow.

### What is actually happening?
The contents inside the parent object get mutated.

---
This issue may be intentional - I hope it is because I like the two-way flexibility - my apologies for reporting this if it is.

**Comment by LinusBorg** [comment]
This is expected behaviour and documented in our guide.

It's not so much intentional (in the sense that we would want to allow that "two-way flexibility) as inevitable.

Otherwise we would have to clone each object passed through a prop which would come with a host of new problems, like performance and memory impacts.
