### ISSUE TITLE
Deleting element from Array used as an associative array

### ISSUE THREAD

**Issue by unrealwill** [vuejs/vue#5855]
### What problem does this feature solve?
I'm trying to remove an element from a sparse array.   
arr[  23 (elt1.id) ] = elt1
arr[  55 (elt2.id) ] = elt2
arr[  74 (elt3.id) ] = elt3

If I try a Vue.delete( arr, elt2.id ) it offsets all following elts by one. I tried splice( elt2.id,1,undefined) but then I have an undefined element in my array when I iterate it with Object.values. From what I've gathered across the web there seemed to be a $remove function in previous versions, but I can't find it anymore.

Currently I'm forced to use an object ( {} ) instead of a sparse array, but it incurs performance penalties.

### What does the proposed API look like?
I think you should target exact match with the JavaScript specification of the behaviors of arrays and objects.

Thank you.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Use splice without the 3rd argument to remove an element

**Comment by unrealwill** [comment]
Hi posva, thanks for your quick response. The behavior of splice without the 3rd argument is not the behaviour I'm looking for, because it offset all the following indices and breaks the "associative array". 
I feel the behaviour is non intuitive, as it is not in-line with Javascript specification of sparse arrays. 

Specifically I'm requesting the myarray.$remove  feature which seemed to be there in the past, which allows to remove an element at an index from an array without disturbing the other indices, and without introducing an "undefined" in the array that we will have to iterate over later on.

**Comment by posva** [comment]
aah, in that case use `Vue.delete` https://vuejs.org/v2/api/#Vue-delete

**Comment by unrealwill** [comment]
Sorry, I tried it already, but it offsets the indices of the following elements.
I don't mean to bother you, but I think this is an edge case which is not currently elegantly solved.
Currently for my associative array I have to use an object (instead of array) with Vue.set and Vue.delete. 
But it should work with an array, if Vue implements a method mimicking the behaviour of what in javascript is defined by :   "delete array[index]"
There are probably cases like a sparse array where the order of keys matter, where using an object won't do the trick. 
You can see more of the subtlety of what I'm talking about in : 
https://stackoverflow.com/questions/27598340/how-should-i-iterate-over-a-sparse-array-in-index-order

**Comment by posva** [comment]
I tested adding it with `Vue.set` and `Vue.delete` and it template using it gets updated twice with the corresponding value.
If you need further help, please use the forums or gitter to post further questions
BTW an associative array should be an object in js... You're complicating your life

**Comment by unrealwill** [comment]
I don't need further help.

You probably tested it wrongly : From my example remove elt2 then try to access elt3 by its Id.

I'm just reporting what I consider either a bug or a missing feature depending on your intent as a library designer. (I won't be bothering you anymore, as I've already lost enough time)

The semantics for Array Vue.js implements is different than the semantics of javascript Array.
It probably won't cost you much to implement it up to javascript specs. (->do a delete when the user ask for a delete, and do a splice when the user ask for a splice).

"BTW an associative array should be an object in js..."-> Not when you need to be able to iterate in key order, and care about non-quadratic performance.  
Javascript array is like a std::map, Javascript object is like a std::unordered_map. (If you don't get this please get it up the chain to someone who does).

Thank you again for your time.

**Comment by posva** [comment]
then provide a jsfiddle with a repro and I can look at it

**Comment by yyx990803** [comment]
FYI there's very little point in using sparse Arrays in JS. To ensure enumeration order you need to keep a copy of the indices anyway, so the iteration speed is the same - the only difference is get/set. You might think it's faster than an object but... always run a benchmark instead of making assumptions. https://jsperf.com/sparse-objects

**Comment by unrealwill** [comment]
Hi, @yyx990803 , sparse Arrays guarantees order. Objects don't. That is an important distinct primitive that we sometimes need. Currently I've encountered the problem while doing some agents simulation. At every timestep of the simulation agents some agents are born (I store them in a sparse array with incrementing Id), and some other agents dies (and I remove them from the structure of living agents). With sparse arrays, these operations, are O(log(Nremainingagents) ). If I use objects, I "lose" the information about the order in which the agents were created. If I use dense arrays, my remove operations become O(N) making simulation step quadratic.

It's not an insurmountable problem, as I can work with a sparse js array (added to data after Vue constructor so that Vue don't get control of it) and keep a Vue copy in sync with it via an object mapping, it's just inelegant as it's kind of against the point of using Vue.

I get that sparse array is probably a feature most developers won't use, so it may be useful to simplify the life of the new users by breaking the somewhat hard to understand semantics of Javascript arrays. But, you probably could be more faithful to Javascript specs, inexperienced users won't see the difference, and more advanced users will get expected behaviour.

Thank you for your time.

**Comment by yyx990803** [comment]
The SO answer you linked to, and the MDN article it links to, already stated that the spec does not guarantee enumeration order with `for...in` on sparse Arrays - while some engines do, if it's not part of the spec then it's just wrong to rely on it. The proper way to deal with it is keeping an extra Array containing the ordered keys, and if you do that, you can use an Object.

Also, it's usually inaccurate to reason about JS performance with big O notations, because it has so much to do with how the underlying engine decides to implement/optimize different cases. I am pretty sure a sparse Array leads to de-opt and wouldn't be as performant as you think it is.

**Comment by unrealwill** [comment]
That's why in the SO answer I linked to, they tell about ".forEach" (which is implemented almost everywhere).

>"The proper way to deal with it is keeping an extra Array containing the ordered keys"
Nope (because then each in the middle modification would lead to quadratic behaviour), the proper way is to use a tree as the underlying data structure (which is what js array is).

JavaScript specs have been written so that developer can enjoy the minimal useful primitives to code efficiently. Tree Maps and Hash Maps are two useful distinct beasts, which are algorithmically very different. It is somewhat natural to give access to them to the programmer. Decent Browser engines implementation are forced into using the right primitive, because otherwise they wouldn't match the specs, or would have piss poor performance. Then they do optimizations to have bigger numbers than the next guy. 

JavaScript today is not as bad as it once was in part because browser implementers decided to respect the underlying theory. Vue.js is great but please don't drag us down in the mud again by removing the constructs which would allow us to rise.

**Comment by yyx990803** [comment]
1. `forEach` will be slower than a manual `for` loop + direct key access from an object, due to the additional checks per the spec plus the cost of invoking the iterator function for each item... given that you care about performance, you should avoid using it - and that also defeats the point of using a sparse array.

2. Sparse arrays will not work properly when used with `v-for`, because we use raw for loops to iterate over data, not `forEach`. Each empty item will still render a `v-for` block. It's unlikely for us to change this behavior because it's technically breaking and will lead to performance regressions.

3. It makes sense to make `Vue.delete` behave like native `delete` on Arrays, and have a separate method for the index-modifying behavior that it currently has. However, this is a breaking change, and so far I don't think the use case and the argument behind it is strong enough to warrant a breaking change.

So - the change you want will most likely not happen, and my suggestion is keep using an object instead. Also, I strongly suggest actually benchmarking your app before assuming the object will be slower than a sparse array - you may have strong algorithmic intuitions, but in JS land... benchmarking is the only way to find out the truth.

**Comment by unrealwill** [comment]
OK, no problem. Thanks for the advices.
