### ISSUE TITLE
please unreserve underscore, and allow it for user usage

### ISSUE THREAD

**Issue by xlotlu** [vuejs/vue#5879]
### Version
2.3.4

---
I have been a developer for many years, and I, as many others, have been using underscore-starting variables and functions to convey special meaning: this is somehow restricted / it's temporary / it's for internal use / it's the real implementation and the other one is a wrapper etc.

Taking away this ability is unnecessary, it is handicapping developers, *and* opens the door for bugs. I was bitten by Vue's handling of `_` properties a long time ago and had to do the same googling many others have done before me. But what prompted me to submit this issue is I just created a `_render` method: given that I was renaming a method that was already used in a few places, combine this with some other edits before and after the rename, the outcome was, as you can imagine, a long and frustrating session of debugging.

I propose underscore should be cleared for regular usage by users. This could be really simple, like renaming the internal stuff to start with `$_` instead, or namespacing everything under something like `this.$` (but I presume that would require some serious code shuffling).

**Comment by nickmessing** [comment]
Properties prefixed by `_` and `$` are historically used internally by vue. I don't think there is enough reasoning to change that.

**Comment by LinusBorg** [comment]
I don't think that it makes much sense to define methods etc in components as "internal", because generally, *all* of them should be considered internal - the public API of a component is defined by its props and events.

While you *can* access methods or data of a component programmatically through e.g. a `$ref`, that's something that's rarel happening.

**Comment by posva** [comment]
accessing methods does happens happens but trying to hide properties from the user by just prepending `_` or `$` is an illusion

**Comment by xlotlu** [comment]
Yes, `_` and `$` are used internally, but there's a huge difference between them: `$` provides a useful, documented, public API, while `_` provides bug-prone unexpected behaviour.

(Yes, it's true the unexpected part is "somewhat documented", but nobody tells you "no, really, don't use underscores for anything, unless you like pain.")

My argument is simple, and frankly seems very compelling to me as a newcomer:
- `_` is bug-prone. People will shoot themselves in the foot due to the unexpected behaviour. There's many issues in this here tracker proving that (though I think my `_render()`-related experience is the worst yet).
- seasoned developers love `_`. Don't alienate them.
- `_` is unnecessary. Getting rid of it is one simple search & replace away.

**Comment by yyx990803** [comment]
This is unlikely to happen because this almost certainly will break someone's existing code, and the gain is arguable.

What we **can** do is raise warnings when users declare data/props/computed/methods that start with `_`. I'd be open to a PR for that.

**Comment by Flamenco** [comment]
I am probably going to get an ass whippin' for suggesting this, but **I would like to see a refactoring of __ and $$ instead of _ and $ internally in the next major version of Vue**.   Sure they are ugly, but they are internal and _I_ won't have to see them.

Two _very common_ javascript conventions reserved internally?  That does not seem to have been the best choice.  

I can live with losing the '$', but not the _ .  Perhaps consider converting the internal '_' to '$$' or '__'.?

IDK ¯\_(ツ)_/¯

**Comment by douglasg14b** [comment]
This naming reservation is a pain when using languages like TypeScript where the common syntax for a member variable backing getters/setters starts with an underscore.

This just sounds like Vue getting in the way of languages, when it is unnecessary and solvable by vue reserving double underscores, or just `$`

**Comment by jartaud** [comment]
I just learn that the hard way.

**Comment by vertic4l** [comment]
Another reason why Vue just sucks :D

**Comment by xlotlu** [comment]
> Another reason why Vue just sucks :D

@vertic4l, c'mon, that is neither helpful nor accurate.

Vue is a beautiful piece of engineering, with a few shortcomings. Which is to be expected, everything has shortcomings.

What's unconstructive though (and if there's something that qualifies for the expression you used I'd say this is it) is the attitude "if I don't find it helpful, then it can't be to others".

Pair that with logic of the sort "this is internal and undocumented so don't use it, but we can't change it because someone might rely on it.", and you have a recipe for frustration.

Projects that care about their users don't mind re-architecting, and have a deprecation strategy such that they warn clients of their API of oncoming changes. But then, that's not to be found here.

**Comment by timbyu** [comment]
As was stated many professional developers have come to use _ (underscore) as a prefix for special cases (Even the developers of Vue found it useful for their purposes!)  It is one of two non alpha characters that can be used to start a variable name, $ being the other and is also take by Vue! 
 
A simple case to demonstrate is to have a prop of something like "searchTerm".  In order to do a .sync I will often have a local variable that receives that props value and then will emit the value as the local variable changes.  Since "searchTerm" is a good descriptive name for the prop and since I can't reuse that name for my local variable I need a prefix.  _ is a simple perfect match.  "_searchTerm" is easy to recognize as being related to searchTerm and makes my code readable.  Again, the underlying language does not allow for other single prefix characters and Vue is taking away the one that should be available.  On the Vue side, simply changing the reserved _ (underscore) to __ (double underscore) would still be simple, concise and not collide with THE SINGLE REMAINING PREFIX WE HAVE AVAILABLE TO US.  Vue 3.0 would be a good place to give underscore back the people (us developers)

**Comment by douglasg14b** [comment]
Really just needs another open issue at this point, because the decision to maintain this is some serious quality oversight...

**Comment by StrangeWill** [comment]
What would be handy: if we _declare_ variables with underscores warnings get thrown.

Had some people on my team caught with this, it isn't immediately intuitive and nothing gives feedback as this being inappropriate (vue-cli, eslint, etc.), I get the reasoning but it would be good to provide a bit better feedback for the developer against this behavior when defining variables we expect to show up under `this._thing` don't.

**Comment by 9mm** [comment]
@vertic4l not what you suck

**Comment by vertic4l** [comment]
> @vertic4l not what you suck

Creative! So you are the bottom of the shitheads.

See you all in some years regreting your chosen path.

**Comment by 9mm** [comment]
Whatever you say Mr. Lindner

![image](https://user-images.githubusercontent.com/1386207/110185132-6c5d9100-7dc6-11eb-9978-0e7bdfe7d786.png)

**Comment by vertic4l** [comment]
You that this is against law and can be charged in real Life?
