### ISSUE TITLE
Is there a way to set current runtime is server? (Or do not only rely on checking "typeof window !== 'undefined'")

### ISSUE THREAD

**Issue by TanMichael** [vuejs/vue#5882]
### What problem does this feature solve?
I want to try Vue SSR with a custom node framework which simulated the global variable "window" in its runtime, but no "navigator" property in this window.
Error occurs while requiring Vue, because of the code in vue.runtime.common.js line 535-536:

// Browser environment sniffing
var inBrowser = typeof window !== 'undefined';
var UA = inBrowser && window.navigator.userAgent.toLowerCase();

I can add the code like "window.navigator = { userAgent: 'all' };" as workaround. But I think Vue runtime will consider running in browser, there should be many side effects with SSR.

If there is a global config that could set runtime environment and skip to checking "typeof window !== 'undefined'", that would be great!

Thanks!

### What does the proposed API look like?
Maybe another way to detect environment
https://stackoverflow.com/a/31090240

**Comment by yyx990803** [comment]
Technically, I think it's very problematic for the framework you are using to simulate `window` but not providing the necessary keys. This would break a lot of code that expects to be run universally by checking environments. Could you share more details on that?

As for how to detect a browser environment - it is intentional to use a simple check because we do want to use the in-browser behavior when Vue is used inside Node + JSDOM.

**Comment by TanMichael** [comment]
Hi yyx990803,

Thanks for your quick reply!

I've contacted with the owner of the custom framework today. They will introduce their framework in depth and explain the reason why they use "window" object this way several days later.
So I will provide more details after that.

**Comment by TanMichael** [comment]
Hi yyx990803,

I have discussed with the guy from the custom framework team. They use that framework for server rendering their own web pages which contain too many window variables. This might be a problem left over by history. In order to reuse their old code which runs in browser before, they simulate `window` in their node framework.
And they also met our problem while they were trying to use Vue SSR. Their solution is to modify the code of Vue locally.

I know it is not a strong reason for you to fix this point. Maybe I have to accept their solution or just give up their framework.

**Comment by mrliptontea** [comment]
@TanMichael Another option might be to wrap Vue module, store your `window` object in a temporary variable, assign `undefined` to `window`, require Vue, restore `window`.

This could work because `inBrowser` is assigned on the top level scope when Vue is imported for the first time. But be aware that this is an internal framework's variable, so it can be moved and this behaviour change anytime.

To be more precise, something like this:

Create `./vue.js` file as follows:
```js
const windowCopy = window;
window = undefined;
const Vue = require('vue');
window = windowCopy;

module.exports = Vue;
```

And then instead of importing/requiring `'vue'` from `node_modules` directly, use your `'./vue.js'`

**Comment by yyx990803** [comment]
Closing due to lack of actionable items.

**Comment by mapleeit** [comment]
Hi, @yyx990803 , I understand the reason that you refuse to change the detect way. Simulating `window` but don't providing the necessary properties is very problematic. 

But I still think the code below is more robust than what it is now. It can always detect the right env no matter what variables users simulate. There always are special ones who do not follow the rule. A great framework should be tolerant.

```javascript
    const inBrowser = (() => {
        try {
            return this === window
        } catch(e) {
            return false
        }
    })()
```
