### ISSUE TITLE
.proxy v-on modifier feature request

### ISSUE THREAD

**Issue by gbezyuk** [vuejs/vue#5935]
### What problem does this feature solve?
Sometimes you have a custom component emitting some events deep in the component hierarchy, while you want to listen for this events somewhere on top of the hierarchy. Consider a simple click over some element for instance. A native event would propagate, while Vue events don't. So for all the intermediate components between the event origin and the listening one, we may need to ensure event propagation manually, simply re-emitting the event with something like this code:
```js
on: { customEventName: (...args) => this.$emit('customEventName', ...args),
```
It's ugly and verbose and it's getting even uglier with templates.

### What does the proposed API look like?
Can we add a `proxy` modifier for `v-on`?
```vue
<ListeningComponent> <!-- @customEventName is received here -->
  <IntermediateComponent1 @customEventName.proxy>
    <IntermediateComponent2 @customEventName.proxy>
      <EmittingComponent/> <!-- @customEventName happens here -->
    </IntermediateComponent2>
  </IntermediateComponent1>
</ListeningComponent>
```

**Comment by posva** [comment]
This was present on v1 and intentionally removed in v2 because it couples the logic to your component hierarchy. We think that for arbitrary comp 2 comp communication you should either user vuex (https://github.com/vuejs/vuex/) or use a global event emitter bus by creating an empty `Vue` instance (this is in the docs).

While manually bubbling up events is possible in v2, we encourage people to use one of the solutions mentioned above
