### ISSUE TITLE
Why v-text didn't support filter ?

### ISSUE THREAD

**Issue by leupom** [vuejs/vue#5939]
### What problem does this feature solve?
Why can't use v-text="doSomething() | filter('args')" ?
Maybe the pipeline operator "|" ?

### What does the proposed API look like?
v-text="doSomething() | filter('args')"

**Comment by nickmessing** [comment]
Why not use `getters` when you can or just inline plain javascript otherwise? `v-text="filter(doSomething(), 'args')"`?
with:
```js
export default {
  methods: {
    doSomething () {...},
    filter () {...}
  }
}
```

**Comment by leupom** [comment]
@nickmessing I have registered filter in Vue.filter and don't want to repeat in a new Vue()

**Comment by nickmessing** [comment]
According to [docs](https://vuejs.org/v2/guide/syntax.html#Filters)
Vue 2.x filters can only be used inside mustache interpolations and v-bind expressions (the latter supported since 2.1.0), because filters are primarily designed for text transformation purposes. For more complex data transforms in other directives, you should use Computed properties instead

Considering that you want to pass some aditional arguments I think filters is not a good way to go.

I'd prefer:
```js
// filters.js
export myCoolFilter (text, arg1, arg2) => `${text} ${arg1} ${arg2}`
```
```html
<!-- Component.vue -->
<template>
  <div v-text="myComputed" />
</template>
<script>
  import { myCoolFilter } from './filters.js'

  export default {
    computed: {
      doSomething () {...},
      myComputed () {
        return myCoolFilter(this.doSomething, 'a', 'b')
      }
    }
  }
</script>
```

Filters are a pretty bad design decision IMO anywhere other than simple text processing like `uppercase`

**Comment by Nirazul** [comment]
You can access your filters in your component like that: `this.$options.filters.myCoolFilter`. So in `v-text` you could write: `<div v-text="$options.filters.myCoolFilter(myData)"`

**Comment by leupom** [comment]
@Nirazul Thanks ^_^

**Comment by LinusBorg** [comment]
filters in directives were intentionally removed in Vue 2.0 after intense discussions, we won't bring them back.

**Comment by Nirazul** [comment]
@LinusBorg 
I'm ok with this, I think you menat @leupom ;D

**Comment by LinusBorg** [comment]
Oh, right. Thanks!

**Comment by lukaserat** [comment]
Just an example using v-bind

```
:text-content.prop="text | filter"
```
