### ISSUE TITLE
Warn when using incompatible pre-compiled templates

### ISSUE THREAD

**Issue by SLaks** [vuejs/vue#5949]
### What problem does this feature solve?
I just wasted ~5 hours debugging https://github.com/JosephusPaye/Keen-UI/issues/332, which was caused by importing a pre-compiled template that was compiled by an older version of Vue that had subtle differences in `VNode`.

A simple warning that the objects passed to `VNode` don't look like they're expected to would have saved me hours.

### What does the proposed API look like?
AFAICT, at least for this particular issue, you can simply warn if `data.directives` exists.

For the future, you may want to include a semver version number in compiled templates so you can more-reliably check for any kind of issue.

**Comment by LinusBorg** [comment]
Thanks for reporting this!

We should open an issue in vue-loader's repository as well as this feature would require work in both repositories.

I like the idea with the semver number.

**Comment by yyx990803** [comment]
Thanks for the request - since then we've kept backwards-compat with old generated code in mind when making new changes, and I believe that's been working well so far. Essentially, any change that causes the runtime to be incompatible with render functions generated from an older version compiler is now considered a breaking change. We will keep doing that so that library authors don't have to re-compile their libraries just to avoid being broken.
