### ISSUE TITLE
how to use Sweet Alert to StandAlone Class From Vue Js ?

### ISSUE THREAD

**Issue by m-alinasab** [vuejs/vue#5952]
hello .

how to use Sweet Alert to StandAlone Class From Vue Js ?

component :
	//my variable is : form = new Form() ( On Everywhere it is needed. )

 	@submit event :
	form.submit('post' , '/admin/posts');

	Class Form :
	submit(request , url){
	// send ajax request
	// if success , run this.onSuccess() method
	// else run this.OnFail()
	}

	OnFail(){
	// i want use Sweet Alert it here .
	}

**Comment by LinusBorg** [comment]
Hello @m-alinasab 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
