### ISSUE TITLE
Children style not updating from custom render function

### ISSUE THREAD

**Issue by donnysim** [vuejs/vue#5986]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/5wwwy85g/](https://jsfiddle.net/5wwwy85g/)

### Steps to reproduce
Click the "Dropdown Toggle" button.

### What is expected?
Parent has class `open` and h1 should become visible - display: block.

### What is actually happening?
Parent has class `open` but child node (h1) display style is not applied. Only the first render value is kept on the child and that is display: none; in this case.

---
Can this be done this way and it's a bug or just not something that should be done? Maybe I just need to fallback to good old direct element style modification.

**Comment by posva** [comment]
the problem lies in

```js
if (this.open) {
          dropDownNode.data.style.display = 'block';
        } else {
          dropDownNode.data.style.display = 'none';
        }
```

The first time, the element doesn't exist, so it takes into account your additions to the data property but after that, it reuses the element, ignoring everything you add to it. You can check for `elm` in the vnode to modify it. That'll work.
Vue does this to prevent unnecessary renders. I don't think we should support rerendering those, as this is pretty advanced stuff that most users wont do and adding a layer of observation will slow down everybody. But I'll share with the team

**Comment by donnysim** [comment]
Not a big problem, can do with `elm` checks though probably would've done something completely crazy if you didn't mention it, was not sure I can use it, thanks :D . Not sure if should keep this open so I'll leave the pleasure to you if nothing comes up :)

**Comment by yyx990803** [comment]
The slot nodes are reused on child update because the parent did not update. During the vdom diff, two nodes with the same identity will be considered the same and skipped for diffing.

This means **you should not be mutating the VNodes passed down from the parent**. If you really need to, you should make a deep clone of the slot nodes in the child render function.

Alternatively, you can

- wrap the slot nodes with fresh VNodes created directly in `render`
- control the dropdown using a parent scope property, in the parent template instead
