### ISSUE TITLE
IOS 9 Page doesn't render

### ISSUE THREAD

**Issue by xAockd** [vuejs/vue#6030]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/g7ucj1xb/](https://jsfiddle.net/g7ucj1xb/)

### Steps to reproduce
Just open the link on iPhone with IOS 9.X.

Vue application wraps a big article and only on IOS 9 it dies.

### What is expected?
Page is shown

### What is actually happening?
Page doesn't render. Error occurred message.

**Comment by posva** [comment]
This is more likely to be a problem with the device not being powerful enough, it already lags on my computer, I cannot imagine opening that on a phone... Vue is not even binding anything and removing it seems to yield the same result.
So, unfortunately, there's nothing we can do here... If you manage to provide a minimal repro (there's just too much html there to even take a look 😄 ), I'll happily take a look. Otherwise, it's probably related to the amount of html you're using.

**Comment by xAockd** [comment]
Why if we remove Vue initialization the page is loaded fine?
It works on IPhone 6s iOS 8 but on iPhone 6 iOS 9 doesn't, so I don't think it's related to a device.

**Comment by posva** [comment]
It may be the straw that broke the camel's back...

**Comment by yyx990803** [comment]
If the page contains extremely large amount of markup, you should **not** mount Vue on the entire page. Mount it only to the part where you need interactivity.

**Comment by xAockd** [comment]
I've tried to mount it only when I need interactivity but I stuck with not dividable parts, for example list of products. I have quite complex markup and 1 product can be around 100-150 lines of html and all of them need interactivity
