### ISSUE TITLE
weird behaviour v-for

### ISSUE THREAD

**Issue by medhamza911** [vuejs/vue#6051]
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/zd7unwLm/](https://jsfiddle.net/zd7unwLm/)

### Steps to reproduce
simply uncomment the one line of code to work 

### What is expected?
no need for that one line of code

### What is actually happening?
nothing

**Comment by amertum** [comment]
You're iterating over an object. See the documentation about that, cf. https://vuejs.org/v2/api/#v-for

**Comment by Plasmatium** [comment]
Hi, @medhamza911 

Modified an observed variable will trigger re-render, but add new member will not.
Modify a variable will invoke its setter, this is under Vue's watch. But add a new member would not invoked its getter.

When you add new members to an observed object (the observed object has `__ob__` member, here is `app.contents.__ob__`), the new members would not be add to observer automatically.

So the modified `app.contents` would not be triggered to re-render.
But, when you assign a new value to `app.contents`,  `app` will find its member has been changed, so re-render triggered.

`app.contents = {}` triggered the watcher of `app`, in next tick (means that the code below that line will be executed before re-render here)

You may try code below, and will find that re-render triggered, because when you modified a variable under watch, it is responsible. But add new member is not a kind of modified.

```
window.app=new Vue({
  el: '#contentVisual',
  data: {
    contents:{a:1}
  }
});
// app.contents={};   
app.contents["test"]={items:[]};
app.contents["test"].items.push({"name":"testing"})
app.contents.a = 2
```

**Comment by LinusBorg** [comment]
See https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
