### ISSUE TITLE
migrate e2e tests to selenium-webdriver so they can be run on saucelabs

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue#61]
also checkout chai-webdriver and nightwatch

**Comment by phoet** [comment]
@yyx990803 i was wondering why you went with nightwatch.js tests. i'm currently looking for alternatives, the main motivation is around development-speed. i can't seem to get anything done in a reasonable amount of time because things [like a repl](https://stackoverflow.com/questions/43596190/driving-nightwatch-tests-through-repl) are missing.

are there any "hacks" that you are using in development that are worth sharing?
