### ISSUE TITLE
Vue.js not work in nw.js

### ISSUE THREAD

**Issue by maple3142** [vuejs/vue#6105]
### Version
2.3.4

### Reproduction link
[https://github.com/maple3142/osu-player](https://github.com/maple3142/osu-player)

### Steps to reproduce
`npm test` or `yarn test`
**7z** required

### What is expected?
A nw.js window show "test"

### What is actually happening?
only {{ msg }} appear

**Comment by yyx990803** [comment]
This report is way too generic - please try to narrow it down, at least with an Error stack trace.

**Comment by maple3142** [comment]
html:
```html
<div class="container">
	<div class="row">
		<div id="app">
			<span>{{ msg }}</span>
		</div>
	</div>
</div>
```
javascript:
```javascript
var app=new Vue({
	el: '#app',
	data: {
		msg: 'test'
	}
});
console.log(Vue);
console.log(app.$el);
```
console:
![](http://i.imgur.com/6kfNbBy.png)

**Comment by LinusBorg** [comment]
I don't see an element with id `#app` that Vue could mount to.

**Comment by dsonet** [comment]
@LinusBorg there is : <div id="app">

**Comment by LinusBorg** [comment]
Yeah sorry, I missed it when I read on mobile. 

But anyway, I can' run that code to test it (never used nw.js) so I can't verify this.

**Comment by yyx990803** [comment]
Ok, so the problem is not really a Vue issue...

1. You need to use the full build of Vue because the default `main` is the runtime only build:

  ``` js
  const Vue = require('vue/dist/vue.common.js')
  ```

2. In nw.js, libs required from `node_modules` are run in a separate "background page" with a different `window` and `document` than the main window, so when you use `el: '#app'`, Vue mounts the instance to the element in the background page instead... to fix it you need to pass Vue the pre-selected element from the main window:

  ``` js
  new Vue({ ... }).$mount(document.querySelector('#app'))
  ```

**Comment by Silve2611** [comment]
This is not working in my case. It says it cant find the #app... Ist there another solution?

**Comment by nickmessing** [comment]
@Silve2611, you need to have `<div id="app"></div>` to mount vue to that div.

**Comment by Silve2611** [comment]
I know that already if i import vue.js like this 	  
<script src="js/vue.js" type="text/javascript"></script> everything is working. It is not working if i use the npm version....
