### ISSUE TITLE
transition erases className unexpectly when part of enter-active-class is already present in component

### ISSUE THREAD

**Issue by comfuture** [vuejs/vue#6145]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/comfuture/nrrhhr8z/1/](https://jsfiddle.net/comfuture/nrrhhr8z/1/)

### Steps to reproduce
1. make component template like below:
```html
<transition enter-active-class="visible transition fade in">
    <div class="ui visible modal" v-if="visible" style="display: block">Hello</div>
</transition>
```

2. make it visible:
```this.visible = true```

### What is expected?
transition class added, then removed on transition ends. but need to leave the original class of nested vnode to `"ui visible modal"`.

### What is actually happening?
But class `visible` is removed from original vnode, and also removed `style="display: block"` property.

---
Of course, using only class names that do not overlap with transitions can avoid problems. However, I think it is better to have the process of recalculating and rendering the original vnode at the last tick after the transition is over.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

If you need the visible class to be there, you should put there directly in the `class` attribute since you have a `v-if` to toggle the visibility anyway. In your current code, it's removed at the end of the transition (https://vuejs.org/v2/guide/transitions.html#Transition-Classes). the style is not removed though...

If at the end, it turns out something actually bugs, I'll gladly take a look at a repro without semantic ui and just plain css 😄
