### ISSUE TITLE
dt and dd without end tags went to wrong.

### ISSUE THREAD

**Issue by mysticatea** [vuejs/vue#6252]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/mysticatea/528857L9/1/](https://jsfiddle.net/mysticatea/528857L9/1/)

### Steps to reproduce
1. Write `<dt>` and `<dd>` without their end tags by turns in a template (except DOM template). For example:

```html
<dl>
    <dt>Title 1
    <dd>Details 1
    <dt>Title 2
    <dd>Details 2
</dl>
```

### What is expected?
The DOM tree will become:

```html
<dl>
    <dt>Title 1</dt>
    <dd>Details 1</dd>
    <dt>Title 2</dt>
    <dd>Details 2</dd>
</dl>
```

### What is actually happening?
The DOM tree became:

```html
<dl>
    <dt>
        Title 1
        <dd>
            Details 1
            <dt>
                Title 2
                <dd>Details 2</dd>
            </dt>
        </dd>
    </dt>
</dl>
```

**Comment by Kocal** [comment]
Normal behavior, you need to close HTML tags.

**Comment by nickmessing** [comment]
@Kocal, no, it's not, according to the HTML specs `dt` and `dd` should self-close in this scenario, nice catch @mysticatea.

**Comment by nickmessing** [comment]
Quote from specs:
> A dt element's end tag can be omitted if the dt element is immediately followed by another dt element or a dd element.
> A dd element's end tag can be omitted if the dd element is immediately followed by another dd element or a dt element, or if there is no more content in the parent element.

**Comment by nickmessing** [comment]
Well, it works as expected with `<li>` and `<p>` closings, so it would make sense to support `<dt>` and `<dd>` but Vue actually asks you to not omit element closings:
```
vue@2.4.2:485 [Vue warn]: Error compiling template:

<dl><dt>dt<dd>dd<dt>dt2<dd>dd2</dl>

- tag <dd> has no matching end tag.
- tag <dt> has no matching end tag.
- tag <dd> has no matching end tag.
- tag <dt> has no matching end tag.


(found in <Root>)
```
same error happens with `<p>` and `<li>` (even tho they works)

**Comment by mysticatea** [comment]
Sure, I thought Vue.js supports auto-closing of `<li>` and `<p>`, so I opened this issue. If those are a deprecated feature, I'm fine if this is "won't fix".

Just I have found it while I'm rewriting [vue-eslint-parser](https://github.com/mysticatea/vue-eslint-parser) to report HTML syntax errors in [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue).

**Comment by nickmessing** [comment]
Technically even `li` and `p` are errors sincd Vue template compiler shows error in the console even when working as expected, I think we need to support them and disable Vue errors because code like `<p><div>hey</div></p>` will work as expected by HTML. I suggest supporting all html specific closings officially, but need to find out what Evan thinks about that.

**Comment by mysticatea** [comment]
Ah, sorry, I found that the behavior which reports lacking end tags as errors has been added in [v2.2.0](https://github.com/vuejs/vue/releases/tag/v2.2.0). So it looks to be going to deprecation. Please feel free to close this issue.

**Comment by nickmessing** [comment]
@mysticatea, I still it should be changed because at the moment it works differently from HTML specification, according to specs it should not be possible to have `dd` or `dt` inside `dd` or `dt`.

**Comment by gebilaoxiong** [comment]
This structure will also be a problem:

```javascript
new Vue({
  template: "<table><tbody><tr><td>td1<tr><td>td2</table>"
}).$mount("#id")
```

I think the stage of `parsing` is a bit of a problem:
https://github.com/vuejs/vue/blob/dev/src/compiler/parser/html-parser.js#L233

**Comment by yyx990803** [comment]
So, the rules about omitting end tags in HTML5 is rather case-by-case. For `p` and `li` it's more straightforward since they just close themselves when another one of itself is encountered, however for `dt`, `dd`, `tr`, `td` and `options` etc., each of them can be terminated by an open tag of itself or some other element, so if we want to strictly adhere to the spec we'd have to hard-code all these possibilities, which imo is not worth it just so that users can intentionally write spec-compliant but (imo) sloppy HTML.

Since we already have the closing tag warning in place, we are essentially enforcing Vue templates to be a stricter subset of HTML, which imo is fine considering the tradeoff here.
