### ISSUE TITLE
Built-In Component component's prop IS can not receive async component factory function

### ISSUE THREAD

**Issue by changchengqin** [vuejs/vue#6273]
### Version
2.4.2

### Steps to reproduce
1.Use Built-in Component : component
``` html
<script src="https://unpkg.com/vue"></script>

<div id="app">
  <p>{{ message }}</p>
  <component></component>
</div>
```
2.Declare a method called getAsyncComponent in Vue methods block that return an asynchronous component factory function
```javascript
new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  },
  methods:{
    getAsyncComponent() {
      return () => Promise.resolve({
        template: `<p>Hello</p>`
      })
    }
  }
})
```
3.Call getAsyncComponent for component's is attribute
``` html
<script src="https://unpkg.com/vue"></script>

<div id="app">
  <p>{{ message }}</p>
  <component :is="getAsyncComponent()"></component>
</div>
```

### What is expected?
 render async component correctly

### What is actually happening?
The getAsyncComponet method will enter the dead loop call

**Comment by posva** [comment]
this is expected behaviour because by using a function, the function gets executed every time the component tries to renders, which is basically when the function is called as well, thus creating an infinite loop. 

Please, next time provide the **actual** repro, not just code. Also, you could have followed up with some information on the issue you created

**Comment by changchengqin** [comment]
ok,thanks.
But it won't always be rendered, because all of the data doesn't change
