### ISSUE TITLE
v-for里的:key使用方法生成的随机数时，:key不符合预期

### ISSUE THREAD

**Issue by HeGangSZ** [vuejs/vue#6292]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/51608/](https://jsfiddle.net/50wL7mdz/51608/)

### Steps to reproduce
如果我按照文档上说明上，给每一个msg都附加一个唯一id，并作为key的话，是没有问题的。
<div v-for="msg in msg_arr" :key="msg.id"></div>

但是如果我想要在for循环生成列表时候用js生成一个唯一的值去赋给key的话，key却不生效，具体表现为：往msg_arr里unshift元素时，之前已经渲染好每项列表都会重新渲染，调用created方法。
<div v-for="msg in msg_arr" :key="Math.round(Math.random() * 4294967296)"></div>

:key所赋予的值必须是msg的属性么，如果我的msg都是一样的值，没有唯一id，那我是否需要在所有v-for循环处理之前做一步数据赋值处理，如果是这样的话就有点麻烦了。

### What is expected?
<div v-for="msg in msg_arr" :key="Math.round(Math.random() * 4294967296)"></div>里的:key符合预期

### What is actually happening?
:key不生效，往msg_arr里unshift元素时，之前已经渲染好每项列表都会重新渲染，调用created方法。

---
v-for循环里绑定的:key是通过调用方法即时生成的随机值，则:key不能生效，之前已经渲染好每项列表都会重新渲染，调用created方法
示例：
<div v-for="msg in msg_arr" :key="Math.round(Math.random() * 4294967296)"></div>

**Comment by posva** [comment]
If you want to generate random keys, these should be generated at the same time you create items and add them to the array because if you call functions in the template, the keys will be created every time the component renders. Completely defeating the purpose of keys

I recommend you to use the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js) to get further help

**Comment by HeGangSZ** [comment]
thanks,i will use those channels to solve the problem

**Comment by Plasmatium** [comment]
Hi @HeGangSZ 
使用 `v-for="(msg, idx) in msg_arr" :key="'key_' + idx"`，这样每个key都不同，并且不会改变，删除和插入的时候Vue可以找到正确的key。如果用Math.random，那么每次操作都会产生不一样的随机值key，被Vue解释为另一个不同的dom
