### ISSUE TITLE
Issue updating Dynamic Select Options

### ISSUE THREAD

**Issue by bubb-rubb** [vuejs/vue#634]
Hi, I'm not able to update the options array for a dynamic select. It seems a javascript error is being thrown and causing execution to stop. The error is  Uncaught TypeError: Cannot read property 'childNodes' of undefined. See the fiddle to reproduce

http://jsfiddle.net/5sH6A/68/

**Comment by user20161119** [comment]
@yyx990803 options is depcrated in new version?
I have similar scenario,address cascade to add new address.
`<select class="validate[required] form-control"  @click="queryProvince" v-model="warehouse_detail.province_id">
      				    <option v-for="item in ssx.province_data" :value="item.id">{{item.name}}</option>
					  </select>`
and encounter iss is that before ajax response,the select ui did not show correctly as follow capture
![image](https://cloud.githubusercontent.com/assets/123967/23121929/4037cb12-f79d-11e6-82d5-4fafae6eccde.png)

**Comment by saeedvaziry** [comment]
any solutions? i have same problem

**Comment by posva** [comment]
Hey, this issue is 3 years old, Vue has changed quite a lot in the meantime. Please, do not reanimate dead threads 😄 

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
