### ISSUE TITLE
Performance: Avoid unnecessary re-render on conditional data change

### ISSUE THREAD

**Issue by Avinm** [vuejs/vue#6342]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/w04Lznry/1/](https://jsfiddle.net/w04Lznry/1/)

### Steps to reproduce
Head over to https://jsfiddle.net/w04Lznry/1/.
Here, we have a function `foo` which is called on every iteration of a ` v-for` directive. The function mutates a data property on the last iteration of the directive and should therefore trigger a re-render on the change. However, it seems like the re-render happens every time the function is called. If the line that mutates the data is removed, the re-render does not happen.
I tested the same with angular and angular seems to re-render only at the last iteration. Should this not be the expected behavior in Vue as well?

### What is expected?
foo() should trigger a re-render only when index is equal to 4.

### What is actually happening?
foo() triggers a re-render every time.

**Comment by posva** [comment]
This is expected behaviour: Methods can contain arbitrary code and cannot be cached. Therefore, every time a component renders, they get called. If inside of that method you change something that triggers a render, the method will get executed again. So, careful with what you're doing, because it enters an infinite loop, it doesn't because `Date.now` is not precise enough 😄  but if [you use `performance.now`](https://jsfiddle.net/ya72n78a/) you'll get an infinite loop (look at the console).

**To put it in a nutshell, if you change data that is used in the template in a method that is called in that very same template, you'll have an infinite loop.**
In your example, even though you're not changing the content of the `li` elements, you're changing the adjacent element (same template) and the whole template renders, and therefore, the method `foo` gets called again when the `v-for` goes through the index 4.

You have many workarounds that depend on your use case, one of them could be using a component, you'll have to ask the question on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js) to get personal help

**Comment by Avinm** [comment]
The issue here is that foo does not change data every time, but just once. So shouldn't re-render occur only when data is changed?

**Comment by posva** [comment]
> In your example, even though you're not changing the content of the li elements, you're changing the adjacent element (same template) and the whole template renders, and therefore, the method foo gets called again when the v-for goes through the index 4.

every 5th `foo` call changes what is displayed adjacently and therefore rerenders the v-for as well because it's the same template, and calls `foo` again

**Comment by Avinm** [comment]
Okay, I noticed that even angular runs into infinite digest when Date is replaced with performance. I have two questions now though:
1. Why is angular still faster?
2. Shouldn't vue avoid the list items from being re-rendered when EndTime is changed since they don't rely on the EndTime?
