### ISSUE TITLE
Should prohibited keywords includes `this`?

### ISSUE THREAD

**Issue by mysticatea** [vuejs/vue#6362]
### What problem does this feature solve?
From https://github.com/vuejs/eslint-plugin-vue/issues/148.

Vue.js has [prohibited keywords](https://github.com/vuejs/vue/blob/c0da43d22f8f4b9aeb4f49d4e86cd9704daaff3f/src/compiler/error-detector.js#L7-L11), but it does not include `this` (though it includes `super`).
My feeling is that the use of `this` causes confusing.

Are there reasons that the prohibited keywords don't include `this`?

### What does the proposed API look like?
The prohibited keywords include `this` keyword.

**Comment by HerringtonDarkholme** [comment]
Sounds reasonable. Especially when vue automatically prefix template identifiers with `this`.

**Comment by nickmessing** [comment]
I actually sometimes use `this` for demonstration purposes for people coming from react background. I don't think it should be prohibited since it works perfectly fine. Rather it should be a part of `eslint-plugin-vue` and be "recommended" instead of "forbidden".

P.S. just though about this now, @HerringtonDarkholme do you think it's reasonable to remove `do` (and `let`) from prohibited keywords? Does it make sense to support do expression? (ex: `@click="myMethod(do { let tmp = f(); tmp * tmp + 1 })"`)

**Comment by HerringtonDarkholme** [comment]
@nickmessing  For `let` and `do`, I don't think we should allow them since it can promote more inappropriate logic in template. Like the example you give, I would think it probably belong to a method on vm.

**Comment by mysticatea** [comment]
> I don't think it should be prohibited since it works perfectly fine. 

Ah, I see. I didn't realize `this.` prefix works fine.

**Comment by yyx990803** [comment]
Since some users actually use `this` inside templates, prohibiting it will be a breaking change. As @nickmessing suggested, I think it would be better to make this a rule in the eslint plugin instead.
