### ISSUE TITLE
Error attempting to clone an element and append child during render

### ISSUE THREAD

**Issue by jjvainav** [vuejs/vue#6403]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/qnfbu9vo/2/](https://jsfiddle.net/qnfbu9vo/2/)

### Steps to reproduce
In the JSFiddle example, uncomment:

```
  <wrapper>
    <foo />
  </wrapper>
```

### What is expected?
The output should be:

foobar
foobar

### What is actually happening?
An 'Uncaught TypeError: Cannot read property 'propsData' of undefined' is generated.

---
I am new to Vue and trying to replicate something similar to this example in React: https://jsfiddle.net/dmrs77v0/1/.

**Comment by sirlancelot** [comment]
You can't clone `VNode`s, every `VNode` must be unique: https://vuejs.org/v2/guide/render-function.html#Constraints

**Comment by LinusBorg** [comment]
@sirlancelot  that's not really the problem.

@jjvainav vNodes representing child components have a different format than vnodes representing elements.

For example, they have no `children`, you can't simply re-use the `tag`, you have to use `componentOptions.CTor` or `componentOptions.tag` (depending on weither that tag is registered globally or not).

it doesn't have `children` because `<div>foo</div>` is the component's template and doesn't come from the parent. You can't inject a `<span>` into the child component without the component using a `<slot>`, and so on, and so on...

This is not a bug, it's a usage question, please use our forum or chat.
