### ISSUE TITLE
Why vue don't pre treat the prop as a local data property，is there has anything else to considered?

### ISSUE THREAD

**Issue by kosilence** [vuejs/vue#6451]
### What problem does this feature solve?
In vue@2.3.3，when we want to pass a prop from Father to Child component, we need to manually create a local data to save the prop, that makes lots of useless works.

```
props: ['initialCounter'],
data: function () {
    return { counter: this.initialCounter }
}
```

What if vue pre treat the prop as a local data property, so that in child component we can direct use the data to do whatever we want do, no worries to change father component data.

If vue want to strictly enforce One-Way-Data-Flow, make child component's data relative independence
 is necessary.

### What does the proposed API look like?
In this feature, i will suggest to do like:

```
props: ['initialCounter', 'initObject'],
methods: function () {
    doSomething: function() {
        // just use it as a local data
        this.initialCounter  = 1;

        // pass the changes to event listener
        this.$emit('onEditCounter', this.initialCounter);
    },
    doSomethingWithObject: function() {
        this.initObject.name = 'abcd';
        this.initObject.age = 43;
    },
    emitMyObject: function() {
        this.$emit('onEditObject', this.initObject);
    }
}
```

**Comment by LinusBorg** [comment]
What if vue pre treat the prop as a local data property, so that in child component we can direct use the data to do whatever we want do, no worries to change father component data.

Then the child would either:

* not receive updates of the prop from the parent anymore, or
* lose local changes when it receives updates from the parent.

That's the reason that you have to copy it to a local data property (if you intend to mutate that value). You need a copy to work with it independently of the updates that can come from the parent.

**Comment by kosilence** [comment]
@LinusBorg
