### ISSUE TITLE
ability to disable change events while already in a change event handler?

### ISSUE THREAD

**Issue by wysisoft** [vuejs/vue#6458]
### What problem does this feature solve?
I have a change event handler that changes values for other fields that have change event handlers, and I want to suppress or disable those event handlers while i'm in changing the values. This is a common pattern in other frameworks (I do it a lot in SharePoint). 

### What does the proposed API look like?
perhaps just a global flag like vm.disableChangeEvents?

**Comment by LinusBorg** [comment]
I'm not sure I'm completely understanding your situation. Can you provide a small example of the issue you are facing? Thanks.

**Comment by jsnanigans** [comment]
this is really easy to do yourself it you need it:
just define a variable i.e. `disableChange` in your data
then instead of 
 ```vue 
<tag @change="myFn()" />
``` 
check the variable before you execute the function: 
```vue
<tag @change="if (!disableChange) myFn()">
```   
or alternatively you could leave the attribute and check it in your function:
```javascript
myFn() {
  if (this.disableChange)
    return

  // ...
}
```

this would also give you more control over what gets disabled

**Comment by yyx990803** [comment]
This sounds more like a usage question - I don't think we should provide dedicated API for such specific use cases.
