### ISSUE TITLE
beforeUnmount in lifecycle?

### ISSUE THREAD

**Issue by Zhangdroid** [vuejs/vue#6469]
### What problem does this feature solve?
I try to build vue version of [react-overdrive](https://github.com/berzniz/react-overdrive), it needs to get the size and position before component destroyed.

Currently,  when I set false to `v-if` or change route, the lifecycle of the component seems like this:

v-if='false' -> DOM removed -> `beforeDestroyed` called -> vm destroy -> `destroyed` called

It seems no way to get the real DOM before component destroyed.

Related: 
* #6106 
* [How to get position and size of component before it destroyed with v-if?](https://forum.vuejs.org/t/how-to-get-position-and-size-of-component-before-it-destroyed-with-v-if/14691)

### What does the proposed API look like?
`beforeUnmount` may useful in some cases:

v-if='false' -> `beforeUnmount` called -> DOM removed -> `unmounted` called(optional) -> `beforeDestroyed` called -> vm destroy -> `destroyed` called

Or like this if it possible:

v-if='false' -> `beforeDestroyed` called -> DOM removed -> vm destroy -> `destroyed` called

**Comment by jsnanigans** [comment]
Isn't this something you could do with the js hooks for the transitions?
https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks
maybe inside the `beforeLeave` or even `leave`

**Comment by posva** [comment]
Indeed, using the `leave` hook on a transition allows you to control this.
Since `beforeMount` will probably always be related to animations and transition (getting access to the element before it is removed from the dom) using a transition looks like the right way to go but, this may be worth adding for the sake of consistency.
Don't forget to add `:css="false"` to the transition 🙂

**Comment by Zhangdroid** [comment]
@posva @jsnanigans Thanks, it solved my problem.
