### ISSUE TITLE
Element data being cleared after initializing vue instance

### ISSUE THREAD

**Issue by Jupakabra** [vuejs/vue#6474]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/Ljquatav/](https://jsfiddle.net/Ljquatav/)

### Steps to reproduce
1. Set jquery data on element is inside the vue root element.
2. Initialize vue instance on root instance.
3. Try accessing jquery data on that element.

### What is expected?
Data should still be there as the element is not rendered by vue and is already there.

### What is actually happening?
Data is cleared.

---
I have various jQuery plugins running on elements and most of them use hidden data for keeping their current state, it seems weird that vue would recreate DOM elements, especially those which don't have any vue bindings on them.

**Comment by posva** [comment]
Unfortunately, Vue is just using the content of `#app` as its template, so any data stored in the DOM element **before** mounting the Vue instance will be gone because vue only uses the HTML as a string to compile it into a render function. You'll need to initialise jQuery plugins in the `mounted` event to make sure they're kept
