### ISSUE TITLE
Be able to use props for styling without writing them inline

### ISSUE THREAD

**Issue by konstantinrachev** [vuejs/vue#6505]
### What problem does this feature solve?
The main problem is that inline styles are getting the code pretty messy, and if I intend to use components with their custom(scoped or not) styles, and for example: include some SASS mixin, it is becoming a struggle with using the components.

The main issue will be faced, when sending some props like image url, color, etc., which will end up being stucked inside our js and html, but not usable inside the style section.

I am well aware that the style tag won't let us using variables inside them, but something like computed styles when compiling down with Webpack, would be awesome.

### What does the proposed API look like?
The idea behind is to use some kind of computed styles section, where using the Vue component variables, would be possible, as it won't be inside the default ```style``` tag.

**Comment by jsnanigans** [comment]
I'm not sure I quite understand what you are trying to do, do you want to use js variables inside the style tag?
could you be a bit more specific of what you are trying to accomplish? maybe share a jsfiddle which illustrates your problem

**Comment by konstantinrachev** [comment]
Okay, sharing a sample fiddle, with a component, which is focus to the described issue: https://jsfiddle.net/1z2wavf9/

As you see, there is a struggle to use props inside the ```style``` tags and is impossible to dynamically change and trigger image change in my case, but whatever.

**Comment by te1** [comment]
You can already bind computed objects to styles:
https://vuejs.org/v2/guide/class-and-style.html#Binding-Inline-Styles

**Comment by yyx990803** [comment]
`<style>` is static by design, since they may be extracted into plain CSS files instead of injected and managed dynamically. On the other hand, props can only be known at runtime. There's no way to modify already extracted CSS at runtime. The convention for dynamic toggling of styles in that case is you write all the possible classes in `<style>` and toggle the class name dynamically.

If you prefer fully dynamic styling, you can always use a CSS-in-JS option with Vue instead.
