### ISSUE TITLE
created hooks fired before destroyed in hot reload

### ISSUE THREAD

**Issue by Lacroute** [vuejs/vue#6518]
### Version
2.3.3

### Reproduction link
[https://github.com/Lacroute/webpack-simple-bug](https://github.com/Lacroute/webpack-simple-bug)

### Steps to reproduce
Just create a minimal project from [this template](https://github.com/vuejs-templates/webpack-simple) and add some logs inside the hooks, you should obtain this in the console.
![alt text](https://raw.githubusercontent.com/Lacroute/webpack-simple-bug/master/src/assets/screenshot.png)

### What is expected?
The previous instance should be destroyed before the new one is created.

### What is actually happening?
The next one is created, so there is several init and then, the old one is destroyed so the init hooks are useless.

---
I don't know if this issue is related to the template or to the framework so I created also here > https://github.com/vuejs-templates/webpack-simple/issues/123 (unfortunately no response)

**Comment by yyx990803** [comment]
What makes this a bug? Why does the destroy/create order matter? It sounds like you are creating side effects that affect not just the component instance itself in your created hooks, which is not really a recommended practice.

**Comment by Lacroute** [comment]
Thanks Evan for your answer.

I don't know what makes this bug, it's just the behavior of a fresh template install. Does this works as expected ?

It matters because I use the hooks to handle my event listeners (from a global bus) so they are fired twice (registered in the created of my component, and removed on the beforeDestroy). I also want to register and unregister module to my store on the fly. And I got errors then.

**Comment by jsnanigans** [comment]
I'm not a vue bus specialist but creating listeners on the fly seams like a really bad idea to me, I'm sure that the destroy/create order the least of your problems since that will only appear in development.
May I suggest that, if you really want to keep it this way that you check if the listener already exists before you add it? you can easily do that with `if (bus._events['my-event-name']) {...}`

**Comment by Lacroute** [comment]
Yes I did that today, but then, the `beforeDestroy` hook removes everything.
I can't find a solution, I'll try the plugin approach. Thanks for your help.

**Comment by jsnanigans** [comment]
Why is it a problem that the beforeDestroy removes the listeners if you create them again the next time the component is mounted?

**Comment by yyx990803** [comment]
The current vdom behavior creates new nodes before destroying old ones - unfortunately, changing that would be a breaking change. I suggest you try to add checks to ensure a component instance can only remove listeners registered by itself.

**Comment by sirlancelot** [comment]
I think I might have a valid reason for this being a bug.

I'm using created & destroyed hooks to register & unregister Vuex modules. During development, if I hot reload a component that registers a Vuex module, it will instead register the module a second time before unregistering it.

Here's the output log:

```
client.js?3ac5:82 [HMR] connected
provisioning-enable-form.vue?eb82:82 registerModule
client.js?3ac5:214 [HMR] bundle rebuilding
client.js?3ac5:222 [HMR] bundle rebuilt in 1051ms
process-update.js?e13e:27 [HMR] Checking for updates on the server...
provisioning-enable-form.vue?45b1:82 registerModule
provisioning-enable-form.vue?eb82:85 unregisterModule
process-update.js?e13e:100 [HMR] Updated modules:
process-update.js?e13e:102 [HMR]  - ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/directory/provisioning-enable-form.vue
process-update.js?e13e:102 [HMR]  - ./src/components/directory/provisioning-enable-form.vue
process-update.js?e13e:107 [HMR] App is up to date.
```

Is there a better way to have a component register a Vuex module or should this ticket be re-opened?

**Comment by Lacroute** [comment]
I did two repos of what am I triying to do.
First of all, the repos:
 - [My external vue app](https://github.com/Lacroute/vue-external-component) and the [main conponent](https://github.com/Lacroute/vue-external-component/blob/master/src/components/External.vue)
 - [The main app](https://github.com/Lacroute/nuxt-external-embed) who embed my component, and the [integration page](https://github.com/Lacroute/nuxt-external-embed/blob/master/pages/index.vue)

What I wanted to do is to make a tool that self register in the store. But I had problems described before. Registering the component inside the nuxt app solved my problem. Am I doing things the right way?

**Comment by Emiya0306** [comment]
+1, so is any one resolve this problem? Can we use webpack `module.hot` to avoid this problem.

**Comment by FeliciousX** [comment]
@Emiya0306 This works and stops the error.

Unfortunately, because it never re-registers the store module, HMR becomes useless. Any updates being done to the store will never be updated after the hot reload.

Since I have [vue-devtool](https://github.com/vuejs/vue-devtools) installed, I create a temporary debugging public method to manually refresh the store I want in my component.

```typescript
// TODO: remove these debug methods
public refreshStore () {
  this.$store.unregisterModule('foo');
  this.$store.registerModule('foo', fooStore);
}
```
I select my component through the vue devtool and do `$vm.refreshStore()`

**Comment by Emiya0306** [comment]
@FeliciousX Yep~ Actually, the store will never remove in HMR by this way.
Refresh store by manual is a good idea! Maybe, can you write a mutation method to clean the store in destroyed lifecycle? I think it will be more cool~ 🎨
```javascript
// store.js
const initialState = JSON.stringify({
    // your store state
})
export default {
  state: JSON.parse(initialState),
  mutations: {
    [types.RESET_STORE]: (state, payload) => {
      state = JSON.parse(initialState)
    }
}
```

```javascript
// component.vue
destroyed () {
    if (!module.hot) {
      store.unregisterModule(['tinyStore']);
    } else {
      store.commit('RESET_STORE')
    }
}
```

@yyx990803 I think this can be enhanced in next vue big version optionally. ✨

By the way, I found if dynamic store was used by any other component **before dynamic module registered**, it would be warning that cannot found this dynamic module.

So can we watch this dynamic module until this module registered? Yeah, I mean always watching this dynamic namespace. ✨

`mapState`, `mapGetters `, `mapAction`, `mapMutation` can watch dynamic namespace.
But `this.$store.state[module namespace]` is not in this case, I think we can let it error.

**Comment by nolimitdev** [comment]
@yyx990803 
> What makes this a bug? Why does the destroy/create order matter? It sounds like you are creating side effects that affect not just the component instance itself in your created hooks, which is not really a recommended practice.

Incorrect order of "beforeDestroy" and "created" is not logical and not expected and makes problems in such usual situation:  if you use Vue + Vue Router and you are at RouteA and navigates from it to RouteB and each route/component register for something (e.g. receiving data supported by root) on "created" and unregister on "beforeDestroy" but when you leave RouteA its "beforeDestroy" is called after RouteB "created" so you have nothing registered! I have tested it and VUE 1 had correct order. It must be changed somewhere in VUE 2 but it is not mentioned in migration guide https://vuejs.org/v2/guide/migration.html It caused many bugs in our VUE apps after migration from v1 to v2.

Correct/expected hooks order in VUE 1 when going from RouteA to RouteB:
- RouteA beforeDestroy
- RouteB created

Incorrect/unexpected hooks  order in VUE 2 when going from RouteA to RouteB:
- RouteB created
- RouteA beforeDestroy

**Comment by bleighb** [comment]
I'm creating a three.js application instance that's passed into my root Vue instance. When I hot reload my App.vue, I want to dispose of the scene and create one anew. So naturally, in the destroy hook I tell the application to clean itself up, and on create, I reload elements. I've been dealing with a lot of strange bugs all day, until I just discovered that the events fire out of order, because hooks firing out of order is the last thing I checked.

I can understand if there's a technical reason for this. But in my opinion, in order for Vue (and other JS frameworks) to live up to their claims of awesomeness and simplicity, there needs to be a solid abstraction layer that doesn't expose complexity like this. Otherwise, the tool just ends up costing more time than it claims to save. I understand this is a contrived example, but, as an example, when I use `fetch` in JS, I never have to worry about the TCP/IP stack. When using hooks in Vue, I similarly (perhaps ideally), shouldn't have to worry about the VDOM behind the scenes.

In that light, would it be possible to reopen this issue and see if we can figure out a solution to this bug?

**Comment by christoph-burker** [comment]
Using vue@2.6.11 here and I'm still experiencing _beforeDestroys_ getting called before _created_. I'm using them to dynamically register vuex stores. The register that is supposed to happen after the reload reregisters the store module (I receive the message "[vuex] state field "..." was overridden by a module with the same name at "..."") and the _beforeDestroy_ that should've happened before is called too late unregisters the module.

This kind of defeats the purpose of hooks and during hot reloads as the lifecycle is kind of not consistent.

**Comment by fexodus** [comment]
> _beforeDestroys_ getting called before _created_

@christoph-burker please be aware that you are not looking at the life cycle of a single component instance. Hot reloading causes a new component instance to be created before the old is destroyed (otherwise hot swap would not be possible). This problem can be addressed with instance counter, e.g.:
```typescript
{
	beforeCreate() {
		if (++instanceCount > 1) return;
		store.registerModule(...);
	},
	destroyed() {
		if (--instanceCount > 0) return;
		store.unregisterModule(...);
	},
}
```

**Comment by atyshka** [comment]
+1 on reopening this. I am using using mapbox for maps, and on my mapbox components I need to use lifecycle hooks to create/delete map layers. Mapbox can't have duplicate layers, so when a HMR occurs, it tries to add a new layer, throwing an error since the old layer has not been destroyed yet. I can use a workaround, but this really is counterintuitive behavior.

**Comment by atyshka** [comment]
I know that changing the order would be a breaking change, but what about adding a new lifecycle hook like destroyQueued, which would allow cleanup before a create is called? Any way to insert cleanup logic before create would work, not necessarily changing the order of the current hooks

**Comment by christoph-burker** [comment]
> @christoph-burker please be aware that you are not looking at the life cycle of a single component instance. Hot reloading causes a new component instance to be created before the old is destroyed (otherwise hot swap would not be possible). This problem can be addressed with instance counter, e.g.: <CODE>

Thanks for your answer! The code looks like a decent workaround, but it's somehow odd having to implement code just for hot reloading to work properly.

I am aware, that it's a new instance that is created, but I still think the old one should be completely destroyed before a new one appears. At least that's what a reload is to me. Anyways, you're getting a (Y) from me

**Comment by fexodus** [comment]
> it's somehow odd having to implement code just for hot reloading to work properly

At first it is a bit counter intuitiv, but i try to look at it from this perspective: If i make no assumptions about 1. how often my component can appear on a page and 2. in which order vue or hot-reloading switches component instances, then i need to account for a n:1 relation between component count & store-module count. So it's not really a matter of hot-reloading working properly, but more about making assumptions about how many component instances can exist at the same time.

On a bright side vuex 5 seems to eliminate this problem by relying on simple JS module imports instead of manual un/register.

**Comment by bilouw** [comment]
> > _beforeDestroys_ getting called before _created_
> 
> @christoph-burker please be aware that you are not looking at the life cycle of a single component instance. Hot reloading causes a new component instance to be created before the old is destroyed (otherwise hot swap would not be possible). This problem can be addressed with instance counter, e.g.:
> 
> ```ts
> {
> 	beforeCreate() {
> 		if (++instanceCount > 1) return;
> 		store.registerModule(...);
> 	},
> 	destroyed() {
> 		if (--instanceCount > 0) return;
> 		store.unregisterModule(...);
> 	},
> }
> ```

Can you please specify what is this instanceCount, how can i get it ? I'm in the same situation, problems with vuex modules registration/unregistration and lifecycle hook ...

**Comment by fexodus** [comment]
> Can you please specify what is this instanceCount, how can i get it ?

It's just a variable that you can put in a closure, e.g.:

```
const provideModule = (path, module) => {
	let instanceCount = 0;
	return {
		beforeCreate() {
			if (++instanceCount > 1) return;
			store.registerModule(path, module());
		},
		destroyed() {
			if (--instanceCount > 0) return;
			store.unregisterModule(path);
		},
	};
};
```

Now you can create a mixin for your store module
```
const provideMyStoreModule = provideModule('my/path', myStoreModule);
```
and bind it to all components that require it
```
mixins: [provideMyStoreModule]
```

**Comment by bilouw** [comment]
Thanks for you reply. Tomorrow, i will test this. But honestly, my concern is that i don't understand how this code solve the problem for now.

Here my problem: I have a vuex module, let say TodoListModule, that i want to register when needed and unregister when not needed. I can't use routes guards because it's a sub-component.

So when i enter routeA, my module is registered by beforeCreate hook. When i quit routeA, my module is unregistered by beforeDestroy hook. Until now that work perfectly. 

My problem come when i try to quit routeA for routeB (routeB also contain my sub-component TodoList). When i enter routeB, before registering my module, i check if the module is already registered. Because the beforeCreate hook of routeB is triggered earlier than beforeDestroy hook of routeA, my module is still registered and the registration on routeB doesn't happen.

Can you explain me how the code you provided resolve this case ?

Sorry to bother you with my problems, and thanks for your help.

**Comment by nolimitdev** [comment]
Whenever possible I combine `created` + `beforeRouteLeave` but in case with sub-component I recommend to combine `mounted` + `beforeDestroy`. In my case time difference between `created` and `mounted` is less than few milliseconds so I use it rather this way without ugly hacks such as counters mentioned above.

**Comment by bilouw** [comment]
> Whenever possible I combine `created` + `beforeRouteLeave` but in case with sub-component I recommend to combine `mounted` + `beforeDestroy`. In my case time difference between `created` and `mounted` is less than few milliseconds so I use it rather this way without ugly hacks such as counters mentioned above.

What you say doesn't resolve the problem. If i'm correct, beforeDestroy of componentA will be trigger AFTER mounted of componentB. That is the problem.

**Comment by fexodus** [comment]
> i want to register when needed and unregister when not needed

> can't use routes guards

That's exactly what the `provideModule` solution should do. It also avoids any router hooks, as components presence can depend on more than a route (e.g. user interaction, server events).

Can you give me a hint which part of the example is giving you doubts?

**Comment by nolimitdev** [comment]
Sorry, you are right @bilouw `mounted` + `beforeDestroy` is only alternative for `created` + `beforeRouteLeave` and does not work for sub-component. You can try sth. like this...

```
// MySubComp.vue
<template>
  ...
</template>
<script>
    var lastCreatedFrom = null;

    export default {

        created() {
            lastCreatedFrom = this.$parent.$vnode.tag;
            console.log("sub-component", this.$parent.$vnode.tag, "created");

        },

        beforeDestroy(){
            if (lastCreatedFrom != this.$parent.$vnode.tag)
                return;

            console.log("sub-component", this.$parent.$vnode.tag, "beforeDestroy");
        },

    }
</script>
```

**Comment by bilouw** [comment]
> > i want to register when needed and unregister when not needed
> 
> > can't use routes guards
> 
> That's exactly what the `provideModule` solution should do. It also avoids any router hooks, as components presence can depend on more than a route (e.g. user interaction, server events).
> 
> Can you give me a hint which part of the example is giving you doubts?

I just don't see how the instanceCount trick can make my module from routeB to register AFTER the unregistration of my module from routeA. From what i see, the beforeCreate hook from routeB will still be triggered earlier than the beforeDestroy from routeA. But correct me if i'm wrong, I must surely miss something.

**Comment by fexodus** [comment]
> module from routeB to register AFTER the unregistration of my module from routeA

I wonder why you would want to destroy/unregister the store module just to create/register it again? Would an update of the module state on route transition not be sufficient? The counter solution keeps your store module registered as long as there is at least one component referencing it.

**Comment by bilouw** [comment]
> I wonder why you would want to destroy/unregister the store module just to create/register it again? 

Because in my app, i don't have just routeA and routeB. I have multiple routes that doesn't use the store module, so i want to unregister it when my component is destroy, in case of the next route doesn't need it (most of the time). BUT, i want to register the module again if the next route need it again.

> The counter solution keeps your store module registered as long as there is at least one component referencing it.

That the point that i don't understand. How can the counter solution knows how many instance is present if it's just a variable initialized with 0 at component creation ?

**Comment by fexodus** [comment]
>  How can the counter solution knows how many instance is present if it's just a variable initialized with 0 at component creation

Ah, now we got to the core. Take a closer look at `provideModule`. It initialises the counter as it creates the mixin (not the component). All component instances that have this mixin as dependency, will trigger the same counter. Just make sure to create the mixin only once and reuse it for all components.

I use a similar solution in production for years without any trouble.

**Comment by bilouw** [comment]
> It initialises the counter as it creates the mixin (not the component). All component instances that have this mixin as dependency, will trigger the same counter. 

Wow, i just tried and the solution seems very elegant. 
Okay, now i get it. I never used mixin for now, so i didn't know that components sharing the same mixin can also share properties (like instanceCount). I thought: what if i want to have independant properties for each component using the mixins ? But for this, we just use a data function. I confounded: data function to declare independant properties for each components, and declaration like instanceCount, that seems to be shared with all components using the mixins. 

Good to know. Thanks again for all your help.

**Comment by Rolanddoda** [comment]
Unfortunately none of the solutions mentioned worked for me. They had issues with computed properties, watchers etc.

I have found a solution which seems to be working at the moment of writing this comment with all the tests I did. If I find that something doesn't works neither with my solution, I will update this comment.

```js
import importedModule from './my-module.js'

export default {
  // ...
  beforeCreate() {
    if (this.$store.hasModule('module-name')) {
      this.$store.unregisterModule('module-name')
    }
    this.$store.registerModule('module-name', importedModule)
  },

  beforeRouteLeave() {
    this.$store.unregisterModule('module-name')
  },
 // ...
}
```
