### ISSUE TITLE
Special v-model fields cleared on input/blur

### ISSUE THREAD

**Issue by jordanramstad** [vuejs/vue#6541]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/ey4rrqhz/1/](https://jsfiddle.net/ey4rrqhz/1/)

### Steps to reproduce
Create a vue application while adding in jQuery-UI (though this should work with any library that adds extra functionality on top of an input, jQuery-UI is just the most easy to use to reproduce).

Create 2 fields, it should not matter the type.

Load in jQuery-UI datepicker into a field that uses v-model.

Enter a value using the datepicker into the field and then add a value in the second field.

### What is expected?
Both fields update properly and are reflected in the vue component data.

### What is actually happening?
First field's input is being cleared.

---
If you remove the fields from the data object in vue, it will instead clear on blur it seems. Trying to fix this has left me pushing away from what is considered the best practice for Vue as well.

Ran into this on a form that has some select fields populated by vuex data, I managed to add in some "hacks" to get the rest of the fields working at the very least (its a standard form so I didn't really need to do much more then populate the initial value). However the vuex field cannot be adjusted like that, so although I feel I understand Vue well, I cannot figure out a way around this.

**Comment by posva** [comment]
This is expected because the datepicker is not changing `item.test` and therefore, when the other value, `item.num` changes, the whole template renders again, and because `v-model` is used on the input, the value of `item.test` is used to fill it, and therefore clean it. In this case `v-model` is not being used (since you're using a jquery date picker). You need to react to the event sent by the datepicker to change `item.test` or just remove `v-model` on the input augmented with the datepicker since it's not being used

**Comment by jordanramstad** [comment]
I see makes sense. Unfortunate but after seeing your comments on it I see its been a heated debate in the JQuery community about changes in the value of inputs triggering events, normally I don't use jQuery-ui or masking plugins so just never noticed this (I was spoiled).

Guess I gotta add some overrides to jQuery *sigh*

Thank you though, very clear answer to a problem I just could not wrap my head around.

**Comment by posva** [comment]
Glad you find it useful 🙂 . I'd personally try to find a plugin that wraps it or create mine in a component
