### ISSUE TITLE
computed properties in v-repeat

### ISSUE THREAD

**Issue by thasmin** [vuejs/vue#66]
Is it possible to use computed properties in v-repeats? As far as I can tell, there's no way to tell which item is being rendered in the computed property. I've also tried adding a function as a property of the data item but that wasn't working either. 

For example:
data: { items: [ { number: 1, text: 'one' }, { number: 2, text: 'two' } ] }
template: <div v-repeat="items"><span color={{propercolor}}>{{text}}</span>
computed: { propercolor: function(item) { return item.number == 1 : 'blue' : 'black'; } }

**Comment by hedefalk** [comment]
Hi,

Newbie-question related to this:

I'm trying to do something very similar but I'm having troubles with "v-component" on the same element as my repeat. I'm doing just like: http://jsfiddle.net/yyx990803/rUAPZ/, I have put 

<tr v-repeat="rows" v-component="row">

and registred the subcomponent with just a computed property:

module.exports =
  components:
    row:
      computed:
        resultText: ->
          this.value.result + "foo"

(sorry, coffescript)

But I get this error that the directive "component" doesn't resolve. In 

compileDirectives this turns out to undefined for "v-component":

dirDef = resolveAsset(options, 'directives', dirName)

while "v-text" and other stuff inside works just fine. There is an "_component" in the options.directives passed in while other built in stuff like "text" is there without the underscore. What can I be doing wrong=

Thanks,
Viktor

**Comment by SgtIria** [comment]
Hi,

That fiddle is pointing at quite an old version of vue  'Vue.js v0.8.2'. Is that the version you want to be using?

A

**Comment by hedefalk** [comment]
Nah, but the code seems legit still:
http://jsfiddle.net/hedefalk/3b8xz2o4/1/

**Comment by hedefalk** [comment]
I could come around my current issue by simply using a filter to compute the property from the simple data object iterated over, but I think I still will need computed properties for more involved things in the future.

**Comment by yyx990803** [comment]
@hedefalk your fiddle isn't loading Vue correctly. Also, note that once you are using a component, it treats the content inside it as "external content to be redistributed in its own template". You need to give the component its own template in its options, or use the `inline-template` attribute.

Working: http://jsfiddle.net/yyx990803/3b8xz2o4/3/

**Comment by SgtIria** [comment]
Yes I've reworked it using coffeescript here http://codepen.io/sgtiria/pen/vOmNpQ?editors=101

**Comment by hedefalk** [comment]
Thanks guys, so this is exactly what I would have wanted (using inline-template):

http://jsfiddle.net/hedefalk/kdv9nhbe/

However, in my real app, I still get the:

"[Vue warn]: Failed to resolve directive: component" when trying to put a v-component on the same element as my v-repeat. I guess something is different but I don't understand it. I guess I need to try to isolate the issue I have in my production code...

I'll be back!

**Comment by yyx990803** [comment]
@hedefalk are you using 0.12-rc in your real app? In 0.12 `v-component` has been deprecated and you can only use custom element components.

**Comment by hedefalk** [comment]
@yyx990803 Oh, I guess I am?

"dependencies": {
    "vue": "yyx990803/vue#next",

**Comment by hedefalk** [comment]
Oh, that was definitely it.

Sooo, I really don't want to stay behind, so how would I achieve something like this if I don't want to break up my template? I mean, the use case is simply this:

I have an iteration of a lot of elements retrieved as json from a backend and I just use v-repeat and everything is fine and I'm all but done. Then I realize I need just one more thing in the inner thing that needs to be computed from the json data but isn't there just yet. I don't want to have to rearrange the templates just for this - I would like to be able to just add a computed attribute on the elements that I can then use inside the v-repeat. Makes sense?

If v-component is removed, I need to stuff a <component> around the template that is "v-repeated"? But what if the computed property needs to be on the actual element that the v-repeat is on, in my case a styleClass on the <tr> ?

Thanks for your patience :)

**Comment by yyx990803** [comment]
I don't think I understand your problem, but this is your fiddle using custom element component (notice `replace: true` option for the component): http://jsfiddle.net/yyx990803/kdv9nhbe/1/

**Comment by hedefalk** [comment]
Thanks a lot! I've been trying to use this approach on my production code, but it doesn't seem to work. I tried to boil it down to my particular problem. To me a wild guess would be something related to the use of a table and custom elements, but I don't know. I figured it might be jsfiddle first that moved out my repeat of the table element before giving the template to my js, but the problem remains even though I used a script-tag for the template. The custom element seems to be moved out of the table:

https://jsfiddle.net/hedefalk/vz522u8m/7/

Thanks for your patience, I guess I'm doing some real wtf here :)

**Comment by yyx990803** [comment]
Hmm okay, this is indeed due to browsers not allowing non-table elements inside tables. You'll have to use `v-component` on table elements. This is something I've overlooked when deprecating `v-component`; in the 0.12 official release I'll make it still usable on table elements.

**Comment by hedefalk** [comment]
Ah, ok! Thanks for investigating this! I guess moving the template to a script didn't help since there's no shadow DOM thing going on, the transformations are applied after the template is put in DOM so the browser has already "fixed" the template?

I'm just starting out with vue.js and don't want to get stuck with an old version, but rather follow your development and be bleeding edge so I have a couple of follow-ups:

My strongest reason for choosing vue.js, over for instance mithril.js or react (which are the only ones I have looked into after dumping angular :) ), is that I'm a fan of this kind of templating. I'm coming from a background where I have used Lift/Scala and done server side rendering using functional transforms of pure and correct html5 documents with mock data just by adding "data-" attributes. I know that times are changing and frontend people need to do the js too, but I really liked the way I have been able to work with a "design person" doing only html/css in the same git repo and me just adding unobtrusive "data-" attributes and then binding it with data.

I guess I'm a bit interested in the rationale for deprecating v-component and what I can expect in the future with other attributes? Is it because the attributes are not correct html5? I'm for instance using v-text over mustache bindings which I guess is just my esthetic preference due to my background.

Will it at all be possible to do what I kind of want to do that is to sometimes have a large correct html5 document (with mock data) and just bind the shit out of it with js but without any external templates?

Again, thanks for your help!

**Comment by hedefalk** [comment]
Sorry to bug you this much, but one last question (for now :) ):

I need to have a styleclass on the tr that depends on the data it's repeated over. I can't seem to find a way to use v-repeat, v-component and v-class on the same tr:

http://jsfiddle.net/hedefalk/px37b9ts/1/

It seems the v-class is evaluated outside the v-repeat/v-component scope?

**Comment by azamat-sharapov** [comment]
@hedefalk http://jsfiddle.net/azamatsharapov/px37b9ts/6/

**Comment by hedefalk** [comment]
@azamat-sharapov Sorry, that doesn't help me. What I'm looking for is a way to use the element iterated over to set a style class. You have simply added "text" by evaluating the static value true.

Thanks,
Viktor

**Comment by yyx990803** [comment]
@hedefalk HTML5 is quite forgiving in terms of custom tags and attributes, and there isn't any substantial downside in using them. On the other hand, Custom Elements is actually being worked on as an official W3C spec, so it is going to be very common in the future.

Component with props is a first-class concept in Vue, that's why they get their own dedicated syntax. Other directives will remain `v-` prefixed attributes.

For your scoping question, see this blog post: http://vuejs.org/2014/12/08/011-component/#Where_Does_It_Belong\?

**Comment by hedefalk** [comment]
@yyx990803 Thanks!

I've read the blog post, but I can't seem to understand how I can use this to get what I want in my current example:

http://jsfiddle.net/hedefalk/px37b9ts/5/

Since inline-template only gives the inner template to the sub-component it seems I just can't fix this thing without resorting to external templates - is this correct?

Thanks again,
Viktor

**Comment by yyx990803** [comment]
You have two options:

1. Use `replace: true` for the component so you include the root node in the component's template (recommended)
2. Use a `<template>` block repeat.

**Comment by hedefalk** [comment]
Sorry if I'm thick as a brick here, but ```replace: true``` just makes the original element be replaced - in my case, if just adding ```replace:true```I loose my ```<tr>``` altogether:

http://jsfiddle.net/hedefalk/px37b9ts/9/

**Comment by yyx990803** [comment]
You'll have to avoid inline template in this case: http://jsfiddle.net/px37b9ts/11/

**Comment by hedefalk** [comment]
Yeah, I was afraid so. This is what I'm actually trying really hard to avoid :)

I find this a little better:

http://jsfiddle.net/hedefalk/abxghy8q/

but I would rather be able to have _one_ template that I can transform as explained above. If you come up with any idea how to do this, I'll be super-happy!

Thanks,
Viktor

**Comment by MicroDreamIT** [comment]
how am i suppose to calculate average, here is the link, http://jsbin.com/xecelovepa/1/edit?html,js,output, http://jsbin.com/cirosuniru/1/edit?html,js,output

**Comment by professor93** [comment]
Hi, how can i use this code in v2.0.2 "http://jsfiddle.net/yyx990803/rUAPZ/"

**Comment by defcc** [comment]
@professor93  you could take look at this https://jsfiddle.net/defcc/0eeLzwh1/
