### ISSUE TITLE
v-model doesen't work with <component :is> logic in simple inputs, checkbox, etc

### ISSUE THREAD

**Issue by yariksav** [vuejs/vue#6605]
### Version
2.4.4

### Reproduction link
[http://jsfiddle.net/yariksav/26moyu4n/4/](http://jsfiddle.net/yariksav/26moyu4n/4/)

### Steps to reproduce
`<component :is="'input'" v-model="test"></component>`
```

data () {
  return {
    test: '111'
  }
}
```

### What is expected?
the value 'test' must change when i edit input

### What is actually happening?
the value doesen't change, input doesen't emit event

**Comment by yyx990803** [comment]
`v-model` relies on static information about the tag it is used on to generate appropriate code during compilation. When used on a `<component>` it generates component-specific code instead of native form element code. This is simply something that we don't support due to the compilation-based nature of `v-model` - use if branches instead.
