### ISSUE TITLE
keep-alive include parameter is not worked with router-view

### ISSUE THREAD

**Issue by okjesse** [vuejs/vue#6619]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/okjesse/k94fphsg/](https://jsfiddle.net/okjesse/k94fphsg/)

### Steps to reproduce
keep-alive include parameter is not worked with router-view

### What is expected?
Home is not keep alived

### What is actually happening?
home is keep alived

**Comment by yyx990803** [comment]
keep-alive include works on **component names, not route names**. Your Foo component doesn't have a name.

**Comment by sqal** [comment]
It happens because you have not given Home component a name

https://jsfiddle.net/b9xk5rdw/

**Comment by okjesse** [comment]
@sqal  thank you,it's woks

**Comment by dkjain** [comment]
Hi sqal,

In both the problem fiddle & solution fiddle, both components have names, 
`const Home = { name: 'Home', `
`const Foo = { name: 'Foo'`

so not sure when you say
> It happens because you have not given Home component a name

Kindly clarify.

thanks

**Comment by Tech-Nomad** [comment]
You also have to use the :key directive to update a component using keep-alive and router-view together with params in the route path like  /blog/:slug

    <keep-alive>
        <router-view :key="$route.fullPath"></router-view>
    </keep-alive>

With this Vue finally updates any new blog posts but caches the previously loaded. Otherwise only the first loaded blog post will be served even the blog/:slug changes all the time.

See also:
https://vuejs.org/v2/api/#key
https://stackoverflow.com/questions/52847979/what-is-router-view-key-route-fullpath
