### ISSUE TITLE
Pass path of changed property to deep watch

### ISSUE THREAD

**Issue by sbward** [vuejs/vue#6640]
### What problem does this feature solve?
Passing the path of a changed property to a deep watch would allow us to determine exactly which data was changed in a deep watch programmatically, especially for data nested under arrays.

Currently if I have a large nested object and I want to know which property was changed, I need to create a watch for every single property.  Furthermore, if any of the watched properties are arrays, then it is impossible to register a watch deeper than the respective array keys.

This has been requested (indirectly) before; see #328 for an example.

### What does the proposed API look like?
Currently, Vue provides `(newVal, oldVal)` arguments to the watch handler, but not the path of the changed attribute.  This information could be passed as a third argument: `(newVal, oldVal, path)`

I'm not sure how the `path` argument should be typed, but one possibility is providing a path string, for example `"$data.propA[2].propB"` would indicate that the change occurred here:

```
data: {
  propA: [
    { ... },
    { ... },
    {
      propB: 'i was changed'
    }
  ]
```

**Comment by yyx990803** [comment]
Unfortunately, Vue's reactivity system is not designed to provide the information - or, put it another way, it entails non-trivial changes and additions to provide an API with marginal benefits.

A deep watcher recursively registers every property as a dependency inside a reactive Object/Array, and should be used with caution because of its performance implications.

In most cases, heavy reliance on watchers indicate a design that can be re-thought and improved to remove the reliance, and deep watchers particularly so. It would probably be better to discuss your actual use cases on the forum or the discord chat before opening a feature request.

**Comment by Wiejeben** [comment]
I was able to achieve this by using the JavaScript Proxy object:
```js
data() {
    return {
        form: new Proxy({
            salutation: '',
            firstName: '',
            suffix: '',
            lastName: '',
        }, {
            set(target, key, value) {
                console.log(`${key} set to ${value}`);
                target[key] = value;
                return true;
            }
        })
    }
}
```
