### ISSUE TITLE
very poorly performance on computed property of computed property that accesses a nested array

### ISSUE THREAD

**Issue by SeregPie** [vuejs/vue#6660]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/kz16r91L/](https://jsfiddle.net/kz16r91L/)

### Steps to reproduce
First computed property accesses a nested array and second computed property accesses the first computed property.

### What is expected?
The computed property is cached and the repeated calls returns the result immediately.

### What is actually happening?
The compute function is not called but each access to the computed property is very slow.

---
Looks like the computed property, that accesses a nested array, is not cached properly.

**Comment by yyx990803** [comment]
This is related and explained in https://github.com/vuejs/vue/issues/6284

For now, you can avoid the iteration cost by freezing the Array, if you don't expect it to be mutated. This will no longer be necessary in 3.0 though.

**Comment by SeregPie** [comment]
Wait. This is not the cause. The cause is, that the **access to an already computed property** is very slow. If you put a watcher between two computed properties, then all is working great.
[see](https://jsfiddle.net/kz16r91L/1/)
I also did the same in my project and all the changes are still reflected properly, but it is a million times faster.

**Comment by Akryum** [comment]
@SeregPie Your test is wrong because the watcher is called before it: https://jsfiddle.net/ns1n6kwq/1/

The performance issue comes from Vue building the dependencies when evaluating the computed properties: accessing the computed properties multiple times add even more dependencies and slow down the component.

One thing I did when having this kind of performance heavy computed properties was to just access the computed property once and assign it into a local variable:

```javascript
myComputed () {
  const a = this.myOtherComputed
  // use a instead of this.myOtherComputed
}
```

You may find that this is in fact as performant as using a watcher: https://jsfiddle.net/LrLqmmjr/1/

**Comment by Akryum** [comment]
Example for my proposed solution: https://jsfiddle.net/kLor5ep7/1/

**Comment by mciesin** [comment]
Did someone come up with a solution for the use case, when the problem of a slowdown is accessing such computed property in multiple components (instead of having multiple accesses to a computed in another computed 😅 ?
