### ISSUE TITLE
can not easily keep component status of v-for with key when array splice

### ISSUE THREAD

**Issue by green-mike** [vuejs/vue#6676]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/mike_huang/syLhp8hL/4/](https://jsfiddle.net/mike_huang/syLhp8hL/4/)

### Steps to reproduce
click first component to remove it.

### What is expected?
remain second component and show second component's status.

### What is actually happening?
remain component show first component's status.

---
I known it happen because use "key=index" then the component "index=1" has been reused. But in current version, key is required. I can't add unique key of array element easily.

I found some suggestions of forum that use object as array element then use object as key directly. ex: https://jsfiddle.net/mike_huang/zm2n0u4v/ But it is not vue expect value and catch warning "Avoid using non-primitive value as key, use string/number value instead". I think it is not right way.

Or must I create unique id manually like the official todoMVC example? Is there graceful solution?

I think it is restriction so I post this issue. thank you.

**Comment by posva** [comment]
> I known it happen because use "key=index" then the component "index=1" has been reused. But in current version, key is required. I can't add unique key of array element easily.

Yeah, it's also because you have a local state in the todo component. Note that if you only use the prop `todo` as the value of the input, you will see the expected behaviour.
You can manually add a key as you said, which is fairly easy in my opinion. Unfortunately, keys are necessary when removing elements in an array that is used in a `v-for`
