### ISSUE TITLE
i want konw if is it fine to put vue-server-renderer/build.js in webpack's produce

### ISSUE THREAD

**Issue by freeozyl80** [vuejs/vue#6696]
### What problem does this feature solve?
just wana know if I use vue-ssr, how can i use as react to include server.js in webpack but not only entry-server

### What does the proposed API look like?
thanks for answer

**Comment by LinusBorg** [comment]
Hello @freeozyl80 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
