### ISSUE TITLE
v-model bind does not update the input value

### ISSUE THREAD

**Issue by mengao89** [vuejs/vue#6717]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/ameng_code/xg9ekuwe/4/](https://jsfiddle.net/ameng_code/xg9ekuwe/4/)

### Steps to reproduce
when type in the custom-input, ,i reset the value to 123456 in the on-change event ,but the input element value does not update

### What is expected?
when the rawvalue reset to 123456,the custom-input will watch the change,and update the input element

### What is actually happening?
when the rawvalue reset to 123456, the custom-input does not watch the value change

---
when i click the button,and reset rawvalue to 'abcdef' ,it work

**Comment by posva** [comment]
This is working as expected because it's a bad practice to modify the input while the user is typing, you can, however, force the value of the input on a nextTick:

```js
// inputChange
Vue.nextTick(() => { 
     // I added a ref="input" to custom-input
    this.$refs.input.$el.value = this.rawvalue
})
```

You can also listen to blur to set back the value(https://jsfiddle.net/c69xayhb/)

FYI, the value does equal `123456` even though the input doesn't reflect that

**Comment by mengao89** [comment]
thanks,can you explain why it work on a nextTick?

**Comment by posva** [comment]
Because `v-model` changes the value again before the browser actually displays it
