### ISSUE TITLE
use directive give component/domHtmlElement add class is vue clear.

### ISSUE THREAD

**Issue by wuchuguang** [vuejs/vue#6719]
### Version
2.4.4

### Reproduction link
[https://gist.github.com/roowe](https://gist.github.com/roowe)

### Steps to reproduce
Vue.directive('sf', {
        bind(el, bind, vnode){
             el.classList.add(myclass);//some time myclass is clear.
        }
});
if use user component has :class="check ...."  myclass will auto clear in vue formwork 

### What is expected?
fixed

### What is actually happening?
fixed

---
fixed

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

> if use user component has :class="check ...." myclass will auto clear in vue formwork

That's expected behaviour. you can probably handle the class addition in the `updated` hook of the directive as well to always keep it
