### ISSUE TITLE
syntax check when using webpack, js and ts, singlefile component

### ISSUE THREAD

**Issue by Jack85** [vuejs/vue#6727]
### Version
2.4.4

### Reproduction link
just simple scenario, not really working but just to show what i mean
[https://jsfiddle.net/50wL7mdz/65985/](https://jsfiddle.net/50wL7mdz/65985/)

### Steps to reproduce
if I have parent child components, child is emiting lets say delete event
and I have MISSTYPE in parent view something like <childcomponent @:delete='handler'
it compiles with no error or warning but the event is obviously not catched anywhere unless you find bad syntax by yourself

### What is expected?
error bad syntax

### What is actually happening?
compiles correctly, no error or warning

**Comment by yyx990803** [comment]
Technically you **can** have an event named `":delete"`, so we can't just assume it's bad syntax.

And due to the decoupled nature of events, it's not possible to active detect wrong event names without you writing explicit code telling us what events the child component may possibly emit.

It should be quite straightforward to write a userland plugin that checks `this.$listeners` and assert that they are valid.

**Comment by Jack85** [comment]
In ts inside export class if you try:
```
public :testmethod()
    {
      console.log('er');
    }
```
you get
error TS1005: '=>' expected.

I guess, in babel similar. So to reach state where in template @:testmethod will be valid is not straigtforward.
Plugin is good idea, i just think that this case would be obvious for framework.
