### ISSUE TITLE
Help Drupal CMS to consider Vue.js for its core

### ISSUE THREAD

**Issue by tonystar** [vuejs/vue#6737]
### What problem does this feature solve?
**Problem/Motivation**

At DrupalCon Vienna, Dries (Drupal CMS founder) proposed a new strategic initiative to test and research how our admin UX could be improved by using a JavaScript framework. As a first step, we have to choose which JavaScript framework will be used as part of the research.

### What does the proposed API look like?
**Proposed resolution**

At DrupalCon Vienna, Core committers, all of the JavaScript subsystem maintainers, the Project Lead, as well as developers with real-world experience building decoupled applications using Drupal’s API’s agreed:

Adding a JavaScript framework to Drupal core now is a good idea.
We need to continue researching this before making a final decision.
We want to have sufficient real-use experience to make a final decision prior to 8.6.0’s development period (Q1 2018).
Additionally they decided React would be the preferred solution #2913321: Proposal to use React for building Drupal’s administrative UIs however there has be a strong opinion with some users and developers that Vue.js meets these criteria and would be a better option. The library does not seem to be up for debate in that issue so this is as alternative approach to meeting those requirements.

***

### Please join this discussion and help Drupal to consider Vue.js!

I propose to show your support here: https://www.drupal.org/node/2913628
and your feedback regarding React for Drupal here: https://www.drupal.org/node/2913321

Vue in Drupal core would make Vue.js much more stronger at all!

***

### A precaucious note from the Vue Maintainers:

Please only comment in those discussions if you have some meaningful argument to contribute.

- Don't clog them with useless "I vote for Vue" comments or something similar. That won't help use in any way.
- If you intend to critizise React, do so in a fact-based and civil manner, and argue *for* Vue rather than *against* React.

**Comment by dawehner** [comment]
@tonystar By reading this issue I get the intention Drupal tries to rewrite its frontend using VUE.
As you could read on https://dri.es/drupal-looking-to-adopt-react its only about additional UX improvements of the admin UI. Please clarify that. I think many people miss the point at the moment.

**Comment by adubovskoy** [comment]
>As you could read on https://dri.es/drupal-looking-to-adopt-react its only about additional UX improvements of the admin UI

I think this is just the first step. If Drupal will have Vue in core then we can easily use it as theme framework for frontend, not only for admin UI pages. 

As soon as we get vendor js framework(library) such as vue/react, it means that is no point to use another library inside project. So, choice "between vue/react just for admin UI" is equal to choice "main js-library for whole drupal infrastructure".

**Comment by tonystar** [comment]
@adubovskoy exactly what I initially meant! Let me to gently repeat:

> I think this is just the first step. If Drupal will have Vue in core then we can easily use it as theme framework for frontend, not only for admin UI pages.

> As soon as we get vendor js framework(library) such as vue/react, it means that is no point to use another library inside project. So, choice "between vue/react just for admin UI" is equal to choice "main js-library for whole drupal infrastructure".

**Comment by LinusBorg** [comment]
### A precaucious note from the Vue Maintainers (@linusborg):

* Please only comment when you have some meaningful argument to contribute. Don't flood those disucssions with useless "I vote for Vue" comments or something similar. That won't help use in any way.
* If you intend to critizise React, do so in a fact-based and civil manner, and argue *for* Vue rather than *against* React.

I feel a need to write this as I witnessed the endless flood of useless comments in a similar thread for wordpress.

@tonystar Could you link to this comment in you OP or even better, can I edit it?

**Comment by tonystar** [comment]
@LinusBorg note added. Also- this particular issue is intended to involve Vue Team to the selection process, not for discussion itself.

**Comment by LinusBorg** [comment]
Thanks.

> Also- this particular issue is intended to involve Vue Team to the selection process, not for discussion itself.

That was not really clear to me, thanks.

**Comment by alexfinnarn** [comment]
I think discussing the future of Web Components is really important for this large discussion. I don't know a lot about this topic, but it seems like React is saying that they don't care about Web Components https://reactjs.org/docs/web-components.html. 

From https://vuejs.org/v2/guide/comparison.html#Polymer, the last paragraph of that section talks about Vue.js and Web Components in the future of the project. 

"It is also totally feasible to offer deeper integration between Vue with Web Component specs such as Custom Elements and Shadow DOM style encapsulation - however at this moment we are still waiting for the specs to mature and be widely implemented in all mainstream browsers before making any serious commitments."

So, I think clarifying that statement and what the Vue.js core team thoughts are since that article was written would aid in the discussion. One of the reasons I like Vue.js is that it seems like it will be an easier transition to Web Components when the specs mature than other frameworks, like React. I think a lot of people look towards that comparison article to inform their framework decisions.

**Comment by yyx990803** [comment]
Closing as the issue has accomplished its goal in raising awareness here but the discussion is better continued in the Drupal threads.

**Comment by tonystar** [comment]
Thanks @yyx990803 for the comprehensive answer (https://www.drupal.org/node/2913628#comment-12292622). This is exactly what I expected from this issue!
