### ISSUE TITLE
Getting the value of a rails link tag into vue?

### ISSUE THREAD

**Issue by GiorgioMartini** [vuejs/vue#6746]
### What problem does this feature solve?
I am creating a dropdown menu in vue...

and as i am in Rails... i need to use the value of whats being returned from something like: url_for(backend.job_alarms_path)

But of course this is not available in vue.. whats the best way to get the value into vue?

here is my haml and vue instance: https://imgur.com/a/eaSJl

### What does the proposed API look like?
there is no api

**Comment by LinusBorg** [comment]
Hello @GiorgioMartini 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
