### ISSUE TITLE
Computed property doesn't update when data member updates

### ISSUE THREAD

**Issue by robduv** [vuejs/vue#6788]
### Version
2.4.4

### Reproduction link
[https://jsfiddle.net/khalr0bo/fx1v4ze6/6/](https://jsfiddle.net/khalr0bo/fx1v4ze6/6/)

### Steps to reproduce
Run the JSFiddle. To see the expected behavior, comment out the 'return null' statement.

### What is expected?
The computed property should be recalculated because the 'now' data member is being updated on a regular interval.

### What is actually happening?
The computed property is not recalculated at all.

**Comment by sirlancelot** [comment]
`problematicProp` is never set to anything so the execution of the computed prop `futureTime` is always returning null.

Be sure to brush up on [How changes are tracked](https://vuejs.org/v2/guide/reactivity.html#How-Changes-Are-Tracked).

**Comment by robduv** [comment]
Apologies if I wasn’t clear, but I am expecting the “now” variable’s updates to recalculate the computed prop. Did you see that when you comment out the “return null” line, this does indeed happen?

**Comment by robduv** [comment]
To expand on my previous post, you don't even see the 'Calculating futureTime' log message unless you comment out `return null` on line 26 of https://jsfiddle.net/khalr0bo/fx1v4ze6/6/, which is what leads me to believe Vue isn't properly tracking `this.now`.

Interestingly, if you add another statement above the `this.problematicProp` check (e.g. https://jsfiddle.net/fx1v4ze6/7/), you'll see via the console logs that the computed prop is recalculated, although it is still set as null due to line 30.

**Comment by yyx990803** [comment]
This is totally expected behavior - if you return before the line that accesses `this.now` is even evaluated, then `this.now` will not be registered as a dependency for the computed property. This is in fact the **desired behavior**: because in this case the return result has nothing to do with `this.now`, so re-calculating when `this.now` changes is unnecessary.

Only when `this.problematicProp` becomes truthy will it re-calculate, and then it will track `this.now` because now the returned value depends on it.

**Comment by robduv** [comment]
Thanks all for the quick responses. I've got my actual code working as expected now, and I learned more about Vue's change tracking as well.

**Comment by paulgeorge92** [comment]
I don't know how you got your code working. But what I understood from your code is that the issue is not with the vue but some javascript context issue. you are using 'this' inside the setInterval.
this.intervalId = setInterval(() => {
      console.log('Updating now data item');
      _this_.now = moment.utc();
}, 1000);

when the interval function is called, the 'this' context is changed from vue object to function. so a new property now is set to the function context and not to the vue object.

All you need to do is set  the vue context in a variable before setting the interval.
By doing the above action, you are creating a copy of vue context and using that variable in the interval function.
var _this = this;
    this.intervalId = setInterval(() => {
      console.log('Updating now data item');
      _this.now = moment.utc();
    }, 1000);

see the updated forked fiddle
https://jsfiddle.net/h6tgrxzp/
