### ISSUE TITLE
why 'transition:transform 3s' will be worked when only style.left changed in transition-group ?

### ISSUE THREAD

**Issue by wulj04** [vuejs/vue#6799]
### Version
2.5.0

### Reproduction link
[https://jsbin.com/yovifuw/edit?html,css,js,output](https://jsbin.com/yovifuw/edit?html,css,js,output)

### Steps to reproduce
click three DIVs ,style.left has changed ,transition-duration  worked when 'transition:left 3s' and 'transition:transform 3s',
it not worked when 'transition:opacity 3s' ,it's right.
but why it work when 'transition:transform 3s'?

### What is expected?
'transition:transform 3s' will not work

### What is actually happening?
'transition:transform 3s' works

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Because you have to set every property you want to transition
