### ISSUE TITLE
Incorrect Selection Displayed When Using Non-Unique Option Values

### ISSUE THREAD

**Issue by tbonz** [vuejs/vue#6814]
### Version
2.5.1

### Reproduction link
[https://jsfiddle.net/tbonz/0xx2wxjn/](https://jsfiddle.net/tbonz/0xx2wxjn/)

### Steps to reproduce
In the provided jsfiddle, choose option 'three' from the dropdown, the selected option displayed instead shows 'one'.

### What is expected?
It is expected that the option selected would be displayed.  Using a unique key for each option has no effect either.

### What is actually happening?
It's not showing the option selected, and instead choosing another option with the same value.

**Comment by yyx990803** [comment]
What's the point of duplicate values here? Note that even if Vue doesn't reset the selected item on user interaction, it will still be selecting the first matching option on a fresh render, because there's no key information in the `selectedValue` array for Vue to infer from. IMO duplicate values like this is intrinsically broken design. Instead you should directly bind the entire object as the value:

https://jsfiddle.net/0xx2wxjn/11/
