### ISSUE TITLE
Inconsistent state possible after middle-click on refresh icon on Firefox 56 

### ISSUE THREAD

**Issue by au-travail** [vuejs/vue#6816]
### Version
2.5.2

### Reproduction link
[http://neofoodclub.fr/repro.html](http://neofoodclub.fr/repro.html)

### Steps to reproduce
1. Be on Firefox 56 or more
2. Check the checkbox.
3. Middle-click on the refresh icon in the toolbar.

### What is expected?
A consistent state, either unchecked and false, or checked and true.

### What is actually happening?
The state is checked and false.

---
On Chrome, the resulting state is unchecked and false.
On Firefox 55 or less, the resulting state was checked and true.

Happens on https://vuejs.org/v2/guide/forms.html#Radio with all inputs except the textarea and text ones.
The number inputs result in a consistent state too.

I couldn't make a jsfiddle for it, because Firefox doesn't attempt to restore input state after a midlle-click refresh on jsfiddle.

**Comment by ytbryan** [comment]
Tried on Safari 11.. it's checked and true

**Comment by au-travail** [comment]
On Firefox 57.0b7, the event "input" (but not the event "change") is triggered on the checkbox in the newly opened tab after a middle-click refresh.

**Comment by au-travail** [comment]
I tested:

* vue doesn't react to "input" event on the checkbox.
* The model is updated (text next to the checkbox changes) when I fire a "change" event on the checkbox.

**Comment by au-travail** [comment]
So basically:

* vue.js updates [select](https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js#L122), [checkbox input](https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js#L82) and [radio input](https://github.com/vuejs/vue/blob/dev/src/platforms/web/compiler/directives/model.js#L105) elements after a "change" event, but not after a "input" event.
* Firefox follows [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/change) and only fires the event "change" when the change is committed by the user. On middle-click refresh, the change is automatically done by Firefox and therefore not by user. Consequently, only the "input" event is fired.

**Comment by au-travail** [comment]
I'm wondering what the reasoning is behind the first point. What would happen if we just changed these 3 `'change'` by `'input'` ? This would probably need a lot of browser compatibility checking.

**Comment by yyx990803** [comment]
After trying out possible solutions, I'm closing this as a wontfix. IMO this is something that should be fixed in Firefox:

- The behavior of normal refresh and middleclick-refresh are inconsistent
- It fires `input` and `input` only in this one specific case when every other browser fires `change` only.

It is technically possible for Vue to address this behavior, however:

- It introduces non-trivial complexity into the codebase
- If listening to both `input` + `change` in FF, it causes all listeners to be fired twice, which is non-efficient and may cause unnecessary re-renders if microtasks fire between `input` and `change`.
- If only use `input` event for all those input types in FF, then it breaks user code that expects to trigger `v-model` updates by manually dispatching `change` events.

So, the tradeoff isn't really worth it for such a niche case.
