### ISSUE TITLE
v-if render end tag of element dynamically

### ISSUE THREAD

**Issue by TrendAlan** [vuejs/vue#6822]
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/50wL7mdz/69081/](https://jsfiddle.net/50wL7mdz/69081/)

### Steps to reproduce
refer to the JSFiddle

### What is expected?
I expect the second tbody in the div with class "scroll_div"

### What is actually happening?
an empty table shows up

**Comment by LinusBorg** [comment]
1. The browser strips out the `<template>` element becaue it is not allowed there, according to the HTML spec.
2. Vue templates don't work like handlebars or others where you actually can conditionally add or leave out end tags in favor of other code. you can only iterate over real, complete HTML elements

So this is expected behaviour.

**Comment by TrendAlan** [comment]
Is there any other way I can doing this?

Thank you so much
