### ISSUE TITLE
Lost a event.currentTarget, when pass a event in the props

### ISSUE THREAD

**Issue by edDimensi** [vuejs/vue#6867]
### Version
2.5.2

### Reproduction link
[https://codesandbox.io/s/4jj5p394q7](https://codesandbox.io/s/4jj5p394q7)

### Steps to reproduce
dispatch event and set event in props component.

### What is expected?
event.currentTarget === HTMLElement

### What is actually happening?
event.currentTarget === null;

---
In vue 2.4.4 i not have that problem.
https://codesandbox.io/s/0yj7yq6lon

**Comment by LinusBorg** [comment]
Hi!

Your problem description is lacking a bit of detail. Your reproduction produces 2 alerts, all show the node nname `BUTTON`, I don't encounter any errors, so I don't see what the problem is.

In which file and which method is `event.currentTarget === null;`?

**Comment by edDimensi** [comment]
@LinusBorg check again https://codesandbox.io/s/4jj5p394q7.
Check dependencies, need vue 2.5.2

**Comment by LinusBorg** [comment]
Okay, this is indriguingly odd: Have you tested this outside of codesandbox? Because to me, it seems to be an issue with the way codesandbox does it's magic:

![image](https://user-images.githubusercontent.com/1444526/31817880-227a241e-b596-11e7-9f98-73d4ff6403c8.png)

For some reason, the event object was replaced by a `MessageEvent` Object, and the currentTarget is a `MEssagePort` object, not the DOM object that the event came from. Those objects are created when commmunic with Shared workers though the Channel Messaging API ([see MDN](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API))

Vue does not use `MessagePort` anywhere in it's source, so that object has to come from somewhere else. The fact that this only happens since v2.5.2 is a good startingpoint to further investigate.

**Comment by edDimensi** [comment]
I test it in my project and i have some problem.

**Comment by LinusBorg** [comment]
by "some", you mean "same" problem?

**Comment by edDimensi** [comment]
yes

**Comment by edDimensi** [comment]
https://jsfiddle.net/4rd2rhzf/1/ one more example

**Comment by LinusBorg** [comment]
Okay, that's weird. 

On a sidenote, it's generally a bad idea to save HTMLElements (which the event contains, namely the `currentTarget`) into `data` - Vue will attempt to make this object reactive, and if this element has lots of child elements, this can lead to a stack overflow.

**Comment by edDimensi** [comment]
@LinusBorg 
![image](https://user-images.githubusercontent.com/11390039/31818653-b7735a12-b5a1-11e7-9c0d-1f4ee533c11e.png)

**Comment by Nirazul** [comment]
This is no vue specific behaviour and occurs also with vanilla javascript. I'm not sure why but I suppose that the `currentTarget` gets cleared when event bubbling is over.

Here's an example:
http://jsfiddle.net/pJvZd/106/

**Comment by yyx990803** [comment]
`event.eventTarget` is a transient value - it will become `null` once the event's propagation finishes. In 2.4 we used micro tasks for nextTick, which triggers updates before event propagation resolves, but that led to a number of very hard to fix bugs. In 2.5 we now use a macro task which waits until DOM events have been propagated and resolved.

Even in 2.4, if you access `event.currentTarget` after a frame, it will become `null`. If you need to pass the currentTarget around, you should save it in another variable when you still have access to it,

**Comment by LinusBorg** [comment]
And to iterate: don' save objects like DOM Events or HTML  Elements in the component's data, the "Reactification" of these elements can quickly break your app.

**Comment by edDimensi** [comment]
@LinusBorg then how me send event to prop?

**Comment by posva** [comment]
@edDimensi save what you need in another variable and pass that (what Evan said)
