### ISSUE TITLE
Be able to use different templates in vue components

### ISSUE THREAD

**Issue by algil** [vuejs/vue#7001]
### What problem does this feature solve?
It will give us the possibility to load a template depending of "anything"

### What does the proposed API look like?
Something like

```html
<template :src="isMobile ? './template.mobile.html' : 'template.desktop.html'"></template>
```

or 

```html
<template v-if="isMobile" src="./template.mobile.html"></template>
<template v-if="!isMobile" src="./template.desktop.html"></template>
```

**Comment by Austio** [comment]
Interesting thought.  IMO, this is not something that should be added to core because vue provides several ways to handle currently (the same conditional inside of a template, passed in as a slot from a parent, hoc, custom vue template sections, etc)

**Comment by gluons** [comment]
Wow! It'll be cool if I can import SFC directly without use `import Mobile from './mobile.vue'` in JavaScript. 😃

```vue
<template v-if='isMobile' src='./mobile.vue'></template>
<template v-else src='./desktop.vue'></template>
```

**Comment by posva** [comment]
It's also not possible to add it to core, it could be added to vue-loader but would be transformed into something like:

```html
<template>
     <div v-if="isMobile>Mobile content</div>
     <div v-else>Other content</div>
</template>
```

I personally think it's better to keep this kind of magic out of webpack template because it doesn't improve the way you write your templates enough but, you can write your own loader and put it in front of vue-loader to make the transformation for you
