### ISSUE TITLE
@click.middle/right not working

### ISSUE THREAD

**Issue by zajca** [vuejs/vue#7020]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/6jy8v5g6/](https://jsfiddle.net/6jy8v5g6/)

### Steps to reproduce
click using middel button on text in fiddle with @click.middle

### What is expected?
call function used in @click.middle

### What is actually happening?
nothing 

---
according to docs: https://vuejs.org/v2/guide/events.html#Mouse-Button-Modifiers
in 2.5 they don't work

**Comment by psimyn** [comment]
According to https://github.com/keepgoingwm/vue/commit/e8e291322065b7111e3f50f1d483e8cfab4b2a37 you should use contextmenu instead. Docs should probably be updated

See https://github.com/vuejs/vue/issues/5330

**Comment by yyx990803** [comment]
These modifiers do not work for `click` because the click event does not actually fire for right clicks and middle clicks. Instead, `contextmenu` and `auxclick` are fired respectively.

This can be confusing so I've implemented a normalization in the compiler that transforms `click.right` and `click.middle` to the respective equivalents. Unfortunately, `auxclick` is not supported universally, so we have to use `mouseup` instead, this is not perfect since it would fire even if the click did not start on the element, but it's close enough and a dragged-middle-click seems an extremely rare operation.
