### ISSUE TITLE
Add lifecycle hooks for v-show change

### ISSUE THREAD

**Issue by niutech** [vuejs/vue#7033]
### What problem does this feature solve?
There is no easy way to create a callback when the `v-show` condition changes and the component is shown/hidden. Using watchers is sufficient only for a single property in `v-show`, but it's cumbersome when the condition is like `v-show="a < 1 && !b || c > 2"`. So I propose to add a new pair of lifecycle hooks (events): `shown` and `hidden`.

### What does the proposed API look like?
```
shown() {
    console.log('The component is shown')
}
hidden() {
    console.log('The component is hidden')
}
```

**Comment by yyx990803** [comment]
v-show in its current implementation simply need to toggle a style property on a single element. Making it recursively invoke hooks on components contained inside the element makes it exponentially more complex for marginal benefits. Just use a computed property for your v-show condition instead.

**Comment by Hulkmaster** [comment]
super late for the party, but this would actually make sense for my scenario:

parent
```vue
<child v-show="condition" :chartData="chartData" />
```

1) `v-show` is done for performance reasons.
2) inside the child there is a component (chartjs), which depends on being displayed for correct rendering

which means if chartData is changed -> chartjs is rendered wrongly, and manual re-render trigger if "v-show" condition is changed

right now i have to put watcher on "condition"; do "defineExpose" and call manually "child" function in order to trigger re-render when component is "visible"

with hook would be just

child
```vue
onShow(isShown: boolean) {
  if (isShown) {
    chartjs.update();
  }
}
```

**Comment by niutech** [comment]
Or maybe you can use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to watch for changes of the element's `style` attribute?
