### ISSUE TITLE
Watcher fires after `nextTick` if watched data is changed in `nextTick`

### ISSUE THREAD

**Issue by yaodingyd** [vuejs/vue#7057]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/t23spoua/](https://jsfiddle.net/t23spoua/)

### Steps to reproduce
I have a watcher and its watched data is changed inside a `nextTick`. I want to get its value in another `nextTick`

### What is expected?
I was hoping watcher would fire before the another `nextTick`

### What is actually happening?
All `nextTick` fire before watcher kicks in

---
Watcher run synchronously so watcher should fire before the other `nextTick`

**Comment by yyx990803** [comment]
This is expected behavior.

1. `nextTick` pushes the callback into a deferred queue, so callbacks pushed by `nextTick` in the same event loop will be fired in the same tick.

2. Triggering another watcher when the queue is already flushing pushes its callback to the end of the current queue (instead of firing it immediately).

**Comment by yaodingyd** [comment]
@yyx990803  so what how so I get the expected results?
