### ISSUE TITLE
Component is patching all SVG's elements (in IE) when updateComponent is triggered

### ISSUE THREAD

**Issue by erwinoviedo** [vuejs/vue#7061]
### Version
2.5.3

### Reproduction link
[https://jsfiddle.net/eoviedo/64j9x1f0/](https://jsfiddle.net/eoviedo/64j9x1f0/)

### Steps to reproduce
1. Open the attached jsfiddle in IE 11
1. Open Developer tools
1. Start a new profiling session
1. Hover the text 'Hover me!' with the pointer few times
1. Stop the profiling session
1. Inspect the results and find the overhead

### What is expected?
VueJS should update only the class of the parent element and it should not do any operation with the SVG elements inside the component.

### What is actually happening?
VueJS is calling patchVnode for every SVG element inside the component in IE only

---
This is happening in IE 11 and is fairly noticeable when there are a important number of SVG element in the page.

**Comment by yyx990803** [comment]
Upon investigation, this actually has nothing to do with Vue:

- `patchVnode` should be and is called for every SVG node in all cases, even in other browsers. This is a virtual dom patch so it is very cheap and fast.

- If you look at the IE11 profile more closely, you'll see that the most expensive calls are actually `setAttribute`, which is called when patching the toggled `active` class.

The root cause seems to be that IE11 is simply extremely inefficient when you toggle a class on an element that contains a large amount of SVG elements with `<use href="#...">`. This performance issue can be reproduced without Vue involved.
