### ISSUE TITLE
use symbol value as key

### ISSUE THREAD

**Issue by djfos** [vuejs/vue#7157]
### What problem does this feature solve?
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

symbol is primitive value and very suitable as key.

### What does the proposed API look like?
no warnings with symbol

**Comment by posva** [comment]
The funny thing is the warning is technically incorrect because Symbols is a primitive type.

If we allow Symbols as keys, some people would try to use them as `Symbol(aValue)` and if that is done inside of a computed property, it would change every time the array changes (as Symbol always returns a new Symbol). So I think it would be worthy to also add a not on the docs.
Because after all, it's up to people to correctly use Symbols and most people will still use plain string or numbers id

**Comment by ElVisPL** [comment]
This warning still exists on IE11
