### ISSUE TITLE
X-template in Internet Explorer 11/ or Microsoft Edge

### ISSUE THREAD

**Issue by kobimilan995** [vuejs/vue#7167]
### Version
2.5.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
I m using vue with laravel. And for inline template i use <script type="text/x-template"></script> tag. 

### What is expected?
I expect to see the landing page component in IE/Edge.

### What is actually happening?
I don't get any errors, i just get blank space where component should be.

**Comment by LinusBorg** [comment]
you seem to have posted the wrong fiddle - it doesnt contain any x-template.

**Comment by kobimilan995** [comment]
Oh sorry about that. https://jsfiddle.net/kobimilan995/Lfeyockj/

**Comment by LinusBorg** [comment]
Thanks for the real link, that clears it up. you have to define templates *outside* of the element you mount your app to.

https://jsfiddle.net/Lfeyockj/1/

**Comment by kobimilan995** [comment]
Thanks for the reply, but unfortunately that doesn't seem to fix the issue.

**Comment by LinusBorg** [comment]
Oh well, that x-template is only for a component - you did not define any template for the main instance, so of course it's empty.

Either you define the template inside of the mount element:

https://jsfiddle.net/Lfeyockj/2/

or your define a template for the main instance:

https://jsfiddle.net/Lfeyockj/3/

And by the way, your example didn't even contain a proper a script tag to Vue, so it couldn't run.

**Comment by kobimilan995** [comment]
Is it ok if i post a .blade.php file i have problem with here? It has 600 lines, but 580 are html, they are irrelevant.

**Comment by LinusBorg** [comment]
if you remove the 580 irrelevant lines. ;)

It's not a runnable example but I'll take a look.

**Comment by kobimilan995** [comment]
![blade](https://user-images.githubusercontent.com/31390546/33498525-f89795ac-d6d1-11e7-8468-408449f65500.png)
![app js](https://user-images.githubusercontent.com/31390546/33498526-f8bbfbe0-d6d1-11e7-883d-8f961d477237.png)
![landing vue](https://user-images.githubusercontent.com/31390546/33498527-f8db9d74-d6d1-11e7-85a5-2a9e687ea5de.png)

**Comment by kobimilan995** [comment]
First one is my blade file. Second is how i register the component. And third is the .vue file itself.

**Comment by kobimilan995** [comment]
Once again, it works as it should at chrome

**Comment by LinusBorg** [comment]
1. Why would you put the template outside of a .vue file? The whole point is to precompile it , which requires for the template to be *in* the .vue file. (But to be honest, that may still work somehow, I never tried.)
2. Then you also use `Vue.customElement()`, which is a sepearate plugin we don't maintain.
3. Then the main file still looks as if you have nested the template *inside* of the part of the page that will be controlled by the main instance. (I can't tell because you don't show how the main instance it set up, but it seems that way because the template is directly beneath the custom element) ..or you don't have  a main instance because you use custom elements?
4. where is the compiled javascript inserted? at the end of the page?

Anyway, I can't debug this, this is not a basic setup. My guess would be that you can't use an x-template because of 1. and/or 2.

**Comment by LinusBorg** [comment]
Afterthought: did you add a polyfill for the custom elements? IE doesn't support those.

**Comment by kobimilan995** [comment]
Hmm. Didn't do that. I m putting it outside the .vue files because i need a lot of blade methods to use inside the template, and if i pass them all as a prop it could get messy. Can you maybe suggest me an alternative for better communication within blade files and vue components?

**Comment by kobimilan995** [comment]
You have no idea how much i appreciate your help! Polyfill for custom elements fixed the issue! Thank you very very much!
