### ISSUE TITLE
Reactivity in Component

### ISSUE THREAD

**Issue by joaomaridalho** [vuejs/vue#7179]
### Version
2.5.9

### Reproduction link
[http://lv.webds.org/condicoes-de-servico](http://lv.webds.org/condicoes-de-servico)

### Steps to reproduce
When you  click to expand the blocks in the page using a data property the value is passing into the parent and updating all properties inside data.

### What is expected?
That when I update the property in data the parent properties don't get altered

### What is actually happening?
property in data is  updating the prop and the prop updating the data in parent

---
When I pass down props to a component and use the prop to define a property inside data and change it's content, the prop updates the parent element.

In my data I want that InitialItems to keep the initial testes value
My data Function:
data: function() {
    return {
      items: this.testes,
      default_classes: "",
      xs: "col-"   this.testes.col[0]._extra_small,
      sm: "col-sm-"   this.testes.col[0]._small,
      md: "col-md-"   this.testes.col[0]._medium,
      lg: "col-lg-"   this.testes.col[0]._large,
      xl: "col-xl-"   this.testes.col[0]._extra_large,
      InitialItems: this.testes
    };
  }

**Comment by posva** [comment]
I don't know where this is coming from but it may happen because of the nature of js, if you pass a nested object, you're passing a reference, and therefore modifying it will modify the original object as well. You have to actually clone it (`initialItems: {...this.testes}` or a deep cloner like lodash's)

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂. Also, a website is not a repro, we need an editable, **boiled down** reproduction

**Comment by joaomaridalho** [comment]
Hi,
Im sorry but I do consider this a bug...
I will explain in a more simple way, and maybe im missing something:
if for example I store in a new variable the props:
```
export default {
  props: ["testes"],
  data: function() {
    return {
      items: this.testes,
    };
  },
  methods: {
    expand(ind) {
  this.items.list[0].expanded = true;
    },
  }
};
```

1. I store the props "testes" in items .
2. Then I call method "expand"
3. I store a new value to the this.items.list[0].expanded = true
4. This storage affects the original props "testes" when it should only affect the "this.items"

Hope I clarified the issue.

**Comment by yyx990803** [comment]
If this is a bug then it needs a reproduction. Please read the requirements.
