### ISSUE TITLE
Cultures not working in Vue which looks like dynamic routing issue

### ISSUE THREAD

**Issue by dexterhussain** [vuejs/vue#7201]
### Version
2.5.9

### Reproduction link
[https://github.com/hmuhdkamran/Cms ](https://github.com/hmuhdkamran/Cms )
Live Website Working at
sqanetcore.thetowertech.com

### Steps to reproduce
Just open the website and open chrome console window it will start showing error. 

### What is expected?
It should run properly and start working as it is working in development server.

### What is actually happening?
I am making a website on Vue using aspnetcore 2.0 which i am using development there is no bug no issues it is working perfectly fine when I am rolling it out to production it is giving me error 
 http://192.168.7.14/api/culture/SupportedCultures 500 (Internal Server Error)
192.168.7.14/:1 Uncaught (in promise) 
{messageTypeId: "Error", text: "Request failed with status code 500", title: "Code:undefined. Error"}
messageTypeId
:
"Error"
text
:
"Request failed with status code 500"
title
:
"Code:undefined. Error"
__proto__
:
Object

**Comment by hmuhdkamran** [comment]
I am facing the same problem

**Comment by posva** [comment]
Sorry but a full project is not a valid repro, it has to be boiled down to the minimal

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by dexterhussain** [comment]
@posva 
I just uploaded code because you cannot do routing. the basic issue is not in the code as it is perfectly working Okay on development machine as soon as it is made production it stops working,
