### ISSUE TITLE
Watcher strange behavior

### ISSUE THREAD

**Issue by sandra1n** [vuejs/vue#7261]
### Version
2.5.11

### Reproduction link
[https://jsfiddle.net/457xmwr7/](https://jsfiddle.net/457xmwr7/)

### Steps to reproduce
Open link. View code

### What is expected?
message must be "hello night stalker"

### What is actually happening?
message is: "why?"

---
why? this happens? why watch method is called?

**Comment by posva** [comment]
It happens because by setting the message in mounted, you trigger a new render and because you're using a plain objectin the v-bind, it's then triggering the watch because it creates a new object every time it renders (because it's `:wtf="{}"`). If you had that object in data instead, it wouldn't trigger the watcher because the value of the wtf prop wouldn't have changed just after mounting

**Comment by sandra1n** [comment]
Hello @posva 
Thanks for explanations.

----------------------------------------------------------

Maybe you know how would be better to do: 
I need prop(wtf Object type). Then i need a watcher for this prop, becase some parent components may update my **message**.
Watcher need to call only when that Prop changes really (not how in my example)

And i have in mounted() event triggers $on. with fresh data, delivered by axios. (with another version of message)
But i can't see my fresh data, because prop wtf always update my message with old.

**Comment by posva** [comment]
create a computed property so it doesn't create a new object everytime it renders
