### ISSUE TITLE
Nested slot would not work

### ISSUE THREAD

**Issue by Fuji-sunny** [vuejs/vue#7275]
### Version
2.5.11

### Reproduction link
[https://jsfiddle.net/SunnyLyu/t1cxqox4/](https://jsfiddle.net/SunnyLyu/t1cxqox4/)

### Steps to reproduce
Just open the jsfiddle can see NOTHING in result panel. And that's the result of the reproduction.

### What is expected?
What I expected to see the DOM should be:
&lt;div&gt;
    &lt;p&gt;label&lt;/p&gt;
    &lt;p&gt;field&lt;/p&gt;
&lt;/div&gt;

but the result DOM is: 
&lt;div&gt;&lt;/div&gt;

and inside the code, the alerts print "undefined" of both this.$slots.label and this.$slots.field.

### What is actually happening?
Is there any suggestion about how we can use nested slot in Vue?

**Comment by sqal** [comment]
It does not render anything because Vue uses template for parent component defined in template option in the script tag, and this template is incorrect, you're using only default slot there instead of namd slots (label, field). The template in HTML block is almost correct, you just need to wrap your paragraphs in <child> component.  Here's fixed example: https://jsfiddle.net/uo3vah90/

Documentation on name slots - [named slots](https://vuejs.org/v2/guide/components.html#Named-Slots)

**Comment by Fuji-sunny** [comment]
@sqal 
yeah, your fixed example is worked! 
Further more, in my situation, I want to pack child tag inside parent tag, which can be used more convenient. People can only use parent tag with the two slots instead of using both parent tag and child tag.

**Comment by yyx990803** [comment]
The slot name is only respected 1 level down - so when the content gets passed to the child, it becomes the default slot.
