### ISSUE TITLE
the same element v-show do not have link relationship

### ISSUE THREAD

**Issue by lasthrun** [vuejs/vue#7288]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/v2v8llxk5](https://codesandbox.io/s/v2v8llxk5)

### Steps to reproduce
1. check App.vue, you can see router view have v-show="true"
2. check components/Hello.vue, you can see v-show="false" in the root

### What is expected?
component should be hidden

### What is actually happening?
component still have show

---
i think v-show should have a && linked.

**Comment by posva** [comment]
The thing here is you are explicitly showing the element by adding v-show on the parent because **it counts as an override**. Put it another way: it's as if you declared a style (eg font-size) on the child (hello.vue) and then override it in the parent (app.vue). The one on the parent would take precedence and this is intentional to allow users override component-specific attributes.

For your case you can always move the `v-show` to a nested `div` or similar or directly provide a prop to toggle visibility

**Comment by lasthrun** [comment]
i know we can solve this problem in some easy way, but there are still some case need this logic.
just think about a tabs of table, and it support search keyword. the tab will use v-show to control what tab should be show. and the table record have it own v-show to check is it should be show. but now, we just can use some solution that do not match our plan logic.

**Comment by lasthrun** [comment]
i don't think put some logic that should in another component into a child component is a good solution.
