### ISSUE TITLE
Component are re-rendered even if not needed 

### ISSUE THREAD

**Issue by titouancreach** [vuejs/vue#7300]
### Version
2.5.13

### Reproduction link
[https://codepen.io/anon/pen/dJpomx?editors=1011](https://codepen.io/anon/pen/dJpomx?editors=1011)

### Steps to reproduce
Render a component with no children (no parameter) and with an empty array have a different behavior. With an empty array, the component is re-render every time the parent change, even if it doesn't depend of the parent. With no parameter, the component is updated correctly. 

### What is expected?
Don't render Foobar if not needed

### What is actually happening?
Render every time

---
https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/115 The link of the issue I opened in vuejs jsx.

**Comment by LinusBorg** [comment]
I'm unsure if we should judge the behaviour of Vue wrong here. What happens it recieves and array of children for the 'FooBar' component's slots, so it causes a re-render.

Since it's a an empty array everytime, that would not be strictly necessary, but the question  is if we can verify that reliably and in a performant way. If i.e. the array had content in the previous render, it *should* cause an update, so we would hagve to compare that `oldArray.length === newArray.length === 0` to optimize this.

The other thing is that the JSX plugin appearantly creates those empty arrays for components that don't have a slot in the first place, so we should definitely triage that other issue independently - depending how this one here gets judged.

**Comment by yyx990803** [comment]
I think this is a pretty rare special case only caused by incorrect transpilation in the jsx plugin. The empty Array should be eliminated whenever possible, as is done in the template compiler. Let's track that in the jsx plugin repo.

As for the reasoning of updating, @LinusBorg has explained it pretty well. Note that even if there is slot content and the content did not change, they'd still be fresh VNodes that need to be diffed in order to ensure consistency. Having a special case for empty arrays isn't really a meaningful improvement in terms of perf.
