### ISSUE TITLE
"slot-scope" name is very misleading, true and clearer name is "slot-props"

### ISSUE THREAD

**Issue by genedronek** [vuejs/vue#7307]
### What problem does this feature solve?
This rename will reduce needless confusion around using slots.   The current name "slot-scope" is rather misleading because "scope" is the wrong concept to suggest; particularly given Angular's use of scope.  The true and correct concept is "props".    My suggested name change, will render current developer confusions moot.    You will have less explaining (and developer questions) to answer.

I know a 2nd rename is gross, but it will help make learning Vue easier.

### What does the proposed API look like?
Add slot-props (alias) for slot-scope, prefer "slot-props" in documentation.   deprecate the spelling "slot-scope"

**Comment by LinusBorg** [comment]
This can be considered anecdotal, but: 

I'm running our forum and am a regular in our chats and on StackOverflow. I can't recall a single question where that naming eas vonfused with Angular's $scope.

Furthermore, 

* the concept of "scoped slots" exists since Vue 2.1 and is standard Vue vocabulary at this point.
* Before we introduced `slot-scope` in 2.5, we havd this:
```html
<template slot="someName" scope="props">

</template>
```
To me, the change from `scope="..."` to `slot-scope="..."` seems natural, while I would suspect that `slot-props` might confuse anyone who has worked with scoped slots previously.

That being said, I certainly won't deny that there is and alswass has been potential for confusion between Vue's concept of `scope` and that of angular, but as I said, it doesn't seem to be a prevalent problem.

I would also agree that, could we turn bakc time and  introduce the feature in `2.1` withe the synatx we have since `2.5` right from the start, going with `slot-props` would prbably have been better.

At this point in time however, with `scoped slots` being an established concept in the Vue community, I don't think that your suggestion offers enough improvement to warrant what is essentially a deprecation of the current syntax (while adding another special attribute that could collide with existing apps).

So my bottom line would be: I'munconvinced, but not 100% opposed either.

**Comment by genedronek** [comment]
LinusB thank you for your time and helpful explanation/consideration.   Yes I agree with your assessment.

**Comment by genedronek** [comment]
LinusB,
My bad.   I must admit my personal confusion over "slot-scope" pivoted on Evan's stretching of the word "scope" for one of his many genius framework features.   At one point I stumbled into a low-level runtime diagnostic that revealed *exactly* how he was transpiling the "scope" attribute.   Freaking clever technique.  yes, perhaps egregiously misnamed, but I still have to find wherever my socks blew off to.  

LinusB, your comment text was educational to me.  Thanks again for the history and your time.
I have been working on a documentation example that may be helpful.   And will share that after I integrate this recent discovery.     Now, where did my socks land?

**Comment by pixelgrid** [comment]
@genedronek what is that runtime you are referring to? im trying to dive into Vue internals and that might be a good starting point

**Comment by genedronek** [comment]
Here is the  link to my fortuitous slot discovery.  [slot scope compiling](https://forum.vuejs.org/t/what-can-be-assigned-to-slot-scope/24195)

Perhaps my choice of calling "runtime" arises from learning NUXT framework and SSR (ServerSideRendering) vue.js where I did not see exploding templates until later on after SSR; during client-side ("runtime") evaluation.

**Comment by genedronek** [comment]
enough.
