### ISSUE TITLE
Custom attributes are not valid

### ISSUE THREAD

**Issue by alrdytaken** [vuejs/vue#7309]
### What problem does this feature solve?
* being buffered by linting- / validation-tools about the invalid html
* risking conflicts with future html / svg / MathML-specs

### What does the proposed API look like?
# short version
Instead of ```<… v-bind= …>``` use ```<… data-v-bind= …>```

# long version
I think I can add to the discussion on https://github.com/vuejs/vue/issues/273 but unfortunately I am not allowed to, so I opened this duplicate.

**Why it buffers me much:**
* Any html-validator I know – Node.js, browser-plugin, IDE – thinks it is invalid and will tell me so.

**Why it buffers me minor:**
* The specs gave us the _data-_ for custom attributes so we can be sure not to conflict with native attributes in future specs. Since native attributes will be intepreted as is in source-code I think that JS will remove the invalid attributes is not a fitting argument.
* custom attributes with _data_ also have there own JavaScript API. I like how it differs the code from native attributes structurally and visually.

**Why I think it's great**
* I think _data-_ might be more bloated but that is a problem with the specs.

**Comment by yyx990803** [comment]
My opinion has been fully stated at https://github.com/vuejs/vue/issues/273#issuecomment-252372047 - this is not something we will ever consider. Also, changing the syntax at this point is a practical impossibility because the whole ecosystem is built upon the existing syntax.

**Comment by alrdytaken** [comment]
> changing the syntax at this point is a practical impossibility because the whole ecosystem is built upon the existing syntax
Well, case closed, I guess. Thanks for your reply.

**Comment by caimaturo** [comment]
What should we do when using inline templates in a non-SPA website? Even if Vue converts the markup to valid HTML5 when executed, it wouldn't be valid initially, when the page loads.

I'm a little confused because it seems, as seen in most issues and forum answers that the only recommended or imposed way to use it is with Single File Components, previously compiled, despite Vue's progressive approach.

I know that this isn't a common practice anymore but there are cases where I'd like to use Vue as a library to add some functionality to existing HTML (WordPress theme for instance) yet have valid HTML. Should I be worried about this anyway?

**Comment by sebastiencail** [comment]
We want to use vue js to create components on a website developed with Apache Wicket. Vuejs invalid html code generates server side errors when html is parsed by wicket. This constraint makes the use of vuejs in an Apache Wicket application incompatible.

see https://github.com/apache/wicket

**Comment by PhantomYdn** [comment]
@sebastiandedeyne , recommend to check out [Vuecket](https://github.com/OrienteerBAP/vuecket) - it's the project to integrate VueJS and Apache Wicket.

**Comment by sebastiencail** [comment]
@PhantomYdn Thank you, interesting project, I will see if it can match our need
