### ISSUE TITLE
how to use this in v-for

### ISSUE THREAD

**Issue by blaze87** [vuejs/vue#7338]
### Version
2.5.13

### Reproduction link
[https://codepen.io/blaze87/pen/rpyjYK](https://codepen.io/blaze87/pen/rpyjYK)

### Steps to reproduce
when i use this.$route.parmas in v-for ;i get an error:$route is undefine

### What is expected?
i want use this.$route.parmas in v-for

### What is actually happening?
when i use this.$route.parmas in v-for ;i get an error:$route is undefine

**Comment by LinusBorg** [comment]
1. You already opened 3 other issues with this question
2. in your second issue, you also received an answer: https://github.com/vuejs/vue/issues/7337#issuecomment-354247803
3. As explained on new-issue.vuejs.org, the issue tracker is **not** meant for support questions. please use the forum (forum.vuejs.org) or the chat (chat.vuejs.org)

If you open more issues for this topic we might have to consider blocking you.

**Comment by blaze87** [comment]
@LinusBorg 
1 the other second issue tip me for Invalid issue
2 #7337 the ans is not right  ，It's very perfunctory
3 how to distinguish is questions or is bug

**Comment by blaze87** [comment]
@LinusBorg  #7339 Ask the same question

**Comment by LinusBorg** [comment]
> #7337 the ans is not right ，It's very perfunctory

Since you don't share runnable code, only a snippet of a template, we can't actually tell what the erorr is. The only error we can see in what you shared, is that you use `this` where you should not.

So this third issue is against our rules as well, since your "reproduction" isn't a reproduction, it's a codepen with a template snippet and 0 lines of Vue code.

You are making our work harder by opening issues that don't follow the rules, please don't.

> how to distinguish is questions or is bug

When in doubt, ask others on forum or chat first.

I will lock this issue for that reason now.

**Comment by yyx990803** [comment]
请仔细看清楚开 issue 的要求，如果你连花点时间看清楚要求都做不到，那也不能指望别人为你花时间。
