### ISSUE TITLE
Bug with v-model.lazy, undeclared object fields and view update.

### ISSUE THREAD

**Issue by totalamd** [vuejs/vue#7348]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/uLtxtfnf/](https://jsfiddle.net/uLtxtfnf/)

### Steps to reproduce
1. type smth in "declaredString" input
2. type smth in "undeclaredString" input

### What is expected?
1. `declaredString` `input` to be updated as well as `obj['declaredString']` model
2. `undeclaredString` `input` to be updated as well as `obj['undeclaredString']` model

### What is actually happening?
1. `declaredString` `input` and model updates as intended
2. `undeclaredString` `input` resets (becomes empty) every time the model (and therefore the view) updates.

---
`undeclaredString` starts to update as intended in any of next cases:
* if you comment `{{ counter }}` interpolation
* if you remove `.lazy` modifier
* if you declare `object` field in advance in `data` section
* if you managed to make input change between model/view update so string become declared

**Comment by posva** [comment]
Unfortunately, by adding the `lazy` modifier to an undeclared variable, you are explicitly telling vue to wait when till the input is blurred to set it. Therefore, by design, everytime vue renders it will use the value, here non-existent, to fill the input, so it clears out.
Ideally, you should declare it (always do if possible). You can isolate the template in a component (https://jsfiddle.net/eoLepb4n/) to make sure it doesn't get re-rendered

**Comment by totalamd** [comment]
Thank you for explanation.
