### ISSUE TITLE
Bind implementation is slower when native in modern browsers

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue#7408]
### Version
2.5.13

### Reproduction link
[https://jsperf.com/vue-bind-perf](https://jsperf.com/vue-bind-perf)

### Steps to reproduce
Run tests across some modern browsers to see the result.

### What is expected?
Custom bind implementation performance is the same level as native.

### What is actually happening?
Custom bind implementation performance is lower than native.

---
Tested in:
* Safari - native is **slower 83%**
* Chrome - native is **faster 61%**
* Edge - native is **faster 91%**
* Firefox - native is **faster 52%**

I believe it is not an issue at all, but I think it is something which can be improved.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report! 

JS engines didn't optimize fn.bind in past and we record that fact in comment. But JS engines are constantly evolving and our implementation is slower, haha.

Since Function.prototype.bind is more used in JS world, I believe JS engines will optimize the native usage more, like [this](https://bugs.chromium.org/p/v8/issues/detail?id=6946). It seems better to use native one.

**Comment by dmitry-vakhnenko** [comment]
PR: https://github.com/vuejs/vue/pull/7445
