### ISSUE TITLE
history模式突然失效

### ISSUE THREAD

**Issue by xuxiaoxiao312** [vuejs/vue#7459]
### Version
2.4.1

### Reproduction link
[https://app.ladybirdedu.com/#/questionnaire/2](https://app.ladybirdedu.com/questionnaire/2)

### Steps to reproduce
源代码：
// export 路由示例
export default new Router({
  mode: 'history',
  scrollBehavior (to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition
    } else {
      return { x: 0, y: 0 }
    }
  },
  routes
})

### What is expected?
url按照history模式显示

### What is actually happening?
url按照hash模式显示

---
路由一直是history模式，但是今天我在没有修改路由相关代码的前提下，写别的组件代码时，页面突然变成了hash 模式，诡异的是只有在我默认使用的Chrome浏览器上会有这个问题，safari 不会出现这个问题
在chrome 浏览器中的效果
![image](https://user-images.githubusercontent.com/24541297/34934090-1fa575be-fa14-11e7-86d9-e8d89d657a2d.png)
在safari中的效果
![image](https://user-images.githubusercontent.com/24541297/34934190-81d197b8-fa14-11e7-9447-1d73f80a911d.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Also, this is related to vue-router. If it turns out to be a bug, make sure to open an issue there with a **boiled down** reproduction 🙂
