### ISSUE TITLE
Functional component is rendered prematurely

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#7588]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/bjqxwLka/](https://jsfiddle.net/bjqxwLka/)

### Steps to reproduce
Check console logs.

### What is expected?
Foo component should not be rendered before ajax call is completed (setting `fetching` to false). 

### What is actually happening?
In Card component I render placeholder text while fetching the data (line 31) otherwise i render its children. And although Foo is initially hidden, somehow its render function gets gets called. Important note. This is only happening when Foo is a functional component, if you remove `functional: true` from Foo then you'll see that it gets rendered only after `Ajax finished` log.

**Comment by posva** [comment]
Hey, thanks for opening an issue.
This is actually expected behaviour because the functional components get rendered in the parent component before being passed to your `Card` component.
However, there is a simple trick using a function. You can, for example, do it with scopedSlots to make sure the functional component is only rendered when you call it: https://jsfiddle.net/j2rocr6r/ You can of course also use a function as a prop
