### ISSUE TITLE
The slot shows information one step from the past

### ISSUE THREAD

**Issue by SnosMe** [vuejs/vue#7601]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/zxjk2k3nkm](https://codesandbox.io/s/zxjk2k3nkm)

### Steps to reproduce
Click on the radio buttons and see that the checked state has the previous one

### What is expected?
Just pressed button has the checked state

### What is actually happening?
Previous pressed button has the checked state

**Comment by ralphchristianeclipse** [comment]
You're modifying .active on the array

    setTab (idx) {
      this.tabs[this.activeTab].active = false
      this.tabs[idx].active = true
      this.activeTab = idx
    }
which doesn't work on vue's reactivity

You must use Vue.set on that one

Vue.set(this.tabs[idx],"active",true)

**Comment by SnosMe** [comment]
Please fork and test your solution first.
- switching tabs works fine, the problem is not related to it
- your code breaks what works

I think that I'm doing something wrong with the `key`. Vue's reactivity thinks that it does not need to be rerendered (`this.$slots.input`), but in fact it is necessary.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.
The direct reason is that `$slots` is only updated after child component's render function call. 
![image](https://user-images.githubusercontent.com/5557143/35878562-a3ad9ba6-0bb3-11e8-846a-544a314c86d2.png)
(The modified demo: https://codesandbox.io/s/q824l05l24)

This is due to how vue updates view - render function gets called from parent to child.
![image](https://user-images.githubusercontent.com/5557143/35878714-11aaff40-0bb4-11e8-8d75-d1a17d6e1c1a.png)

So in your example, when `selectedUser` is updated, root render function is called first, then `tabs`'s render function which calls `tab.renderTitle` (while tab's $slots.input is outdated),  and lastly `tab`'s render function, that finally updates $slots.input.

Therefore, there's nothing vue could do here - your code is actually working against vue's fundamental update logic, that is, trying to get child's render result inside parent, before child can be rendered. Please consider changing your implementation.
