### ISSUE TITLE
Case discrepancy between regular event names and sync modifier event names

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue#7613]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/www2xo5k5w](https://codesandbox.io/s/www2xo5k5w)

Case should be consistent across the entire framework when it comes to emitting events. In this repo, you can see that using `$emit()` with snake-case events works, but using snake-case with a sync modifier fails (sync expects camelCase). This inconsistency leads to confusion and mistakes.

**Comment by posva** [comment]
It's not being consistent, what happens is that `:sync-text.sync` expands onto `:sync-text` + `@update:syncText`.
This is something we will reconsider in next version but we cannot change it now as it will be a breaking change.

But feel free to improve the section in the docs: https://vuejs.org/v2/guide/components.html#sync-Modifier
We could definitely have a small example with `some-text` instead of `foo`.
It would be great if you could submit a PR at https://github.com/vuejs/vuejs.org 🙂

**Comment by ffxsam** [comment]
@posva Sure, I'd be glad to open a PR when I get a chance!

Another approach instead of a breaking change would be to slowly introduce it, e.g. start printing a console warning that event names emitted in snake case will be deprecated. During that transition period over a few versions, both snake case and camel case event names could be supported. Eventually the snake case is phased out.
