### ISSUE TITLE
While building, local CSS in components getting overridden with Global CSS 

### ISSUE THREAD

**Issue by lijukrks** [vuejs/vue#7616]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/1pc2e9yj/2/](https://jsfiddle.net/1pc2e9yj/2/)

### Steps to reproduce
1. Added Global CSS  in main.js ( say Bootstrap.min.css)
2. Adding  a  CSS class in component level scope
3  Build a production build

### What is expected?
Priority for component level CSS.

### What is actually happening?
Priority for global CSS.

**Comment by posva** [comment]
Make sure to include the CSS from libraries first:

```js
// main.js
import Vue from 'vue'
import 'bootstrap/css/bootstrap.css' // I don't know where it is
import App from './App'

// rest of the code
```

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue in the relevant repository (template or vue-loader in this case) if it turns out to be a bug 🙂

**Comment by lijukrks** [comment]
Thanks for the comment 

I have fixed it in this way already if I used to write my CSS in the component scope then why it is overridden by global CSS? component level CSS have the priority right? if I am wrong please correct me.

**Comment by posva** [comment]
It also depends on the css rule specificity but that a completely different topic unrelated to Vue 🙂
