### ISSUE TITLE
自定义的过滤器组件，使用搜狗输入法会无法输入中文

### ISSUE THREAD

**Issue by brahmachen** [vuejs/vue#7621]
### Version
2.1.10

### Reproduction
封装组件实现字母自动大写的过滤器，用搜狗输入法无法输入中文，输入的是大写字母
### Steps to reproduce
VplateInput.vue
```javascript
<template>
    <input
        type="text"
        class="form-control"
        ref="vinput"
        v-bind:value="value"
        v-on:input="updateValue($event.target.value)"
        v-on:blur="formatValue"
    >
</template>
<script>
export default {
    props: {
        value: {
            type: String,
            default: ''
        }
    },
    mounted: function () {
        this.formatValue()
    },
    methods: {
        updateValue: function (value) {
            var result = value.toUpperCase();
            this.$emit('input', result)
        },
        formatValue: function () {
            this.$refs.vinput.value = this.value.toUpperCase()
        }
    }
}
</script>
```
使用：
```html
<vplate-input v-model.trim="plateNumber" />
```

### What is expected?
如果输入的内容有字母则自动转为大写字母，输入中文则保持原样

### What is actually happening?
用搜狗输入法无法输入中文
比如输入鲁B12345，就会变成LUB12345

**Comment by JounQin** [comment]
监听中文文本输入不能用 input 事件，见：https://developer.mozilla.org/zh-CN/docs/Web/Events/compositionstart

**Comment by posva** [comment]
You will get the value when the composition ends

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
