### ISSUE TITLE
vue router push 到的 route 如果有redirect， 参数无法传递到新地址

### ISSUE THREAD

**Issue by Fangty1** [vuejs/vue#7632]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/50wL7mdz/97494/](https://jsfiddle.net/50wL7mdz/97494/)

### Steps to reproduce
vue-router 2.5.3
vue 2.5.13
//
vue 通过name, params 方式路由。 如果路由目标有配置 redirect ， 那么第一个目标路由 和最终的redirect都收不到params

### What is expected?
vue-router 2.5.3
vue 2.5.13
//
vue 通过name, params 方式路由。 如果路由目标有配置 redirect ， 那么第一个目标路由 和最终的redirect都收不到params

### What is actually happening?
vue-router 2.5.3
vue 2.5.13
//
vue 通过name, params 方式路由。 如果路由目标有配置 redirect ， 那么第一个目标路由 和最终的redirect都收不到params

**Comment by posva** [comment]
In your fiddle you don't have any params but you can actually pass params any way you want (https://router.vuejs.org/en/essentials/redirect-and-alias.html)
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue (**in vue-router repository**) if it turns out to be a bug 🙂
