### ISSUE TITLE
v-bind:class no work

### ISSUE THREAD

**Issue by NineSay** [vuejs/vue#7636]
The selector name cannot contain '-' or '_'.
For example
no work
```
<button v-bind:class="btn-bg-blue"><button>
<button v-bind:class="btn_bg_blue"><button>
```
can work
```
<button v-bind:class="btn-bg-blue"><button>
```

**Comment by sirlancelot** [comment]
When you use `v-bind` or just `:`, Vue is expecting a valid JavaScript expression for the attribute value. Neither of those values are JS expressions, you'll want to surround the value with single quotes like so: `<button v-bind:class="'btn-bg-blue'"></button>` But since you're just providing a static string it's better to remove `v-bind` entirely. [`v-bind` documentation](https://vuejs.org/v2/api/#v-bind)

**Comment by NineSay** [comment]
OK! Thanks!
