### ISSUE TITLE
[Suggestion] Cache vm.$emit data

### ISSUE THREAD

**Issue by LucasLeandro1204** [vuejs/vue#7662]
### What problem does this feature solve?
If a listener is instantiated after the event is emitted, it will not get triggered. So if the value is cached, the listener will be triggered even after the event is emitted.

### What does the proposed API look like?
Add a flag parameter to cache the value

```javascript
vm.$emit('foo', { bar: 'baz' }, true);
```

Thank you people, awesome job <3

**Comment by LucasLeandro1204** [comment]
And I can do it, if accepted =)

**Comment by LinusBorg** [comment]
What would be a real-life scenario where this can be useful? I'm trying yo bff earns in which situation you would apply a listener on a child component only later and not upfront

**Comment by posva** [comment]
I don't think this is a good idea because it will replay all previously `$emitted` cached events whenever you attach an event listener which looks like a very specific use case

But it can be implemented in userland by replacing `Vue.prototype.$emit` and `Vue.prototype.$on` with your custom implementation that call the original one 🙂
