### ISSUE TITLE
[async component] add an API to reload load failed async component

### ISSUE THREAD

**Issue by jiananshi** [vuejs/vue#7717]
### What problem does this feature solve?
Currently vue async-component use http to load js file which may fail due to network break or timeout, if there is an API exposed in a way which can make `errorComp` lead user to interact and try to reload this component instead of refresh the whole page.

In addition, detailed error should be exposed to the `errorComp` so that it can show different states based on the error, tks in advance.

### What does the proposed API look like?
```vue
<template>
  <p v-if="$asyncComp.error">{ $asyncComp.error.message }</p>
  <button
     v-if="$asyncComp.error && $asyncComp.error.name === 'NETWORK_TIMEOUT'"
     @click="reload">click to reload</button>
</template>

<script>
  export default {
     methods: {
       reload() { this.$asyncComp.reload(); }
     }
  };
</script>
```

**Comment by posva** [comment]
I don't think this is a good idea because it should be easier to handle at an application level what can or cannot be displayed if there's no internet connection.

If you need a dynamic approach where you can retry fetching the component, you can implement it in userland by using a data property that you set to the result of the promise that resolves the component. Making it easy to trigger a new request.

**Comment by yyx990803** [comment]
This can be done with your own wrapper component. It doesn't need to be built-in.

**Comment by Mighty683** [comment]
https://codesandbox.io/s/vue-template-c63ne

If anybody would search for solution.
