### ISSUE TITLE
when use v-model with Array prop, update prop unexpected by someway.

### ISSUE THREAD

**Issue by Rouberg** [vuejs/vue#7718]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/5uLrp7w6/](https://jsfiddle.net/5uLrp7w6/)

### Steps to reproduce
step1. open

step2. click tab `replied`.

The detail I wrote in comments.

### What is expected?
component update it's share data between parent component should be more strict.

I wish statement `list[0].active = true` should work.

### What is actually happening?
statement `list[0].active = true` work unexpected, and it modified share data between it's parent component.

**Comment by posva** [comment]
This is inherent to javascript nature: objects are passed by reference so all components end up modifying the same object.
BTW, you should declare `active` in the initial data.
I'm not sure why you are hardcoding values in your example but maybe this is what you want to do: https://jsfiddle.net/441w01qv/

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
