### ISSUE TITLE
Can I use vue to develop static websites

### ISSUE THREAD

**Issue by kavanLi** [vuejs/vue#7754]
![image](https://user-images.githubusercontent.com/33696428/37008029-2de11f4c-211b-11e8-8b84-5091879b6cf5.png)
![image](https://user-images.githubusercontent.com/33696428/37008032-30dcbed6-211b-11e8-8833-725abfdf608c.png)
I need to develop a static website like the above image, this static web may have 15 pages. Can I use vue to make it out? or other things like html   bootstrap is better? or there is aother technich that I can use?

This is my question? Anyone familiar to static web can answer me? Thanks in Advanced.

**Comment by maxirozay** [comment]
Yes you can and your issue will be closed because you didn't respected the issue template.

**Comment by posva** [comment]
Check Nuxt.js if you want statically rendered websites
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by kavanLi** [comment]
thanks, get it
