### ISSUE TITLE
Unclear update schedule

### ISSUE THREAD

**Issue by vitaly-t** [vuejs/vue#7758]
Why regular releases halted after Dec 19, 2017? This is now an unusually long delay for the next update.

Usually on GitHub one provides a milestone that points at what is going on in terms of the next update, but you do not have any. You only [have 3 old ones with 0 issues in them](https://github.com/vuejs/vue/milestones).

Please update and maintain the [milestones](https://github.com/vuejs/vue/milestones) that would gives a clear picture of where the project at in terms of the next update/release.

**Comment by vitaly-t** [comment]
Auto-closed, wow! That's no good. 😞

**Comment by frlinw** [comment]
@vitaly-t https://github.com/vuejs/roadmap

**Comment by vitaly-t** [comment]
@frlinw Thank you!

I still think that milestones should be maintained as the standard way of planning an update, plus this is where developers on GitHub check first of all.

**Comment by yyx990803** [comment]
Auto closed because we have clear issue policies in the issue template which you obviously didn't read ;)

Just because GitHub has milestones doesn't mean we have to use them. It's up to the maintainers to decide how and where to manage plans for the project. Also, next time when you make suggestions to an open source project, consider using a tone that actually sounds like a suggestion rather than making demands like a paying customer.

**Comment by vitaly-t** [comment]
I was being polite in my suggestion. And from what you are saying, only those who pay you get to make suggestions, while the rest will just have to dance around 💃 

>  It's up to the maintainers to decide how and where to manage plans for the project.

Sounds positively autocratic.

**Comment by yyx990803** [comment]
Anyone can make suggestions given its proposed in a proper manner. You request was also a valid suggestion, while being a bit on the entitled side.

And please stop stretching my words.
