### ISSUE TITLE
Configurable 'document' reference

### ISSUE THREAD

**Issue by mihajlo-brankovic** [vuejs/vue#7769]
### What problem does this feature solve?
I'm using .vue components containing html and styles. I want to use a container wrapped into an iframe. I'm using the following code. 

    new Vue({
      el:iframeContainer,  // reference to a container element within an iframe
      template: '<Panel/>',
      components : { Panel }
    });

The rendered html gets injected properly, but the generated style tag does not. It gets injected into the default (main) document head element, which makes no sense in this case cause it's isolated from the rendered html.

One solution would be to have an option to configure custom document object. 
Another option would be to make sure that both (html and styles) get injected into the same isolated context (document).     

I would prefer the first one. 

### What does the proposed API look like?
Vue.options.document = myIframe.contentDocument.

Vue.document = Vue.options.document || document;

**Comment by posva** [comment]
Hey, this is not something that can be fixed in Vue core, it is related to either the webpack config or to vue-loader usage. Maybe you should check https://vue-loader.vuejs.org/en/, you may be extracting the CSS in a scenario you don't want to, but that's webpack question and we prefer you use other channels like the forum or the discord server to ask it 🙂

**Comment by yyx990803** [comment]
This is something the build setup really wasn't designed for. You probably want to use a different build setup if you want a component to target an iframe - instead of relying on `vue-style-loader` for the final style insertion, remove it (make `css-loader` the last loader for your CSS) and handle the insertion yourself:

``` js
import css from './foo.css'

export default {
  mounted () {
    // insert CSS yourself
  }
}
```

**Comment by mihajlo-brankovic** [comment]
Thank you for the clarification.

This actually worked for me:
```
{
        test: /\.vue$/,
        loader: "vue-loader",
        options: {
          loaders: {
            ......
            scss: [{
                loader:"style-loader",
                options:{
                  insertInto: '(iframe selector)'
                }
            }, "css-loader", "sass-loader"],
            .....
          }        
        }
      }
```
