### ISSUE TITLE
default slot replaced but also executed and throw errors

### ISSUE THREAD

**Issue by rawbin-** [vuejs/vue#7773]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/rawbin/8y1vsc9h/8/](https://jsfiddle.net/rawbin/8y1vsc9h/8/)

### Steps to reproduce
chid with default slot and render incorrect data

### What is expected?
no error， or just replace and not execuite

### What is actually happening?
execute and throw unrelated errors
![image](https://user-images.githubusercontent.com/8169783/37187193-20d9ff6a-2384-11e8-89da-e25408cdacd0.png)

### background
https://jsfiddle.net/rawbin/wL5u5097/

**Comment by posva** [comment]
Please follow the errors provided in the console. Here's a version with no errors following the console errors: https://jsfiddle.net/2zr02nvs/
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by rawbin-** [comment]
@posva  use the index instead of the item can work around this error to throw, but the reason to show the error is the templated in the child component expected to be replated but computed as not expected 
it's expected to be not computed or rendered
