### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by zhangenming** [vuejs/vue#7774]
### Version
2.5.13

### Reproduction link
[https://codesandbox.io/s/xlz0rk5roq](https://codesandbox.io/s/xlz0rk5roq)

### Steps to reproduce
1 vue init webpack vueDemo

2 change main.js 
template: "<App/>"  --->>> template: "1<App/>" 
will get a [Vue warn]

3 change index.html
 <div id="app"></div> --->>> <div id="app">2<App/></div>
will rendered string 2

that's get a Different results

### What is expected?
that's get a same results

### What is actually happening?
that's get a Different results

**Comment by posva** [comment]
Vue needs a root element to mount, so it cannot be `2<App/>`, but it can be `<div id="app">2</App></div>`

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by zhangenming** [comment]
sorry
but
```
<div id="app">
     <a>
        <App/>
        <App/>
        <App/>
     </a>
</div>
```
it's only get one App,and
```
template: "<a><App/><App/><App/></a>"
```
will get three App
