### ISSUE TITLE
Checkbox binding not working

### ISSUE THREAD

**Issue by Sparki2002** [vuejs/vue#7782]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/Sparki2002/dnjrjkmn/2/](https://jsfiddle.net/Sparki2002/dnjrjkmn/2/)

### Steps to reproduce
1. Create a data property named "value"
2. Create a input element with checkbox type on your template and bind it's value attribute to the value property
3. Run the code and check and uncheck the checkbox while observing the value property

### What is expected?
The value property should be the same as the checkbox check state

### What is actually happening?
- The value property is always false

---
- It's working on Firefox (59/60), but not on Chrome (64/65).
- I've also tried using the checked attribute on the input element
- I can't use v-model because of other mechanisms in my code

**Comment by maxirozay** [comment]
You should use `v-model`.

`<input v-model="value" type="checkbox">`

**Comment by posva** [comment]
What @maxirozay said. You can also listen to the `change` event

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
