### ISSUE TITLE
textarea with v-model cannot be updated dynamically

### ISSUE THREAD

**Issue by enricribas** [vuejs/vue#7789]
### Version
2.5.14

### Reproduction link
[https://jsfiddle.net/50wL7mdz/175796/](https://jsfiddle.net/50wL7mdz/175796/)

### Steps to reproduce
change the textarea to enter some text, try to clear it with code.
an input works fine, but textarea does not.
shift click the button, text clears
shift-enter, log fires, text does not clear.

### What is expected?
it should clear

### What is actually happening?
it does not clear.

---
thanks for looking into this.

**Comment by posva** [comment]
It doesn't clear because enter also changes the variable. Add `.prevent` to make it work the way you want.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by enricribas** [comment]
thank you, will do. I guess input works because it doesn't change the value? Seems like I should be able to change the value 'after' enter has changed it. Ah well.

PS. I tried googling for 30 minutes to find a solution before posting. It's not always easy to find answers.
