### ISSUE TITLE
Usage of vue app in an iframe embedded in index.html of a website.

### ISSUE THREAD

**Issue by akash-potdar7** [vuejs/vue#7877]
### What problem does this feature solve?
I'm not sure if its a feature to meet my usecase, i think not. Let me propose it anyway.
So, my usecase is, my application is something like a chatbot. Starts from user embedding a async js call to my js file from his index.html and that js will do the chatbot work. Basically iframe is the best solution. But then I'm sourcing my iframe body's onload to get client.js sourced so that vue is mounted to index.html . The issue is it is not picking up the XYZ.vue styles.

### What does the proposed API look like?
There's no api in the usecase yet

**Comment by posva** [comment]
This is not related to vue. In the best case, it could be related to vue-loader but please,  consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
