### ISSUE TITLE
Could you please support using symbol value for ":key" field(when using v-for doing list rendering)?

### ISSUE THREAD

**Issue by gitby15** [vuejs/vue#7936]
### What problem does this feature solve?
When I using "v-for" to render an list, every "instance" in the list has an "id",
I would like to use a symbol type to express my "id" , and fill my "id" into ":key".
Every thing is OK until my "id" has duplicate（Example: push same "instance" into list twice by mistake）

In function "checkDuplicateKeys", when Vue detected duplicate key, it will log a warning, the warnning code is :
```js
"warn(
            ("Duplicate keys detected: '"   key   "'. This may cause an update error."),
            vnode.context
          );"
```
When the file "key" is symbol type, the browser will throw an error because jointing a symbol value with string, and then byebye my application.

I check the document, It didn't tell us that we can use an symbol into key, so I think it is not a bug.
So, could you please support symbol type in list rendering?

### What does the proposed API look like?
<template>
  <ul>
     <li v-for="(item, idx) in list" :key="item.id">{{item.content}}</li>
  </ul>
</template>
<script>
import ...
 export default Vue.extend({
     data(){
          return {
              list:[{id:Symbol('id), content:'a'},{id:Symbol('id), content:'b'},{id:Symbol('id), content:'c'},{id:Symbol('id), content:'d'}]
          }
      }
  })
</script>

**Comment by posva** [comment]
It works fine: http://jsfiddle.net/jgbsjoxs/
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by mpawelski** [comment]
It was also not clear for me that symbols as keys are supported. Untill I searched github and found it's explicitly [supported](https://github.com/vuejs/vue/pull/7271) since [v2.5.12](https://github.com/vuejs/vue/releases/tag/v2.5.12).

I think [documentation](https://vuejs.org/v2/api/#key) should be updated and say that `key` can be `number | string | symbol`. Also console warning _[Vue warn]: Avoid using non-primitive value as key, use string/number value instead._ should be changed to _[Vue warn]: Avoid using non-primitive value as key, use string/number/**symbol** value instead._

Then it will be more obvious that this is supported, and not just "happens to work by accident".

**Comment by posva** [comment]
@mpawelski could you open a pull request at vuejs/vuejs.org please if there isn't one already?
