### ISSUE TITLE
 IOS 11.3 WeChat web page video click cannot play

### ISSUE THREAD

**Issue by qiangyuxiao** [vuejs/vue#7951]
# Version
 2.5.2
# Link to minimal reproduction
https://mzkr830q3y.codesandbox.io/
# Steps to reproduce
* IOS11.3 system and real machine
* Open web link in WeChat
* Click on the video play button
# Problem code
```
created() {
      Bus.$on('playVideo', (item) => {
        this.showVideo = true;
        this.item = item;
        this.handle_play();
      });
    },
methods: {
      handle_play: function () {
          this.showVideo = true;
           setTimeout(() => {
             const video = this.$refs.video;
             try {
               if (!video.paused) {
                // video.pause();
                this.pause(video);
              } else {
                // video.play();
                if (this.canfullScreen()) {
                  this.play(video, true);
                } else {
                  this.play(video);
                }
              }
            } catch (e) {
              console.log(e);
            }
          }, 0);
      }
}
```
# What is expected?
* IOS11.3 system, normal video playback
# What is actually happening?
* IOS11.3 system, click on the video, has been loaded, can not play
* IOS other versions  and  Android click on video in WeChat, can play normally
# Any additional comments? (optional)
 * Previously when upgrading vue2.5.2, encountered a problem with the execution timing of $nextTick, downgraded using setTimeout(function(){}, 0)
* Through the delay time, such as: setTimeout (function () {}, 100), can repair IOS11.3 WeChat web pages can not play the problem
* Suspected timing issue with Vue 2.5.2 on setTimeout(function(){}, 0) in IOS 11.3 systems

**Comment by sodatea** [comment]
The reproduction link is broken due to several failing resources hosted on some unknown (maybe internal?) domain (https://css.intra.weibo.cn). Please provide a valid reproduction.

As for the described problem, https://github.com/vuejs/vue/issues/7109#issuecomment-346494821 might be related, and there's a workaround in the subsequent discussions.

As for the event loop issue, we'll likely revert to always using microTasks as Evan stated [here](https://github.com/vuejs/vue/issues/8109#issuecomment-385546524).
