### ISSUE TITLE
Support for exporting function for functional component

### ISSUE THREAD

**Issue by titouancreach** [vuejs/vue#7954]
### What problem does this feature solve?

Read support for HOC component, composition...

### What does the proposed API look like?
instead of exporting an object like:

```javascript
export default {
  functional: true,
  name: 'myComponentName',
  render(h) {
    return h('div', 'Hello World');
  }
}
```
We could also export directly the render function 
```javascript
export function myComponentName(h, context) {
  return h('div', 'Hello World');
}
```
Since our component is now a function, we can compose it much easier.

**Comment by LinusBorg** [comment]
Well, the component isn't a function in a technical sense. We still use that options object internally to describe it.

One reasons that we can't simply use a function is that this would collide with the way async components work:
```
Vue.component('myAsncComponent', () => import ('./someComponent.vue'))

/// or locally in a component:
components: {
  'myAsncComponent': () => import ('./someComponent.vue')
}
```
When a component registration is done with a function (that is not a Vue contructor), it's assumed that it's an async component.
```javascript
Vue.component('functionalComponet', function (h, props) {
  return h('div', 'Hello World')
})
```
The above code will break since Vue doesn't expect a render function, and there's not clean way to tell a render function from a loader function for an async component, so it's not really possible to implement that with the current API.

**Comment by titouancreach** [comment]
Thanks for answering, I understand that is not possible with the current API but is it something that Vue would like to implement ?

**Comment by LinusBorg** [comment]
We will surely think about how to make functional components easier when we work towarda Vue 3, but that is still a log time down the road.
