### ISSUE TITLE
Get list of all mixins of a component

### ISSUE THREAD

**Issue by netstuff** [vuejs/vue#7955]
### What problem does this feature solve?
Is there way to get all component mixins as a list?
For example, it would be useful to collect (merge) default options from each of mixin. Because every mixin must extend functionality with same options. Or realize some functionality in dependence of existing mixins.

### What does the proposed API look like?
Vue.mixin

**Comment by posva** [comment]
`$options.mixins` should work
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by netstuff** [comment]
Thank you very much, @posva. And sorry :)
