### ISSUE TITLE
var decodingMap and function decodeAttr do not properly decode all HTML entities from template

### ISSUE THREAD

**Issue by kidplug** [vuejs/vue#7994]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/286784/](https://jsfiddle.net/50wL7mdz/286784/)

### Steps to reproduce
In a template, in an HTML attribute, use any HTML entity not included in the "decodingMap" variable.

### What is expected?
HTML entities present in the HTML template should be decoded properly by Vue prior to being set into the DOM.

### What is actually happening?
Vue is only decoding a few entities (specified in var decodingMap) and ignoring all others, which really includes the full unicode charset.

---
In vue.js:8765 is the var decodingMap which only decodes lt, gt, quot, amp (and sometimes newline and tab).
This is not the proper way to decode attribute values.  ANY HTML entity can be used in an attribute value.

**Comment by yyx990803** [comment]
This is a wontfix. The reasoning:

1. It is not necessary to encode HTML entities inside attribute values.

2. The decoding map in the HTML parser is only for handling **some** browsers' auto-encoding behavior. In some browsers, for example with `<div foo="<">`, when we extract the `outerHTML` from the element, some browsers return `<div foo="&lt;">` instead of `<div foo="<">`.

Simply put: **you should not be encoding anything inside your attributes**. If you want Vue to handle the case you showed in the repro, you need to have a convincing reason on why you are doing it in the first place.

**Comment by kidplug** [comment]
@yyx990803 the use case I have, is to include a newline char aka code 10 as an HTML entity inside an HTML title attribute.  I think its a legit reason to use an encoded char in a template.

**Comment by kidplug** [comment]
@yyx990803 also the template source can come from anywhere - not necessarily from an existing part of the DOM on which you extract outerHTML.   In my case I'm pulling the HTML from a standalone .html template file.  Seems intuitive to me that any valid HTML from an .html file should be interpreted properly by Vue when used as a template.

**Comment by kidplug** [comment]
@yyx990803 But thanks for at least understanding what the issue is and giving a meaninful response.
@posva was not grasping my previous issues.

**Comment by qgates** [comment]
@yyx990803 I have a similar use-case to @kidplug. I'd like newlines inside title attributes and Vue won't allow it. Though this could be considered an edge-case it's a fairly common requirement, no?

**Comment by yyx990803** [comment]
As a workaround: `<p :title="'foo\nbar'">{{ message }}</p>`

**Comment by qgates** [comment]
Thank you very much @yyx990803!

I'd just gotten there v-bind:title using data or computed property, but this is closer to native. Shame we can't have a more intuitive approach - perhaps a directive to passthrough vanilla HTML with attributes?

**Comment by jackframework** [comment]
I want to set the unicode of icon font at the HTML attribute.

**Comment by networkimprov** [comment]
Workaround should be mentioned in API doc.

I ran into this for placeholder `:placeholder="' \u2315'"`

**Comment by twogood** [comment]
Thank you @kidplug for raising this issue and #7970! I too would have wished it solved in Vue.js but for now will make a workaround.

@yyx990803: Our .NET Core Razor framework encodes "+" signs for us whether we like it or not and for legacy reasons we need to compile this HTML with Vue.compile(). So we need full entity decoding in attributes.

**Comment by davisre** [comment]
I can add that both erb and haml, the two most commonly used templating languages in ruby on rails, escape both single and double quotation marks, which makes sense because those frameworks allow attributes to be delimited with either single or double quotation marks -- which is valid HTML -- so you need a way to include the delimiter in the value.

It'd be really nice if vue added support for an escaped single quotation mark -- `&#39;` -- like it already has for a double. Without that, dynamic values in attributes are a headache.

**Comment by lengthmin** [comment]
as a workaround:
```vue
<span
  v-html="`<a class='u-email' href='mailto:${$siteConfig.email}'>${$siteConfig.email}</a>`"
></span>
```

using v-html to render true HTML
