### ISSUE TITLE
Page not showing on iPad specifically

### ISSUE THREAD

**Issue by Maaiketol** [vuejs/vue#8008]
### Version
2.5.16

### Reproduction link
[https://codepen.io/maaiketol/pen/PRgVpO](https://codepen.io/maaiketol/pen/PRgVpO)

### Steps to reproduce
You'll have to open the link in ipad. And you'll see that it'll show: 

{{person.-name}}
{{person.title}}

### What is expected?
That the persons will show up like they do when opened in a browser .

### What is actually happening?
It is not showing me the right content, but it's showing me only {{person.-name}}
{{person.title}}

**Comment by posva** [comment]
If you see `{{ something }}` it is because some of the code is wrong and there is an error in the console you should check (make sure you are using the non-minified version of vue to test). Please, check that before opening an issue and when you open an issue, please boil it down to make sure it is actually a bug.
You can always ask questions (and often get faster answers) in the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js)
