### ISSUE TITLE
Getting an error when mixin CSS Module mode .vue components

### ISSUE THREAD

**Issue by meikidd** [vuejs/vue#8054]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/k21mq7qp5v](https://codesandbox.io/s/k21mq7qp5v)

### Steps to reproduce
mixin with the .vue component which turned on CSS Module mode.

```
// MyComponent.vue
<script>
import MyMixin from "./MyMixin";

export default {
  name: "MyComponent",
  mixins: [MyMixin],
  created() {
    console.log(this.$style);
  }
};
</script>

<style lang="scss" module>
.yellow {
  color: yellow;
}
</style>
```

```
// MyMixin.vue
<template>
  <div :class="$style.red">I'am MyMixin</div>  
</template>


<script>
export default {
  name: "MyMixin"
};
</script>

<style lang="scss" module>
.red {
  color: red;
}
</style>
```

### What is expected?
merge the $style object, and the output of console.log($style) is expected be `{red: "...", yellow: "..."}`

### What is actually happening?
throw an error: `TypeError: Cannot redefine property: $style`

**Comment by posva** [comment]
A mixin doesn't bring a style with it. They're actually meant to be pure js objects, not vue components (with a template). They are meant to mix logic
If you want to share the style between components it's much easier (and natural) to create a separate file and import that one.
That being said, this is something that would need to be fixed in vue-loader as that's where the `$style` is injected but this is not how mixins were meant to be used

**Comment by meikidd** [comment]
Thanks for your reply. I think you are right, a mixin should be pure objects with logic.
But when I try to use `extends` instead of `mixin`, I still get the same error.
