### ISSUE TITLE
Camel case property names in inline template

### ISSUE THREAD

**Issue by melihkorkmaz** [vuejs/vue#8086]
### Version
2.5.16

### Reproduction link
[https://codepen.io/melihkorkmaz/pen/yjaVJp](https://codepen.io/melihkorkmaz/pen/yjaVJp)

### Steps to reproduce
I have a component which has requried prop as function named "onSelectionChange". When I use this component in a x-template I can use v-bind:onSelectionChange="myFunc" and it works. But if I want to use this in an inline template I have to use v-bind:on-selection-change="myFunc". Is this correct?

### What is expected?
I'm expecting to use same prop name either in x-template or inline-template

### What is actually happening?
I have to change prop name to use my component in an inline-component.

---
I added codepen repo, but it's not working. I put my code in there just describe my problem.

**Comment by posva** [comment]
Unfortunately, this is an HTML limitation, tag names are converted to lower case.
You're not limited by that when using Vue files.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
