### ISSUE TITLE
Vue route object gets freeze by vue's core

### ISSUE THREAD

**Issue by furyscript** [vuejs/vue#8091]
### Version
2.5.13

### Reproduction link
[https://github.com/samturrell/vue-breadcrumbs/tree/master/example](https://github.com/samturrell/vue-breadcrumbs/tree/master/example)

### Steps to reproduce
I'm using this plugin https://github.com/samturrell/vue-breadcrumbs but have a problem by getting the route params using for breadcrumb.
The problem, as you can see on open issue https://github.com/samturrell/vue-breadcrumbs/issues/1 , is that vue-router freeze the object and it's impossibile to manage params.
It's easy to reproduce, just install plugin and create two route with dynamic params. Links aren't replace when found `:id` (or something) but they keeps string literally.

You can find example in link

### What is expected?
Get route params chain

### What is actually happening?
Just explain into steps to reproduce

**Comment by yyx990803** [comment]
1. This is a 3rd party plugin issue.

2. Even if it's related to Vue, it should be reported to the vue-router repo.

3. The route object is an immutable mapping of the current URL. **This is by design.** You should never attempt to mutate the route object. Instead, trigger a navigation with `$router.push`.
