### ISSUE TITLE
Make it possible to set static classes within the attrs hash on a data object

### ISSUE THREAD

**Issue by emileber** [vuejs/vue#8098]
### What problem does this feature solve?

The doc on [data objects](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth) is kind of misleading:

> ```
>   // Normal HTML attributes
>   attrs: {
>     id: 'foo'
>   },
> ```

Since [`staticClass` isn't listed](https://github.com/vuejs/vuejs.org/pull/621), I was wondering why my `attrs: { class: 'static-class' } }` wasn't added to an element. I find it odd to have to do `class: { 'static-class': true }`.

### What does the proposed API look like?

@chrisvfritz [said in the doc issue on static class](https://github.com/vuejs/vuejs.org/pull/621#issuecomment-384812777):

> I think `attrs: { class: 'my-class' } }` might make sense as an alias for `class: { 'my-class': true }`.

**Comment by armandomendivil** [comment]
you can user something like
```
<div :class="getClass" />

getClass() {
  return 'static-class'; // or whatever you want to return
}
```

**Comment by emileber** [comment]
@armandomendivil this feature request is about **data objects** specifically, which are often used with functional components. This is not a question issue.

**Comment by fnlctrl** [comment]
If your functional component doesn't need to merge outer classes, why not just do
`class: 'static-class'`?

**Comment by fnlctrl** [comment]
I guess you assumed `class` option to only accept objects, but it actually accepts string literals too:
https://jsfiddle.net/kgLgq7k2/
So there's no need for the proposed alias.

**Comment by chrisvfritz** [comment]
> I guess you assumed `class` option to only accept objects, but it actually accepts string literals too.

I think that assumption is my fault, as we don't make that clear in the current docs. I'm fixing that now. 🙂 I also honestly forgot that it accepts the same interface as a class binding (including arrays as well). 😅

**Comment by emileber** [comment]
@fnlctrl `class` can be an object, a string and an array. I know how it works.

The thing is, `staticClass` is different from `class`.

```js
{
  class: { static: false },
  staticClass: 'static'
}
```

In this case, the result is `class="static"`.

**Comment by fnlctrl** [comment]
> staticClass is different from class

> it's a little frustrating that it's not documented

I don't understand why `staticClass` being undocumented and behaving different could be the reason to include another alias...

`staticClass` is intentionally left undocumented to reduce the API surface, and avoid the `which one to use?` and `what's the difference?` and `why another class field?` questions that people may have. Though it is in fact stable enough to use in production - it would never be removed for 2.x as vue enforces strict compatibility between different versions of runtime/compiled code.

If you've seen other libs use it and want to use it too - cool. But as it's not intended to be part of the public API, it would remain undocumented.

**Comment by emileber** [comment]
Maybe a warning about `staticClass` would be better than nothing. The alias was @chrisvfritz idea, which is better than nothing.

> `staticClass` is intentionally left undocumented to reduce the API surface

This is hurting more than it helps.

**Comment by emileber** [comment]
The templates makes it possible to use `<element class="static" :class="{dynamic}" />` and it's counter intuitive that `attrs: { class: 'static' }` doesn't work. 

It could be left undocumented, but it should at least work.

**Comment by fnlctrl** [comment]
If `attrs: { class: 'static' }` is made to work then we introduce other complexities:

1. Should `attrs: { class }` work with array/objects like `class`?
2. Should `attrs: { class }` be merged with `class`? Or should `attrs: { class }`  take precedence and override `class`?

I don't see value in adding another way to do exactly the same thing as `class: 'string-literal'` that can potentially lead to confusions. 
`class` is already good enough to solve your original use case, and is the one single way to bind classes throughout the documentation. That's why I see no need in introducing another alias that breaks the consistency.

**Comment by emileber** [comment]
It could work as `class="static"` on an element, as it already does within templates.

> another alias that breaks the consistency.

Consistency is already broken since `class` isn't included in the "normal HTML attributes".

**Comment by chrisvfritz** [comment]
> A lot of Vue plugin and libraries use `staticClass` and it's a little frustrating that it's not documented 

@emileber I can understand that frustration. It's a tricky situation, but I still think the end result of documenting it would be _more_ confusion, as people misuse it because they don't fully understand the subtle behavior.

> the attrs alias would be a great way to make it accessible as it seems obvious from the doc

@fnlctrl I still agree this would be useful, because they _are_ HTML attributes. It's intuitive for users that they be allowed in `attrs`. Thinking about it more though, @emileber, I think this just isn't easily feasible the way we handle `class` and `style` internally - and it may not be something we can fix without breaking changes.

To give a little background, I find the way we currently treat `class` and `style` problematic. They're the only HTML attributes that:

- aren't (and _can't_) be included in `attrs`
- aren't included in `$attrs`
- don't respect `inheritAttrs: false`

But long story short, I agree (obviously) that it'd be great to have `class` and `style` work inside `attrs`, but it may be something we'll have to wait until Vue 3 for, when we can do a more general overhaul.

**Comment by emileber** [comment]
I understand, and now that this discussion is documented in the issues, it's better than nothing! Thanks guys! 👍

**Comment by emileber** [comment]
Another confusing thing that I just remembered, static classes applied on a **functional** component by a parent (`<my-functional class="static" />`) will not be applied by default and are not present in the data object `class` or `attrs` properties.

They are only available in the undocumented `staticClass`.

**Comment by IlCallo** [comment]
Tip for anyone reaching here for my same reason.
You can access and update `staticClass` at run-time, eg. into `mounted` hook, via `this.$vnode.data.staticClass` (provided that both `data` and `staticClass` are defined).

Note that you still have to make the component to update to make the changes effective.
I used `this.$forceUpdate()`, maybe there is a better way.
