### ISSUE TITLE
IE problem using directive to uppercase input v-model

### ISSUE THREAD

**Issue by ArthurGreve** [vuejs/vue#8158]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/ktycksy6/](https://jsfiddle.net/ktycksy6/)

### Steps to reproduce
Using Internet Explorer, type on the input anything that ends with a letter [eg: asdas, 1234r, w1e2d] and remove the focus from the input.

### What is expected?
Input keeps new value typed.

### What is actually happening?
The input value goes back to previous value.

---
I'm working on a project where some input[type=text] values must be uppercase, and so, I created a directive that as the user types a value it would automatically uppercase the letter.

It works on Chrome, by the way, but it doesn't on IE.

**Comment by posva** [comment]
While the behaviour may seem weird, you should never directly modify the value of the input if you use `v-model` because it's splitting up the source of truth.

Instead, you should use a computed property with a setter that sets the text to an uppercase value: https://jsfiddle.net/s3qrsnyp/

if you want to keep the lazy behaviour, you will have to play with two variables

**Comment by ArthurGreve** [comment]
Thanks @posva for your reply.
I'll do as you say.
