### ISSUE TITLE
is vm._computedWatchers available?

### ISSUE THREAD

**Issue by XiaoLuo01** [vuejs/vue#8164]
### What problem does this feature solve?
Ihave many variate be watched in computed property . And I want to get the all variate from computed property at a time , so I can put this variates into a Array, and I find a vue instance of vm._computedWatchers can get all variate , but I can't find this in vue official website . so I want to make sure this property is available?

### What does the proposed API look like?
computed: { quickType() { return this.getSearchValue('quick') }, titleExpre() { return this.getSearchValue('title') } .... more },

**Comment by posva** [comment]
Anything starting with `_` is pretty much private.
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by XiaoLuo01** [comment]
ok thank, sorry to bother you
