### ISSUE TITLE
tabs keep-alive memory leaks

### ISSUE THREAD

**Issue by axy541877028** [vuejs/vue#8209]
### Version
2.5.2

### Reproduction link
[http://panjiachen.github.io/vue-element-admin/#/example/table/dynamic-table](http://panjiachen.github.io/vue-element-admin/#/example/table/dynamic-table)

### Steps to reproduce
http://img.cdn.test.jookee.com/1526866395000Video_2018-05-21_092951.wmv    
If the link step is repeated 2-3 times or more, memory is checked for memory leaks

### What is expected?
With different levels of routing jump I will clear the value inside the include, the same level will not, in order to achieve cache local function

### What is actually happening?
Repeatedly, memory usage continues to increase, feeling that the memory of the vue instance or the cleared component is not cleared. Click several times is very easy to memory leak, I used this method in the project, the effect is greater Click twice to use memory 100M

---
Tabs Keep-alive how to free cached memory

**Comment by posva** [comment]
This is not a valid repro. It must be minimal and editable. Otherwise it would be very difficult for us to know if the problem comes from your implementation or from Vue.

---

You can us the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) to seek help 🙂
