### ISSUE TITLE
Can vue support "template url"?

### ISSUE THREAD

**Issue by peipeichengbao** [vuejs/vue#8211]
### Version
2.5.16

### Reproduction link
[https://cn.vuejs.org/v2/guide/components-edge-cases.html#X-Templates](https://cn.vuejs.org/v2/guide/components-edge-cases.html#X-Templates)

### Steps to reproduce
I don't want to use ".vue" and webpack because my web page size need smaller. So I just use "<script src='assets/js/vue.min.js'></script>". Now, I need to package some components and I found that vue only support "template", I must write my view as string or use "text/x-template", but "x-template" divided view and controller into two scripts. So, is there a better solution?

### What is expected?
just like angular's templateUrl

### What is actually happening?
X-template becomes hard to maintain when components become more and more.

**Comment by posva** [comment]
If you want your webpack to be smaller, **you should be using vue files and webpack**. You can always codesplit components (check async components in docs)

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
