### ISSUE TITLE
DOM out of sync for input changes when vNode value match new current state.

### ISSUE THREAD

**Issue by diervo** [vuejs/vue#8215]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/0qo6z8x6qw](https://codesandbox.io/s/0qo6z8x6qw)

### Steps to reproduce
In the example we have an input which accepts numbers. 
If an alphanumeric character is introduced, we want to reset the input to the initial value "100"
With the default value set "100", typing a number and then a letter, things work as expected and the value is reset.
With the default value set "100", typing a character will result in to the DOM being out of sync.

### What is expected?
The DOM should always be in sync with the property value.

### What is actually happening?
DOM gets out of sync: If after a DOM modification on an input the value happens to be the same as the current vNode value, the diffing will ignore the node and leave it untouched.

---
I believe this is due to a problem on the algorithm for vNode diffing where we just check for === from vNode properties.
I found very odd that this issue hasn't been raised since it seems that any sort of inline normalization of values could potentially run into this cases.

Maybe there is a trivial workaround or different pattern for this type of cases?

**Comment by posva** [comment]
This is working as expected, what is happening is that the component doesn't rerender because the prop hasn't changed as you are basically doing `this.state = "100"` while `this.state` is already `"100"`
If you want to constrain the input value, you will have to modify the actual element `value`.
Another solution is to always sync the value and use a computed property on the component to use a valid value, or a watcher to communicate a new value.
There are other options, and one will probably fit your project better, but that's something that you can discuss in other communication channels like the discord, forum or SO

**Comment by sqal** [comment]
I has a similar problem once and I think this answer may help you understand what's going one here https://github.com/vuejs/vue/issues/7506#issuecomment-372139382

 + possible solution https://codesandbox.io/s/6vklw7pjm3

**Comment by diervo** [comment]
The problem with that approach is that it fundamentally breaks encapsulation.

I do like the workaround from @posva even though it requires the developer of that component to be aware and do the manual sync.

To give more context, we are using snabbdom in the context of custom elements and web components where you can't just freely reach out to arbitrary nodes.

We were interested in seeing what VueJS take on it was since it exhibits the same behavior/bug that was reported to us from our developers.

Certainly I was not expecting any change since it has dramatically perf implications everywhere :)

Thanks for the quick responses.
