### ISSUE TITLE
console.warn when Vue is already defined on window

### ISSUE THREAD

**Issue by gtarsia** [vuejs/vue#8226]
### What problem does this feature solve?
I went from referencing vue from unpkg from an html `<script>` to using webpack.  
I forgot to remove those `<script>`, so I went a bit crazy because Vue.set wasn't doing anything.  

I think this warning would really help with that problem for people making that mistake when migrating to webpack.

### What does the proposed API look like?
I don't think the API would change.

**Comment by posva** [comment]
Apart from this being a bit too much for Vue as it also involves how bundling is done (since modules create scopes and writing `Vue.set` instead of `window.Vue.set` may yield different results), I'm not sure it's possible to make sure the warning is not reported incorrectly.
This is also a very rare problem since most people use the cli to scaffold the project which already comes with an index.html file

**Comment by yyx990803** [comment]
This will only happen when you call `Vue.set` without explicitly importing it, and that should be a warning if you are using ESLint.
