### ISSUE TITLE
v-model <select> default/wrong option get selected on ajax/option render

### ISSUE THREAD

**Issue by ridaamirini** [vuejs/vue#8236]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/m5vxyl321j](https://codesandbox.io/s/m5vxyl321j)

### Steps to reproduce
See example. ( TestSelect.vue )

### What is expected?
The select should render, and the option with the same value as the v-model should be selected.

### What is actually happening?
The first option in the select is active.

---
My workaround:  https://codesandbox.io/s/ym9ro4qnw9

**Comment by posva** [comment]
There's no v-model in your codesanbox
Keep in mind select elements do not use `value`, they need the `selected` attribute in the option.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by ridaamirini** [comment]
Sorry for that :)
