### ISSUE TITLE
When using props as initial data, child data does not update when prop is modified by parent

### ISSUE THREAD

**Issue by DarylPinto** [vuejs/vue#8254]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/darylp/xcg9qvtr/](https://jsfiddle.net/darylp/xcg9qvtr/)

### Steps to reproduce
1. Open fiddle
2. Click "Update" button

### What is expected?
The child component should set it's `data.msg` to the value of the *prop* `defaultMsg` as documented here: https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow

The child component should render: "Message: Hello World"

### What is actually happening?
The `defaultMsg` prop is passed in to the child component correctly, but `data.msg` is not updated.

The child component renders: "Message: "

---
I ran into this issue while fetching data from an API to update the parent component's data. The parent's data is passed down to the child as a prop to be used as an initial value, which can then be changed within the child component.

Passing in data right away (e.g. Not using an API) works properly, as does displaying the prop in the child directly (not using the child components `data`)

This issue only occurs when using a prop as an initial value for the child's data, and updating the prop from the parent after the child has mounted.

**Comment by posva** [comment]
This is working as expected. `data` is invoked once. Use a computed property instead.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But come back and open an issue if it turns out to be a bug 🙂
