### ISSUE TITLE
errorCaptured hook

### ISSUE THREAD

**Issue by zhaosaisai** [vuejs/vue#8258]
### What problem does this feature solve?
Why this hook function is used to catch subcomponent errors instead of catching their own errors?
The source code is as follows:

```js
function handleError (err: Error, vm: any, info: string) {
  if (vm) {
    let cur = vm
    while ((cur = cur.$parent)) {
      const hooks = cur.$options.errorCaptured
      if (hooks) {
        for (let i = 0; i < hooks.length; i  ) {
          try {
            const capture = hooks[i].call(cur, err, vm, info) === false
            if (capture) return
          } catch (e) {
            globalHandleError(e, cur, 'errorCaptured hook')
          }
        }
      }
    }
  }
  globalHandleError(err, vm, info)
}
```

### What does the proposed API look like?
Why not design this way?
```js
function handleError (err: Error, vm: any, info: string) {
  if (vm) {
    let cur = vm
    while (cur) {
      const hooks = cur.$options.errorCaptured
      if (hooks) {
        for (let i = 0; i < hooks.length; i  ) {
          try {
            const capture = hooks[i].call(cur, err, vm, info) === false
            if (capture) return
          } catch (e) {
            globalHandleError(e, cur, 'errorCaptured hook')
          }
        }
      }
      cur = cur.$parent
    }
  }
  globalHandleError(err, vm, info)
}
```

**Comment by LinusBorg** [comment]
This is just a sylistic difference.

**Comment by yGuy** [comment]
@LinusBorg - sorry, but I disagree here. I just ran into the same issue. This is *not* just a stylistic difference, but a *behavioral difference* and one that at first sight does seem reasonable: 

The current implementation does *not* capture errors that happen in the same component, but only errors that happen in child and descendant components because the first hook that is checked is the hook of the `$parent` component (the cursor variable `cur` is set to the parent *before* the handler is checked and thus the own option is ignored). The proposed change however first checks the `vm` and then all their parents, which seems more appropriate to me, too. 

In my use-case the error happens when I mount a component and even though the component that I am trying to mount has the `errorCapture` declared, it is not being invoked because `$parent` is not yet set and thus the error goes straight to the global error handler. I can work around this by adding my code to the global error handler, but one can argue that this might not have been the intended behavior: The documentation is not perfectly clear on this. It does say:

> Called when an error from any descendent component is captured

So it could have been intentional that errors originating from the component itself will not be captured, but if that is the case, I would like to see this stated explicitly in the documentation and I would also like to know if there is a way to capture an error in the component itself without hooking into the global error handler.
