### ISSUE TITLE
render issue when transition-group child is a component that loads asynchronously

### ISSUE THREAD

**Issue by hmexx** [vuejs/vue#8284]
### Version
2.5.16

### Reproduction link
[http://www.google.com](http://www.google.com)

### Steps to reproduce
I don't have time to create a minim repro at the moment so feel free to close this report if you feel it's user error, or a known issue, but here is some pseudo-code:

--- in the parent
```
<transition-group>
<custom-component v-for="a in array"/>
</transition-group>
```
--- in the custom component 

```
<template>
<subsubcomponent/>
</template>

components: {
    subsubcomponent: () =>
    new Promise((resolve) => setTimeout(() => resolve(import("subsubcomponent.vue")),5000))
}
```
--- 

I'm adding the artificial loading delay to make the issue reproducible. With no setTimeout() it happens sporadically depending on load times. If I remove the `<transition-group>` then the rendering never fails.

The error message is:
```
[Vue warn]: Error in updated hook: "TypeError: Cannot read property 'cloneNode' of undefined"

found in

---> <TransitionGroup>
       <CCoachList> at src\components\cCoachList.vue
         <CCoachDirectory> at src\components\pages\cCoachDirectory.vue
```

### What is expected?
transition-group loads components as they become available

### What is actually happening?
if components take too long to load, the first item in the in the group displays correctly, the others fail

**Comment by posva** [comment]
the repro is mandatory...

**Comment by azurons** [comment]
Got the same error with transition-group and custom-component,
i can't reproduce it because it's quite random because my transition group are triggered by socket.io and sometimes when the call is "too fast" it crash with the same error.

Basically my client wait a request and the custom-component take the name of a parameter in the request, and sometimes when request are sent too fast the custom-component crash and refuse to change.

Will investigate
