### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by mbkupfer** [vuejs/vue#8285]
### What problem does this feature solve?
String interpolation

Was going through the example in the link below, and noticed that it wouldn't work when trying to use string interpolation. Could this be made possible?
  
https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks

### What does the proposed API look like?
```
new Vue({
  data: {
    a: 1
  },
  created: function () {
    // `this` points to the vm instance
    console.log('a is: ${this.a}' )
  }
})
```

**Comment by posva** [comment]
What you wrote works if you use backticks: 🙂 

```js
`a is: ${this.a}`
```

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
