### ISSUE TITLE
babel, promise, chrome 66

### ISSUE THREAD

**Issue by ariran5** [vuejs/vue#8318]
### Version
2.5.16

### Reproduction link
[https://yadi.sk/i/kEgLN0O-3XFsi6](https://yadi.sk/i/kEgLN0O-3XFsi6)

### Steps to reproduce
npm i -g vue-cli

vue create testPromise
cd testPromise
npm run serve

open helloWorld file and use promise in js
after
let a = async () => {};
console.log(a() instanceof Promise) // false

open project in chrome 66

https://yadi.sk/i/QsTMDQhT3XGvD7

chrome 66 fixed bug and this check is very bad

### What is expected?
console.log(a() instanceof Promise) // true

### What is actually happening?
console.log(a() instanceof Promise) // false

**Comment by Justineo** [comment]
Hi, but why does this have anything to do with Vue.js? It seems that the code you posted is not from Vue.js.

**Comment by ariran5** [comment]
this code probably adds babel, but it applies to everyone who writes on vue

**Comment by ariran5** [comment]
I did not put additional packages, just started the project thanks to vue-cli

**Comment by posva** [comment]
That is not a valid repro. You can use the forum or discord server to ask questions 🙂

**Comment by sodatea** [comment]
That's the exactly expected behavior for babel / core-js. When the native Promise implementation is absent or buggy, they polyfill it.

In most projects utilizing babel to transpile ES6+ code, async functions will be transpiled with regenerator-runtime and the abovementioned Promise polyfill from core-js. In that case, the `instanceof` check will pass.

The only bad case is that when you import babel-polyfill in your project but choose not to transpile async functions, or imported a third-party untranspiled codebase (or execute untranspiled code in devtools). But why would you do that? I don't think it's an issue that worth fixing.

**Comment by ariran5** [comment]
I use SSR bundle in nodejs, and I use async syntax.
I will not use babel for node js to run vue ssr

**Comment by ariran5** [comment]
it's time to move on react

**Comment by yyx990803** [comment]
@ariran5 moving to React doesn't solve your problem. But feel free to.
