### ISSUE TITLE
Inputs (checkbox radio) does not toggle when using :checked with @input or @click together

### ISSUE THREAD

**Issue by chriszhxi** [vuejs/vue#8340]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/50wL7mdz/359929/](https://jsfiddle.net/50wL7mdz/359929/)

### Steps to reproduce
Clicking on input(checkbox or radio) does not toggle its status. 

Remove either :checked or @input would solved the problem.

but I need them both.

@click  does  the same thing.

### What is expected?
Checkbox or radio should be toggled if I clicked it.

### What is actually happening?
Checkbox or raido does not toggle when I clicking it.

**Comment by sodatea** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

------

You can toggle `isChecked` in the click handler (or use `v-model` instead of `v-bind`).
Or add `v-once` directive to the markup to create a one-time binding.
