### ISSUE TITLE
Is Vue.js going to be abandoned?

### ISSUE THREAD

**Issue by rattrap19** [vuejs/vue#8360]
### Version
2.5.16

### Reproduction link
[https://vuejs.org](https://vuejs.org)

### Steps to reproduce
The github profile of Vue.js is getting less and less activity.

### What is expected?
 If to look at the 'contributors' section we can see that commits chart is very poor lately.

### What is actually happening?
Should I use it for my projects?

**Comment by sodatea** [comment]
Hi, thanks for your interest.

We are definitely not going to abandon Vue.js. Feel free to use it for your projects.

1. Vue.js has been working quite stable. There's a healthy ecosystem and no critical bug in core, you can pick it up at any time without worrying about its maintenance.
2. **It is under active development**, actually. The commits chart doesn't reflect this because those developments are done in open pull requests which hasn't been merged into the base branch yet.

Vue.js has a large ecosystem of companion libraries including vue-cli, vue-loader, etc.
For now the core team's major focus is Vue CLI 3, which aims to be the standard tooling baseline for the Vue ecosystem and brings a whole new developer experience. We have just reached Release Candidate phase for it. You can check it out at <https://cli.vuejs.org/>.

Once we released the stable version of Vue CLI, which is expected to be done in the coming weeks, we'll come back to core and start merging pull requests.
Actually we have already reviewed and approved a lot PRs (https://github.com/vuejs/vue/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved). So if you are expecting a new version just stay tuned. But for production usage, you don't have to wait for that.
