### ISSUE TITLE
v-for documentation conflicts with warnings

### ISSUE THREAD

**Issue by micahhainline** [vuejs/vue#8372]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/1dncegky/](https://jsfiddle.net/1dncegky/)

### Steps to reproduce
Intentionally include a v-for with no key per documentation

### What is expected?
No warning is shown

### What is actually happening?
A warning is shown indicating that it was a mistake to not include a key

---
The problem is actually in the documentation. In https://vuejs.org/v2/guide/list.html#key the documentation indicates that sometimes not including a key is fine, but there will be a build warning if you don't include the key at all. It appears that the system will be fine with a key of "undefined". It clarifies that it was considered that we would include a key and intentional that it was not included. The code seems to work as expected, the warning is suppressed, everyone's happy.

My request is that the docs get updated and the warning gets updated to clue people in to that as a solution to the warning when you really don't want to include a separate key.

**Comment by sodatea** [comment]
As the documentation says, not including a key is only fine **when your list render output does not rely on child component state or temporary DOM state (e.g. form input values)**.

It is a warning rather than an error because our vdom algorithm could deal with it at the expense of considerable performance deterioration. But using `v-for` without `key` is still considered as an anti-pattern and we chose to keep the warning.

The `v-bind:key="undefined"` escape hatch is not intentional. And the [require-v-for-key rule of eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/require-v-for-key.md) is available to detect this use case. We might consider adding this check in core, too.
