### ISSUE TITLE
v-model.trim on custom components removes whitespaces while text is edited

### ISSUE THREAD

**Issue by tonila** [vuejs/vue#8431]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/6fj0avLy/](https://jsfiddle.net/6fj0avLy/)

### Steps to reproduce
1. Write text "aa b" to Custom input component
2. Delete "b"

### What is expected?
Whitespace after "aa" remains intact

### What is actually happening?
Whitespace is removed

---
When similar test is done to regular input, it is working as expected. 
Custom inputs are not usable, because they remove whitespaces, while text is being edited.

**Comment by jacekkarczmarczyk** [comment]
Similar issue with `.number` (type "1.1")
https://codepen.io/anon/pen/RJEpoW?editors=1010

**Comment by posva** [comment]
v-model on components do not know if the value is bound to an input (text type or not), so it cannot apply the same behaviour as for an input. This would have to implemented in userland.
Ideally, I think it could be solved with custom modifiers #3666 (which is closed at the moment but may be re-discussed)

For the moment, the best approach is to have a prop instead of a modifier (since right now they are not accessible from the component) and handle the logic in the component

**Comment by Andre741** [comment]
Hi, might it be possible to highlight this in the documentation?
