### ISSUE TITLE
vue $set do not work

### ISSUE THREAD

**Issue by vvpvvp** [vuejs/vue#8472]
Version
2.5.16

Reproduction link
https://codepen.io/vvpvvp/pen/XYvxMg

Steps to reproduce
1、click 'change a value' button
2、click 'change a value use $set' button

What is expected?
value a changed

What is actually happening?
value a not changed

**Comment by JounQin** [comment]
That's because if you add a property `a` onto `value` first, then `value` will has its own property named `a`, then you `$set` it, it will not be reactive because it should not be proxy.

See source code: https://github.com/vuejs/vue/blob/master/src/core/observer/index.js#L199-L202

So you should always use `$set` instead of manually adding property.
