### ISSUE TITLE
Scoped style inheritance inconvenient

### ISSUE THREAD

**Issue by kidwon24** [vuejs/vue#8500]
### What problem does this feature solve?
To reproduce the issue which let to my suggestion please follow [the example](https://codesandbox.io/s/jjl952o545).

A particular inherited style in the example is founded to not work: 
```css
.master header nav .btn svg {
  fill: #7f7f7f;
}
```
which is the color fill of the vector.

So in order to solve the issue I had to use what you suggest as deep selector 
`.btn >>> svg` 

However  that creates great inconvenience for example in my project the master element has a lot of children so I have to go through hundred of style lines to ensure if every selector is applied and doesn't need deep selecting.
Indeed the issue has workarounds  and it's debatable of is it a matter of scoped styling but I believe it is the case scoped through inheritance much like the `props` attribute works for the js API. Sometimes how an element looks and is styled really depends to the component it belongs to.
Pardon me if there's something I overlooked and that isn't an actual issue. 

### What does the proposed API look like?
What catches my attention about scoped styling is it goes down to the following structure:
`<div data-v-783f90ce=""><header data-v-783f90ce="">` so the styling goes like:
```css
div header[data-v-783f90ce] {

}
```
When I believe in regular css is perfectly fine to use inheritance like:
```css
div[data-v-783f90ce] header {

}
```
Although I believe that the problem I witnessed has somewhat in common with the `data-v-` attribute but not quite sure is it the real reason for the current implementation behavior.
Nevertheless I think **vuejs** is great framework  and I just love it and especially the ease and convenience it creates and how good and logical it structured and interacts naturally. So I believe that the following precedent creates inconvenience and is in conflict with framework great nature.
I sure believe that what occurs isn't accidental so there's a particular reason for current implementation perhaps this is how upcoming native css specification looks like so you have to follow it or some other particular reason but still there might be a solution.

Probably `scoped="deep"`  where deep selecting works as default  or `scoped="inherit"` where `data-v` inheritance concerns parent and it takes care for its children styling might be a good tip so please consider it.

Thank you for your time keep up the good work. Appreciate it, great framework.

**Comment by posva** [comment]
I'm not sure to get your problem...
Having to use the deep selector makes it possible to keeps styles scoped, you are trading verbosity for convenience/scoping.

What I see is that you may want to pass a prop to change some attributes of a button instead of having everything in css. You can also have multiple `style` blocks in your vue file, making some of them global, which would apply without anything extra, as that's the nature of CSS.

```css
div[data-v-783f90ce] header {

}
```

would actually not work for scoped styles as it would apply to any `header`, in any component used inside of the one containing this style

I believe this is more of a discussion about how to handle it, so I would recommend you to head over the forum or discord chat to share and discuss your thoughts on this topic 🙂

**Comment by kidwon24** [comment]
Indeed @posva  good point what you say makes perfect sense. Thank you for your swift reply.
Still it's a serious issue I have to go trough 100 of lines styles to ensure each one is applied in browser tools and doesn't need deep selecting  which might take hours. 
I use vuejs for convenience and time saving when in this case it's quite the opposite please consider it and don't rush to closing the issue.

**Comment by posva** [comment]
This has actually nothing to deal with Vue but rather about your CSS strategy, which is partly using vue-loader scoped styles. In any case, I told you that way isn't possible and gave you, what looks to me, like a solution but because of the first point, this should be discussed in another channel first. I definitely didn't _"rush close"_ this issue as I gave you reasons 😄

**Comment by Justineo** [comment]
IMO there is no “absolute convenience”, it's all about trade-offs. Scoped styles are designed to isolate component styles from each other thus we gain better encapsulation so that changing parent styles won't (in most cases) introduce style regression for its children. It's just another kind of “convenience” regarding to maintainability.

And BTW if you can use CSS custom properties in your product, whey will provide another mechanism for style inheritance and it goes down to the children according to DOM structures. Defining child style using a custom property means you would be explicitly expecting styles from parents, which may be a better balance point for such parent-child situation.
