### ISSUE TITLE
Why textarea with a fixed value still change

### ISSUE THREAD

**Issue by jasonxia23** [vuejs/vue#8510]
### What problem does this feature solve?
Maybe a stupid question.
But textarea with value props will change even if it is set to be a fixed value.
See examples [here](https://jsfiddle.net/0dzvcf4d/18698/)

### What does the proposed API look like?
`value` props of textarea should not change after it is set to be a fixed value.

**Comment by Justineo** [comment]
Without `v-model`, changes to the value of the input will not update `input` value so it has been `a` all the time. Since the prop is not changed, Vue won't update `<input>`'s internal state `value` so the `value` is set to `a` only the first time `input` event is triggered.

**Comment by sodatea** [comment]
https://vuejs.org/v2/guide/forms

> Although a bit magical, `v-model` is essentially syntax sugar for updating data on user input events, plus special care for some edge cases.

------

Next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by jasonxia23** [comment]
@Justineo Actually I think it is a strange behavior after using React. If Vue don't update `<input>`'s internal state, how to make sure what the output equal to the state.
@sodatea Thanks for your suggestion🙂
