### ISSUE TITLE
[Suggestion] Regarding issues in Chinese 

### ISSUE THREAD

**Issue by exotype** [vuejs/vue#8525]
I know this is probably not the place for this but i don't know where else to reach you, 
i'd like to suggest that you try to tell Chinese users to speak to report issues in English if and whenever they can, because a lot of people in my current company and others i know of are shutting down Vue proposals on account of not being able to understand bug tickets made for VueJS and the fact many popular libraries are primarily and/or exclusively in Chinese.

It's important for VueJS to have a healthy Chinese community but i feel that the community's disregard for non-Chinese users is ultimately damaging VueJS and frustrating the efforts of Vue evangelists in the west. Couple the non-english documentation and issues with React's facebook backing and it's very hard to convince anyone in management that Vue is the way to go, i feel that i'm not alone and would also like to hear what others have to say about it.

**Comment by LinusBorg** [comment]
> It's important for VueJS to have a healthy Chinese community but i feel that the community's disregard for non-Chinese users is ultimately damaging VueJS and frustrating the efforts of Vue evangelists in the west.

*It's important for VueJS to have a healthy **English**-speaking community but i feel that the community's disregard for non-**english** users is ultimately damaging VueJS and frustrating the efforts of Vue evangelists in **China**.*

Wouldn't that sound a bit condescending towards your part 

On a more serious note, the success of Vue is to no small part due to the Adoption in the chinese market - and that happened because Vue's creatr is chinese and provided great documentation and support in chinese.

While I can empathise with your request it sound a bit like the western market is somehow superior or more important, which we won't side with.

If your company sees it as a problem that a big part of the community is chinese instead of seeing the value in the global adoption, that's their problem. Yes, some of the biggest libs are from china, yet have good english docs. Others of the greatest libs (like Vuetify) are from the west.

Why someone would see that as a negative is beyond me.

**Comment by exotype** [comment]
@yyx990803 and @LinusBorg I think you guys got it the wrong way, i'm not saying tell the Chinese devs they can't speak Chinese, but rather try to ask them to use English if and when they can as that makes the issues understandable for everyone and invites collaboration from everyone, not just Chinese speakers.

Ultimately i'd like to bring the communities closer together and possibly even have both communities collaborate on stuff, so i'm in no way saying the west is better, i have great respect for Chinese tech and the amazing stuff they manage to do with apps like Wechat.
But fact of the matter is it's more likely for a Chinese web developer to be able to understand english than it is for any western developer to understand Chinese, that's not saying the west is better, just that English is more inclusive amongst developers and should be used whenever possible so that communities don't splinter into different groups based on their first languages, you know?

Maybe there's just one issue currently but there's usually more than one, but all in all, i just wanted to voice a potential issue in trying to promote Vue adoption in companies and start a discussion, if no other people have such problems then it's disregardable and i'll try to bring up the issue to my colleagues again.
Thanks for your attention and sorry to have bothered you guys with a non-issue discussion.

**Comment by Justineo** [comment]
> but rather try to ask them to use English if and when they can as that makes the issues understandable for everyone and invites collaboration from everyone, not just Chinese speakers.

What if there are more Chinese speakers in the community? Would you convince us to encourage everyone to file issues in Chinese so “that makes the issues understandable for everyone and invites collaboration from everyone, not just English speakers”?

Ironically we Chinese developers are actually doing a lot in Chinese community to encourage people to use English on GitHub and provide English documentation for their OSS. But unfortunately not everyone can fully express themselves in English while some issue need very detailed elaboration. If they use Chinese instead at least Chinese speakers can understand better and provide some help. The only issue with Chinese content under discussion right now is a good example of this (I suppose it’s the same one Evan mentioned earlier). Given that 95%+ of the discussions are already in English (many of them are provided by Chinese speakers), I just want to ask those who are still trying to eliminate all Chinese usage in the community, to show a little empathy. Maybe it’s not you, but I think you should try to explain this to those who cannot bear to see any Chinese character on the screen instead.

**Comment by LinusBorg** [comment]
> but rather try to ask them to use English if and when they can as that makes the issues understandable for everyone and invites collaboration from everyone, not just Chinese speakers.

Again: not everyone speaks english, so English issues are *not* "understandable for everyone" - they are understandable for most people from *your hemisphere*

**Comment by exotype** [comment]
@Justineo Will do, and thanks for the efforts in trying to encourage it which i'm also sure to mention.

@LinusBorg I feel that one of the good things about development and the web in particular is that first languages are not as much of a barrier as they are in real life, the web is very international and a big part of it is the fact that english is a common language.

I understand that not all of them speak English but especially for new Chinese developers starting out i feel it's important for them to be encouraged to learn it and use it when they can, it brings them into the larger community and tears down walls built around first languages, as well as it opens new doors for them to work outside China, give conferences and learn from non-chinese tutorials.

My first language is not english either, but i don't feel offended in any way by speaking it online and/or being expected to, instead i feel like it's a great thing to bring us all together and break down silly language boundaries that would've splintered us otherwise. All in all what i'd suggest is as @Justineo said simply encouraging them, especially the new devs to use English if they're bilingual.

But at the same time i understand China is different from Russia, India, Romania, etc... especially when it comes to the internet and so Chinese users are more used to having their own internal communities rather than being part of a global internet experience, but that's another issue altogether unfortunately out of our hands.

All in all i feel confident enough that this is a non-issue and that the Chinese community is already working hard to mitigate it.

**Comment by yyx990803** [comment]
Also FYI - in the new issue creator [we already explicitly encourage Chinese users to use English](http://new-issue.vuejs.org/?repo=vuejs/vue&lang=zh-cn). This is literally the first thing they see. If they still opt to use Chinese, it's most likely because their English skills doesn't allow them to clearly explain the problem they are trying to describe, and in those cases forcing them to use English just makes the problem harder to understand for everyone involved.

Final comments before I unsubscribe:

- There is absolutely no "disregard for non-Chinese users" given the actual percentage of Chinese issues is quite low. I'm not sure where you get that impression from, but that impression is simply wrong. All our communication channels (release notes, Twitter, blog posts, documentation, issues, conferences) are using English as the first (and in most cases the only) language.

- If your colleagues or manager cites the presence of Chinese issues as a reason for not adopting Vue, they are probably pulling misleading arguments like "Vue is focused on China only and lacks a western community". Ask them to prove it. Ask them to check how many open issues are actually in Chinese. Ask them to search on Twitter, Medium and StackOverflow to see how many Vue articles and discussions in English are out there. Ask them to search about Vue conferences and meetups going on around the globe. Ask them to read our documentation. Then ask them again do they really think this is going to be a problem.
