### ISSUE TITLE
Hook event won't emit if v-if is change

### ISSUE THREAD

**Issue by mehwww** [vuejs/vue#8530]
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/2xp6xn653n](https://codesandbox.io/s/2xp6xn653n)

### Steps to reproduce
1. run program, custom directive hook function has been called correctly
2. change `isMounted` to `false`, hook function will never called no matter how `isMounted` is change

### What is expected?
Mounted hook function called every time it's vnode mounted.

### What is actually happening?
Mounted hook won't call anyway if v-if is falsy

**Comment by LinusBorg** [comment]
this is expected behaviour. `mounted` is run only once at the beginning.

1. if you start with `isMounted: false`, the custom directive won't be applied on the initial render
2. then, `mounted` is run and the `hook:mounted` event is dispatched
3. since the custom directive wasn't applied, it doesn't react to the event
4. then `isMounted` becomes `true`, so the component re-renders and applies the custom directive
5. but now `mounted` isn't called because the component has already been mounted before - instead, `updated` is called.
