### ISSUE TITLE
Remove a component element in a list

### ISSUE THREAD

**Issue by bigradish** [vuejs/vue#8590]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/bigradish/eywraw8t/229044/](https://jsfiddle.net/bigradish/eywraw8t/229044/)

### Steps to reproduce
1. Click on the second item once;
2. Click on the button.

### What is expected?
The second item is removed.

### What is actually happening?
The last item is removed

**Comment by yyx990803** [comment]
You are using index as the key, that's the expected behavior.

**Comment by bigradish** [comment]
@yyx990803 Could you tell me the best practice for picking a key for a compoent?
And it will be better that you can make the code on the jsfiddle work.
Thanks.

**Comment by Justineo** [comment]
It's working as I expected. You need to describe your expected behavior more clearly because the items in your list are identical.

**Comment by bigradish** [comment]
@Justineo As I said in the "Steps to reproduce" section, follow these steps:
1. Click on the second item once;
2. Click on the button.

Thank you.

**Comment by leopiccionia** [comment]
@bigradish Here's a working example: https://jsfiddle.net/leopiccionia/mLhe325u/

The difference between provided reproduction and working example:
* In provided reproduction, we had `key` set {1, 2, 3, 4, 5} before, and {1, 2, 3, 4} after the splice, so Vue removed the item whose index was 5.
* In my working example, we had `key` set {1, 2, 3, 4, 5} before, and {1, 3, 4, 5} after the splice, so Vue removed the item whose `id` was 2. It's essential to always provided an unique `key`, that always represent exactly the same element.

**Comment by bigradish** [comment]
@leopiccionia Thank you so much. :)

**Comment by Justineo** [comment]
@bigradish

As described in [docs](https://vuejs.org/v2/guide/list.html#key):

> This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).

Binding `key`s to loop indexes is equal to this default mode. You are identifying unique item according to their place in the list. As @leopiccionia said, your items actually changed from { 1, 2, 3, 4, 5 } to { 1, 2, 3, 4 } because after removing the 2nd item, the `key`s are recalculated so that you are identifying item#3 as the new item#2, item#4 as the new item#3, and so on. To Vue's perspective, it only knows that item#2's data is changed and the item#5 is removed.

To get your expected result, you need to specify `key`s that truly stand for uniqueness of the item data, instead of the index.

**Comment by bigradish** [comment]
@Justineo Thank you for your information.

**Comment by ranransun** [comment]
how to deal with it?
