### ISSUE TITLE
是不是优化的问题，导致样式丢失

### ISSUE THREAD

**Issue by newpost** [vuejs/vue#8629]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/niceguy01/db9pfgxy/](https://jsfiddle.net/niceguy01/db9pfgxy/)

### Steps to reproduce
直接run

### What is expected?
有样式background-position: center;

### What is actually happening?
没有background-position: center;

**Comment by posva** [comment]
This has nothing to deal with Vue.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by newpost** [comment]
why to closed this

**Comment by Justineo** [comment]
请查一下 `background` 属性的含义。
