### ISSUE TITLE
fix svg example

### ISSUE THREAD

**Issue by munepom** [vuejs/vue#8650]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/munepom/sgjtL47o/](https://jsfiddle.net/munepom/sgjtL47o/)

### Steps to reproduce
please open the jsfiddle link, and use devtool to show console

### What is expected?
no warning

### What is actually happening?
the following warning is displayed on the console

```
vue.js:603 [Vue tip]: <axis-label v-for="stat in stats">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
```

if beginners see this, they will get confused...

---
to fix: set stat.id (uuid?) and use it for key?

**Comment by posva** [comment]
Sometimes not using a key is intentional, as said in the docs. Thanks for your interest but I think the example is fine like that. The warning includes a link to the docs and it's quite the opposite of confusing 😄 (confusing would be a _cannot read x from undefined_ or _undefined is not a function_)

**Comment by munepom** [comment]
> Sometimes not using a key is intentional, as said in the docs.

Yeah! That's right 👍 
Thanks for fast checking 😄
