### ISSUE TITLE
Error render website created by vue in facebook app browser

### ISSUE THREAD

**Issue by thongtd** [vuejs/vue#8687]
### Version
2.5.13

### Reproduction link
[https://vue.pizza/app/#/login?redirect=%2F](https://vue.pizza/app/#/login?redirect=%2F)

### Steps to reproduce
1. Share the link https://vue.pizza/app/#/login?redirect=%2F to facebook
2. Use facebook app -> click to this link has shared. Please make sure you are use facebook app browser.

### What is expected?
Page display

### What is actually happening?
Page blank. Can not display correctly

Image: https://ibb.co/dSkCyK

---
I guess facebook browser can not render vuejs code.

**Comment by fnlctrl** [comment]
Please provide a reproduction link with source code.

----------------------------------------

This is probably caused by facebook app browser's WebView not supporting some JavaScript features you're using. Make sure you have correctly set up [babel](https://babeljs.io/) to transpile JavaScript to support older browser/webviews

**Comment by Namish-TNG** [comment]
The issue is still not fixed. I am not able to view my Vue app on the Facebook in-app browser. It works flawlessly on Safari, Chrome,
