### ISSUE TITLE
[KeepAlive]  The cache is removed, but the componentInstance hasn't destroy?

### ISSUE THREAD

**Issue by Devince** [vuejs/vue#8708]
### Version
2.5.10

### Reproduction link
[https://github.com/Devince/testKeepAlive](https://github.com/Devince/testKeepAlive)

### Steps to reproduce
keepalive的问题，主要是这个：
 if (cached$$1 && (!current || cached$$1.tag !== current.tag)) {
    cached$$1.componentInstance.$destroy();
  }

function pruneCacheEntry (
  cache,
  key,
  keys,
  current
) {
  var cached$$1 = cache[key];
  if (cached$$1 && (!current || cached$$1.tag !== current.tag)) {
    cached$$1.componentInstance.$destroy();
  }
  cache[key] = null;
  remove(keys, key);
}

### What is expected?
缓存都清了，组件应该同时销毁吧

### What is actually happening?
缓存都清了，组件没有销毁，导致实例多个相同组件

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue. The list of steps to reproduce is important. Make sure to clean unecessary dependencies like Vuex.
Also, you can provide a simple [jsfiddle](http://jsfiddle.net/posva/wsr78d2w/) or a [codesandbox](https://codesandbox.io/) instead of a github repo (which is using the old version of the cli). This would make things much easier for us to test 😉 
Thanks!

**Comment by Devince** [comment]
Thanks! I just do that the version of vue was upgraded to v2.5.17 and this works well !
