### ISSUE TITLE
Accessing data through functions passed from parent causes list siblings to re-compute

### ISSUE THREAD

**Issue by anderspitman** [vuejs/vue#8811]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/t0h73urf/](https://jsfiddle.net/t0h73urf/)

### Steps to reproduce
Click the button.

### What is expected?
computed.value is only recalculated for the changed list element (look at the console logs). See this slightly modified fiddle for expected behavior (not using the accessor): https://jsfiddle.net/twnmoLsh/2/

### What is actually happening?
All 3 computed.value elements are recalculated.

**Comment by HcySunYang** [comment]
In your reproduction link(https://jsfiddle.net/t0h73urf/), the computed property `value` has two dependencies: `this.accessorFunc` and `this.item`.
In your modified link(https://jsfiddle.net/twnmoLsh/2/), the computed property `value` has only one dependency: `this.item`.
`this.accessorFunc` is always changed when the component is updated. As a workaround, you can use `methods` instead of function expressions:
```html
    <list-item
      :accessor-func='fn'>
    </list-item>
```
```js
methods: {
  fn (item) { return item.value }
}
```

**Comment by posva** [comment]
As you have an inline function, this one is being recreated every time the template renders, therefore, the prop changes and the computed property needs to be re evaluated (and this for every component). As @HcySunYang suggested, a method would make it work. A similar thing happens with plain objects.

Since the function is created inside of the `render` function (when the template is compiled), we cannot hoist it to prevent this

**Comment by anderspitman** [comment]
That makes sense and your solution works. Thanks!
