### ISSUE TITLE
Vue.directive-The element of the instruction binding does not have data update. Upload also triggers.

### ISSUE THREAD

**Issue by chenrenxing** [vuejs/vue#8816]
When I bind two different elements to different instructions v-hello and v-world, I find that both v-hello and v-world hook functions upload are triggered when the template is updated, and I think the binding element upload should trigger only the elements bound by the instruction.

**Comment by sqal** [comment]
> v-world hook functions

Are you using function syntax or an object with `bind` function? because if the first one then this behavior is correct. it will be called when the directive is bound to the element and also every time component is updated. Is explained in the docs https://vuejs.org/v2/guide/custom-directive.html#Function-Shorthand

**Comment by chenrenxing** [comment]
Thank you for your answer.
The problem I have here is that the v-hello and v-word instructions update the data of other elements after they are bound to their respective elements, triggering the update hook function of the v-hello and v-word instructions, which I think is called when the template where the bound element is updated.

**Comment by sqal** [comment]
@chenrenxing can you provide some reproduction of this issue? i am afraid i don't quite understand your problem

**Comment by chenrenxing** [comment]
@sqal 
First of all, thank you
    <button @click="change">{{msg}}</button>
    <p v-world></p>
    <p v-hello></p>
<script>
    var vm = new Vue({
        el: '#itany',
        data: {
            msg: 'welcome'
        },
        methods: {
            change(){
                this.msg = 'thank'
            }
        },
        directives: {
            world: {
                update(){
                    alert('update');
                },
            },
            hello: {
                update(){
                    alert('update');
                },
            }
        }
    });
</script>
If you click the change event to trigger, I don't think the hook function alert ('update') of the v-world and v-hello instructions should be triggered.

**Comment by chenrenxing** [comment]
@sqal 
First of all, thank you

-  `<button @click="change"> {{msg}} </button> <p v-world></p> <p v-hello></p>`
- `<script>
    var vm = new Vue({
        el: '#itany',
        data: {
            msg: 'welcome'
        },
        methods: {
            change(){
                this.msg = 'thank'
            }
        },
        directives: {
            world: {
                update(){
                    alert('update');
                },
            },
            hello: {
                update(){
                    alert('update');
                },
            }
        }
    });</script>`
If you click the change event to trigger, I don't think the hook function alert ('update') of the v-world and v-hello instructions should be triggered.

**Comment by sqal** [comment]
@chenrenxing They should be triggered and here's why. When you click on the button you change `this.msg` property and because its value changed, it will trigger the update of the component (template). Now let's see what [documenttion](https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions) says about directive's update hook: 

> update: called after the containing component’s VNode has updated, but possibly before its children have updated. 

So as you see your code works as expected. Notice that when you click on the button for the second time, `update` hooks are not called, because `this.msg` hasn't changed therefore Vue doesn't need to re-render your component.
