### ISSUE TITLE
setInterval interferes with selecting an option

### ISSUE THREAD

**Issue by opowell** [vuejs/vue#8835]
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/1bv7se9h/43/](http://jsfiddle.net/1bv7se9h/43/)

### Steps to reproduce
Load the page. Select an option from the list. Most of the time selection will fail (due to timer interference).

### What is expected?
Selection should work as normal.

### What is actually happening?
Selection does not work if it fires around the same time as the setInterval timer fires.

**Comment by posva** [comment]
mmh, this is due to how rendering works. If you want to prevent the select from being rendered again and therefore get the not updated value selected again, you will have to put it in a component.

The problem is that the select element won't fire the `change` event until the mouse button is released but if the element is replaced while the mouse is pressed it won't work.

To fix it we would have to prevent replacing the select element in the middle of the template, which is not possible

**Comment by ElMatella** [comment]
I understand your point here, but why replacing `v-model` by `@input="choice = $event.target.value"` is solving the problem? Isn't v-model supposed to be just a "sugar  syntax" for this?

http://jsfiddle.net/1bv7se9h/46/

**Comment by posva** [comment]
That's in components but the reason it's working it's because you're not binding the selected value. You can do that with ` :value.prop="choice"` on the select and the issue will appear 😉

**Comment by opowell** [comment]
It seems odd to me that the whole template is redrawn (rather than just the affected parts). But presumably there is a good reason for this.
