### ISSUE TITLE
Cachable filters

### ISSUE THREAD

**Issue by Demivan** [vuejs/vue#8880]
### What problem does this feature solve?
There are a lot of issues created about filters: #8497, #7304, #5920, #5682, #5109 etc.  
Most of the issues are created because filters are executed multiple times.  
For all of these issues answer is the same: for vdom comparison vue needs to run filter and then compares resulting dom tree - use computed properties instead.

Because filters are not cached right now there is no reason to use filters in mustache interpolations - they are the same as methods.  
Angular filters for example are only evaluated when inputs change and this makes them much more usable.
Filters are supposed to be pure functions anyway and I see no reason to not cache them.

Making filters cachable (like computed properties) opens up possibilities for using them in mustache interpolations.
Examples where cachable filters will be beneficial:
* vue-i18n by @kazupon works around this issue by having `v-t` directive to cache result of the translation. 
https://kazupon.github.io/vue-i18n/guide/directive.html#t-vs-v-t But is less flexible then mustache interpolation:
It would be more readable and flexible instead of:
 ```js
<p v-t="'hello'"></p>
```
 to write
 ```js
<p>{{ "hello" | $t }}</p>
```
and it will be possible to do this:
```js
<p>{{ "hello" | $t }} {{ "world" | $t }}</p>
```
* Use Moment.js for date formatting. Moment.js is slow and because filters are not cached it is not really usable, especially when rendering lists.
* All other places for formatting text, dates etc. 
* Creating computed property for each formatted value (text, date etc) is just a lot of work and unnecessary code to write.

### What does the proposed API look like?
Make all filters work like computed properties instead of methods.  
Or add different symbol (instead of pipe) to denote filters that are cachable (pure).

**Comment by posva** [comment]
As you already saw this has been discussed many times and it's not going to happen. You can however achieve it in user and with a memoize helper (lodash has one)

**Comment by Demivan** [comment]
Memorize will work but it will use more memory.
At least, if it is not going to be changed, it would be nice to update docs to clarify that filters are executed on every re-render.

**Comment by adamvleggett** [comment]
@posva I know this has been discussed many times, but I think you should consider the number of times it has been discussed as a sign that it should be given further consideration. Many developers are under the impression that this is the behavior of Vue - why wouldn't it be, otherwise there's really no important reason to have filters. This is even implied in the accepted answer to https://stackoverflow.com/questions/47940007/what-is-the-difference-between-filters-and-methods-in-vue-js which is the first place people look when they want to understand filters. It's not made explicit in the docs at all, as the last comment mentions. This is all problematic, and it would make Vue a significantly better framework if this were made the behavior.
