### ISSUE TITLE
Element that removed with animation from 2d table moves to the top-left corner

### ISSUE THREAD

**Issue by xorik** [vuejs/vue#8908]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/60eqgkx3/](https://jsfiddle.net/60eqgkx3/)

### Steps to reproduce
Click on the test button

### What is expected?
Removed element should be faded when deleted without any movement

### What is actually happening?
Removed element starts to move to the top-left corner

---
I can remove the `position: absolute` css rule, but I need it for other cases (for example when new element should be immediately appear at the same time to fade with previous

**Comment by posva** [comment]
You will have to apply custom logic to remove the CSS attribute for your specific case as this is happening because of the CSS rules

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
