### ISSUE TITLE
Vue templates in runtime & compilerOptions

### ISSUE THREAD

**Issue by faiwer** [vuejs/vue#8921]
### What problem does this feature solve?
Hello. I don't use `.vue` files. Instead of it I use template-string-field in `.js` files. But I can't find any way to set `compilerOptions.preserveWhitespace = false`. I've delved into `vue-template-compiler` and `vue` packages and found out that compiler-function (`compileToFunctions`) is created immediately after importing Vue-package. After that Vue uses that `compileToFunctions` all the time. Is it a deadend? 

Also it's a bit strange that `compileToFunctions` is called again and again for each instance of one component (in `Vue.prototype.$mount`). When there is a static template string in a component definition I think the result can be cached for the class-component. 

### What does the proposed API look like?
Something like `vue-loader` for webpack
```
new Vue({ compilerOptions: {...} });
```

**Comment by posva** [comment]
Since this is a very specific use case that goes in a very different direction from what we recommend, you will have to find your way to have the same compiler from vue-loader in your front bundle
If you have improvements regarding caching compilation of templates, we could have a repro or a PR for that though 🙂 (make sure it doesn't impact the runtime version if you do though)
