### ISSUE TITLE
Scoped Slot delegate to child component. Slot is in child component always set, also if it not set

### ISSUE THREAD

**Issue by MaximilianFranke** [vuejs/vue#8936]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/j1451yzrm5](https://codesandbox.io/s/j1451yzrm5)

### Steps to reproduce
Open sample

### What is expected?
The output of the second sample should be:
....
Child component...has scopedslot: false
....

### What is actually happening?
The output of the second sample is:
....
Child component...has scopedslot: true 
....

**Comment by MaximilianFranke** [comment]
also interesting if you remove the v-if in Parent.vue the default of the basicslot is still rendered but the default of the scopedslot isn't anymore.

**Comment by posva** [comment]
It's because it's a function, so you have to call it to check if the result is undefined (or an empty array in the future https://github.com/vuejs/vue/issues/8056). In the Parent component there's always the scoped slot in the template but that's not the case in App.vue, so the function may also not exist
