### ISSUE TITLE
Let component.methods take a function not only an object

### ISSUE THREAD

**Issue by thomsa** [vuejs/vue#8972]
### What problem does this feature solve?
I've been trying to separate a component's filters, computed,methods, etc to separate files and then import the classes pass down 'this' as an argument, which works for created and data since they take a function. With this approach it would be possible to put all the component property declarations into another file, thus leading to cleaner code.

### What does the proposed API look like?
```
export class MyComponentMethods {
	constructor(myComponent) { 
               // wohoo I have a reference to the component itself!
        }
}

import MyComponentMethods from "./methods";

export default { 
name: ...
methods: () => MyComponentMethods(this),
}
```

**Comment by Justineo** [comment]
You can use mixins to organize reused methods. And I don't really understand how is separating a component and its methods making the code cleaner...

**Comment by thomsa** [comment]
Thanks for pointing mixins out!
I meant the cleanness by much less noise. In a larger component the code can be a lot. (Or I got into a project where they did all wrong, rather this is the case :) )

**Comment by thomsa** [comment]
Thanks for pointing mixins out!
I meant the cleanness by much less noise. In a larger component the code can be a lot. (Or I got into a project where they did all wrong, rather this is the case :) )

**Comment by Justineo** [comment]
You can always separate things into smaller modules, but I think solely separating methods doesn't sound like a good idea. Since mixins are totally capable of doing the separation, I think there's no need to provide such usage in Vue's core.

BTW. If you are just separating scripts out from a single file component, you can actually use `<script src="..."></script>` to include separate script files into single file components.
