### ISSUE TITLE
Fire of keyboard event with key modifier using IME had been changed in the version of 2.5.14

### ISSUE THREAD

**Issue by toBeTheLight** [vuejs/vue#9000]
### Version
2.5.14

### Reproduction link
[https://github.com/toBeTheLight/issue-20181029](https://github.com/toBeTheLight/issue-20181029)

### Steps to reproduce
1. Use IME
2. Type some letters in the input with @keydown.down
3. Press the down arrow of the keyboard

### What is expected?
The event is not fired as same as version before 2.5.14

### What is actually happening?
The event is fired in version  2.5.14. 
But it is not fired in version before 2.5.14.

---
When user has not ended composition (compositionend event) with IME, before version of 2.5.14, keyboard events with modifiers (e.g, keydown@enter, keydown@up) will not be fired. 
After version of 2.5.14 it will. 
And the keyboard arrow keys are usually be used to choose the right word, so this change will result in a lot of extra events.

![qq20181029-145852](https://user-images.githubusercontent.com/23555178/47634132-4b982780-db8b-11e8-9262-b0bc1be73158.gif)

**Comment by Justineo** [comment]
After some investigation, I think it might be caused by [f7311c9](https://github.com/vuejs/vue/commit/f7311c90b35da6ee680dacb0566a276bff907ccb#diff-def87b236277e39eb2ec3c0e1a761f3f).

During composition, `$event.keyCode` for keyboard events will always be the first key that triggers composition while `$event.key` points to the actual pressed key. Before the commit above, we always checked `keyCode` first so the handler won't be triggered. After that we check `key` first so it leads to this issue. Not sure what should be the intended behavior because I'm not familiar with the background of this change so maybe this should be discussed further.

**Comment by Justineo** [comment]
On a second thought I think current behavior is more reasonable. It’s more accurate and you can use `compositionstart`/`compositionend` events to check if a keydown event happens during composition. There seems no reason to revert.

**Comment by toBeTheLight** [comment]
@Justineo  I have found another issue，if there is an alert(or window.open) in handler, the event will fire twice in IE. 
And i had changed code in the reproduction link.
Should i open a new issue ?

**Comment by Justineo** [comment]
Yes, please open a new issue.
