### ISSUE TITLE
Render function on input removes reactivity

### ISSUE THREAD

**Issue by Acidic9** [vuejs/vue#9027]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/embed/oooq7o2q16?module=%2Fsrc%2FApp.vue](https://codesandbox.io/embed/oooq7o2q16?module=%2Fsrc%2FApp.vue)

### Steps to reproduce
Create a vue component js file with a render function which is simply an input and a value.

### What is expected?
The input should stay reactive with the data, no matter if it's manually edited.

### What is actually happening?
The input loses reactivity after being manually edited.

### Extra info
https://stackoverflow.com/questions/53149991/render-function-on-input-removes-reactivity-in-vue

**Comment by LinusBorg** [comment]
You are using `attrs` to set the `value` attribute. as soon as you edit the content of the input, the *attribute*'s value is still updated in the DOM (you can check your console) but that attribute is no longer relevant to what is being displayed, because by spec, the `value` *attribute* is only the initial value, and as soon as the user changes it, it's no longer relevant even if you updater it later.

That's why in the render function generated by the template, Vue doesn't use `attrs`, it uses `domProps`. It looks something like this:
```javascript
render(createElement) {
    return createElement("input", {
      domProps: { value: this.value }
    });
  }
```

Now, we don't change the *attribute* by changing the DOM, we change the *property* wiht javascript.

In vanilla javascript, the difference between the two concepts looks like this:
```javascript
const el = document.querySelector('#yourelement')
// changing the attribute - this will have no effect once the user changes the input themselves:
el.setAttribute('value', 'new value')

// changing the DOM property - this will overwrite the changes that the user did:
el.value = 'new value'
```
