### ISSUE TITLE
Why is the next Vue-next not submitting code inreal time?

### ISSUE THREAD

**Issue by bailnl** [vuejs/vue#9028]
### What problem does this feature solve?
Why is the next Vue-next not submitting code inreal time?

### What does the proposed API look like?
Why is the next Vue-next not submitting code inreal time?

**Comment by LinusBorg** [comment]
We don't understand your question.

**Comment by jacekkarczmarczyk** [comment]
I guess he's asking why there's no commits related to 2.X-next or 3.0

**Comment by LinusBorg** [comment]
Oh, thanks, that makes sense. 

Because we are still prototyping. 

At this stage, having everyone join in would create too much confusion. 

We will share the full code alongside detailed RFCs once we feel that we reached something that is worth discussing. 

Right now, we change things a round practically in a daily basis, so people would have your le following  and discussing changes effectively.

**Comment by bailnl** [comment]
@LinusBorg  @jacekkarczmarczyk  thanks
