### ISSUE TITLE
'too much recursion' for Provided   Mixins

### ISSUE THREAD

**Issue by lrembacz** [vuejs/vue#9032]
### Version
2.5.7

### Reproduction link
[https://codesandbox.io/s/2vnzq8659y](https://codesandbox.io/s/2vnzq8659y)

### Steps to reproduce
Component is a mixins Component with @Provided implemented.
We uses @Mixins for another component and after that we getting error.

### What is expected?
Getting Provided EventBus and no errors about recursions.

### What is actually happening?
There are too much recursions alert and problem with mergeData for components.

---
When we are using Provided inside main component there is no error alert.

**Comment by posva** [comment]
Your code doesn't seem to output that error.
The thing here is that the problem could come from vue-property-decorator since you are heavily using it
To me it looks like this PR https://github.com/vuejs/vue/pull/8870 fixes the problem. If it doesn't, please provide a repro without the vue-property-decorator or open an issue there
