### ISSUE TITLE
<template> within scope slot not displaying child elements

### ISSUE THREAD

**Issue by lifedispenser** [vuejs/vue#9047]
### Version
edge (2.5.17)

### Reproduction link
[http://jsfiddle.net/eywraw8t/452973/](http://jsfiddle.net/eywraw8t/452973/)

### Steps to reproduce
See fiddle. If you change the `template` tag to `div` then the 'hello' does render from the scoped slot.

### What is expected?
hello should be rendered in the template tag

### What is actually happening?
hello is not being rendered

---
Couldn't find any documentation supporting this behavior. Also have seen a lot of tutorials showing templates used with scope slots.

**Comment by posva** [comment]
Please, check the console. when using `template` you are returning multiple nodes. You can either use a functional component or wrap what is rendered by `$scopedSlots`

**Comment by Justineo** [comment]
When you use a `<template>`, its children will be returned, so `this.$scopedSlot.default(...)` returns an array of `VNode`. When you use a `<div>` then the node itself will be returned, which makes `this.$scopedSlot.default(...)` return a single `VNode`. When you use `<template>`, the `example` component isn't rendering correctly because it doesn't have a single root node. You can

1. wrap the scoped slot with a single node
2. try to return the first child if by the scoped slot returns an array

**Comment by xxRockOnxx** [comment]
@Justineo I can confirmed what you said. So is the docs wrong then? I'm referring to the `todo-list` example from ehere https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots
