### ISSUE TITLE
Does not send forms by POST

### ISSUE THREAD

**Issue by nazar2692** [vuejs/vue#9056]
### Version
2.5.17

### Reproduction link
[https://codepen.io/Myron26/pen/zMoqJj?editors=1010](https://codepen.io/Myron26/pen/zMoqJj?editors=1010)

### Steps to reproduce
Choose different values for selects and send form

### What is expected?
not sent data to the server

### What is actually happening?
if you use the same form without vue js cycles then the data is sent to the server

**Comment by posva** [comment]
it does send the request as a regular form

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
