### ISSUE TITLE
Vue   Typescript   Inversify -> Injecting VueComponent via Inversify container.

### ISSUE THREAD

**Issue by lrembacz** [vuejs/vue#9077]
### Version
2.5.7

### Reproduction link
[https://codesandbox.io/s/oxjrp8j0xy](https://codesandbox.io/s/oxjrp8j0xy)

### Steps to reproduce
Getting error when injecting VueComponent from implementation.

### What is expected?
Injection is working.

### What is actually happening?
Error in created hook: "Error: The number of constructor arguments in the derived class Test must be >= than the number of constructor arguments of its base class."

---
What should be provided in constructor if super() called doesnt actually work? Is there any better solution to do that?

**Comment by posva** [comment]
The error you get is unrelated to Vue. It comes from `container.get<Testable>("Testable");`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
