### ISSUE TITLE
undefined when i want to  programmatic navigation using this.$router.push({path:'pathName'})

### ISSUE THREAD

**Issue by manusiakemos** [vuejs/vue#9080]
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/pj6w3lwn20](https://codesandbox.io/s/pj6w3lwn20)

### Steps to reproduce
fix it

### What is expected?
move to the route that i want to

### What is actually happening?
return undefined in console

**Comment by posva** [comment]
This is too much for a repro

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
