### ISSUE TITLE
v-if should work with out v-else

### ISSUE THREAD

**Issue by fabianrios** [vuejs/vue#9113]
### What problem does this feature solve?
if I want just not to render a part of the template I should be able to do it by putting v-if="data" but at the moment the contents inside get evaluated so if data is empty and inside I do something like data.property then it breaks because data.property is undefined, unless I put a v-else. if I already put a conditional saying only process when there is data, why it should force me to make a v-else if I don´t have anything else to show.

### What does the proposed API look like?
<div v-if="data"></div>

**Comment by posva** [comment]
Yeah, this is the same as a regular `if` in js, you have to `if (data && data.property)`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by fabianrios** [comment]
I was using :v-if instead of v-if, stupid mistake sorry for that.

**Comment by posva** [comment]
Ah, I see, you may be interested in this eslint-rule: https://github.com/vuejs/eslint-plugin-vue/issues/328 😉
