### ISSUE TITLE
入口app.vue 中 update之前的生命周期取不到当前页面的路由信息

### ISSUE THREAD

**Issue by ApolloRoad** [vuejs/vue#9125]
### Version
2.5.17

### Reproduction link
[https://github.com/ApolloRoad/vue-new-issue](https://github.com/ApolloRoad/vue-new-issue)

### Steps to reproduce
2分钟复现
例如   当前url为  http://localhost:8080/#/about?bid=1
在 app.vue  created的时候取  this.$route.name 为null   , 但是在 about页面created的时候为 about,   app.vue只有在 update的时候才能取到

### What is expected?
所有生命周期应该都能取到

### What is actually happening?
codesandbox在线编译无法复现,本地调试编译是可以取到的，再次地址栏回车或者关掉直接打开字页面以及上线是不行的

---
我的问题已经解决了，但理论上应该能取到，我做微信开发，微信大部分业务都通过url完成。

**Comment by posva** [comment]
It's because you are using a lazy import, delaying the actual navigation to the route

----

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
