### ISSUE TITLE
Using  statement evaluated as a function(e.g. `f.bind()`) inside v-on handler doesn't work

### ISSUE THREAD

**Issue by jaeseokk** [vuejs/vue#9261]
### Version
2.5.21

### Reproduction link
[https://codesandbox.io/s/vq4rx8pzk7?module=%2Fsrc%2FApp.vue](https://codesandbox.io/s/vq4rx8pzk7?module=%2Fsrc%2FApp.vue)

### Steps to reproduce
Use method with `bind()`(e.g. `someMethods.bind(this)`) in v-on handler
```vue
<button v-on:click="handleButtonClick.bind(this);">not working</button>
```

### What is expected?
When the event triggered,  the registered method handler should be called.

### What is actually happening?
The registered method is not called. `some.Methods.bind(this)` is recognized as simple inline statement.

**Comment by Justineo** [comment]
It's expected. Vue will invoke the handler for you only if you provide a property path or a function literal.

https://github.com/vuejs/vue/blob/0ed0aad77228b95e9a61a87386736938837527f8/src/compiler/codegen/events.js#L99-L106

BTW, You don't need to call `bind` because methods are already bound to the component instance, unless you mistakenly used arrow functions.
