### ISSUE TITLE
Web component - Benchmark

### ISSUE THREAD

**Issue by vogloblinsky** [vuejs/vue#9279]
Hi,

I have created a benchmark suite for Web Components librairies. Vue.js is implemented with his web component target feature, and you can see the raw results here : https://vogloblinsky.github.io/web-components-benchmark/

I will release soon a blog post explaining in detail that, but i want a feedback of many librairies authors before, to be sure i am not wrong in my implementations.

Source code here : https://github.com/vogloblinsky/web-components-benchmark

Can you have a look and give me some feedbacks ?

Thanks

**Comment by yyx990803** [comment]
Some feedback:

- Use `vue.runtime.min.js` - built web components don't need the compiler at runtime.

- Use `export default` instead of `module.exports`. The latter bails out of module concatenation.

- Building one component file for each component in an app is not the intended usage: all the common modules used by the components will be duplicated, including the webpack wrapper, css injection runtime, etc... this significantly bloats the bundle. Unless you want each component inside your app to be usable standalone, it's pretty pointless to do it like this (also makes the build scripts more complex, the bundle bigger and slower...) Suggested usage is write the Vue app exactly how you'd write it as a normal Vue app (importing child components) and build a single web component for the entire app.

**Comment by yyx990803** [comment]
BTW, some implementations (e.g. Riot.js) isn't actually exporting native web components...
