### ISSUE TITLE
Object order is not retained

### ISSUE THREAD

**Issue by aurimus** [vuejs/vue#9310]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/Luqme3f6/](https://jsfiddle.net/Luqme3f6/)

### Steps to reproduce
1. Object with keys as numbers unsorted
2. v-for loop

### What is expected?
The order should be retained

### What is actually happening?
The object is sorted by keys

**Comment by Justineo** [comment]
This is the expected behavior as 
1. Object traversing order is not specified in ES3, so you'd better not rely on the declaration order
2. The order is now specified in ES6(ES2015), and integer indices are sorted in ascending order so your code is working as expected

Read more at http://2ality.com/2015/10/property-traversal-order-es6.html.

**Comment by Justineo** [comment]
> What if I am developing for new browsers only? (admin interface)

What I mean is your usage will lead to incorrect results no matter you are developing for new browsers or not.

> You must be incorrect about sorting order - check the provided fiddle!

Have you read the post I mentioned above? The order of integer indices won’t be retained. Just how your fiddle is behaving.
