### ISSUE TITLE
Feature: add templateUrl

### ISSUE THREAD

**Issue by phplego** [vuejs/vue#9312]
I know it has been closed by devs many times, but I beleive it should be opened again. Please let US choose the way we store the template.

**Comment by Justineo** [comment]
Hello, your issue has been closed because it does not conform to our issue requirements. In order to ensure every issue provides the necessary information for us to investigate, we require the use of the [Issue Helper](https://new-issue.vuejs.org/?repo=vuejs/vue) when creating new issues. Thank you!
