### ISSUE TITLE
Vue input component $emit event not consistent

### ISSUE THREAD

**Issue by mheere** [vuejs/vue#9321]
### Version
2.5.22

### Reproduction link
[https://jsfiddle.net/mheere/rfLo9gn7/21/](https://jsfiddle.net/mheere/rfLo9gn7/21/)

### Steps to reproduce
Run the fiddle

### What is expected?
When entering more than 3 chars it should not allow any more editing of the text...

### What is actually happening?
First keydown it works (as in, it cuts off the text) but then it allows the text to grow more than 3 chars..

**Comment by Justineo** [comment]
In this case you are emitting the same value (the first three characters) so it won't trigger `v-model` to be updated, otherwise it may lead to infinite updates. In this case, you should handle the local data yourself inside the custom input element (eg. Directly fixing the value of the input element via DOM API).

**Comment by Justineo** [comment]
https://jsfiddle.net/Justineo/sfm28gk5/2/

**Comment by mheere** [comment]
Hi Gu - that is brilliant - thanks!
If you are ever in London I'll buy you a drink!
Cheers
Marcel
