### ISSUE TITLE
ios10打开白屏，报错是unexpected token '*'

### ISSUE THREAD

**Issue by cluod** [vuejs/vue#9339]
### Version
2.5.16

### Reproduction link
[http://app.starluxe.cn/#/libeika?shareOriginChannel=libeika&utm_source=libeika](http://app.starluxe.cn/#/libeika?shareOriginChannel=libeika&utm_source=libeika)

![image](https://user-images.githubusercontent.com/15325313/51363705-40aebc80-1b14-11e9-8eb7-bbc3e16116ee.png)

### Steps to reproduce
ios10打开白屏

### What is expected?
告知问题原因

### What is actually happening?
ios10打开白屏

**Comment by Justineo** [comment]
I'm sorry but it is not a valid reproduction. We require a link to **minimal** reproduction, instead of a URL of your whole project. Please try to boil down the problem so we'll be able to look into. If you have questions about minimal reproductions, please read this part of the [issue helper](https://new-issue.vuejs.org/?repo=vuejs/vue):

![image](https://user-images.githubusercontent.com/1726061/51364032-8cae3100-1b15-11e9-8839-bfeadcacde70.png)

**Comment by sodatea** [comment]
http://lmgtfy.com/?q=iOS+Vue+unexpected+token+%27*%27

Google 到的第一个链接就是，Swiper 的问题。
