### ISSUE TITLE
Custom directives must be provided value in pug template

### ISSUE THREAD

**Issue by lxmfly123** [vuejs/vue#9351]
### Version
2.5.17

### Reproduction link
[https://codepen.io/lxm9/pen/pGzWWz?editors=1011](https://codepen.io/lxm9/pen/pGzWWz?editors=1011)

### Steps to reproduce
Just open the reproduction link and watch

### What is expected?
The `input` element should be focused.

### What is actually happening?
The console output error: v is not defined.

---
Custom directives must be provided value in pug template, or it will raise an error: v is not defined.

**Comment by posva** [comment]
This is related to pug. You can change the behaviour with `doctype`: https://pugjs.org/api/reference.html#options

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by lxmfly123** [comment]
Thanks and sorry. I did search in the forum and found no specific answer, but I missed StackOverflow. I guess maybe the doc of vue can add some tips on pug.
