### ISSUE TITLE
Please put the uninstall command in the official document.

### ISSUE THREAD

**Issue by nkgwnoto** [vuejs/vue#9374]
### What problem does this feature solve?
Premise
· The npm install vue described in the installation page of the official documentation page https://vuejs.org/v2/guide/installation.html has been executed and installed.
· I wanted to revert to a state that was not installed once and install it again.

trouble
· Uninstall command corresponding to installation command of official document could not be found

Suggestion
· I want you to put the uninstall command in the official document.

### What does the proposed API look like?
Since this is an issue for the document this time, there is no proposal for the API.

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vuejs.org

**Comment by innofreitas** [comment]
Diretmasmter@hotmail

Em 26 de jan de 2019 03:31, "nkgwnoto" <notifications@github.com> escreveu:

What problem does this feature solve?

Premise
· The npm install vue described in the installation page of the official
documentation page https://vuejs.org/v2/guide/installation.html has been
executed and installed.
· I wanted to revert to a state that was not installed once and install it
again.

trouble
· Uninstall command corresponding to installation command of official
document could not be found

Suggestion
· I want you to put the uninstall command in the official document.
What does the proposed API look like?

Since this is an issue for the document this time, there is no proposal for
the API.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vuejs/vue/issues/9374>, or mute the thread

**Comment by innofreitas** [comment]
Em sáb, 26 de jan de 2019 04:10, Jacek Karczmarczyk <
notifications@github.com escreveu:
