### ISSUE TITLE
Unmounting a target in an event handler stops that event from propagatin

### ISSUE THREAD

**Issue by ianwremmel** [vuejs/vue#9478]
### Version
2.6.0

### Reproduction link
[https://codepen.io/ianwremmel/pen/omdQxG](https://codepen.io/ianwremmel/pen/omdQxG)

### Steps to reproduce
Click the submit button

### What is expected?
The page posts back to itself

### What is actually happening?
The button disappears and nothing else happens

---
This changed somewhere between 2.5.22 and 2.6.0. I assume it had something do with the increased use of microtask.

This is clearly an odd reproduction example, but it's the minimal reproduction for something that is, in fact, useful. We have a Vue components that replaces our buttons with a spinner so that they can't be double submitted.

**Comment by yyx990803** [comment]
Yeah, this is unfortunately the expected behavior after 2.6 - it is easier if you think of the update as synchronous. The button is removed from the DOM before the event bubbles to the form, so the event is actually cancelled. A workaround is setting your `clicked` flag in a setTimeout(0), essentially waiting until the event has finished bubbling before removing the button.

**Comment by ianwremmel** [comment]
I know it’s an edge case, but shouldn’t this have been treated as a breaking change? The docs imply (though admittedly they don’t explicitly state) that the 2.5 behavior is what one should expect unless stop propagation is explicitly indicated.

**Comment by yyx990803** [comment]
This does technically break some edge cases, however it was necessary to fix other more important cases caused by not using microtasks. As explained, microtasks are conceptually similar to synchronous updates when we are talking about ordering against DOM events. So if you write a button that instantly removes itself when clicked, the submit event will not trigger either. This happens even if you are not using Vue, and the only workaround is to delay the removal of the button.
