### ISSUE TITLE
Inconsistent order of events

### ISSUE THREAD

**Issue by asvny** [vuejs/vue#9480]
### Version
2.6.5

### Reproduction link
[https://jsfiddle.net/8g1nh5rc/1/](https://jsfiddle.net/8g1nh5rc/1/)

### Steps to reproduce
1. When I click 'Show panel' button , it logs clicked outside

### What is expected?
For the first click, it should not invoke v-click-outside event handlers 

### What is actually happening?
When I click the button, it invokes the v-click-outside handler eagerly.

---
I have filed the issue here rather in the v-click-outside because I suspect it is because of scheduling of micro-tasks because it used to work fine for older versions of Vue (https://jsfiddle.net/amw9rfhq)

**Comment by posva** [comment]
It's the library since v-clickaway works correctly: https://jsfiddle.net/sz8jLn5e/

**Comment by LinusBorg** [comment]
Well, it's surely related to our revert of the way we handle micro/macro tasks. 

But that revert was necessary to avoid other, more common issues  that the change in 2.5 introduced.

And since all we did was revert to the pre-2.5 behaviour, the lib you are using is also failing with any version before 2.5:

https://jsfiddle.net/Linusborg/7c4pw20v/

We're aware that this is in a grey area between a bugfix and a breaking change, but it was necessary as best as we could tell. So it has to be fixed in the library.

**Comment by asvny** [comment]
@posva  and @LinusBorg  .. that was very helpful .. thank you !
