### ISSUE TITLE
keyup

### ISSUE THREAD

**Issue by five00miles** [vuejs/vue#9481]
### Version
2.6.4

### Reproduction link
[https://codepen.io/anon/pen/WPJWWZ#anon-signup](https://codepen.io/anon/pen/WPJWWZ#anon-signup)

### Steps to reproduce
直接使用不同版本vue即可

### What is expected?
解决或者告知是否哪里出了问题

### What is actually happening?
keyup在不同版本的vue中，对应的安卓浏览器和安卓微信下的反应不同，或支持或无效，我手中的是mix2s

**Comment by posva** [comment]
it is indeed wrong, you use one version of vue not multiple ones.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
