### ISSUE TITLE
Array Deep Change for HTML Attr.

### ISSUE THREAD

**Issue by BoltDoggy** [vuejs/vue#9494]
### Version
2.5.17

### Reproduction link
[https://jsfiddle.net/71wrbz2c/2/](https://jsfiddle.net/71wrbz2c/2/)

### Steps to reproduce
Click the div, and Use Chrome Developer tool, you can see

<img width="333" alt="default" src="https://user-images.githubusercontent.com/2586280/52774663-b7d66280-3078-11e9-942d-eb65b2ab23bc.png">

### What is expected?

```
{{arr}} // show [['1', '2'], ['2', '1']]
  <div :data-arr="arr" @click="test">点击我</div> // data-arr show [['1', '2'], ['2', '1']] => 1,2,2,1, too
```

### What is actually happening?

```
{{arr}} // show [['1', '2'], ['2', '1']] is true
  <div :data-arr="arr" @click="test">点击我</div> // data-arr show [['1', '2'], ['2']] => 1,2,2 is false
```

**Comment by posva** [comment]
Because html attributes are stored as strings, it makes sense (for performance reasons) to only check if the actual value changes, in the case of an array or object, that would be the reference to it, which doesn't change unless you replace the whole array. So, using `:data-arr="arr.toString()` will make it work as you expect.
I could be wrong about the performance but keep in mind the only reason this works is because the toString method is being called automatically by the browser making it look like you can pass an array

**Comment by yyx990803** [comment]
Maybe for plain attrs we want to compare the values after we convert both to strings.
