### ISSUE TITLE
Make Vue.observable work directly on arrays

### ISSUE THREAD

**Issue by mitar** [vuejs/vue#9500]
### What problem does this feature solve?
This would allow one to have state as an array of values without a need for intermediary wrapper plain objects.

See example: https://jsfiddle.net/9L5ymbv7/

### What does the proposed API look like?
No changes to the API, just support that `Vue.observable` would work on an array.

**Comment by JMsnow** [comment]
### a

**Comment by Shasharoman** [comment]
### More detail for this feature request

I want to try to add this feature, and finally give up because I am not familiar enough with Vue development. Here is the reason I found the problem, I hope this helps the developers who want to add this feature.

code example: https://jsfiddle.net/o8qagk1e/

The reason is that when `Vue.observable` directly uses an array as a parameter, the access value in the corresponding watcher cannot trigger pub/sub dependency collection, because using the array directly in the watcher does not trigger the corresponding `getter` method.

A workaround is to use a wrapped array object like {items: []}.

**Comment by yyx990803** [comment]
Unfortunately this is not possible given ES5 limitations. Will be supported in v3 (when using Proxies) though.

**Comment by avioli** [comment]
Best I could come up with is this:

https://jsfiddle.net/yhg5d6ck/

```js
Vue.observableArray = function(data) {
  const wrapper = Vue.observable({ array: Array.from(data || []) });
  const getter = () => wrapper.array;
  const setter = (value) => {
    wrapper.array = Array.from(value || []);
  };
  return { get: getter, set: setter };
};

const todosGetter = Vue.observableArray([1, 2, 3]);

new Vue({
  el: "#app",
  computed: {
    todos: todosGetter,
    arrayLength: function() {
      return this.todos.length;
    },
  },
  methods: {
    onClick: function () {
      this.todos.push({});
    },
    onReset: function() {
      this.todos = new Set([1, 2, 3, 1, 2, 3]);
    },
  },
});
```
