### ISSUE TITLE
There is a break change in 2.6 that is not involved in release log

### ISSUE THREAD

**Issue by aimergenge** [vuejs/vue#9552]
### Version
2.6.7

### Reproduction link
[https://codesandbox.io/s/v8n1p04v85](https://codesandbox.io/s/v8n1p04v85)

### Steps to reproduce
click the checkbox, the `checked` data changed, while the checked of the checkbox didn't, thus the UI is different from the data.

This didn't occurred below vue2.6.

### What is expected?
the checkbox update wrongly

### What is actually happening?
the checkbox update correctlly

**Comment by aimergenge** [comment]
the key thing may be: how vue handle event.preventDefault() is different from before.

**Comment by LinusBorg** [comment]
Dupicate of #9535 
We don't consider this a breaking change, but rather a fix, because the behaviour that we have in 2.6 (and had before 2.5) is more correct - preventing the default behaviour of a checkbox prevents the browser from marking it checked.

The code you show here only worked accidentally in 2.5, as a side effect of the patch algo using a macrotask. 

I also don't understand why possible usecase the preventDefault could have here.
