### ISSUE TITLE
v2.6.7 breaks scoped slots compiled with older version

### ISSUE THREAD

**Issue by AngusFu** [vuejs/vue#9553]
### Version
2.6.7

### Reproduction link
[https://codesandbox.io/s/r5903m5vjp](https://codesandbox.io/s/r5903m5vjp)

### Steps to reproduce

使用 vue@2.6.6 以及之前版本开发、编译的 UI 组件库，在与 vue@2.6.7 一起工作时报错。

原因在于：Commit [7ec4627](https://github.com/vuejs/vue/commit/7ec4627902020cccd7b3f4fbc63e1b0d6b9798cd) 改变了 `resolveScopedSlots` 方法的参数顺序。

### What is expected?
v2.6.7 应该继续支持旧的 scoped slot 编译结果吧？

否则，难道 vue 每 release 一次，各种 UI 组件库的开发者们也得重新跟着重新编译发版吗？

### What is actually happening?

vue@2.6.6 及 vue@2.5.x 编译后的 scope slots，在 vue@2.6.7  环境能够不报错。

![](https://ws4.sinaimg.cn/large/006tKfTcly1g0ffs6r2lsj31h40hu40x.jpg)

**Comment by Justineo** [comment]
If I understand correctly this commit is actually a bug fix for the issue that components built in 2.6.6 cannot work in 2.5.x's runtime. But unfortunately for components build with compiler 2.6.6 they are actually depending on a bug which was fixed in 2.6.7. So components built with 2.6.6 or maybe some of the prior 2.6.x versions will be required to be compiled again with latest version to make them compatible with 2.5.x & 2.6.7+.

> v2.6.7 应该继续支持旧的 scoped slot 编译结果吧？

Yes but 2.6.7 is fixing a breaking change.

Sorry for the inconvenience.

**Comment by AngusFu** [comment]
@Justineo Thx, I got it.

也就是说，2.6.7+ 的编译结果能够兼容 2.5.x 的 runtime，因此我应该用 2.6.7+ 去重新编译我的 UI libary，并且，在使用时，必须使用 2.5.x 的 runtime，或者 2.6.7+ 的 runtime。（试了下， 2.6.6 的 runtime 不行）。

**Comment by Justineo** [comment]
You are right.

**Comment by yyx990803** [comment]
对，根本原因是 2.6.4~2.6.6 这个范围内的版本的参数顺序有问题，跟 2.5/2.6.7+ 不兼容，所以避免用几个版本去编译你的库即可。

**Comment by donglegend** [comment]
slot-scope 用在循环里，2.6.7版本还是有同样的问题。2.6.4之前没问题

**Comment by Justineo** [comment]
@donglegend 请创建一个可以重现的新 issue，谢谢！

**Comment by donglegend** [comment]
> @donglegend 请创建一个可以重现的新 issue，谢谢！

不好意思，当我试图创建一个新的 情景浮现时，问题不再出现。但是我的那个项目安装2.6.7却有问题，由于项目比较复杂了，可能由于某些缓存等不可知原因，我再探究一下，谢谢！

**Comment by donglegend** [comment]
@Justineo 
不好意思，当我试图创建一个纯净的场景浮现时，问题不再出现。但是我的项目安装v2.6.7却有问题，猜测可能由于项目比较复杂，或许是缓存或者其他原因，我再探究一下，谢谢！
