### ISSUE TITLE
$forceUpdate doesn't affect checkbox

### ISSUE THREAD

**Issue by aimergenge** [vuejs/vue#9575]
### Version
2.6.7

### Reproduction link
[https://codesandbox.io/s/v8n1p04v85](https://codesandbox.io/s/v8n1p04v85)

### Steps to reproduce
1. have a look at code in BreakDemo.vue
2. input some text in the text input, after 1s, the value reset to default
3. select another option, after 1s , the value reset to default
4. click on the checkbox, after 1s, the value doesn’t reset to default

### What is expected?
the value of checkbox is resetted

### What is actually happening?
the value of checkbox is not resetted

---
It seems that $forceUpdate doesn't affect checkbox

**Comment by yyx990803** [comment]
You should not rely on `$forceUpdate` like that - the way your checkbox is set up makes it get out-of-sync with your component state, so the checkbox in the DOM is checked but your state says it's not. On next update Vue thinks nothing has changed **because the state didn't change**.

In Vue you are responsible for making sure the checkbox syncs its DOM checked state back to your component state, using e.g. `v-model`.

**Comment by benface** [comment]
I know it's been some time since this issue was closed, but I just wanted to say that I find this behavior very confusing. I would expect `$forceUpdate()` to re-render everything, including `checked`. Why does it work with `value` but not `checked`? Seems inconsistent.
