### ISSUE TITLE
Support Vueify

### ISSUE THREAD

**Issue by golgote** [vuejs/vue#9587]
### What problem does this feature solve?
We have noticed that the Vueify repository on Github is being **archived** so we cannot post issues there anymore and I don't know where else to post this opinion. We use **Vueify** and Browserify to deploy our components. We don't build full SPA or Apps, we just enhance some parts of our websites with Vue. I bet a lot of other users also use Vue this way, because this is one of Vue strength as mentioned on the frontpage.

> An incrementally adoptable ecosystem that scales between a library and a full-featured framework.

We also don't really use nodejs, we are a PHP shop, so we try to mix both Vue and PHP together without diving too much into the nodejs ecosystem. Browserify has been a mean to do that and it serves us well by allowing us to use npm packages in the browser without too much troubles. Is this going against progress? I don't know. I have had a look at webpack and rollup, and all I can say is that it is not for us because there is too much configuration involved. I also tried VueCLI and it's great, but it seems to be designed for building full apps. If some day we have requests for full apps, we will definitely use it because it makes a great job at hiding the webpack complexities. 

But for today, all I am asking is that you unarchive the Vueify repository and maybe grant admin access to someone who might have the time and willingness to maintain it and keep it alive? (not me, I don't have time nor skill to do it, sorry)

Or if you consider it is really dead, maybe you could write a little tutorial on how to achieve the same things with webpack, just for people who need to migrate (ie. take modules from node_modules and bundle them for use with require() and parse .vue SFC and bundle css in css directory and js in the js bundle). 

Thanks very much.

### What does the proposed API look like?
Trying to keep a command like this alive:

`browserify -t [ envify --NODE_ENV production ] -t vueify -p [ vueify/plugins/extract-css -o public/css/bundle.css ] main.js -o public/js/bundle.js`

**Comment by posva** [comment]
> it is not for us because there is too much configuration involved

Well, what to say, so you want us to keep a tool updated because you don't want to write the configuration for more up to date and powerful tools?
AFAIK vueify still works with browserify

> But for today, all I am asking is that you unarchive the Vueify repository and maybe grant admin access to someone who might have the time and willingness to maintain it and keep it alive? (not me, I don't have time nor skill to do it, sorry)

Seems fair but who is going to maintain it? Unarchiving will not achieve anything. We can add a message to the top of the repo but we cannot just give away the package to the first person who wants to maintain it and keep it as an official solution.
I think the best would be for someone willing to maintain it (outside of the core team) to fork the project and we could link it in the readme

cc @yyx990803 in case I'm forgetting anything

**Comment by leopiccionia** [comment]
> We also don't really use nodejs, we are a PHP shop, so we try to mix both Vue and PHP together without diving too much into the nodejs ecosystem.

The shop where I work is not PHP-only, but we use [Laravel Mix](https://laravel-mix.com/docs/4.0/mixjs) for similar scenarios. It's a wrapper around Webpack, requires minimal configuration, has built-in suppor for *.Vue files (via `vue-loader`) and doesn't require Laravel.

**Comment by golgote** [comment]
Thanks for sharing @leopiccionia I'll give it a try.

**Comment by golgote** [comment]
I have had a look at laravel-mix and it is not a solution because it uses webpack and webpack forces you to do thing like that : https://github.com/laravel/laravel/blob/master/resources/js/bootstrap.js

This is a little ridiculous because they bundle things and then they make them global again... So we will stick with Browserify for now and wait for the next big thing in javascript, that will hopefully allow us to get rid of all this mess.

**Comment by josephlarralde** [comment]
+1

I'm developing cordova + vuejs apps, and I have a very simple custom build system that I would love to be able to keep using.
example here : https://github.com/CRI-MotionLab/Streamo
Right now I'm reading webpack docs but they are very dense and look overcomplicated compared to my build scripts.
Anyway, I guess I have no choice to switch to webpack since I won't be the one who will maintain vueify, and its dependencies already have reported vulnerability issues, but that's a significant loss of time in my case.

Cheers
