### ISSUE TITLE
Handle acronym in  PascalCase to kebab-case

### ISSUE THREAD

**Issue by mortyccp** [vuejs/vue#9620]
### What problem does this feature solve?
Given my component name with acronym as `HTTPImage`, the kebab-case is `<h-t-t-p-image>`.  
Without global register and repeatedly redefine the register name each time the component is used, can we add support to change it to `<http-image>`.

### What does the proposed API look like?
Without breaking program using `VButton` style, we might add option to opt for this style.

**Comment by Justineo** [comment]
Using initialism may lead to ambiguity if you have adjacent abbreviations. eg. instead of `XMLHTTPRequest`, we have `XMLHttpRequest` (as you can see it's still inconsistent). I think I'd rather use `HttpImage` (treating an abbreviation as a word) for your case so it would naturally match to `http-image`.

**Comment by mortyccp** [comment]
OK. You have a great point on adjacent acronym. Will accept this tradeoff and avoid acronym. Thanks
