### ISSUE TITLE
optionMergeStrategies does not set 3rd "vm" argument for components

### ISSUE THREAD

**Issue by berniegp** [vuejs/vue#9623]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/ugv3rL7w/](https://jsfiddle.net/ugv3rL7w/)

### Steps to reproduce
Assign a function to "Vue.config.optionMergeStrategies.created" that uses the 3rd "vm" argument.

### What is expected?
The documentation for "optionMergeStrategies" states:

"The context Vue instance is passed as the third argument."

### What is actually happening?
The "Vue.config.optionMergeStrategies.created" function does not receive a Vue instance when merging properties of components.

---
The "vm" argument is correctly passed when merging options of the root Vue instance, but not for components.

**Comment by yyx990803** [comment]
This should be a documentation issue - merge strategy functions can be called during both Component class creation and instance creation. In the former case there is no instance to be passed, so it is undefined. The latter case is very rare as it only happens when you are manually `new`ing an extended component.
