### ISSUE TITLE
当.vue文件中的div的class名称为m-ad时，会导致节点内容显示不出来

### ISSUE THREAD

**Issue by mypridelife** [vuejs/vue#9710]
### Version
2.6.8

### Reproduction link
[https://jsbin.com/lilicek/edit?html,output](https://jsbin.com/lilicek/edit?html,output)

### What is expected?
页面显示hello world

### What is actually happening?
浏览器：谷歌。
页面未显示任何内容

---
在普通的html中未复现，故怀疑是vue的问题，才疏学浅，不知道从何排查起，求告知，谢谢

**Comment by posva** [comment]
The page works... Also you are using a very old version of Vue in your repro

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
