### ISSUE TITLE
Default scoped slot is not present under data.scopedSlots object in functional component

### ISSUE THREAD

**Issue by sqal** [vuejs/vue#9711]
### Version
2.6.8

### Reproduction link
[https://jsfiddle.net/m7thp9o8/](https://jsfiddle.net/m7thp9o8/)

### Steps to reproduce
- Check console logs

### What is expected?
I expect `data.scopedSlots` to always be the same as its mirrored object `scopedSlots` in functional component context.

### What is actually happening?
Default scoped slot function is undefined in `data.scopedSlots` (but not in `context.scopedSlots`) object unless I explicitly use default scoped slot the template, 

```vue
<template #default>
  <p>main content</p>
</template>
```

**Comment by yyx990803** [comment]
This is expected. `data.scopedSlots` is the raw scopedSlots that is passed from the parent, and you should not use it directly (since in manually written render functions, it can literally be anything) - `context.scopedSlots` on the other hand is the normalized value with additional guarantees - e.g. proxying to normal slots & always returning array of VNodes.

In this case `default` is actually a normal slot and only exists on `context.scopedSlots` because of the proxying behavior.
