### ISSUE TITLE
Interaction between v-scope and v-if not correct (regression from 2.5.x)

### ISSUE THREAD

**Issue by patrickas** [vuejs/vue#9725]
### Version
2.6.8

### Reproduction link
[http://jsfiddle.net/1pyxu5ch/1/](http://jsfiddle.net/1pyxu5ch/1/)

### Steps to reproduce
The fiddle contains two parts.

Part 1 is the old working syntax.

Part 2 is the commented out new syntax that does not work anymore. Un-commenting this part triggers the error.

### What is expected?
template is only included when the condition is true

### What is actually happening?
syntax error

---
The fiddle uses 2.6.9 from https://unpkg.com/vue@2.6.9/dist/vue.js but I could not find that version in the drop down so I put 2.6.8 instead.

This was actually originally reported in issue #9658 for 2.6.8 and fixed in https://github.com/vuejs/vue/commit/781c70514e01bc402828946805bfad7437c7175e but it seems the fix is not enough since the issue is still happening.

Filing as a regression since the old functionality will be discontinued in future releases.

**Comment by yyx990803** [comment]
Note: this the expected behavior when using the new syntax (I forgot to clarify this in the commit that fixed #9658)

- When using the new syntax, `v-if` on `<template v-slot>` has a higher priority. Conceptually, this `v-if` determines whether the slot is passed to the child, and has no access the the slot scope.

- The solution is to use an additional `<template v-if>` **inside** the slot, which is more explicit.
