### ISSUE TITLE
Use mixin data to initialize component data

### ISSUE THREAD

**Issue by julaudo** [vuejs/vue#9744]
### Version
2.6.10

### Reproduction link
[https://codepen.io/anon/pen/PLdmWE](https://codepen.io/anon/pen/PLdmWE)

### Steps to reproduce
Run the codepen and look at the output

### What is expected?
Mixin property (init): Mixin property
Mixin property (created): Mixin property

### What is actually happening?
Mixin property (init):
Mixin property (created): Mixin property

**Comment by posva** [comment]
I don't think it is a good idea to initialize data from the data of another mixin, it will make order matter and ideally, every mixin is an encapsulated behavior box. Creating implicit necessary order between mixins (or components) would allow the creation of difficult to maintain mixins.
In this case, setting the data in the created hook already works and makes more sense since it doesn't depend on the order of mixins
