### ISSUE TITLE
v-html not working for slot

### ISSUE THREAD

**Issue by bbugh** [vuejs/vue#9769]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/mo476zhg/](https://jsfiddle.net/mo476zhg/)

### Steps to reproduce
1. Create a component with a `slot`.
2. Use `v-html` on the slot to provide default content
3. Attempt to use component without providing slot content
4. Observe that `v-html` is ignored on the slot

### What is expected?
`v-html` should output to the `slot` when no default slot value is provided

### What is actually happening?
v-html is ignored and the slot is empty

**Comment by posva** [comment]
Don't open issues providing fake repros

v-html changes the element innerHTML property, so it won't work on a slot

**Comment by bbugh** [comment]
Sorry, what? I don't know what you mean about fake repros. I provided a jsfiddle demonstrating the issue, and outlined the clear steps to reproduce the issue.

Can you tell me what I needed to do differently? I definitely don't want to create more work for you guys, I'm sure it's hard enough to run an open source project.

Can we discuss adding something to the documentation about `v-html` not working on slots if this is working as intended? Or perhaps a warning? 

It was very confusing and seems like a bug.

**Comment by posva** [comment]
When providing a repro it should contain the necessary code to showcase the problem, so you should have added the component with a slot and the v-html directive. To me, it looked like you took a jsfiddle, forked it and pasted the link, that's why I said fake repro.

Feel free to open an issue or PR in the vuejs docs repo (vuejs/vuejs.org) if there isn't one already 🙂 

BTW, using v-html to set the content of the slot looks like a bad idea for the security reasons outlined in the docs

**Comment by bbugh** [comment]
OH NO, that jsfiddle link is definitely not the one I meant to post. I'm so sorry about that, I apologize for  wasting your time! I'll make sure that the link actually works next time I post it in a bug. Thank you for the tip about the docs repo, I will do that. 

Thanks for all of your hard work maing Vue awesome!

**Comment by Balaji1202** [comment]
Yes, as @posva pointed out, v-html behaves as javascript's innerHTML, it replaces the complete content of your component, instead of the slot alone. Instead, send the content as a string prop to your child element and use it wherever in your child element container as a v-html directive. Hope it helps.
