### ISSUE TITLE
The $refs maybe undefined

### ISSUE THREAD

**Issue by underfin** [vuejs/vue#9856]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/3q34mqqwxm](https://codesandbox.io/embed/3q34mqqwxm)

### Steps to reproduce
1. In the template not ref use.
2. In the ts use `readonly $refs!: { div: Element };`
3. In the runtime `this.div.xx` will throw error.

### What is expected?
Throw error in compiler-time.

### What is actually happening?
Throw error in runtime.

---
we can use `readonly $refs!: { div: Element | undefined };` and  `this.div!.xx` .

**Comment by HyunmoAhn** [comment]
I have same Issue.

### Version
2.6.3


### Description 

Sometimes, when some of each refresh page, mounted lifecycle of component can't get this.$ref because it is before render.

I know mounted doesn't guarantee completed about render. 
But It is caused child component but I am not associate with child component.

And, It is occurred randomly!

### Example Code
```
// template
<template>
  <div class="asset_box" ref="assetBox">
    <span class="amount" ref="amount">
      amount
    </span>
    <div class="gauge_box">
      <span class="blind">asset gauge</span>
      <div class="gauge" ref="gauge"></div>
    </div>
   ... ellipsis
    <error-one-coin v-if="isShowError"></error-one-coin> // child component but doesn't associate with $ref
  </div>
</template>

// mounted
mounted () {
    console.log(this.$refs, document.querySelector('.asset_box'), document.querySelector('.amount'), 
},
```

### Analysis
I got braking point on mounted code like below capture.
![image](https://user-images.githubusercontent.com/23732795/56005693-b1790580-5d0c-11e9-9c2e-8f2957a63c4c.png)

#### normal case.
![image](https://user-images.githubusercontent.com/23732795/56005720-d40b1e80-5d0c-11e9-9c5d-36840872e443.png)
- console of chrome browser on breakpoint
![image](https://user-images.githubusercontent.com/23732795/56005726-d9686900-5d0c-11e9-91d9-0165f1285aa9.png)

`.asset_box` is target component that has `mounted` lifecycle.

#### error case
![image](https://user-images.githubusercontent.com/23732795/56005749-f735ce00-5d0c-11e9-8d6d-34cbdb6330c0.png)
- console of chrome browser on breakpoint
![image](https://user-images.githubusercontent.com/23732795/56005755-00269f80-5d0d-11e9-8138-7568ae85c6d3.png)

The location that `.asset_box` has `comment` like `<!---->`

If you need more information, I comment more.

Please Tell whether it is bug or not.
Thank you.

**Comment by underfin** [comment]
@HyunmoAhn . Can you provider all code in your case? My problem is related with `$refs` type defined.

**Comment by LinusBorg** [comment]
@underfin I fail to see what you think wrong about the behaviour you are showing. There's no element to reference, so $refs is empty.

It seems you think you should be able to overwrite $refs with a permanent value. That's not the case. $refs is created dynamically during runtime, and will always only contain the refs that are currently found in the document.

@HyunmoAhn Your problem seems unrelated. The `<!-- -->` comment in the page's markup indicates that you have a render error, which is why there's no ref: Because of the render error, no element was created, so there's no element for the ref to reference.

**Comment by underfin** [comment]
@LinusBorg , my case only its `$refs` maybe undefined. Now, I change my code in https://codesandbox.io/embed/3q34mqqwxm. As you say，`$refs` is created dynamically during runtime, the same maybe removed during runtime.So, I think its type should include `undefined`.
Also,  its path `src/core/vdom/modules/ref.js` with code, `refs[key] = undefined`.
`export function registerRef (vnode: VNodeWithData, isRemoval: ?boolean) {
  const key = vnode.data.ref
  if (!isDef(key)) return

  const vm = vnode.context
  const ref = vnode.componentInstance || vnode.elm
  const refs = vm.$refs
  if (isRemoval) {
    if (Array.isArray(refs[key])) {
      remove(refs[key], ref)
    } else if (refs[key] === ref) {
      refs[key] = undefined
    }
  } else {
    if (vnode.data.refInFor) {
      if (!Array.isArray(refs[key])) {
        refs[key] = [ref]
      } else if (refs[key].indexOf(ref) < 0) {
        // $flow-disable-line
        refs[key].push(ref)
      }
    } else {
      refs[key] = ref
    }
  }
}`

**Comment by LinusBorg** [comment]
$refs is never undefined. It's always an object. It just may be an empty object sometimes, but the types already deflect that.

**Comment by underfin** [comment]
@LinusBorg, yea, its right, I misstated it with `this.$refs.div` to `this,$refs`.Can you reopen the issuse with rename, I want to request pr to fix it.

**Comment by LinusBorg** [comment]
I still don't understand what you want to fix, though.

**Comment by underfin** [comment]
@LinusBorg . `readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] };` `$refs` is defined on now. The type with `$refs` should defined `readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] | undefined };`.

**Comment by pikax** [comment]
From what I understand the OP is referring to typescript only, because the type doesn't get automatically picked up by the compiler when he does 
```typescript
console.log(this.$refs.div.nodeType); // compiler can't resolve the correct type and `nodeType` show an error
```

Is not vuejs fault, you need to cast your element to the type you want to infer to typescript
```typescript
console.log((this.$refs.div as Element).nodeType);
```

I recommend you check [Type Guards and Differentiating Types](http://www.typescriptlang.org/docs/handbook/advanced-types.html)


It might be useful to add the `undefined` to `Vue.$refs` interface
```typescript
 readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] | undefined };
```

In regards to runtime error, you should always check if the ref is not undefined and if is an instance or an array.

**Comment by Hammster** [comment]
> It might be useful to add the `undefined` to `Vue.$refs` interface
> 
> ```ts
>  readonly $refs: { [key: string]: Vue | Element | Vue[] | Element[] | undefined };
> ```

I just stumbled on this, `undefined` should always be given for index signatures due to the nature of `prop['propName']` currently I can only add `// @ts-ignore` above the affected lines. to get the result I want.

![Code_piVUr37ibA](https://user-images.githubusercontent.com/1093709/61534568-412b0000-aa30-11e9-9cbb-5a6579fe8901.png)

**Comment by Akimyou** [comment]
In my case.

```Vue
<template>
<div>
    ...
    <application-gateway
      v-if="data && vccCredit"
      :flowData="data"
      :vccCredit="vccCredit"
      :vccPartners="vccPartners"
      ref="applicationGateway"
    >
    </application-gateway>
    ...
</div>
</template>

<script>
  async applyNowHandler() {
    const applicationGateway = this.$refs.applicationGateway as any
    // prevent amazing Cannot read property 'start' of undefined
    this.$nextTick(() => {
      applicationGateway.start()
    })
  }
</script>
```

I promise add loading when fetching `data` and `vccCredit`. And add the `$nextTick`.

But `applicationGateway` ref still  be undefined in some case.

![image](https://user-images.githubusercontent.com/14974790/64311045-2e1ac200-cfd5-11e9-928d-58d0279b2274.png)

I don't know why?

May be we need change the $ref define in types/vue.d.ts.

https://cn.vuejs.org/v2/api/#ref

@underfin ,  support you.

**Comment by juliussa** [comment]
> In my case.
> 
> ```
> <template>
> <div>
>     ...
>     <application-gateway
>       v-if="data && vccCredit"
>       :flowData="data"
>       :vccCredit="vccCredit"
>       :vccPartners="vccPartners"
>       ref="applicationGateway"
>     >
>     </application-gateway>
>     ...
> </div>
> </template>
> 
> <script>
>   async applyNowHandler() {
>     const applicationGateway = this.$refs.applicationGateway as any
>     // prevent amazing Cannot read property 'start' of undefined
>     this.$nextTick(() => {
>       applicationGateway.start()
>     })
>   }
> </script>
> ```
> 
> I promise add loading when fetching `data` and `vccCredit`. And add the `$nextTick`.
> 
> But `applicationGateway` ref still be undefined in some case.
> 
> ![image](https://user-images.githubusercontent.com/14974790/64311045-2e1ac200-cfd5-11e9-928d-58d0279b2274.png)
> 
> I don't know why?
> 
> May be we need change the $ref define in types/vue.d.ts.
> 
> https://cn.vuejs.org/v2/api/#ref
> 
> @underfin , support you.

Do you try to use v-show instead v-if?

**Comment by Akimyou** [comment]
I try to do not use `v-if` and `ref` together then make sure `$ref` target is available at first.
@juliussa , Thanks.
