### ISSUE TITLE
Is that possible to get current element ref inside v-bind

### ISSUE THREAD

**Issue by CGQAQ** [vuejs/vue#9881]
### What problem does this feature solve?
Use itself attrs or something as its binding source

### What does the proposed API look like?
:attr="self.attr" or something like this

**Comment by posva** [comment]
no, unless you setup an explicit ref but it will be better to pass a method that is lazily called so the ref is actually valid as refs are computed once the component renders

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
