### ISSUE TITLE
Mouseleave is not fired when v-for list updated

### ISSUE THREAD

**Issue by h0rn3z0r** [vuejs/vue#9897]
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/p5goevhL](https://jsfiddle.net/p5goevhL)

### Steps to reproduce
* Hover second element
* Hold your cursor for 1 second

### What is expected?
When first element is removed, second should fire mouseleave event and delete itself from hovered array

### What is actually happening?
Second element's mouseleave event is not triggered

---
This bug only happens when new items array length is equal or greater than the old one. In my demo there is a "working" button to test that.

**Comment by posva** [comment]
hey, thanks for the demo but it seems to be working fine.

I change the element being hovered to the first one to see the array grow (I think that's what you meant) but if the element gets removed it never gets to trigger the mouseleave event

When dealing with events, remember Vue only add event listeners, it's very close to vanilla js. You may be encountering a problem that is related to how things work in the browser

**Comment by h0rn3z0r** [comment]
@posva, thank you for your time!
> if the element gets removed it never gets to trigger the mouseleave event

I am absolutely agree with that, but could you clarify a little bit more what is going on behind the scenes when [1,2,3] array is replaced by [2,3,4] or at least point to related docs section? Because that is Vue-specific part. As I supposed, the 2nd element is not destroyed but simply is moved to the left after 1nd element destroying, preserving all listeners, because elements are keyed, thus mouseleave should be triggered (tested in plain JS). Am I wrong?
Why this is working for [1,2,3] -> [2,3] and fail for [1,2,3] -> [2,3,4] or [1,2,3] -> [2,3,4,5]?

**Comment by posva** [comment]
> Why this is working for [1,2,3] -> [2,3] and fail for [1,2,3] -> [2,3,4] or [1,2,3] -> [2,3,4,5]?

but in you jsfiddle both are working. The first element is always the one being destroyed because you keyed the elements (which is good). If you need help, please use the appropriate channels like the forum and the chat

**Comment by h0rn3z0r** [comment]
@posva I just realized now that my demo works on Chromium browser and does not work on Firefox which I am using. That is why we had a little misunderstanding.
Is it something that Vue completely cannot deal with?

**Comment by posva** [comment]
I see
I gave it another look, and what happens is that the first scenario works because we are removing an element before the one we highlight, so the second element is never removed from the dom, only the first one and the second effectively moves. On the second scenario though, elements are removed and added once again: Vue patching mechanism is different regarding what elements are being modified. There is an open issue about it but I'm struggling to find it.

The thing is, mouseleave doesn't seem to trigger after removal on Chrome either. So the fact it works in chrome is just a coincidence maybe related to how chrome deals with dom insertions. My point is that the approach you are taking is the one causing the problem. Maybe listening to mouseleave isn't enough, you also need to listen for element removal
