### ISSUE TITLE
websocket errors being thrown in browser when using default vue cli 3 install

### ISSUE THREAD

**Issue by wgrs** [vuejs/vue#9900]
### Version
2.6.10

### Reproduction link
[https://codepen.io/wgrs/pen/wZmjyK?editors=1111](https://codepen.io/wgrs/pen/wZmjyK?editors=1111)

### Steps to reproduce
Browser errors wont show in the minimal repro so that is pointless.

### What is expected?
to be able to create a starter app that does not throw console errors.

### What is actually happening?
On create a new vue app and selecting all the defaults, and app is created but the browser is inundated with websocket errors.

---
I don't think this is a vue issue, but more a webpack dev server issue.. however I have no idea - all I know is that I cant get a clear default install running. I am using vue 3.5.5 but the version box wont take that version.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This is a help request related to your environment, so I'm closing it

**Comment by wgrs** [comment]
Ok - tried discord with zero help - tried stack overflow as well.  Maybe time to try a different framework.

**Comment by wgrs** [comment]
So not being able to get a default install running is not a bug????

**Comment by yyx990803** [comment]
@wgrs 

First of all, your issue pertains to [vue-cli](https://github.com/vuejs/vue-cli) and this is the wrong repo.

Second, when you report an issue to vue-cli, you will see that we require information on your OS, Node version, package manager version etc., because all of them may be related to the problem you are seeing.

You seem to think if it's not working for you it must be not working for anyone, but that's not the case. A default installation works perfectly fine for all our team members. Mind you, there are close to 2 million downloads of `@vue/cli-service` each week - if it is broken for everyone we would have hundreds of issues complaining about the same thing, but that's not the case, so obviously it is related to something about your system, most likely related to network setup. If you really think this is a bug, you need to provide enough information so that we can at least try to reproduce it, instead of filing entitled complaints, harassing team members with private messages.

You are more than welcome to use a different framework. But if you don't learn to interact with open source maintainers in a more constructive manner you won't get far with anything.
