### ISSUE TITLE
DOM Lag while inputing (over 80 or 100  component in one template and every component has a watcher )

### ISSUE THREAD

**Issue by Jochii12** [vuejs/vue#9956]
### Version
2.6.10

### Reproduction link
[https://codepen.io/LeoKi12/pen/jRoWwE](https://codepen.io/LeoKi12/pen/jRoWwE)

### Steps to reproduce
how do i fix the issue about dom laggin . 

### What is expected?
smoothing inputing

### What is actually happening?
I have a problem for this every time i input, checking box, or selecting radio. the dom is lagging or delay response.

every component has this kind of code.

```
<template>
    <div>
       ..some temp ex. over 50 to 70+ input with radio and checkbox
       <input v-model="someData.name"/>
    </div>
</template>

<script>
import { mapActions } from "vuex"
export default ({
  data: () => ({
       someData: {}
  }),
  watch:{
      someData:{
        handler(obj){
         this.putDataToVuex({ someData: obj })  
       }
     }
  },
  methods:{
     ...mapActions(`vuexname`,["putDataToVuex"])
  }
})
</script>
```
thanks.

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
