### ISSUE TITLE
IE   文本框输入后ESC 回退 并没有触发双向绑定 

### ISSUE THREAD

**Issue by BivoZeou** [vuejs/vue#9991]
### Version
2.6.10

### Reproduction link
[https://jsbin.com/burakafati/edit?html,output](https://jsbin.com/burakafati/edit?html,output)

### Steps to reproduce
1.打开IE 11
2.选中一个已经绑定好数据的 文本框  
3.然后 输入字符
4.ESC 回退到输入之前的状态  

### What is expected?
ESC回退后 触发双向绑定

### What is actually happening?
没有触发双向绑定, model里的值没有变化,只有界面上回退了

**Comment by posva** [comment]
Your repro doesn't even run...
If it rolls back, you probably have something handling that.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
