### ISSUE TITLE
Reactivity breaks math.gl vector prototype methods

### ISSUE THREAD

**Issue by davidmanzanares** [vuejs/vue#9997]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/s/o1l2jk2j05?fontsize=14](https://codesandbox.io/s/o1l2jk2j05?fontsize=14)

### Steps to reproduce
1. Go to https://codesandbox.io/s/o1l2jk2j05?fontsize=14
2. Press the button
3. You'll see and error that shouldn't have happened (the logs will show that the Vector3 instance doesn't have an 'add' method anymore. Even though new instances of Vector3 have them.

### What is expected?
VueJS reactivity should be transparent

### What is actually happening?
VueJS reactivity is not transparent, since it hides/removes methods of instances of classes of math.gl

---
I don't know if this is documented behavior, but I didn't see it here: https://vuejs.org/v2/guide/reactivity.html

**Comment by posva** [comment]
you cannot use an arrow function for data

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by davidmanzanares** [comment]
The problem happens if you use a regular function too: https://codesandbox.io/s/1zqwqmk2nj

The original issue happened without using a component with a plain object assigned to `data`.

I suspect that this issue happens due to the way math.gl builds Vector3 like an array.

I'm new to Vue, but I still think this is a bug.

**Comment by Justineo** [comment]
Vue is currently hijacking the `__proto__` of `Array` instances to the patched version: https://github.com/vuejs/vue/blob/1137e415c9e8701d1b0a25e5812f8c4dffeeeaaa/src/core/observer/index.js#L87-L91

So Vue's reactivity system can only work reliably with native `Array`s. MATH.GL's `Vector3` extends the native `Array` with custom methods so even Vue keeps those methods (eg. `target.__proto__ = Object.create(target.__proto__, src)`), the reactivity system won't work because Vue cannot patch those methods it's not aware of.
