### ISSUE TITLE
Mutating object's property of props does not warn anything

### ISSUE THREAD

**Issue by ashnamuh** [vuejs/vue#9998]
### Version
2.6.10

### Reproduction link
[https://codesandbox.io/embed/389331xv4p](https://codesandbox.io/embed/389331xv4p)

### Steps to reproduce
1. type whatevet in text and text2 form
2. check it console

### What is expected?
I expect that MyInput2 also warn "Avoid mutating a prop directly..." error. 

### What is actually happening?
Warn anything

---
I have no idea why It don't warn anything if add or mutate object's property  in props. Yes, i should use `emit` to mutate props' data. But i want to understand why it happen. If this is a bug of Vue, i hope it will be fixed later.

**Comment by yyx990803** [comment]
This has been explicitly mentioned in the docs:

> Note that objects and arrays in JavaScript are passed by reference, so if the prop is an array or object, mutating the object or array itself inside the child component will affect parent state.

In Vue 2 there is currently no (performant enough) way to detect **nested** mutations. In Vue 3 however, this will indeed trigger warnings.

**Comment by bilouw** [comment]
I searched hours on the internet about this question. First i thought that it was clearly forbidden to mutate props. Then i noticed myself that mutate an object doesn't trigger warnings. But i knew i read somewhere that is was because Vue doesn't detect nested mutations.

I see the documentation said that changing an object in child will reflect changes in parent but in red alert like "don't do this". But it's clearly seems the simplest things to do. And if i take the official documentation, it said that we should make a copy in data or computed. But it's the same things that mutating props !! (because reference, it's just that Vue doesn't detect it so no warnings).

So how should we make to avoid mutating props for REAL, and why is this a problem for reference types ? It seems to be a real problem because Evan You said that in vue 3 warnings will be trigger even on nested structure, but i don't see why because, parent is updated so the data stay sync.

Should we juste pass one level nested object to component ? Should we make deep copy every times ?

Why the documentation is so ambigious about that ?

I think the whole internet need this clarification (or is it just me :p ?),
Thanks.
